Repository WalletWasabi/WalletWasabi, pull requests merged in 2019-10, with the labels that each got.

#2391 Simplify default expression
  WalletWasabi/Services/TransactionProcessor.cs
  WalletWasabi/Services/WalletService.cs
Labels: refactoring

#2390 Add rules to prefer simple using statement & compound assignment
  .editorconfig
  WalletWasabi.Tests/IntegrationTests/RegTests.cs
Labels: refactoring

#2387 Fix formatting
  WalletWasabi.Tests/UnitTests/AsyncMutexTests.cs
Labels: refactoring

#2385 Correct indentation
  WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/PinPadViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoViewModel.cs
  WalletWasabi.Gui/Dialogs/TextInputDialogViewModel.cs
  WalletWasabi.Gui/ManagedDialogs/ManagedFileChooserViewModel.cs
  WalletWasabi.Gui/Shell/Commands/HelpCommands.cs
  WalletWasabi.Gui/Shell/Commands/ToolCommands.cs
  WalletWasabi.Gui/Tabs/SettingsViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/RecoverWalletViewModel.cs
  WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
  WalletWasabi/Nito/AsyncEx/AsyncWaitQueueExtensions.cs
  WalletWasabi/Services/WalletService.cs
Labels: refactoring

#2395 Clear warning message before search hw.
  WalletWasabi.Gui/Tabs/WalletManager/LoadWalletViewModel.cs
Labels: UX

#2351 Add canonical to website
  WalletWasabi.Backend/wwwroot/index.html
Labels: feature/enhancement

#2467 Improve transaction privacy by taking clusters info into account
  WalletWasabi.Gui/Controls/WalletExplorer/CoinViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
  WalletWasabi.Gui/ViewModels/AddressViewModel.cs
  WalletWasabi.Tests/IntegrationTests/RegTests.cs
  WalletWasabi.Tests/UnitTests/KeyManagementTests.cs
  WalletWasabi.Tests/UnitTests/LinqExtensionsTests.cs
  WalletWasabi.Tests/UnitTests/SmartCoinTests.cs
  WalletWasabi.Tests/UnitTests/SmartLabelTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/AllTransactionStoreTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/SmartTransactionTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionStoreTests.cs
  WalletWasabi/BlockchainAnalysis/Cluster.cs
  WalletWasabi/BlockchainAnalysis/SmartLabel.cs
  WalletWasabi/Coins/SmartCoin.cs
  WalletWasabi/Extensions/LinqExtensions.cs
  WalletWasabi/JsonConverters/SmartLabelJsonConverter.cs
  WalletWasabi/Transactions/TransactionBuilding/SmartCoinSelector.cs
  WalletWasabi/Transactions/TransactionHistoryBuilder.cs
Labels: feature/enhancement
