Repository WalletWasabi/WalletWasabi, pull requests merged in 2019-07, with the labels that each got.

#1994 Potential spent coins issue fix
  WalletWasabi/Services/WalletService.cs
Labels: debug, priority

#1949 Bitcoin URL support
  WalletWasabi.Gui/Behaviors/PasteAddressOnClickBehavior.cs
  WalletWasabi.Gui/Controls/ExtendedTextBox.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendTabView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
  WalletWasabi.Tests/ParserTests.cs
  WalletWasabi/Helpers/AddressStringParser.cs
Labels: feature/enhancement

#1993 Managed Open File/Folder Dialog compatible with all Linux Distros
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionViewerViewModel.cs
  WalletWasabi.Gui/Converters/FileSizeStringConverter.cs
  WalletWasabi.Gui/Helpers/ByteSizeHelper.cs
  WalletWasabi.Gui/ManagedDialogs/ChildFitter.cs
  WalletWasabi.Gui/ManagedDialogs/ManagedFileChooser.xaml
  WalletWasabi.Gui/ManagedDialogs/ManagedFileChooser.xaml.cs
  WalletWasabi.Gui/ManagedDialogs/ManagedFileChooserFilterViewModel.cs
  WalletWasabi.Gui/ManagedDialogs/ManagedFileChooserItemViewModel.cs
  WalletWasabi.Gui/ManagedDialogs/ManagedFileChooserNavigationItem.cs
  WalletWasabi.Gui/ManagedDialogs/ManagedFileChooserSources.cs
  WalletWasabi.Gui/ManagedDialogs/ManagedFileChooserViewModel.cs
  WalletWasabi.Gui/ManagedDialogs/ManagedFileDialog.xaml
  WalletWasabi.Gui/ManagedDialogs/ManagedFileDialog.xaml.cs
  WalletWasabi.Gui/ManagedDialogs/ManagedFileDialogExtensions.cs
  WalletWasabi.Gui/ManagedDialogs/ResourceSelectorConverter.cs
  WalletWasabi.Gui/Program.cs
  WalletWasabi.Gui/Tabs/WalletManager/LoadWalletViewModel.cs
Labels: UX, feature/enhancement

#1951 Correct typos
  WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
  WalletWasabi.Gui/CommandLine/PasswordFinderCommand.cs
  WalletWasabi.Gui/Controls/WalletExplorer/CoinListView.xaml
  WalletWasabi.Packager/Program.cs
  WalletWasabi.Tests/RegTests.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/DataEncodation/EncoderBase.cs
  WalletWasabi/Models/ChaumianCoinJoin/CcjRound.cs
  WalletWasabi/Models/Height.cs
  WalletWasabi/Services/WalletService.cs
  WalletWasabi/TorSocks5/Models/Fields/ByteArrayFields/AddrField.cs
Labels: documentation/support, solution is not controversial
