Repository WalletWasabi/WalletWasabi, pull requests merged in 2019-09, with the labels that each got.

#2211 Add optional settings
  WalletWasabi.Documentation/BackendDeployment.md
Labels: documentation/support

#2218 Simplify member access
  WalletWasabi.Backend/Controllers/BatchController.cs
  WalletWasabi.Backend/Controllers/OffchainController.cs
  WalletWasabi.Backend/Controllers/SoftwareController.cs
  WalletWasabi.Gui/Tabs/AboutViewModel.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/InputOutOfBoundaryException.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/Masking/Scoring/Penalty4.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/Versions/ErrorCorrectionBlocks.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/Versions/QRCodeVersion.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/Versions/VersionTable.cs
  WalletWasabi/Helpers/AddressStringParser.cs
  WalletWasabi/Nito/AsyncEx/AsyncLock.cs
  WalletWasabi/Nito/Collections/Deque.cs
  WalletWasabi/TorSocks5/TorHttpClient.cs
  WalletWasabi/WebClients/Wasabi/WasabiClient.cs
Labels: refactoring

#2215 Fix typo and some editing
  WalletWasabi.Tests/README.md
  WalletWasabi.Tests/UnitTests/SmartCoinTests.cs
Labels: refactoring

#2187 Remove Chinese character masking from PasswordBox
  WalletWasabi.Gui/App.xaml
  WalletWasabi.Gui/CommandLine/Daemon.cs
  WalletWasabi.Gui/Controls/LockScreen/PinLockScreen.xaml
  WalletWasabi.Gui/Controls/LockScreen/PinLockScreen.xaml.cs
  WalletWasabi.Gui/Controls/NoparaPasswordBox.cs
  WalletWasabi.Gui/Controls/NoparaPasswordBox.xaml
  WalletWasabi.Gui/Controls/TogglePasswordBox.cs
  WalletWasabi.Gui/Controls/TogglePasswordBox.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/PinPadView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/SendTabView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoViewModel.cs
  WalletWasabi.Gui/Tabs/SettingsView.xaml
  WalletWasabi.Gui/Tabs/WalletManager/GenerateWalletView.xaml
  WalletWasabi.Gui/Tabs/WalletManager/GenerateWalletViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/LoadWalletView.xaml
  WalletWasabi.Gui/Tabs/WalletManager/LoadWalletViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/RecoverWalletView.xaml
  WalletWasabi.Gui/Tabs/WalletManager/RecoverWalletViewModel.cs
  WalletWasabi.Tests/UnitTests/PasswordTests.cs
  WalletWasabi/Helpers/PasswordHelper.cs
Labels: UX, refactoring

#2219 Fix name violation
  WalletWasabi.Gui/ManagedDialogs/ManagedFileDialogExtensions.cs
  WalletWasabi.Packager/NSubsys/PeUtility.cs
  WalletWasabi/Exceptions/TorSocks5FailureResponseException.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/Masking/Scoring/Penalty4.cs
  WalletWasabi/Stores/HashChain.cs
Labels: refactoring

#2223 Validations system refactor.
  WalletWasabi.Gui/Controls/MultiTextBox.xaml
  WalletWasabi.Gui/Controls/TogglePasswordBox.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoViewModel.cs
  WalletWasabi.Gui/Converters/ErrorDescriptorToBorderColorConverter.cs
  WalletWasabi.Gui/Converters/ErrorDescriptorsJsonConverter.cs
  WalletWasabi.Gui/Converters/ErrorSeverityColorConverter.cs
  WalletWasabi.Gui/Styles/Styles.xaml
  WalletWasabi.Gui/Tabs/SettingsViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/GenerateWalletViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/LoadWalletViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/RecoverWalletViewModel.cs
  WalletWasabi.Gui/ViewModels/Validation/ReflectionHelper.cs
  WalletWasabi.Gui/ViewModels/Validation/Validator.cs
  WalletWasabi.Gui/ViewModels/ViewModelBase.cs
  WalletWasabi.Tests/UnitTests/ValidateMethodTests.cs
  WalletWasabi.Tests/WalletWasabi.Tests.csproj
  WalletWasabi/Helpers/PasswordHelper.cs
  WalletWasabi/Models/ErrorDescriptor.cs
  WalletWasabi/Models/ErrorDescriptors.cs
  WalletWasabi/Models/ErrorSeverity.cs
Labels: UX, priority

#2214 Nitpicking
  WalletWasabi.Documentation/BackendDeployment.md
Labels: refactoring

#2288 Refactoring
  WalletWasabi/JsonConverters/DateTimeOffsetUnixSecondsConverter.cs
Labels: refactoring

#2249 Stylistic changes
  WalletWasabi.Gui/Behaviors/BindSelectedTextBehavior.cs
  WalletWasabi.Gui/Behaviors/ClearPropertyOnLostFocusBehavior.cs
  WalletWasabi.Gui/Behaviors/CommandOnFirstVisible.cs
  WalletWasabi.Gui/Behaviors/FocusBehavior.cs
Labels: refactoring

#2285 Remove osx deadlock possiblity.
  WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
  WalletWasabi.Tests/IntegrationTests/RegTests.cs
  WalletWasabi/Models/UpdateStatusResult.cs
  WalletWasabi/Services/UpdateChecker.cs
  WalletWasabi/WebClients/Wasabi/WasabiClient.cs
Labels: UX, mac os

#2301 Simplify name access
  WalletWasabi.Gui/CommandLine/PasswordFinder.cs
  WalletWasabi.Gui/CommandLine/PasswordFinderCommand.cs
  WalletWasabi.Gui/Controls/ExtendedTextBox.cs
  WalletWasabi.Gui/Controls/MultiTextBox.cs
  WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionBroadcasterViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionViewerViewModel.cs
  WalletWasabi.Gui/Dialogs/AvaloniaControlsExtensions.cs
  WalletWasabi.Gui/Dialogs/CannotCloseDialogViewModel.cs
  WalletWasabi.Gui/Dialogs/TextInputDialogViewModel.cs
  WalletWasabi.Gui/Helpers/AvaloniaThreadingExtensions.cs
  WalletWasabi.Gui/MainWindow.xaml.cs
  WalletWasabi.Gui/Shell/Commands/DiskCommands.cs
  WalletWasabi.Gui/Shell/Commands/HelpCommands.cs
  WalletWasabi.Gui/Shell/Commands/SystemCommands.cs
  WalletWasabi.Gui/Shell/Commands/ToolCommands.cs
  WalletWasabi.Gui/Tabs/AboutViewModel.cs
  WalletWasabi.Gui/ViewModels/AddressViewModel.cs
  WalletWasabi.Gui/ViewModels/MainWindowViewModel.cs
  WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
Labels: refactoring

#2307 Fix formatting
  WalletWasabi.Gui/Controls/EditableTextBlock.cs
  WalletWasabi.Gui/Controls/LockScreen/PinLockScreen.xaml.cs
  WalletWasabi.Gui/Controls/LockScreen/SlideLockScreen.xaml.cs
  WalletWasabi.Gui/Controls/MultiTextBox.cs
  WalletWasabi.Gui/Controls/QrCode.cs
  WalletWasabi.Gui/Controls/SortingArrow.cs
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionViewModel.cs
  WalletWasabi.Gui/ViewModels/AddressViewModel.cs
  WalletWasabi/Logging/Logger.cs
  WalletWasabi/Models/ErrorDescriptors.cs
  WalletWasabi/Services/UpdateChecker.cs
  WalletWasabi/Services/WalletService.cs
  WalletWasabi/Services/WasabiSynchronizer.cs
  WalletWasabi/Stores/IndexStore.cs
  WalletWasabi/TorSocks5/TorProcessManager.cs
  WalletWasabi/TorSocks5/TorSocks5Client.cs
  WalletWasabi/WebClients/Wasabi/ChaumianCoinJoin/AliceClient.cs
Labels: refactoring

#2291 Correct TypeArgumentException's namespace
  WalletWasabi.Gui/Converters/AmountForegroundConverter.cs
  WalletWasabi.Gui/Converters/BooleanStringConverter.cs
  WalletWasabi.Gui/Converters/CoinItemExpanderColorConverter.cs
  WalletWasabi.Gui/Converters/CoinJoinedVisibilityConverter.cs
  WalletWasabi.Gui/Converters/CoinStatusBorderBrushConverter.cs
  WalletWasabi.Gui/Converters/CoinStatusColorConverter.cs
  WalletWasabi.Gui/Converters/CoinStatusForegroundConverter.cs
  WalletWasabi.Gui/Converters/CoinStatusStringConverter.cs
  WalletWasabi.Gui/Converters/FeeTargetTimeConverter.cs
  WalletWasabi.Gui/Converters/FilterLeftStatusConverter.cs
  WalletWasabi.Gui/Converters/InverseBooleanConverter.cs
  WalletWasabi.Gui/Converters/MoneyBrushConverter.cs
  WalletWasabi.Gui/Converters/MoneyStringConverter.cs
  WalletWasabi.Gui/Converters/NetworkStringConverter.cs
  WalletWasabi.Gui/Converters/PhaseStringConverter.cs
  WalletWasabi.Gui/Converters/PrivacyLevelValueConverter.cs
  WalletWasabi.Gui/Converters/StatusBarStatusStringConverter.cs
  WalletWasabi.Gui/Converters/TimeSpanStringConverter.cs
  WalletWasabi.Gui/Converters/TimeSpanVisibilityConverter.cs
  WalletWasabi.Gui/Converters/UsdExchangeRateAmountToolTipConverter.cs
  WalletWasabi/Exceptions/TypeArgumentException.cs
Labels: refactoring

#2286 Use the same messages
  WalletWasabi.Backend/Config.cs
  WalletWasabi.Gui/Config.cs
  WalletWasabi.Tests/IntegrationTests/P2pTests.cs
  WalletWasabi/Exceptions/NotSupportedNetworkException.cs
  WalletWasabi/Helpers/Constants.cs
  WalletWasabi/Helpers/PasswordHelper.cs
  WalletWasabi/Stores/StartingFilters.cs
  WalletWasabi/WebClients/BlockCypher/BlockCypherClient.cs
  WalletWasabi/WebClients/SmartBit/SmartBitClient.cs
Labels: refactoring

#2287 Fix typos
  WalletWasabi.Gui/Tabs/WalletManager/RecoverWalletView.xaml
  WalletWasabi.Packager/Program.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/Masking/Scoring/PenaltyFactory.cs
  WalletWasabi/Helpers/PasswordHelper.cs
  WalletWasabi/Models/Height.cs
  WalletWasabi/Services/WalletService.cs
Labels: refactoring

#2341 Add rule to use expression body for lambdas
  .editorconfig
  WalletWasabi.Backend/Startup.cs
  WalletWasabi.Gui/Behaviors/CommandOnClickBehavior.cs
  WalletWasabi.Gui/Behaviors/CommandOnClickReleaseBehavior.cs
  WalletWasabi.Gui/Behaviors/CommandOnDoubleClickBehavior.cs
  WalletWasabi.Gui/Behaviors/CommandOnLostFocusBehavior.cs
  WalletWasabi.Gui/Behaviors/FocusBehavior.cs
  WalletWasabi.Gui/Controls/EditableTextBlock.cs
  WalletWasabi.Gui/Controls/ExtendedTextBox.cs
  WalletWasabi.Gui/Controls/LockScreen/SlideLockScreen.xaml.cs
  WalletWasabi.Gui/Controls/MultiTextBox.cs
  WalletWasabi.Gui/Controls/SortingArrow.cs
  WalletWasabi.Gui/Controls/TogglePasswordBox.cs
  WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/CoinViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/PinPadViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionBroadcasterViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletAdvancedViewModel.cs
  WalletWasabi.Gui/Dialogs/GenSocksServFailDialogViewModel.cs
  WalletWasabi.Gui/Dialogs/TextInputDialogViewModel.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Gui/Helpers/ShellUtils.cs
  WalletWasabi.Gui/Shell/Commands/HelpCommands.cs
  WalletWasabi.Gui/Shell/Commands/ToolCommands.cs
  WalletWasabi.Gui/Tabs/WalletManager/LoadWalletViewModel.cs
  WalletWasabi.Gui/ViewModels/MainWindowViewModel.cs
  WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
  WalletWasabi.Tests/UnitTests/AsyncMutexTests.cs
  WalletWasabi.Tests/UnitTests/HashChainTests.cs
  WalletWasabi/Extensions/TextReaderExtensions.cs
Labels: refactoring

#2360 Correct indentation
  WalletWasabi.Gui/Behaviors/ClearPropertyOnLostFocusBehavior.cs
  WalletWasabi.Gui/Behaviors/CommandOnEnterBehavior.cs
  WalletWasabi.Gui/Behaviors/CommandOnFirstVisible.cs
  WalletWasabi.Gui/Behaviors/CommandOnKeyDownBehavior.cs
  WalletWasabi.Gui/Behaviors/CommandOnKeyUpBehavior.cs
  WalletWasabi.Gui/Behaviors/CommandOnPointerEnterLeaveBehavior.cs
  WalletWasabi.Gui/Behaviors/GreyOutOnDisabledBehavior.cs
  WalletWasabi.Gui/Behaviors/PasteAddressOnClickBehavior.cs
  WalletWasabi.Gui/Behaviors/SuggestionBehavior.cs
  WalletWasabi.Gui/Controls/EditableTextBlock.cs
  WalletWasabi.Gui/Controls/ExtendedListBox.cs
  WalletWasabi.Gui/Controls/ExtendedTextBox.cs
  WalletWasabi.Gui/Controls/MultiTextBox.cs
  WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/WalletManagerViewModel.cs
  WalletWasabi.Gui/ViewModels/AddressViewModel.cs
Labels: refactoring

#2357 Fix formatting
  WalletWasabi.Gui/Behaviors/ClearPropertyOnLostFocusBehavior.cs
  WalletWasabi/KeyManagement/KeyManager.cs
Labels: refactoring

#2364 Put parameters on new line
  WalletWasabi.Gui/Behaviors/CommandOnEnterBehavior.cs
  WalletWasabi.Gui/Behaviors/CommandOnKeyDownBehavior.cs
  WalletWasabi.Gui/Behaviors/CommandOnKeyUpBehavior.cs
  WalletWasabi.Gui/Behaviors/CommandOnPointerEnterLeaveBehavior.cs
  WalletWasabi.Gui/Behaviors/SuggestionBehavior.cs
  WalletWasabi.Gui/Controls/EditableTextBlock.cs
  WalletWasabi.Gui/Controls/ExtendedListBox.cs
  WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionBroadcasterViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionViewerViewModel.cs
  WalletWasabi.Gui/Dialogs/CannotCloseDialogViewModel.cs
  WalletWasabi.Gui/Helpers/AvaloniaThreadingExtensions.cs
  WalletWasabi.Gui/MainWindow.xaml.cs
  WalletWasabi.Gui/Tabs/WalletManager/LoadWalletViewModel.cs
  WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
  WalletWasabi.Tests/IntegrationTests/RegTests.cs
  WalletWasabi/Nito/AsyncEx/AsyncWaitQueueExtensions.cs
  WalletWasabi/Services/WalletService.cs
Labels: refactoring

#2356 Add signature to zkSNACKS PGP
  PGP.txt
Labels: feature/enhancement, solution is not controversial
