Repository WalletWasabi/WalletWasabi, pull requests merged in 2019-08, with the labels that each got.

#2006 Manual tx fee setting
  WalletWasabi.Gui/Behaviors/CommandOnKeyDownBehavior.cs
  WalletWasabi.Gui/Behaviors/CommandOnKeyUpBehavior.cs
  WalletWasabi.Gui/Behaviors/CommandOnPointerEnterLeaveBehavior.cs
  WalletWasabi.Gui/Behaviors/GreyOutOnDisabledBehavior.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendTabView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
  WalletWasabi.Gui/Tabs/SettingsView.xaml
  WalletWasabi.Gui/Tabs/SettingsViewModel.cs
  WalletWasabi.Gui/UiConfig.cs
  WalletWasabi.Tests/RegTests.cs
  WalletWasabi/Extensions/NBitcoinExtensions.cs
  WalletWasabi/Models/AllFeeEstimate.cs
  WalletWasabi/Services/WalletService.cs
  WalletWasabi/Services/WasabiSynchronizer.cs
Labels: feature/enhancement

#2043 A Brand New wasabiwallet.io ⭐️
  WalletWasabi.Backend/InitConfigStartupTask.cs
  WalletWasabi.Backend/UnversionedWebBuilder.cs
  WalletWasabi.Backend/WalletWasabi.Backend.csproj
  WalletWasabi.Backend/WebsiteTorifier.cs
  WalletWasabi.Backend/wwwroot/css/_variables.scss
  WalletWasabi.Backend/wwwroot/css/bootstrap.css
  WalletWasabi.Backend/wwwroot/css/style.css
  WalletWasabi.Backend/wwwroot/images/apple.png
  WalletWasabi.Backend/wwwroot/images/chrome-browser.png
  WalletWasabi.Backend/wwwroot/images/download-black.svg
  WalletWasabi.Backend/wwwroot/images/download.svg
  WalletWasabi.Backend/wwwroot/images/hero-off.jpg
  WalletWasabi.Backend/wwwroot/images/hero-on.jpg
  WalletWasabi.Backend/wwwroot/images/icon-colored-finder.svg
  WalletWasabi.Backend/wwwroot/images/icon-colored-linux.svg
  WalletWasabi.Backend/wwwroot/images/icon-colored-onion.png
  WalletWasabi.Backend/wwwroot/images/icon-colored-ubuntu.svg
  WalletWasabi.Backend/wwwroot/images/icon-colored-windows.svg
  WalletWasabi.Backend/wwwroot/images/icon-external.svg
  WalletWasabi.Backend/wwwroot/images/illustration-coinjoin.svg
  WalletWasabi.Backend/wwwroot/images/linux.png
  WalletWasabi.Backend/wwwroot/images/shader-loop.svg
  WalletWasabi.Backend/wwwroot/images/shader-wasabi.svg
  WalletWasabi.Backend/wwwroot/images/tor-browser.png
  WalletWasabi.Backend/wwwroot/images/wasabi-social.jpg
  WalletWasabi.Backend/wwwroot/images/wasabi-wallet-laptop.png
  WalletWasabi.Backend/wwwroot/images/wasabi-wallet-logo.svg
  WalletWasabi.Backend/wwwroot/images/windows.png
  WalletWasabi.Backend/wwwroot/index.html
Labels: UX, documentation/support, priority

#2068 Move in-wallet FAQ links to the new site
  WalletWasabi.Gui/Shell/Commands/HelpCommands.cs
  WalletWasabi.Gui/Tabs/AboutViewModel.cs
Labels: UX, documentation/support

#2094 Improve BuildTransaction documentation
  WalletWasabi/Services/WalletService.cs
Labels: documentation/support

#2112 Fix select all X checkbox functionality
  WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs
Labels: debug

#2069 Documentation site link added to about page and help menu
  WalletWasabi.Gui/Icons/Icons.xaml
  WalletWasabi.Gui/Shell/Commands/HelpCommands.cs
  WalletWasabi.Gui/Shell/MainMenu/HelpMainMenuItems.cs
  WalletWasabi.Gui/Tabs/AboutView.xaml
  WalletWasabi.Gui/Tabs/AboutViewModel.cs
Labels: UX, documentation/support

#2092 Test transaction processing code
  WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletViewModel.cs
  WalletWasabi.Tests/TransactionProcessorTests.cs
  WalletWasabi/Services/TransactionProcessor.cs
  WalletWasabi/Services/WalletService.cs
  azure-pipelines-linux.yml
  azure-pipelines-osx.yml
  azure-pipelines-windows.yml
Labels: refactoring, tests

#2100 OSX Clipboard handling fixes
  WalletWasabi.Gui/CommandLine/Daemon.cs
  WalletWasabi.Gui/Controls/NoparaPasswordBox.cs
  WalletWasabi.Gui/Controls/NoparaPasswordBox.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/GenerateWalletView.xaml
  WalletWasabi.Gui/Tabs/WalletManager/GenerateWalletViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/LoadWalletViewModel.cs
  WalletWasabi.Gui/WalletWasabi.Gui.csproj
  WalletWasabi.Tests/PasswordTests.cs
  WalletWasabi/Helpers/Constants.cs
  WalletWasabi/Helpers/PasswordHelper.cs
  WalletWasabi/KeyManagement/KeyManager.cs
  azure-pipelines-linux.yml
  azure-pipelines-osx.yml
  azure-pipelines-windows.yml
Labels: debug, priority

#2128 WalletService InitializeAsync Refactor
  WalletWasabi/Services/WalletService.cs
Labels: refactoring

#2127 Move paste code check in its right place
  WalletWasabi.Gui/Controls/NoparaPasswordBox.cs
Labels: refactoring

#2116 Refactor coin selection to leverage NBitcoin
  WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionViewerViewModel.cs
  WalletWasabi.Tests/RegTests.cs
  WalletWasabi/Helpers/Constants.cs
  WalletWasabi/Helpers/LabelBuilder.cs
  WalletWasabi/KeyManagement/HdPubKey.cs
  WalletWasabi/Models/SmartCoin.cs
  WalletWasabi/Models/TransactionBuilding/BuildTransactionResult.cs
  WalletWasabi/Models/TransactionBuilding/ChangeStrategy.cs
  WalletWasabi/Models/TransactionBuilding/DestinationRequest.cs
  WalletWasabi/Models/TransactionBuilding/FeeStrategy.cs
  WalletWasabi/Models/TransactionBuilding/FeeStrategyType.cs
  WalletWasabi/Models/TransactionBuilding/MoneyRequest.cs
  WalletWasabi/Models/TransactionBuilding/MoneyRequestType.cs
  WalletWasabi/Models/TransactionBuilding/PaymentIntent.cs
  WalletWasabi/Models/TransactionBuilding/SmartCoinSelector.cs
  WalletWasabi/Services/WalletService.cs
  WalletWasabi/WalletWasabi.csproj
Labels: refactoring

#2123 GetOrDownloadBlockAsync Refactor
  WalletWasabi.Tests/P2pTests.cs
  WalletWasabi/Services/WalletService.cs
Labels: refactoring

#2136 Monospaced Embedded Font
  WalletWasabi.Gui/Assets/Inconsolata-Regular.ttf
  WalletWasabi.Gui/Controls/WalletExplorer/CoinListView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/SendTabView.xaml
  WalletWasabi.Gui/Styles/Styles.xaml
Labels: UX

#2131 [DOC] Add introduction to ReadMe
  README.md
Labels: documentation/support
