Repository WalletWasabi/WalletWasabi, pull requests merged in 2020-10, with the labels that each got.

#4458 trivial: Remove unused `HttpResponseMessageExtensions.*` methods.
  WalletWasabi/Tor/Http/Extensions/HttpResponseMessageExtensions.cs
Labels: size/M

#4459 trivial: Remove unused `DataDir` property from Wallet.
  WalletWasabi/Tor/Http/Extensions/HttpResponseMessageExtensions.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/XS

#4413 Move event invocation outside of Lock
  WalletWasabi.Gui/Global.cs
  WalletWasabi/Blockchain/Analysis/FeesEstimation/FeeProviders.cs
Labels: size/M

#4457 trivial: Remove unused constructor from WasabiSynchronizer.
  WalletWasabi/Services/WasabiSynchronizer.cs
Labels: size/XS

#4449 Small cleanup
  WalletWasabi.Fluent.Desktop/Program.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/Views/HomeView.axaml.cs
  WalletWasabi.Fluent/Views/MainView.axaml.cs
  WalletWasabi.Fluent/Views/StatusBar.axaml.cs
Labels: size/S

#4444 Fix lurking wife mode in transaction details
  WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionInfoTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionViewModel.cs
Labels: size/S

#4461 WasabiSynchronizer: Constructors
  WalletWasabi/Services/WasabiSynchronizer.cs
Labels: size/S

#4451 Attempt to make `ExpirationTestsAsync` more robust wrt CI.
  WalletWasabi.Tests/UnitTests/MemoryTests.cs
Labels: size/M

#4462 WasabiClient: Add missing ConfigureAwait(false).
  WalletWasabi/WebClients/Wasabi/WasabiClient.cs
Labels: size/M

#4473 Remove duplicated port setting
  WalletWasabi.Backend/Program.cs
  WalletWasabi.Gui/Program.cs
Labels: size/XS

#4472 Make all Program classes consistently static (VS warning)
  WalletWasabi.Backend/Program.cs
  WalletWasabi.Gui/Program.cs
Labels: size/XS

#4467 Remove unused methods from HttpRequestMessageExtensions.
  WalletWasabi/Tor/Http/Extensions/HttpRequestMessageExtensions.cs
Labels: size/M

#4468 Rename Tests' Global to Common and make it a static utility class.
  WalletWasabi.Tests/Common.cs
  WalletWasabi.Tests/Global.cs
  WalletWasabi.Tests/Helpers/TestNodeBuilder.cs
  WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
  WalletWasabi.Tests/IntegrationTests/P2pTests.cs
  WalletWasabi.Tests/IntegrationTests/TorTests.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/RegressionTests/Common.cs
  WalletWasabi.Tests/UnitTests/BitcoinCore/P2pBasedTests.cs
  WalletWasabi.Tests/UnitTests/Filters/IndexStoreTests.cs
  WalletWasabi.Tests/UnitTests/IoTests.cs
  WalletWasabi.Tests/UnitTests/KeyManagementTests.cs
  WalletWasabi.Tests/UnitTests/LegalTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/AllTransactionStoreTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/OperationMergerTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionStoreMock.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionStoreTests.cs
  WalletWasabi.Tests/UnitTests/WalletDirTests.cs
  WalletWasabi.Tests/XunitConfiguration/RegTestFixture.cs
Labels: size/L

#4452 Feature/vdg/list wallets in nav bar
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent/App.xaml
  WalletWasabi.Fluent/Behaviors/SplitViewAutoBehavior.cs
  WalletWasabi.Fluent/Controls/NavBarItem.cs
  WalletWasabi.Fluent/Controls/NavBarItem.xaml
  WalletWasabi.Fluent/Controls/NavBarListBox.cs
  WalletWasabi.Fluent/Controls/NavBarTreeItem.cs
  WalletWasabi.Fluent/Controls/NavBarTreeItem.xaml
  WalletWasabi.Fluent/Controls/NavBarTreeView.cs
  WalletWasabi.Fluent/Converters/NavBarIconConverter.cs
  WalletWasabi.Fluent/Icons/Icons.xaml
  WalletWasabi.Fluent/Styles/Styles.xaml
  WalletWasabi.Fluent/ViewLocator.cs
  WalletWasabi.Fluent/ViewModels/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/ClosedHardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/ClosedWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/ClosedWatchOnlyWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/HardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/HomePageViewModel.cs
  WalletWasabi.Fluent/ViewModels/HomeViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBarItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/SettingsPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/ViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/WalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/WalletViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/WatchOnlyWalletViewModel.cs
  WalletWasabi.Fluent/Views/HomePageView.axaml
  WalletWasabi.Fluent/Views/HomePageView.axaml.cs
  WalletWasabi.Fluent/Views/MainView.axaml
  WalletWasabi.Fluent/Views/MainWindow.xaml
  WalletWasabi.Fluent/Views/MainWindow.xaml.cs
  WalletWasabi.Fluent/Views/NavBar.axaml
  WalletWasabi.Fluent/Views/NavBar.axaml.cs
  WalletWasabi.Fluent/Views/SettingsPageView.axaml
  WalletWasabi.Fluent/Views/SettingsPageView.axaml.cs
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
Labels: size/XXL

#4474 Remove leftover code
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Backend/Startup.cs
Labels: size/S

#4476 Create CreateHostBuilder method
  WalletWasabi.Backend/Program.cs
Labels: size/XS

#4469 Update Swagger
  WalletWasabi.Backend/WalletWasabi.Backend.csproj
Labels: size/XS

#4470 Remove version from backend package
  WalletWasabi.Backend/WalletWasabi.Backend.csproj
Labels: size/XS

#4477 Fix data directory inconsistencies in Tests
  WalletWasabi.Tests/Common.cs
  WalletWasabi.Tests/Helpers/TestNodeBuilder.cs
  WalletWasabi.Tests/IntegrationTests/P2pTests.cs
  WalletWasabi.Tests/RegressionTests/BackendTests.cs
  WalletWasabi.Tests/RegressionTests/BuildTests.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/RegressionTests/Common.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi.Tests/RegressionTests/WalletTests.cs
  WalletWasabi.Tests/UnitTests/BitcoinCore/P2pBasedTests.cs
  WalletWasabi.Tests/UnitTests/Filters/IndexStoreTests.cs
  WalletWasabi.Tests/UnitTests/IoTests.cs
  WalletWasabi.Tests/UnitTests/KeyManagementTests.cs
  WalletWasabi.Tests/UnitTests/LegalTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/AllTransactionStoreTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionStoreMock.cs
  WalletWasabi.Tests/UnitTests/WalletDirTests.cs
  WalletWasabi.Tests/XunitConfiguration/RegTestFixture.cs
  WalletWasabi/Helpers/EnvironmentHelpers.cs
Labels: size/L

#4478 Remove WalletWasabi.Community
  WalletWasabi.Community/Dojo.md
Labels: size/XS

#4427 Encode PSBT using base64 instead of base16
  WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
  WalletWasabi/WebClients/PayJoin/PayjoinClient.cs
Labels: size/S

#4479 Revert "Remove leftover code"
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Backend/Startup.cs
Labels: size/S

#4480 Remove unused ctor
  WalletWasabi.Backend/Global.cs
Labels: size/XS

#4481 Fix BroadcastInvalidTxAsync RegTest
  WalletWasabi.Tests/RegressionTests/BackendTests.cs
Labels: size/XS

#4482 Fix CoinJoinTests
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
Labels: size/XS

#4483 Add back endpoint
  WalletWasabi.Backend/Program.cs
Labels: size/XS

#4490 Increase timeout for SingleInstanceChecker.
  WalletWasabi/Services/SingleInstanceChecker.cs
Labels: size/XS

#4406 Use SuppressMessage attribute instead of #pragma warning to suppress naming violations
  WalletWasabi.Backend/Program.cs
  WalletWasabi.Packager/Program.cs
  WalletWasabi/Crypto/SchnorrBlindingSignature.cs
Labels: size/S

#4376 Keep OS system alive when CoinJoining
  WalletWasabi.Gui/CommandLine/Daemon.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Tests/UnitTests/Clients/PreventSleepTests.cs
  WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
  WalletWasabi/Helpers/EnvironmentHelpers.cs
  WalletWasabi/Services/SystemAwakeChecker.cs
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/M

#4488 Move `SendAndRetryAsync` from `TorHttpClientExtensions` to `ITorHttpC…
  WalletWasabi.Tests/RegressionTests/BackendTests.cs
  WalletWasabi/Tor/Http/Extensions/TorHttpClientExtensions.cs
  WalletWasabi/Tor/Http/Interfaces/ITorHttpClient.cs
  WalletWasabi/WebClients/Wasabi/WasabiClient.cs
Labels: size/L

#4484 Fix formatting & some refactoring
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent/App.xaml.cs
  WalletWasabi.Fluent/Behaviors/SplitViewAutoBehavior.cs
  WalletWasabi.Fluent/Controls/NavBarTreeItem.xaml
  WalletWasabi.Fluent/Icons/Icons.xaml
  WalletWasabi.Fluent/Styles/Styles.xaml
  WalletWasabi.Fluent/ViewModels/NavBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/SettingsPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/WalletViewModel.cs
  WalletWasabi.Fluent/Views/MainView.axaml
  WalletWasabi.Fluent/Views/MainWindow.xaml
  WalletWasabi.Fluent/Views/MainWindow.xaml.cs
  WalletWasabi.Fluent/Views/NavBar.axaml
  WalletWasabi.Fluent/Views/NavBar.axaml.cs
  WalletWasabi.Fluent/Views/SettingsPageView.axaml.cs
  WalletWasabi.Fluent/Views/StatusBar.axaml
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
Labels: size/L

#4498 Remove dojo from website
  WalletWasabi.Backend/wwwroot/index.html
Labels: size/XS

#4495 Use SuppressMessage attribute instead of #pragma warning
  WalletWasabi.Backend/Startup.cs
  WalletWasabi.Packager/NSubsys/PeUtility.cs
  WalletWasabi.Tests/RegressionTests/Common.cs
  WalletWasabi.Tests/TestableRpcService.cs
  WalletWasabi/Blockchain/Transactions/SmartTransaction.cs
Labels: size/S

#4446 TorHttpClient - internal separation of clearnet mode and Tor mode.
  WalletWasabi/Tor/Http/ClearnetHttpClient.cs
  WalletWasabi/Tor/Http/Extensions/HttpContentExtensions.cs
  WalletWasabi/Tor/Http/IHttpClient.cs
  WalletWasabi/Tor/Http/Interfaces/ITorHttpClient.cs
  WalletWasabi/Tor/Http/TorHttpClient.cs
  WalletWasabi/Tor/Socks5/TorSocks5Client.cs
Labels: size/L

#4496 Remove pragma warning and use discard
  WalletWasabi.Tests/RegressionTests/BackendTests.cs
  WalletWasabi.Tests/RegressionTests/BuildTests.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/RegressionTests/DosTests.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi.Tests/RegressionTests/WalletTests.cs
Labels: size/M

#4429 [WabiSabi] Range proof
  WalletWasabi.Tests/UnitTests/Crypto/ProofSystemTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/LinearRelationTests.cs
  WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Statement.cs
  WalletWasabi/Crypto/ZeroKnowledge/ProofSystem.cs
  WalletWasabi/Crypto/ZeroKnowledge/Transcript.cs
Labels: size/L

#4506 trivial: Remove redundant IDisposable.
  WalletWasabi/Tor/Http/TorHttpClient.cs
Labels: size/XS

#4504 Use TryGet* approach in SystemNetExtensions.
  WalletWasabi.Tests/UnitTests/Userfacing/ParserTests.cs
  WalletWasabi/BitcoinCore/CoreNode.cs
  WalletWasabi/Extensions/SystemNetExtensions.cs
  WalletWasabi/Tor/Socks5/TorSocks5Client.cs
Labels: size/L

#4508 [Trivial] Simplify name
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Tests/UnitTests/Crypto/BlindingTests.cs
  WalletWasabi.Tests/XunitConfiguration/RegTestFixture.cs
  WalletWasabi/Helpers/EnvironmentHelpers.cs
Labels: size/S

#4499 VDG: NavBar compability with OSX
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent/Controls/NavBarItem.xaml
  WalletWasabi.Fluent/Controls/NavBarTreeItem.xaml
  WalletWasabi.Fluent/Helpers/Const.cs
  WalletWasabi.Fluent/Helpers/PlatformExtension.cs
  WalletWasabi.Fluent/Styles/Styles.xaml
  WalletWasabi.Fluent/Views/MainWindow.xaml
  WalletWasabi.Fluent/Views/NavBar.axaml
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
Labels: size/M

#4500 [Fluent] Dark and Light theme prework
  WalletWasabi.Fluent/App.xaml
  WalletWasabi.Fluent/Styles/Styles.xaml
  WalletWasabi.Fluent/Styles/Themes/BaseDark.xaml
  WalletWasabi.Fluent/Styles/Themes/BaseLight.xaml
  WalletWasabi.Fluent/Views/MainView.axaml
  WalletWasabi.Fluent/Views/NavBar.axaml
  WalletWasabi.Fluent/Views/StatusBar.axaml
Labels: size/M

#4515 Add legacy get all fees API
  WalletWasabi.Backend/Controllers/LegacyController.cs
Labels: size/S

#4516 Add legacy exchange-rate API
  WalletWasabi.Backend/Controllers/LegacyController.cs
Labels: size/XS

#4492 Update and optimize title and h1
  WalletWasabi.Backend/wwwroot/index.html
Labels: size/S

#4513 Tor restart.
  WalletWasabi/Tor/Socks5/TorSocks5Client.cs
Labels: size/XS

#4518 TorSocks5Client: Remove unused code.
  WalletWasabi/Tor/Socks5/TorSocks5Client.cs
Labels: size/M

#4519 Refactor VerField.
  WalletWasabi/Tor/Socks5/Models/Bases/OctetSerializableBase.cs
  WalletWasabi/Tor/Socks5/Models/Fields/OctetFields/VerField.cs
  WalletWasabi/Tor/Socks5/Models/Messages/MethodSelectionResponse.cs
  WalletWasabi/Tor/Socks5/Models/Messages/TorSocks5Request.cs
  WalletWasabi/Tor/Socks5/Models/Messages/TorSocks5Response.cs
  WalletWasabi/Tor/Socks5/Models/Messages/VersionMethodRequest.cs
Labels: size/M

#4525 Ensure `ExposedKeys` are properly cleaned up before usage
  WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
Labels: size/S

#4528 Rename to PrivacyMode
  WalletWasabi.Gui/Controls/TransactionDetails/Views/TransactionDetails.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/CoinListView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/CoinViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionInfoTabView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionInfoTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionViewerView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionViewerViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletViewModel.cs
  WalletWasabi.Gui/Converters/PrivacyModeStringConverter.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Gui/UiConfig.cs
  WalletWasabi.Gui/ViewModels/AddressViewModel.cs
  WalletWasabi.Tests/UnitTests/MemoryTests.cs
  WalletWasabi.Tests/UnitTests/NBitcoinTests.cs
  WalletWasabi/Extensions/NBitcoinExtensions.cs
Labels: size/L

#4530 Add CodeFactor shell checker config
  .shellcheckrc
Labels: size/XS

#4520 bugfix HwiClient.SendCommandAsync() recursive call
  WalletWasabi/Hwi/HwiClient.cs
Labels: size/XS

#4523 [Trivial] Use expression body
  WalletWasabi.Gui/Tabs/WalletManager/RecoverWallets/RecoverWalletViewModel.cs
  WalletWasabi/Crypto/Mac.cs
Labels: size/S

#4524 [Trivial] Remove unused member
  WalletWasabi/WebClients/PayJoin/PayjoinReceiverException.cs
Labels: size/XS

#4536 Rename to privacy mode in UiConfig
  WalletWasabi.Gui/UiConfig.cs
Labels: size/XS

#4522 Remove unused variable
  WalletWasabi/CoinJoin/Coordinator/MixingLevels/MixingLevel.cs
Labels: size/XS

#4534 [Fluent] Rename LWM to Privacy Mode
  WalletWasabi.Fluent/ViewModels/WalletViewModel.cs
Labels: size/XS

#4463 Add config option to close Tor instance on quit
  WalletWasabi.Gui/Config.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Gui/Tabs/SettingsView.xaml
  WalletWasabi.Gui/Tabs/SettingsViewModel.cs
  WalletWasabi/Tor/TorProcessManager.cs
Labels: size/M

#4485 Add Nullable reference types to new projects (Fluent)
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
Labels: size/XS

#4541 [Trivial] Correct comment
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
Labels: size/XS

#4540 [Trivial] Fix capitalization
  WalletWasabi.Gui/Helpers/NotificationHelpers.cs
  WalletWasabi.Gui/Tabs/WalletManager/HardwareWallets/ConnectHardwareWalletViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/WalletManagerViewModel.cs
Labels: size/S

#4538 TorSocks5Request: Remove unused constructor.
  WalletWasabi/Tor/Socks5/Models/Messages/TorSocks5Request.cs
Labels: size/XS

#4537 Randomize lock names in SingleInstanceChecker test.
  WalletWasabi.Tests/UnitTests/Clients/SingleInstanceCheckerTests.cs
  WalletWasabi/Services/SingleInstanceChecker.cs
Labels: size/M

#4533 WasabiSynchronizer: Add missing ConfigureAwait(false).
  WalletWasabi/Services/WasabiSynchronizer.cs
Labels: size/S

#4539 Fluent: NavBar - Wasabi Logo - Animation - Polish
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent/Controls/NavBarItem.xaml
  WalletWasabi.Fluent/Controls/NavBarTreeItem.xaml
  WalletWasabi.Fluent/Icons/Icons.xaml
  WalletWasabi.Fluent/Styles/Themes/Base.xaml
  WalletWasabi.Fluent/Styles/Themes/BaseDark.xaml
  WalletWasabi.Fluent/Styles/Themes/BaseLight.xaml
  WalletWasabi.Fluent/ViewModels/NavBarItemViewModel.cs
  WalletWasabi.Fluent/Views/MainView.axaml
  WalletWasabi.Fluent/Views/NavBar.axaml
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
Labels: size/L

#4548 [Fluent] Add some common csproj settings
  WalletWasabi.Backend/WalletWasabi.Backend.csproj
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Gui/WalletWasabi.Gui.csproj
  WalletWasabi.Packager/WalletWasabi.Packager.csproj
  WalletWasabi.Tests/WalletWasabi.Tests.csproj
  WalletWasabi/WalletWasabi.csproj
Labels: size/XL

#4535 [Fluent] Migrate ViewModelBase.cs
  WalletWasabi.Fluent/ViewLocator.cs
  WalletWasabi.Fluent/ViewModels/NavBarItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/ViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/WalletViewModel.cs
Labels: size/S

#4487 [Fluent] Modal Dialog Infrastructure
  WalletWasabi.Fluent/App.xaml
  WalletWasabi.Fluent/Controls/Dialog.xaml
  WalletWasabi.Fluent/Controls/Dialog.xaml.cs
  WalletWasabi.Fluent/Styles/Styles.xaml
  WalletWasabi.Fluent/Styles/Themes/BaseDark.xaml
  WalletWasabi.Fluent/Styles/Themes/BaseLight.xaml
  WalletWasabi.Fluent/ViewModels/Dialogs/DialogViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/DialogViewModelBaseOfTResult.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/IDialogHost.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/TestDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/SettingsPageViewModel.cs
  WalletWasabi.Fluent/Views/Dialogs/TestDialogView.axaml
  WalletWasabi.Fluent/Views/Dialogs/TestDialogView.axaml.cs
  WalletWasabi.Fluent/Views/MainView.axaml
  WalletWasabi.Fluent/Views/MainWindow.axaml
  WalletWasabi.Fluent/Views/MainWindow.axaml.cs
  WalletWasabi.Fluent/Views/SettingsPageView.axaml
Labels: size/L

#4532 TorSocks5Client: Remove isRecursiveCall.
  WalletWasabi/Tor/Socks5/TorSocks5Client.cs
Labels: size/M

#4555 Fix Logical Evaluation
  WalletWasabi.Fluent/Behaviors/SplitViewAutoBehavior.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/DialogViewModelBase.cs
Labels: size/XS

#4559 Use shorter syntax in Global class.
  WalletWasabi.Gui/Global.cs
Labels: size/M

#4552 Document more `MempoolNotifiesAsync` test.
  WalletWasabi.Tests/UnitTests/BitcoinCore/P2pBasedTests.cs
  WalletWasabi/BitcoinCore/Rpc/IRPCClient.cs
  WalletWasabi/BitcoinCore/Rpc/RpcClientBase.cs
  WalletWasabi/Blockchain/Mempool/MempoolService.cs
  WalletWasabi/Services/HostedServices.cs
Labels: size/M

#4556 Fix CC Kata test
  WalletWasabi.Tests/AcceptanceTests/HwiKatas.cs
Labels: size/S

#4544 QR without extra click
  WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs
Labels: size/XS

#4558 trivial: Fix nullability issues in NotificationHelpers.cs
  WalletWasabi.Gui/Helpers/NotificationHelpers.cs
Labels: size/S

#4493 [Fluent] TextBox style
  WalletWasabi.Fluent/Styles/Styles.xaml
  WalletWasabi.Fluent/Styles/Themes/Base.xaml
  WalletWasabi.Fluent/Styles/Themes/BaseDark.xaml
  WalletWasabi.Fluent/Styles/Themes/BaseLight.xaml
  WalletWasabi.Fluent/ViewModels/Dialogs/DialogViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/SettingsPageViewModel.cs
  WalletWasabi.Fluent/Views/NavBar.axaml
  WalletWasabi.Fluent/Views/SettingsPageView.axaml
Labels: size/M

#4551 [Fluent] Change theme button for developing
  WalletWasabi.Fluent/ViewModels/SettingsPageViewModel.cs
  WalletWasabi.Fluent/Views/SettingsPageView.axaml
Labels: size/S

#4561 Fix nullability for events and its `object sender` parameter.
  CONTRIBUTING.md
  WalletWasabi.Backend/InitConfigStartupTask.cs
  WalletWasabi.Gui/Controls/LockScreen/SlideLock.cs
  WalletWasabi.Gui/Controls/SortingArrow.cs
  WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs
  WalletWasabi.Gui/MainWindow.xaml.cs
  WalletWasabi.Gui/Program.cs
  WalletWasabi.Gui/ViewModels/ViewModelBase.cs
  WalletWasabi.Tests/RegressionTests/Common.cs
  WalletWasabi/Bases/NotifyPropertyChangedBase.cs
  WalletWasabi/BitcoinCore/Monitoring/RpcFeeProvider.cs
  WalletWasabi/BitcoinCore/Monitoring/RpcMonitor.cs
  WalletWasabi/BitcoinCore/P2pNode.cs
  WalletWasabi/Blockchain/Analysis/FeesEstimation/FeeProviders.cs
  WalletWasabi/Blockchain/Analysis/FeesEstimation/IFeeProvider.cs
  WalletWasabi/Blockchain/BlockFilters/IndexBuilderService.cs
  WalletWasabi/Blockchain/Blocks/BlockNotifier.cs
  WalletWasabi/Blockchain/P2p/TrustedP2pBehavior.cs
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
  WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
  WalletWasabi/CoinJoin/Client/CoinJoinProcessor.cs
  WalletWasabi/CoinJoin/Coordinator/Coordinator.cs
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
  WalletWasabi/Services/UpdateChecker.cs
  WalletWasabi/Services/WasabiSynchronizer.cs
  WalletWasabi/Stores/IndexStore.cs
  WalletWasabi/Wallets/P2pBlockProvider.cs
  WalletWasabi/Wallets/Wallet.cs
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/L

#4567 `Synchronizer` must be stopped after `HostedServices`.
  WalletWasabi.Gui/Global.cs
Labels: size/S

#4565 trivial: Use new syntax in TorSocks5Client.cs
  WalletWasabi/Tor/Socks5/TorSocks5Client.cs
Labels: size/XS

#4569 [Trivial] Fix comment + format
  WalletWasabi.Fluent/ViewModels/SettingsPageViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/PinPadViewModel.cs
  WalletWasabi.Tests/AcceptanceTests/HwiKatas.cs
  WalletWasabi/Stores/IndexStore.cs
Labels: size/S

#4564 trivial: Remove superfluous condition.
  WalletWasabi/Tor/TorProcessManager.cs
Labels: size/XS

#4573 Feature/vdg/content area
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent/App.xaml
  WalletWasabi.Fluent/Controls/ContentArea.axaml
  WalletWasabi.Fluent/Controls/ContentArea.axaml.cs
  WalletWasabi.Fluent/Controls/Dialog.xaml
  WalletWasabi.Fluent/Views/Dialogs/TestDialogView.axaml
  WalletWasabi.Fluent/Views/HomePageView.axaml
  WalletWasabi.Fluent/Views/MainView.axaml
  WalletWasabi.Fluent/Views/SettingsPageView.axaml
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
Labels: size/L

#4566 TorProcessManager: Improve documentation, rename `Stop` to `MonitorCt…
  WalletWasabi/Tor/TorProcessManager.cs
Labels: size/M

#4576 ITorHttpClient interface does not require IDisposable. TorHttpClient …
  WalletWasabi.Tests/UnitTests/Clients/MockTorHttpClient.cs
  WalletWasabi/Tor/Http/Bases/TorDisposableBase.cs
  WalletWasabi/Tor/Http/Interfaces/ITorHttpClient.cs
  WalletWasabi/Tor/Http/TorHttpClient.cs
Labels: size/M

#4572 Upgrade XUnit packages
  WalletWasabi.Tests/WalletWasabi.Tests.csproj
Labels: size/XS

#4577 `WasabiClient` no longer inherits `TorDisposableBase`.
  WalletWasabi/Tor/Http/Bases/TorDisposableBase.cs
  WalletWasabi/WebClients/Wasabi/WasabiClient.cs
Labels: size/M

#4579 WasabiSynchronizer: Cancelling + logging.
  WalletWasabi/Services/WasabiSynchronizer.cs
  WalletWasabi/Tor/Socks5/TorSocks5Client.cs
Labels: size/S

#4582 Pass byte via constructor to MethodField.
  WalletWasabi/Tor/Socks5/Models/Fields/ByteArrayFields/MethodsField.cs
  WalletWasabi/Tor/Socks5/Models/Fields/OctetFields/MethodField.cs
  WalletWasabi/Tor/Socks5/Models/Fields/OctetFields/VerField.cs
  WalletWasabi/Tor/Socks5/Models/Messages/MethodSelectionResponse.cs
Labels: size/M

#4526 Fix some obvious null warnings
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionBroadcasterViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionViewerViewModel.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Gui/Shell/Commands/SystemCommands.cs
  WalletWasabi.Gui/Shell/Commands/ToolCommands.cs
  WalletWasabi.Gui/Tabs/WalletManager/HardwareWallets/ConnectHardwareWalletViewModel.cs
Labels: size/S

#4574 [Fluent] Standardized Styles for fonts and control alignment
  WalletWasabi.Fluent/Styles/Styles.xaml
  WalletWasabi.Fluent/Views/MainView.axaml
  WalletWasabi.Fluent/Views/NavBar.axaml
Labels: size/L

#4589 [Trivial] Fix wrong usage of Task.FromException
  WalletWasabi.Gui/CommandLine/CrashReportCommand.cs
Labels: size/XS

#4562 [Fluent] Action button style
  WalletWasabi.Fluent/Styles/Styles.xaml
  WalletWasabi.Fluent/Styles/Themes/Base.xaml
  WalletWasabi.Fluent/Styles/Themes/BaseDark.xaml
  WalletWasabi.Fluent/Styles/Themes/BaseLight.xaml
  WalletWasabi.Fluent/Views/SettingsPageView.axaml
Labels: size/S

#4557 [Fluent] Dialog interactions
  WalletWasabi.Fluent/ViewModels/Dialogs/TestDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/SettingsPageViewModel.cs
  WalletWasabi.Fluent/Views/Dialogs/TestDialogView.axaml
Labels: size/M

#4585 Remove control statements from Main()
  WalletWasabi.Gui/Program.cs
Labels: size/M

#4590 Fix UpdateChecker Nullable
  WalletWasabi/Services/UpdateChecker.cs
Labels: size/S

#4586 Remove CrashReported from Global
  WalletWasabi.Gui/CrashReport/ViewModels/CrashReportWindowViewModel.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Gui/Program.cs
Labels: size/S

#4592 Quick fix to fluent project
  WalletWasabi.Fluent.Desktop/Program.cs
Labels: size/S

#4587 Remove Environment.Exit from Daemon
  WalletWasabi.Gui/CommandLine/MixerCommand.cs
  WalletWasabi.Gui/Program.cs
Labels: size/M

#4588 Remove Environment.Exit from PasswordFinder
  WalletWasabi.Gui/CommandLine/PasswordFinderCommand.cs
Labels: size/S

#4601 Remove PSBT output if KeyPath added to both inputs and outputs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
Labels: size/S

#4510 [WabiSabi] WabiSabi API version
  WalletWasabi.Tests/UnitTests/Crypto/GroupElements/GeneralTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/GroupElements/GeneratorTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/GroupElements/OperationTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/ProofSystemTests.cs
  WalletWasabi.Tests/UnitTests/Wabisabi/CredentialTests.cs
  WalletWasabi/Crypto/Extensions.cs
  WalletWasabi/Crypto/Groups/GroupElement.cs
  WalletWasabi/Crypto/ScalarVector.cs
  WalletWasabi/Crypto/ZeroKnowledge/ProofSystem.cs
  WalletWasabi/Helpers/Constants.cs
  WalletWasabi/Wabisabi/CredentialIssuer.cs
  WalletWasabi/Wabisabi/CredentialPool.cs
  WalletWasabi/Wabisabi/IssuanceRequest.cs
  WalletWasabi/Wabisabi/IssuanceValidationData.cs
  WalletWasabi/Wabisabi/RegistrationRequest.cs
  WalletWasabi/Wabisabi/RegistrationResponse.cs
  WalletWasabi/Wabisabi/RegistrationValidationData.cs
  WalletWasabi/Wabisabi/WabiSabiClient.cs
  WalletWasabi/Wabisabi/WabiSabiErrorCode.cs
  WalletWasabi/Wabisabi/WabiSabiException.cs
Labels: size/XXL

#4602 VersionMethodRequest & NMethodsField refactoring.
  WalletWasabi/Tor/Socks5/Models/Fields/OctetFields/NMethodsField.cs
  WalletWasabi/Tor/Socks5/Models/Messages/VersionMethodRequest.cs
Labels: size/M

#4598 TorSocks5Client: Adjust accessibility modifiers.
  WalletWasabi/Tor/Socks5/TorSocks5Client.cs
Labels: size/S

#4605 Fix naming violations
  WalletWasabi/Crypto/Groups/GroupElement.cs
Labels: size/S

#4583 [Fluent] Fix nullable warnings for events
  WalletWasabi.Fluent.Desktop/Program.cs
  WalletWasabi.Gui/Global.cs
Labels: size/XS

#4581 Add CancellationTokens to TorSocks5Client methods.
  WalletWasabi/Tor/Http/TorHttpClient.cs
  WalletWasabi/Tor/Socks5/TorSocks5Client.cs
Labels: size/M

#4584 Fix formatting
  WalletWasabi.Fluent.Desktop/Program.cs
  WalletWasabi.Fluent/App.xaml.cs
  WalletWasabi.Fluent/Controls/ContentArea.axaml
  WalletWasabi.Fluent/Controls/Dialog.xaml
  WalletWasabi.Fluent/Controls/Dialog.xaml.cs
  WalletWasabi.Fluent/Controls/NavBarItem.xaml
  WalletWasabi.Fluent/Controls/NavBarTreeItem.xaml
  WalletWasabi.Fluent/Styles/Styles.xaml
  WalletWasabi.Fluent/Views/NavBar.axaml
  WalletWasabi.Fluent/Views/SettingsPageView.axaml
  WalletWasabi/Services/SingleInstanceChecker.cs
  WalletWasabi/Services/WasabiSynchronizer.cs
  WalletWasabi/Tor/Http/Extensions/HttpRequestMessageExtensions.cs
  WalletWasabi/Tor/Http/TorHttpClient.cs
Labels: size/M

#4606 [Backport] Cherry picking changes to v1.1.1.12.1
  WalletWasabi.Gui/Controls/StatusBar.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/CoinInfoTabView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoView.xaml
  WalletWasabi.Gui/CrashReport/ViewModels/CrashReportWindowViewModel.cs
  WalletWasabi.Gui/CrashReport/Views/CrashReportWindow.xaml
  WalletWasabi.Gui/Tabs/AboutView.xaml
  WalletWasabi.Gui/Tabs/LegalDocumentsView.xaml
  WalletWasabi.Gui/Tabs/SettingsView.xaml
  WalletWasabi.Gui/UiConfig.cs
  WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
  WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
  WalletWasabi/Hwi/Models/HardwareWalletModels.cs
  WalletWasabi/Legal/Assets/LegalDocuments.txt
  WalletWasabi/TorSocks5/TorHttpClient.cs
  WalletWasabi/WebClients/PayJoin/PayjoinClient.cs
Labels: size/L

#4560 [Trivial] Fix name violation
  WalletWasabi.Fluent/ViewModels/Dialogs/DialogViewModelBaseOfTResult.cs
Labels: size/S

#4607 Dump version to v1.1.12.1 backport release
  WalletWasabi.Backend/wwwroot/index.html
  WalletWasabi/Helpers/Constants.cs
Labels: size/S

#4580 WasabiSynchronizer: Constants for state & dispose cleanup.
  WalletWasabi/Services/WasabiSynchronizer.cs
Labels: size/M

#4578 Initialize the backing field instead of the property in the constructor
  WalletWasabi.Fluent/ViewModels/WalletViewModel.cs
  WalletWasabi.Gui/Controls/QrCode.cs
  WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionBroadcasterViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletViewModel.cs
  WalletWasabi.Gui/Tabs/SettingsViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/HardwareWallets/ConnectHardwareWalletViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletViewModel.cs
  WalletWasabi.Gui/ViewModels/MainWindowViewModel.cs
  WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
  WalletWasabi/Blockchain/Analysis/Clustering/Cluster.cs
Labels: size/M

#4609 CoinJoinClient: Constants for state & dispose cleanup
  WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
Labels: size/S

#4617 [Trivial] Use Hashes.DoubleSHA256 instead of the obsolete method Hashes.Hash256
  WalletWasabi.Tests/UnitTests/BitcoinCore/IndexBuilderServiceTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/BlindingTests.cs
  WalletWasabi/Helpers/NBitcoinHelpers.cs
Labels: size/XS

#4618 [Trivial] Simplify member access
  WalletWasabi.Fluent/Controls/NavBarListBox.cs
  WalletWasabi.Fluent/Controls/NavBarTreeItem.xaml.cs
  WalletWasabi.Fluent/Controls/NavBarTreeView.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/TestDialogViewModel.cs
  WalletWasabi.Tests/UnitTests/Crypto/BlindingTests.cs
  WalletWasabi.Tests/UnitTests/Hwi/DefaultResponseTests.cs
  WalletWasabi/Helpers/Constants.cs
Labels: size/M

#4621 Remove some unused constructors
  WalletWasabi/Tor/Socks5/Models/Bases/ByteArraySerializableBase.cs
  WalletWasabi/Tor/Socks5/Models/Fields/ByteArrayFields/PasswdField.cs
  WalletWasabi/Tor/Socks5/Models/Fields/OctetFields/PLenField.cs
  WalletWasabi/Tor/Socks5/Models/Fields/OctetFields/ULenField.cs
  WalletWasabi/Tor/Socks5/Models/Messages/TorSocks5Response.cs
  WalletWasabi/Tor/Socks5/Models/Messages/UsernamePasswordRequest.cs
  WalletWasabi/Tor/Socks5/Models/Messages/UsernamePasswordResponse.cs
Labels: size/L

#4620 Pass dependencies via constructor in CoinListViewModel (remove Locator)
  WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
Labels: size/M

#4615 [Backport] Cherry picking changes to v1.1.12.2
  WalletWasabi.Gui/Controls/WalletExplorer/CoinInfoTabView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/CoinListView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/CoinViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionViewModel.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Gui/Suggestions/SuggestLabelView.xaml
  WalletWasabi.Gui/packages.lock.json
  WalletWasabi.Packager/packages.lock.json
  WalletWasabi.Tests/IntegrationTests/P2pTests.cs
  WalletWasabi.Tests/RegressionTests/BuildTests.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/RegressionTests/Common.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi.Tests/RegressionTests/WalletTests.cs
  WalletWasabi.Tests/UnitTests/BitcoinCore/P2pBasedTests.cs
  WalletWasabi.Tests/UnitTests/Filters/IndexStoreTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/AllTransactionStoreTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/PayjoinTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
  WalletWasabi/Blockchain/Analysis/Clustering/Cluster.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/Blockchain/TransactionBuilding/SmartCoinSelector.cs
  WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs
  WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
  WalletWasabi/Blockchain/Transactions/AllTransactionStore.cs
  WalletWasabi/Blockchain/Transactions/AllTransactionStoreMock.cs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
  WalletWasabi/Blockchain/Transactions/TransactionHistoryBuilder.cs
  WalletWasabi/Blockchain/Transactions/TransactionSummary.cs
  WalletWasabi/Helpers/Constants.cs
  WalletWasabi/Stores/BitcoinStore.cs
  WalletWasabi/Stores/BitcoinStoreMock.cs
  WalletWasabi/Stores/IndexStore.cs
  WalletWasabi/WalletWasabi.csproj
  WalletWasabi/Wallets/FileSystemBlockRepository.cs
  WalletWasabi/Wallets/Wallet.cs
  WalletWasabi/packages.lock.json
Labels: size/XL

#4627 Add Label Styles + move fontsize values to resources
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent/Styles/Styles.xaml
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
Labels: size/M

#4628 Dump client version to v1.1.12.2
  WalletWasabi.Backend/wwwroot/index.html
  WalletWasabi/Helpers/Constants.cs
Labels: size/S

#4599 [Fluent] format and colors
  WalletWasabi.Fluent/Styles/Styles.xaml
  WalletWasabi.Fluent/Styles/Themes/Base.xaml
Labels: size/L

#4593 [Fluent] ContentArea modifications
  WalletWasabi.Fluent/Controls/ContentArea.axaml
  WalletWasabi.Fluent/Controls/ContentArea.axaml.cs
  WalletWasabi.Fluent/Controls/Dialog.xaml
  WalletWasabi.Fluent/Views/MainView.axaml
Labels: size/M

#4608 Concept for cleaner PSBT update
  WalletWasabi.Gui/packages.lock.json
  WalletWasabi.Packager/packages.lock.json
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
  WalletWasabi/Extensions/NBitcoinExtensions.cs
  WalletWasabi/WalletWasabi.csproj
  WalletWasabi/packages.lock.json
Labels: size/L

#4626 Pass parameter via constructor to AuthVerField
  WalletWasabi/Tor/Socks5/Models/Fields/OctetFields/AuthVerField.cs
  WalletWasabi/Tor/Socks5/Models/Messages/UsernamePasswordRequest.cs
  WalletWasabi/Tor/Socks5/Models/Messages/UsernamePasswordResponse.cs
Labels: size/S

#4625 Pass parameter via constructor to AuthStatusField
  WalletWasabi/Tor/Socks5/Models/Fields/OctetFields/AuthStatusField.cs
  WalletWasabi/Tor/Socks5/Models/Messages/UsernamePasswordResponse.cs
Labels: size/M

#4624 Pass parameters via constructor to AtypField
  WalletWasabi/Tor/Socks5/Models/Fields/ByteArrayFields/AddrField.cs
  WalletWasabi/Tor/Socks5/Models/Fields/OctetFields/AtypField.cs
  WalletWasabi/Tor/Socks5/Models/Messages/TorSocks5Request.cs
  WalletWasabi/Tor/Socks5/Models/Messages/TorSocks5Response.cs
Labels: size/M

#4507 Add WasabiClientFactory and remove Synchronizer.WasabiClient.
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
  WalletWasabi.Tests/IntegrationTests/P2pTests.cs
  WalletWasabi.Tests/RegressionTests/BuildTests.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/RegressionTests/Common.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi.Tests/RegressionTests/WalletTests.cs
  WalletWasabi/Blockchain/Mempool/MempoolService.cs
  WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs
  WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
  WalletWasabi/CoinJoin/Client/Clients/SatoshiClient.cs
  WalletWasabi/CoinJoin/Client/CoinJoinProcessor.cs
  WalletWasabi/Services/UpdateChecker.cs
  WalletWasabi/Services/WasabiSynchronizer.cs
  WalletWasabi/Tor/Http/Bases/TorDisposableBase.cs
  WalletWasabi/Tor/Socks5/TorSocks5Client.cs
  WalletWasabi/Wallets/P2pBlockProvider.cs
  WalletWasabi/Wallets/Wallet.cs
  WalletWasabi/WebClients/Wasabi/WasabiClient.cs
  WalletWasabi/WebClients/Wasabi/WasabiClientFactory.cs
Labels: size/L

#4604 (Fluent) Use TerminateService
  WalletWasabi.Fluent.Desktop/Program.cs
  WalletWasabi.Gui/CommandLine/Daemon.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Gui/MainWindow.xaml.cs
  WalletWasabi.Gui/Program.cs
  WalletWasabi.Gui/Rpc/JsonRpcServer.cs
  WalletWasabi.Gui/Rpc/WasabiJsonRpcService.cs
  WalletWasabi/Services/Terminate/TerminateService.cs
Labels: size/L

#4634 fix editor config and stylecop in rider / fluent sln
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.sln
Labels: size/S

#4595 VDG: Fluent - Implements the home screen
  WalletWasabi.Fluent.Desktop/Program.cs
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent/Behaviors/AttachedToVisualTreeBehavior.cs
  WalletWasabi.Fluent/Behaviors/FocusOnAttachedBehavior.cs
  WalletWasabi.Fluent/Icons/Icons.xaml
  WalletWasabi.Fluent/Styles/OptionButton.xaml
  WalletWasabi.Fluent/Styles/Styles.xaml
  WalletWasabi.Fluent/Styles/Themes/BaseDark.xaml
  WalletWasabi.Fluent/Styles/Themes/BaseLight.xaml
  WalletWasabi.Fluent/ViewModels/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/ClosedWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/IDialogHost.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/TestDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/HomePageViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBarItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/SettingsPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
  WalletWasabi.Fluent/Views/AddWalletPageView.axaml
  WalletWasabi.Fluent/Views/AddWalletPageView.axaml.cs
  WalletWasabi.Fluent/Views/HomePageView.axaml
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
Labels: size/XL

#4630 Validations upgrade
  WalletWasabi.Gui/Validation/Validations.cs
Labels: size/M

#4637 Do not isolate Tor stream when checking connection status
  WalletWasabi/Tor/Socks5/TorSocks5Client.cs
Labels: size/XS

#4635 First review round
  WalletWasabi.Tests/UnitTests/Crypto/ProofSystemHelpers.cs
  WalletWasabi.Tests/UnitTests/Crypto/ProofSystemTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/KnowledgeOfDlogTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/KnowledgeOfRepTests.cs
  WalletWasabi/Crypto/Extensions.cs
  WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Equation.cs
  WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Knowledge.cs
  WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Statement.cs
  WalletWasabi/Crypto/ZeroKnowledge/NonInteractive/Prover.cs
  WalletWasabi/Crypto/ZeroKnowledge/NonInteractive/Verifier.cs
  WalletWasabi/Crypto/ZeroKnowledge/Proof.cs
  WalletWasabi/Crypto/ZeroKnowledge/ProofSystem.cs
  WalletWasabi/Wabisabi/CredentialIssuer.cs
  WalletWasabi/Wabisabi/RegistrationRequest.cs
  WalletWasabi/Wabisabi/RegistrationResponse.cs
  WalletWasabi/Wabisabi/WabiSabiClient.cs
Labels: size/L

#4613 Refactoring: Split `TorMonitor` off `TorProcessManager`.
  WalletWasabi.Gui/Config.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi/Tor/TorMonitor.cs
  WalletWasabi/Tor/TorProcessManager.cs
Labels: size/L

#4640 Possible NREs in WasabiClient
  WalletWasabi.Tests/RegressionTests/Common.cs
  WalletWasabi/WebClients/Wasabi/WasabiClient.cs
Labels: size/M

#4645 Remove registry package
  WalletWasabi.Gui/packages.lock.json
  WalletWasabi.Packager/packages.lock.json
  WalletWasabi/WalletWasabi.csproj
  WalletWasabi/packages.lock.json
Labels: size/L
