Repository WalletWasabi/WalletWasabi, pull requests merged in 2020-04, with the labels that each got.

#3423 Fix enless loop when exiting during filter processing
  WalletWasabi.Gui/Controls/WalletExplorer/ClosedWalletViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/HardwareWallets/ConnectHardwareWalletViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletViewModel.cs
  WalletWasabi/Stores/IndexStore.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/S

#3422 Fixes duplicate key exception
  WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerViewModel.cs
  WalletWasabi.Gui/WalletWasabi.Gui.csproj
Labels: size/S

#3429 Fixes/wallet manager load multiple wallets
  WalletWasabi.Gui/Controls/WalletExplorer/ClosedWalletViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletViewModel.cs
Labels: size/S

#3430 Do not overwrite existing block
  WalletWasabi/Wallets/Wallet.cs
Labels: size/S

#3431 Update onion seeds for mainnet
  WalletWasabi/OnionSeeds/MainOnionSeeds.txt
Labels: size/XXL

#3289 Support opening wallet
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Gui/Rpc/JsonRpcRequestHandler.cs
  WalletWasabi.Gui/Rpc/WasabiJsonRpcService.cs
  WalletWasabi.Tests/UnitTests/Converters/OutPointAsTxoRefJsonConverterTests.cs
  WalletWasabi.Tests/UnitTests/Converters/TxoRef.cs
  WalletWasabi/JsonConverters/OutPointAsTxoRefJsonConverter.cs
Labels: size/M

#3432 Mark keys with dust as used
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
Labels: size/S

#3441 fix resizing of coinjoin page.
  WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabView.xaml
Labels: size/S

#3438 Fix Window oversize: Use a behaviour to bind window size.
  WalletWasabi.Gui/Behaviors/BindWindowSizeBehavior.cs
  WalletWasabi.Gui/MainWindow.xaml
  WalletWasabi.Gui/MainWindow.xaml.cs
  WalletWasabi.Gui/ViewModels/MainWindowViewModel.cs
Labels: size/M

#3473 Fix hardware loading the wrong hardware wallet
  WalletWasabi.Gui/Tabs/WalletManager/HardwareWallets/ConnectHardwareWalletViewModel.cs
Labels: size/XS

#3455 Fixes/dialogs not sizing
  WalletWasabi.Gui/WalletWasabi.Gui.csproj
  WalletWasabi.Gui/WasabiWindow.xaml
Labels: size/XS

#3484 Remove About Wallet Wasabi menu item.
  WalletWasabi.Gui/App.xaml
Labels: size/XS

#3474 Dump version to v1.1.11
  WalletWasabi.Backend/wwwroot/index.html
  WalletWasabi/Helpers/Constants.cs
Labels: size/S

#3451 Make Max Amount consistent
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
Labels: size/XS

#3457 Enable LWM button (Wallet Explorer)
  WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerViewModel.cs
Labels: size/XS

#3476 Edit settings node text
  WalletWasabi.Gui/Tabs/SettingsView.xaml
Labels: size/XS

#3489 Fix typo and shorten tooltip
  WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoView.xaml
Labels: size/XS

#3475 Update README image
  README.md
Labels: size/XS

#3502 Lower max coord fee from 0.7% to 0.3%
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
Labels: size/XS

#3234 Update NBitcoin
  WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
  WalletWasabi.Tests/RegressionTests/BackendTests.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/RegressionTests/DosTests.cs
  WalletWasabi.Tests/RegressionTests/WalletTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/SchnorrBlindingSignatureTests.cs
  WalletWasabi.Tests/UnitTests/CryptoTests.cs
  WalletWasabi.Tests/UnitTests/JsonConvertersTest/UnblindedSignatureTests.cs
  WalletWasabi/CoinJoin/Client/Clients/AliceClient.cs
  WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
  WalletWasabi/CoinJoin/Common/Crypto/SchnorrPubKey.cs
  WalletWasabi/CoinJoin/Common/Models/ActiveOutput.cs
  WalletWasabi/CoinJoin/Common/Models/ConnectionConfirmationResponse.cs
  WalletWasabi/CoinJoin/Common/Models/InputsResponse.cs
  WalletWasabi/CoinJoin/Common/Models/OutputRequest.cs
  WalletWasabi/CoinJoin/Coordinator/MixingLevels/MixingLevel.cs
  WalletWasabi/CoinJoin/Coordinator/MixingLevels/MixingLevelCollection.cs
  WalletWasabi/CoinJoin/Coordinator/Participants/Alice.cs
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
  WalletWasabi/Crypto/SchnorrBlindingSignature.cs
  WalletWasabi/Crypto/UnblindedSignature.cs
  WalletWasabi/Extensions/NBitcoinExtensions.cs
  WalletWasabi/JsonConverters/BigIntegerJsonConverter.cs
  WalletWasabi/JsonConverters/GolombRiceFilterJsonConverter.cs
  WalletWasabi/JsonConverters/UnblindedSignatureJsonConverter.cs
  WalletWasabi/WalletWasabi.csproj
Labels: priority, size/L

#3495 Order elements in some classes
  WalletWasabi.Gui/Controls/WalletExplorer/BuildTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/CoinViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs
Labels: size/L

#3493 Order elements in some classes
  WalletWasabi.Gui/Behaviors/BindSelectedTextBehavior.cs
  WalletWasabi.Gui/Behaviors/ClearPropertyOnLostFocusBehavior.cs
  WalletWasabi.Gui/Behaviors/FocusBehavior.cs
  WalletWasabi.Gui/Behaviors/PasteAddressOnClickBehavior.cs
  WalletWasabi.Gui/CommandLine/MixerCommand.cs
  WalletWasabi.Gui/CommandLine/Native.cs
  WalletWasabi.Gui/CommandLine/PasswordFinderCommand.cs
Labels: size/M

#3501 Refactor block downloading code
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
  WalletWasabi.Tests/IntegrationTests/P2pTests.cs
  WalletWasabi.Tests/RegressionTests/BuildTests.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi.Tests/RegressionTests/WalletTests.cs
  WalletWasabi/Wallets/CachedBlockProvider.cs
  WalletWasabi/Wallets/FileSystemBlockRepository.cs
  WalletWasabi/Wallets/IBlockProvider.cs
  WalletWasabi/Wallets/IRepository.cs
  WalletWasabi/Wallets/P2pBlockProvider.cs
  WalletWasabi/Wallets/Wallet.cs
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/XXL

#3505 Order elements in some classes
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
Labels: size/L

#3506 Order elements in some classes
  WalletWasabi.Gui/Controls/WalletExplorer/PinPadViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoViewModel.cs
Labels: size/L

#3517 Update NBitcoin to 5.0.28
  WalletWasabi.Tests/RegressionTests/BackendTests.cs
  WalletWasabi.Tests/RegressionTests/WalletTests.cs
  WalletWasabi/WalletWasabi.csproj
Labels: size/XS

#3515 Changed togglepassworbox component
  WalletWasabi.Gui/Controls/TogglePasswordBox.cs
  WalletWasabi.Gui/Controls/TogglePasswordBox.xaml
Labels: size/S

#3536 Order elements in some classes
  WalletWasabi.Gui/Rpc/JsonRpcRequestHandler.cs
  WalletWasabi.Gui/Rpc/JsonRpcResponse.cs
  WalletWasabi.Gui/Rpc/JsonRpcServer.cs
  WalletWasabi.Gui/Rpc/JsonRpcService.cs
  WalletWasabi.Gui/Rpc/WasabiJsonRpcService.cs
  WalletWasabi.Gui/Shell/Commands/DiskCommands.cs
  WalletWasabi.Gui/Shell/Commands/SystemCommands.cs
  WalletWasabi.Gui/Shell/Commands/ToolCommands.cs
  WalletWasabi.Gui/Shell/Commands/WalletCommands.cs
Labels: size/L

#3535 Order elements in some classes
  WalletWasabi.Gui/Helpers/ShellUtils.cs
  WalletWasabi.Gui/Models/JsonRpcServerConfiguration.cs
  WalletWasabi.Gui/Models/ShieldState.cs
  WalletWasabi.Gui/Models/StatusBarStatuses/Status.cs
  WalletWasabi.Gui/Models/StatusBarStatuses/StatusSet.cs
  WalletWasabi.Gui/Rpc/JsonRpcMethodAttribute.cs
  WalletWasabi.Gui/Rpc/JsonRpcMethodMetadata.cs
  WalletWasabi.Gui/Rpc/JsonRpcRequest.cs
Labels: size/M

#3530 Order elements in some classes
  WalletWasabi.Gui/Controls/BusyIndicator.cs
  WalletWasabi.Gui/Controls/EditableTextBlock.cs
  WalletWasabi.Gui/Controls/ExtendedListBox.cs
  WalletWasabi.Gui/Controls/ExtendedTextBox.cs
  WalletWasabi.Gui/Controls/MultiTextBox.cs
Labels: size/M

#3531 Order elements in some classes
  WalletWasabi.Gui/Controls/QrCode.cs
  WalletWasabi.Gui/Controls/Shields.cs
  WalletWasabi.Gui/Controls/SortingArrow.cs
Labels: size/L

#3532 Order elements in some classes
  WalletWasabi.Gui/Controls/TogglePasswordBox.cs
  WalletWasabi.Gui/Dialogs/CannotCloseDialogViewModel.cs
  WalletWasabi.Gui/Dialogs/TextInputDialogViewModel.cs
Labels: size/M

#3526 Add WalletName to Notifications
  WalletWasabi.Gui/Controls/WalletExplorer/ClosedWalletViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Gui/Helpers/NotificationHelpers.cs
Labels: size/L

#3491 Use expression body
  WalletWasabi.Gui/Behaviors/BindWindowSizeBehavior.cs
  WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletViewModel.cs
  WalletWasabi.Gui/ViewModels/MainWindowViewModel.cs
Labels: size/M

#3539 Add Hw Address icon.
  WalletWasabi.Gui/Icons/Icons.xaml
Labels: size/XS

#3546 Order elements in some classes
  WalletWasabi.Gui/Shell/MainMenu/FileMainMenuItems.cs
  WalletWasabi.Gui/Shell/MainMenu/HelpMainMenuItems.cs
  WalletWasabi.Gui/Shell/MainMenu/ToolsMainMenuItems.cs
  WalletWasabi.Gui/Tabs/AboutViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/GenerateWallets/GenerateWalletViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/RecoverWallets/RecoverWalletViewModel.cs
Labels: size/M

#3547 Order elements in some classes
  WalletWasabi.Gui/Tabs/SettingsViewModel.cs
  WalletWasabi.Gui/ViewModels/AddressViewModel.cs
  WalletWasabi.Gui/ViewModels/MainWindowViewModel.cs
Labels: size/L

#3548 Order elements in some classes
  WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
  WalletWasabi.Gui/ViewModels/ViewModelBase.cs
Labels: size/L

#3549 Order elements in some classes
  WalletWasabi.Gui/Config.cs
  WalletWasabi.Gui/UiConfig.cs
Labels: size/M

#3555 Update nbitcoin version
  WalletWasabi/WalletWasabi.csproj
Labels: size/XS

#3553 Log failing attempts to start rpc server
  WalletWasabi.Gui/Global.cs
Labels: size/S

#3088 Use CachedRpcClient
  WalletWasabi.Backend/InitConfigStartupTask.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi/BitcoinCore/CachedRpcClient.cs
  WalletWasabi/BitcoinCore/CoreNode.cs
  WalletWasabi/BitcoinCore/RpcClientBase.cs
Labels: size/L

#3533 Remove saving of the non-opened wallets on quit.
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/S

#3538 Add Let's Encrypt to BackendDeployment.md
  WalletWasabi.Documentation/BackendDeployment.md
Labels: size/S

#3558 Fix CI warnings
  WalletWasabi.Tests/UnitTests/BitcoinCore/RpcBasedTests.cs
Labels: size/XS

#3564 Order elements
  WalletWasabi.Tests/UnitTests/BitcoinCore/RpcBasedTests.cs
Labels: size/L

#3565 Order elements in some classes
  WalletWasabi.Tests/Global.cs
  WalletWasabi.Tests/RpcTests.cs
  WalletWasabi.Tests/UnitTests/Clients/MockTorHttpClient.cs
  WalletWasabi.Tests/UnitTests/Hwi/HwiProcessBridgeMock.cs
  WalletWasabi.Tests/UnitTests/ValidateMethodTests.cs
  WalletWasabi.Tests/XunitConfiguration/LiveServerTestsFixture.cs
  WalletWasabi.Tests/XunitConfiguration/RegTestFixture.cs
Labels: size/M

#3563 Order elements in some classes
  WalletWasabi.Packager/NSubsys/PeUtility.cs
  WalletWasabi.Tests/IntegrationTests/ExtPubKeyExplorerTests.cs
  WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
  WalletWasabi.Tests/IntegrationTests/TorTests.cs
  WalletWasabi.Tests/RegressionTests/BackendTests.cs
  WalletWasabi.Tests/RegressionTests/BuildTests.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/RegressionTests/DosTests.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi.Tests/RegressionTests/WalletTests.cs
Labels: size/L

#3560 remove persisting window size
  WalletWasabi.Gui/Behaviors/BindWindowSizeBehavior.cs
  WalletWasabi.Gui/MainWindow.xaml
  WalletWasabi.Gui/MainWindow.xaml.cs
  WalletWasabi.Gui/UiConfig.cs
  WalletWasabi.Gui/ViewModels/MainWindowViewModel.cs
Labels: size/L

#3550 Add password to Enqueue method
  WalletWasabi.Gui/Rpc/WasabiJsonRpcService.cs
Labels: size/XS

#3571 Order elements in some classes
  WalletWasabi/BitcoinCore/CachedRpcClient.cs
  WalletWasabi/CoinJoin/Coordinator/Coordinator.cs
  WalletWasabi/Extensions/ExceptionExtensions.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/DataEncodation/ECISet.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/DataEncodation/EightBitByteEncoder.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/DataEncodation/InputRecognition/ModeEncodeCheck.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/Positioning/Stencils/PatternStencilBase.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/Versions/VersionControl.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/Versions/VersionTable.cs
Labels: size/L

#3575 Fixes/update avalonia multiple fixes
  WalletWasabi.Gui/App.xaml
  WalletWasabi.Gui/WalletWasabi.Gui.csproj
Labels: size/S

#3573 Prevent 0 peers and increase max connections
  WalletWasabi.Gui/Global.cs
  WalletWasabi/Wallets/P2pBlockProvider.cs
Labels: size/S

#3559 Auto expand wallets when user selects them.
  WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerViewModel.cs
Labels: size/XS

#3577 Fix formatting
  WalletWasabi.Backend/InitConfigStartupTask.cs
  WalletWasabi.Tests/IntegrationTests/P2pTests.cs
  WalletWasabi.Tests/UnitTests/Converters/OutPointAsTxoRefJsonConverterTests.cs
  WalletWasabi.Tests/UnitTests/JsonConvertersTest/UnblindedSignatureTests.cs
  WalletWasabi.Tests/UnitTests/ListExtensionTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
  WalletWasabi/Crypto/SchnorrBlindingSignature.cs
  WalletWasabi/Wallets/CachedBlockProvider.cs
Labels: size/S

#3576 Order elements in some classes
  WalletWasabi.Gui/Controls/WalletExplorer/CoinListView.xaml.cs
  WalletWasabi/Bases/OctetSerializableBase.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/BitMatrix.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/Masking/Pattern0.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/Masking/Pattern1.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/Masking/Pattern2.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/Masking/Pattern3.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/Masking/Pattern4.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/Masking/Pattern5.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/Masking/Pattern6.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/Masking/Pattern7.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/QrEncoder.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/Versions/ErrorCorrectionBlock.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/Versions/ErrorCorrectionBlocks.cs
Labels: size/M

#3568 Better exception handling on SendTab
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
  WalletWasabi.Gui/Helpers/NotificationHelpers.cs
Labels: size/S

#3569 Add rule to remove unnecessary cast
  .editorconfig
  WalletWasabi/Wallets/Wallet.cs
Labels: size/XS

#3578 Fix exception warning while using rpc
  WalletWasabi.Gui/Rpc/WasabiJsonRpcService.cs
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/S

#3542 Backend filter index builder to use bitcoin knots 2
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Tests/RegressionTests/BackendTests.cs
  WalletWasabi.Tests/RegressionTests/WalletTests.cs
  WalletWasabi.Tests/UnitTests/BitcoinCore/IndexBuilderServiceTests.cs
  WalletWasabi.Tests/UnitTests/MockRpcClient.cs
  WalletWasabi/Blockchain/BlockFilters/History/ActionHistoryHelper.cs
  WalletWasabi/Blockchain/BlockFilters/History/ActionItem.cs
  WalletWasabi/Blockchain/BlockFilters/History/Operation.cs
  WalletWasabi/Blockchain/BlockFilters/IndexBuilderService.cs
  WalletWasabi/Blockchain/BlockFilters/SyncInfo.cs
  WalletWasabi/Blockchain/BlockFilters/UtxoEntry.cs
Labels: size/XL

#3584 Fix Wrong Filter
  WalletWasabi.Gui/Global.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/Stores/IndexStore.cs
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/M

#3585 Dump version to v1.1.11.1
  WalletWasabi.Backend/wwwroot/index.html
  WalletWasabi/Helpers/Constants.cs
Labels: size/S

#3598 Typo
  WalletWasabi.Gui/CommandLine/Daemon.cs
Labels: size/XS

#3594 Fix WalletManager error notification
  WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletViewModel.cs
Labels: size/XS

#3528 Pay with Payjoin (bip79)
  WalletWasabi.Gui/Controls/WalletExplorer/BuildTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
  WalletWasabi.Tests/UnitTests/Clients/MockTorHttpClient.cs
  WalletWasabi.Tests/UnitTests/Transactions/PayjoinTests.cs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
  WalletWasabi/Extensions/NBitcoinExtensions.cs
  WalletWasabi/Wallets/Wallet.cs
  WalletWasabi/WebClients/PayJoin/IPayjoinClient.cs
  WalletWasabi/WebClients/PayJoin/PayjoinClient.cs
  WalletWasabi/WebClients/PayJoin/PayjoinException.cs
  WalletWasabi/WebClients/PayJoin/PayjoinReceiverException.cs
  WalletWasabi/WebClients/PayJoin/PayjoinSenderException.cs
Labels: size/XXL

#3605 Fix typos
  WalletWasabi.Tests/UnitTests/Transactions/PayjoinTests.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/Stores/IndexStore.cs
Labels: size/S
