Repository WalletWasabi/WalletWasabi, pull requests merged in 2020-06, with the labels that each got.

#3683 [WEBSITE] Make presskit link the direct download
  WalletWasabi.Backend/wwwroot/index.html
Labels: size/XS

#3714 Enable StaticElementsMustAppearBeforeInstanceElements
  Settings.StyleCop
Labels: size/XS

#3694 Enable ElementMustNotBeOnSingleLine
  Settings.StyleCop
Labels: size/XS

#3722 Fix StatusRequestTestAsync [Naive]
  WalletWasabi.Backend/Controllers/BlockchainController.cs
  WalletWasabi.Tests/RegressionTests/BackendTests.cs
  WalletWasabi/Blockchain/BlockFilters/IndexBuilderService.cs
Labels: size/S

#3556 Add HW Wallet and Watch-only wallet icons.
  WalletWasabi.Gui/Controls/WalletExplorer/ClosedHardwareWalletViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/ClosedWalletViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/ClosedWatchOnlyWalletViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/HardwareWalletViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WatchOnlyWalletViewModel.cs
  WalletWasabi.Gui/Icons/Icons.xaml
Labels: size/L

#3724 Disable CodeMaid's Build Progress Tool Window
  CodeMaid.config
Labels: size/XS

#3730 Small SEO tweaks
  WalletWasabi.Backend/wwwroot/index.html
Labels: size/XS

#3741 Fix bug of banning clients in case of mempool dis-acceptance
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
Labels: size/XL

#3745 Add Onion-Location HTTP header
  WalletWasabi.Backend/wwwroot/index.html
Labels: size/XS

#3757 Prevent transaction store poisoning
  WalletWasabi.Gui/Global.cs
  WalletWasabi/Helpers/Constants.cs
Labels: size/S

#3762 Fix stylecop issue (Element must not be on single line)
  WalletWasabi/Blockchain/TransactionOutputs/CoinsView.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/DataEncodation/ECISet.cs
  WalletWasabi/Mono/OptionValueCollection.cs
  WalletWasabi/TorSocks5/Models/Messages/MethodSelectionResponse.cs
  WalletWasabi/TorSocks5/Models/Messages/UsernamePasswordResponse.cs
  WalletWasabi/TorSocks5/Models/Messages/VersionMethodRequest.cs
Labels: size/M

#3766 Enable SplitParametersMustStartOnLineAfterDeclaration
  Settings.StyleCop
Labels: size/XS

#3763 Fix typos
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
Labels: size/XS

#3761 Enable DeclarationKeywordsMustFollowOrder
  Settings.StyleCop
Labels: size/XS

#3759 [StyleCop] Enable ConstantsMustAppearBeforeFields
  Settings.StyleCop
Labels: size/XS

#3764 Return IsLikelyCoinJoin as part of gethistory
  WalletWasabi.Gui/Rpc/WasabiJsonRpcService.cs
  WalletWasabi/Blockchain/Transactions/TransactionHistoryBuilder.cs
  WalletWasabi/Blockchain/Transactions/TransactionSummary.cs
Labels: size/XS

#3756 Do not access `Global` via service locator in `MainWindowViewModel` c…
  WalletWasabi.Gui/Program.cs
  WalletWasabi.Gui/ViewModels/MainWindowViewModel.cs
Labels: size/M

#3769 ClientDeployment.md: fix small typo
  WalletWasabi.Documentation/ClientDeployment.md
Labels: size/XS

#3729 RPC optional parameters and batching capability
  WalletWasabi.Gui/Rpc/JsonRpcMethodMetadata.cs
  WalletWasabi.Gui/Rpc/JsonRpcRequest.cs
  WalletWasabi.Gui/Rpc/JsonRpcRequestHandler.cs
  WalletWasabi.Gui/Rpc/JsonRpcService.cs
  WalletWasabi.Tests/RpcTests.cs
Labels: size/M

#3770 .gitignore: add generated WindowsInstaller files
  .gitignore
Labels: size/XS

#3773 5.0.40
  WalletWasabi.Tests/UnitTests/ParserTests.cs
  WalletWasabi/WalletWasabi.csproj
Labels: size/XS

#3765 Place static elements before non-static elements
  WalletWasabi/Models/Height.cs
Labels: size/L

#3776 BitcoinStore: Improve DI
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Tests/IntegrationTests/P2pTests.cs
  WalletWasabi.Tests/RegressionTests/Common.cs
  WalletWasabi.Tests/UnitTests/BitcoinCore/P2pBasedTests.cs
  WalletWasabi/Stores/BitcoinStore.cs
Labels: size/M

#3780 Unify package prefix
  WalletWasabi.Packager/Program.cs
Labels: size/XS

#3778 Make locktime take effect in all cases
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
Labels: size/XS

#3790 Add missing .ConfigureAwait(false) to Global.cs
  WalletWasabi.Gui/Global.cs
Labels: size/S

#3702 Ensure single application instance
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Gui/Program.cs
  WalletWasabi.Tests/UnitTests/Clients/WasabiClientTests.cs
  WalletWasabi/Nito/AsyncEx/AsyncMutex.cs
  WalletWasabi/Services/SingleInstanceChecker.cs
Labels: size/L

#3786 Refactor CommandInterpreter class
  WalletWasabi.Gui/CommandLine/CommandInterpreter.cs
  WalletWasabi.Gui/CommandLine/MixerCommand.cs
  WalletWasabi.Gui/CommandLine/PasswordFinderCommand.cs
  WalletWasabi.Gui/Program.cs
  WalletWasabi.Tests/UnitTests/GUI/CommandInterpreterTest.cs
Labels: size/L

#3768 [Stylecop] Enable ParametersMustBeOnSameLineOrSeparateLines
  Settings.StyleCop
Labels: size/XS

#3792 Make wallet name argument required
  WalletWasabi.Gui/CommandLine/MixerCommand.cs
Labels: size/XS

#3797 Place constants before non constants
  WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/DataEncodation/ECISet.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/QRCodeConstantVariable.cs
  WalletWasabi/Helpers/Constants.cs
Labels: size/M

#3796 Put method parameters on new line
  WalletWasabi/Gma/QrCodeNet/Encoding/Versions/VersionTable.cs
Labels: size/L

#3798 [DI] Refactor `Global` a bit
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Gui/Program.cs
Labels: size/M

#3749 Update website description
  WalletWasabi.Backend/wwwroot/index.html
Labels: size/XS

#3802 Order static elements
  WalletWasabi.Backend/Controllers/BlockchainController.cs
  WalletWasabi.Tests/UnitTests/Transactions/AllTransactionStoreTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/DataEncodation/ECISet.cs
Labels: size/L

#3801 Put parameters on different lines
  WalletWasabi.Gui/Controls/EditableTextBlock.cs
  WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionBroadcasterViewModel.cs
Labels: size/L

#3807 codesing => codesign
  WalletWasabi.Packager/MacSignTools.cs
Labels: size/XS

#3800 [DI] Improve `BitcoinStore` class wrt dependency injection
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Tests/IntegrationTests/P2pTests.cs
  WalletWasabi.Tests/RegressionTests/Common.cs
  WalletWasabi.Tests/UnitTests/BitcoinCore/P2pBasedTests.cs
  WalletWasabi.Tests/UnitTests/Filters/IndexStoreTests.cs
  WalletWasabi/Stores/BitcoinStore.cs
  WalletWasabi/Stores/IndexStore.cs
Labels: size/M

#3814 Add Deterministic guide back
  WalletWasabi.Documentation/Guides/DeterministicBuildGuide.md
Labels: size/M

#3813 Add command line tool Tip to WasabikaCodex
  WalletWasabi.Documentation/WasabikaCodex.md
Labels: size/XS

#3817 Update to NBitcoin 5.0.43
  WalletWasabi/WalletWasabi.csproj
Labels: size/XS

#3812 Adjust down the new base denomination by 1sat in case collision
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
Labels: size/S

#3771 PeriodicRunner: Fix possible NullPointerException
  WalletWasabi/Bases/PeriodicRunner.cs
Labels: size/XS

#3818 Do not throw exception when switching to V4 backend
  WalletWasabi/Services/WasabiSynchronizer.cs
Labels: size/S

#3827 Place parameters on separate lines
  WalletWasabi.Gui/Behaviors/CommandBaseBehavior.cs
  WalletWasabi.Gui/Controls/ExtendedListBox.cs
  WalletWasabi.Tests/XunitConfiguration/RegTestFixture.cs
  WalletWasabi/Extensions/TextReaderExtensions.cs
Labels: size/S

#3826 Add ConfigureAwait(false) convention
  CONTRIBUTING.md
Labels: size/XS

#3824 Create officially supported OSs and devices document
  WalletWasabi.Documentation/WasabiCompatibility.md
Labels: size/M

#3822 Add NonWitness UTXO in PSBT for Trezor compat
  WalletWasabi.Tests/IntegrationTests/P2pTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/PayjoinTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
  WalletWasabi/Blockchain/Transactions/AllTransactionStore.cs
  WalletWasabi/Blockchain/Transactions/AllTransactionStoreMock.cs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
  WalletWasabi/Hwi/HwiClient.cs
  WalletWasabi/Hwi/Parsers/HwiParser.cs
  WalletWasabi/Stores/BitcoinStore.cs
  WalletWasabi/Stores/BitcoinStoreMock.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/L

#3828 Put first parameter on new line
  WalletWasabi.Backend/Config.cs
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Gui/Controls/WalletExplorer/ClosedWalletViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs
  WalletWasabi.Gui/Helpers/AvaloniaThreadingExtensions.cs
  WalletWasabi.Gui/Tabs/WalletManager/GenerateWallets/GenerateWalletSuccessViewModel.cs
  WalletWasabi.Tests/RpcTests.cs
  WalletWasabi.Tests/UnitTests/HashChainTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/AllTransactionStoreTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
  WalletWasabi/Blockchain/Transactions/SmartTransaction.cs
  WalletWasabi/Helpers/RuntimeParams.cs
  WalletWasabi/Mono/OptionValueCollection.cs
  WalletWasabi/Nito/AsyncEx/AsyncWaitQueueExtensions.cs
Labels: size/L

#3819 Fix Possible DoS Attack Vector
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRoundConfig.cs
Labels: size/M

#3842 fix ugly hack on slide lockscreen logo
  WalletWasabi.Gui/Controls/LockScreen/SlideLockScreenView.xaml
  WalletWasabi.Gui/Icons/Icons.xaml
Labels: size/S

#3839 update avalonia to 0.9.11
  WalletWasabi.Gui/WalletWasabi.Gui.csproj
Labels: size/XS

#3733 Crash Reporting system
  WalletWasabi.Gui/Behaviors/CloseWindowBehavior.cs
  WalletWasabi.Gui/CommandLine/CommandInterpreter.cs
  WalletWasabi.Gui/CommandLine/CrashReportCommand.cs
  WalletWasabi.Gui/CrashReport/CrashReportApp.xaml
  WalletWasabi.Gui/CrashReport/CrashReportApp.xaml.cs
  WalletWasabi.Gui/CrashReport/CrashReporter.cs
  WalletWasabi.Gui/CrashReport/ViewModels/CrashReportWindowViewModel.cs
  WalletWasabi.Gui/CrashReport/Views/CrashReportWindow.xaml
  WalletWasabi.Gui/CrashReport/Views/CrashReportWindow.xaml.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Gui/Program.cs
  WalletWasabi.Gui/Styles/Styles.xaml
  WalletWasabi.Tests/Helpers/StringNoWhiteSpaceEqualityComparer.cs
  WalletWasabi.Tests/UnitTests/GUI/CommandInterpreterTest.cs
  WalletWasabi.Tests/UnitTests/SerializableExceptionTests.cs
  WalletWasabi.Tests/UnitTests/StringNoWhiteSpaceEqualityComparerTests.cs
  WalletWasabi/Extensions/ExceptionExtensions.cs
  WalletWasabi/Models/SerializableException.cs
Labels: size/XL
