Repository WalletWasabi/WalletWasabi, pull requests merged in 2020-01, with the labels that each got.

#3015 WalletWasabi.Documentation: fix typo's in Guides
  WalletWasabi.Documentation/Guides/20190416HardwareWalletTestingGuide.md
  WalletWasabi.Documentation/Guides/20190617ContributionGame.md
Labels: size/XS

#3020 Update NuGets
  WalletWasabi.Backend/WalletWasabi.Backend.csproj
  WalletWasabi.Tests/WalletWasabi.Tests.csproj
  WalletWasabi/WalletWasabi.csproj
Labels: size/XS

#3021 Increase open files limit
  WalletWasabi.Documentation/BackendDeployment.md
Labels: size/S

#2370 Refactor Project Management
  WalletWasabi.Documentation/WasabikaCodex.md
Labels: feature/enhancement

#3026 Add Quality Gate
  WalletWasabi.QualityGate/Program.cs
  WalletWasabi.QualityGate/WalletWasabi.QualityGate.csproj
  WalletWasabi.sln
  azure-pipelines-quality.yml
Labels: size/M

#3027 Add Quality Gate
  WalletWasabi.QualityGate/Program.cs
  WalletWasabi.QualityGate/PullRequestSize.cs
  WalletWasabi.QualityGate/WalletWasabi.QualityGate.csproj
  WalletWasabi.sln
  azure-pipelines-quality.yml
Labels: size/XS

#3028 Enable ElementsMustAppearInTheCorrectOrder
  Settings.StyleCop
Labels: size/XS

#3030 Merge pull request #3030 from nopara73/revertchanges
  WalletWasabi.QualityGate/PullRequestSize.cs
  WalletWasabi.QualityGate/WalletWasabi.QualityGate.csproj
  azure-pipelines-quality.yml
Labels: size/M

#3031 Remove leftover solution trash
  WalletWasabi.sln
Labels: size/S

#3022 Use using statement for IDisposable http objects
  WalletWasabi.Tests/IntegrationTests/ExternalApiTests.cs
  WalletWasabi/WebClients/BlockchainInfo/BlockchainInfoExchangeRateProvider.cs
  WalletWasabi/WebClients/Coinbase/CoinbaseExchangeRateProvider.cs
  WalletWasabi/WebClients/ExchangeRateProviders.cs
  WalletWasabi/WebClients/Gemini/GeminiExchangeRateProvider.cs
  WalletWasabi/WebClients/ItBit/ItBitExchangeRateProvider.cs
  WalletWasabi/WebClients/SmartBit/SmartBitClient.cs
Labels: size/S

#3034 Catch all JsonException when reading json config files
  WalletWasabi/Bases/ConfigBase.cs
Labels: size/XS

#3035 Fetch Coordinator Address from ExtPubKey
  WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
  WalletWasabi.Documentation/BackendDeployment.md
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRoundConfig.cs
  WalletWasabi/Helpers/Constants.cs
Labels: size/M
