Repository WalletWasabi/WalletWasabi, pull requests merged in 2020-11, with the labels that each got.

#4653 Remove Locator and pass dependencies via constructor in PinLockScreenViewModel
  WalletWasabi.Gui/Controls/LockScreen/PinLockScreenViewModel.cs
  WalletWasabi.Gui/ViewModels/MainWindowViewModel.cs
Labels: size/S

#4646 Remove the canClose property
  WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs
  WalletWasabi.Gui/MainWindow.xaml.cs
  WalletWasabi.Gui/ViewModels/MainWindowViewModel.cs
Labels: size/S

#4647 Prevent building CJ with fee lower than minMemPoolFee
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/UnitTests/BitcoinCore/RpcBasedTests.cs
  WalletWasabi.Tests/UnitTests/CoordinatorRoundTests.cs
  WalletWasabi.Tests/UnitTests/MockRpcClient.cs
  WalletWasabi/BitcoinCore/Rpc/CachedRpcClient.cs
  WalletWasabi/BitcoinCore/Rpc/IRPCClient.cs
  WalletWasabi/BitcoinCore/Rpc/RpcClientBase.cs
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
  WalletWasabi/Extensions/NBitcoinExtensions.cs
  WalletWasabi/Extensions/RPCClientExtensions.cs
Labels: size/L

#4650 [Trivial] Fix formatting
  WalletWasabi.Fluent/Controls/ContentArea.axaml.cs
  WalletWasabi.Fluent/Styles/OptionButton.xaml
  WalletWasabi.Fluent/ViewModels/HomePageViewModel.cs
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
  WalletWasabi.Tests/UnitTests/Crypto/ProofSystemTests.cs
  WalletWasabi.Tests/UnitTests/Wabisabi/CredentialTests.cs
  WalletWasabi/Crypto/Extensions.cs
  WalletWasabi/Wabisabi/CredentialIssuer.cs
  WalletWasabi/Wabisabi/IssuanceRequest.cs
  WalletWasabi/Wabisabi/RegistrationRequest.cs
  WalletWasabi/Wabisabi/RegistrationValidationData.cs
  WalletWasabi/Wabisabi/WabiSabiClient.cs
  WalletWasabi/Wabisabi/WabiSabiException.cs
Labels: size/M

#4649 [Trivial] Fix typos
  WalletWasabi.Fluent/Controls/ContentArea.axaml
  WalletWasabi.Fluent/Views/AddWalletPageView.axaml
  WalletWasabi.Gui/Global.cs
Labels: size/S

#4660 Allow nullability for equality
  WalletWasabi.Gui/Models/Sorting/SortingPreference.cs
  WalletWasabi.Gui/Models/StatusBarStatuses/Status.cs
  WalletWasabi/BitcoinCore/Monitoring/RpcStatus.cs
  WalletWasabi/Blockchain/Analysis/Clustering/Cluster.cs
  WalletWasabi/Blockchain/Analysis/Clustering/SmartLabel.cs
  WalletWasabi/Blockchain/Analysis/FeesEstimation/AllFeeEstimate.cs
  WalletWasabi/Blockchain/Keys/HdPubKey.cs
  WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
  WalletWasabi/Blockchain/Transactions/SmartTransaction.cs
  WalletWasabi/CoinJoin/Common/Crypto/SchnorrKey.cs
  WalletWasabi/CoinJoin/Common/Crypto/SchnorrPubKey.cs
  WalletWasabi/CoinJoin/Coordinator/MixingLevels/MixingLevel.cs
  WalletWasabi/Crypto/Mac.cs
  WalletWasabi/Helpers/ByteHelpers.cs
  WalletWasabi/Hwi/Models/HwiOption.cs
  WalletWasabi/Models/UpdateStatus.cs
  WalletWasabi/Tor/Http/Models/HttpProtocol.cs
  WalletWasabi/Tor/Socks5/Models/Bases/ByteArraySerializableBase.cs
  WalletWasabi/Tor/Socks5/Models/Bases/OctetSerializableBase.cs
Labels: size/L

#4651 Fix nullable warnings
  WalletWasabi.Fluent.Desktop/Program.cs
Labels: size/XS

#4652 Remove static keyword
  WalletWasabi.Gui/Global.cs
Labels: size/XS

#4654 [Tor] Deserialize Byte Arrays from Constructors
  WalletWasabi/Tor/Socks5/Models/Bases/ByteArraySerializableBase.cs
  WalletWasabi/Tor/Socks5/Models/Fields/ByteArrayFields/AddrField.cs
  WalletWasabi/Tor/Socks5/Models/Fields/ByteArrayFields/MethodsField.cs
  WalletWasabi/Tor/Socks5/Models/Fields/ByteArrayFields/PasswdField.cs
  WalletWasabi/Tor/Socks5/Models/Fields/ByteArrayFields/PortField.cs
  WalletWasabi/Tor/Socks5/Models/Fields/ByteArrayFields/UNameField.cs
  WalletWasabi/Tor/Socks5/Models/Interfaces/IByteArraySerializable.cs
  WalletWasabi/Tor/Socks5/Models/Messages/MethodSelectionResponse.cs
  WalletWasabi/Tor/Socks5/Models/Messages/TorSocks5Request.cs
  WalletWasabi/Tor/Socks5/Models/Messages/TorSocks5Response.cs
  WalletWasabi/Tor/Socks5/Models/Messages/UsernamePasswordRequest.cs
  WalletWasabi/Tor/Socks5/Models/Messages/UsernamePasswordResponse.cs
  WalletWasabi/Tor/Socks5/Models/Messages/VersionMethodRequest.cs
  WalletWasabi/Tor/Socks5/TorSocks5Client.cs
Labels: size/L

#4570 [Fluent] Recovery words prototype
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent/App.xaml
  WalletWasabi.Fluent/Controls/ConcatenatingWrapPanel.cs
  WalletWasabi.Fluent/Controls/TagsBox.xaml
  WalletWasabi.Fluent/Controls/TagsBox.xaml.cs
  WalletWasabi.Fluent/Styles/Themes/BaseDark.xaml
  WalletWasabi.Fluent/Styles/Themes/BaseLight.xaml
  WalletWasabi.Fluent/ViewModels/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/RecoverWalletPageViewModel.cs
  WalletWasabi.Fluent/Views/AddWalletPageView.axaml
  WalletWasabi.Fluent/Views/RecoveryPageView.axaml
  WalletWasabi.Fluent/Views/RecoveryPageView.axaml.cs
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
Labels: size/XL

#4639 API code documentation
  WalletWasabi.Tests/UnitTests/Wabisabi/CredentialTests.cs
  WalletWasabi/Wabisabi/CredentialIssuer.cs
  WalletWasabi/Wabisabi/CredentialPool.cs
  WalletWasabi/Wabisabi/IssuanceRequest.cs
  WalletWasabi/Wabisabi/IssuanceValidationData.cs
  WalletWasabi/Wabisabi/RegistrationRequest.cs
  WalletWasabi/Wabisabi/RegistrationRequestMessage.cs
  WalletWasabi/Wabisabi/RegistrationResponse.cs
  WalletWasabi/Wabisabi/RegistrationResponseMessage.cs
  WalletWasabi/Wabisabi/RegistrationValidationData.cs
  WalletWasabi/Wabisabi/WabiSabiClient.cs
Labels: size/L

#4571 [Fluent] Create Wallet
  WalletWasabi.Fluent/App.xaml.cs
  WalletWasabi.Fluent/Behaviors/AttachedToVisualTreeBehavior.cs
  WalletWasabi.Fluent/Behaviors/AutoBringIntoViewExtension.cs
  WalletWasabi.Fluent/Behaviors/CheckMarkVisibilityBehavior.cs
  WalletWasabi.Fluent/Behaviors/DisposingBehavior.cs
  WalletWasabi.Fluent/Behaviors/FocusFirstTextBoxInItemsControlBehavior.cs
  WalletWasabi.Fluent/Behaviors/FocusNextItemBehavior.cs
  WalletWasabi.Fluent/Behaviors/FocusOnAttachedBehavior.cs
  WalletWasabi.Fluent/Behaviors/SplitViewAutoBehavior.cs
  WalletWasabi.Fluent/Converters/BoolOpacityConverters.cs
  WalletWasabi.Fluent/Icons/Icons.xaml
  WalletWasabi.Fluent/Styles/OptionButton.xaml
  WalletWasabi.Fluent/Styles/Styles.xaml
  WalletWasabi.Fluent/ViewModels/AddWallet/ConfirmRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoveryWordViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/DialogViewModelBaseOfTResult.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/EnterPasswordViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/TestDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBarItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/RoutableViewModel.cs
  WalletWasabi.Fluent/ViewModels/SettingsPageViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/ConfirmRecoveryWordsView.axaml
  WalletWasabi.Fluent/Views/AddWallet/ConfirmRecoveryWordsView.axaml.cs
  WalletWasabi.Fluent/Views/AddWallet/RecoveryWordsView.axaml
  WalletWasabi.Fluent/Views/AddWallet/RecoveryWordsView.axaml.cs
  WalletWasabi.Fluent/Views/AddWalletPageView.axaml
  WalletWasabi.Fluent/Views/Dialogs/EnterPasswordView.axaml
  WalletWasabi.Fluent/Views/Dialogs/EnterPasswordView.axaml.cs
  WalletWasabi.Fluent/Views/MainView.axaml
  WalletWasabi.Fluent/Views/MainWindow.axaml
  WalletWasabi.Fluent/Views/SettingsPageView.axaml
  WalletWasabi/Userfacing/PasswordHelper.cs
Labels: size/XXL

#4662 Fluent validate wallet name as user types
  WalletWasabi.Fluent/ViewModels/AddWalletPageViewModel.cs
  WalletWasabi/Blockchain/Keys/WalletGenerator.cs
Labels: size/M

#4661 LiveServerTests: Use factory method to instantiate TorHttpClient.
  WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
Labels: size/S

#4665 TorSocks5Client: Add missing cancellation token + some docs.
  WalletWasabi/Tor/Socks5/TorSocks5Client.cs
Labels: size/M

#4663 [trivial] Remove superfluous command.
  WalletWasabi/Tor/Http/TorHttpClient.cs
Labels: size/XS

#4664 Move SSL authentication from TorHttpClient to TorSocks5Client.
  WalletWasabi/Tor/Http/TorHttpClient.cs
  WalletWasabi/Tor/Socks5/TorSocks5Client.cs
Labels: size/S

#4641 [WabiSabi] Review III
  WalletWasabi.Tests/UnitTests/Crypto/ProofSystemHelpers.cs
  WalletWasabi.Tests/UnitTests/Crypto/ProofSystemTests.cs
  WalletWasabi/Crypto/CoordinatorParameters.cs
  WalletWasabi/Crypto/CoordinatorSecretKey.cs
  WalletWasabi/Crypto/CryptoGuards.cs
  WalletWasabi/Crypto/GroupElementVector.cs
  WalletWasabi/Crypto/Mac.cs
  WalletWasabi/Crypto/ScalarVector.cs
  WalletWasabi/Crypto/ZeroKnowledge/Credential.cs
  WalletWasabi/Crypto/ZeroKnowledge/CredentialPresentation.cs
  WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Equation.cs
  WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Knowledge.cs
  WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Statement.cs
  WalletWasabi/Crypto/ZeroKnowledge/Proof.cs
  WalletWasabi/Crypto/ZeroKnowledge/ProofSystem.cs
  WalletWasabi/Crypto/ZeroKnowledge/SyntheticSecretNonceProvider.cs
  WalletWasabi/Crypto/ZeroKnowledge/Transcript.cs
  WalletWasabi/Helpers/Guard.cs
  WalletWasabi/Wabisabi/CredentialIssuer.cs
  WalletWasabi/Wabisabi/WabiSabiClient.cs
Labels: size/L

#4672 Fix typos
  WalletWasabi.Fluent/Views/AddWalletPageView.axaml
  WalletWasabi/Extensions/NBitcoinExtensions.cs
  WalletWasabi/Wabisabi/CredentialIssuer.cs
  WalletWasabi/Wabisabi/IssuanceRequest.cs
  WalletWasabi/Wabisabi/RegistrationRequestMessage.cs
  WalletWasabi/Wabisabi/WabiSabiClient.cs
Labels: size/S

#4668 Refactor SmartCoin
  WalletWasabi.Gui/Controls/WalletExplorer/CoinViewModel.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Gui/Rpc/WasabiJsonRpcService.cs
  WalletWasabi.Tests/Common.cs
  WalletWasabi.Tests/RegressionTests/BuildTests.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi.Tests/RegressionTests/WalletTests.cs
  WalletWasabi.Tests/UnitTests/SmartCoinTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/AllTransactionStoreTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/OperationMergerTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/PayjoinTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionStoreTests.cs
  WalletWasabi/Blockchain/Analysis/Clustering/Cluster.cs
  WalletWasabi/Blockchain/TransactionBuilding/BuildTransactionResult.cs
  WalletWasabi/Blockchain/TransactionBuilding/SmartCoinSelector.cs
  WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs
  WalletWasabi/Blockchain/TransactionOutputs/CoinsView.cs
  WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
  WalletWasabi/Blockchain/Transactions/TransactionHistoryBuilder.cs
  WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
  WalletWasabi/CoinJoin/Client/Rounds/ClientState.cs
  WalletWasabi/Extensions/NBitcoinExtensions.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/XXL

#4677 Fix Tor identity bug
  WalletWasabi/Tor/Socks5/TorSocks5Client.cs
Labels: size/XS

#4675 WasabiSynchronizer: Rename `Cancel` -> `StopCts` & make API contract …
  WalletWasabi/Services/WasabiSynchronizer.cs
Labels: size/M

#4679 Lazy coins
  WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
Labels: size/M

#4623 [Fluent] Navigation state
  WalletWasabi.Fluent/Behaviors/FocusOnAttachedBehavior.cs
  WalletWasabi.Fluent/Controls/ContentArea.axaml
  WalletWasabi.Fluent/Controls/ContentArea.axaml.cs
  WalletWasabi.Fluent/Controls/Dialog.xaml
  WalletWasabi.Fluent/Controls/Dialog.xaml.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/ConfirmRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/ClosedHardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/ClosedWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/ClosedWatchOnlyWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/DialogScreenViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/DialogViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/DialogViewModelBaseOfTResult.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/TestDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/HardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/HomePageViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBarItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavigationStateViewModel.cs
  WalletWasabi.Fluent/ViewModels/RecoverWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/RoutableViewModel.cs
  WalletWasabi.Fluent/ViewModels/SettingsPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
  WalletWasabi.Fluent/ViewModels/WalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/WalletViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/WatchOnlyWalletViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/ConfirmRecoveryWordsView.axaml
  WalletWasabi.Fluent/Views/AddWallet/RecoveryWordsView.axaml
  WalletWasabi.Fluent/Views/AddWalletPageView.axaml
  WalletWasabi.Fluent/Views/Dialogs/EnterPasswordView.axaml
  WalletWasabi.Fluent/Views/Dialogs/TestDialogView.axaml
  WalletWasabi.Fluent/Views/MainView.axaml
  WalletWasabi.Fluent/Views/RecoveryPageView.axaml
  WalletWasabi.Fluent/Views/SettingsPageView.axaml
Labels: size/XL

#4680 SmartTransaction and HdPubKey to know all the SmartCoins it is connected to
  WalletWasabi/Blockchain/Keys/HdPubKey.cs
  WalletWasabi/Blockchain/TransactionBuilding/BuildTransactionResult.cs
  WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs
  WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
  WalletWasabi/Blockchain/Transactions/SmartTransaction.cs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
Labels: size/M

#4683 Remove ITorHttpClient.SendAndRetryAsync.
  WalletWasabi.Tests/RegressionTests/BackendTests.cs
  WalletWasabi/Tor/Http/Interfaces/ITorHttpClient.cs
  WalletWasabi/WebClients/Wasabi/WasabiClient.cs
Labels: size/L

#4682 Fix typos + trivial cleanup
  WalletWasabi.Fluent/ViewModels/Dialogs/DialogViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/RecoveryWordsView.axaml
  WalletWasabi/Crypto/ZeroKnowledge/Credential.cs
  WalletWasabi/Crypto/ZeroKnowledge/CredentialPresentation.cs
Labels: size/S

#4659 BitcoindRpcProcessBridge: ReasonableCoreShutdownTimeout increased.
  WalletWasabi/BitcoinCore/Processes/BitcoindRpcProcessBridge.cs
  WalletWasabi/Microservices/ProcessAsync.cs
Labels: size/M

#4671 [WabiSabi] Serialization messages
  WalletWasabi.Tests/UnitTests/Wabisabi/SerializationTests.cs
  WalletWasabi/Crypto/GroupElementVector.cs
  WalletWasabi/Crypto/Mac.cs
  WalletWasabi/Crypto/ScalarVector.cs
  WalletWasabi/Crypto/ZeroKnowledge/CredentialPresentation.cs
  WalletWasabi/Crypto/ZeroKnowledge/Proof.cs
  WalletWasabi/Wabisabi/IssuanceRequest.cs
  WalletWasabi/Wabisabi/RegistrationRequestMessage.cs
  WalletWasabi/Wabisabi/RegistrationValidationData.cs
  WalletWasabi/Wabisabi/Serialization/GroupElementJsonConverter.cs
  WalletWasabi/Wabisabi/Serialization/ScalarJsonConverter.cs
Labels: size/L

#4692 Slim down ITorHttpClient.
  WalletWasabi.Tests/UnitTests/Transactions/PayjoinTests.cs
  WalletWasabi/Tor/Http/Interfaces/ITorHttpClient.cs
  WalletWasabi/Tor/Http/TorHttpClient.cs
  WalletWasabi/WebClients/PayJoin/PayjoinClient.cs
Labels: size/M

#4676 Add IsTrimable() to string extension
  WalletWasabi.Fluent/ViewModels/AddWalletPageViewModel.cs
  WalletWasabi/Extensions/StringExtensions.cs
  WalletWasabi/Userfacing/PasswordHelper.cs
Labels: size/S

#4681 Remove readonly field naming rule
  .editorconfig
  WalletWasabi.Backend/Controllers/SoftwareController.cs
  WalletWasabi.Backend/Middlewares/HeadMethodMiddleware.cs
  WalletWasabi.Gui/Controls/LockScreen/SlideLockScreenViewModel.cs
  WalletWasabi.Packager/NSubsys/PeUtility.cs
  WalletWasabi/BitcoinCore/Processes/BitcoindRpcProcessBridge.cs
  WalletWasabi/Crypto/StrobeProtocol/Strobe.cs
  WalletWasabi/Crypto/ZeroKnowledge/SyntheticSecretNonceProvider.cs
  WalletWasabi/Mono/OptionSet.cs
  WalletWasabi/Nito/AsyncEx/AsyncLock.cs
  WalletWasabi/Nito/AsyncEx/AwaitableDisposable.cs
  WalletWasabi/Nito/AsyncEx/DefaultAsyncWaitQueue.cs
  WalletWasabi/Nito/Collections/CollectionHelpers.cs
  WalletWasabi/Nito/Collections/Deque.cs
  WalletWasabi/Nito/Disposables/Internals/BoundAction.cs
  WalletWasabi/Nito/Disposables/SingleDisposable.cs
  WalletWasabi/Services/SingleInstanceChecker.cs
  WalletWasabi/Services/Terminate/TerminateService.cs
  WalletWasabi/WebClients/ExchangeRateProviders.cs
Labels: size/L

#4688 [Fluent] Use common buttons for EnterPasswordView
  WalletWasabi.Fluent/ViewModels/Dialogs/EnterPasswordViewModel.cs
  WalletWasabi.Fluent/Views/Dialogs/EnterPasswordView.axaml
Labels: size/M

#4667 [Fluent] Cleanup tasks
  WalletWasabi.Fluent/Controls/ContentArea.axaml
  WalletWasabi.Fluent/Converters/NavBarIconConverter.cs
  WalletWasabi.Fluent/Styles/ActionButton.xaml
  WalletWasabi.Fluent/Styles/Checkmark.xaml
  WalletWasabi.Fluent/Styles/FontSizes.xaml
  WalletWasabi.Fluent/Styles/InvisibleButton.xaml
  WalletWasabi.Fluent/Styles/Label.xaml
  WalletWasabi.Fluent/Styles/OptionButton.xaml
  WalletWasabi.Fluent/Styles/PlainButton.xaml
  WalletWasabi.Fluent/Styles/SplitView.xaml
  WalletWasabi.Fluent/Styles/Styles.xaml
  WalletWasabi.Fluent/Styles/TextBox.xaml
  WalletWasabi.Fluent/Styles/Themes/Base.xaml
  WalletWasabi.Fluent/ViewModels/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/CreateWallet/ConfirmRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/CreateWallet/RecoveryWordViewModel.cs
  WalletWasabi.Fluent/ViewModels/CreateWallet/RecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/DialogScreenViewModel.cs
  WalletWasabi.Fluent/ViewModels/HomePageViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/RecoverWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/SettingsPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/ClosedHardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/ClosedWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/ClosedWatchOnlyWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/HardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WatchOnlyWalletViewModel.cs
  WalletWasabi.Fluent/Views/AddWalletPageView.axaml
  WalletWasabi.Fluent/Views/CreateWallet/ConfirmRecoveryWordsView.axaml
  WalletWasabi.Fluent/Views/CreateWallet/ConfirmRecoveryWordsView.axaml.cs
  WalletWasabi.Fluent/Views/CreateWallet/RecoveryWordsView.axaml
  WalletWasabi.Fluent/Views/CreateWallet/RecoveryWordsView.axaml.cs
  WalletWasabi.Fluent/Views/Dialogs/EnterPasswordView.axaml
  WalletWasabi.Fluent/Views/MainView.axaml
  WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
  WalletWasabi.Fluent/Views/NavBar/NavBar.axaml.cs
  WalletWasabi.Fluent/Views/SettingsPageView.axaml
Labels: size/XL

#4648 Refactor TorMonitor.
  WalletWasabi.Gui/Global.cs
  WalletWasabi/Bases/PeriodicRunner.cs
  WalletWasabi/Tor/TorMonitor.cs
  WalletWasabi/Tor/TorProcessManager.cs
Labels: size/L

#4693 Remove FromByte from OctetSerializableBase.
  WalletWasabi/Tor/Socks5/Models/Bases/OctetSerializableBase.cs
  WalletWasabi/Tor/Socks5/Models/Fields/OctetFields/CmdField.cs
  WalletWasabi/Tor/Socks5/Models/Fields/OctetFields/PLenField.cs
  WalletWasabi/Tor/Socks5/Models/Fields/OctetFields/RepField.cs
  WalletWasabi/Tor/Socks5/Models/Fields/OctetFields/RsvField.cs
  WalletWasabi/Tor/Socks5/Models/Fields/OctetFields/ULenField.cs
  WalletWasabi/Tor/Socks5/Models/Interfaces/IByteSerializable.cs
  WalletWasabi/Tor/Socks5/Models/Messages/TorSocks5Request.cs
  WalletWasabi/Tor/Socks5/Models/Messages/TorSocks5Response.cs
  WalletWasabi/Tor/Socks5/Models/Messages/UsernamePasswordRequest.cs
Labels: size/L

#4695 TorSocks5Client: Stream encapsulation
  WalletWasabi/Tor/Http/TorHttpClient.cs
  WalletWasabi/Tor/Socks5/TorSocks5Client.cs
Labels: size/S

#4691 Trivial refactoring
  WalletWasabi.Fluent/Behaviors/CheckMarkVisibilityBehavior.cs
  WalletWasabi.Fluent/Controls/TagsBox.xaml.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Tests/UnitTests/CoordinatorRoundTests.cs
  WalletWasabi.Tests/UnitTests/Wabisabi/CredentialTests.cs
  WalletWasabi.Tests/UnitTests/Wabisabi/SerializationTests.cs
  WalletWasabi/Userfacing/PasswordHelper.cs
  WalletWasabi/Wabisabi/IssuanceRequest.cs
  WalletWasabi/Wabisabi/RegistrationRequestMessage.cs
  WalletWasabi/Wabisabi/RegistrationValidationData.cs
  WalletWasabi/Wabisabi/WabiSabiClient.cs
Labels: size/XL

#4696 [trivial] Clean up MockTorHttpClient.
  WalletWasabi.Tests/UnitTests/Clients/MockTorHttpClient.cs
Labels: size/XS

#4699 Update footer link on website
  WalletWasabi.Backend/wwwroot/index.html
Labels: size/XS

#4705 Remove .shellcheckrc file
  .shellcheckrc
Labels: size/XS

#4666 [Fluent] Wallet recovery workflow
  WalletWasabi.Fluent.Desktop/Program.cs
  WalletWasabi.Fluent/App.xaml.cs
  WalletWasabi.Fluent/Behaviors/FocusBehavior.cs
  WalletWasabi.Fluent/Behaviors/FocusNextItemBehavior.cs
  WalletWasabi.Fluent/Controls/ConcatenatingWrapPanel.cs
  WalletWasabi.Fluent/Controls/ContentArea.axaml
  WalletWasabi.Fluent/Controls/TagsBox.xaml
  WalletWasabi.Fluent/Controls/TagsBox.xaml.cs
  WalletWasabi.Fluent/Converters/NavBarIconConverter.cs
  WalletWasabi.Fluent/Helpers/PlatformExtension.cs
  WalletWasabi.Fluent/Icons/Icons.xaml
  WalletWasabi.Fluent/ScreenViewLocator.cs
  WalletWasabi.Fluent/ViewLocator.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/ConfirmRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoveryWordViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/AdvancedRecoveryOptionsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/EnterPasswordViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavigationStateViewModel.cs
  WalletWasabi.Fluent/ViewModels/RecoverWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/RoutableViewModel.cs
  WalletWasabi.Fluent/ViewModels/SettingsPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModelBase.cs
  WalletWasabi.Fluent/Views/AddWallet/ConfirmRecoveryWordsView.axaml
  WalletWasabi.Fluent/Views/AddWallet/ConfirmRecoveryWordsView.axaml.cs
  WalletWasabi.Fluent/Views/AddWallet/RecoverWalletView.axaml
  WalletWasabi.Fluent/Views/AddWallet/RecoverWalletView.axaml.cs
  WalletWasabi.Fluent/Views/AddWallet/RecoveryWordsView.axaml
  WalletWasabi.Fluent/Views/AddWallet/RecoveryWordsView.axaml.cs
  WalletWasabi.Fluent/Views/Dialogs/AdvancedRecoveryOptionsView.axaml
  WalletWasabi.Fluent/Views/Dialogs/AdvancedRecoveryOptionsView.axaml.cs
  WalletWasabi.Fluent/Views/RecoveryPageView.axaml
  WalletWasabi.Fluent/Views/RecoveryPageView.axaml.cs
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
Labels: size/XXL

#4700 Correct methods' name
  WalletWasabi.Fluent/ViewModels/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/EnterPasswordViewModel.cs
  WalletWasabi.Gui/CommandLine/Daemon.cs
  WalletWasabi.Gui/Tabs/WalletManager/GenerateWallets/GenerateWalletViewModel.cs
  WalletWasabi.Tests/UnitTests/Userfacing/PasswordTests.cs
  WalletWasabi/Extensions/StringExtensions.cs
  WalletWasabi/Userfacing/PasswordHelper.cs
Labels: size/S

#4698 Add IRelativeHttpClient.
  WalletWasabi/Tor/Http/ClearnetHttpClient.cs
  WalletWasabi/Tor/Http/IRelativeHttpClient.cs
  WalletWasabi/Tor/Http/Interfaces/ITorHttpClient.cs
  WalletWasabi/Tor/Http/TorHttpClient.cs
Labels: size/M

#4713 Revert "Add IRelativeHttpClient."
  WalletWasabi/Tor/Http/ClearnetHttpClient.cs
  WalletWasabi/Tor/Http/IRelativeHttpClient.cs
  WalletWasabi/Tor/Http/Interfaces/ITorHttpClient.cs
  WalletWasabi/Tor/Http/TorHttpClient.cs
Labels: size/M

#4709 [trivial] Remove unused TorException class.
  WalletWasabi/Tor/Exceptions/TorException.cs
Labels: size/S

#4711 [trivial] AsyncLock: Fix nullability issue.
  WalletWasabi/Nito/AsyncEx/AsyncLock.cs
Labels: size/XS

#4708 [Trivial] Fix typo
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/RecoverWalletView.axaml
Labels: size/XS

#4712 [Fluent] Simply RecoverWalletViewModel & AdvancedRecoveryOptionsViewModel
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/AdvancedRecoveryOptionsViewModel.cs
Labels: size/M

#4690 [Fluent] Make dialogs routable and use dialog screen for EnterPasswordView
  WalletWasabi.Fluent/ViewModels/AddWallet/ConfirmRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/AdvancedRecoveryOptionsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/DialogViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/DialogViewModelBaseOfTResult.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/EnterPasswordViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/TestDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/HomePageViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavigationStateViewModel.cs
  WalletWasabi.Fluent/ViewModels/RoutableViewModel.cs
  WalletWasabi.Fluent/ViewModels/SettingsPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModelBase.cs
  WalletWasabi.Fluent/Views/AddWalletPageView.axaml
  WalletWasabi.Fluent/Views/Dialogs/AdvancedRecoveryOptionsView.axaml
  WalletWasabi.Fluent/Views/Dialogs/EnterPasswordView.axaml
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
Labels: size/L

#4643 Terminate Wasabi on Windows system events like shutdown
  WalletWasabi.Gui/Program.cs
  WalletWasabi.Gui/packages.lock.json
  WalletWasabi.Packager/packages.lock.json
  WalletWasabi/Services/Terminate/TerminateService.cs
  WalletWasabi/WalletWasabi.csproj
  WalletWasabi/packages.lock.json
Labels: size/L

#4642 BackendTests to use ClearnetHttpClient
  WalletWasabi.Tests/RegressionTests/BackendTests.cs
  WalletWasabi.Tests/XunitConfiguration/RegTestFixture.cs
  WalletWasabi/Tor/Http/BackendHttpClient.cs
  WalletWasabi/Tor/Http/IHttpClient.cs
  WalletWasabi/WebClients/Wasabi/WasabiClient.cs
Labels: size/L

#4716 Remove useless extension
  WalletWasabi/Extensions/NBitcoinExtensions.cs
Labels: size/XS

#4714 Add IRelativeHttpClient (2)
  WalletWasabi.Tests/RegressionTests/BackendTests.cs
  WalletWasabi.Tests/UnitTests/Clients/MockTorHttpClient.cs
  WalletWasabi.Tests/UnitTests/Transactions/PayjoinTests.cs
  WalletWasabi/Tor/Http/BackendHttpClient.cs
  WalletWasabi/Tor/Http/ClearnetHttpClient.cs
  WalletWasabi/Tor/Http/IRelativeHttpClient.cs
  WalletWasabi/Tor/Http/Interfaces/ITorHttpClient.cs
  WalletWasabi/Tor/Http/TorHttpClient.cs
Labels: size/L

#4717 Make HdPubKey have Cluster and not SmartCoin
  WalletWasabi.Gui/Controls/WalletExplorer/CoinViewModel.cs
  WalletWasabi.Tests/Common.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
  WalletWasabi/Blockchain/Analysis/Clustering/Cluster.cs
  WalletWasabi/Blockchain/Keys/HdPubKey.cs
  WalletWasabi/Blockchain/TransactionBuilding/SmartCoinSelector.cs
  WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs
  WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
Labels: size/L

#4719 Make HdPubKey have Anonset and not SmartCoin
  WalletWasabi.Gui/CommandLine/Daemon.cs
  WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/CoinViewModel.cs
  WalletWasabi.Gui/Rpc/WasabiJsonRpcService.cs
  WalletWasabi.Tests/Common.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/UnitTests/SmartCoinTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
  WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs
  WalletWasabi/Blockchain/Analysis/Clustering/Cluster.cs
  WalletWasabi/Blockchain/Keys/HdPubKey.cs
  WalletWasabi/Blockchain/TransactionBuilding/SmartCoinSelector.cs
  WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs
  WalletWasabi/Blockchain/TransactionOutputs/CoinsView.cs
  WalletWasabi/Blockchain/TransactionOutputs/ICoinsView.cs
  WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
  WalletWasabi/Blockchain/TransactionProcessing/ProcessedResult.cs
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
  WalletWasabi/CoinJoin/Client/Rounds/ClientState.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/L

#4718 Set indent_size to 4 for C# Files
  .editorconfig
Labels: size/XS

#4727 [Fluent] Use using instead of clr-namespace for xmlns in xaml
  WalletWasabi.Fluent/App.xaml
  WalletWasabi.Fluent/Controls/ContentArea.axaml
  WalletWasabi.Fluent/Controls/Dialog.xaml
  WalletWasabi.Fluent/Controls/NavBarItem.xaml
  WalletWasabi.Fluent/Controls/NavBarTreeItem.xaml
  WalletWasabi.Fluent/Controls/TagsBox.xaml
  WalletWasabi.Fluent/Styles/FontSizes.xaml
  WalletWasabi.Fluent/Styles/SplitView.xaml
  WalletWasabi.Fluent/Styles/Styles.xaml
  WalletWasabi.Fluent/Styles/TextBox.xaml
  WalletWasabi.Fluent/Styles/Themes/Base.xaml
  WalletWasabi.Fluent/Styles/Themes/BaseDark.xaml
  WalletWasabi.Fluent/Styles/Themes/BaseLight.xaml
  WalletWasabi.Fluent/Views/AddWallet/ConfirmRecoveryWordsView.axaml
  WalletWasabi.Fluent/Views/AddWallet/RecoverWalletView.axaml
  WalletWasabi.Fluent/Views/AddWallet/RecoveryWordsView.axaml
  WalletWasabi.Fluent/Views/AddWalletPageView.axaml
  WalletWasabi.Fluent/Views/Dialogs/AdvancedRecoveryOptionsView.axaml
  WalletWasabi.Fluent/Views/Dialogs/EnterPasswordView.axaml
  WalletWasabi.Fluent/Views/Dialogs/TestDialogView.axaml
  WalletWasabi.Fluent/Views/HomePageView.axaml
  WalletWasabi.Fluent/Views/MainView.axaml
  WalletWasabi.Fluent/Views/MainWindow.axaml
  WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
  WalletWasabi.Fluent/Views/SettingsPageView.axaml
  WalletWasabi.Fluent/Views/StatusBar.axaml
Labels: size/L

#4722 [Fluent] Added and refactored RoutableViewModel navigation helper methods
  WalletWasabi.Fluent/ViewModels/AddWallet/ConfirmRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/TestDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/RoutableViewModel.cs
  WalletWasabi.Fluent/ViewModels/SettingsPageViewModel.cs
Labels: size/L

#4726 [Fluent] Reset navigation when Dialog is using IScreen
  WalletWasabi.Fluent/Controls/Dialog.xaml.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/DialogScreenViewModel.cs
Labels: size/M

#4728 [Fluent] Enable compiled bindings + unified font size definitions
  WalletWasabi.Fluent/Controls/ContentArea.axaml
  WalletWasabi.Fluent/Views/AddWallet/ConfirmRecoveryWordsView.axaml
  WalletWasabi.Fluent/Views/AddWallet/RecoveryWordsView.axaml
  WalletWasabi.Fluent/Views/AddWalletPageView.axaml
  WalletWasabi.Fluent/Views/Dialogs/EnterPasswordView.axaml
  WalletWasabi.Fluent/Views/Dialogs/TestDialogView.axaml
  WalletWasabi.Fluent/Views/HomePageView.axaml
  WalletWasabi.Fluent/Views/MainView.axaml
  WalletWasabi.Fluent/Views/SettingsPageView.axaml
  WalletWasabi.Fluent/Views/StatusBar.axaml
Labels: size/M

#4710 [Fluent] Don't close recovery wallet page when the user closes the pwdbox
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
Labels: size/S

#4732 [Fluent] Disable PageTransition for RoutedViewHost
  WalletWasabi.Fluent/Views/MainView.axaml
Labels: size/S

#4733 [trivial] Use IRelativeHttpClient instead of ITorHttpClient in WasabiClient.
  WalletWasabi/WebClients/Wasabi/WasabiClient.cs
Labels: size/M

#4729 Pass dependency via constructor (remove Locator)
  WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/WalletManagerViewModel.cs
Labels: size/S

#4735 [easy] Backend tests to use ClearnetHttpClient
  WalletWasabi.Tests/RegressionTests/BackendTests.cs
Labels: size/S

#4739 Add IsSubscribeToSessionEnding
  WalletWasabi/Services/Terminate/TerminateService.cs
Labels: size/XS

#4707 Fix Node disconnect exception
  WalletWasabi/BitcoinCore/Monitoring/P2pReconnector.cs
  WalletWasabi/BitcoinCore/P2pNode.cs
Labels: size/L

#4730 Upgrade to dotnet 5.0
  README.md
  WalletWasabi.Backend/WalletWasabi.Backend.csproj
  WalletWasabi.Documentation/BackendDeployment.md
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Gui/WalletWasabi.Gui.csproj
  WalletWasabi.Gui/packages.lock.json
  WalletWasabi.Packager/Program.cs
  WalletWasabi.Packager/WalletWasabi.Packager.csproj
  WalletWasabi.Packager/packages.lock.json
  WalletWasabi.Tests/UnitTests/Hwi/HwiProcessBridgeMock.cs
  WalletWasabi.Tests/UnitTests/Userfacing/ParserTests.cs
  WalletWasabi.Tests/WalletWasabi.Tests.csproj
  WalletWasabi/Extensions/StringExtensions.cs
  WalletWasabi/Hwi/Parsers/HwiParser.cs
  WalletWasabi/Io/MutexIoManager.cs
  WalletWasabi/Mono/CommandSet.cs
  WalletWasabi/Mono/OptionSet.cs
  WalletWasabi/WalletWasabi.csproj
  WalletWasabi/packages.lock.json
  azure-pipelines-cd.yml
  azure-pipelines-detbuild.yml
  azure-pipelines-linux.yml
  azure-pipelines-osx.yml
  azure-pipelines-windows.yml
Labels: size/L

#4740 Fix off by one bug
  WalletWasabi/Io/MutexIoManager.cs
Labels: size/XS

#4741 Unify the Navbar on OSX and Windows
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent/App.xaml
  WalletWasabi.Fluent/Views/HomePageView.axaml
  WalletWasabi.Fluent/Views/MainView.axaml
  WalletWasabi.Fluent/Views/MainWindow.axaml
  WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
Labels: size/M

#4744 Specify analysis level in project files
  WalletWasabi.Backend/WalletWasabi.Backend.csproj
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Gui/WalletWasabi.Gui.csproj
  WalletWasabi.Packager/WalletWasabi.Packager.csproj
  WalletWasabi.Tests/WalletWasabi.Tests.csproj
  WalletWasabi/WalletWasabi.csproj
Labels: size/XS

#4745 [trivial] ITorHttpClient: Remove IsTorUsed property.
  WalletWasabi.Tests/UnitTests/Clients/MockTorHttpClient.cs
  WalletWasabi/Tor/Http/Interfaces/ITorHttpClient.cs
  WalletWasabi/Tor/Http/TorHttpClient.cs
Labels: size/XS

#4723 SatoshiClient does not inherit from TorDisposable.
  WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/RegressionTests/DosTests.cs
  WalletWasabi.Tests/UnitTests/Clients/MockTorHttpClient.cs
  WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
  WalletWasabi/CoinJoin/Client/Clients/SatoshiClient.cs
  WalletWasabi/Tor/Http/IHttpClient.cs
  WalletWasabi/Tor/Http/IRelativeHttpClient.cs
  WalletWasabi/Tor/Http/TorHttpClient.cs
  WalletWasabi/WebClients/PayJoin/PayjoinClient.cs
  WalletWasabi/WebClients/Wasabi/WasabiClientFactory.cs
Labels: size/M

#4749 Rename Tor exceptions
  WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
  WalletWasabi/CoinJoin/Client/Clients/AliceClientBase.cs
  WalletWasabi/Services/WasabiSynchronizer.cs
  WalletWasabi/Tor/Exceptions/ConnectionException.cs
  WalletWasabi/Tor/Exceptions/TorSocks5FailureResponseException.cs
  WalletWasabi/Tor/Http/TorHttpClient.cs
  WalletWasabi/Tor/Socks5/Exceptions/TorConnectCommandFailedException.cs
  WalletWasabi/Tor/Socks5/Exceptions/TorConnectionException.cs
  WalletWasabi/Tor/Socks5/TorSocks5Client.cs
  WalletWasabi/Tor/TorMonitor.cs
Labels: size/L

#4736 WasabiClient is no longer disposable
  WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
  WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
  WalletWasabi.Tests/RegressionTests/BackendTests.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/RegressionTests/Common.cs
  WalletWasabi/Blockchain/Mempool/MempoolService.cs
  WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs
  WalletWasabi/CoinJoin/Client/CoinJoinProcessor.cs
  WalletWasabi/Services/UpdateChecker.cs
  WalletWasabi/Services/WasabiSynchronizer.cs
  WalletWasabi/Wallets/Wallet.cs
  WalletWasabi/WebClients/Wasabi/WasabiClient.cs
  WalletWasabi/WebClients/Wasabi/WasabiClientFactory.cs
Labels: size/L

#4697 Remove safe and async mutexing IOs 2
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Tests/IntegrationTests/P2pTests.cs
  WalletWasabi.Tests/UnitTests/AbandonedTasksTests.cs
  WalletWasabi.Tests/UnitTests/BitcoinCore/P2pBasedTests.cs
  WalletWasabi.Tests/UnitTests/Filters/IndexStoreTests.cs
  WalletWasabi.Tests/UnitTests/IoTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/AllTransactionStoreTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionStoreTests.cs
  WalletWasabi/Blockchain/Transactions/AllTransactionStore.cs
  WalletWasabi/Blockchain/Transactions/TransactionStore.cs
  WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
  WalletWasabi/Io/DigestableSafeIoManager.cs
  WalletWasabi/Io/MutexIoManager.cs
  WalletWasabi/Io/SafeIoManager.cs
  WalletWasabi/Nito/AsyncEx/AbandonedTasks.cs
  WalletWasabi/Stores/BitcoinStore.cs
  WalletWasabi/Stores/IndexStore.cs
Labels: size/XL

#4750 Improve cancellation of initialization
  WalletWasabi.Gui/Global.cs
Labels: size/S

#4751 Improve readability
  WalletWasabi.Fluent/Controls/TagsBox.xaml.cs
  WalletWasabi.Gui/Controls/WalletExplorer/PinPadViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionViewModel.cs
  WalletWasabi.Gui/ViewModels/AddressViewModel.cs
  WalletWasabi/CoinJoin/Client/Clients/AliceClientBase.cs
  WalletWasabi/Extensions/RPCClientExtensions.cs
  WalletWasabi/Hwi/HwiClient.cs
  WalletWasabi/Stores/IndexStore.cs
  WalletWasabi/Tor/Http/TorHttpClient.cs
  WalletWasabi/Wallets/P2pBlockProvider.cs
Labels: size/M

#4753 Improve shutdown speed
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionStoreMock.cs
  WalletWasabi/Blockchain/Transactions/AllTransactionStore.cs
  WalletWasabi/Blockchain/Transactions/TransactionStore.cs
  WalletWasabi/Stores/BitcoinStore.cs
  WalletWasabi/Stores/IndexStore.cs
Labels: size/M

#4756 Remove unused AddOrReplaceRound method.
  WalletWasabi/CoinJoin/Client/Rounds/ClientState.cs
Labels: size/S

#4757 BobClient without being disposable.
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi/CoinJoin/Client/Clients/BobClient.cs
  WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
Labels: size/M

#4686 Shutdown Wasabi on Docker gracefully
  WalletWasabi/Services/Terminate/TerminateService.cs
Labels: size/M

#4760 Speed up Global DisposeAsync
  WalletWasabi.Gui/Global.cs
Labels: size/S

#4743 [Fluent] Progress Ring
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent/App.xaml
  WalletWasabi.Fluent/Controls/ProgressRing.xaml
  WalletWasabi.Fluent/Controls/ProgressRing.xaml.cs
  WalletWasabi.Fluent/Controls/ProgressRingArc.xaml
  WalletWasabi.Fluent/Controls/ProgressRingArc.xaml.cs
  WalletWasabi.Fluent/Views/SettingsPageView.axaml
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
Labels: size/L

#4755 [Fluent] Dialog closing fixes
  WalletWasabi.Fluent/ViewModels/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/DialogScreenViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/DialogViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/DialogViewModelBaseOfTResult.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/RoutableViewModel.cs
  WalletWasabi.Fluent/Views/MainView.axaml
Labels: size/L

#4764 Remove TorDisposableBase.
  WalletWasabi/CoinJoin/Client/Clients/AliceClientBase.cs
  WalletWasabi/Tor/Http/Bases/TorDisposableBase.cs
  WalletWasabi/Tor/Http/Interfaces/ITorHttpClient.cs
  WalletWasabi/Tor/Http/TorHttpClient.cs
Labels: size/M

#4768 Update supported operating systems
  WalletWasabi.Documentation/WasabiCompatibility.md
Labels: size/XS

#4759 Recover button CanExecute logic
  WalletWasabi.Gui/Tabs/WalletManager/RecoverWallets/RecoverWalletViewModel.cs
Labels: size/S

#4721 [Fluent] initial implementation of legal docs navigation.
  WalletWasabi.Fluent/Controls/ContentArea.axaml
  WalletWasabi.Fluent/Controls/ContentArea.axaml.cs
  WalletWasabi.Fluent/Controls/Dialog.xaml
  WalletWasabi.Fluent/Icons/Icons.xaml
  WalletWasabi.Fluent/Styles/PlainButton.xaml
  WalletWasabi.Fluent/ViewModels/AddWallet/LegalDocumentsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/TermsAndConditionsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/DialogViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/DialogViewModelBaseOfTResult.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/EnterPasswordViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/RoutableViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/LegalDocumentsView.axaml
  WalletWasabi.Fluent/Views/AddWallet/LegalDocumentsView.axaml.cs
  WalletWasabi.Fluent/Views/AddWallet/TermsAndConditionsView.axaml
  WalletWasabi.Fluent/Views/AddWallet/TermsAndConditionsView.axaml.cs
  WalletWasabi.Fluent/Views/AddWalletPageView.axaml
  WalletWasabi.Fluent/Views/Dialogs/EnterPasswordView.axaml
Labels: size/XL

#4771 Show warnings when ConfigureAwait(true/false) is missing. These warni…
  .editorconfig
  WalletWasabi.Backend/.editorconfig
  WalletWasabi.Tests/.editorconfig
Labels: size/S

#4774 ConfigureAwait(false) in library project
  WalletWasabi/BitcoinCore/CoreNode.cs
  WalletWasabi/BitcoinCore/Rpc/CachedRpcClient.cs
  WalletWasabi/BitcoinCore/Rpc/RpcClientBase.cs
  WalletWasabi/Blockchain/BlockFilters/IndexBuilderService.cs
  WalletWasabi/Blockchain/Blocks/BlockNotifier.cs
  WalletWasabi/Blockchain/Transactions/AllTransactionStore.cs
  WalletWasabi/Extensions/RPCClientExtensions.cs
  WalletWasabi/Extensions/StreamExtensions.cs
  WalletWasabi/Helpers/NBitcoinHelpers.cs
  WalletWasabi/Helpers/RuntimeParams.cs
  WalletWasabi/Hwi/HwiClient.cs
  WalletWasabi/Mono/CommandSet.cs
  WalletWasabi/Mono/HelpCommand.cs
  WalletWasabi/Tor/Http/Extensions/HttpResponseMessageExtensions.cs
  WalletWasabi/Tor/Http/Helpers/HttpMessageHelper.cs
  WalletWasabi/WebClients/Bitstamp/BitstampExchangeRateProvider.cs
  WalletWasabi/WebClients/BlockchainInfo/BlockchainInfoExchangeRateProvider.cs
  WalletWasabi/WebClients/CoinGecko/CoinGeckoExchangeRateProvider.cs
  WalletWasabi/WebClients/Coinbase/CoinbaseExchangeRateProvider.cs
  WalletWasabi/WebClients/ExchangeRateProviders.cs
  WalletWasabi/WebClients/Gemini/GeminiExchangeRateProvider.cs
  WalletWasabi/WebClients/ItBit/ItBitExchangeRateProvider.cs
Labels: size/L

#4775 Fix errors
  WalletWasabi/Crypto/ZeroKnowledge/Credential.cs
  WalletWasabi/Crypto/ZeroKnowledge/CredentialPresentation.cs
  WalletWasabi/Crypto/ZeroKnowledge/ProofSystem.cs
  WalletWasabi/Wabisabi/CredentialIssuer.cs
  WalletWasabi/Wabisabi/WabiSabiClient.cs
Labels: size/M

#4776 Avoid zero-length array allocations in library project
  WalletWasabi/Crypto/ZeroKnowledge/ProofSystem.cs
Labels: size/XS

#4777 Remove unused members in library project
  WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs
Labels: size/XS

#4778 Use 'AsSpan' instead of the 'System.Range'-based indexer on 'byte[]' to avoid creating unnecessary data copies
  WalletWasabi/Crypto/Groups/GroupElement.cs
Labels: size/XS

#4779 Make cts the last parameter by convention in the library project
  WalletWasabi.Tests/UnitTests/AsyncMutexTests.cs
  WalletWasabi/Blockchain/Transactions/AllTransactionStore.cs
  WalletWasabi/Nito/AsyncEx/AsyncMutex.cs
  WalletWasabi/Services/SingleInstanceChecker.cs
  WalletWasabi/Stores/BitcoinStore.cs
Labels: size/S

#4780 Equality warning fixes
  WalletWasabi/Models/ErrorDescriptor.cs
  WalletWasabi/Models/Height.cs
Labels: size/S

#4781 Remove confawait check from the GUI project.
  WalletWasabi.Gui/.editorconfig
Labels: size/XS

#4782 Simplify object initializations in library project
  WalletWasabi/BitcoinCore/Configuration/Whitening/WhiteEntry.cs
  WalletWasabi/BitcoinCore/CoreNode.cs
  WalletWasabi/WebClients/Bitstamp/BitstampExchangeRateProvider.cs
  WalletWasabi/WebClients/BlockchainInfo/BlockchainInfoExchangeRateProvider.cs
  WalletWasabi/WebClients/CoinGecko/CoinGeckoExchangeRateProvider.cs
  WalletWasabi/WebClients/Coinbase/CoinbaseExchangeRateProvider.cs
  WalletWasabi/WebClients/Gemini/GeminiExchangeRateProvider.cs
  WalletWasabi/WebClients/ItBit/ItBitExchangeRateProvider.cs
  WalletWasabi/WebClients/PayJoin/PayjoinClient.cs
Labels: size/M

#4783 Deconstruct variable declarations in library project
  WalletWasabi/Blockchain/Transactions/TransactionStore.cs
  WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
  WalletWasabi/CoinJoin/Coordinator/Coordinator.cs
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
  WalletWasabi/Io/DigestableSafeIoManager.cs
  WalletWasabi/WebClients/Wasabi/WasabiClient.cs
Labels: size/M

#4784 Forward cancellation token
  WalletWasabi/WebClients/Wasabi/WasabiClient.cs
Labels: size/XS

#4785 Fix some null warnings
  WalletWasabi/Extensions/LinqExtensions.cs
Labels: size/M

#4786 Fighting with warnings
  WalletWasabi.Gui/Models/ShieldState.cs
  WalletWasabi.Tests/UnitTests/Converters/OutPointAsTxoRefJsonConverterTests.cs
  WalletWasabi.Tests/UnitTests/Converters/TxoRef.cs
  WalletWasabi/BitcoinCore/Monitoring/RpcStatus.cs
  WalletWasabi/Blockchain/Analysis/FeesEstimation/AllFeeEstimate.cs
  WalletWasabi/CoinJoin/Common/Models/BlindedOutputWithNonceIndex.cs
Labels: size/L

#4787 Remove unnecessary supression
  WalletWasabi/Crypto/SchnorrBlindingSignature.cs
Labels: size/XS

#4788 Remove global rule and add to lib project only
  .editorconfig
  WalletWasabi.Backend/.editorconfig
  WalletWasabi.Tests/.editorconfig
  WalletWasabi/.editorconfig
Labels: size/S

#4737 [Fluent] Search
  WalletWasabi.Fluent/Controls/NavBarItem.xaml
  WalletWasabi.Fluent/Controls/NavBarItem.xaml.cs
  WalletWasabi.Fluent/Icons/Icons.xaml
  WalletWasabi.Fluent/Styles/TextBox.xaml
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/Search/SearchCategory.cs
  WalletWasabi.Fluent/ViewModels/Search/SearchItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Search/SearchResult.cs
  WalletWasabi.Fluent/ViewModels/SearchPageViewModel.cs
  WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
  WalletWasabi.Fluent/Views/SearchPageView.axaml
  WalletWasabi.Fluent/Views/SearchPageView.axaml.cs
Labels: size/L

#4773 Features/vdg/settings
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent/App.xaml
  WalletWasabi.Fluent/Controls/ConcatenatingWrapPanel.cs
  WalletWasabi.Fluent/Controls/ContentArea.axaml
  WalletWasabi.Fluent/Icons/Icons.xaml
  WalletWasabi.Fluent/Styles/TextBox.xaml
  WalletWasabi.Fluent/Styles/Themes/Base.xaml
  WalletWasabi.Fluent/ViewModels/AddWallet/ConfirmRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/AdvancedRecoveryOptionsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/TestDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/RoutableViewModel.cs
  WalletWasabi.Fluent/ViewModels/SearchPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/SettingsPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/SettingsPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/ClosedWalletViewModel.cs
  WalletWasabi.Fluent/Views/Settings/BitcoinSettingsView.xaml
  WalletWasabi.Fluent/Views/Settings/BitcoinSettingsView.xaml.cs
  WalletWasabi.Fluent/Views/Settings/GeneralSettingsView.xaml
  WalletWasabi.Fluent/Views/Settings/GeneralSettingsView.xaml.cs
  WalletWasabi.Fluent/Views/Settings/NetworkSettingsView.xaml
  WalletWasabi.Fluent/Views/Settings/NetworkSettingsView.xaml.cs
  WalletWasabi.Fluent/Views/Settings/PrivacySettingsView.xaml
  WalletWasabi.Fluent/Views/Settings/PrivacySettingsView.xaml.cs
  WalletWasabi.Fluent/Views/Settings/SettingsPageView.xaml
  WalletWasabi.Fluent/Views/Settings/SettingsPageView.xaml.cs
  WalletWasabi.Fluent/Views/SettingsPageView.axaml
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
Labels: size/XL

#4769 [Fluent] Trivial cleanup
  WalletWasabi.Fluent/Controls/ProgressRing.xaml
  WalletWasabi.Fluent/ViewModels/AddWallet/ConfirmRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/TermsAndConditionsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/AdvancedRecoveryOptionsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/EnterPasswordViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/TestDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/RoutableViewModel.cs
  WalletWasabi.Fluent/Views/Dialogs/AdvancedRecoveryOptionsView.axaml
Labels: size/M

#4758 [Fluent] Import wallet
  WalletWasabi.Fluent/ViewModels/AddWallet/ImportWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/Views/AddWalletPageView.axaml
Labels: size/L

#4789 Fix naming violations
  WalletWasabi/Crypto/SchnorrBlindingSignature.cs
Labels: size/S

#4794 Minor refactoring in TorTests.
  WalletWasabi.Tests/IntegrationTests/TorTests.cs
Labels: size/M

#4796 [Fluent] Add IsBusy on ContentArea to display a loading ring animation
  WalletWasabi.Fluent/Controls/ContentArea.axaml
  WalletWasabi.Fluent/Controls/ContentArea.axaml.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/RoutableViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/RecoverWalletView.axaml
  WalletWasabi.Fluent/Views/AddWalletPageView.axaml
Labels: size/L

#4793 [Fluent] Add settings tabs to search
  WalletWasabi.Fluent/Icons/Icons.xaml
  WalletWasabi.Fluent/ViewModels/SearchPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/SettingsPageViewModel.cs
  WalletWasabi.Fluent/Views/Settings/SettingsPageView.xaml
Labels: size/L

#4797 [Fluent] Use standardized fluent easing in resources
  WalletWasabi.Fluent/Controls/Dialog.xaml
  WalletWasabi.Fluent/Controls/ProgressRing.xaml
  WalletWasabi.Fluent/Styles/Styles.xaml
Labels: size/S

#4805 [Fluent] Make endcaps on progress ring indicator round.
  WalletWasabi.Fluent/Controls/ProgressRingArc.xaml
Labels: size/S

#4801 [Fluent] Move view model classes to proper folders
  WalletWasabi.Fluent/Behaviors/FocusBehavior.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/ConfirmRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/ImportWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/LegalDocumentsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/TermsAndConditionsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/AdvancedRecoveryOptionsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/DialogViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/DialogViewModelBaseOfTResult.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/EnterPasswordViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/TestDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/HomePageViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationStateViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/RoutableViewModel.cs
  WalletWasabi.Fluent/ViewModels/Search/SearchItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Search/SearchPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/SettingsPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/ClosedHardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/ClosedWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/ClosedWatchOnlyWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/HardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WatchOnlyWalletViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/AddWalletPageView.axaml
  WalletWasabi.Fluent/Views/AddWallet/AddWalletPageView.axaml.cs
  WalletWasabi.Fluent/Views/Search/SearchPageView.axaml
  WalletWasabi.Fluent/Views/Search/SearchPageView.axaml.cs
Labels: size/M

#4800 PayjoinClient accepts HttpClient only through IRelativeHttpClient now.
  WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs
  WalletWasabi/WebClients/PayJoin/PayjoinClient.cs
  WalletWasabi/WebClients/Wasabi/WasabiClientFactory.cs
Labels: size/M

#4767 Add isolateStream as parameter too.
  WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
  WalletWasabi.Tests/UnitTests/Clients/MockTorHttpClient.cs
  WalletWasabi/Tor/Http/BackendHttpClient.cs
  WalletWasabi/Tor/Http/ClearnetHttpClient.cs
  WalletWasabi/Tor/Http/IHttpClient.cs
  WalletWasabi/Tor/Http/IRelativeHttpClient.cs
  WalletWasabi/Tor/Http/TorHttpClient.cs
Labels: size/L

#4807 Add KeyPaths first to PSBT
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
  WalletWasabi/Extensions/NBitcoinExtensions.cs
Labels: size/XS

#4812 VDG: automatically show welcome screen
  WalletWasabi.Fluent/ViewModels/HomePageViewModel.cs
Labels: size/XS

#4813 Features/vdg simplify navigation
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/ConfirmRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/ImportWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/LegalDocumentsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/TermsAndConditionsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/AdvancedRecoveryOptionsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/DialogViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/DialogViewModelBaseOfTResult.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/EnterPasswordViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/TestDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/HomePageViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/RoutableViewModel.cs
  WalletWasabi.Fluent/ViewModels/Search/SearchItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Search/SearchPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/SettingsPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModelBase.cs
Labels: size/L

#4815 search entries and categories are registered.
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/Search/SearchPageViewModel.cs
Labels: size/L

#4816 Make navigationstate a singleton.. .and dont pass it to every ctor.
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/ConfirmRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/ImportWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/LegalDocumentsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/TermsAndConditionsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/AdvancedRecoveryOptionsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/DialogViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/DialogViewModelBaseOfTResult.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/EnterPasswordViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/TestDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/HomePageViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationState.cs
  WalletWasabi.Fluent/ViewModels/Navigation/RoutableViewModel.cs
  WalletWasabi.Fluent/ViewModels/Search/SearchItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Search/SearchPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/SettingsPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/ClosedHardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/ClosedWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/ClosedWatchOnlyWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/HardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WatchOnlyWalletViewModel.cs
Labels: size/L

#4799 [Fluent] Separate settings
  WalletWasabi.Fluent.Desktop/Program.cs
  WalletWasabi.Fluent/App.xaml
  WalletWasabi.Fluent/Controls/InfoMessage.axaml
  WalletWasabi.Fluent/Controls/InfoMessage.axaml.cs
  WalletWasabi.Fluent/Converters/EnumToFriendlyNameConverter.cs
  WalletWasabi.Fluent/Helpers/ThemeHelper.cs
  WalletWasabi.Fluent/Icons/Icons.xaml
  WalletWasabi.Fluent/Model/RestartNeededEventArgs.cs
  WalletWasabi.Fluent/Styles/Themes/Base.xaml
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/BitcoinTabViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/GeneralTabViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/NetworkTabViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/PrivacyTabViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/SettingsPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/SettingsTabViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/Wallets/ClosedWalletViewModel.cs
  WalletWasabi.Fluent/Views/Settings/BitcoinSettingsView.xaml
  WalletWasabi.Fluent/Views/Settings/GeneralSettingsView.xaml
  WalletWasabi.Fluent/Views/Settings/NetworkSettingsView.xaml
  WalletWasabi.Fluent/Views/Settings/PrivacySettingsView.xaml
  WalletWasabi.Fluent/Views/Settings/SettingsPageView.xaml
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Gui/Models/FeeDisplayFormat.cs
  WalletWasabi.Gui/Tabs/SettingsViewModel.cs
  WalletWasabi.Gui/UiConfig.cs
Labels: size/XXL

#4811 [Fluent] About Screen Implementation
  WalletWasabi.Fluent/Styles/FontSizes.xaml
  WalletWasabi.Fluent/Styles/TextBox.xaml
  WalletWasabi.Fluent/Styles/Themes/BaseDark.xaml
  WalletWasabi.Fluent/Styles/Themes/BaseLight.xaml
  WalletWasabi.Fluent/ViewModels/AboutViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/AboutAdvancedInfoViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Fluent/Views/AboutView.axaml
  WalletWasabi.Fluent/Views/AboutView.axaml.cs
  WalletWasabi.Fluent/Views/AddWallet/RecoverWalletView.axaml
  WalletWasabi.Fluent/Views/Dialogs/AboutAdvancedInfoView.axaml
  WalletWasabi.Fluent/Views/Dialogs/AboutAdvancedInfoView.axaml.cs
Labels: size/L

#4802 [Fluent] NavBar bottom items refactoring
  WalletWasabi.Fluent/Converters/NavBarIconConverter.cs
  WalletWasabi.Fluent/Icons/Icons.xaml
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/Search/SearchItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/PrivacyModeViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/SettingsPageViewModel.cs
  WalletWasabi.Fluent/Views/HomePageView.axaml
  WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
  WalletWasabi.Fluent/Views/Search/SearchPageView.axaml
Labels: size/L

#4817 [Fluent] [Trivial] Fix caption in About search item
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
Labels: size/XS

#4818 Fix search navigation
  WalletWasabi.Fluent/ViewModels/AboutViewModel.cs
  WalletWasabi.Fluent/ViewModels/Search/SearchItemViewModel.cs
  WalletWasabi.Fluent/Views/AboutView.axaml
Labels: size/S

#4819 Vdg/some polishing
  WalletWasabi.Fluent/Styles/SplitView.xaml
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Fluent/Views/MainWindow.axaml
  WalletWasabi.Fluent/Views/Search/SearchPageView.axaml
  WalletWasabi.Fluent/Views/StatusBar.axaml
Labels: size/M

#4820 remove selecting code that breaks navigation.
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
Labels: size/XS

#4821 Refactorings
  WalletWasabi.Fluent/Behaviors/AutoBringIntoViewExtension.cs
  WalletWasabi.Fluent/Controls/TagsBox.xaml.cs
Labels: size/M

#4823 Vdg/replace rx ui navigation
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/ConfirmRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/ImportWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/TermsAndConditionsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/AdvancedRecoveryOptionsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/DialogScreenViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/TestDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/HomePageViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/INavigatable.cs
  WalletWasabi.Fluent/ViewModels/Navigation/INavigationManager.cs
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationMode.cs
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationStack.cs
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationState.cs
  WalletWasabi.Fluent/ViewModels/Navigation/RoutableViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/TargettedNavigationStack.cs
  WalletWasabi.Fluent/ViewModels/Search/SearchItemViewModel.cs
  WalletWasabi.Fluent/Views/MainView.axaml
Labels: size/XL

#4824 fix ReSharper warnings and remove redundant code.
  WalletWasabi.Fluent/ScreenViewLocator.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/AboutAdvancedInfoViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/AdvancedRecoveryOptionsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/DialogScreenViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/DialogViewModelBaseOfTResult.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/EnterPasswordViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationState.cs
  WalletWasabi.Fluent/ViewModels/Navigation/RoutableViewModel.cs
  WalletWasabi.Fluent/ViewModels/Search/SearchItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Search/SearchPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/GeneralTabViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/PrivacyModeViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/SettingsPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/ClosedHardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/ClosedWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/ClosedWatchOnlyWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/HardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WatchOnlyWalletViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/TermsAndConditionsView.axaml
  WalletWasabi.Fluent/Views/Dialogs/EnterPasswordView.axaml
  WalletWasabi.Fluent/Views/Settings/BitcoinSettingsView.xaml
  WalletWasabi.Fluent/Views/Settings/GeneralSettingsView.xaml
  WalletWasabi.Fluent/Views/Settings/NetworkSettingsView.xaml
  WalletWasabi.Fluent/Views/Settings/PrivacySettingsView.xaml
  WalletWasabi.Fluent/Views/Settings/SettingsPageView.xaml
Labels: size/L

#4795 WasabiClientFactory: Use proper HTTP client.
  WalletWasabi/WebClients/Wasabi/WasabiClientFactory.cs
Labels: size/S

#4792 Avoid using the same DNS records for good in ClearnetHttpClient
  WalletWasabi/Tor/Http/ClearnetHttpClient.cs
Labels: size/S

#4724 Improve anonymity scoring
  WalletWasabi.Backend/WalletWasabi.Backend.csproj
  WalletWasabi.Gui/WalletWasabi.Gui.csproj
  WalletWasabi.Packager/WalletWasabi.Packager.csproj
  WalletWasabi.Tests/Common.cs
  WalletWasabi.Tests/Helpers/BitcoinFactory.cs
  WalletWasabi.Tests/Helpers/Common.cs
  WalletWasabi.Tests/Helpers/CryptoHelpers.cs
  WalletWasabi.Tests/Helpers/ServiceFactory.cs
  WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
  WalletWasabi.Tests/IntegrationTests/P2pTests.cs
  WalletWasabi.Tests/IntegrationTests/TorTests.cs
  WalletWasabi.Tests/RegressionTests/BackendTests.cs
  WalletWasabi.Tests/RegressionTests/BuildTests.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/RegressionTests/Common.cs
  WalletWasabi.Tests/RegressionTests/DosTests.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi.Tests/RegressionTests/WalletTests.cs
  WalletWasabi.Tests/UnitTests/BlockchainAnalysis/CoinJoinAnonscoreTests.cs
  WalletWasabi.Tests/UnitTests/BlockchainAnalysis/NormalSpendAnonScoreTests.cs
  WalletWasabi.Tests/UnitTests/BlockchainAnalysis/PubKeyReuseAnonScoreTests.cs
  WalletWasabi.Tests/UnitTests/BlockchainAnalysis/ReceiveAnonScoreTests.cs
  WalletWasabi.Tests/UnitTests/BlockchainAnalysis/SelfSpendAnonScoreTests.cs
  WalletWasabi.Tests/UnitTests/BlockchainAnalysis/WalletIrrelevantAnonScoreTests.cs
  WalletWasabi.Tests/UnitTests/Clients/SingleInstanceCheckerTests.cs
  WalletWasabi.Tests/UnitTests/Filters/IndexStoreTests.cs
  WalletWasabi.Tests/UnitTests/IoTests.cs
  WalletWasabi.Tests/UnitTests/KeyManagementTests.cs
  WalletWasabi.Tests/UnitTests/LegalTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/AllTransactionStoreTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/OperationMergerTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/PayjoinTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionStoreMock.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionStoreTests.cs
  WalletWasabi.Tests/UnitTests/WalletDirTests.cs
  WalletWasabi.Tests/WalletWasabi.Tests.csproj
  WalletWasabi.Tests/XunitConfiguration/RegTestFixture.cs
  WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs
  WalletWasabi/Blockchain/Keys/HdPubKey.cs
  WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
  WalletWasabi/Extensions/NBitcoinExtensions.cs
  WalletWasabi/WalletWasabi.csproj
Labels: size/XXL

#4822 [Fluent] Fix search navigation and initial navigation
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
Labels: size/XS

#4827 Fluent: update avalonia
  WalletWasabi.Fluent.Desktop/Program.cs
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent.Desktop/nuget.config
  WalletWasabi.Fluent/Styles/Themes/BaseDark.xaml
  WalletWasabi.Fluent/Styles/Themes/BaseLight.xaml
  WalletWasabi.Fluent/ViewModels/Settings/SettingsTabViewModelBase.cs
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
Labels: size/M

#4826 [Fluent] View legal docs
  WalletWasabi.Fluent/ViewModels/AddWallet/LegalDocumentsViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationStack.cs
  WalletWasabi.Fluent/ViewModels/Search/SearchItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Search/SearchPageViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/LegalDocumentsView.axaml
Labels: size/L
