Repository WalletWasabi/WalletWasabi, pull requests merged in 2020-03, with the labels that each got.

#3173 Order elements in some classes
  WalletWasabi/BitcoinCore/Endpointing/EndPointStrategy.cs
  WalletWasabi/BitcoinCore/Monitoring/P2pReconnector.cs
  WalletWasabi/BitcoinCore/Monitoring/RpcFeeProvider.cs
  WalletWasabi/BitcoinCore/Monitoring/RpcMonitor.cs
  WalletWasabi/BitcoinCore/Monitoring/RpcStatus.cs
Labels: size/M

#3148 Clean WasabiSetupRegtest.md
  WalletWasabi.Documentation/WasabiSetupRegtest.md
Labels: size/M

#3174 Refactoring CI yamls 2
  azure-pipelines-linux.yml
  azure-pipelines-osx.yml
  azure-pipelines-windows.yml
Labels: size/XS

#3175 Fix IsWatchOnly / IsHardwareWallet xamls
  WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoViewModel.cs
Labels: priority, size/S

#3177 Order elements in some classes
  WalletWasabi/BitcoinCore/P2pNode.cs
  WalletWasabi/BitcoinCore/Processes/BitcoindRpcProcessBridge.cs
  WalletWasabi/BitcoinCore/Processes/PidFile.cs
  WalletWasabi/BitcoinCore/RpcWrappedClient.cs
Labels: size/M

#3178 Implement WalletManager
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Tests/IntegrationTests/RegTests.cs
  WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs
  WalletWasabi/CoinJoin/Client/CoinJoinProcessor.cs
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/L

#3182 Dump version to v1.1.10.3
  WalletWasabi.Backend/wwwroot/index.html
  WalletWasabi/Helpers/Constants.cs
Labels: size/S

#3135 Count locked external keys to get consecutive unused keys
  WalletWasabi.Tests/UnitTests/KeyManagementTests.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
Labels: size/XS

#3186 Delete ManualTesting.md
  WalletWasabi.Documentation/ManualTesting.md
Labels: size/XS

#3167 Legal Documents Grammar/Syntax Edits
  WalletWasabi.Gui/Assets/LegalDocuments.txt
  WalletWasabi/Legal/Assets/LegalDocuments.txt
Labels: size/L

#3187 Nitpicking
  WalletWasabi.Documentation/ClientDeployment.md
  WalletWasabi.Gui/ViewModels/MainWindowViewModel.cs
Labels: size/S

#3184 Multi wallet daemon decoupled from global wallet service
  WalletWasabi.Gui/CommandLine/Daemon.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Gui/Tabs/WalletManager/LoadWalletViewModel.cs
Labels: size/M

#3191 Add LegalDocuments class code with unit tests
  WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
  WalletWasabi.Tests/UnitTests/LegalTests.cs
  WalletWasabi/Legal/LegalDocuments.cs
Labels: size/L

#3193 Order elements in some classes
  WalletWasabi/Blockchain/Keys/BlockchainState.cs
  WalletWasabi/Blockchain/Keys/HdPubKey.cs
  WalletWasabi/Blockchain/Mempool/MempoolService.cs
  WalletWasabi/Blockchain/P2p/P2pBehavior.cs
  WalletWasabi/Blockchain/P2p/TrustedP2pBehavior.cs
  WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs
Labels: size/L

#3185 Order elements in some classes
  WalletWasabi/Blockchain/BlockFilters/IndexBuilderService.cs
  WalletWasabi/Blockchain/BlockFilters/SyncInfo.cs
  WalletWasabi/Blockchain/BlockFilters/UtxoEntry.cs
  WalletWasabi/Blockchain/Blocks/BlockNotifier.cs
  WalletWasabi/Blockchain/Blocks/SmartHeader.cs
  WalletWasabi/Blockchain/Blocks/SmartHeaderChain.cs
Labels: size/L

#3192 Legal Documents
  WalletWasabi.Gui/Assets/LegalDocuments.txt
  WalletWasabi.Gui/Controls/MultiTextBox.cs
  WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Gui/Shell/Commands/HelpCommands.cs
  WalletWasabi.Gui/Tabs/LegalDocumentsView.xaml
  WalletWasabi.Gui/Tabs/LegalDocumentsViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/GenerateWalletView.xaml
  WalletWasabi.Gui/Tabs/WalletManager/GenerateWalletViewModel.cs
  WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
  WalletWasabi.Gui/ViewModels/TextResourceViewModelBase.cs
  WalletWasabi.Gui/ViewModels/WasabiDocumentTabViewModel.cs
Labels: size/XL

#3188 Bring out walletservice to a variable.
  WalletWasabi.Gui/Tabs/WalletManager/LoadWalletViewModel.cs
Labels: size/XS

#3199 Fix race condition on legal version check
  WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
Labels: priority, size/XS

#3202 Clean some xaml files
  WalletWasabi.Gui/Controls/GroupBox.xaml
  WalletWasabi.Gui/Controls/LockScreen/SlideLock.xaml
  WalletWasabi.Gui/Controls/MultiTextBox.xaml
  WalletWasabi.Gui/Controls/TogglePasswordBox.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionInfoTabView.xaml
  WalletWasabi.Gui/Icons/Icons.xaml
  WalletWasabi.Gui/Styles/Styles.xaml
Labels: size/L

#3181 Order elements in some classes
  WalletWasabi/Blockchain/Analysis/Clustering/Cluster.cs
  WalletWasabi/Blockchain/Analysis/Clustering/SmartLabel.cs
  WalletWasabi/Blockchain/Analysis/FeesEstimation/AllFeeEstimate.cs
  WalletWasabi/Blockchain/Analysis/FeesEstimation/FeeProviders.cs
  WalletWasabi/Blockchain/BlockFilters/History/ActionHistoryHelper.cs
  WalletWasabi/Blockchain/BlockFilters/History/ActionItem.cs
Labels: size/L

#3195 Order elements in some classes
  WalletWasabi/Blockchain/TransactionBuilding/BuildTransactionResult.cs
  WalletWasabi/Blockchain/TransactionBuilding/DestinationRequest.cs
  WalletWasabi/Blockchain/TransactionBuilding/FeeStrategy.cs
  WalletWasabi/Blockchain/TransactionBuilding/MoneyRequest.cs
  WalletWasabi/Blockchain/TransactionBuilding/PaymentIntent.cs
  WalletWasabi/Blockchain/TransactionBuilding/SmartCoinSelector.cs
Labels: size/L

#3198 Add Custom Change Address Feature
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
  WalletWasabi.Gui/Tabs/SettingsView.xaml
  WalletWasabi.Gui/Tabs/SettingsViewModel.cs
  WalletWasabi.Gui/UiConfig.cs
Labels: size/M

#3211 Update NBitcoin
  WalletWasabi/Helpers/NBitcoinHelpers.cs
  WalletWasabi/JsonConverters/KeyJsonConverter.cs
  WalletWasabi/WalletWasabi.csproj
Labels: size/S

#3218 Beautify throw exception
  WalletWasabi/BitcoinCore/Processes/BitcoindException.cs
  WalletWasabi/BitcoinCore/Processes/BitcoindRpcProcessBridge.cs
Labels: size/XS

#3224 Order elements in some classes
  WalletWasabi/Blockchain/Transactions/SmartTransaction.cs
  WalletWasabi/Blockchain/Transactions/TransactionBroadcastEntry.cs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
  WalletWasabi/Blockchain/Transactions/TransactionHistoryBuilder.cs
  WalletWasabi/Blockchain/Transactions/TransactionStore.cs
Labels: size/M

#3204 Order elements in some classes
  WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs
  WalletWasabi/Blockchain/TransactionOutputs/CoinsView.cs
  WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
Labels: size/M

#3219 Order elements in some classes
  WalletWasabi/Blockchain/TransactionProcessing/ProcessedResult.cs
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
  WalletWasabi/Blockchain/Transactions/Operations/Append.cs
  WalletWasabi/Blockchain/Transactions/Operations/Remove.cs
  WalletWasabi/Blockchain/Transactions/Operations/Update.cs
Labels: size/M

#3228 _cancelWalletServiceInitialization work 2
  WalletWasabi.Gui/CommandLine/Daemon.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Gui/Tabs/WalletManager/LoadWalletViewModel.cs
  WalletWasabi.Tests/RegressionTests/BuildTests.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/L

#3229 Multiwallet-ing dequeue logic
  WalletWasabi.Gui/Dialogs/CannotCloseDialogViewModel.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Gui/Rpc/WasabiJsonRpcService.cs
  WalletWasabi.Gui/Tabs/WalletManager/LoadWalletViewModel.cs
  WalletWasabi.Tests/RegressionTests/BuildTests.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/L

#3230 [CodeScene] Multiwallet-ing dequeue logic
  WalletWasabi.Gui/Dialogs/CannotCloseDialogViewModel.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Gui/Rpc/WasabiJsonRpcService.cs
  WalletWasabi.Gui/Tabs/WalletManager/LoadWalletViewModel.cs
  WalletWasabi.Tests/RegressionTests/BuildTests.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/L

#3201 Lock receive address
  WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs
  WalletWasabi.Gui/Icons/Icons.xaml
  WalletWasabi.Gui/ViewModels/AddressViewModel.cs
Labels: size/M

#3237 Multiwallet-ing StatusBar alternative
  WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
  WalletWasabi/Services/WalletService.cs
Labels: size/XS

#3232 Order elements in some classes
  WalletWasabi/CoinJoin/Common/Models/ActiveOutput.cs
  WalletWasabi/CoinJoin/Common/Models/HdPubKeyBlindedPair.cs
  WalletWasabi/CoinJoin/Coordinator/Banning/BannedUtxo.cs
  WalletWasabi/CoinJoin/Coordinator/Banning/UtxoReferee.cs
  WalletWasabi/CoinJoin/Coordinator/MixingLevels/MixingLevelCollection.cs
  WalletWasabi/CoinJoin/Coordinator/Participants/Alice.cs
  WalletWasabi/CoinJoin/Coordinator/Participants/Bob.cs
Labels: size/L

#3231 Order elements in some classes
  WalletWasabi/CoinJoin/Client/Clients/AliceClient.cs
  WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
  WalletWasabi/CoinJoin/Client/Clients/Queuing/DequeueResult.cs
  WalletWasabi/CoinJoin/Client/CoinJoinProcessor.cs
  WalletWasabi/CoinJoin/Client/Rounds/ClientRound.cs
  WalletWasabi/CoinJoin/Client/Rounds/ClientRoundRegistration.cs
  WalletWasabi/CoinJoin/Client/Rounds/ClientState.cs
Labels: size/L

#3244 Remove walletservice singleton from MainWindow
  WalletWasabi.Gui/MainWindow.xaml.cs
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/S

#3243 Fix bug: mixall + keepalive
  WalletWasabi.Gui/CommandLine/Daemon.cs
Labels: size/XS

#3239 Improve the dequeuing of coins on exit
  WalletWasabi.Gui/Dialogs/CannotCloseDialogView.xaml
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Gui/Tabs/WalletManager/LoadWalletViewModel.cs
  WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
Labels: size/XS

#3238 Add CoinJoin status monitor
  WalletWasabi.Backend/Controllers/BlockchainController.cs
  WalletWasabi/Backend/Models/Responses/StatusResponse.cs
  WalletWasabi/CoinJoin/Coordinator/Coordinator.cs
Labels: size/S

#3241 Order elements in some classes
  WalletWasabi/Exceptions/InsufficientBalanceException.cs
  WalletWasabi/Exceptions/InvalidTxException.cs
  WalletWasabi/Exceptions/TorSocks5FailureResponseException.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/DataEncodation/InputRecognition/RecognitionStruct.cs
Labels: size/S

#3240 Order elements in some classes
  WalletWasabi/CoinJoin/Coordinator/Coordinator.cs
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRoundConfig.cs
Labels: size/L

#3251 Improve GUI folder structure
  WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
  WalletWasabi.Gui/Suggestions/SuggestLabelView.xaml
  WalletWasabi.Gui/Suggestions/SuggestLabelView.xaml.cs
  WalletWasabi.Gui/Suggestions/SuggestLabelViewModel.cs
  WalletWasabi.Gui/Suggestions/SuggestionBehavior.cs
  WalletWasabi.Gui/Suggestions/SuggestionViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/GenerateWallets/GenerateWalletSuccessView.xaml
  WalletWasabi.Gui/Tabs/WalletManager/GenerateWallets/GenerateWalletSuccessView.xaml.cs
  WalletWasabi.Gui/Tabs/WalletManager/GenerateWallets/GenerateWalletSuccessViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/GenerateWallets/GenerateWalletView.xaml
  WalletWasabi.Gui/Tabs/WalletManager/GenerateWallets/GenerateWalletView.xaml.cs
  WalletWasabi.Gui/Tabs/WalletManager/GenerateWallets/GenerateWalletViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletType.cs
  WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletView.xaml
  WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletView.xaml.cs
  WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/RecoverWallets/RecoverWalletView.xaml
  WalletWasabi.Gui/Tabs/WalletManager/RecoverWallets/RecoverWalletView.xaml.cs
  WalletWasabi.Gui/Tabs/WalletManager/RecoverWallets/RecoverWalletViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/WalletManagerViewModel.cs
Labels: size/M

#3253 Creating walletDirectories class
  WalletWasabi.Gui/CommandLine/Daemon.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Gui/Rpc/WasabiJsonRpcService.cs
  WalletWasabi.Gui/Shell/Commands/DiskCommands.cs
  WalletWasabi.Gui/Shell/Commands/ToolCommands.cs
  WalletWasabi.Gui/Tabs/WalletManager/GenerateWallets/GenerateWalletViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/RecoverWallets/RecoverWalletViewModel.cs
  WalletWasabi.Gui/ViewModels/MainWindowViewModel.cs
  WalletWasabi.Tests/UnitTests/WalletDirTests.cs
  WalletWasabi.Tests/WalletWasabi.Tests.csproj
  WalletWasabi/Wallets/WalletDirectories.cs
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/L

#3255 [Codescene] Wallets dir
  WalletWasabi.Gui/CommandLine/Daemon.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Gui/Rpc/WasabiJsonRpcService.cs
  WalletWasabi.Gui/Shell/Commands/DiskCommands.cs
  WalletWasabi.Gui/Shell/Commands/ToolCommands.cs
  WalletWasabi.Gui/Tabs/WalletManager/GenerateWallets/GenerateWalletViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/RecoverWallets/RecoverWalletViewModel.cs
  WalletWasabi.Gui/ViewModels/MainWindowViewModel.cs
  WalletWasabi.Tests/UnitTests/WalletDirTests.cs
  WalletWasabi.Tests/WalletWasabi.Tests.csproj
  WalletWasabi/Wallets/WalletDirectories.cs
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/L

#3250 Trigger both validation on Address or CustomChangeAddress
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
Labels: size/S

#3245 Implement mix to another wallet with Daemon
  WalletWasabi.Gui/CommandLine/Daemon.cs
  WalletWasabi.Gui/CommandLine/MixerCommand.cs
  WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
Labels: size/M

#3246 Legal Documents as a LockScreen
  WalletWasabi.Gui/Controls/LockScreen/LockScreen.xaml
  WalletWasabi.Gui/Controls/LockScreen/LockScreenViewModelBase.cs
  WalletWasabi.Gui/Controls/LockScreen/PinLockScreenViewModel.cs
  WalletWasabi.Gui/Controls/LockScreen/SlideLock.cs
  WalletWasabi.Gui/Controls/LockScreen/SlideLockScreenViewModel.cs
  WalletWasabi.Gui/Controls/LockScreen/WasabiLockScreenViewModelBase.cs
  WalletWasabi.Gui/MainWindow.xaml
  WalletWasabi.Gui/Tabs/LegalDocumentsView.xaml
  WalletWasabi.Gui/Tabs/LegalDocumentsViewModel.cs
  WalletWasabi.Gui/ViewModels/MainWindowViewModel.cs
  WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
  WalletWasabi.Gui/ViewModels/WasabiDocumentTabViewModel.cs
Labels: size/L

#3263 Order elements in some classes
  WalletWasabi/Gma/QrCodeNet/Encoding/BitList.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/BitMatrixBase.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/MatrixPoint.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/MatrixRectangle.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/MatrixSize.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/QRCodeConstantVariable.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/ReedSolomon/GaloisField256.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/ReedSolomon/GeneratorPolynomial.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/ReedSolomon/PolyDivideStruct.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/ReedSolomon/Polynomial.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/StateMatrix.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/TriStateMatrix.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/VersionDetail.cs
Labels: size/L

#3262 Order elements in some classes
  WalletWasabi/Gma/QrCodeNet/Encoding/DataEncodation/ECISet.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/DataEncodation/EncodationStruct.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/EncodingRegion/FormatInformation.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/EncodingRegion/VersionInformation.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/Positioning/Stencils/AlignmentPattern.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/Positioning/Stencils/PatternStencilBase.cs
Labels: size/L

#3270 Order KeyManager
  WalletWasabi/Blockchain/Keys/KeyManager.cs
Labels: size/L

#3269 Bring logger initialization forward
  WalletWasabi.Gui/CommandLine/CommandInterpreter.cs
  WalletWasabi.Gui/Global.cs
Labels: size/XS

#3265 Remove TxoRef (part 1)
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi.Tests/UnitTests/SmartCoinTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
  WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs
  WalletWasabi/Blockchain/TransactionOutputs/CoinsView.cs
  WalletWasabi/Blockchain/TransactionOutputs/ICoinsView.cs
  WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
  WalletWasabi/Extensions/NBitcoinExtensions.cs
Labels: size/M

#3266 Remove TxoRef (part 2)
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
  WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
  WalletWasabi/CoinJoin/Client/Rounds/ClientState.cs
  WalletWasabi/Services/WalletService.cs
Labels: size/M

#3271 Move WalletService to Wallets folder
  WalletWasabi.Gui/CommandLine/Daemon.cs
  WalletWasabi.Gui/Controls/WalletExplorer/BuildTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/CoinViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletAdvancedViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletViewModel.cs
  WalletWasabi.Gui/Suggestions/SuggestLabelViewModel.cs
  WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
  WalletWasabi.Tests/IntegrationTests/P2pTests.cs
  WalletWasabi.Tests/RegressionTests/Common.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
  WalletWasabi/Blockchain/Transactions/TransactionHistoryBuilder.cs
  WalletWasabi/Wallets/WalletService.cs
Labels: size/M

#3274 Rename WalletService to Wallet
  WalletWasabi.Gui/CommandLine/Daemon.cs
  WalletWasabi.Gui/Controls/WalletExplorer/BuildTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/CoinViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletAdvancedViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletViewModel.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Gui/Rpc/WasabiJsonRpcService.cs
  WalletWasabi.Gui/Suggestions/SuggestLabelViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletViewModel.cs
  WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
  WalletWasabi.Tests/IntegrationTests/P2pTests.cs
  WalletWasabi.Tests/RegressionTests/BuildTests.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/RegressionTests/Common.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi.Tests/RegressionTests/WalletTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
  WalletWasabi/Blockchain/Transactions/TransactionHistoryBuilder.cs
  WalletWasabi/CoinJoin/Client/CoinJoinProcessor.cs
  WalletWasabi/Wallets/Wallet.cs
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/XL

#3268 Make sure daemon password console works on Windows 7
  WalletWasabi/Helpers/PasswordConsole.cs
Labels: size/M

#3276 Add WalletState
  WalletWasabi.Tests/IntegrationTests/P2pTests.cs
  WalletWasabi.Tests/RegressionTests/BuildTests.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi.Tests/RegressionTests/WalletTests.cs
  WalletWasabi/Wallets/Wallet.cs
  WalletWasabi/Wallets/WalletManager.cs
  WalletWasabi/Wallets/WalletState.cs
Labels: size/M

#3277 Pipe events
  WalletWasabi/Wallets/Wallet.cs
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/M

#3280 Review the logs
  WalletWasabi.Documentation/BackendDeployment.md
Labels: size/XS

#3281 [Draft] Make config stuff sync
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Backend/InitConfigStartupTask.cs
  WalletWasabi.Gui/Config.cs
  WalletWasabi.Gui/Controls/MultiTextBox.cs
  WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletViewModel.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Gui/MainWindow.xaml.cs
  WalletWasabi.Gui/Program.cs
  WalletWasabi.Gui/Tabs/SettingsViewModel.cs
  WalletWasabi.Gui/UiConfig.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/RegressionTests/DosTests.cs
  WalletWasabi.Tests/XunitConfiguration/RegTestFixture.cs
  WalletWasabi/Bases/ConfigBase.cs
  WalletWasabi/CoinJoin/Coordinator/Coordinator.cs
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRoundConfig.cs
  WalletWasabi/Interfaces/IConfig.cs
  WalletWasabi/Services/ConfigWatcher.cs
Labels: size/L

#3252 update to new avalonia release
  WalletWasabi.Gui/WalletWasabi.Gui.csproj
Labels: size/XS

#3279 Remove TxoRef (part 4)
  WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
  WalletWasabi.Tests/XunitConfiguration/LiveServerTestsFixture.cs
Labels: size/M

#3286 Continue towards multiwallet
  WalletWasabi.Gui/Controls/WalletExplorer/WalletAdvancedViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletViewModel.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Tests/IntegrationTests/P2pTests.cs
  WalletWasabi.Tests/RegressionTests/BuildTests.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi.Tests/RegressionTests/WalletTests.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs
  WalletWasabi/Wallets/Wallet.cs
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/L

#3278 Remove TxoRef (part 3)
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
  WalletWasabi.Gui/Rpc/WasabiJsonRpcService.cs
  WalletWasabi.Tests/RegressionTests/BuildTests.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
  WalletWasabi/CoinJoin/Client/Rounds/ClientState.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/M

#3294 Move SetLastAccessTimeForNow
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/S

#3300 Revert "Move SetLastAccessTimeForNow"
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/S

#3292 Order elements in some classes
  WalletWasabi/Io/DigestableSafeMutexIoManager.cs
  WalletWasabi/Io/IoManager.cs
  WalletWasabi/Io/MutexIoManager.cs
  WalletWasabi/Io/SafeMutexIoManager.cs
  WalletWasabi/JsonConverters/EndPointJsonConverter.cs
  WalletWasabi/Logging/BenchmarkLogger.cs
  WalletWasabi/Logging/Logger.cs
Labels: size/M

#3293 Order elements in some classes
  WalletWasabi/Microservices/ProcessBridge.cs
  WalletWasabi/Models/ErrorDescriptor.cs
  WalletWasabi/Models/ErrorDescriptors.cs
  WalletWasabi/Models/Height.cs
  WalletWasabi/Models/ServiceConfiguration.cs
  WalletWasabi/Mono/ArgumentSource.cs
  WalletWasabi/Mono/Command.cs
  WalletWasabi/Mono/CommandOption.cs
Labels: size/L

#3288 Order elements in some classes
  WalletWasabi/Http/Models/HeaderField.cs
  WalletWasabi/Http/Models/HttpProtocol.cs
  WalletWasabi/Http/Models/RequestLine.cs
  WalletWasabi/Http/Models/StartLine.cs
  WalletWasabi/Http/Models/StatusLine.cs
  WalletWasabi/Hwi/Exceptions/HwiException.cs
  WalletWasabi/Hwi/HwiClient.cs
  WalletWasabi/Hwi/Models/HwiEnumerateEntry.cs
  WalletWasabi/Hwi/Models/HwiOption.cs
Labels: size/L

#3306 fix exchange rate unit: USD/BTC
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
  WalletWasabi.Gui/Converters/UsdExchangeRateAmountToolTipConverter.cs
Labels: size/XS

#3285 Order elements in some classes
  WalletWasabi/Helpers/ByteArrayBuilder.cs
  WalletWasabi/Helpers/ByteHelpers.cs
  WalletWasabi/Helpers/EventsAwaiter.cs
  WalletWasabi/Helpers/NBitcoinHelpers.cs
  WalletWasabi/Helpers/RuntimeParams.cs
Labels: size/M

#3296 Order elements in some classes
  WalletWasabi/Nito/Collections/Deque.cs
  WalletWasabi/Nito/Disposables/Internals/BoundAction.cs
Labels: size/L

#3304 Remove TxoRef from protocol message
  WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/RegressionTests/DosTests.cs
  WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
  WalletWasabi/Blockchain/TransactionOutputs/TxoRef.cs
  WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
  WalletWasabi/CoinJoin/Common/Models/InputProofModel.cs
  WalletWasabi/Extensions/NBitcoinExtensions.cs
  WalletWasabi/JsonConverters/OutPointAsTxoRefJsonConverter.cs
Labels: size/L

#3295 Order elements in some classes
  WalletWasabi/Mono/CommandOptionSet.cs
  WalletWasabi/Mono/CommandSet.cs
  WalletWasabi/Mono/Option.cs
  WalletWasabi/Mono/OptionSet.cs
  WalletWasabi/Mono/OptionValueCollection.cs
  WalletWasabi/Nito/AsyncEx/AsyncMutex.cs
Labels: size/L

#3307 Use the IRpcClient abstraction
  WalletWasabi.Backend/Controllers/BlockchainController.cs
  WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Backend/InitConfigStartupTask.cs
  WalletWasabi.Tests/RegressionTests/BackendTests.cs
  WalletWasabi.Tests/RegressionTests/BuildTests.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/RegressionTests/Common.cs
  WalletWasabi.Tests/RegressionTests/DosTests.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi.Tests/RegressionTests/WalletTests.cs
  WalletWasabi.Tests/UnitTests/BlockNotifierTests.cs
  WalletWasabi.Tests/UnitTests/MockRpcClient.cs
  WalletWasabi/BitcoinCore/CoreNode.cs
  WalletWasabi/BitcoinCore/IRPCClient.cs
  WalletWasabi/BitcoinCore/Monitoring/RpcFeeProvider.cs
  WalletWasabi/BitcoinCore/Monitoring/RpcMonitor.cs
  WalletWasabi/BitcoinCore/Processes/BitcoindRpcProcessBridge.cs
  WalletWasabi/BitcoinCore/RpcClientBase.cs
  WalletWasabi/BitcoinCore/RpcWrappedClient.cs
  WalletWasabi/Blockchain/BlockFilters/IndexBuilderService.cs
  WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs
  WalletWasabi/CoinJoin/Client/CoinJoinProcessor.cs
  WalletWasabi/CoinJoin/Coordinator/Banning/UtxoReferee.cs
  WalletWasabi/CoinJoin/Coordinator/Coordinator.cs
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
  WalletWasabi/Extensions/RPCClientExtensions.cs
Labels: size/XL

#3305 Multiwallet business logic final
  WalletWasabi.Gui/CommandLine/CommandInterpreter.cs
  WalletWasabi.Gui/CommandLine/Daemon.cs
  WalletWasabi.Gui/CommandLine/PasswordFinderCommand.cs
  WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Gui/Suggestions/SuggestLabelViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletViewModel.cs
  WalletWasabi.Tests/IntegrationTests/P2pTests.cs
  WalletWasabi.Tests/RegressionTests/BuildTests.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi.Tests/RegressionTests/WalletTests.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/Blockchain/Transactions/AllTransactionStore.cs
  WalletWasabi/Wallets/Wallet.cs
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/XL

#3315 Make StartWalletAsync public
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/XS

#3316 Use UTC for LastAccessTime
  WalletWasabi/Blockchain/Keys/KeyManager.cs
Labels: size/XS

#3319 Order elements in some classes
  WalletWasabi/TorSocks5/Models/Messages/MethodSelectionResponse.cs
  WalletWasabi/TorSocks5/Models/Messages/TorSocks5Request.cs
  WalletWasabi/TorSocks5/Models/Messages/TorSocks5Response.cs
  WalletWasabi/TorSocks5/Models/Messages/UsernamePasswordRequest.cs
  WalletWasabi/TorSocks5/Models/Messages/UsernamePasswordResponse.cs
  WalletWasabi/TorSocks5/Models/Messages/VersionMethodRequest.cs
Labels: size/L

#3324 Implement TryEstimateSmartFeeAsync to fix backend
  WalletWasabi.Tests/UnitTests/MockRpcClient.cs
  WalletWasabi/BitcoinCore/IRPCClient.cs
  WalletWasabi/BitcoinCore/RpcClientBase.cs
Labels: size/M

#3322 Order elements in some classes
  WalletWasabi/Wallets/Wallet.cs
  WalletWasabi/Wallets/WalletManager.cs
  WalletWasabi/WebClients/BlockchainInfo/BlockchainInfoExchangeRateProvider.cs
Labels: size/L

#3326 Add WalletStateChanged event to WalletManager
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/S

#3313 Remove unreachable case
  WalletWasabi.Gui/Config.cs
Labels: size/XS

#3320 Order elements in some classes
  WalletWasabi/TorSocks5/ITorHttpClient.cs
  WalletWasabi/TorSocks5/TorHttpClient.cs
  WalletWasabi/TorSocks5/TorProcessManager.cs
  WalletWasabi/TorSocks5/TorSocks5Client.cs
Labels: size/L

#3312 Order elements in some classes
  WalletWasabi/TorSocks5/Models/Fields/OctetFields/AuthVerField.cs
  WalletWasabi/TorSocks5/Models/Fields/OctetFields/CmdField.cs
  WalletWasabi/TorSocks5/Models/Fields/OctetFields/MethodField.cs
  WalletWasabi/TorSocks5/Models/Fields/OctetFields/NMethodsField.cs
  WalletWasabi/TorSocks5/Models/Fields/OctetFields/PLenField.cs
  WalletWasabi/TorSocks5/Models/Fields/OctetFields/RepField.cs
  WalletWasabi/TorSocks5/Models/Fields/OctetFields/RsvField.cs
  WalletWasabi/TorSocks5/Models/Fields/OctetFields/ULenField.cs
  WalletWasabi/TorSocks5/Models/Fields/OctetFields/VerField.cs
Labels: size/L

#3318 [2] Remove Hardware Wallet Stuff from LoadWalletView
  WalletWasabi.Gui/Tabs/WalletManager/HardwareWallets/ConnectHardwareWalletViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletView.xaml
  WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletViewModel.cs
Labels: size/M

#3287 Multiwallet wallet explorer
  WalletWasabi.Gui/Controls/WalletExplorer/ClosedWalletViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletViewModelBase.cs
  WalletWasabi.Gui/Icons/Icons.xaml
  WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletViewModel.cs
Labels: size/L

#3336 Remove unused function
  WalletWasabi.Gui/Tabs/WalletManager/WalletManagerViewModel.cs
Labels: size/XS

#3329 Fix regtest
  WalletWasabi.Tests/RegressionTests/SendTests.cs
Labels: size/XS

#3314 Interpolation
  .editorconfig
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Gui/Rpc/WasabiJsonRpcService.cs
  WalletWasabi.Packager/MacSignTools.cs
  WalletWasabi.Tests/Helpers/TestNodeBuilder.cs
  WalletWasabi.Tests/UnitTests/AsyncMutexTests.cs
  WalletWasabi/Blockchain/BlockFilters/StartingFilters.cs
  WalletWasabi/CoinJoin/Coordinator/Banning/BannedUtxo.cs
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
  WalletWasabi/Helpers/EndPointParser.cs
  WalletWasabi/Nito/AsyncEx/AsyncMutex.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/M

#3350 Fix on Windows, remembering maximized / normal window size.
  WalletWasabi.Gui/MainWindow.xaml
  WalletWasabi.Gui/MainWindow.xaml.cs
Labels: size/S

#3333 Add WalletAdded event to WalletManager
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/XS

#3354 Specify Tor data dir arg to be our own directory
  WalletWasabi/TorSocks5/TorProcessManager.cs
Labels: size/XS

#3332 sync wallet explorer selection with selected tab
  WalletWasabi.Gui/Controls/WalletExplorer/ClosedWalletViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletAdvancedViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletViewModel.cs
  WalletWasabi.Gui/ViewModels/WasabiDocumentTabViewModel.cs
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/L

#3357 use expression bodies
  WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletViewModelBase.cs
Labels: size/S

#3360 [Trivial] Simplify name
  WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerViewModel.cs
  WalletWasabi.Gui/Helpers/AvalonStudioShellExtensions.cs
Labels: size/XS

#3362 [Refactoring] Extract method
  WalletWasabi.Gui/Controls/WalletExplorer/WalletViewModel.cs
Labels: size/S

#3338 [3.2] Remove Hardware Wallet Stuff from LoadWalletView
  WalletWasabi.Gui/Tabs/WalletManager/HardwareWallets/ConnectHardwareWalletViewModel.cs
Labels: size/L

#3364 Remove 'is true' when not neccessary
  WalletWasabi.Gui/Behaviors/PasteAddressOnClickBehavior.cs
  WalletWasabi.Gui/Controls/MultiTextBox.cs
  WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletViewModel.cs
  WalletWasabi.Gui/Converters/LurkingWifeModeStringConverter.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Gui/Tabs/SettingsViewModel.cs
  WalletWasabi.Gui/ViewModels/AddressViewModel.cs
Labels: size/M

#3359 [Trivial] Combine two if statements
  WalletWasabi.Gui/Controls/WalletExplorer/WalletViewModel.cs
Labels: size/S

#3355 Order elements in some classes
  WalletWasabi/WebClients/Coinbase/CoinbaseExchangeRateProvider.cs
  WalletWasabi/WebClients/Gemini/GeminiExchangeRateProvider.cs
  WalletWasabi/WebClients/ItBit/ItBitExchangeRateProvider.cs
  WalletWasabi/WebClients/SmartBit/SmartBitClient.cs
  WalletWasabi/WebClients/SmartBit/SmartBitExchangeRateProvider.cs
  WalletWasabi/WebClients/Wasabi/WasabiClient.cs
Labels: size/M

#3369 Clear IsBusy on Wallet load error
  WalletWasabi.Gui/Controls/WalletExplorer/ClosedWalletViewModel.cs
Labels: size/XS

#3358 [4] Remove Hardware Wallet Stuff from LoadWalletView
  WalletWasabi.Gui/Models/LoadWalletEntry.cs
  WalletWasabi.Gui/Tabs/WalletManager/HardwareWallets/ConnectHardwareWalletViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/HardwareWallets/HardwareWalletViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletType.cs
  WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletViewModel.cs
Labels: size/L

#3366 Correct fee percent log message
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
Labels: size/XS

#3374 Fix DivideByZero exception
  WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
Labels: size/XS

#3371 Multiwalleting generate wallet
  WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/GenerateWallets/GenerateWalletSuccessViewModel.cs
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/S

#3380 Add GetWallets method to WalletManager
  WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerViewModel.cs
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/S

#3375 update avalonia with bug fixes for release.
  WalletWasabi.Gui/WalletWasabi.Gui.csproj
Labels: size/XS

#3383 Order elements in some classes
  WalletWasabi.Backend/Config.cs
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Backend/InitConfigStartupTask.cs
  WalletWasabi.Backend/Startup.cs
  WalletWasabi.Backend/WebsiteTorifier.cs
Labels: size/M

#3382 Order elements in some classes
  WalletWasabi.Backend/Controllers/BatchController.cs
  WalletWasabi.Backend/Controllers/BlockchainController.cs
  WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
  WalletWasabi.Backend/Controllers/OffchainController.cs
Labels: size/M

#3384 Wallet explorer utility buttons.
  WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletViewModel.cs
  WalletWasabi.Gui/Icons/Icons.xaml
  WalletWasabi.Gui/ViewModels/IWalletViewModel.cs
  WalletWasabi.Gui/ViewModels/WasabiDocumentTabViewModel.cs
Labels: size/L

#3386 Fix the selection of the wallet in the Password Test tab
  WalletWasabi.Gui/Tabs/WalletManager/GenerateWallets/GenerateWalletSuccessViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/WalletManagerViewModel.cs
Labels: size/S

#3387 fix right click anywhere on WalletItem
  WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerView.xaml
Labels: size/XS

#3388 Align WalletExplorer's Header text & Icons
  WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerView.xaml
Labels: size/M

#3385 Indicate correctly that the Wallet is being Started
  WalletWasabi.Gui/Controls/WalletExplorer/ClosedWalletViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletViewModelBase.cs
  WalletWasabi.Gui/Tabs/WalletManager/HardwareWallets/ConnectHardwareWalletViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletViewModel.cs
  WalletWasabi/Wallets/Wallet.cs
  WalletWasabi/Wallets/WalletManager.cs
  WalletWasabi/Wallets/WalletState.cs
Labels: size/M

#3390 Make Wallet explorer context menu consistent from main menu
  WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerView.xaml
Labels: size/XS

#3389 Dispose WalletManagerView properly
  WalletWasabi.Gui/Tabs/WalletManager/WalletManagerViewModel.cs
Labels: size/M

#3392 Fix double click outside text (Load Wallet tab)
  WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletView.xaml
Labels: size/XS

#3381 Multiwalleting LoadWalletViewModel
  WalletWasabi.Gui/Models/LoadWalletEntry.cs
  WalletWasabi.Gui/Rpc/WasabiJsonRpcService.cs
  WalletWasabi.Gui/Tabs/WalletManager/HardwareWallets/ConnectHardwareWalletViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/RecoverWallets/RecoverWalletViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/WalletManagerViewModel.cs
Labels: size/L

#3395 Fix HistoryTab not updating
  WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs
Labels: size/XS

#3400 Fix a lot of bugs
  WalletWasabi.Gui/Controls/WalletExplorer/ClosedWalletViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletViewModelBase.cs
  WalletWasabi.Gui/Converters/WalletLoadingBoolConverter.cs
  WalletWasabi.Gui/Tabs/WalletManager/HardwareWallets/ConnectHardwareWalletViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletView.xaml
  WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletViewModel.cs
  WalletWasabi.Gui/ViewModels/WasabiDocumentTabViewModel.cs
Labels: size/L

#3331 RPC extension GetVerboseBlock verbosity 3
  WalletWasabi.Tests/UnitTests/BitcoinCore/RpcBasedTests.cs
  WalletWasabi.Tests/UnitTests/MockRpcClient.cs
  WalletWasabi/BitcoinCore/IRPCClient.cs
  WalletWasabi/BitcoinCore/RpcClientBase.cs
  WalletWasabi/BitcoinCore/RpcModels/RpcPubkeyType.cs
  WalletWasabi/BitcoinCore/RpcModels/VerboseBlockInfo.cs
  WalletWasabi/BitcoinCore/RpcModels/VerboseInputInfo.cs
  WalletWasabi/BitcoinCore/RpcModels/VerboseOutputInfo.cs
  WalletWasabi/BitcoinCore/RpcModels/VerboseTransactionInfo.cs
  WalletWasabi/BitcoinCore/RpcParser.cs
Labels: size/L

#3409 Fix NRE
  WalletWasabi/Bases/PeriodicRunner.cs
Labels: size/S

#3413 Remove unused variable
  WalletWasabi.Gui/MainWindow.xaml.cs
Labels: size/XS

#3410 Prevent opening stopped wallets
  WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerViewModel.cs
Labels: size/XS

#3414 Fix Hardware wallet loading
  WalletWasabi.Gui/Tabs/WalletManager/HardwareWallets/ConnectHardwareWalletViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/RecoverWallets/RecoverWalletViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/WalletManagerViewModel.cs
Labels: size/L
