Repository WalletWasabi/WalletWasabi, pull requests merged in 2020-09, with the labels that each got.

#4264 Coordinator SecretKey and Parameters
  WalletWasabi.Tests/UnitTests/Crypto/CoordinatorKeyTests.cs
  WalletWasabi/Crypto/CoordinatorParameters.cs
  WalletWasabi/Crypto/CoordinatorSecretKey.cs
  WalletWasabi/Crypto/CryptoGuards.cs
  WalletWasabi/Crypto/Extensions.cs
  WalletWasabi/Crypto/GroupElementVector.cs
  WalletWasabi/Crypto/ScalarVector.cs
Labels: size/L

#4261 Make P2pBasedTests serial.
  WalletWasabi.Tests/UnitTests/BitcoinCore/SerialP2pBasedTests.cs
Labels: size/XS

#4275 Fix CodeFactor style issues
  WalletWasabi/BitcoinCore/Rpc/RpcErrorTools.cs
  WalletWasabi/Extensions/RPCClientExtensions.cs
Labels: size/S

#4276 Create robots.txt
  WalletWasabi.Backend/wwwroot/robots.txt
Labels: size/XS

#4273 Fix CodeFactor issues
  WalletWasabi.Tests/UnitTests/HashChainTests.cs
Labels: size/M

#4256 [WabiSabi] Transcript Object
  WalletWasabi.Tests/UnitTests/Crypto/TestTranscript.cs
  WalletWasabi.Tests/UnitTests/Crypto/TranscriptTests.cs
  WalletWasabi/Crypto/StrobeProtocol/Strobe.cs
  WalletWasabi/Crypto/ZeroKnowledge/Transcript.cs
Labels: size/L

#4272 Fix horizontal scroll bar issues
  WalletWasabi.Gui/Controls/WalletExplorer/CoinInfoTabView.xaml
  WalletWasabi.Gui/Tabs/SettingsView.xaml
Labels: size/M

#4279 Allow stalebot to act on priority issues and PRs
  .github/stale.yml
Labels: size/XS

#3739 Bandwidth improvement v4
  WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
  WalletWasabi.Backend/Startup.cs
  WalletWasabi.Tests/RegressionTests/BackendTests.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/RegressionTests/DosTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/BlindingTests.cs
  WalletWasabi/CoinJoin/Common/Crypto/SchnorrPubKey.cs
  WalletWasabi/CoinJoin/Coordinator/MixingLevels/MixingLevel.cs
  WalletWasabi/CoinJoin/Coordinator/MixingLevels/MixingLevelCollection.cs
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
  WalletWasabi/CoinJoin/Coordinator/Rounds/RoundNonceProvider.cs
  WalletWasabi/Crypto/SchnorrBlindingSignature.cs
  WalletWasabi/Extensions/NBitcoinExtensions.cs
  WalletWasabi/Helpers/Constants.cs
Labels: size/L

#4271 [Wabisabi] MAC generation
  WalletWasabi.Tests/UnitTests/Crypto/GroupElements/GeneralTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/GroupElements/GeneratorTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/MacTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/KnowledgeOfDlogTests.cs
  WalletWasabi/Crypto/CoordinatorParameters.cs
  WalletWasabi/Crypto/CryptoGuards.cs
  WalletWasabi/Crypto/Groups/Generators.cs
  WalletWasabi/Crypto/Groups/GroupElement.cs
  WalletWasabi/Crypto/Mac.cs
  WalletWasabi/Crypto/ZeroKnowledge/Transcript.cs
Labels: size/L

#4277 [WabiSabi] Add Equation class for linear relation proofs
  WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/LinearRelationTests.cs
  WalletWasabi/Crypto/CryptoGuards.cs
  WalletWasabi/Crypto/ScalarVector.cs
  WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Equation.cs
  WalletWasabi/Crypto/ZeroKnowledge/Statement.cs
Labels: size/L

#4286 Open Wasabi in normal size by default.
  WalletWasabi.Gui/UiConfig.cs
Labels: size/XS

#4288 Add pointover border to wallet explorer actions so it looks more like…
  WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerView.xaml
Labels: size/S

#4283 Change "Price" to "BTC/USD"
  WalletWasabi.Gui/Controls/StatusBar.xaml
Labels: size/XS

#4287 Hwi/Models: add BitBox02 support
  WalletWasabi/Hwi/Models/HardwareWalletModels.cs
Labels: size/XS

#4280 [WabiSabi] Linear relation
  WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/LinearRelationTests.cs
  WalletWasabi/Crypto/Extensions.cs
  WalletWasabi/Crypto/GroupElementVector.cs
  WalletWasabi/Crypto/ScalarVector.cs
  WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Equation.cs
  WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Knowledge.cs
  WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Statement.cs
Labels: size/L

#4289 Don't order wallets by wallet state
  WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletViewModel.cs
Labels: size/XS

#4297 Remove SmartBit
  WalletWasabi.Tests/IntegrationTests/ExternalApiTests.cs
  WalletWasabi/WebClients/ExchangeRateProviders.cs
  WalletWasabi/WebClients/SmartBit/Models/SmartBitExchangeRate.cs
  WalletWasabi/WebClients/SmartBit/SmartBitClient.cs
  WalletWasabi/WebClients/SmartBit/SmartBitExchangeRateProvider.cs
Labels: size/L

#4298 Fix CheckUpdatesTestsAsync
  WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
Labels: size/XS

#4294 Tests: Remove 'Serial' prefix.
  WalletWasabi.Tests/UnitTests/Bases/PeriodicRunnerTests.cs
  WalletWasabi.Tests/UnitTests/BitcoinCore/NodeBuildingTests.cs
  WalletWasabi.Tests/UnitTests/BitcoinCore/P2pBasedTests.cs
  WalletWasabi.Tests/UnitTests/BitcoinCore/SerialNodeBuildingTests.cs
  WalletWasabi.Tests/UnitTests/BlockNotifierTests.cs
  WalletWasabi.Tests/UnitTests/Clients/SingleInstanceCheckerTests.cs
  WalletWasabi.Tests/UnitTests/Hwi/DefaultResponseTests.cs
  WalletWasabi.Tests/UnitTests/Hwi/SerialDefaultResponseTests.cs
  WalletWasabi.Tests/UnitTests/MemoryTests.cs
  WalletWasabi.Tests/UnitTests/SerialMemoryTests.cs
  WalletWasabi.Tests/XunitConfiguration/SerialCollectionDefinition.cs
Labels: size/L

#4300 Remove nullable warning.
  WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
Labels: size/XS

#4311 Apply Visual Studio Code Cleanup with the least intrusive configuration
  WalletWasabi.Gui/CommandLine/Daemon.cs
  WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs
  WalletWasabi.Tests/UnitTests/Crypto/MacTests.cs
  WalletWasabi.Tests/UnitTests/Filters/IndexStoreTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionStoreMock.cs
  WalletWasabi/Crypto/CryptoGuards.cs
  WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Statement.cs
  WalletWasabi/Logging/BenchmarkLogger.cs
Labels: size/S

#4312 Apply VS Code Cleanup
  WalletWasabi/Wallets/Wallet.cs
Labels: size/XS

#4313 CodeMaid all the things!
  WalletWasabi.Gui/Behaviors/PreventTooltipStuckBehavior.cs
  WalletWasabi.Gui/Controls/EditableTextBlock.xaml
  WalletWasabi.Gui/Controls/LockScreen/SlideLockScreenView.xaml
  WalletWasabi.Gui/Controls/ModalDialog.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlView.xaml
  WalletWasabi.Gui/CrashReport/Views/CrashReportWindow.xaml
  WalletWasabi.Gui/Dialogs/CannotCloseDialogView.xaml.cs
  WalletWasabi.Gui/MainWindow.xaml
  WalletWasabi.Gui/ViewModels/IWalletViewModel.cs
  WalletWasabi.Gui/ViewModels/MainWindowViewModel.cs
  WalletWasabi.Gui/WasabiWindow.xaml
  WalletWasabi.Packager/packages.lock.json
  WalletWasabi.Tests/AcceptanceTests/HwiKatas.cs
  WalletWasabi.Tests/UnitTests/Bases/PeriodicRunnerTests.cs
  WalletWasabi.Tests/UnitTests/Packager/BitnodesApiTests.cs
  WalletWasabi.Tests/UnitTests/SmartBlockProviderTests.cs
  WalletWasabi.Tests/UnitTests/TestBlockProvider.cs
  WalletWasabi/Services/SingleInstanceChecker.cs
  WalletWasabi/Wallets/CachedBlockProvider.cs
  WalletWasabi/Wallets/IBlockProvider.cs
  WalletWasabi/Wallets/IRepository.cs
  WalletWasabi/packages.lock.json
Labels: size/M

#4295 [WabiSabi] Improve Transcript API
  WalletWasabi.Tests/UnitTests/Crypto/TranscriptTests.cs
  WalletWasabi/Crypto/ZeroKnowledge/SyntheticSecretNonceProvider.cs
  WalletWasabi/Crypto/ZeroKnowledge/Transcript.cs
Labels: size/L

#4320 IoHelpers: add missing ConfigureAwait(false).
  WalletWasabi/Helpers/IoHelpers.cs
Labels: size/XS

#4302 Fix Tor tests
  WalletWasabi.Tests/IntegrationTests/TorTests.cs
Labels: size/S

#4308 Fix typos & grammar
  WalletWasabi.Tests/UnitTests/WalletDirTests.cs
  WalletWasabi/BitcoinCore/Rpc/CachedRpcClient.cs
  WalletWasabi/Blockchain/Keys/WalletGenerator.cs
  WalletWasabi/Crypto/Extensions.cs
  WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Knowledge.cs
  WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Statement.cs
  WalletWasabi/Extensions/RPCClientExtensions.cs
  WalletWasabi/Legal/Assets/LegalDocuments.txt
Labels: size/S

#4316 Remove extra space in LegalDocuments.txt
  WalletWasabi/Legal/Assets/LegalDocuments.txt
Labels: size/XS

#4292 Publish binaries in zip format
  WalletWasabi.Packager/ArgsProcessor.cs
  WalletWasabi.Packager/Program.cs
  azure-pipelines-cd.yml
Labels: size/M

#4309 [WabiSabi] Implement Fiat-Shamir transform
  WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/FiatShamirTransformTests.cs
  WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Statement.cs
  WalletWasabi/Crypto/ZeroKnowledge/NonInteractive/FiatShamirTransform/Prover.cs
  WalletWasabi/Crypto/ZeroKnowledge/NonInteractive/FiatShamirTransform/Verifier.cs
  WalletWasabi/Crypto/ZeroKnowledge/NonInteractive/Proof.cs
  WalletWasabi/Crypto/ZeroKnowledge/Transcript.cs
Labels: size/L

#4339 Use constants for state in TorProcessManager.
  WalletWasabi/TorSocks5/TorProcessManager.cs
Labels: size/S

#4341 Better code coverage
  .coverage.sh
  WalletWasabi.Documentation/CodeCoverage.md
  WalletWasabi.Tests/WalletWasabi.Tests.csproj
Labels: size/M

#4284 Build transaction without the backend
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
Labels: size/L

#4354 Add TorInstallator class.
  WalletWasabi/Tor/TorInstallator.cs
  WalletWasabi/Tor/TorProcessManager.cs
Labels: size/M

#4343 Add status badge for continuous delivery
  README.md
Labels: size/XS

#4346 Add selected BTC value in USD to watermark in Send tab
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
Labels: size/M

#4322 Ignore if addition overflowed because it is irrelevant
  WalletWasabi/Crypto/SchnorrBlindingSignature.cs
Labels: size/XS

#4356 Use some null syntax sugars to simplify the codebase
  WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionBroadcasterViewModel.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi/Blockchain/BlockFilters/IndexBuilderService.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/Blockchain/Mempool/MempoolService.cs
  WalletWasabi/Extensions/LinqExtensions.cs
  WalletWasabi/Extensions/ListExtensions.cs
  WalletWasabi/Extensions/NBitcoinExtensions.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/DataEncodation/DataEncode.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/DataEncodation/InputRecognition/InputRecognise.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/ReedSolomon/ReedSolomonEncoder.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/Versions/ErrorCorrectionBlocks.cs
  WalletWasabi/Helpers/Guard.cs
  WalletWasabi/Helpers/IoHelpers.cs
  WalletWasabi/Helpers/PasswordHelper.cs
  WalletWasabi/Io/DigestableSafeMutexIoManager.cs
  WalletWasabi/Mono/CommandSet.cs
  WalletWasabi/Mono/OptionSet.cs
  WalletWasabi/Mono/StringCoda.cs
  WalletWasabi/Nito/AsyncEx/Synchronous/SynchronousTaskExtensions.cs
  WalletWasabi/Nito/Collections/CollectionHelpers.cs
  WalletWasabi/Nito/Collections/Deque.cs
  WalletWasabi/Stores/IndexStore.cs
  WalletWasabi/Tor/Http/Helpers/HttpMessageHelper.cs
  WalletWasabi/Tor/Http/TorHttpClient.cs
  WalletWasabi/Tor/Socks5/TorSocks5Client.cs
Labels: size/L

#4350 Proof of iparams
  WalletWasabi.Tests/UnitTests/Crypto/ProofSystemTests.cs
  WalletWasabi/Crypto/CoordinatorSecretKey.cs
  WalletWasabi/Crypto/Mac.cs
  WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Statement.cs
  WalletWasabi/Crypto/ZeroKnowledge/ProofSystem.cs
  WalletWasabi/Crypto/ZeroKnowledge/Transcript.cs
Labels: size/L

#4360 Revert logic change
  WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs
Labels: size/XS

#4305 Make `dataDir` to be TorProcessManager argument.
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
  WalletWasabi.Tests/IntegrationTests/TorTests.cs
  WalletWasabi/Tor/TorProcessManager.cs
Labels: size/M

#4349 TorProcessManager - move settings
  WalletWasabi/Tor/TorProcessManager.cs
Labels: size/S

#4319 trivial: TorProcessManager - private fields.
  WalletWasabi/Tor/TorProcessManager.cs
Labels: size/XS

#4365 Typos
  WalletWasabi.Tests/UnitTests/Crypto/ProofSystemTests.cs
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
Labels: size/S

#4368 Check deterministic builds with CI 2
  azure-pipelines-detbuild.yml
Labels: size/M

#4307 Fix formatting
  WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerViewModel.cs
  WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
  WalletWasabi.Tests/UnitTests/Hwi/HwiProcessBridgeMock.cs
  WalletWasabi/Hwi/Parsers/HwiParser.cs
Labels: size/M

#4369 Create deterministic build status badge
  README.md
Labels: size/XS

#4301 Adjust GetDefaultBitcoinCoreDataDirOrEmptyString.
  WalletWasabi.Gui/Config.cs
  WalletWasabi/Helpers/EnvironmentHelpers.cs
Labels: size/M

#4324 Use `IAsyncLifetime` in TorTests & LiveServerTests.
  WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
  WalletWasabi.Tests/IntegrationTests/TorTests.cs
Labels: size/M

#4306 Don't change the selected wallet when loading
  WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletViewModel.cs
Labels: size/XS

#4362 Improve Send control
  WalletWasabi.Backend/Config.cs
  WalletWasabi.Backend/InitConfigStartupTask.cs
  WalletWasabi.Gui/Behaviors/PasteAddressOnClickBehavior.cs
  WalletWasabi.Gui/CommandLine/Daemon.cs
  WalletWasabi.Gui/CommandLine/PasswordFinder.cs
  WalletWasabi.Gui/Config.cs
  WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoViewModel.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Gui/Tabs/SettingsViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/GenerateWallets/GenerateWalletViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/RecoverWallets/RecoverWalletViewModel.cs
  WalletWasabi.Packager/Program.cs
  WalletWasabi.Tests/UnitTests/GUI/SendControlViewModelTest.cs
  WalletWasabi.Tests/UnitTests/Userfacing/BitcoinInputTests.cs
  WalletWasabi.Tests/UnitTests/Userfacing/ParserTests.cs
  WalletWasabi.Tests/UnitTests/Userfacing/PasswordTests.cs
  WalletWasabi/BitcoinCore/Configuration/Whitening/WhiteEntry.cs
  WalletWasabi/BitcoinCore/CoreNode.cs
  WalletWasabi/Blockchain/Keys/WalletGenerator.cs
  WalletWasabi/Helpers/Constants.cs
  WalletWasabi/Helpers/Guard.cs
  WalletWasabi/JsonConverters/EndPointJsonConverter.cs
  WalletWasabi/Userfacing/AddressStringParser.cs
  WalletWasabi/Userfacing/BitcoinInput.cs
  WalletWasabi/Userfacing/EndPointParser.cs
  WalletWasabi/Userfacing/PasswordConsole.cs
  WalletWasabi/Userfacing/PasswordHelper.cs
Labels: size/L

#4340 Remove TorProcessManager.Mock() method
  WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi/Tor/TorProcessManager.cs
Labels: size/M

#4370 Improve Blocks Storage (Fix bug + Implement pruning) (2)
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Tests/IntegrationTests/P2pTests.cs
  WalletWasabi.Tests/RegressionTests/BuildTests.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/RegressionTests/Common.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi.Tests/RegressionTests/WalletTests.cs
  WalletWasabi.Tests/UnitTests/BitcoinCore/P2pBasedTests.cs
  WalletWasabi/Stores/BitcoinStore.cs
  WalletWasabi/Wallets/FileSystemBlockRepository.cs
Labels: size/L

#4314 Add VSCode settings to make editorconfig work
  CONTRIBUTING.md
Labels: size/S

#4366 Move TorLogPath to TorSettings and move TorSettings out of TorProcess…
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Gui/Shell/Commands/DiskCommands.cs
  WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
  WalletWasabi.Tests/IntegrationTests/TorTests.cs
  WalletWasabi.Tests/UnitTests/Tor/TorSettingsTests.cs
  WalletWasabi/Tor/TorProcessManager.cs
  WalletWasabi/Tor/TorSettings.cs
Labels: size/M

#4374 Remove code duplication from TorInstallator.
  WalletWasabi/Tor/TorInstallator.cs
Labels: size/M

#4380 Round max amount to 20999999.9769 btc
  WalletWasabi.Tests/UnitTests/Userfacing/BitcoinInputTests.cs
  WalletWasabi/Helpers/Constants.cs
  WalletWasabi/Userfacing/BitcoinInput.cs
Labels: size/S

#4373 Simplify AnyCoinsQueued
  WalletWasabi/CoinJoin/Client/Rounds/ClientState.cs
Labels: size/S

#4378 Remove leftover code
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
Labels: size/XS

#4379 [WabiSabi] Remove Simulators and refactor ResponseToChallenge
  WalletWasabi.Tests/UnitTests/Crypto/TranscriptTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/LinearRelationTests.cs
  WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Equation.cs
  WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Knowledge.cs
  WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Statement.cs
  WalletWasabi/Crypto/ZeroKnowledge/NonInteractive/FiatShamirTransform/Prover.cs
  WalletWasabi/Crypto/ZeroKnowledge/NonInteractive/Proof.cs
  WalletWasabi/Crypto/ZeroKnowledge/SyntheticSecretNonceProvider.cs
  WalletWasabi/Helpers/Guard.cs
Labels: size/L

#4385 Wabi sabi/small improvements
  WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/LinearRelationTests.cs
  WalletWasabi/Crypto/Mac.cs
  WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Equation.cs
  WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Knowledge.cs
  WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Statement.cs
Labels: size/M

#4321 Remove unnecessary controls in SendControlView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlView.xaml
Labels: size/S

#4389 TorProcessManager & ProcessAsync API.
  WalletWasabi/Helpers/EnvironmentHelpers.cs
  WalletWasabi/Tor/TorProcessManager.cs
  WalletWasabi/Tor/TorSettings.cs
Labels: size/M

#4387 [WabiSabi] Refactor Proof System
  WalletWasabi.Tests/UnitTests/Crypto/ProofSystemTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/FiatShamirTransformTests.cs
  WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Equation.cs
  WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Statement.cs
  WalletWasabi/Crypto/ZeroKnowledge/NonInteractive/FiatShamirTransform/Prover.cs
  WalletWasabi/Crypto/ZeroKnowledge/NonInteractive/Proof.cs
  WalletWasabi/Crypto/ZeroKnowledge/NonInteractive/Prover.cs
  WalletWasabi/Crypto/ZeroKnowledge/NonInteractive/Verifier.cs
  WalletWasabi/Crypto/ZeroKnowledge/ProofSystem.cs
  WalletWasabi/Crypto/ZeroKnowledge/Transcript.cs
Labels: size/L

#4390 [WabiSabi] Use new constructions
  WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/ChallengeTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/KnowledgeOfDlogTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/KnowledgeOfRepTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/ProverTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/StatementTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/VerifierTests.cs
  WalletWasabi/Crypto/ZeroKnowledge/Challenge.cs
  WalletWasabi/Crypto/ZeroKnowledge/KnowledgeOfDlog.cs
  WalletWasabi/Crypto/ZeroKnowledge/KnowledgeOfDlogParams.cs
  WalletWasabi/Crypto/ZeroKnowledge/KnowledgeOfRep.cs
  WalletWasabi/Crypto/ZeroKnowledge/KnowledgeOfRepParams.cs
  WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Statement.cs
  WalletWasabi/Crypto/ZeroKnowledge/Prover.cs
  WalletWasabi/Crypto/ZeroKnowledge/Statement.cs
  WalletWasabi/Crypto/ZeroKnowledge/Verifier.cs
Labels: size/XL

#4388 Use friendly wallet names
  WalletWasabi.Gui/Tabs/WalletManager/HardwareWallets/ConnectHardwareWalletViewModel.cs
  WalletWasabi.Tests/UnitTests/WalletDirTests.cs
  WalletWasabi/Extensions/EnumExtension.cs
  WalletWasabi/Helpers/IoHelpers.cs
  WalletWasabi/Hwi/Models/HardwareWalletModels.cs
  WalletWasabi/Wallets/WalletDirectories.cs
Labels: size/L

#4391 [WabiSabi] Remove Fully Qualified identifiers
  WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/KnowledgeOfDlogTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/KnowledgeOfRepTests.cs
  WalletWasabi/Crypto/ZeroKnowledge/NonInteractive/Verifier.cs
  WalletWasabi/Crypto/ZeroKnowledge/ProofSystem.cs
  WalletWasabi/Crypto/ZeroKnowledge/Transcript.cs
Labels: size/M

#4393 [WabiSabi] Proofs of SerialNumber, MAC show and UTs
  WalletWasabi.Tests/UnitTests/Crypto/ProofSystemTests.cs
  WalletWasabi/Crypto/ZeroKnowledge/Credential.cs
  WalletWasabi/Crypto/ZeroKnowledge/CredentialPresentation.cs
  WalletWasabi/Crypto/ZeroKnowledge/ProofSystem.cs
Labels: size/L

#4383 Remove unnecessary controls
  WalletWasabi.Gui/Tabs/WalletManager/GenerateWallets/GenerateWalletView.xaml
  WalletWasabi.Gui/Tabs/WalletManager/HardwareWallets/ConnectHardwareWalletView.xaml
Labels: size/S

#4323 Show exchange rate for BTC/USD as "Loading..." rather than "$0" at initialization
  WalletWasabi.Gui/Controls/StatusBar.xaml
  WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
Labels: size/M

#4395 Add verification to TorInstallator
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Tests/Global.cs
  WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
  WalletWasabi.Tests/IntegrationTests/TorTests.cs
  WalletWasabi.Tests/UnitTests/Tor/TorSettingsTests.cs
  WalletWasabi/Tor/TorInstallator.cs
  WalletWasabi/Tor/TorProcessManager.cs
  WalletWasabi/Tor/TorSettings.cs
Labels: size/L

#4397 Use EnumExtension's FriendlyName on DequeueReason enum
  WalletWasabi.Gui/Global.cs
  WalletWasabi/CoinJoin/Client/Clients/Queuing/DequeueReason.cs
Labels: size/M

#4399 Remove v3 code from client side
  WalletWasabi.Backend/README.md
  WalletWasabi/CoinJoin/Client/Clients/AliceClient.cs
  WalletWasabi/CoinJoin/Client/Clients/AliceClientBase.cs
  WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
  WalletWasabi/CoinJoin/Common/Models/InputsRequest.cs
  WalletWasabi/CoinJoin/Common/Models/RoundStateResponse.cs
  WalletWasabi/Helpers/Constants.cs
  WalletWasabi/JsonConverters/RoundStateResponseJsonConverter.cs
Labels: size/L

#4403 Move the rest of installation stuff from TorProcessManager to TorInstallator.
  WalletWasabi/Tor/TorInstallator.cs
  WalletWasabi/Tor/TorProcessManager.cs
Labels: size/M

#4407 Update NBitcoin and NBitcoin.Secp256k1
  .gitignore
  WalletWasabi.Gui/packages.lock.json
  WalletWasabi.Packager/packages.lock.json
  WalletWasabi/WalletWasabi.csproj
  WalletWasabi/packages.lock.json
Labels: size/M

#4404 Make button height same as textbox height
  WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoView.xaml
Labels: size/XS

#4412 Add site_name metatag og to the website
  WalletWasabi.Backend/wwwroot/index.html
Labels: size/XS

#4417 Use underscore only for private fields
  .editorconfig
Labels: size/S

#4414 Add balance proof
  WalletWasabi.Tests/UnitTests/Crypto/ProofSystemTests.cs
  WalletWasabi/Crypto/ZeroKnowledge/ProofSystem.cs
Labels: size/M

#4419 Improve fee estimation
  WalletWasabi.Backend/Controllers/BatchController.cs
  WalletWasabi.Backend/Controllers/BlockchainController.cs
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/UnitTests/BitcoinCore/RpcBasedTests.cs
  WalletWasabi/BitcoinCore/Monitoring/RpcFeeProvider.cs
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
  WalletWasabi/Extensions/RPCClientExtensions.cs
  WalletWasabi/WebClients/Wasabi/WasabiClient.cs
Labels: size/L

#4420 Remove initialvalue
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
Labels: size/S

#4424 Remove unused variables
  WalletWasabi.Tests/UnitTests/Crypto/ProofSystemTests.cs
Labels: size/XS

#4423 Fix name violation
  WalletWasabi/Crypto/ZeroKnowledge/SyntheticSecretNonceProvider.cs
Labels: size/S

#4409 Add comment to gitignore file
  .gitignore
Labels: size/XS

#4422 GUI validation: trivial improvements.
  WalletWasabi.Gui/Validation/ValidationExtensions.cs
  WalletWasabi.Gui/Validation/Validations.cs
  WalletWasabi/Models/ErrorDescriptor.cs
Labels: size/S

#4432 TorSocks5Client: Remove unused code.
  WalletWasabi/Tor/Socks5/TorSocks5Client.cs
Labels: size/M

#4405 TorProcessManager.Start - async version
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
  WalletWasabi.Tests/IntegrationTests/TorTests.cs
  WalletWasabi/Logging/BenchmarkLogger.cs
  WalletWasabi/Tor/TorProcessManager.cs
Labels: size/L

#4428 TorHttpClient: SslStream is supposed to support SNI since .NET Core 2.1.
  WalletWasabi/Tor/Http/TorHttpClient.cs
Labels: size/S

#4425 Labelling
  WalletWasabi.Gui/Controls/WalletExplorer/CoinInfoTabView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/CoinListView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/CoinViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionViewModel.cs
  WalletWasabi.Gui/Suggestions/SuggestLabelView.xaml
  WalletWasabi.Tests/UnitTests/Transactions/PayjoinTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
  WalletWasabi/Blockchain/Analysis/Clustering/Cluster.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/Blockchain/TransactionBuilding/SmartCoinSelector.cs
  WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs
  WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
  WalletWasabi/Blockchain/Transactions/TransactionHistoryBuilder.cs
  WalletWasabi/Blockchain/Transactions/TransactionSummary.cs
Labels: size/L

#4418 Add Link Title Attributes in the website
  WalletWasabi.Backend/wwwroot/index.html
Labels: size/L

#4441 Remove unused variable
  WalletWasabi.Tests/UnitTests/Crypto/ProofSystemTests.cs
Labels: size/XS

#4439 Remove commented out code
  WalletWasabi/Wallets/P2pBlockProvider.cs
Labels: size/XS

#4443 Revert "VDG - Initial implementation of new Navigation System"
  WalletWasabi.Fluent.Desktop/Program.cs
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent/App.xaml.cs
  WalletWasabi.Fluent/ScreenViewLocator.cs
  WalletWasabi.Fluent/ViewModels/HomeViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainWindowViewModel.cs
  WalletWasabi.Fluent/Views/HomeView.axaml
  WalletWasabi.Fluent/Views/HomeView.axaml.cs
  WalletWasabi.Fluent/Views/MainView.axaml
  WalletWasabi.Fluent/Views/MainView.axaml.cs
  WalletWasabi.Fluent/Views/MainWindow.xaml
  WalletWasabi.Fluent/Views/StatusBar.axaml
  WalletWasabi.Fluent/Views/StatusBar.axaml.cs
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Gui/Program.cs
  WalletWasabi.Gui/ViewModels/MainWindowViewModel.cs
  WalletWasabi.Gui/WalletWasabi.Gui.csproj
  WalletWasabi.sln
  WalletWasabi/WalletWasabi.csproj
Labels: size/XL

#4445 TorProcessManager.IsTorRunningAsync no longer accepts NULL.
  WalletWasabi.Tests/IntegrationTests/TorTests.cs
  WalletWasabi/Tor/TorProcessManager.cs
Labels: size/XS

#4450 Move `TorProcessManager.IsRunningAsync` method to `TorSocks5Client` c…
  WalletWasabi.Tests/IntegrationTests/TorTests.cs
  WalletWasabi/Tor/Socks5/TorSocks5Client.cs
  WalletWasabi/Tor/TorProcessManager.cs
Labels: size/M

#4453 Merge constructors in TorHttpClient.
  WalletWasabi/Tor/Http/TorHttpClient.cs
Labels: size/M

#4456 [Fluent] Fix Wasabi process never ends
  WalletWasabi/Services/WasabiSynchronizer.cs
Labels: size/XS

#4454 [Fluent] Add navigaton back button and working WhenNavigatedTo()
  WalletWasabi.Fluent/Icons/Icons.xaml
  WalletWasabi.Fluent/ViewModels/HomeViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/ViewModelBase.cs
  WalletWasabi.Fluent/Views/MainView.axaml
Labels: size/M
