Repository WalletWasabi/WalletWasabi, pull requests merged in 2020-02, with the labels that each got.

#3045 Clarify daily routine steps
  WalletWasabi.Documentation/WasabikaCodex.md
Labels: size/S

#3053 Fix more typos
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Gui/Styles/Styles.xaml
  WalletWasabi.Gui/Tabs/WalletManager/GenerateWalletViewModel.cs
  WalletWasabi.Tests/IntegrationTests/RegTests.cs
  WalletWasabi.Tests/UnitTests/IoTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
  WalletWasabi/Backend/Models/Responses/FiltersResponse.cs
  WalletWasabi/Backend/Models/Responses/SynchronizeResponse.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/ReedSolomon/Polynomial.cs
  WalletWasabi/Nito/Collections/Deque.cs
  WalletWasabi/Nito/Disposables/SingleDisposable.cs
  WalletWasabi/Services/WalletService.cs
Labels: size/M

#3054 Use c# 8 ranges
  WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
  WalletWasabi/Backend/Models/FilterModel.cs
  WalletWasabi/Helpers/PasswordHelper.cs
  WalletWasabi/TorSocks5/Models/Messages/TorSocks5Request.cs
  WalletWasabi/TorSocks5/Models/Messages/TorSocks5Response.cs
  WalletWasabi/TorSocks5/Models/Messages/UsernamePasswordRequest.cs
  WalletWasabi/TorSocks5/TorSocks5Client.cs
Labels: size/S

#3049 Correct comments
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
Labels: size/S

#3056 Double rpcworkqueue
  WalletWasabi.Documentation/BackendDeployment.md
Labels: size/XS

#3052 Add build rpc call
  WalletWasabi.Gui/Rpc/WasabiJsonRpcService.cs
Labels: size/S

#3024 Implement Advanced Coin Details Tab
  WalletWasabi.Gui/Controls/WalletExplorer/CoinInfoTabView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/CoinInfoTabView.xaml.cs
  WalletWasabi.Gui/Controls/WalletExplorer/CoinInfoTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/CoinListView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/CoinViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabView.xaml
  WalletWasabi.Gui/Icons/Icons.xaml
Labels: size/L

#3014 Set DocumentationTextMustBeginWithACapitalLetter to true
  Settings.StyleCop
  WalletWasabi.Backend/Middlewares/HeadMethodMiddleware.cs
  WalletWasabi/Bases/TorDisposableBase.cs
  WalletWasabi/Blockchain/Analysis/FeesEstimation/AllFeeEstimate.cs
  WalletWasabi/Extensions/LinqExtensions.cs
  WalletWasabi/Extensions/RPCClientExtensions.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/DataEncodation/InputRecognition/ModeEncodeCheck.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/EncodingRegion/BCHCalculator.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/EncodingRegion/VersionInformation.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/ReedSolomon/GaloisField256.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/ReedSolomon/Polynomial.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/ReedSolomon/ReedSolomonEncoder.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/Versions/VersionControl.cs
  WalletWasabi/Helpers/ByteArrayBuilder.cs
  WalletWasabi/Helpers/EventAwaiter.cs
  WalletWasabi/Helpers/EventsAwaiter.cs
  WalletWasabi/Hwi/Exceptions/HwiErrorCode.cs
  WalletWasabi/Hwi/Models/HardwareWalletModels.cs
  WalletWasabi/Io/SafeMutexIoManager.cs
  WalletWasabi/Nito/Collections/Deque.cs
  WalletWasabi/TorSocks5/Models/Fields/ByteArrayFields/AddrField.cs
Labels: size/XS

#3048 Fix some style CodeFactor issues
  WalletWasabi.Gui/Helpers/ShellUtils.cs
  WalletWasabi.Packager/NSubsys/PeUtility.cs
  WalletWasabi.Packager/Program.cs
  WalletWasabi.Packager/Tools.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
  WalletWasabi/Helpers/EnvironmentHelpers.cs
  WalletWasabi/Models/Height.cs
Labels: size/M

#3060 Final round of Typo fixes
  WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
  WalletWasabi.Gui/Helpers/FileHelpers.cs
  WalletWasabi.Gui/Models/StatusBarStatuses/StatusType.cs
  WalletWasabi.Gui/Tabs/WalletManager/LoadWalletViewModel.cs
  WalletWasabi.Tests/IntegrationTests/RegTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
  WalletWasabi/Blockchain/Transactions/SmartTransaction.cs
  WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/EncodingRegion/FormatInformation.cs
  WalletWasabi/WebClients/Wasabi/WasabiClient.cs
Labels: size/M

#3051 Add status request API - for filters
  WalletWasabi.Backend/Controllers/BlockchainController.cs
  WalletWasabi.Tests/IntegrationTests/RegTests.cs
  WalletWasabi/Backend/Models/Responses/StatusResponse.cs
  WalletWasabi/Blockchain/BlockFilters/IndexBuilderService.cs
Labels: size/L

#3065 update avalonia to 0.9.3
  WalletWasabi.Gui/WalletWasabi.Gui.csproj
Labels: size/XS

#3069 Fix typo
  WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
Labels: size/XS

#3068 Fix 'Single line comments must begin with single space issue'
  WalletWasabi.Tests/UnitTests/NBitcoinTests.cs
Labels: size/S

#3075 Add IgnoreDoubleSpendMultiTxAsync
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
Labels: size/M

#3076 Simplify ProcessResultAfterConfirmationCorrectAsync test
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
Labels: size/S

#3079 Enable CoinListView Item Virtualization
  WalletWasabi.Gui/Controls/WalletExplorer/CoinListView.xaml
Labels: size/XS

#3078 Use Rpc wrapper everywhere
  WalletWasabi.Backend/Controllers/BlockchainController.cs
  WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Backend/InitConfigStartupTask.cs
  WalletWasabi.Tests/IntegrationTests/RegTests.cs
  WalletWasabi.Tests/UnitTests/BlockNotifierTests.cs
  WalletWasabi.Tests/UnitTests/MockRpcClient.cs
  WalletWasabi/BitcoinCore/CoreNode.cs
  WalletWasabi/BitcoinCore/IRPCClient.cs
  WalletWasabi/BitcoinCore/Monitoring/RpcFeeProvider.cs
  WalletWasabi/BitcoinCore/Monitoring/RpcMonitor.cs
  WalletWasabi/BitcoinCore/Processes/BitcoindRpcProcessBridge.cs
  WalletWasabi/BitcoinCore/RpcClientBase.cs
  WalletWasabi/BitcoinCore/RpcWrappedClient.cs
  WalletWasabi/Blockchain/BlockFilters/IndexBuilderService.cs
  WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs
  WalletWasabi/CoinJoin/Client/CoinJoinProcessor.cs
  WalletWasabi/CoinJoin/Coordinator/Banning/UtxoReferee.cs
  WalletWasabi/CoinJoin/Coordinator/Coordinator.cs
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
  WalletWasabi/Extensions/RPCClientExtensions.cs
Labels: size/L

#3050 Generate wallet rpc
  WalletWasabi.Gui/Rpc/WasabiJsonRpcService.cs
  WalletWasabi.Gui/Tabs/WalletManager/GenerateWalletViewModel.cs
  WalletWasabi/Blockchain/Keys/WalletGenerator.cs
  WalletWasabi/Extensions/ExceptionExtensions.cs
Labels: size/L

#3094 Revert "Use Rpc wrapper everywhere"
  WalletWasabi.Backend/Controllers/BlockchainController.cs
  WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Backend/InitConfigStartupTask.cs
  WalletWasabi.Tests/IntegrationTests/RegTests.cs
  WalletWasabi.Tests/UnitTests/BlockNotifierTests.cs
  WalletWasabi.Tests/UnitTests/MockRpcClient.cs
  WalletWasabi/BitcoinCore/CoreNode.cs
  WalletWasabi/BitcoinCore/IRPCClient.cs
  WalletWasabi/BitcoinCore/Monitoring/RpcFeeProvider.cs
  WalletWasabi/BitcoinCore/Monitoring/RpcMonitor.cs
  WalletWasabi/BitcoinCore/Processes/BitcoindRpcProcessBridge.cs
  WalletWasabi/BitcoinCore/RpcClientBase.cs
  WalletWasabi/BitcoinCore/RpcWrappedClient.cs
  WalletWasabi/Blockchain/BlockFilters/IndexBuilderService.cs
  WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs
  WalletWasabi/CoinJoin/Client/CoinJoinProcessor.cs
  WalletWasabi/CoinJoin/Coordinator/Banning/UtxoReferee.cs
  WalletWasabi/CoinJoin/Coordinator/Coordinator.cs
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
  WalletWasabi/Extensions/RPCClientExtensions.cs
Labels: size/XL

#3084 Improve double spending detection performance
  WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
Labels: size/M

#3095 Use Task.WhenAll
  WalletWasabi.Backend/Controllers/BlockchainController.cs
Labels: size/XS

#3093 Refactor GetHashCode to ( tuple )GetHashCode
  WalletWasabi.Gui/Models/StatusBarStatuses/Status.cs
  WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
  WalletWasabi/Blockchain/TransactionOutputs/TxoRef.cs
  WalletWasabi/CoinJoin/Common/Crypto/SchnorrKey.cs
  WalletWasabi/CoinJoin/Common/Crypto/SchnorrPubKey.cs
  WalletWasabi/CoinJoin/Coordinator/MixingLevels/MixingLevel.cs
  WalletWasabi/Hwi/Models/HwiOption.cs
  WalletWasabi/Models/UpdateStatus.cs
Labels: size/S

#3096 [WEBSITE] change broken link
  WalletWasabi.Backend/wwwroot/index.html
Labels: debug, size/XS

#3087 Make SelectLockTimeForTransaction test deterministic
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
  WalletWasabi/Services/WalletService.cs
Labels: size/S

#3098 unify notification messages
  WalletWasabi.Gui/Controls/LockScreen/PinLockScreenViewModel.cs
  WalletWasabi.Gui/Helpers/NotificationHelpers.cs
  WalletWasabi.Gui/Tabs/SettingsViewModel.cs
Labels: size/XS

#3097 Add notification when PSBT file was saved.
  WalletWasabi.Gui/Controls/WalletExplorer/BuildTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionBroadcasterViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionViewerViewModel.cs
  WalletWasabi.Gui/Tabs/SettingsViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/GenerateWalletSuccessViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/RecoverWalletViewModel.cs
Labels: size/XS

#3089 Add BinarySearchExtensions, required for multi-wallet support, keepin…
  WalletWasabi.Tests/UnitTests/ListExtensionTests.cs
  WalletWasabi/Extensions/ListExtensions.cs
Labels: size/L

#3106 MultiWallet: Add icons for open and closed Wallets.
  WalletWasabi.Gui/Icons/Icons.xaml
Labels: size/M

#3107 Improve Load Speed: CJ Heuristic (1.7x faster)
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
Labels: size/S

#3110 Revert buggy Azure CI fix
  azure-pipelines-osx.yml
Labels: size/XS, waiting for dependency

#3109 Place CoinJoin client to WalletService
  WalletWasabi.Gui/CommandLine/Daemon.cs
  WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/CoinViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
  WalletWasabi.Gui/Converters/PhaseColorConverter.cs
  WalletWasabi.Gui/Dialogs/CannotCloseDialogViewModel.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Gui/MainWindow.xaml.cs
  WalletWasabi.Gui/Rpc/WasabiJsonRpcService.cs
  WalletWasabi.Tests/IntegrationTests/P2pTests.cs
  WalletWasabi.Tests/IntegrationTests/RegTests.cs
  WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs
  WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
  WalletWasabi/CoinJoin/Client/CoinJoinProcessor.cs
  WalletWasabi/Services/WalletService.cs
Labels: size/L

#3108 Improve Load Speed: Input Iteration
  WalletWasabi.Tests/IntegrationTests/RegTests.cs
  WalletWasabi.Tests/UnitTests/SmartCoinTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
  WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
  WalletWasabi/CoinJoin/Client/Rounds/ClientState.cs
  WalletWasabi/Services/WalletService.cs
Labels: size/M

#3112 [WEBSITE] fix broken link
  WalletWasabi.Backend/wwwroot/index.html
Labels: debug, size/XS

#3114 Trivial: Edit comments number
  WalletWasabi.Tests/IntegrationTests/RegTests.cs
Labels: size/S

#3119 Give WalletService to wallet dependent ViewModels
  WalletWasabi.Gui/CommandLine/CommandInterpreter.cs
  WalletWasabi.Gui/Controls/SuggestLabelViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/CoinViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletViewModel.cs
Labels: size/M

#3120 MultiWallet 4 / 10 : PhaseColourConverter fixes to be multiwallet compatible.
  WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs
  WalletWasabi.Gui/Converters/PhaseColorConverter.cs
  WalletWasabi.Gui/Converters/PhaseStringConverter.cs
  WalletWasabi.Gui/Models/RoundPhaseState.cs
Labels: size/M

#3092 Implement HistoryViewTab's Details View
  WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionInfo.cs
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionInfoTabView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionInfoTabView.xaml.cs
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionInfoTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionViewModel.cs
Labels: size/L

#3127 Trivial: Fix misspelling
  WalletWasabi.Gui/Global.cs
Labels: size/XS

#3132 Optimize Wallet Load (3.6x faster)
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
  WalletWasabi/Blockchain/Analysis/Clustering/Cluster.cs
  WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs
  WalletWasabi/Blockchain/TransactionOutputs/CoinsView.cs
  WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
  WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
Labels: size/L

#3133 Order elements (KeyManager.cs)
  WalletWasabi/Blockchain/Keys/KeyManager.cs
Labels: size/L

#3137 legalversion Preparation PR
  WalletWasabi.Backend/Controllers/SoftwareController.cs
  WalletWasabi.Gui/Shell/Commands/HelpCommands.cs
  WalletWasabi.Gui/Tabs/WalletManager/GenerateWalletViewModel.cs
  WalletWasabi/Models/UpdateStatus.cs
  WalletWasabi/Services/UpdateChecker.cs
Labels: size/M

#3138 Adding Legal docs update to the Backend
  WalletWasabi.Backend/Controllers/SoftwareController.cs
  WalletWasabi.Backend/Controllers/WasabiController.cs
  WalletWasabi.Backend/wwwroot/index.html
  WalletWasabi/Backend/Models/Responses/VersionsResponse.cs
  WalletWasabi/Helpers/Constants.cs
  WalletWasabi/Legal/Assets/LegalDocuments.txt
  WalletWasabi/Legal/LegalDocuments.cs
  WalletWasabi/WalletWasabi.csproj
Labels: size/M

#3126 Order elements in some classes
  WalletWasabi/Backend/Models/FilterModel.cs
  WalletWasabi/Bases/ByteArraySerializableBase.cs
  WalletWasabi/Bases/ConfigBase.cs
  WalletWasabi/Bases/OctetSerializableBase.cs
Labels: size/M

#3047 Add naming rule for local const (PascalCase)
  .editorconfig
  WalletWasabi.Tests/UnitTests/Hwi/HwiProcessBridgeMock.cs
  WalletWasabi.Tests/UnitTests/IoTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/AllTransactionStoreTests.cs
  WalletWasabi/Helpers/IoHelpers.cs
  WalletWasabi/Mono/StringCoda.cs
Labels: size/M

#3143 Implement Client Side API Connection to Legal docs + a bunch of tests
  WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
  WalletWasabi.Tests/UnitTests/Clients/WasabiClientTests.cs
  WalletWasabi/Models/UpdateStatus.cs
  WalletWasabi/Services/UpdateChecker.cs
  WalletWasabi/WebClients/Wasabi/WasabiClient.cs
Labels: size/L

#3144 Create technical tutorial for RegTest setup
  WalletWasabi.Documentation/WasabiSetupRegtest.md
Labels: size/L

#3161 Move back Ports.md document
  WalletWasabi.Documentation/Ports.md
Labels: size/S

#3160 Move back HowToDebug.md document
  WalletWasabi.Documentation/Guides/HowToDebug.md
Labels: size/L

#3156 fix code factor issues for mainwindowVM
  WalletWasabi.Gui/ViewModels/MainWindowViewModel.cs
Labels: size/M

#3154 CoinListVM CodeFactor issues fixed
  WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs
Labels: size/L

#3157 Codefactor fix transaction vm issues
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionViewerViewModel.cs
Labels: size/M

#3153 CoinJoinTabVM uses its own internal WalletService.
  WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs
Labels: size/M

#3159 Remove Id property from WalletViewModel
  WalletWasabi.Gui/Controls/WalletExplorer/BuildTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletViewModel.cs
Labels: size/XS

#3165 Pass WalletService instead of WalletViewModel around
  WalletWasabi.Gui/Controls/WalletExplorer/BuildTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionViewerViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletActionViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletAdvancedViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletViewModel.cs
  WalletWasabi.Gui/ViewModels/AddressViewModel.cs
  WalletWasabi/Services/WalletService.cs
Labels: size/L

#3171 Measure wallet load performance
  WalletWasabi/Services/WalletService.cs
Labels: size/S

#3168 Wasabi document tab vm implements disposables for us
  WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/PinPadViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionBroadcasterViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionViewerViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoViewModel.cs
  WalletWasabi.Gui/Tabs/SettingsViewModel.cs
  WalletWasabi.Gui/ViewModels/TextResourceViewModelBase.cs
  WalletWasabi.Gui/ViewModels/WasabiDocumentTabViewModel.cs
Labels: size/L

#3169 Fix lots of code factor issues
  WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionBroadcasterViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoViewModel.cs
  WalletWasabi.Gui/Tabs/SettingsViewModel.cs
Labels: size/XL

#3172 Order elements in some classes
  WalletWasabi/Bases/PeriodicRunner.cs
  WalletWasabi/Bases/TorDisposableBase.cs
  WalletWasabi/BitcoinCore/Configuration/CoreConfig.cs
  WalletWasabi/BitcoinCore/Configuration/CoreConfigLine.cs
  WalletWasabi/BitcoinCore/Configuration/CoreConfigTranslator.cs
Labels: size/M
