Repository WalletWasabi/WalletWasabi, pull requests merged in 2020-08, with the labels that each got.

#4097 Add PathMap to solve deterministic build on CallerFilePath
  WalletWasabi.Backend/WalletWasabi.Backend.csproj
  WalletWasabi.Gui/WalletWasabi.Gui.csproj
  WalletWasabi.Packager/WalletWasabi.Packager.csproj
  WalletWasabi.Tests/WalletWasabi.Tests.csproj
  WalletWasabi/WalletWasabi.csproj
Labels: size/XS

#4109 Dump v1 1 12
  WalletWasabi.Backend/wwwroot/index.html
  WalletWasabi/Helpers/Constants.cs
  WalletWasabi/OnionSeeds/MainOnionSeeds.txt
Labels: size/XL

#4116 Revert "Limit coin detail double-click behavior to a focus target control ins…"
  WalletWasabi.Gui/Controls/WalletExplorer/CoinListView.xaml
Labels: size/S

#3950 Update DeterministicBuildGuide a bit.
  WalletWasabi.Documentation/Guides/DeterministicBuildGuide.md
Labels: size/M

#4132 Better logging for coordinator round
  WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
Labels: size/M

#4133 Make sure Alice remove happens only if alice didn't remove its connec…
  WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
Labels: size/M

#4134 Optimize estimate all fee
  WalletWasabi.Tests/UnitTests/AllFeeEstimateTests.cs
  WalletWasabi/BitcoinCore/CachedRpcClient.cs
  WalletWasabi/Blockchain/Analysis/FeesEstimation/AllFeeEstimate.cs
  WalletWasabi/Extensions/RPCClientExtensions.cs
Labels: size/L

#4136 Server Load Hotfix
  WalletWasabi.Backend/Controllers/BlockchainController.cs
Labels: size/S

#4137 Fix Failing Atomic Cache
  WalletWasabi.Backend/Controllers/BlockchainController.cs
  WalletWasabi.Tests/UnitTests/MemoryTests.cs
  WalletWasabi/BitcoinCore/CachedRpcClient.cs
  WalletWasabi/Extensions/MemoryExtensions.cs
  WalletWasabi/Wallets/SmartBlockProvider.cs
Labels: priority, size/L

#4111 Replace `hidden service` with `onion service`
  WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
Labels: size/XS

#4057 Refactoring: TorSettings
  WalletWasabi.Tests/UnitTests/TorSocks5/TorSettingsTests.cs
  WalletWasabi/TorSocks5/TorProcessManager.cs
  WalletWasabi/TorSocks5/TorSettings.cs
Labels: size/L

#4068 User friendly notification message
  WalletWasabi/Extensions/ExceptionExtensions.cs
Labels: size/S

#4106 Allow suggesting same words multiple times when typing recovery words
  WalletWasabi.Gui/Tabs/WalletManager/RecoverWallets/RecoverWalletViewModel.cs
Labels: size/XS

#4101 Move complexity from WalletManager to SuggestLabelViewModel.
  WalletWasabi.Gui/Suggestions/SuggestLabelViewModel.cs
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/M

#4099 Wallet.cs: Remove unused method.
  WalletWasabi/Wallets/Wallet.cs
Labels: size/S

#4080 Show checkouted branch
  WalletWasabi.Documentation/BackendDeployment.md
Labels: size/S

#4050 Update software description
  WalletWasabi.Gui/WalletWasabi.Gui.csproj
  WalletWasabi.Packager/Program.cs
Labels: size/XS

#3996 Packager: Introduce ArgsProcessor.
  WalletWasabi.Packager/ArgsProcessor.cs
  WalletWasabi.Packager/MacSignTools.cs
  WalletWasabi.Packager/Program.cs
  WalletWasabi.Tests/UnitTests/Packager/ArgsProcessorTests.cs
  WalletWasabi.Tests/WalletWasabi.Tests.csproj
Labels: size/L

#3983 Check for existence of gedit before trying to launch it
  WalletWasabi.Gui/Helpers/FileHelpers.cs
Labels: size/XS

#4071 TorSocks5Client: Remove unused constructor.
  WalletWasabi/TorSocks5/TorProcessManager.cs
  WalletWasabi/TorSocks5/TorSocks5Client.cs
Labels: size/S

#4035 Update .editorconfig for *.csproj files.
  .editorconfig
Labels: size/M

#4070 Validate Account keypath
  WalletWasabi.Gui/Tabs/WalletManager/RecoverWallets/RecoverWalletViewModel.cs
Labels: size/S

#4142 [1/3] Add contributing guide for using Grid sparingly.
  CONTRIBUTING.md
Labels: size/XS

#4141 Add sourceFileMap to debug
  WalletWasabi.Documentation/Guides/HowToDebug.md
Labels: size/XS

#4143 [2/3] Replacing Trivial Grids with Panel
  WalletWasabi.Gui/App.xaml
  WalletWasabi.Gui/Controls/BusyIndicator.xaml
  WalletWasabi.Gui/Controls/EditableTextBlock.xaml
  WalletWasabi.Gui/Controls/LockScreen/PinLockScreenView.xaml
  WalletWasabi.Gui/Controls/LockScreen/SlideLock.cs
  WalletWasabi.Gui/Controls/LockScreen/SlideLock.xaml
  WalletWasabi.Gui/Controls/LockScreen/SlideLockScreenView.xaml
  WalletWasabi.Gui/Controls/ModalDialog.xaml
  WalletWasabi.Gui/Controls/MultiTextBox.xaml
  WalletWasabi.Gui/Controls/Spinner.xaml
  WalletWasabi.Gui/Controls/StatusBar.xaml
  WalletWasabi.Gui/Controls/TogglePasswordBox.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlView.xaml
  WalletWasabi.Gui/CrashReport/Views/CrashReportWindow.xaml
  WalletWasabi.Gui/Dialogs/GenSocksServFailDialogView.xaml
  WalletWasabi.Gui/Tabs/LegalDocumentsView.xaml
  WalletWasabi.Gui/Tabs/WalletManager/GenerateWallets/GenerateWalletView.xaml
  WalletWasabi.Gui/Tabs/WalletManager/HardwareWallets/ConnectHardwareWalletView.xaml
  WalletWasabi.Gui/Tabs/WalletManager/WalletManagerView.xaml
Labels: size/L

#4081 Features/price providers
  WalletWasabi.Backend/Controllers/OffchainController.cs
  WalletWasabi.Tests/IntegrationTests/ExternalApiTests.cs
  WalletWasabi/Interfaces/IExchangeRateProvider.cs
  WalletWasabi/WebClients/Bitstamp/BitstampExchangeRate.cs
  WalletWasabi/WebClients/Bitstamp/BitstampExchangeRateProvider.cs
  WalletWasabi/WebClients/BlockchainInfo/BlockchainInfoExchangeRateProvider.cs
  WalletWasabi/WebClients/CoinGecko/CoinGeckoExchangeRate.cs
  WalletWasabi/WebClients/CoinGecko/CoinGeckoExchangeRateProvider.cs
  WalletWasabi/WebClients/Coinbase/CoinbaseExchangeRateProvider.cs
  WalletWasabi/WebClients/ExchangeRateProviders.cs
  WalletWasabi/WebClients/Gemini/GeminiExchangeRateProvider.cs
  WalletWasabi/WebClients/ItBit/ItBitExchangeRateProvider.cs
  WalletWasabi/WebClients/SmartBit/SmartBitExchangeRateProvider.cs
Labels: size/L

#4144 Add Tor logs
  WalletWasabi.Documentation/BackendDeployment.md
Labels: size/S

#4145 [PATCH] Connection confirmation lock
  WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
Labels: size/M

#4131 Add more logging to TorSocks5Client.
  WalletWasabi/Logging/Logger.cs
  WalletWasabi/TorSocks5/TorSocks5Client.cs
Labels: size/L

#4112 Implement serialization + scalar operations for GroupElement
  WalletWasabi.Tests/UnitTests/Crypto/GroupElementTests.cs
  WalletWasabi/Crypto/GroupElement.cs
Labels: size/L

#4149 WabiSabi Crypto Work
  WalletWasabi.Tests/UnitTests/Crypto/GroupElementTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/RandomTests.cs
  WalletWasabi.Tests/UnitTests/IoTests.cs
  WalletWasabi.Tests/UnitTests/KeyManagementTests.cs
  WalletWasabi.Tests/UnitTests/PasswordTests.cs
  WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
  WalletWasabi/Crypto/GroupElement.cs
  WalletWasabi/Crypto/Randomness/InsecureRandom.cs
  WalletWasabi/Crypto/Randomness/MockRandom.cs
  WalletWasabi/Crypto/Randomness/RandomString.cs
  WalletWasabi/Crypto/Randomness/SecureRandom.cs
  WalletWasabi/Crypto/Randomness/UnsecureRandom.cs
  WalletWasabi/Crypto/Randomness/WasabiRandom.cs
  WalletWasabi/Crypto/StringCipher.cs
  WalletWasabi/Crypto/TokenGenerator.cs
  WalletWasabi/Helpers/Constants.cs
  WalletWasabi/Helpers/RandomString.cs
  WalletWasabi/TorSocks5/TorSocks5Client.cs
Labels: size/XL

#4150 Organize Group Element Tests
  WalletWasabi.Tests/UnitTests/Crypto/GroupElements/GeneralTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/GroupElements/OperationTests.cs
Labels: size/L

#4148 [3/3] Simplify Grid col/row definitions declarations
  WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/PinPadView.xaml
  WalletWasabi.Gui/Dialogs/CannotCloseDialogView.xaml
  WalletWasabi.Gui/Dialogs/TextInputDialogView.xaml
Labels: size/M

#4084 Open Transaction Details tab based on wallet name
  WalletWasabi.Gui/Controls/TransactionDetails/ViewModels/TransactionDetailsViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionViewModel.cs
Labels: size/S

#4034 Improve Packager to be more user-friendly for Linux & macOS.
  WalletWasabi.Packager/Program.cs
Labels: size/S

#4125 Add update docs step to client deployment guide
  WalletWasabi.Documentation/ClientDeployment.md
Labels: size/S

#4140 Clarify notification message
  WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
Labels: size/XS

#4155 Improve documentation for debugging
  WalletWasabi.Documentation/Guides/HowToDebug.md
Labels: size/M

#4100 Add LockTimeSelector + unit test.
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
  WalletWasabi.Tests/UnitTests/Wallet/LockTimeSelectorTests.cs
  WalletWasabi/Wallets/LockTimeSelector.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/L

#4158 Remove ConfigureAwait(false) from tests.
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/RpcTests.cs
  WalletWasabi.Tests/TestableRpcService.cs
  WalletWasabi.Tests/UnitTests/BlockNotifierTests.cs
  WalletWasabi.Tests/UnitTests/Clients/WasabiClientTests.cs
Labels: size/S

#3873 Add Nullable reference types to all projects (option 3)
  WalletWasabi.Backend/WalletWasabi.Backend.csproj
  WalletWasabi.Gui/WalletWasabi.Gui.csproj
  WalletWasabi.Packager/WalletWasabi.Packager.csproj
  WalletWasabi.Tests/WalletWasabi.Tests.csproj
  WalletWasabi/WalletWasabi.csproj
Labels: size/XS

#4160 Remove #nullable enable
  WalletWasabi.Packager/ArgsProcessor.cs
  WalletWasabi/Crypto/UnblindedSignature.cs
  WalletWasabi/WebClients/Bitstamp/BitstampExchangeRate.cs
  WalletWasabi/WebClients/Bitstamp/BitstampExchangeRateProvider.cs
  WalletWasabi/WebClients/CoinGecko/CoinGeckoExchangeRate.cs
  WalletWasabi/WebClients/CoinGecko/CoinGeckoExchangeRateProvider.cs
  WalletWasabi/WebClients/ExchangeRateProviders.cs
Labels: size/S

#4161 Update WabiSabi code with Nullable Reference Types
  WalletWasabi.Tests/UnitTests/Crypto/GroupElements/GeneralTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/GroupElements/OperationTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/RandomTests.cs
  WalletWasabi/Crypto/GroupElement.cs
  WalletWasabi/Crypto/SchnorrBlindingSignature.cs
  WalletWasabi/Crypto/StringCipher.cs
Labels: size/M

#4159 Implement WabiSabi Generators
  WalletWasabi.Tests/UnitTests/Crypto/GroupElements/GeneralTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/GroupElements/GeneratorTests.cs
  WalletWasabi/Crypto/GroupElement.cs
Labels: size/L

#4157 Add missing option to how to debug documentation
  WalletWasabi.Documentation/Guides/HowToDebug.md
Labels: size/XS

#3901 Fix Trezor T Kata
  WalletWasabi.Tests/AcceptanceTests/HwiKatas.cs
Labels: size/S

#4163 Change History Tab's default sorting to decreasing
  WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs
  WalletWasabi.Gui/UiConfig.cs
Labels: size/XS

#4156 Replace 'Bitcoin Core' by 'Bitcoin Knots' when logging
  WalletWasabi.Backend/Global.cs
  WalletWasabi/BitcoinCore/CoreNode.cs
  WalletWasabi/BitcoinCore/Processes/BitcoindRpcProcessBridge.cs
  WalletWasabi/Helpers/Constants.cs
  WalletWasabi/Helpers/EnvironmentHelpers.cs
  WalletWasabi/Wallets/P2pBlockProvider.cs
Labels: size/M

#4167 Update WasabikaCodex.md add missing setup elements to Visual Studio guide
  WalletWasabi.Documentation/WasabikaCodex.md
Labels: size/XS

#4168 Add Valhalla board to Wasabika Codex
  WalletWasabi.Documentation/WasabikaCodex.md
Labels: size/S

#3831 [StyleCop] Enable ParameterMustFollowComma
  Settings.StyleCop
Labels: size/XS

#3809 Refactor BitcoinStore - step 2
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Tests/IntegrationTests/P2pTests.cs
  WalletWasabi.Tests/RegressionTests/Common.cs
  WalletWasabi.Tests/UnitTests/BitcoinCore/P2pBasedTests.cs
  WalletWasabi.Tests/UnitTests/Filters/IndexStoreTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/AllTransactionStoreTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/PayjoinTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
  WalletWasabi/Blockchain/Transactions/AllTransactionStore.cs
  WalletWasabi/Blockchain/Transactions/AllTransactionStoreMock.cs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
  WalletWasabi/Stores/BitcoinStore.cs
  WalletWasabi/Stores/BitcoinStoreMock.cs
  WalletWasabi/Stores/IndexStore.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/L

#4174 Make PropertySummaryDocumentationMustMatchAccessors false
  Settings.StyleCop
Labels: size/XS

#4175 Valhalla assignee table and Git tips added to WasabikaCodex.md
  WalletWasabi.Documentation/WasabikaCodex.md
Labels: size/S

#4115 Fix shield tooltips not showing on CoinListView.
  WalletWasabi.Gui/Controls/WalletExplorer/CoinListView.xaml
Labels: size/M

#4044 StatusBar background based on network
  WalletWasabi.Gui/App.xaml
  WalletWasabi.Gui/Controls/StatusBar.xaml
  WalletWasabi.Gui/Converters/NetworkColorConverter.cs
  WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
Labels: size/M

#4164 Fix some small nullable warnings
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionViewModel.cs
  WalletWasabi.Gui/MainWindow.xaml.cs
  WalletWasabi.Gui/UiConfig.cs
Labels: size/S

#4177 Update WasabikaCodex.md
  WalletWasabi.Documentation/WasabikaCodex.md
Labels: size/M

#4178 Remove setter
  WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
Labels: size/XS

#3836 [StyleCop] Enable DoNotPlaceRegionsWithinElements
  Settings.StyleCop
Labels: size/XS

#4179 Make StaticElementsMustAppearBeforeInstanceElements false
  Settings.StyleCop
Labels: size/XS

#3835 Update blockchain privacy features
  README.md
Labels: size/XS

#4108 Add Hardware Wallet integration guidance
  WalletWasabi.Documentation/Guides/HardwareWalletIntegration.md
Labels: size/S

#4184 CommandInterpreterTest: Add missing StringNoWhiteSpaceEqualityComparer.
  WalletWasabi.Tests/UnitTests/GUI/CommandInterpreterTest.cs
Labels: size/XS

#4173 NodeBuildingTests.GetVersionTestsAsync: Increase timeout significantl…
  WalletWasabi.Tests/UnitTests/BitcoinCore/NodeBuildingTests.cs
Labels: size/S

#3885 Logger - documentation & LogMode.DEBUG bugfix
  WalletWasabi/Logging/LogLevel.cs
  WalletWasabi/Logging/LogMode.cs
  WalletWasabi/Logging/Logger.cs
Labels: size/L

#4180 Make some tests to run in serial mode.
  WalletWasabi.Tests/UnitTests/BitcoinCore/NodeBuildingTests.cs
  WalletWasabi.Tests/UnitTests/BitcoinCore/SerialNodeBuildingTests.cs
  WalletWasabi.Tests/UnitTests/Hwi/DefaultResponseTests.cs
  WalletWasabi.Tests/UnitTests/Hwi/SerialDefaultResponseTests.cs
  WalletWasabi.Tests/XunitConfiguration/SerialCollectionDefinition.cs
Labels: size/L

#4151 Implement Knowledge of Discrete Log and Knowledge of Representation
  WalletWasabi.Packager/packages.lock.json
  WalletWasabi.Tests/Helpers/CryptoHelpers.cs
  WalletWasabi.Tests/UnitTests/Crypto/GroupElements/GeneralTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/GroupElements/GeneratorTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/GroupElements/OperationTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/ChallengeTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/KnowledgeOfDiscreteLogTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/KnowledgeOfRepresentationTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/ProverTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/VerifierTests.cs
  WalletWasabi.Tests/UnitTests/LinqExtensionsTests.cs
  WalletWasabi/Crypto/Groups/Generators.cs
  WalletWasabi/Crypto/Groups/GroupElement.cs
  WalletWasabi/Crypto/Randomness/MockRandom.cs
  WalletWasabi/Crypto/Randomness/WasabiRandom.cs
  WalletWasabi/Crypto/ZeroKnowledge/Challenge.cs
  WalletWasabi/Crypto/ZeroKnowledge/KnowledgeOfDiscreteLog.cs
  WalletWasabi/Crypto/ZeroKnowledge/KnowledgeOfRepresentation.cs
  WalletWasabi/Crypto/ZeroKnowledge/Prover.cs
  WalletWasabi/Crypto/ZeroKnowledge/Verifier.cs
  WalletWasabi/Extensions/LinqExtensions.cs
Labels: size/XL

#4194 remove completely unused control.
  WalletWasabi.Gui/App.xaml
  WalletWasabi.Gui/Controls/MultiTextBox.cs
  WalletWasabi.Gui/Controls/MultiTextBox.xaml
Labels: size/L

#3997 IoHelpers: DeleteRecursivelyWithMagicDustAsync -> TryDeleteDirectoryAsync
  WalletWasabi.Packager/MacSignTools.cs
  WalletWasabi.Packager/Program.cs
  WalletWasabi.Packager/packages.lock.json
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/UnitTests/Filters/IndexStoreTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
  WalletWasabi.Tests/UnitTests/WalletDirTests.cs
  WalletWasabi.Tests/XunitConfiguration/RegTestFixture.cs
  WalletWasabi/BitcoinCore/CoreNode.cs
  WalletWasabi/Helpers/IoHelpers.cs
Labels: size/L

#4185 Refactoring: PidFile class.
  WalletWasabi/BitcoinCore/Processes/BitcoindRpcProcessBridge.cs
  WalletWasabi/BitcoinCore/Processes/PidFile.cs
Labels: size/M

#4195 Add waitForExit info to make it clear what it does.
  WalletWasabi/TorSocks5/TorProcessManager.cs
Labels: size/XS

#4196 Make BlockNotifierTests run in serial mode in xunit.
  WalletWasabi.Tests/UnitTests/SerialBlockNotifierTests.cs
Labels: size/S

#4186 Crash report layout fix
  WalletWasabi.Gui/CrashReport/ViewModels/CrashReportWindowViewModel.cs
  WalletWasabi.Gui/CrashReport/Views/CrashReportWindow.xaml
Labels: size/S

#4188 Add new async process API that is supposed to replace ProcessBridge API.
  WalletWasabi.Tests/UnitTests/Microservices/ProcessAsyncTest.cs
  WalletWasabi/Microservices/ProcessAsync.cs
  WalletWasabi/Microservices/ProcessInvoker.cs
  WalletWasabi/Microservices/ProcessStartInfoFactory.cs
Labels: size/L

#4199 Use more portable variant of `/bin/sh`.
  WalletWasabi/Helpers/EnvironmentHelpers.cs
Labels: size/S

#4201 [WIP] Implement AND proofs for knowledge proofs
  WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/ChallengeTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/KnowledgeOfDiscreteLogTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/KnowledgeOfDlogTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/KnowledgeOfRepTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/KnowledgeOfRepresentationTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/ProverTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/StatementTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/VerifierTests.cs
  WalletWasabi/Crypto/ZeroKnowledge/Challenge.cs
  WalletWasabi/Crypto/ZeroKnowledge/KnowledgeOfDlog.cs
  WalletWasabi/Crypto/ZeroKnowledge/KnowledgeOfDlogParams.cs
  WalletWasabi/Crypto/ZeroKnowledge/KnowledgeOfRep.cs
  WalletWasabi/Crypto/ZeroKnowledge/KnowledgeOfRepParams.cs
  WalletWasabi/Crypto/ZeroKnowledge/Prover.cs
  WalletWasabi/Crypto/ZeroKnowledge/Statement.cs
  WalletWasabi/Crypto/ZeroKnowledge/Verifier.cs
Labels: size/XL

#4207 Receive change in the first clean change address
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
Labels: size/XS

#4206 Nullable Reference Types - nits.
  WalletWasabi.Gui/Validation/Validations.cs
  WalletWasabi.Gui/ViewModels/ViewModelBase.cs
  WalletWasabi/Helpers/PasswordHelper.cs
Labels: size/S

#4211 MemoryTests: Make time-sensitive test to run in serial order.
  WalletWasabi.Tests/UnitTests/MemoryTests.cs
  WalletWasabi.Tests/UnitTests/SerialMemoryTests.cs
Labels: size/L

#4060 Show amount in USD in tooltip (Send/Build tabs)
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
  WalletWasabi.Gui/Converters/UsdExchangeRateAmountToolTipConverter.cs
Labels: size/M

#4225 Shell path on Mac fix
  WalletWasabi/Helpers/EnvironmentHelpers.cs
Labels: size/XS

#4230 Fix GetSynchronizeAsync
  WalletWasabi.Backend/Controllers/BatchController.cs
Labels: size/XS

#4231 Add default value to estimateSmartFeeMode
  WalletWasabi.Backend/Controllers/BatchController.cs
Labels: size/XS

#4229 Don't define constant strings multiple times
  WalletWasabi.Backend/Controllers/BlockchainController.cs
  WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Backend/InitConfigStartupTask.cs
  WalletWasabi.Tests/RegressionTests/BackendTests.cs
  WalletWasabi.Tests/RegressionTests/BuildTests.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/RegressionTests/Common.cs
  WalletWasabi.Tests/RegressionTests/DosTests.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi.Tests/RegressionTests/WalletTests.cs
  WalletWasabi.Tests/UnitTests/BitcoinCore/IndexBuilderServiceTests.cs
  WalletWasabi.Tests/UnitTests/BitcoinCore/RpcBasedTests.cs
  WalletWasabi.Tests/UnitTests/MockRpcClient.cs
  WalletWasabi/BitcoinCore/CoreNode.cs
  WalletWasabi/BitcoinCore/Monitoring/RpcFeeProvider.cs
  WalletWasabi/BitcoinCore/Monitoring/RpcMonitor.cs
  WalletWasabi/BitcoinCore/Processes/BitcoindRpcProcessBridge.cs
  WalletWasabi/BitcoinCore/Rpc/CachedRpcClient.cs
  WalletWasabi/BitcoinCore/Rpc/IRPCClient.cs
  WalletWasabi/BitcoinCore/Rpc/Models/RpcPubkeyType.cs
  WalletWasabi/BitcoinCore/Rpc/Models/VerboseBlockInfo.cs
  WalletWasabi/BitcoinCore/Rpc/Models/VerboseInputInfo.cs
  WalletWasabi/BitcoinCore/Rpc/Models/VerboseOutputInfo.cs
  WalletWasabi/BitcoinCore/Rpc/Models/VerboseTransactionInfo.cs
  WalletWasabi/BitcoinCore/Rpc/RpcClientBase.cs
  WalletWasabi/BitcoinCore/Rpc/RpcErrorTools.cs
  WalletWasabi/BitcoinCore/Rpc/RpcParser.cs
  WalletWasabi/Blockchain/BlockFilters/IndexBuilderService.cs
  WalletWasabi/Blockchain/Blocks/BlockNotifier.cs
  WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs
  WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
  WalletWasabi/CoinJoin/Client/CoinJoinProcessor.cs
  WalletWasabi/CoinJoin/Coordinator/Banning/UtxoReferee.cs
  WalletWasabi/CoinJoin/Coordinator/Coordinator.cs
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
  WalletWasabi/Extensions/ExceptionExtensions.cs
  WalletWasabi/Extensions/RPCClientExtensions.cs
Labels: size/L

#3785 Update website menu
  WalletWasabi.Backend/wwwroot/index.html
Labels: size/XS

#4098 Website html and css fixes
  WalletWasabi.Backend/wwwroot/css/style.css
  WalletWasabi.Backend/wwwroot/index.html
Labels: size/L

#4232 Add a basic test for AbsoluteExpirationRelativeToNow
  WalletWasabi.Tests/UnitTests/MemoryTests.cs
Labels: size/S

#4234 Replace BitcoinStore with SmartHeaderChain in StatusBarViewModel.
  WalletWasabi.Gui/Program.cs
  WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
Labels: size/S

#4235 Some XAML clean up.
  WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionBroadcasterView.xaml
  WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletView.xaml
Labels: size/S

#4219 Refactor StatusBarViewModel.
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Gui/Program.cs
  WalletWasabi.Gui/ViewModels/MainWindowViewModel.cs
  WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
Labels: size/M

#4237 Packager will work on every drive
  WalletWasabi.Packager/Program.cs
Labels: size/XS

#4238 Adding stalebot conf file to the repository
  .github/stale.yml
Labels: size/M

#4036 Fix Manual Fee Validation
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
  WalletWasabi.Tests/UnitTests/GUI/SendControlViewModelTest.cs
Labels: size/M

#3924 Refactor out BitnodesApi class to make it testable.
  WalletWasabi.Packager/BitnodesApi.cs
  WalletWasabi.Packager/Program.cs
  WalletWasabi.Tests/UnitTests/Packager/BitnodesApiTests.cs
Labels: size/L

#4248 [RPC] Add the address to the returned values when calling listkeys method
  WalletWasabi.Gui/Rpc/WasabiJsonRpcService.cs
Labels: size/XS

#4215 HwiClient and new process API.
  WalletWasabi.Gui/CrashReport/CrashReporter.cs
  WalletWasabi.Tests/UnitTests/Hwi/DefaultResponseTests.cs
  WalletWasabi.Tests/UnitTests/Hwi/HwiProcessBridgeMock.cs
  WalletWasabi.Tests/UnitTests/Hwi/SerialDefaultResponseTests.cs
  WalletWasabi/Helpers/EnvironmentHelpers.cs
  WalletWasabi/Hwi/HwiClient.cs
  WalletWasabi/Hwi/ProcessBridge/HwiProcessBridge.cs
  WalletWasabi/Hwi/ProcessBridge/IHwiProcessInvoker.cs
Labels: size/M

#4249 Remove unused const
  WalletWasabi/Helpers/Constants.cs
Labels: size/XS

#4254 Remove unused consts
  WalletWasabi/Helpers/Constants.cs
Labels: size/S

#4257 Do NOT advise to write down the password
  WalletWasabi.Gui/Tabs/WalletManager/GenerateWallets/GenerateWalletSuccessView.xaml
Labels: debug, priority, size/XS

#4258 Improve HWI tests.
  WalletWasabi.Tests/UnitTests/Hwi/SerialDefaultResponseTests.cs
Labels: size/M

#4245 Improve SmartBlockProviderTests.
  WalletWasabi.Tests/UnitTests/SmartBlockProviderTests.cs
  WalletWasabi.Tests/UnitTests/TestBlockProvider.cs
  WalletWasabi/Wallets/SmartBlockProvider.cs
Labels: size/M

#4262 Nit - Fix typo
  WalletWasabi.Gui/Tabs/WalletManager/GenerateWallets/GenerateWalletSuccessView.xaml
Labels: size/XS

#4266 Remove unused JsonConverters
  WalletWasabi/JsonConverters/FeeRatePerKbJsonConverter.cs
  WalletWasabi/JsonConverters/FunnyBoolJsonConverter.cs
  WalletWasabi/JsonConverters/GolombRiceFilterJsonConverter.cs
  WalletWasabi/JsonConverters/ScriptJsonConverter.cs
Labels: size/L

#4246 NullFail check added to test
  WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
  WalletWasabi.Tests/AcceptanceTests/HwiKatas.cs
Labels: size/L

#4251 [PoC] Coldcard freeze and throws UnknownError during test
  WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
  WalletWasabi.Tests/AcceptanceTests/HwiKatas.cs
Labels: size/L

#4191 Fix Coldcard & Ledger S Katas
  WalletWasabi.Tests/AcceptanceTests/HwiKatas.cs
Labels: size/M

#3863 Refactored ProcessBridge with #3849 merged.
  WalletWasabi/Bases/ExceptionInfo.cs
  WalletWasabi/BitcoinCore/Processes/BitcoindProcessBridge.cs
  WalletWasabi/BitcoinCore/Processes/BitcoindRpcProcessBridge.cs
  WalletWasabi/Extensions/ProcessExtensions.cs
  WalletWasabi/Helpers/EnvironmentHelpers.cs
  WalletWasabi/Microservices/IProcessBridge.cs
  WalletWasabi/Microservices/ProcessBridge.cs
Labels: size/L
