Repository WalletWasabi/WalletWasabi, pull requests merged in 2020-05, with the labels that each got.

#3586 Refactor Validation
  WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoViewModel.cs
  WalletWasabi.Gui/Converters/ErrorDescriptorToBorderColorConverter.cs
  WalletWasabi.Gui/Tabs/SettingsViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/GenerateWallets/GenerateWalletViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/RecoverWallets/RecoverWalletViewModel.cs
  WalletWasabi.Gui/Validation/IRegisterValidationMethod.cs
  WalletWasabi.Gui/Validation/IValidations.cs
  WalletWasabi.Gui/Validation/ValidationExtensions.cs
  WalletWasabi.Gui/Validation/Validations.cs
  WalletWasabi.Gui/ViewModels/Validation/ReflectionHelper.cs
  WalletWasabi.Gui/ViewModels/Validation/ValidateMethodAttribute.cs
  WalletWasabi.Gui/ViewModels/Validation/Validator.cs
  WalletWasabi.Gui/ViewModels/ViewModelBase.cs
  WalletWasabi.Tests/UnitTests/ValidateMethodTests.cs
  WalletWasabi/Helpers/PasswordHelper.cs
  WalletWasabi/Models/ErrorDescriptors.cs
  WalletWasabi/Models/IValidationErrors.cs
Labels: size/XL

#3600 Enable PropertySummaryDocumentationMustMatchAccessors
  Settings.StyleCop
  WalletWasabi.Gui/Rpc/JsonRpcRequest.cs
  WalletWasabi/Blockchain/Analysis/FeesEstimation/AllFeeEstimate.cs
  WalletWasabi/Blockchain/TransactionProcessing/ProcessedResult.cs
  WalletWasabi/CoinJoin/Client/Rounds/ClientRoundRegistration.cs
  WalletWasabi/CoinJoin/Common/Models/RoundStateResponse.cs
  WalletWasabi/Interfaces/IConfig.cs
  WalletWasabi/Io/DigestableSafeMutexIoManager.cs
  WalletWasabi/Logging/Logger.cs
  WalletWasabi/Nito/AsyncEx/AsyncMutex.cs
  WalletWasabi/Nito/AsyncEx/IAsyncWaitQueue.cs
  WalletWasabi/Services/WasabiSynchronizer.cs
Labels: size/M

#3623 Update WasabiSetupRegtest by using Bitcoin Knots
  WalletWasabi.Documentation/WasabiSetupRegtest.md
Labels: size/XS

#3629 Refactor UnblindedSignature class
  WalletWasabi.Tests/UnitTests/JsonConvertersTest/UnblindedSignatureTests.cs
  WalletWasabi/Crypto/UnblindedSignature.cs
Labels: size/M

#3537 Tweak LegalDocsView.
  WalletWasabi.Gui/Tabs/LegalDocumentsView.xaml
Labels: size/M

#3621 Use expression body + formatting
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
  WalletWasabi/Extensions/NBitcoinExtensions.cs
  WalletWasabi/Helpers/PasswordHelper.cs
  WalletWasabi/Wallets/P2pBlockProvider.cs
Labels: size/S

#3610 Enable DocumentationTextMustNotBeEmpty
  Settings.StyleCop
Labels: size/XS

#3630 Add a shebang line to the top of .coverage.sh file
  .coverage.sh
Labels: size/XS

#3561 Reduce bandwidth by not downloading same block more than once
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Tests/Helpers/TestNodeBuilder.cs
  WalletWasabi.Tests/UnitTests/SmartBlockProviderTests.cs
  WalletWasabi/BitcoinCore/CoreNode.cs
  WalletWasabi/BitcoinCore/CoreNodeParams.cs
  WalletWasabi/Wallets/SmartBlockProvider.cs
Labels: size/L

#3639 Remove BIP21 "bpu" payjoin detection
  WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
Labels: size/XS

#3633 [RPC] Add "confirmations" field to "listunspentcoins" json response
  WalletWasabi.Gui/Rpc/WasabiJsonRpcService.cs
Labels: size/XS

#3631 Remove duplicate code
  WalletWasabi.Packager/Program.cs
Labels: size/M

#3617 Refactor Wallet Generated Screen
  WalletWasabi.Gui/Tabs/WalletManager/GenerateWallets/GenerateWalletSuccessView.xaml
  WalletWasabi.Gui/Tabs/WalletManager/GenerateWallets/GenerateWalletSuccessView.xaml.cs
  WalletWasabi.Gui/Tabs/WalletManager/GenerateWallets/GenerateWalletSuccessViewModel.cs
Labels: size/M

#3615 Password finder
  WalletWasabi.Gui/CommandLine/PasswordFinderCommand.cs
Labels: size/XS

#3613 Enable SingleLineCommentMustBePrecededByBlankLine
  Settings.StyleCop
Labels: size/XS

#3652 Check if IsCoinBase first when checking if utxo is immature
  WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
Labels: size/XS

#3622 Refactor SchnorrBlinding class
  WalletWasabi/Crypto/SchnorrBlindingSignature.cs
Labels: size/M

#3666 Fix spelling
  WalletWasabi.Documentation/Guides/HowToDebug.md
Labels: size/XS

#3645 Make MixUntilAnonymitySet an enum
  WalletWasabi.Gui/CommandLine/Daemon.cs
  WalletWasabi.Gui/Config.cs
  WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs
  WalletWasabi.Gui/Converters/PrivacyLevelValueConverter.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Gui/Models/TargetPrivacy.cs
  WalletWasabi.Gui/Tabs/SettingsViewModel.cs
  WalletWasabi.Tests/IntegrationTests/P2pTests.cs
  WalletWasabi.Tests/RegressionTests/Common.cs
  WalletWasabi/Models/MixUntilAnonymitySet.cs
  WalletWasabi/Models/ServiceConfiguration.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/L

#3670 Stricten Mempool Acceptance With Batching
  WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
  WalletWasabi/Extensions/LinqExtensions.cs
  WalletWasabi/Extensions/RPCClientExtensions.cs
  WalletWasabi/Helpers/NBitcoinHelpers.cs
Labels: size/L

#3642 make error notification clear
  WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
Labels: size/XS

#3656 Hide CoinJoin tab if watch only wallet
  WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/WalletViewModel.cs
Labels: size/S

#3678 Dismiss false alarms on Backend about filter generation
  WalletWasabi.Backend/Controllers/BlockchainController.cs
  WalletWasabi/Blockchain/BlockFilters/IndexBuilderService.cs
Labels: size/S

#3684 Refactoring: Use is null
  WalletWasabi.Gui/Rpc/JsonRpcRequest.cs
  WalletWasabi/Crypto/UnblindedSignature.cs
  WalletWasabi/Extensions/LinqExtensions.cs
  WalletWasabi/Helpers/Guard.cs
  WalletWasabi/Nito/Collections/Deque.cs
Labels: size/S

#3570 Add rule to use pattern matching
  .editorconfig
  WalletWasabi.Tests/UnitTests/Converters/TxoRef.cs
Labels: size/XS

#3677 Auto close wallet manager in a better place.
  WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/WalletManagerViewModel.cs
Labels: size/M

#3692 Log Debug instead of Info
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
Labels: size/XS

#3637 Support Payjoin through Clearnet HTTPClient when Tor is explicitly turned off.
  WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
  WalletWasabi.Tests/UnitTests/Clients/MockTorHttpClient.cs
  WalletWasabi/WebClients/PayJoin/PayjoinClient.cs
Labels: size/M

#3689 Fix CodeFactor style issue (Single line comment must be preceded by blank line)
  WalletWasabi.Gui/CommandLine/Daemon.cs
  WalletWasabi.Packager/Tools.cs
  WalletWasabi.Tests/UnitTests/BitcoinCore/ConfigTranslatorTests.cs
  WalletWasabi.Tests/UnitTests/BitcoinCore/IndexBuilderServiceTests.cs
  WalletWasabi.Tests/UnitTests/HashChainTests.cs
  WalletWasabi.Tests/UnitTests/LegalTests.cs
  WalletWasabi.Tests/UnitTests/PasswordTests.cs
  WalletWasabi.Tests/UnitTests/SmartCoinTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/SmartTransactionTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
  WalletWasabi/BitcoinCore/CachedRpcClient.cs
  WalletWasabi/Blockchain/Analysis/FeesEstimation/AllFeeEstimate.cs
  WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs
  WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs
  WalletWasabi/Blockchain/Transactions/SmartTransaction.cs
  WalletWasabi/CoinJoin/Common/Models/RoundStateResponse.cs
  WalletWasabi/CoinJoin/Coordinator/Coordinator.cs
  WalletWasabi/Extensions/RPCClientExtensions.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/BitList.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/DataEncodation/DataEncode.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/DataEncodation/ECISet.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/DataEncodation/EightBitByteEncoder.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/DataEncodation/InputRecognition/InputRecognise.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/EncodingRegion/BCHCalculator.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/EncodingRegion/VersionInformation.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/Masking/Scoring/Penalty3.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/Positioning/Stencils/TimingPattern.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/ReedSolomon/GaloisField256.cs
  WalletWasabi/Helpers/HttpRequestUriBuilder.cs
  WalletWasabi/Http/Models/RequestLine.cs
  WalletWasabi/Hwi/HwiClient.cs
  WalletWasabi/Logging/Logger.cs
  WalletWasabi/Nito/AsyncEx/AsyncMutex.cs
  WalletWasabi/Nito/Collections/Deque.cs
  WalletWasabi/Services/WasabiSynchronizer.cs
  WalletWasabi/TorSocks5/Models/Fields/ByteArrayFields/PortField.cs
Labels: size/L

#3705 Add verbose console logging for CI tests
  azure-pipelines-linux.yml
  azure-pipelines-osx.yml
  azure-pipelines-windows.yml
Labels: size/XS

#3707 Call Environment.Exit at a better place
  WalletWasabi.Gui/CommandLine/Daemon.cs
  WalletWasabi.Gui/CommandLine/MixerCommand.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Gui/Program.cs
Labels: size/M

#3698 Save column sorting preferences
  WalletWasabi.Gui/Controls/LockScreen/SlideLockScreenView.xaml
  WalletWasabi.Gui/Controls/SortingArrow.cs
  WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs
  WalletWasabi.Gui/Converters/SortingPreferenceJsonConverter.cs
  WalletWasabi.Gui/Models/Sorting/SortOrder.cs
  WalletWasabi.Gui/Models/Sorting/SortingPreference.cs
  WalletWasabi.Gui/UiConfig.cs
Labels: size/L

#3711 [Trivial] Simplify conditional expression
  WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs
  WalletWasabi.Packager/Program.cs
  WalletWasabi/Blockchain/Mempool/MempoolService.cs
  WalletWasabi/Nito/Collections/Deque.cs
Labels: size/S
