Repository WalletWasabi/WalletWasabi, pull requests merged in 2020-12, with the labels that each got.

#4832 [Fluent] Clean-up
  WalletWasabi.Fluent/Behaviors/FocusNextItemBehavior.cs
  WalletWasabi.Fluent/Controls/Dialog.xaml.cs
  WalletWasabi.Fluent/Controls/InfoMessage.axaml.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/TestDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Fluent/Views/AboutView.axaml
  WalletWasabi.Fluent/Views/AboutView.axaml.cs
  WalletWasabi.Fluent/Views/AddWallet/AddWalletPageView.axaml.cs
  WalletWasabi.Fluent/Views/AddWallet/ConfirmRecoveryWordsView.axaml.cs
  WalletWasabi.Fluent/Views/AddWallet/LegalDocumentsView.axaml.cs
  WalletWasabi.Fluent/Views/AddWallet/RecoverWalletView.axaml.cs
  WalletWasabi.Fluent/Views/AddWallet/RecoveryWordsView.axaml.cs
  WalletWasabi.Fluent/Views/AddWallet/TermsAndConditionsView.axaml.cs
  WalletWasabi.Fluent/Views/Dialogs/AboutAdvancedInfoView.axaml
  WalletWasabi.Fluent/Views/Dialogs/AboutAdvancedInfoView.axaml.cs
  WalletWasabi.Fluent/Views/Dialogs/AdvancedRecoveryOptionsView.axaml.cs
  WalletWasabi.Fluent/Views/Dialogs/EnterPasswordView.axaml.cs
  WalletWasabi.Fluent/Views/HomePageView.axaml.cs
  WalletWasabi.Fluent/Views/MainView.axaml
  WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
  WalletWasabi.Fluent/Views/Search/SearchPageView.axaml.cs
  WalletWasabi.Fluent/Views/Settings/SettingsPageView.xaml.cs
Labels: size/L

#4828 Fix typo
  CONTRIBUTING.md
Labels: size/XS

#4829 Fix typo
  README.md
Labels: size/XS

#4831 Fix typo
  WalletWasabi.Documentation/ClientDeployment.md
Labels: size/XS

#4830 Warning text nitpick
  WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
Labels: size/XS

#4833 Add sanity check to BlockchainAnalyzer.AdjustWalletInputs
  WalletWasabi.Tests/UnitTests/BlockchainAnalysis/PubKeyReuseAnonScoreTests.cs
  WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs
Labels: size/S

#4838 [Fluent] [Trivial] Fix AcrylicFallbackColor type
  WalletWasabi.Fluent/Styles/Themes/BaseDark.xaml
  WalletWasabi.Fluent/Styles/Themes/BaseLight.xaml
Labels: size/XS

#4836 Remove missing entries from SLN
  WalletWasabi.sln
Labels: size/XS

#4814 Add CancellationToken forwarding rule (CA2016)
  .editorconfig
  WalletWasabi/Bases/PeriodicRunner.cs
  WalletWasabi/BitcoinCore/CoreNode.cs
  WalletWasabi/BitcoinCore/P2pNode.cs
  WalletWasabi/BitcoinCore/Processes/BitcoindRpcProcessBridge.cs
  WalletWasabi/Blockchain/Transactions/TransactionStore.cs
  WalletWasabi/Stores/IndexStore.cs
  WalletWasabi/Tor/Http/TorHttpClient.cs
  WalletWasabi/Tor/Socks5/TorSocks5Client.cs
  WalletWasabi/Wallets/FileSystemBlockRepository.cs
  WalletWasabi/Wallets/Wallet.cs
  WalletWasabi/WebClients/PayJoin/PayjoinClient.cs
Labels: size/M

#4840 [Fluent] Collapse navbar view when there are no wallets available.
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Fluent/Views/MainView.axaml
Labels: size/M

#4839 [Fluent] Navigation metadata
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.sln
  WalletWasabi.Fluent.Generators/AutoNotifyGenerator.cs
  WalletWasabi.Fluent.Generators/NavigationMetaDataGenerator.cs
  WalletWasabi.Fluent.Generators/PropertyGenerator.cs
  WalletWasabi.Fluent.Generators/WalletWasabi.Fluent.Generators.csproj
  WalletWasabi.Fluent/ViewModels/AboutViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/INavigationStack.cs
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationManager.cs
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationStack.cs
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationState.cs
  WalletWasabi.Fluent/ViewModels/Navigation/RoutableViewModel.cs
  WalletWasabi.Fluent/ViewModels/TestViewModel1.cs
  WalletWasabi.Fluent/ViewModels/TestViewModel2.cs
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
Labels: size/XL

#4843 Generated INPC and ViewModel registration
  WalletWasabi.Fluent.Generators/NavigationMetaDataGenerator.cs
  WalletWasabi.Fluent/ViewModels/AboutViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/LegalDocumentsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoveryWordViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/TermsAndConditionsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/AdvancedRecoveryOptionsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/DialogScreenViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/DialogViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/EnterPasswordViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/TestDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/HomePageViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationManager.cs
  WalletWasabi.Fluent/ViewModels/Navigation/RoutableViewModel.cs
  WalletWasabi.Fluent/ViewModels/Search/SearchItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Search/SearchPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/BitcoinTabViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/GeneralSettingsTabViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/NetworkSettingsTabViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/PrivacyModeViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/PrivacySettingsTabViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/SettingsPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/TestViewModel1.cs
  WalletWasabi.Fluent/ViewModels/TestViewModel2.cs
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/ClosedWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModelBase.cs
  WalletWasabi.Fluent/Views/Settings/GeneralSettingsView.xaml
  WalletWasabi.Fluent/Views/Settings/NetworkSettingsView.xaml
  WalletWasabi.Fluent/Views/Settings/PrivacySettingsView.xaml
  WalletWasabi.Fluent/Views/Settings/SettingsPageView.xaml
Labels: size/XXL

#4835 [Fluent] Fix solution file
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.sln
Labels: size/S

#4731 [Fluent] Add hardware wallet
  WalletWasabi.Fluent/Assets/HardwareIcons/coldcard.png
  WalletWasabi.Fluent/Assets/HardwareIcons/coldcard.svg
  WalletWasabi.Fluent/Assets/HardwareIcons/generic.png
  WalletWasabi.Fluent/Assets/HardwareIcons/ledger.png
  WalletWasabi.Fluent/Assets/HardwareIcons/ledger.svg
  WalletWasabi.Fluent/Assets/HardwareIcons/normal.png
  WalletWasabi.Fluent/Assets/HardwareIcons/trezor.png
  WalletWasabi.Fluent/Assets/HardwareIcons/trezor.svg
  WalletWasabi.Fluent/Controls/ContentArea.axaml
  WalletWasabi.Fluent/Controls/InfoMessage.axaml
  WalletWasabi.Fluent/Converters/HardwareWalletIconConverter.cs
  WalletWasabi.Fluent/Converters/WalletTypeImageConverter.cs
  WalletWasabi.Fluent/Icons/Icons.xaml
  WalletWasabi.Fluent/Styles/HyperlinkButton.xaml
  WalletWasabi.Fluent/Styles/Styles.xaml
  WalletWasabi.Fluent/Styles/Themes/Base.xaml
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/AddedWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/ConfirmRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/RecoveryWordViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/RecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/ConnectHardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/DetectedHardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/HardwareWalletOperations.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModelBase.cs
  WalletWasabi.Fluent/Views/AddWallet/AddWalletPageView.axaml
  WalletWasabi.Fluent/Views/AddWallet/AddedWalletPageView.axaml
  WalletWasabi.Fluent/Views/AddWallet/AddedWalletPageView.axaml.cs
  WalletWasabi.Fluent/Views/AddWallet/Create/ConfirmRecoveryWordsView.axaml
  WalletWasabi.Fluent/Views/AddWallet/Create/ConfirmRecoveryWordsView.axaml.cs
  WalletWasabi.Fluent/Views/AddWallet/Create/RecoveryWordsView.axaml
  WalletWasabi.Fluent/Views/AddWallet/Create/RecoveryWordsView.axaml.cs
  WalletWasabi.Fluent/Views/AddWallet/HardwareWallet/ConnectHardwareWalletView.axaml
  WalletWasabi.Fluent/Views/AddWallet/HardwareWallet/ConnectHardwareWalletView.axaml.cs
  WalletWasabi.Fluent/Views/AddWallet/HardwareWallet/DetectedHardwareWalletView.axaml
  WalletWasabi.Fluent/Views/AddWallet/HardwareWallet/DetectedHardwareWalletView.axaml.cs
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Gui/Tabs/WalletManager/HardwareWallets/HardwareWalletViewModel.cs
  WalletWasabi/Hwi/Models/HwiEnumerateEntry.cs
Labels: size/XL

#4849 [Fluent] Add support for generic types in property generators
  WalletWasabi.Fluent.Generators/AutoNotifyGenerator.cs
  WalletWasabi.Fluent.Generators/NavigationMetaDataGenerator.cs
  WalletWasabi.Fluent.Generators/PropertyGenerator.cs
Labels: size/M

#4851 Fluent: more metadata.
  WalletWasabi.Fluent.Generators/NavigationMetaDataGenerator.cs
  WalletWasabi.Fluent/ViewModels/AboutViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/LegalDocumentsViewModel.cs
  WalletWasabi.Fluent/ViewModels/HomePageViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationState.cs
  WalletWasabi.Fluent/ViewModels/Navigation/RoutableViewModel.cs
  WalletWasabi.Fluent/ViewModels/Search/SearchPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/BitcoinTabSettingsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/SettingsPageViewModel.cs
  WalletWasabi.Fluent/Views/Settings/BitcoinSettingsView.xaml
  WalletWasabi.Fluent/Views/Settings/SettingsPageView.xaml
Labels: size/L

#4763 Replace SingleInstance AsyncMutex with TcpListener.
  WalletWasabi.Documentation/Ports.md
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Tests/UnitTests/Clients/SingleInstanceCheckerTests.cs
  WalletWasabi/Services/SingleInstanceChecker.cs
Labels: size/L

#4853 Add code quality rule (CA2000: Dispose objects before losing scope)
  .editorconfig
Labels: size/XS

#4845 [Trivial] Fix name violations
  WalletWasabi/WebClients/Wasabi/WasabiClient.cs
Labels: size/S

#4841 Clean documentation
  WalletWasabi.Documentation/Guides/20180719DemoGuide.md
  WalletWasabi.Documentation/Guides/20190416HardwareWalletTestingGuide.md
  WalletWasabi.Documentation/Guides/20190617ContributionGame.md
Labels: size/XS

#4854 [Trivial] Remove unused variables
  WalletWasabi.Tests/UnitTests/Crypto/MacTests.cs
Labels: size/XS

#4863 [Trivial] Use StringBuilder.Append(char) for single character strings
  WalletWasabi.Gui/Converters/PascalToPhraseConverter.cs
  WalletWasabi/Backend/Models/FilterModel.cs
  WalletWasabi/Mono/OptionSet.cs
Labels: size/S

#4847 Add avoid zero-length array allocations rule
  .editorconfig
  WalletWasabi.Tests/UnitTests/Crypto/ProofSystemHelpers.cs
  WalletWasabi.Tests/UnitTests/Crypto/ProofSystemTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/TranscriptTests.cs
  WalletWasabi.Tests/UnitTests/Wabisabi/CredentialTests.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/Positioning/Stencils/AlignmentPattern.cs
Labels: size/S

#4852 Add code quality rule (CA1829: Use Length/Count property instead of Enumerable.Count method)
  .editorconfig
  WalletWasabi.Gui/Rpc/JsonRpcRequestHandler.cs
  WalletWasabi.Tests/UnitTests/Clients/WasabiClientTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/TranscriptTests.cs
  WalletWasabi.Tests/UnitTests/NBitcoinTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
  WalletWasabi.Tests/UnitTests/Wabisabi/CredentialTests.cs
  WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Knowledge.cs
  WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Statement.cs
  WalletWasabi/Extensions/NBitcoinExtensions.cs
Labels: size/M

#4855 Swap arguments order
  WalletWasabi/Backend/Models/FilterModel.cs
Labels: size/XS

#4861 TransactionFactoryTests: Fix usings.
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
Labels: size/L

#4859 [Fluent] [Trivial] Rename settings tabs to match view models
  WalletWasabi.Fluent/Views/Settings/BitcoinTabSettingsView.xaml
  WalletWasabi.Fluent/Views/Settings/BitcoinTabSettingsView.xaml.cs
  WalletWasabi.Fluent/Views/Settings/GeneralSettingsTabView.xaml
  WalletWasabi.Fluent/Views/Settings/GeneralSettingsTabView.xaml.cs
  WalletWasabi.Fluent/Views/Settings/NetworkSettingsTabView.xaml
  WalletWasabi.Fluent/Views/Settings/NetworkSettingsTabView.xaml.cs
  WalletWasabi.Fluent/Views/Settings/PrivacySettingsTabView.xaml
  WalletWasabi.Fluent/Views/Settings/PrivacySettingsTabView.xaml.cs
  WalletWasabi.Fluent/Views/Settings/SettingsPageView.xaml
Labels: size/M

#4857 [Fluent] [Trivial] Remove usage of ReactiveUserControl
  WalletWasabi.Fluent/Views/AddWallet/AddedWalletPageView.axaml.cs
Labels: size/XS

#4858 [Fluent] [Trivial] Cleanup WalletWasabi.Fluent project file
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
Labels: size/S

#4850 Upgrade Windows CI vmImage
  azure-pipelines-windows.yml
Labels: size/XS

#4871 Dump version to 1.1.12.3
  WalletWasabi.Backend/wwwroot/index.html
  WalletWasabi/Helpers/Constants.cs
Labels: size/S

#4874 [Fluent] Recovery words view fixes
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/Create/RecoveryWordsView.axaml
Labels: size/XS

#4872 [Fluent] Move the Open wallet folder button into search
  WalletWasabi.Fluent/ViewModels/HomePageViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/OpenWalletsFolderViewModel.cs
  WalletWasabi.Fluent/Views/HomePageView.axaml
Labels: size/M

#4875 [Fluent] Move Dialog back button away from content
  WalletWasabi.Fluent/Controls/ContentArea.axaml
Labels: size/XS

#4873 Remove Homepage / Rename Search to Action Center
  WalletWasabi.Fluent/Controls/ContentArea.axaml
  WalletWasabi.Fluent/Icons/Icons.xaml
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/HomePageViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/Search/SearchPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/SettingsPageViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/HardwareWallet/DetectedHardwareWalletView.axaml
  WalletWasabi.Fluent/Views/HomePageView.axaml
  WalletWasabi.Fluent/Views/Search/SearchPageView.axaml
  WalletWasabi.Fluent/Views/Wallets/ClosedHardwareWalletView.axaml
  WalletWasabi.Fluent/Views/Wallets/ClosedHardwareWalletView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/ClosedWalletView.axaml
  WalletWasabi.Fluent/Views/Wallets/ClosedWalletView.xaml.cs
  WalletWasabi.Fluent/Views/Wallets/LoginView.axaml
  WalletWasabi.Fluent/Views/Wallets/LoginView.xaml.cs
Labels: size/L

#4876 fix resizing of welcome screen content.
  WalletWasabi.Fluent/Views/AddWallet/TermsAndConditionsView.axaml
Labels: size/XS

#4877 Vdg/fix resizing added screen
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/AddedWalletPageView.axaml
Labels: size/S

#4870 Add rule to disable CA1816 warnings
  .editorconfig
Labels: size/XS

#4879 [Fluent] [Trivial] Remove unused property from view locator
  WalletWasabi.Fluent/ViewLocator.cs
Labels: size/XS

#4881 [Fluent] Static view locator
  WalletWasabi.Fluent.Generators/StaticViewLocatorGenerator.cs
  WalletWasabi.Fluent/ViewLocator.cs
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
Labels: size/L

#4880 Tests: Set higher timeout for GetNodeVersionTestsAsync.
  WalletWasabi.Tests/UnitTests/BitcoinCore/NodeBuildingTests.cs
Labels: size/XS

#4882 [Fluent] Finishing off jobs
  WalletWasabi.Fluent/App.xaml
  WalletWasabi.Fluent/Controls/Dialog.xaml
  WalletWasabi.Fluent/Controls/InfoMessage.axaml.cs
  WalletWasabi.Fluent/Controls/TileButton.axaml
  WalletWasabi.Fluent/Controls/TileButton.axaml.cs
  WalletWasabi.Fluent/Icons/Icons.xaml
  WalletWasabi.Fluent/Styles/HyperlinkButton.xaml
  WalletWasabi.Fluent/Styles/Themes/BaseDark.xaml
  WalletWasabi.Fluent/Styles/Themes/BaseLight.xaml
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/ConnectHardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/ImportWalletViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/AddWalletPageView.axaml
  WalletWasabi.Fluent/Views/AddWallet/HardwareWallet/ConnectHardwareWalletView.axaml
  WalletWasabi.Fluent/Views/TransactionBroadcasting/LoadTransactionView.axaml
Labels: size/L

#4887 [Fluent] [Trivial] Fix nullable warnings
  WalletWasabi.Fluent.Generators/StaticViewLocatorGenerator.cs
  WalletWasabi.Fluent/ViewLocator.cs
Labels: size/XS

#4883 Use Process.WaitForExitAsync from .NET 5.
  WalletWasabi/Microservices/ProcessAsync.cs
Labels: size/M

#4888 Fluent layout minifixes
  WalletWasabi.Fluent/Views/AddWallet/RecoverWalletView.axaml
  WalletWasabi.Fluent/Views/Dialogs/AdvancedRecoveryOptionsView.axaml
Labels: size/S

#4889 [Fluent] Add links in action center from the old file/help menu.
  WalletWasabi.Fluent/Icons/Icons.xaml
  WalletWasabi.Fluent/ViewModels/AboutViewModel.cs
  WalletWasabi.Fluent/ViewModels/HelpAndSupport/BugReportLinkViewModel.cs
  WalletWasabi.Fluent/ViewModels/HelpAndSupport/DocsLinkViewModel.cs
  WalletWasabi.Fluent/ViewModels/HelpAndSupport/UserSupportViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/OpenDirectory/OpenConfigFileViewModel.cs
  WalletWasabi.Fluent/ViewModels/OpenDirectory/OpenDataFolderViewModel.cs
  WalletWasabi.Fluent/ViewModels/OpenDirectory/OpenLogsViewModel.cs
  WalletWasabi.Fluent/ViewModels/OpenDirectory/OpenTorLogsViewModel.cs
  WalletWasabi.Fluent/ViewModels/OpenDirectory/OpenWalletsFolderViewModel.cs
  WalletWasabi.Fluent/ViewModels/OpenWalletsFolderViewModel.cs
  WalletWasabi.Fluent/ViewModels/TriggerCommandViewModel.cs
Labels: size/L

#4893 return to login page after oobe.
  WalletWasabi.Fluent/ViewModels/AddWallet/AddedWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationManager.cs
Labels: size/M

#4885 [Fluent] Navigate back to Action Center when already selected in NavBar
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/AddWalletPageView.axaml
  WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
  WalletWasabi.Fluent/Views/Settings/SettingsPageView.xaml
Labels: size/M

#4894 Fluent: remove initialisation of legacy stuff from old ui project.
  WalletWasabi.Fluent.Desktop/Program.cs
  WalletWasabi.Fluent/App.xaml.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Gui/ViewModels/MainWindowViewModel.cs
  WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
Labels: size/M

#4884 Clean bin directory before publish on backend
  WalletWasabi.Documentation/BackendDeployment.md
Labels: size/XS

#4896 Unify Fluent and GUI solution file
  NuGet.Config
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.sln
  WalletWasabi.Fluent.Desktop/nuget.config
  WalletWasabi.sln
  azure-pipelines-linux.yml
  azure-pipelines-osx.yml
  azure-pipelines-windows.yml
Labels: size/L

#4899 [Fluent] Action Center layout optimization
  WalletWasabi.Fluent/Views/Search/SearchPageView.axaml
Labels: size/XS

#4904 put add wallet button back.
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
Labels: size/XS

#4808 Do not subscribe to SystemEvents in DEBUG
  WalletWasabi/Services/Terminate/TerminateService.cs
Labels: size/S

#4907 Add log access guide
  WalletWasabi.Documentation/BackendDeployment.md
Labels: size/XS

#4905 [Fluent] [Trivial] Remove unused xaml usings
  WalletWasabi.Fluent/Views/AddWallet/AddWalletPageView.axaml
  WalletWasabi.Fluent/Views/AddWallet/HardwareWallet/DetectedHardwareWalletView.axaml
  WalletWasabi.Fluent/Views/Search/SearchPageView.axaml
  WalletWasabi.Fluent/Views/Wallets/ClosedHardwareWalletView.axaml
  WalletWasabi.Fluent/Views/Wallets/ClosedWalletView.axaml
  WalletWasabi.Fluent/Views/Wallets/LoginView.axaml
Labels: size/S

#4910 Fluent - Trivial - Avalonia 0.10-rc1
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
Labels: size/S

#4911 Have console only in Debug
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
Labels: size/S

#4914 Fluent: Trivial : prevent label stealing click inside checkbox.
  WalletWasabi.Fluent/Views/AddWallet/TermsAndConditionsView.axaml
Labels: size/XS

#4897 Move SingleInstanceChecker to program.cs from global
  WalletWasabi.Fluent.Desktop/Program.cs
  WalletWasabi.Gui/Global.cs
Labels: size/M

#4915 Fluent implement a DialogResult<T>
  WalletWasabi.Fluent/ViewModels/AboutViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/AdvancedRecoveryOptionsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/DialogResult.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/DialogResultKind.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/DialogViewModelBaseOfTResult.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/EnterPasswordViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/TestDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/RoutableViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/TargettedNavigationStack.cs
  WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/LoadTransactionViewModel.cs
Labels: size/L

#4924 [Fluent] Move DustThreshold to the Bitcoin tab
  WalletWasabi.Fluent/ViewModels/Settings/BitcoinTabSettingsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/GeneralSettingsTabViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/NetworkSettingsTabViewModel.cs
  WalletWasabi.Fluent/Views/Settings/BitcoinTabSettingsView.xaml
  WalletWasabi.Fluent/Views/Settings/GeneralSettingsTabView.xaml
Labels: size/M

#4906 [Fluent] Disable dismiss dialogs by clicking outside
  WalletWasabi.Fluent/Controls/ContentArea.axaml
  WalletWasabi.Fluent/Controls/Dialog.xaml.cs
  WalletWasabi.Fluent/ViewModels/AboutViewModel.cs
  WalletWasabi.Fluent/Views/AboutView.axaml
  WalletWasabi.Fluent/Views/MainView.axaml
Labels: size/M

#4920 [Fluent] Move about view to HelpAndSupport directory
  WalletWasabi.Fluent/ViewModels/HelpAndSupport/AboutViewModel.cs
  WalletWasabi.Fluent/Views/HelpAndSupport/AboutView.axaml
  WalletWasabi.Fluent/Views/HelpAndSupport/AboutView.axaml.cs
Labels: size/XS

#4895 [Fluent] Display errors
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/AddedWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/ConfirmRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/RecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/ConnectHardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/DetectedHardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/HardwareWalletOperations.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/ImportWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/LegalDocumentsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/TermsAndConditionsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/AdvancedRecoveryOptionsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/EnterPasswordViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/ShowErrorDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/TestDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/RoutableViewModel.cs
  WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/BroadcastTransactionViewModel.cs
  WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/LoadTransactionViewModel.cs
  WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/SuccessBroadcastTransactionViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/AddWalletPageView.axaml
  WalletWasabi.Fluent/Views/AddWallet/AddedWalletPageView.axaml
  WalletWasabi.Fluent/Views/AddWallet/Create/ConfirmRecoveryWordsView.axaml
  WalletWasabi.Fluent/Views/AddWallet/Create/RecoveryWordsView.axaml
  WalletWasabi.Fluent/Views/AddWallet/HardwareWallet/ConnectHardwareWalletView.axaml
  WalletWasabi.Fluent/Views/AddWallet/HardwareWallet/DetectedHardwareWalletView.axaml
  WalletWasabi.Fluent/Views/AddWallet/LegalDocumentsView.axaml
  WalletWasabi.Fluent/Views/AddWallet/RecoverWalletView.axaml
  WalletWasabi.Fluent/Views/AddWallet/TermsAndConditionsView.axaml
  WalletWasabi.Fluent/Views/Dialogs/AdvancedRecoveryOptionsView.axaml
  WalletWasabi.Fluent/Views/Dialogs/EnterPasswordView.axaml
  WalletWasabi.Fluent/Views/Dialogs/ShowErrorDialogView.axaml
  WalletWasabi.Fluent/Views/Dialogs/ShowErrorDialogView.axaml.cs
  WalletWasabi.Fluent/Views/Dialogs/TestDialogView.axaml
  WalletWasabi.Fluent/Views/Search/SearchPageView.axaml
  WalletWasabi.Fluent/Views/Settings/SettingsPageView.xaml
  WalletWasabi.Fluent/Views/TransactionBroadcasting/BroadcastTransactionView.axaml
  WalletWasabi.Fluent/Views/TransactionBroadcasting/LoadTransactionView.axaml
  WalletWasabi.Fluent/Views/TransactionBroadcasting/SuccessBroadcastTransactionView.axaml
  WalletWasabi.Fluent/Views/TransactionBroadcasting/SuccessBroadcastTransactionView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/LoginView.xaml.cs
  WalletWasabi/Helpers/ImportWalletHelper.cs
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/XL

#4918 [Fluent] Vertically center confirmation words
  WalletWasabi.Fluent/Views/AddWallet/Create/ConfirmRecoveryWordsView.axaml
Labels: size/XS

#4927 [Fluent] Hide cancel button on rec words confirmation
  WalletWasabi.Fluent/Views/AddWallet/Create/ConfirmRecoveryWordsView.axaml
Labels: size/XS

#4919 [Fluent] About page fixes
  WalletWasabi.Fluent/Icons/Icons.xaml
  WalletWasabi.Fluent/ViewModels/Dialogs/AboutAdvancedInfoViewModel.cs
  WalletWasabi.Fluent/ViewModels/HelpAndSupport/AboutViewModel.cs
  WalletWasabi.Fluent/Views/Dialogs/AboutAdvancedInfoView.axaml
  WalletWasabi.Fluent/Views/HelpAndSupport/AboutView.axaml
Labels: size/L

#4922 CA2200: Rethrow to preserve stack details
  .editorconfig
  WalletWasabi.Backend/Controllers/BlockchainController.cs
  WalletWasabi.Tests/RegressionTests/BuildTests.cs
  WalletWasabi/Services/WasabiSynchronizer.cs
Labels: size/XS

#4926 Prefer the memory-based overloads of ReadAsync/WriteAsync methods in stream-based classes (CA1835)
  .editorconfig
  WalletWasabi.Gui/Rpc/JsonRpcServer.cs
  WalletWasabi/Extensions/StreamExtensions.cs
  WalletWasabi/Helpers/NBitcoinHelpers.cs
  WalletWasabi/Tor/Http/TorHttpClient.cs
  WalletWasabi/Tor/Socks5/TorSocks5Client.cs
Labels: size/S

#4933 [Fluent] TileButton action style
  WalletWasabi.Fluent/Controls/TileButton.axaml
  WalletWasabi.Fluent/Styles/Themes/Base.xaml
  WalletWasabi.Fluent/Views/AddWallet/AddWalletPageView.axaml
Labels: size/S

#4930 [Fluent] Add full screen navigation target
  WalletWasabi.Fluent.Generators/NavigationMetaDataGenerator.cs
  WalletWasabi.Fluent/Controls/Dialog.xaml
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/DialogScreenViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationState.cs
  WalletWasabi.Fluent/ViewModels/Navigation/RoutableViewModel.cs
  WalletWasabi.Fluent/Views/MainView.axaml
Labels: size/M

#4928 Fluent/add wallet back in dialog
  WalletWasabi.Fluent/Styles/ActionButton.xaml
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/AddedWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/ConfirmRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/DetectedHardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/HardwareWalletOperations.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/WalletType.cs
  WalletWasabi/Helpers/ImportWalletHelper.cs
Labels: size/M

#4935 [Fluent] Search bar position
  WalletWasabi.Fluent/Views/Search/SearchPageView.axaml
Labels: size/XS

#4940 [Fluent] [Trivial] Remove unused using
  WalletWasabi.Fluent/Controls/TileButton.axaml.cs
  WalletWasabi.Fluent/Converters/NavBarIconConverter.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/RecoveryWordViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/DialogViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/HelpAndSupport/AboutViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationStack.cs
  WalletWasabi.Fluent/ViewModels/Settings/GeneralSettingsTabViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/SettingsPageViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/LoginView.axaml.cs
Labels: size/S

#4939 [Fluent] Fix some warnings
  WalletWasabi.Fluent.Generators/NavigationMetaDataGenerator.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/HardwareWalletOperations.cs
  WalletWasabi.Fluent/ViewModels/Search/SearchItemViewModel.cs
Labels: size/XS

#4941 [Fluent] Added Skip navigation mode
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationMode.cs
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationStack.cs
Labels: size/S

#4936 [Fluent] Add skip button
  WalletWasabi.Fluent/Controls/ContentArea.axaml
  WalletWasabi.Fluent/Controls/ContentArea.axaml.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/ConfirmRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/RoutableViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/AddWalletPageView.axaml
  WalletWasabi.Fluent/Views/AddWallet/Create/ConfirmRecoveryWordsView.axaml
Labels: size/M

#4945 [Fluent] Enable skip mnemonic confirmation if debugger attached.
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/ConfirmRecoveryWordsViewModel.cs
Labels: size/XS

#4903 Remove Environment.Exit duplication
  WalletWasabi.Fluent.Desktop/Program.cs
  WalletWasabi.Gui/Program.cs
  WalletWasabi/Services/Terminate/TerminateService.cs
Labels: size/L

#4925 [Trivial] Do not use Count/LongCount when Any can be used (CA1827)
  .editorconfig
  WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
Labels: size/XS

#4934 Remove unused code
  WalletWasabi/Extensions/StringExtensions.cs
Labels: size/M

#4950 Fix Continuous delivery for Fluent
  azure-pipelines-cd.yml
Labels: size/XS

#4917 Move CrashReport business to Fluent
  WalletWasabi.Fluent.Desktop/Program.cs
  WalletWasabi.Fluent/CrashReport/CrashReporter.cs
  WalletWasabi.Gui/CommandLine/CommandInterpreter.cs
  WalletWasabi.Gui/CommandLine/CrashReportCommand.cs
  WalletWasabi.Gui/CrashReport/CrashReportApp.xaml
  WalletWasabi.Gui/CrashReport/CrashReportApp.xaml.cs
  WalletWasabi.Gui/CrashReport/CrashReporter.cs
  WalletWasabi.Gui/CrashReport/ViewModels/CrashReportWindowViewModel.cs
  WalletWasabi.Gui/CrashReport/Views/CrashReportWindow.xaml
  WalletWasabi.Gui/CrashReport/Views/CrashReportWindow.xaml.cs
  WalletWasabi.Gui/Program.cs
  WalletWasabi.Tests/UnitTests/GUI/CommandInterpreterTest.cs
  WalletWasabi.Tests/UnitTests/SerializableExceptionTests.cs
  WalletWasabi.Tests/WalletWasabi.Tests.csproj
  WalletWasabi/Models/SerializableException.cs
Labels: size/XL

#4946 Remove ExtPubKey loader from KeyManager
  WalletWasabi.Gui/Tabs/WalletManager/HardwareWallets/ConnectHardwareWalletViewModel.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
Labels: size/M

#4944 Translate Probabilities to Anonymity Sets
  WalletWasabi.Tests/UnitTests/BlockchainAnalysis/CoinJoinAnonscoreTests.cs
  WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs
Labels: size/S

#4953 Add icon to wallet file
  WalletWasabi.Fluent/Converters/WalletTypeImageConverter.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/AddedWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/ConfirmRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/DetectedHardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/Helpers/ImportWalletHelper.cs
  WalletWasabi/Wallets/WalletType.cs
Labels: size/L

#4961 Remove unused file Native.cs
  WalletWasabi.Gui/CommandLine/Native.cs
Labels: size/M

#4964 Remove unused code (NBitcoinExtensions)
  WalletWasabi/Extensions/NBitcoinExtensions.cs
Labels: size/M

#4967 Remove unused code
  WalletWasabi/Blockchain/Mempool/MempoolService.cs
  WalletWasabi/Extensions/TextReaderExtensions.cs
Labels: size/S

#4968 Networkify Wallets
  WalletWasabi.Fluent.Desktop/Program.cs
  WalletWasabi.Gui/Program.cs
  WalletWasabi.Tests/RegressionTests/BuildTests.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi.Tests/UnitTests/WalletDirTests.cs
  WalletWasabi/Wallets/WalletDirectories.cs
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/M

#4965 Add trivial logs to catch null exception (backport)
  WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs
Labels: size/M

#4963 Fix null warnings for params that are null by default
  WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
  WalletWasabi.Tests/UnitTests/MockRpcClient.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
  WalletWasabi/Blockchain/Blocks/BlockNotifier.cs
  WalletWasabi/Blockchain/Keys/HdPubKey.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/Blockchain/TransactionBuilding/DestinationRequest.cs
  WalletWasabi/Blockchain/Transactions/SmartTransaction.cs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
  WalletWasabi/CoinJoin/Coordinator/Coordinator.cs
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
  WalletWasabi/Exceptions/InvalidTxException.cs
  WalletWasabi/Helpers/NBitcoinHelpers.cs
  WalletWasabi/Hwi/Models/HwiOption.cs
  WalletWasabi/Mono/Command.cs
  WalletWasabi/Mono/CommandOption.cs
  WalletWasabi/Mono/CommandSet.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/M

#4971 Remove unused code
  WalletWasabi/BitcoinCore/Configuration/CoreConfigTranslator.cs
Labels: size/S

#4949 Remove unused code
  WalletWasabi/Extensions/ListExtensions.cs
Labels: size/M

#4973 [Fluent] [Trivial] Use expression body for lambdas
  WalletWasabi.Fluent/Converters/MoneyConverters.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/ConfirmRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/DetectedHardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/TermsAndConditionsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/SettingsPageViewModel.cs
Labels: size/M

#4966 Remove useless parameter
  WalletWasabi/Blockchain/Mempool/MempoolService.cs
  WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs
Labels: size/XS

#4972 Remove unused parameter
  WalletWasabi.Gui/Program.cs
Labels: size/XS

#4976 Tor parallel bits - part 2: Improve performance by not allocating for every single byte of an HTT…
  WalletWasabi/Tor/Http/Constants.cs
  WalletWasabi/Tor/Http/Helpers/HttpMessageHelper.cs
Labels: size/XS
