Repository WalletWasabi/WalletWasabi, pull requests merged in 2020-07, with the labels that each got.

#3848 Update supported hw list.
  WalletWasabi.Gui/Tabs/WalletManager/HardwareWallets/ConnectHardwareWalletView.xaml
Labels: size/XS

#3811 BlockNotifierTests: Make `NotifyBlocksAsync` test more robust
  WalletWasabi.Tests/UnitTests/BlockNotifierTests.cs
Labels: size/M

#3852 Fixing the nuget problem on CI windows
  NuGet.Config
Labels: size/XS

#3855 Test wallet password if it was not tested
  WalletWasabi.Gui/Controls/WalletExplorer/ClosedWalletViewModel.cs
Labels: size/S

#3857 Organize crypto tests
  WalletWasabi.Tests/UnitTests/Crypto/BlindingTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/SchnorrBlindingSignatureTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/StringCipherTests.cs
  WalletWasabi.Tests/UnitTests/JsonConvertersTest/UnblindedSignatureTests.cs
Labels: size/L

#3856 Implement True/False guards
  WalletWasabi.Tests/UnitTests/GuardTests.cs
  WalletWasabi/Helpers/Guard.cs
Labels: size/M

#3861 Small refactoring
  WalletWasabi.Gui/Converters/PrivacyLevelValueConverter.cs
  WalletWasabi.Gui/Rpc/JsonRpcService.cs
  WalletWasabi.Tests/RegressionTests/Common.cs
  WalletWasabi/BitcoinCore/RpcParser.cs
  WalletWasabi/Mono/OptionSet.cs
Labels: size/S

#3853 Document HwiCommands.cs
  WalletWasabi/Hwi/Models/HwiCommands.cs
Labels: size/L

#3799 Modify .editorconfig
  .editorconfig
Labels: size/M

#3849 Send PSBT data through stdIn in HwiProcessBridge
  WalletWasabi.Tests/UnitTests/Hwi/DefaultResponseTests.cs
  WalletWasabi.Tests/UnitTests/Hwi/HwiProcessBridgeMock.cs
  WalletWasabi/Hwi/HwiClient.cs
  WalletWasabi/Hwi/Models/HwiOption.cs
  WalletWasabi/Hwi/ProcessBridge/HwiProcessBridge.cs
  WalletWasabi/Microservices/IProcessBridge.cs
  WalletWasabi/Microservices/ProcessBridge.cs
Labels: size/M

#3843 V4 client side API version update fix
  WalletWasabi/CoinJoin/Client/Clients/CoinJoinClientBase.cs
  WalletWasabi/Extensions/HttpResponseMessageExtensions.cs
  WalletWasabi/Services/WasabiSynchronizer.cs
Labels: size/M

#3599 show wallet balance in USD.
  WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/WalletViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletViewModelBase.cs
  WalletWasabi.Tests/UnitTests/NBitcoinTests.cs
  WalletWasabi/Extensions/NBitcoinExtensions.cs
Labels: size/M

#3865 reword the crash report message
  WalletWasabi.Gui/CrashReport/ViewModels/CrashReportWindowViewModel.cs
Labels: size/XS

#3868 Fix exception when opening About before initialization
  WalletWasabi.Gui/Tabs/AboutViewModel.cs
Labels: size/S

#3838 [Trivial] Add empty line before single-line comment
  WalletWasabi.Tests/UnitTests/HashChainTests.cs
Labels: size/XS

#3867 Fix FeePercentage when amount is 0
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
Labels: size/S

#3869 Refactor Randomness
  WalletWasabi.Tests/UnitTests/Crypto/BlindingTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/RandomTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/StringCipherTests.cs
  WalletWasabi/Crypto/Randomness/IWasabiRandom.cs
  WalletWasabi/Crypto/Randomness/IWasabiRandomExtensions.cs
  WalletWasabi/Crypto/Randomness/MockRandom.cs
  WalletWasabi/Crypto/Randomness/SecureRandom.cs
  WalletWasabi/Crypto/Randomness/UnsecureRandom.cs
  WalletWasabi/Crypto/StringCipher.cs
  WalletWasabi/Helpers/ByteArrayEqualityComparer.cs
  WalletWasabi/Helpers/HashHelpers.cs
Labels: size/L

#3876 Clear coinjoins
  WalletWasabi/CoinJoin/Coordinator/Coordinator.cs
Labels: size/S

#3833 Replace string.Empty by empty quotes
  WalletWasabi.Gui/CommandLine/PasswordFinder.cs
  WalletWasabi.Gui/Controls/ExtendedTextBox.cs
  WalletWasabi.Gui/Controls/LockScreen/PinLockScreenViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/CoinInfoTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionInfoTabViewModel.cs
  WalletWasabi.Gui/Converters/RpcStatusStringConverter.cs
  WalletWasabi.Gui/Rpc/JsonRpcRequestHandler.cs
  WalletWasabi.Gui/Tabs/SettingsViewModel.cs
  WalletWasabi.Gui/ViewModels/AddressViewModel.cs
  WalletWasabi.Tests/RpcTests.cs
  WalletWasabi.Tests/UnitTests/BitcoinCore/ConfigTranslatorTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/PayjoinTests.cs
  WalletWasabi/BitcoinCore/Configuration/CoreConfigLine.cs
  WalletWasabi/BitcoinCore/Configuration/NetworkTranslator.cs
  WalletWasabi/BitcoinCore/Configuration/Whitening/WhiteEntry.cs
  WalletWasabi/Helpers/Guard.cs
  WalletWasabi/Helpers/HttpMessageHelper.cs
  WalletWasabi/Models/ErrorDescriptor.cs
  WalletWasabi/Mono/OptionSet.cs
  WalletWasabi/Mono/StringCoda.cs
Labels: size/M

#3859 Transaction tab UI rework (Part 1/2)
  WalletWasabi.Gui/Controls/TransactionDetails/Models/AddressAmountTuple.cs
  WalletWasabi.Gui/Controls/TransactionDetails/ViewModels/TransactionDetailsViewModel.cs
  WalletWasabi.Gui/Controls/TransactionDetails/Views/TransactionDetails.xaml
  WalletWasabi.Gui/Controls/TransactionDetails/Views/TransactionDetails.xaml.cs
  WalletWasabi.Gui/Controls/WalletExplorer/CoinListView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionInfo.cs
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionInfoTabView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionInfoTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionViewerView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionViewerViewModel.cs
  WalletWasabi.Gui/Converters/MoneyBrushConverter.cs
  WalletWasabi.Gui/Converters/MoneyStringConverter.cs
  WalletWasabi.Gui/Styles/Styles.xaml
Labels: size/L

#3871 Transaction tab UI rework (Part 2/2)
  WalletWasabi.Gui/Controls/TransactionDetails/Models/AddressAmountTuple.cs
  WalletWasabi.Gui/Controls/TransactionDetails/ViewModels/TransactionDetailsViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionBroadcasterView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionBroadcasterViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionViewerView.xaml
Labels: size/L

#3880 Hide block height if the transaction is not confirmed
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionInfoTabView.xaml
Labels: size/XS

#3889 Fix NRE
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionBroadcasterViewModel.cs
Labels: size/XS

#3890 Add back Confirmed property
  WalletWasabi.Gui/Controls/TransactionDetails/ViewModels/TransactionDetailsViewModel.cs
Labels: size/XS

#3884 Implement getting random Scalar
  WalletWasabi.Tests/UnitTests/Crypto/RandomTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/ScalarTests.cs
  WalletWasabi/Crypto/Randomness/IWasabiRandom.cs
  WalletWasabi/Crypto/Randomness/IWasabiRandomExtensions.cs
  WalletWasabi/Crypto/Randomness/MockRandom.cs
Labels: size/L

#3874 Move HashHelpers under Crypto namespace
  WalletWasabi.Gui/Controls/LockScreen/PinLockScreenViewModel.cs
  WalletWasabi.Gui/Tabs/SettingsViewModel.cs
  WalletWasabi.Tests/UnitTests/Crypto/HashingTests.cs
  WalletWasabi/Crypto/HashHelpers.cs
  WalletWasabi/Helpers/ByteArrayEqualityComparer.cs
  WalletWasabi/Helpers/IoHelpers.cs
  WalletWasabi/Helpers/NBitcoinHelpers.cs
  WalletWasabi/Io/DigestableSafeMutexIoManager.cs
  WalletWasabi/Io/MutexIoManager.cs
Labels: size/M

#3881 Add empty quotes convention
  CONTRIBUTING.md
Labels: size/S

#3934 Change comment style
  WalletWasabi.Documentation/Guides/DeterministicBuildGuide.md
Labels: size/XS

#3970 Fixes/3909 tooltip stuck on screen
  WalletWasabi.Gui/Behaviors/PreventTooltipStuckBehavior.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerView.xaml
Labels: size/M

#3977 Update NBitcoin version
  WalletWasabi/WalletWasabi.csproj
Labels: size/XS

#3954 Add title in dialog for QR Code prompt to avoid NRE.
  WalletWasabi.Gui/Controls/QrCode.cs
Labels: size/XS

#3965 Make Legal docs unselectable and uncopyable
  WalletWasabi.Gui/Tabs/LegalDocumentsView.xaml
Labels: size/S

#3944 change customer to user support
  WalletWasabi.Gui/Icons/Icons.xaml
  WalletWasabi.Gui/Shell/Commands/HelpCommands.cs
  WalletWasabi.Gui/Shell/MainMenu/HelpMainMenuItems.cs
  WalletWasabi.Gui/Tabs/AboutView.xaml
  WalletWasabi.Gui/Tabs/AboutViewModel.cs
Labels: size/L

#4009 Fix crash reporter on OSX.
  WalletWasabi.Gui/Program.cs
Labels: size/XS

#4018 Implement GetInt and GetString for Randomness
  WalletWasabi.Tests/UnitTests/Crypto/RandomTests.cs
  WalletWasabi.Tests/UnitTests/IoTests.cs
  WalletWasabi.Tests/UnitTests/KeyManagementTests.cs
  WalletWasabi.Tests/UnitTests/PasswordTests.cs
  WalletWasabi/CoinJoin/Client/Clients/CoinJoinClientBase.cs
  WalletWasabi/Crypto/Randomness/InsecureRandom.cs
  WalletWasabi/Crypto/Randomness/MockRandom.cs
  WalletWasabi/Crypto/Randomness/RandomString.cs
  WalletWasabi/Crypto/Randomness/SecureRandom.cs
  WalletWasabi/Crypto/Randomness/UnsecureRandom.cs
  WalletWasabi/Crypto/Randomness/WasabiRandom.cs
  WalletWasabi/Crypto/StringCipher.cs
  WalletWasabi/Crypto/TokenGenerator.cs
  WalletWasabi/Helpers/Constants.cs
  WalletWasabi/Helpers/RandomString.cs
  WalletWasabi/TorSocks5/TorSocks5Client.cs
Labels: size/L

#4016 Add comments to explain anonset calculation.
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
Labels: size/S

#4012 tidy up the wallet info view layout.
  WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoViewModel.cs
Labels: size/M

#3972 Allow payjoin to pay fees from change output
  WalletWasabi.Tests/UnitTests/Clients/MockTorHttpClient.cs
  WalletWasabi.Tests/UnitTests/Clients/WasabiClientTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/PayjoinTests.cs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
  WalletWasabi/Extensions/ExceptionExtensions.cs
  WalletWasabi/Helpers/Constants.cs
  WalletWasabi/WebClients/PayJoin/IPayjoinClient.cs
  WalletWasabi/WebClients/PayJoin/PayjoinClient.cs
  WalletWasabi/WebClients/PayJoin/PayjoinClientParameters.cs
  WalletWasabi/WebClients/PayJoin/PayjoinReceiverException.cs
Labels: size/L

#4011 Fix recovery page layout
  WalletWasabi.Gui/Styles/Styles.xaml
  WalletWasabi.Gui/Tabs/WalletManager/RecoverWallets/RecoverWalletView.xaml
  WalletWasabi.Gui/Tabs/WalletManager/RecoverWallets/RecoverWalletViewModel.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
Labels: size/L

#3888 Remove unnecessary return
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionBroadcasterView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/TransactionBroadcasterViewModel.cs
Labels: size/S

#4023 Ignore payjoin server errors
  WalletWasabi.Tests/UnitTests/Transactions/PayjoinTests.cs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
  WalletWasabi/Extensions/ExceptionExtensions.cs
Labels: size/S

#4019 Implement GroupElement Encapsulation
  WalletWasabi.Tests/UnitTests/Crypto/GroupElementTests.cs
  WalletWasabi/Crypto/GroupElement.cs
Labels: size/L

#4038 Update NBitcoin
  WalletWasabi/WalletWasabi.csproj
Labels: size/XS

#4028 Update Backend docs with Tor upgrade
  WalletWasabi.Documentation/BackendDeployment.md
Labels: size/S

#4040 Add fall back mode to Ledger signing
  WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
Labels: size/S

#4047 Add mempoolreplacement and double spend test
  WalletWasabi.Documentation/BackendDeployment.md
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Tests/Helpers/TestNodeBuilder.cs
  WalletWasabi.Tests/UnitTests/BitcoinCore/RpcBasedTests.cs
  WalletWasabi.Tests/UnitTests/MockRpcClient.cs
  WalletWasabi/BitcoinCore/CoreNode.cs
  WalletWasabi/BitcoinCore/CoreNodeParams.cs
  WalletWasabi/BitcoinCore/IRPCClient.cs
  WalletWasabi/BitcoinCore/RpcClientBase.cs
Labels: size/M

#4033 Rename UI elements Observers -> Known by
  WalletWasabi.Gui/Controls/WalletExplorer/CoinInfoTabView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/CoinListView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabView.xaml
  WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
  WalletWasabi.Gui/Suggestions/SuggestLabelView.xaml
  WalletWasabi/Blockchain/Keys/KeyManager.cs
Labels: size/S

#4056 TorProcessManager & quotes.
  WalletWasabi/BitcoinCore/Processes/BitcoindRpcProcessBridge.cs
  WalletWasabi/TorSocks5/TorProcessManager.cs
  WalletWasabi/TorSocks5/TorSocks5Client.cs
Labels: size/S

#3988 Limit coin detail double-click behavior to a focus target control ins…
  WalletWasabi.Gui/Controls/WalletExplorer/CoinListView.xaml
Labels: size/S

#4063 TorProcessManager: Remove unused method.
  WalletWasabi/TorSocks5/TorProcessManager.cs
Labels: size/S

#4069 update to avalonia 0.9.12 for deterministic builds
  WalletWasabi.Gui/WalletWasabi.Gui.csproj
Labels: size/XS

#4066 Fix the update of confirmations on History Tab
  WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs
Labels: size/XS

#4058 Add Generator to GroupElement
  WalletWasabi.Tests/UnitTests/Crypto/GroupElementTests.cs
  WalletWasabi/Crypto/GroupElement.cs
Labels: size/L

#4072 Dump version to v1_1_12
  WalletWasabi.Backend/wwwroot/index.html
  WalletWasabi/Helpers/Constants.cs
  WalletWasabi/OnionSeeds/MainOnionSeeds.txt
Labels: size/XL

#4073 Improve deterministic build guide
  WalletWasabi.Documentation/Guides/DeterministicBuildGuide.md
Labels: size/XS

#4074 Update hash of SkiaSharp in nuget lock file
  WalletWasabi.Gui/packages.lock.json
  WalletWasabi.Tests/packages.lock.json
Labels: size/XS

#4075 Add Linux and macOs package hashes to packages.lock.json
  WalletWasabi.Gui/packages.lock.json
  WalletWasabi/packages.lock.json
Labels: size/XXL

#4076 Increase rpcworkqueue
  WalletWasabi.Documentation/BackendDeployment.md
Labels: size/XS

#4087 Packager fix for App icon path
  WalletWasabi.Gui/WalletWasabi.Gui.csproj
  WalletWasabi.Packager/Program.cs
Labels: size/S

#4093 Revert "Dump version to v1_1_12"
  WalletWasabi.Backend/wwwroot/index.html
  WalletWasabi/Helpers/Constants.cs
  WalletWasabi/OnionSeeds/MainOnionSeeds.txt
Labels: size/XL

#4088 Use GetOrCreate for cache
  WalletWasabi.Backend/Controllers/BlockchainController.cs
  WalletWasabi.Backend/WalletWasabi.Backend.csproj
  WalletWasabi.Backend/packages.lock.json
  WalletWasabi.Gui/packages.lock.json
  WalletWasabi.Packager/packages.lock.json
  WalletWasabi.Tests/UnitTests/MemoryTests.cs
  WalletWasabi.Tests/UnitTests/SmartBlockProviderTests.cs
  WalletWasabi.Tests/WalletWasabi.Tests.csproj
  WalletWasabi.Tests/packages.lock.json
  WalletWasabi/BitcoinCore/CachedRpcClient.cs
  WalletWasabi/BitcoinCore/IRPCClient.cs
  WalletWasabi/BitcoinCore/RpcClientBase.cs
  WalletWasabi/CoinJoin/Coordinator/Banning/UtxoReferee.cs
  WalletWasabi/Extensions/MemoryExtensions.cs
  WalletWasabi/Wallets/SmartBlockProvider.cs
Labels: size/L

#4095 Update BackendDeployment.md
  WalletWasabi.Documentation/BackendDeployment.md
Labels: size/XS

#4096 Add more tests to AtomicGetOrCreateAsync
  WalletWasabi.Tests/UnitTests/MemoryTests.cs
Labels: size/M

#4082 Fix bug
  WalletWasabi.Gui/Controls/TransactionDetails/ViewModels/TransactionDetailsViewModel.cs
Labels: size/XS
