Repository WalletWasabi/WalletWasabi, pull requests merged in 2021-01, with the labels that each got.

#4980 Tor parallel bits - part 4: Logger: Add missing overloads for message+exception.
  WalletWasabi/Logging/Logger.cs
Labels: size/S

#4975 Tor parallel bits - part 1
  WalletWasabi/Helpers/Guard.cs
  WalletWasabi/Tor/Socks5/Models/Bases/OctetSerializableBase.cs
  WalletWasabi/Tor/Socks5/Models/Fields/ByteArrayFields/MethodsField.cs
  WalletWasabi/Tor/Socks5/Models/Fields/ByteArrayFields/PasswdField.cs
  WalletWasabi/Tor/Socks5/Models/Fields/ByteArrayFields/PortField.cs
  WalletWasabi/Tor/Socks5/Models/Fields/ByteArrayFields/UNameField.cs
  WalletWasabi/Tor/Socks5/Models/Fields/OctetFields/AtypField.cs
  WalletWasabi/Tor/Socks5/Models/Fields/OctetFields/CmdField.cs
  WalletWasabi/Tor/Socks5/Models/Fields/OctetFields/NMethodsField.cs
  WalletWasabi/Tor/Socks5/Models/Fields/OctetFields/RepField.cs
  WalletWasabi/Tor/Socks5/Models/Fields/OctetFields/RsvField.cs
  WalletWasabi/Tor/Socks5/Models/Interfaces/IByteSerializable.cs
  WalletWasabi/Tor/Socks5/Models/Messages/TorSocks5Response.cs
  WalletWasabi/Tor/Socks5/TorSocks5Client.cs
Labels: size/L

#4960 Move PasswordFinder logic to Library
  WalletWasabi.Fluent.Desktop/Program.cs
  WalletWasabi.Gui/CommandLine/CommandInterpreter.cs
  WalletWasabi.Gui/CommandLine/PasswordFinder.cs
  WalletWasabi.Gui/CommandLine/PasswordFinderCommand.cs
  WalletWasabi.Gui/Program.cs
  WalletWasabi/Wallets/PasswordFinder.cs
Labels: size/L

#4985 Add thread ID to logging messages.
  WalletWasabi/Logging/Logger.cs
Labels: size/XS

#4974 [Fluent] [Trivial] Use pattern matching (not operator)
  WalletWasabi.Fluent.Generators/AutoNotifyGenerator.cs
  WalletWasabi.Fluent.Generators/NavigationMetaDataGenerator.cs
  WalletWasabi.Fluent.Generators/PropertyGenerator.cs
  WalletWasabi.Fluent.Generators/StaticViewLocatorGenerator.cs
Labels: size/XS

#4969 Fix some trivial null warnings
  WalletWasabi/BitcoinCore/Configuration/CoreConfig.cs
  WalletWasabi/BitcoinCore/Configuration/CoreConfigTranslator.cs
  WalletWasabi/BitcoinCore/Configuration/Whitening/WhiteEntry.cs
  WalletWasabi/BitcoinCore/CoreNode.cs
  WalletWasabi/Blockchain/BlockFilters/IndexBuilderService.cs
  WalletWasabi/Blockchain/Blocks/BlockNotifier.cs
Labels: size/M

#4970 [Trivial] Remove unused code
  WalletWasabi.Tests/UnitTests/MockRpcClient.cs
  WalletWasabi/Blockchain/Blocks/SmartHeaderChain.cs
Labels: size/M

#4977 Tor parallel bits - part 3: StreamExtensions: Fix "ReadBlockAsync" method and use it in TorSock…
  WalletWasabi/Extensions/StreamExtensions.cs
  WalletWasabi/Tor/Socks5/TorSocks5Client.cs
Labels: size/M

#4982 Tor parallel bits - part 5: Remove IHttpClient.SupportedSslProtocols.
  WalletWasabi/Tor/Http/ClearnetHttpClient.cs
  WalletWasabi/Tor/Http/IHttpClient.cs
  WalletWasabi/Tor/Socks5/TorSocks5Client.cs
Labels: size/XS

#4979 TorProcessManager: Report that Tor process has exited when waiting fo…
  WalletWasabi/Tor/TorProcessManager.cs
Labels: size/XS

#4864 Implement HWI checksums checking.
  WalletWasabi.Tests/UnitTests/Hwi/HwiBinaryHashesTests.cs
  WalletWasabi/Microservices/MicroserviceHelpers.cs
Labels: size/M

#4991 Use friendlier name
  WalletWasabi.Backend/wwwroot/index.html
Labels: size/XS

#4978 Transaction processor tests usings
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
Labels: size/L

#4990 Do not try to send again on user Cancel
  WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
Labels: size/XS

#4958 [Fluent] Login
  WalletWasabi.Fluent/Converters/WalletIconConverter.cs
  WalletWasabi.Fluent/Converters/WalletTypeImageConverter.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/AddedWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/LoginViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/ClosedWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/HardwareWallet/ClosedHardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/HardwareWallet/HardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WatchOnlyWallet/ClosedWatchOnlyWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WatchOnlyWallet/WatchOnlyWalletViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/AddedWalletPageView.axaml
  WalletWasabi.Fluent/Views/AddWallet/HardwareWallet/DetectedHardwareWalletView.axaml
  WalletWasabi.Fluent/Views/Dialogs/ShowErrorDialogView.axaml
  WalletWasabi.Fluent/Views/Login/LoginView.axaml
  WalletWasabi.Fluent/Views/Login/LoginView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/ClosedHardwareWalletView.axaml
  WalletWasabi.Fluent/Views/Wallets/ClosedWalletView.axaml
  WalletWasabi.Fluent/Views/Wallets/LoginView.axaml
  WalletWasabi/Wallets/Wallet.cs
Labels: size/L

#4993 [easy] Add missing "using"s and fix nullability issue.
  WalletWasabi.Tests/RegressionTests/BackendTests.cs
Labels: size/XS

#4943 [Fluent] Auto IsBusy
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/DetectedHardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/LoginViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/RoutableViewModel.cs
  WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/BroadcastTransactionViewModel.cs
Labels: size/M

#4992 [trivial] TorSocks5Request: Remove unused constructor.
  WalletWasabi/Tor/Socks5/Models/Messages/TorSocks5Request.cs
Labels: size/S

#4996 Correct capitalized mnemonic
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/RecoverWallets/RecoverWalletViewModel.cs
Labels: size/XS

#5002 Fix Trezor T initialization in Fluent
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/ConnectHardwareWalletViewModel.cs
Labels: size/M

#4983 Tor parallel bits - part 6: HttpRequestMessageExtensions modifications.
  WalletWasabi.Tests/UnitTests/Tor/Http/Extensions/HttpRequestMessageExtensionsTests.cs
  WalletWasabi/Tor/Http/Extensions/HttpRequestMessageExtensions.cs
  WalletWasabi/Tor/Http/TorHttpClient.cs
Labels: size/L

#4962 Remove CLI completely
  WalletWasabi.Fluent.Desktop/Program.cs
  WalletWasabi.Gui/CommandLine/CommandInterpreter.cs
  WalletWasabi.Gui/CommandLine/Daemon.cs
  WalletWasabi.Gui/CommandLine/MixerCommand.cs
  WalletWasabi.Gui/Program.cs
  WalletWasabi/Mono/ArgumentSource.cs
  WalletWasabi/Mono/Command.cs
  WalletWasabi/Mono/CommandOption.cs
  WalletWasabi/Mono/CommandOptionSet.cs
  WalletWasabi/Mono/CommandSet.cs
  WalletWasabi/Mono/HelpCommand.cs
  WalletWasabi/Mono/HelpOption.cs
  WalletWasabi/Mono/Option.cs
  WalletWasabi/Mono/OptionAction.cs
  WalletWasabi/Mono/OptionContext.cs
  WalletWasabi/Mono/OptionException.cs
  WalletWasabi/Mono/OptionSet.cs
  WalletWasabi/Mono/OptionValueCollection.cs
  WalletWasabi/Mono/OptionValueType.cs
  WalletWasabi/Mono/StringCoda.cs
Labels: size/XXL

#5005 [Fluent] Use DockPanel in login view and do not set height
  WalletWasabi.Fluent/Views/Login/LoginView.axaml
Labels: size/S

#4988 Tor parallel bits - part 8: TorSocks5Client & NetworkStream.DataAvailable
  WalletWasabi.Tests/IntegrationTests/TorTests.cs
  WalletWasabi/Extensions/StreamExtensions.cs
  WalletWasabi/Helpers/ByteArrayBuilder.cs
  WalletWasabi/Tor/Socks5/Models/Messages/TorSocks5Request.cs
  WalletWasabi/Tor/Socks5/TorSocks5Client.cs
Labels: size/L

#5010 Disable daemon mode of Core on Client side
  WalletWasabi/BitcoinCore/CoreNode.cs
Labels: size/XS

#5006 Use [NotNullWhen(true)] attribute
  WalletWasabi.Backend/Config.cs
  WalletWasabi.Fluent/ViewModels/Settings/BitcoinTabSettingsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/NetworkSettingsTabViewModel.cs
  WalletWasabi.Gui/Behaviors/PasteAddressOnClickBehavior.cs
  WalletWasabi.Gui/Config.cs
  WalletWasabi.Gui/Rpc/JsonRpcRequest.cs
  WalletWasabi.Gui/Rpc/JsonRpcService.cs
  WalletWasabi.Gui/Tabs/SettingsViewModel.cs
  WalletWasabi.Tests/UnitTests/Hwi/DefaultResponseTests.cs
  WalletWasabi.Tests/UnitTests/Userfacing/ParserTests.cs
  WalletWasabi/BitcoinCore/Configuration/CoreConfigTranslator.cs
  WalletWasabi/BitcoinCore/Configuration/Whitening/WhiteBind.cs
  WalletWasabi/BitcoinCore/Configuration/Whitening/WhiteEntry.cs
  WalletWasabi/BitcoinCore/Configuration/Whitening/WhiteList.cs
  WalletWasabi/BitcoinCore/CoreNode.cs
  WalletWasabi/Blockchain/Mempool/MempoolService.cs
  WalletWasabi/Blockchain/P2p/P2pBehavior.cs
  WalletWasabi/Blockchain/P2p/TrustedP2pBehavior.cs
  WalletWasabi/Blockchain/P2p/UntrustedP2pBehavior.cs
  WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs
  WalletWasabi/Blockchain/TransactionBuilding/PaymentIntent.cs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
  WalletWasabi/Crypto/UnblindedSignature.cs
  WalletWasabi/Helpers/JsonHelpers.cs
  WalletWasabi/Hwi/HwiClient.cs
  WalletWasabi/Hwi/Parsers/HwiParser.cs
  WalletWasabi/Io/SafeIoManager.cs
  WalletWasabi/JsonConverters/EndPointJsonConverter.cs
  WalletWasabi/Userfacing/AddressStringParser.cs
  WalletWasabi/Userfacing/EndPointParser.cs
  WalletWasabi/Wallets/PasswordFinder.cs
Labels: size/L

#5023 Remove unused code
  WalletWasabi/BitcoinCore/Configuration/Whitening/WhiteList.cs
  WalletWasabi/Blockchain/TransactionBuilding/PaymentIntent.cs
Labels: size/S

#5001 Set log level from cmdline
  WalletWasabi.Fluent.Desktop/Program.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Gui/Program.cs
  WalletWasabi/Logging/Logger.cs
Labels: size/M

#5029 Dispose stuff
  WalletWasabi.Tests/UnitTests/Wabisabi/CredentialTests.cs
  WalletWasabi.Tests/UnitTests/Wabisabi/SerializationTests.cs
Labels: size/S

#5030 Be consistent with capitalization
  WalletWasabi.Tests/UnitTests/Wabisabi/CredentialTests.cs
  WalletWasabi.Tests/UnitTests/Wabisabi/SerializationTests.cs
  WalletWasabi/Wabisabi/CredentialIssuer.cs
  WalletWasabi/Wabisabi/CredentialPool.cs
  WalletWasabi/Wabisabi/IssuanceRequest.cs
  WalletWasabi/Wabisabi/IssuanceValidationData.cs
  WalletWasabi/Wabisabi/RegistrationRequestMessage.cs
  WalletWasabi/Wabisabi/RegistrationResponseMessage.cs
  WalletWasabi/Wabisabi/RegistrationValidationData.cs
  WalletWasabi/Wabisabi/Serialization/GroupElementJsonConverter.cs
  WalletWasabi/Wabisabi/Serialization/ScalarJsonConverter.cs
  WalletWasabi/Wabisabi/WabiSabiClient.cs
  WalletWasabi/Wabisabi/WabiSabiErrorCode.cs
  WalletWasabi/Wabisabi/WabiSabiException.cs
Labels: size/M

#5031 Use correct punctuation for comments.
  WalletWasabi.Tests/UnitTests/Wabisabi/CredentialTests.cs
  WalletWasabi.Tests/UnitTests/Wabisabi/SerializationTests.cs
Labels: size/M

#4998 Remove ProcessInvoker class
  WalletWasabi.Tests/UnitTests/BitcoinCore/NodeBuildingTests.cs
  WalletWasabi.Tests/UnitTests/Hwi/DefaultResponseTests.cs
  WalletWasabi/BitcoinCore/CoreNode.cs
  WalletWasabi/Hwi/HwiClient.cs
  WalletWasabi/Hwi/ProcessBridge/HwiProcessBridge.cs
  WalletWasabi/Microservices/ProcessInvoker.cs
Labels: size/L

#5042 Cleanup
  WalletWasabi.Tests/UnitTests/Crypto/BlindingTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/CredentialIssuerKeyTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/MacTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/ProofSystemHelpers.cs
  WalletWasabi.Tests/UnitTests/Crypto/ProofSystemTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/TranscriptTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/KnowledgeOfDlogTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/KnowledgeOfRepTests.cs
  WalletWasabi.Tests/UnitTests/Wabisabi/CredentialTests.cs
  WalletWasabi.Tests/UnitTests/Wabisabi/SerializationTests.cs
  WalletWasabi/Crypto/CredentialIssuerParameters.cs
  WalletWasabi/Crypto/CredentialIssuerSecretKey.cs
  WalletWasabi/Crypto/Mac.cs
  WalletWasabi/Crypto/ZeroKnowledge/CredentialPresentation.cs
  WalletWasabi/Crypto/ZeroKnowledge/ProofSystem.cs
  WalletWasabi/JsonConverters/UnblindedSignatureJsonConverter.cs
  WalletWasabi/WabiSabi/Crypto/CredentialIssuer.cs
  WalletWasabi/WabiSabi/Crypto/CredentialPool.cs
  WalletWasabi/WabiSabi/Crypto/IssuanceRequest.cs
  WalletWasabi/WabiSabi/Crypto/IssuanceValidationData.cs
  WalletWasabi/WabiSabi/Crypto/RegistrationRequestMessage.cs
  WalletWasabi/WabiSabi/Crypto/RegistrationResponseMessage.cs
  WalletWasabi/WabiSabi/Crypto/RegistrationValidationData.cs
  WalletWasabi/WabiSabi/Crypto/Serialization/GroupElementJsonConverter.cs
  WalletWasabi/WabiSabi/Crypto/Serialization/ScalarJsonConverter.cs
  WalletWasabi/WabiSabi/Crypto/WabiSabiClient.cs
  WalletWasabi/WabiSabi/Crypto/WabiSabiErrorCode.cs
  WalletWasabi/WabiSabi/Crypto/WabiSabiException.cs
Labels: size/L

#5027 [Trivial][Fluent] Small refactorings
  WalletWasabi.Fluent.Generators/AutoNotifyGenerator.cs
  WalletWasabi.Fluent/Controls/Dialog.axaml.cs
  WalletWasabi.Fluent/Helpers/FileDialogHelper.cs
  WalletWasabi.Fluent/ViewModels/Navigation/RoutableViewModel.cs
Labels: size/M

#5034 Fix returned type of methods that return null
  WalletWasabi.Gui/Controls/ExtendedTextBox.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
  WalletWasabi.Gui/Converters/ErrorDescriptorToBorderColorConverter.cs
  WalletWasabi.Gui/Converters/ErrorSeverityColorConverter.cs
  WalletWasabi.Gui/Tabs/WalletManager/HardwareWallets/ConnectHardwareWalletViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletViewModel.cs
  WalletWasabi.Tests/UnitTests/BitcoinCore/ConfigTranslatorTests.cs
  WalletWasabi/BitcoinCore/Configuration/CoreConfigTranslator.cs
  WalletWasabi/BitcoinCore/CoreNode.cs
  WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
  WalletWasabi/CoinJoin/Coordinator/Banning/UtxoReferee.cs
  WalletWasabi/Extensions/RPCClientExtensions.cs
  WalletWasabi/Extensions/TextReaderExtensions.cs
  WalletWasabi/Helpers/ByteHelpers.cs
  WalletWasabi/JsonConverters/BitcoinEncryptedSecretNoECJsonConverter.cs
  WalletWasabi/JsonConverters/BlockCypherDateTimeOffsetJsonConverter.cs
  WalletWasabi/JsonConverters/ByteArrayJsonConverter.cs
  WalletWasabi/JsonConverters/HDFingerprintJsonConverter.cs
  WalletWasabi/JsonConverters/KeyPathJsonConverter.cs
  WalletWasabi/JsonConverters/RoundStateResponseJsonConverter.cs
  WalletWasabi/Legal/LegalDocuments.cs
  WalletWasabi/Tor/Http/Extensions/HttpResponseMessageExtensions.cs
  WalletWasabi/Tor/Http/Helpers/HttpMessageHelper.cs
  WalletWasabi/Wallets/P2pBlockProvider.cs
  WalletWasabi/WebClients/PayJoin/IPayjoinClient.cs
  WalletWasabi/WebClients/PayJoin/PayjoinClient.cs
Labels: size/M

#5038 [Fluent] Use expression body for accessors
  WalletWasabi.Fluent/Controls/ConcatenatingWrapPanel.cs
Labels: size/M

#4984 Fix some CA2000 warnings in tests.
  WalletWasabi.Tests/UnitTests/BitcoinCore/IndexBuilderServiceTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/RandomTests.cs
  WalletWasabi.Tests/UnitTests/MemoryTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/PayjoinTests.cs
Labels: size/M

#5043 [Fluent] Clear navigation stacks on close
  WalletWasabi.Fluent.Desktop/Program.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Gui/Global.cs
Labels: size/S

#5041 Tor parallel bits - part 7 [second attempt]: Add TorException base class and add a few comments.
  WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
  WalletWasabi.Tests/IntegrationTests/TorTests.cs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
  WalletWasabi/CoinJoin/Client/Clients/AliceClientBase.cs
  WalletWasabi/Services/WasabiSynchronizer.cs
  WalletWasabi/Tor/Http/TorHttpClient.cs
  WalletWasabi/Tor/Socks5/Exceptions/TorConnectCommandFailedException.cs
  WalletWasabi/Tor/Socks5/Exceptions/TorConnectionException.cs
  WalletWasabi/Tor/Socks5/Exceptions/TorException.cs
Labels: size/M

#5052 Legal bits - part 1: Remove legal check at Add Wallet
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
Labels: size/XS

#5053 Legal bits - part 2: Remove continue button
  WalletWasabi.Fluent/Views/AddWallet/LegalDocumentsView.axaml
Labels: size/XS

#5054 Legal bits - part 3: Remove Legaldocs from GUI and StatusBar
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Gui/Program.cs
  WalletWasabi.Gui/Shell/Commands/HelpCommands.cs
  WalletWasabi.Gui/Shell/MainMenu/HelpMainMenuItems.cs
  WalletWasabi.Gui/Tabs/LegalDocumentsView.xaml
  WalletWasabi.Gui/Tabs/LegalDocumentsView.xaml.cs
  WalletWasabi.Gui/Tabs/LegalDocumentsViewModel.cs
  WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
Labels: size/L

#5056 [WabiSabi Protocol] Implement Coordinator Boilerplate and Configurability
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Tests/UnitTests/Wabisabi/Backend/ConfigTests.cs
  WalletWasabi.Tests/UnitTests/Wabisabi/Backend/CoordinatorTests.cs
  WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
  WalletWasabi/WabiSabi/CoordinatorParameters.cs
  WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
Labels: size/L

#4987 [Fluent] Password finder
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/App.axaml
  WalletWasabi.Fluent/Assets/PasswordFinder/numbers.png
  WalletWasabi.Fluent/Assets/PasswordFinder/symbols.png
  WalletWasabi.Fluent/Controls/QuestionControl.axaml
  WalletWasabi.Fluent/Controls/QuestionControl.axaml.cs
  WalletWasabi.Fluent/Converters/EnumConverters.cs
  WalletWasabi.Fluent/Converters/EnumToFriendlyNameConverter.cs
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/HardwareWalletOperations.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/EnterPasswordViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/LoginViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/ContainsNumbersViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/ContainsSymbolsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/PasswordFinderIntroduceViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/PasswordFoundViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/PasswordNotFoundViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/SearchPasswordViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/SelectCharsetViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/HardwareWallet/DetectedHardwareWalletView.axaml
  WalletWasabi.Fluent/Views/Login/LoginView.axaml
  WalletWasabi.Fluent/Views/Login/PasswordFinder/ContainsNumbersView.axaml
  WalletWasabi.Fluent/Views/Login/PasswordFinder/ContainsNumbersView.axaml.cs
  WalletWasabi.Fluent/Views/Login/PasswordFinder/ContainsSymbolsView.axaml
  WalletWasabi.Fluent/Views/Login/PasswordFinder/ContainsSymbolsView.axaml.cs
  WalletWasabi.Fluent/Views/Login/PasswordFinder/PasswordFinderIntroduceView.axaml
  WalletWasabi.Fluent/Views/Login/PasswordFinder/PasswordFinderIntroduceView.axaml.cs
  WalletWasabi.Fluent/Views/Login/PasswordFinder/PasswordFoundView.axaml
  WalletWasabi.Fluent/Views/Login/PasswordFinder/PasswordFoundView.axaml.cs
  WalletWasabi.Fluent/Views/Login/PasswordFinder/PasswordNotFoundView.axaml
  WalletWasabi.Fluent/Views/Login/PasswordFinder/PasswordNotFoundView.axaml.cs
  WalletWasabi.Fluent/Views/Login/PasswordFinder/SearchPasswordView.axaml
  WalletWasabi.Fluent/Views/Login/PasswordFinder/SearchPasswordView.axaml.cs
  WalletWasabi.Fluent/Views/Login/PasswordFinder/SelectCharsetView.axaml
  WalletWasabi.Fluent/Views/Login/PasswordFinder/SelectCharsetView.axaml.cs
  WalletWasabi.Fluent/Views/Settings/GeneralSettingsTabView.axaml
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
  WalletWasabi/Wallets/PasswordFinder.cs
  WalletWasabi/Wallets/PasswordFinder/PasswordFinderCharset.cs
  WalletWasabi/Wallets/PasswordFinder/PasswordFinderHelper.cs
  WalletWasabi/Wallets/PasswordFinder/PasswordFinderOptions.cs
Labels: size/XL

#5062 ByteHelpers: Do not allow "null" value.
  WalletWasabi/Helpers/ByteHelpers.cs
Labels: size/XS

#5066 Wait longer
  WalletWasabi.Tests/UnitTests/Wabisabi/Backend/ConfigTests.cs
Labels: size/XS

#5009 Add bitcoind & Tor checksums verification
  WalletWasabi.Tests/UnitTests/BitcoinCore/BitcoindBinaryHashesTests.cs
  WalletWasabi.Tests/UnitTests/Tor/TorBinaryHashesTests.cs
  WalletWasabi/Microservices/Binaries/README.md
  WalletWasabi/Microservices/MicroserviceHelpers.cs
  WalletWasabi/Tor/TorSettings.cs
Labels: size/L

#5061 Wabisabi performance improvement
  WalletWasabi/Crypto/Groups/Generators.cs
  WalletWasabi/Crypto/Groups/GroupElement.cs
  WalletWasabi/Crypto/ScalarVector.cs
  WalletWasabi/Crypto/ZeroKnowledge/Credential.cs
  WalletWasabi/Crypto/ZeroKnowledge/ProofSystem.cs
  WalletWasabi/WabiSabi/Crypto/WabiSabiClient.cs
  WalletWasabi/WalletWasabi.csproj
Labels: size/M

#5060 Tor parallel bits - part 10: TorSocks5Client: Remove AssertConnectedAsync.
  WalletWasabi/Tor/Socks5/TorSocks5Client.cs
Labels: size/M

#5063 Crypto - Nits
  WalletWasabi.Tests/UnitTests/Crypto/GroupElements/GeneralTests.cs
  WalletWasabi/Crypto/SchnorrBlindingSignature.cs
Labels: size/M

#5070 ByteHelpers: ToHex(): Do not retun null
  WalletWasabi.Tests/UnitTests/Crypto/GroupElements/GeneralTests.cs
  WalletWasabi/Helpers/ByteHelpers.cs
Labels: size/S

#5069 CI: "--locked-mode" is ignored. Fix it.
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/packages.lock.json
  WalletWasabi.Gui/packages.lock.json
  WalletWasabi.Packager/packages.lock.json
  WalletWasabi/packages.lock.json
  azure-pipelines-linux.yml
  azure-pipelines-osx.yml
  azure-pipelines-windows.yml
Labels: size/M

#5068 Add productivity tips
  WalletWasabi.Documentation/WasabikaCodex.md
Labels: size/L

#5004 [Fluent] Wallet Navigation
  WalletWasabi.Fluent/Converters/NavBarItemsListBoxAlignmentConverter.cs
  WalletWasabi.Fluent/Converters/NegativeDoubleConverter.cs
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/ViewModels/AddWallet/AddedWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/LoginViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Actions/AdvancedWalletActionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Actions/CoinJoinWalletActionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Actions/ReceiveWalletActionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Actions/SendWalletActionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Actions/WalletActionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModelBase.cs
  WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
  WalletWasabi.Fluent/Views/Wallets/Actions/AdvancedWalletActionView.axaml
  WalletWasabi.Fluent/Views/Wallets/Actions/AdvancedWalletActionView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Actions/CoinJoinWalletActionView.axaml
  WalletWasabi.Fluent/Views/Wallets/Actions/CoinJoinWalletActionView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Actions/ReceiveWalletActionView.axaml
  WalletWasabi.Fluent/Views/Wallets/Actions/ReceiveWalletActionView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Actions/SendWalletActionView.axaml
  WalletWasabi.Fluent/Views/Wallets/Actions/SendWalletActionView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/ClosedHardwareWalletView.axaml
  WalletWasabi.Fluent/Views/Wallets/ClosedWalletView.axaml
Labels: size/XL

#5076 [Fluent] Update to Avalonia 0.10.0 release
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
Labels: size/L

#5075 Remove unused code
  WalletWasabi/Gma/QrCodeNet/Encoding/BitList.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/BitMatrix.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/BitMatrixBase.cs
  WalletWasabi/Tor/Socks5/Models/Bases/ByteArraySerializableBase.cs
Labels: size/M

#5077 Fix SelectMostPrivateIndependentlyOfCluster flaky test
  WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
Labels: size/XS

#5065 [WabiSabi Protocol] Implement UTXO banning
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/UtxoPrisonTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/UtxoPrisonWardenTests.cs
  WalletWasabi.Tests/UnitTests/Wabisabi/Backend/ConfigTests.cs
  WalletWasabi/JsonConverters/Timing/DefaultValueTimeSpanAttribute.cs
  WalletWasabi/JsonConverters/Timing/TimeSpanJsonConverter.cs
  WalletWasabi/WabiSabi/Backend/Banning/Inmate.cs
  WalletWasabi/WabiSabi/Backend/Banning/Prison.cs
  WalletWasabi/WabiSabi/Backend/Banning/Punishment.cs
  WalletWasabi/WabiSabi/Backend/Banning/Warden.cs
  WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
  WalletWasabi/WabiSabi/CoordinatorParameters.cs
  WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
Labels: size/XL

#5087 Set LastKnownChange as it was forgotten
  WalletWasabi/WabiSabi/Backend/Banning/Warden.cs
Labels: size/XS

#5064 Tor parallel bits - part 11: TorSocks5Client: Improve ConnectAsync method.
  WalletWasabi/Tor/Http/TorHttpClient.cs
  WalletWasabi/Tor/Socks5/TorSocks5Client.cs
Labels: size/M

#5089 Add LastKnownChange correct behavior test
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/UtxoPrisonWardenTests.cs
  WalletWasabi/WabiSabi/Backend/Banning/Warden.cs
Labels: size/S

#5090 Update .NET SDK link
  README.md
  WalletWasabi.Documentation/Guides/HowToDebug.md
Labels: size/XS

#5091 Document rpcthread setting
  WalletWasabi.Documentation/BackendDeployment.md
Labels: size/XS

#5093 Fix PrisonChangeTracking test.
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/UtxoPrisonTests.cs
Labels: size/S

#5097 Make tests exact
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/UtxoPrisonWardenTests.cs
  WalletWasabi.Tests/UnitTests/Wabisabi/Backend/ConfigTests.cs
  WalletWasabi/Bases/PeriodicRunner.cs
Labels: size/M

#5098 Make ID be a Guid
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/UtxoPrisonTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/UtxoPrisonWardenTests.cs
  WalletWasabi/WabiSabi/Backend/Banning/Inmate.cs
  WalletWasabi/WabiSabi/Backend/Banning/Prison.cs
Labels: size/M

#5096 [trivial] Guard: Fix nullability issues.
  WalletWasabi/Helpers/Guard.cs
Labels: size/XS

#5085 [Nit-fix] Adjust the spacing to be equal in ConnectHardwareWalletView.
  WalletWasabi.Fluent/Views/AddWallet/HardwareWallet/ConnectHardwareWalletView.axaml
Labels: size/XS

#5101 Fix some warnings
  WalletWasabi.Tests/UnitTests/BitcoinCore/ConfigTests.cs
  WalletWasabi.Tests/UnitTests/BitcoinCore/P2pBasedTests.cs
Labels: size/M

#5047 [Fluent] Hardware wallet (round 2)
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/ConnectHardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/DetectedHardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/HardwareWalletOperations.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/HardwareWallet/ConnectHardwareWalletView.axaml
  WalletWasabi/Crypto/Groups/Generators.cs
  WalletWasabi/Helpers/HardwareWalletOperationHelpers.cs
Labels: size/XL

#5099 Turn on RBF by default for every transaction
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
  WalletWasabi/Helpers/Constants.cs
Labels: size/XS

#5095 Remove IRelativeHttp client interface.
  WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
  WalletWasabi.Tests/UnitTests/Clients/MockTorHttpClient.cs
  WalletWasabi.Tests/UnitTests/Transactions/PayjoinTests.cs
  WalletWasabi/CoinJoin/Client/Clients/AliceClientBase.cs
  WalletWasabi/CoinJoin/Client/Clients/BobClient.cs
  WalletWasabi/CoinJoin/Client/Clients/SatoshiClient.cs
  WalletWasabi/Tor/Http/BackendHttpClient.cs
  WalletWasabi/Tor/Http/ClearnetHttpClient.cs
  WalletWasabi/Tor/Http/IHttpClient.cs
  WalletWasabi/Tor/Http/IRelativeHttpClient.cs
  WalletWasabi/Tor/Http/TorHttpClient.cs
  WalletWasabi/WebClients/PayJoin/PayjoinClient.cs
  WalletWasabi/WebClients/Wasabi/WasabiClient.cs
  WalletWasabi/WebClients/Wasabi/WasabiClientFactory.cs
Labels: size/L

#5105 [trivial] SyncInfo - typo & unused property
  WalletWasabi/Blockchain/BlockFilters/IndexBuilderService.cs
  WalletWasabi/Blockchain/BlockFilters/SyncInfo.cs
Labels: size/S
