Repository WalletWasabi/WalletWasabi, pull requests merged in 2021-10, with the labels that each got.

#6437 WabiSabi: Fix some nullability warnings
  WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/RegressionTests/DosTests.cs
  WalletWasabi/CoinJoin/Coordinator/Coordinator.cs
Labels: size/L

#6443 [WabiSabi] Random delays in input registration
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi/Crypto/StrobeProtocol/StrobeHasher.cs
  WalletWasabi/Extensions/TaskExtensions.cs
  WalletWasabi/Extensions/TimeSpanExtensions.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Crypto/RoundHasher.cs
  WalletWasabi/WabiSabi/Models/RoundState.cs
  WalletWasabi/WabiSabi/ProtocolContants.cs
Labels: size/M

#6460 [WabiSabi] Recheck inputs for spend status during connection confirmation
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/M

#6454 [WabiSabi] Schedule SignTransaction requests
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/S

#6461 WabiSabi: Minor stuff
  WalletWasabi.Tests/UnitTests/GuardTests.cs
  WalletWasabi/Tor/TorSettings.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/XS

#6462 `WabiSabi`: `ArenaBuilder` in tests.
  WalletWasabi.Tests/Helpers/ArenaBuilder.cs
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepConnectionConfirmationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputToBlameRoundTests.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/L

#6466 [WabiSabi] Fix edge case when there is not remaining time
  WalletWasabi/Extensions/TimeSpanExtensions.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/S

#6464 Update WasabiCompatibility.md - grammar fixes
  WalletWasabi.Documentation/WasabiCompatibility.md
Labels: size/XS

#6420 New! Send UX
  WalletWasabi.Fluent/Controls/PreviewItem.axaml
  WalletWasabi.Fluent/Helpers/EnumerableExtensions.cs
  WalletWasabi.Fluent/Helpers/TransactionHelpers.cs
  WalletWasabi.Fluent/Styles/Button.axaml
  WalletWasabi.Fluent/ViewModels/Dialogs/Authorization/AuthorizationDialogBase.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/Base/DialogViewModelBaseOfTResult.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/InsufficientBalanceDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/LineChartDemo/SendLineChartViewModel.cs
  WalletWasabi.Fluent/ViewModels/LineChartDemo/XYLineChartViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/RoutableViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/FeeChartViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/OptimisePrivacyViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendFeeViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionInfo.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Fluent/Views/Dialogs/InsufficientBalanceDialogView.axaml
  WalletWasabi.Fluent/Views/LineChartDemo/SendLineChartView.axaml
  WalletWasabi.Fluent/Views/LineChartDemo/SendLineChartView.axaml.cs
  WalletWasabi.Fluent/Views/LineChartDemo/XYLineChartView.axaml
  WalletWasabi.Fluent/Views/LineChartDemo/XYLineChartView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Send/SendFeeView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml
  WalletWasabi.Gui/Config.cs
Labels: size/XXL

#6457 [WabiSabi] Schedule Output Registration requests
  WalletWasabi/Crypto/Extensions.cs
  WalletWasabi/Extensions/TaskExtensions.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/DependencyGraphTaskScheduler.cs
Labels: size/M

#6468 `ArenaBuilder` & `Arena.IRPCClient`
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/AliceTimeoutTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/ConfirmConnectionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputToBlameRoundTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterOutputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RemoveInputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/SignTransactionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/RequestHandlerDisposeTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/ArenaRequestHandler.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
Labels: size/M

#6475 [Fluent] Fix labels during send
  WalletWasabi.Fluent/Helpers/TransactionHelpers.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/OptimisePrivacyViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionInfo.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
Labels: size/S

#6608 `ArenaRequestHandler`: Cleanup
  WalletWasabi.Backend/Controllers/WabiSabiController.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/AliceTimeoutTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/ConfirmConnectionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputToBlameRoundTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterOutputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RemoveInputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/SignTransactionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/RequestHandlerDisposeTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/ArenaRequestHandler.cs
  WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
Labels: size/M

#6600 [Trivial] Orange coin good - Green coin bad
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/Styles/Themes/Base.axaml
  WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
Labels: size/M

#6611 `InitConfigStartupTask`: Fix two warnings.
  WalletWasabi.Backend/InitConfigStartupTask.cs
  WalletWasabi.Fluent.Desktop/Program.cs
Labels: size/S

#6610 `WabiSabiCoordinator`: Clean up.
  WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
Labels: size/XS

#6604 [Trivial] Fix CodeFactor
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
  WalletWasabi.Tests/UnitTests/QrDecode/QrCodeDecodingTests.cs
Labels: size/S
