Repository WalletWasabi/WalletWasabi, pull requests merged in 2021-08, with the labels that each got.

#6127 Fix PrivacyContentControl crash on designer mode.
  WalletWasabi.Fluent/Controls/PrivacyContentControl.axaml.cs
Labels: size/XS

#6130 `RunningTasks`: Fix the implementation
  WalletWasabi.Tests/UnitTests/Nito/AsyncEx/RunningTasksTests.cs
  WalletWasabi/Nito/AsyncEx/AbandonedTasks.cs
  WalletWasabi/Nito/AsyncEx/RunningTasks.cs
Labels: size/M

#6104 [WabiSabi] Recheck that all the Txo are unspent
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepInputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/M

#6080 Start Wasabi on Linux distributions boot up
  WalletWasabi.Fluent/Helpers/LinuxStartupHelper.cs
  WalletWasabi.Fluent/Helpers/MacOsStartupHelper.cs
  WalletWasabi.Fluent/Helpers/StartupHelper.cs
  WalletWasabi.Fluent/Helpers/WindowsStartupHelper.cs
  WalletWasabi.Fluent/ViewModels/Settings/GeneralSettingsTabViewModel.cs
  WalletWasabi.Fluent/Views/Settings/GeneralSettingsTabView.axaml
  WalletWasabi.Tests/Helpers/LinuxStartupTestHelper.cs
  WalletWasabi.Tests/Helpers/WindowsStartupTestHelper.cs
  WalletWasabi.Tests/UnitTests/StartWasabiOnSystemStartupTests.cs
Labels: size/L

#6076 [WabiSabi] Remove credential retrieval from output registration
  WalletWasabi.Backend/Controllers/WabiSabiController.cs
  WalletWasabi.Tests/Helpers/ArenaRequestHandlerAdapter.cs
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterOutputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/SerializationTests.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/ArenaRequestHandler.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/IWabiSabiApiRequestHandler.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
  WalletWasabi/WabiSabi/Client/ArenaClient.cs
  WalletWasabi/WabiSabi/Client/BobClient.cs
  WalletWasabi/WabiSabi/Client/DependencyGraphTaskScheduler.cs
  WalletWasabi/WabiSabi/Client/SmartRequestNode.cs
  WalletWasabi/WabiSabi/Client/WabiSabiHttpApiClient.cs
  WalletWasabi/WabiSabi/Crypto/CredentialIssuer.cs
  WalletWasabi/WabiSabi/Crypto/CredentialRequesting/CredentialsRequest.cs
  WalletWasabi/WabiSabi/Crypto/WabiSabiClient.cs
  WalletWasabi/WabiSabi/Models/OutputRegistrationResponse.cs
Labels: size/L

#6131 Use ToList() to prevent the collection that is being iterated to get modified
  WalletWasabi/Blockchain/Keys/KeyManager.cs
Labels: size/XS

#6140 Clone collection to prevent it from being mutated
  WalletWasabi/Stores/IndexStore.cs
Labels: size/XS

#6002 [Fluent] OpenCVSharp for Webcamera and QRDecode
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/Models/WebcamQrReader.cs
  WalletWasabi.Fluent/QRCodeDecoder/Corner.cs
  WalletWasabi.Fluent/QRCodeDecoder/EncodingMode.cs
  WalletWasabi.Fluent/QRCodeDecoder/ErrorCorrection.cs
  WalletWasabi.Fluent/QRCodeDecoder/Finder.cs
  WalletWasabi.Fluent/QRCodeDecoder/QRDecoder.cs
  WalletWasabi.Fluent/QRCodeDecoder/ReedSolomon.cs
  WalletWasabi.Fluent/QRCodeDecoder/StaticTables.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/ShowQrCameraDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/Views/Dialogs/ShowQrCameraDialogView.axaml
  WalletWasabi.Fluent/Views/Dialogs/ShowQrCameraDialogView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
  WalletWasabi.Tests/UnitTests/QrCode/QrCodeDecodingTests.cs
  WalletWasabi.Tests/UnitTests/QrCode/QrTestResources/DoubleQRCode.png
  WalletWasabi.Tests/UnitTests/QrCode/QrTestResources/NotBitcoinAddress.jpg
  WalletWasabi.Tests/UnitTests/QrCode/QrTestResources/Payment_details_included.jpg
  WalletWasabi.Tests/UnitTests/QrCode/QrTestResources/QRBrick.jpg
  WalletWasabi.Tests/UnitTests/QrCode/QrTestResources/Random_address_starting_with_1.png
  WalletWasabi.Tests/UnitTests/QrCode/QrTestResources/Text_QR-code.png
  WalletWasabi.Tests/UnitTests/QrCode/QrTestResources/mouseOverQR.jpg
  WalletWasabi.Tests/UnitTests/QrDecode/QrCodeDecodingTests.cs
  WalletWasabi.Tests/UnitTests/QrDecode/QrResources/AddressTest1.png
  WalletWasabi.Tests/UnitTests/QrDecode/QrResources/AddressTest2.png
  WalletWasabi.Tests/UnitTests/QrDecode/QrResources/QRwithZebraBackground.png
  WalletWasabi.Tests/UnitTests/QrDecode/QrResources/QrByPhone.jpg
  WalletWasabi.Tests/UnitTests/QrDecode/QrResources/qr-embed-logos.png
  WalletWasabi.Tests/WalletWasabi.Tests.csproj
Labels: size/XXL

#6158 WabiSabi: Add tests for `MoneySatoshiJsonConverter`
  WalletWasabi.Tests/UnitTests/WabiSabi/SerializationTests.cs
  WalletWasabi/JsonConverters/Bitcoin/MoneySatoshiJsonConverter.cs
  WalletWasabi/WabiSabi/Models/Serialization/JsonSerializationOptions.cs
Labels: size/M

#6157 `WabiSabiHttpApiIntegrationTests`: Remove unused `GetStatefullMockRpc`
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
Labels: size/M

#6133 `IdempotentActionFilterImpl` & concurrency
  WalletWasabi.Backend/Filters/IdempotentActionFilterAttributeImpl.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
Labels: size/L

#6160 [WabiSabi] Trivial: fix typo in CredentialIssuer
  WalletWasabi/WabiSabi/Crypto/CredentialIssuer.cs
Labels: size/XS

#6150 [WabiSabi] Reduce ReissuanceAsync lock-contention
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Crypto/CredentialIssuer.cs
Labels: size/M

#6154 [WabiSabi] Reduce ReadyToSignAsync lock-contention
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/S

#6155 [WabiSabi] Simplify RegisterInputAsync
  WalletWasabi/WabiSabi/Backend/PostRequests/InputRegistrationHandler.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/L

#6058 Inhibit sleep/shutdown on Linux
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Tests/UnitTests/Crypto/RandomTests.cs
  WalletWasabi.Tests/UnitTests/Helpers/PowerSaving/LinuxInhibitorTests.cs
  WalletWasabi/Helpers/IPowerSavingInhibitorTask.cs
  WalletWasabi/Helpers/PowerSaving/LinuxInhibitorTask.cs
  WalletWasabi/Microservices/ProcessAsync.cs
  WalletWasabi/Services/SystemAwakeChecker.cs
  WalletWasabi/Tor/TorProcessManager.cs
Labels: size/L

#6151 [WabiSabi] Reduce ConfirmConnection lock-contention
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/M

#6167 AbsoluteExpirationRelativeToNowExpiresCorrectlyAsync: Switch Task.Del…
  WalletWasabi.Tests/UnitTests/MemoryTests.cs
Labels: size/XS

#6161 [WabiSabi] Throw if already signalled
  WalletWasabi/WabiSabi/Backend/Banning/Prison.cs
  WalletWasabi/WabiSabi/Backend/Models/WabiSabiProtocolErrorCode.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Rounds/RoundParameters.cs
Labels: size/S

#6171 [Fluent] Hide QR scan button on unsupported OS
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Labels: size/XS

#6162 [WabiSabi] Throw if Alice already confirmed connection
  WalletWasabi/WabiSabi/Backend/Models/WabiSabiProtocolErrorCode.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/S

#6170 [Fluent] Tagsbox consistent margin
  WalletWasabi.Fluent/Controls/TagsBox.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml
Labels: size/S

#6169 [Fluent] Allow enter a recovery word twice
  WalletWasabi.Fluent/Views/AddWallet/RecoverWalletView.axaml
Labels: size/XS

#6149 [Fluent] Fix NavBar collapse bug
  WalletWasabi.Fluent/Styles/SplitView.axaml
Labels: size/XS

#6124 [Fluent] Send - suggested labels
  WalletWasabi.Fluent/Controls/TagsBox.axaml
  WalletWasabi.Fluent/Controls/TagsBox.axaml.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Labels/SuggestionLabelViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Labels/SuggestionLabelsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Labels: size/L

#6183 [Fluent] Add cancel button to Send preview screen
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
Labels: size/XS

#6190 [Fluent] Validation error message fixes
  WalletWasabi.Fluent/Styles/TextBox.axaml
Labels: size/XS

#6189 [Fluent] Privacy Control - increase smoothness
  WalletWasabi.Fluent/Views/Wallets/Send/PrivacyControlView.axaml
Labels: size/S

#6188 [Fluent] OptimisePrivacyScreen warning message fixes
  WalletWasabi.Fluent/Views/Wallets/Send/OptimisePrivacyView.axaml
Labels: size/XS

#6187 [Fluent] fix `Broadcast` button visibility
  WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
Labels: size/XS

#6186 [Fluent] HW auth dialog - remove back button
  WalletWasabi.Fluent/ViewModels/Dialogs/Authorization/HardwareWalletAuthDialogViewModel.cs
Labels: size/XS

#6185 [Fleunt] ContentArea - Remove `IsCancel` from cancel button
  WalletWasabi.Fluent/Controls/ContentArea.axaml
Labels: size/XS

#6195 [Fluent] Validation error message fixes 2
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml
Labels: size/XS

#6192 [Fluent] Privacy Control - skip screen if there is only one cluster
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
Labels: size/S

#6198 [Fluent] Fix navigation issue after `InsufficientBalanceException`
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
Labels: size/S

#6200 [Fluent] Update to Avalonia version 0.10.7
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/Converters/BoolConverters.cs
  WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
Labels: size/L

#6199 [Fluent] Fee Slider - fix invalid feerate
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendFeeViewModel.cs
Labels: size/XS

#6121 Initial Wabisabi integration
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/RoundStatusTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletPieChartTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/RoundStatus/RoundStatusLargeTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/RoundStatus/RoundStatusLargeTileView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/RoundStatus/RoundStatusMediumTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/RoundStatus/RoundStatusMediumTileView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/RoundStatus/RoundStatusWideTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/RoundStatus/RoundStatusWideTileView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/RoundStatusTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/RoundStatusTileView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletPieChart/WalletPieChartLargeTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletPieChart/WalletPieChartMediumTileView.axaml
Labels: size/XL

#6159 Inhibit sleep on Windows
  WalletWasabi/Helpers/PowerSaving/WindowsPowerAvailabilityTask.cs
  WalletWasabi/Services/SystemAwakeChecker.cs
Labels: size/L

#6174 [WabiSabi] Handle Input registration failures
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/Participant.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/M

#5522 [Fluent] Source generators update
  WalletWasabi.Fluent.Generators/AutoNotifyGenerator.cs
  WalletWasabi.Fluent.Generators/NavigationMetaDataGenerator.cs
  WalletWasabi.Fluent.Generators/PropertyGenerator.cs
  WalletWasabi.Fluent.Generators/StaticViewLocatorGenerator.cs
  WalletWasabi.Fluent.Generators/WalletWasabi.Fluent.Generators.csproj
  WalletWasabi.Fluent.Generators/packages.lock.json
Labels: size/XL

#5973 [Fluent] Filter synchronization on loading screen
  WalletWasabi.Fluent/ViewModels/Wallets/LoadingViewModel.cs
Labels: size/L

#6255 [WabiSabi] Rename Task<CredentialResponse> HandleRequest{,Async}
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Crypto/CredentialIssuer.cs
Labels: size/M

#6243 [Fluent] Fix add hw wallet
  WalletWasabi.Fluent/ViewModels/AddWallet/AddedWalletPageViewModel.cs
Labels: size/S

#6235 [Fluent] Recover Wallet - layout fixes
  WalletWasabi.Fluent/Views/AddWallet/RecoverWalletView.axaml
Labels: size/M

#6253 [WabiSabi] Properly authenticate ReadyToSign requests by making AliceId secret again
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputSuccessTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RemoveInputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/SerializationTests.cs
  WalletWasabi/WabiSabi/Backend/Models/Alice.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Client/AliceClient.cs
  WalletWasabi/WabiSabi/Client/ArenaClient.cs
  WalletWasabi/WabiSabi/Models/ConnectionConfirmationRequest.cs
  WalletWasabi/WabiSabi/Models/InputRegistrationResponse.cs
  WalletWasabi/WabiSabi/Models/InputsRemovalRequest.cs
  WalletWasabi/WabiSabi/Models/ReadyToSignRequestRequest.cs
Labels: size/L

#6254 [WabiSabi] Unregister Alice
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/AliceTimeoutTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
  WalletWasabi/WabiSabi/Client/AliceClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/L

#6262 fix auto complete box appearing when it shouldnt on osx.
  WalletWasabi.Fluent/Controls/TagsBox.axaml.cs
Labels: size/XS, ww2 testing

#6245 [Fluent] [LineChart] Auto label alignment
  WalletWasabi.Fluent/Controls/LineChart.Properties.cs
  WalletWasabi.Fluent/Controls/LineChart.cs
  WalletWasabi.Fluent/Styles/BalanceLineChart.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/SendFeeView.axaml
Labels: size/L

#6233 [Fluent] Wallet Balance Chart fixes
  WalletWasabi.Fluent/Helpers/EnumerableExtensions.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletBalanceChartTileViewModel.cs
Labels: size/M

#6196 [Fluent] fix popup
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PocketViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Send/PrivacyControlView.axaml
Labels: size/L

#6273 [WabiSabi][RPC] Remove `enqueue` and `dequeue` rpc methods
  WalletWasabi.Gui/Rpc/WasabiJsonRpcService.cs
Labels: size/S

#6268 Fix DiffTooSmallToBlameAsync test
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
Labels: size/S

#6275 Privatize StartRoundAsync
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/XS

#6271 add an appviewmodel and implementation to prevent shutdown.
  WalletWasabi.Fluent/App.axaml
  WalletWasabi.Fluent/App.axaml.cs
  WalletWasabi.Fluent/Providers/ICanShutdownProvider.cs
  WalletWasabi.Fluent/ViewModels/ApplicationViewModel.cs
Labels: size/M

#6278 Revert "Privatize StartRoundAsync"
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/XS
