Repository WalletWasabi/WalletWasabi, pull requests merged in 2021-12, with the labels that each got.

#6636 Fix ArgumentNullException exception when cancelling importing a wallet
  WalletWasabi.Fluent/Helpers/FileDialogHelper.cs
Labels: size/XS

#6787 [trivial] Fix test comment.
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/TransactionSignaturesRequestTests.cs
Labels: size/XS

#6788 Switch 'FeeRateJsonConverter' from 'JsonConverter' to 'JsonConverter<T>'
  WalletWasabi/JsonConverters/Bitcoin/FeeRateJsonConverter.cs
Labels: size/S

#6769 [VDG] [Fluent] Dialog screen size optimization - width and height thresholds
  WalletWasabi.Fluent/Controls/Dialog.axaml
  WalletWasabi.Fluent/Controls/Dialog.axaml.cs
  WalletWasabi.Fluent/Views/MainView.axaml
Labels: size/M

#6790 Switch 'MoneyBtcJsonConverter' from 'JsonConverter' to 'JsonConverter<T>'
  WalletWasabi/JsonConverters/Bitcoin/FeeRateJsonConverter.cs
  WalletWasabi/JsonConverters/Bitcoin/MoneyBtcJsonConverter.cs
Labels: size/S

#6794 Switch BitcoinEncryptedSecretNoECJsonConverter from 'JsonConverter' to 'JsonConverter<T>'
  WalletWasabi/JsonConverters/BitcoinEncryptedSecretNoECJsonConverter.cs
Labels: size/S

#6793 Switch BitcoinAddressJsonConverter from 'JsonConverter' to 'JsonConverter<T>'
  WalletWasabi/JsonConverters/BitcoinAddressJsonConverter.cs
Labels: size/S

#6798 Set Width and Height for PasswordAuthDialog
  WalletWasabi.Fluent/Views/Dialogs/Authorization/PasswordAuthDialogView.axaml
Labels: size/XS

#6792 Switch 'ScriptJsonConverter' from 'JsonConverter' to 'JsonConverter<T>'
  WalletWasabi/JsonConverters/Bitcoin/ScriptJsonConverter.cs
Labels: size/S

#6782 [Fluent] Monospace Fixes Redux
  WalletWasabi.Fluent/Assets/Fonts/CascadiaCode.ttf
  WalletWasabi.Fluent/Assets/Fonts/RobotoMono-Regular.ttf
  WalletWasabi.Fluent/Styles/Styles.axaml
  WalletWasabi.Fluent/Styles/TextBox.axaml
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletInfoView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/CoinJoinDetailsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/TransactionDetailsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalance/WalletBalanceMediumTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveAddressView.axaml
  WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveAddressesView.axaml
  WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml
Labels: size/L

#6617 [VDG] Custom transaction fee
  WalletWasabi.Fluent/Behaviors/NumberBoxBehavior.cs
  WalletWasabi.Fluent/UiConfig.cs
  WalletWasabi.Fluent/ViewModels/Settings/GeneralSettingsTabViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/AdvancedSendOptionsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionInfo.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Fluent/Views/Settings/GeneralSettingsTabView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/AdvancedSendOptionsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/AdvancedSendOptionsView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml
Labels: size/L

#6724 Event sourcing event repository
  WalletWasabi.Tests/UnitTests/EventSourcing/InMemoryEventRepositoryTests.cs
  WalletWasabi.Tests/UnitTests/EventSourcing/TestDomain/TestInMemoryEventRepository.cs
  WalletWasabi.Tests/UnitTests/EventSourcing/TestDomain/TestWrappedEvent.cs
  WalletWasabi/EventSourcing/AggregateEvents.cs
  WalletWasabi/EventSourcing/AggregateTypeIds.cs
  WalletWasabi/EventSourcing/InMemoryEventRepository.cs
  WalletWasabi/EventSourcing/WrappedEvent.cs
  WalletWasabi/Exceptions/OptimisticConcurrencyException.cs
  WalletWasabi/Exceptions/TransientException.cs
  WalletWasabi/Interfaces/EventSourcing/IEventRepository.cs
Labels: size/XL

#6768 [VDG] Use the last used conf target by default
  WalletWasabi.Fluent/Config.cs
  WalletWasabi.Fluent/UiConfig.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/AdvancedSendOptionsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/FeeChartViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendFeeViewModel.cs
Labels: size/M

#6809 Use `async` code Packager
  WalletWasabi.Packager/Program.cs
Labels: size/M

#6758 Privacy Issue - Resolve Workflow
  NuGet.Config
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/Behaviors/BindableFlyoutOpenBehavior.cs
  WalletWasabi.Fluent/Behaviors/ListBoxPreviewBehavior.cs
  WalletWasabi.Fluent/Behaviors/ShowFlyoutOnPointerOverBehavior.cs
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/Styles/Themes/Base.axaml
  WalletWasabi.Fluent/ViewModels/Wallets/Send/ChangeAvoidanceSuggestionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/OptimisePrivacyViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyOptimisationLevel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacySuggestionControlViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacySuggestionsFlyoutViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SuggestionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionSummaryViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Send/OptimisePrivacyView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/OptimisePrivacyView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Send/PrivacySuggestionControl.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionSummary.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionSummary.axaml.cs
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
Labels: size/XXL

#6799 [Fluent] Rearranging "Unused Receive Addresses" view
  WalletWasabi.Fluent/Behaviors/DataBoxItemDetailsAdorner.cs
  WalletWasabi.Fluent/Behaviors/HistoryItemDetailsBehavior.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
  WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveAddressesView.axaml
Labels: size/L

#6789 [test] Idempotency: Add more tests
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/ReadyToSignRequestRequestTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Crypto/CredentialRequesting/RealCredentialsRequestTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Crypto/CredentialRequesting/ZeroCredentialsRequestTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Crypto/OwnershipProofTests.cs
  WalletWasabi/Crypto/OwnershipIdentifier.cs
  WalletWasabi/Crypto/OwnershipProof.cs
  WalletWasabi/Extensions/ImmutableValueSequenceExtensions.cs
  WalletWasabi/Models/ImmutableValueSequence.cs
  WalletWasabi/WabiSabi/Crypto/CredentialRequesting/ZeroCredentialsRequest.cs
  WalletWasabi/WabiSabi/Crypto/IssuanceRequest.cs
  WalletWasabi/WabiSabi/Models/ReadyToSignRequestRequest.cs
  WalletWasabi/WabiSabi/Models/ReissueCredentialRequest.cs
Labels: size/L

#6830 Fix Packager
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
Labels: size/XS

#6836 Update NuGet packages
  WalletWasabi.Fluent.Generators/WalletWasabi.Fluent.Generators.csproj
  WalletWasabi.Fluent.Generators/packages.lock.json
  WalletWasabi.Tests/WalletWasabi.Tests.csproj
Labels: size/S

#6720 Throw OpCancelledExc instead of InvalidOpExc in WalletManager.cs
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/S

#6833 [VDG] [Fluent] Fix keyboard shortcuts in ContentArea
  WalletWasabi.Fluent/Behaviors/ButtonExecuteCommandOnKeyDownBehavior.cs
  WalletWasabi.Fluent/Controls/ContentArea.axaml
  WalletWasabi.Fluent/Views/AddWallet/Create/ConfirmRecoveryWordsView.axaml
  WalletWasabi.Fluent/Views/AddWallet/TermsAndConditionsView.axaml
  WalletWasabi.Fluent/Views/Dialogs/AdvancedRecoveryOptionsView.axaml
  WalletWasabi.Fluent/Views/Dialogs/Authorization/HardwareWalletAuthDialogView.axaml
  WalletWasabi.Fluent/Views/Dialogs/Authorization/PasswordAuthDialogView.axaml
  WalletWasabi.Fluent/Views/Dialogs/CreatePasswordDialogView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/SendFeeView.axaml
Labels: size/L

#6847 [Trivial] Fix typo
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Crypto/CredentialRequesting/ZeroCredentialsRequestTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Crypto/OwnershipProofTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/ConnectionConfirmationRequestTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/OutputRegistrationRequestTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/TransactionSignaturesRequestTests.cs
Labels: size/M

#6846 [Trivial] Fix CodeFactor issues
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/Versions/QRCodeVersion.cs
Labels: size/S

#6837 [VDG] [Fluent] Stretch balance chart tile in normal and wide layout
  WalletWasabi.Fluent/Helpers/TileHelper.cs
  WalletWasabi.Fluent/Views/Wallets/Home/WalletTiles.axaml
  WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
Labels: size/S

#6519 [Fluent] Adjust transaction fee if overpayment detected
  WalletWasabi.Fluent/Helpers/TransactionFeeHelper.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/FeeChartViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendFeeViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionInfo.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
  WalletWasabi/Exceptions/TransactionFeeOverpaymentException.cs
Labels: size/L

#6854 Fix TagControl's text wrapping
  WalletWasabi.Fluent/Controls/TagControl.axaml
  WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveAddressesView.axaml
Labels: size/XS

#6823 [VDG] Label entry dialog v2
  WalletWasabi.Fluent/Helpers/TransactionHelpers.cs
  WalletWasabi.Fluent/Styles/Themes/Base.axaml
  WalletWasabi.Fluent/ViewModels/Dialogs/LabelEntryDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/RoutableViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionInfo.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Fluent/Views/Dialogs/Authorization/PasswordAuthDialogView.axaml
  WalletWasabi.Fluent/Views/Dialogs/LabelEntryDialogView.axaml
  WalletWasabi.Fluent/Views/Dialogs/LabelEntryDialogView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionSummary.axaml
Labels: size/L

#6855 [VDG] Flash CJ row in transaction history when new happened
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
Labels: size/S

#6810 Packager: BUILDINFO.json
  WalletWasabi.Packager/BuildInfo.cs
  WalletWasabi.Packager/Program.cs
Labels: size/M

#6861 Add try/catch to Arena step methods
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/LoggerTools.cs
Labels: size/L

#6869 Show unconfirmed CJ in history list
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinsHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
Labels: size/S

#6835 Event sourcing: Formatting
  WalletWasabi.Tests/UnitTests/EventSourcing/InMemoryEventRepositoryTests.cs
  WalletWasabi.Tests/UnitTests/EventSourcing/TestDomain/TestInMemoryEventRepository.cs
  WalletWasabi/EventSourcing/InMemoryEventRepository.cs
  WalletWasabi/EventSourcing/WrappedEvent.cs
  WalletWasabi/Interfaces/EventSourcing/IEventRepository.cs
Labels: size/XL

#6838 [VDG] [Fluent] Use chart for privacy control tile on medium size layout
  WalletWasabi.Fluent/Styles/Separator.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyControlTileView.axaml
Labels: size/M

#6848 Replace `IsNullOrEmpty()` with `IsNullOrWhiteSpace()`
  WalletWasabi/Hwi/Parsers/HwiParser.cs
Labels: size/XS

#6843 Remove unnecessary null check
  WalletWasabi.Fluent/Behaviors/BindableFlyoutOpenBehavior.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
Labels: size/XS

#6880 Empty wallet home screen
  WalletWasabi.Fluent/Controls/HistoryPlaceholderPanel.axaml
  WalletWasabi.Fluent/Controls/HistoryPlaceholderPanel.axaml.cs
  WalletWasabi.Fluent/Helpers/TileHelper.cs
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/Styles/BalanceLineChart.axaml
  WalletWasabi.Fluent/Styles/Styles.axaml
  WalletWasabi.Fluent/Styles/Themes/Base.axaml
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/LineChartPlaceholderViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletBalanceChartTileViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTablePlaceholder.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTablePlaceholder.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyControlTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceChart/WalletBalanceChartLargeTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceChart/WalletBalanceChartMediumTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceChart/WalletBalanceChartWideTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/WalletTilesPlaceholder.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/WalletTilesPlaceholder.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
Labels: size/XXL

#6875 Fix IndexBuilder exception when Reorging
  WalletWasabi/Blockchain/BlockFilters/IndexBuilderService.cs
Labels: size/XS

#6887 Fix icons on ios
  WalletWasabi.Fluent/App.axaml
  WalletWasabi.Fluent/Assets/WasabiLogo.ico
  WalletWasabi.Fluent/Assets/WasabiLogo_white.ico
  WalletWasabi.Fluent/ViewModels/ApplicationViewModel.cs
  WalletWasabi.Packager/Content/Osx/App/Contents/Resources/WasabiLogo.icns
  WalletWasabi.Packager/Content/Osx/WasabiLogo.icns
Labels: size/S

#6892 fix ios installer background
  WalletWasabi.Packager/Content/Osx/Dmg/.DS_Store.dat
  WalletWasabi.Packager/Content/Osx/Dmg/.background/Logo_with_text_small.png
Labels: size/XS

#6896 TorHttpPool: Improve logging.
  WalletWasabi/Tor/Socks5/Pool/TorHttpPool.cs
  WalletWasabi/Tor/Socks5/TorTcpConnection.cs
Labels: size/S

#6897 Logger: Change format from `class:method` to `class.method` so that one can f…
  WalletWasabi/Logging/Logger.cs
Labels: size/XS

#6876 Polish Resolve Transaction Issues Workflow
  WalletWasabi.Fluent/Models/PrivacySuggestionBenefit.cs
  WalletWasabi.Fluent/Styles/Themes/BaseDark.axaml
  WalletWasabi.Fluent/Styles/Themes/BaseLight.axaml
  WalletWasabi.Fluent/ViewModels/Wallets/Send/ChangeAvoidanceSuggestionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PocketSuggestionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyOptimisationLevel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacySuggestionsFlyoutViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SuggestionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionInfo.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionSummaryViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Send/ChangeAvoidanceSuggestionControl.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/ChangeAvoidanceSuggestionControl.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Send/PocketSuggestionControl.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/PocketSuggestionControl.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Send/PrivacySuggestionControl.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionSummary.axaml
Labels: size/L

#6903 [Fluent] Try fixing missing privacy percent values in some systems
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
Labels: size/XS

#6901 [Trivial] Remove GlobalUsings for GUI project
  WalletWasabi.Gui/GlobalUsings.cs
Labels: size/XS

#6907 Quick-fix for #6906
  WalletWasabi.Fluent/ViewModels/ApplicationViewModel.cs
Labels: size/XS

#6904 Fix 0 privacy percentage issue
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
Labels: size/XS

#6935 Remove unnecessary condition
  WalletWasabi/Crypto/UnblindedSignature.cs
Labels: size/XS

#6871 Add FeesDifferentThanExpected test to TransactionFactoryTests
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
  WalletWasabi/Blockchain/TransactionBuilding/PaymentIntent.cs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
Labels: size/M

#6806 Switch ByteArrayJsonConverter from 'JsonConverter' to 'JsonConverter<T>'
  WalletWasabi.Tests/UnitTests/JsonConverters/ByteArrayJsonConverterTests.cs
  WalletWasabi/JsonConverters/ByteArrayJsonConverter.cs
Labels: size/M

#6909 Remove feerate different sanity check
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
Labels: size/M

#6948 [Trivial] Update LICENSE.md
  LICENSE.md
Labels: size/XS

#6924 trivial: Fixes two payjoin test warnings.
  WalletWasabi.Tests/UnitTests/Transactions/PayjoinTests.cs
Labels: size/XS

#6934 [Trivial] Use range operator
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
  WalletWasabi/Blockchain/Mempool/MempoolService.cs
  WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
  WalletWasabi/Extensions/StringExtensions.cs
  WalletWasabi/Tor/Control/TorControlReplyReader.cs
  WalletWasabi/Userfacing/BitcoinInput.cs
  WalletWasabi/Userfacing/PasswordHelper.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Utils/CoinJoinTransactionArchiver.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/S

#6951 [Trivial] Remove unused variable
  WalletWasabi.Fluent/Rpc/WasabiJsonRpcService.cs
Labels: size/XS

#6941 [Backport] Remove feerate different sanity check
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
Labels: size/S

#6912 Remove PlatformTarget from Backend, Packager, Tests
  WalletWasabi.Backend/WalletWasabi.Backend.csproj
  WalletWasabi.Packager/WalletWasabi.Packager.csproj
  WalletWasabi.Tests/WalletWasabi.Tests.csproj
Labels: size/XS

#6950 Fix string cipher
  WalletWasabi.Tests/UnitTests/Crypto/StringCipherTests.cs
  WalletWasabi/Crypto/StringCipher.cs
Labels: size/L

#6469 Make texts more consistent in Settings
  WalletWasabi.Fluent/Views/Settings/GeneralSettingsTabView.axaml
  WalletWasabi.Fluent/Views/Settings/NetworkSettingsTabView.axaml
Labels: size/S

#6962 Fix NRE in UT
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/RoundStateUpdaterTests.cs
Labels: size/XS
