Repository WalletWasabi/WalletWasabi, pull requests merged in 2021-02, with the labels that each got.

#5100 Remove BackendHttpClient.
  WalletWasabi.Tests/RegressionTests/BackendTests.cs
  WalletWasabi/Tor/Http/BackendHttpClient.cs
Labels: size/M

#5103 [Fluent] Hardware wallet (round 3)
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/ConnectHardwareWalletViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/HardwareWallet/ConnectHardwareWalletView.axaml
Labels: size/M

#5055 Legal bits - part 4: Refactor LegalDocuments class
  WalletWasabi.Fluent/ViewModels/AddWallet/LegalDocumentsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/TermsAndConditionsViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/ClosedWalletViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/LegalDocumentsView.axaml
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Tests/UnitTests/LegalTests.cs
  WalletWasabi/Legal/LegalDocuments.cs
  WalletWasabi/Services/LegalChecker.cs
Labels: size/L

#5114 [Trivial] Docs: Add Tor Browser changelog link
  WalletWasabi.Documentation/Guides/UpgradeTorDaemons.md
Labels: size/XS

#5086 [Fluent] Send LineChart control
  WalletWasabi.Fluent/Controls/LineChart.cs
  WalletWasabi.Fluent/ViewModels/TestLineChartViewModel.cs
  WalletWasabi.Fluent/Views/MainWindow.axaml
  WalletWasabi.Fluent/Views/TestLineChartView.axaml
  WalletWasabi.Fluent/Views/TestLineChartView.axaml.cs
Labels: size/XXL

#5120 Disallow unconfirmed outputs registration
  WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
Labels: size/XS

#5121 Fluent - restore mainview.
  WalletWasabi.Fluent/Views/MainWindow.axaml
Labels: size/XS

#5122 [Fluent] [Trivial] Split LineChart properties into a separate file
  WalletWasabi.Fluent/Controls/LineChart.Properties.cs
  WalletWasabi.Fluent/Controls/LineChart.cs
Labels: size/XXL

#5123 [Fluent] [LineChart] Show drag cursor on pointer over event
  WalletWasabi.Fluent/Controls/LineChart.cs
Labels: size/M

#5106 Use IHttpClient in CoinJoinClient.
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/RegressionTests/DosTests.cs
  WalletWasabi/CoinJoin/Client/Clients/AliceClient4.cs
  WalletWasabi/CoinJoin/Client/Clients/AliceClientBase.cs
  WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
  WalletWasabi/Tor/TorMonitor.cs
  WalletWasabi/WebClients/Wasabi/WasabiClientFactory.cs
Labels: size/M

#5124 [Fluent] Line chart sizing
  WalletWasabi.Fluent/Controls/LineChart.Properties.cs
  WalletWasabi.Fluent/Controls/LineChart.cs
  WalletWasabi.Fluent/Views/TestLineChartView.axaml
Labels: size/L

#5126 [Fluent] Use IList for LineChart properties
  WalletWasabi.Fluent/Controls/LineChart.Properties.cs
Labels: size/S

#5117 Move validation folder to Fluent project
  WalletWasabi.Fluent/Validation/IRegisterValidationMethod.cs
  WalletWasabi.Fluent/Validation/IValidations.cs
  WalletWasabi.Fluent/Validation/ValidationExtensions.cs
  WalletWasabi.Fluent/Validation/Validations.cs
  WalletWasabi.Fluent/ViewLocator.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/RecoveryWordViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/AdvancedRecoveryOptionsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/EnterPasswordViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/BitcoinTabSettingsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/NetworkSettingsTabViewModel.cs
  WalletWasabi.Fluent/ViewModels/ViewModelBase.cs
Labels: size/L

#5128 Increase test timeouts
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/UtxoPrisonWardenTests.cs
  WalletWasabi.Tests/UnitTests/Wabisabi/Backend/ConfigTests.cs
Labels: size/S

#5024 Best Effort to connect to nodes privately
  WalletWasabi.Documentation/ClientDeployment.md
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Packager/ArgsProcessor.cs
  WalletWasabi.Packager/BitnodesApi.cs
  WalletWasabi.Packager/Program.cs
  WalletWasabi.Tests/UnitTests/BestEffortEndpointConnectorTests.cs
  WalletWasabi.Tests/UnitTests/Packager/ArgsProcessorTests.cs
  WalletWasabi.Tests/UnitTests/Packager/BitnodesApiTests.cs
  WalletWasabi/BestEffortEndpointConnector.cs
Labels: size/XL

#5135 [Fluent] Load wallet automatically
  WalletWasabi.Fluent/ViewModels/Wallets/ClosedWalletViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/ClosedWalletView.axaml
  WalletWasabi.Fluent/Views/Wallets/HardwareWallet/ClosedHardwareWalletView.axaml
  WalletWasabi.Fluent/Views/Wallets/HardwareWallet/ClosedHardwareWalletView.axaml.cs
Labels: size/M

#5115 Fluent Send: Base
  WalletWasabi.Fluent.Desktop/Program.cs
  WalletWasabi.Fluent.Generators/NavigationMetaDataGenerator.cs
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
  WalletWasabi.Fluent/Controls/Dialog.axaml
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/Styles/Styles.axaml
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/AddedWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/ConfirmRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/RecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/ConnectHardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/DetectedHardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/LegalDocumentsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/TermsAndConditionsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/AboutAdvancedInfoViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/AdvancedRecoveryOptionsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/EnterPasswordViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/ShowErrorDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/TestDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/LoginViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/ContainsNumbersViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/ContainsSymbolsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/PasswordFinderIntroduceViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/PasswordFoundViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/PasswordNotFoundViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/SearchPasswordViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/SelectCharsetViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/RoutableViewModel.cs
  WalletWasabi.Fluent/ViewModels/Search/SearchItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/SettingsPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/SettingsTabViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/LoadTransactionViewModel.cs
  WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/SuccessBroadcastTransactionViewModel.cs
  WalletWasabi.Fluent/ViewModels/TriggerCommandViewModel.cs
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Actions/AdvancedWalletActionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Actions/CoinJoinWalletActionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Actions/ReceiveWalletActionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Actions/SendWalletActionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Actions/WalletActionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModelBase.cs
  WalletWasabi.Fluent/Views/Dialogs/TestDialogView.axaml
  WalletWasabi.Fluent/Views/Dialogs/TestDialogView.axaml.cs
  WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
  WalletWasabi.Fluent/Views/Wallets/Actions/SendWalletActionView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml.cs
Labels: size/XXL

#5104 [Fluent] TagsBox improvements
  WalletWasabi.Fluent/App.axaml
  WalletWasabi.Fluent/Controls/TagControl.axaml
  WalletWasabi.Fluent/Controls/TagControl.axaml.cs
  WalletWasabi.Fluent/Controls/TagsBox.axaml
  WalletWasabi.Fluent/Controls/TagsBox.axaml.cs
  WalletWasabi.Fluent/Converters/HardwareWalletIconConverter.cs
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoveryWordIndexed.cs
Labels: size/L

#5131 Fix some CRLF -> LF.
  WalletWasabi.Fluent.Generators/PropertyGenerator.cs
  WalletWasabi.Fluent/Controls/LineChart.Properties.cs
  WalletWasabi.Fluent/Controls/LineChart.cs
  WalletWasabi.Fluent/Converters/EnumConverters.cs
  WalletWasabi.Fluent/Converters/MoneyConverters.cs
  WalletWasabi.Fluent/Converters/NavBarItemsListBoxAlignmentConverter.cs
  WalletWasabi.Fluent/Converters/NegativeDoubleConverter.cs
  WalletWasabi.Fluent/Converters/WalletIconConverter.cs
  WalletWasabi.Fluent/Helpers/Const.cs
  WalletWasabi.Fluent/Helpers/FileDialogHelper.cs
  WalletWasabi.Fluent/Helpers/ThemeHelper.cs
  WalletWasabi.Fluent/Model/RestartNeededEventArgs.cs
  WalletWasabi.Fluent/ViewModels/Login/LoginViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/ContainsNumbersViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/ContainsSymbolsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/PasswordFoundViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/PasswordNotFoundViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/SelectCharsetViewModel.cs
  WalletWasabi.Fluent/ViewModels/OpenDirectory/OpenWalletsFolderViewModel.cs
  WalletWasabi.Fluent/ViewModels/Search/SearchCategory.cs
  WalletWasabi.Fluent/ViewModels/Settings/GeneralSettingsTabViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/PrivacyModeViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/PrivacySettingsTabViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/SettingsTabViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/BroadcastTransactionViewModel.cs
  WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/LoadTransactionViewModel.cs
  WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/SuccessBroadcastTransactionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Actions/AdvancedWalletActionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Actions/CoinJoinWalletActionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Actions/ReceiveWalletActionViewModel.cs
Labels: size/M

#5139 improve website
  WalletWasabi.Backend/wwwroot/index.html
Labels: size/XS

#5132 [trivial] Rename: WasabiClientFactory ->HttpClientFactory
  WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Tests/IntegrationTests/P2pTests.cs
  WalletWasabi.Tests/RegressionTests/BuildTests.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi.Tests/RegressionTests/WalletTests.cs
  WalletWasabi/Blockchain/Mempool/MempoolService.cs
  WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs
  WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
  WalletWasabi/CoinJoin/Client/CoinJoinProcessor.cs
  WalletWasabi/Services/UpdateChecker.cs
  WalletWasabi/Services/WasabiSynchronizer.cs
  WalletWasabi/Wallets/P2pBlockProvider.cs
  WalletWasabi/Wallets/Wallet.cs
  WalletWasabi/WebClients/Wasabi/HttpClientFactory.cs
Labels: size/L

#5141 [Fluent] Fix wallet navigation issue when wallet is created
  WalletWasabi.Fluent/ViewModels/AddWallet/AddedWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
Labels: size/XS

#5143 [Fluent] TagsBox fixes part 2
  WalletWasabi.Fluent/Controls/TagControl.axaml
  WalletWasabi.Fluent/Controls/TagControl.axaml.cs
  WalletWasabi.Fluent/Controls/TagsBox.axaml
  WalletWasabi.Fluent/Controls/TagsBox.axaml.cs
  WalletWasabi.Fluent/Styles/Themes/BaseDark.axaml
  WalletWasabi.Fluent/Styles/Themes/BaseLight.axaml
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoveryWordIndexed.cs
Labels: size/L

#5152 Fix typo in method name
  WalletWasabi/Tor/Http/Helpers/HttpMessageHelper.cs
Labels: size/XS

#5153 [Fluent] Tagsbox fixes round 3
  WalletWasabi.Fluent/Controls/TagsBox.axaml.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/RecoverWalletView.axaml
Labels: size/L

#5167 Update Constants.UserAgents
  WalletWasabi/Helpers/Constants.cs
Labels: size/XS

#5142 [Trivial] Docs: Fix typos
  WalletWasabi.Documentation/Guides/UpgradeTorDaemons.md
Labels: size/XS

#5148 [Fluent] Set DesignWidth and DesignHeight to minimal supported size
  WalletWasabi.Fluent/Views/AddWallet/AddWalletPageView.axaml
  WalletWasabi.Fluent/Views/AddWallet/AddedWalletPageView.axaml
  WalletWasabi.Fluent/Views/AddWallet/Create/ConfirmRecoveryWordsView.axaml
  WalletWasabi.Fluent/Views/AddWallet/Create/RecoveryWordsView.axaml
  WalletWasabi.Fluent/Views/AddWallet/HardwareWallet/ConnectHardwareWalletView.axaml
  WalletWasabi.Fluent/Views/AddWallet/HardwareWallet/DetectedHardwareWalletView.axaml
  WalletWasabi.Fluent/Views/AddWallet/LegalDocumentsView.axaml
  WalletWasabi.Fluent/Views/AddWallet/RecoverWalletView.axaml
  WalletWasabi.Fluent/Views/AddWallet/TermsAndConditionsView.axaml
  WalletWasabi.Fluent/Views/Dialogs/AboutAdvancedInfoView.axaml
  WalletWasabi.Fluent/Views/Dialogs/AdvancedRecoveryOptionsView.axaml
  WalletWasabi.Fluent/Views/Dialogs/EnterPasswordView.axaml
  WalletWasabi.Fluent/Views/Dialogs/ShowErrorDialogView.axaml
  WalletWasabi.Fluent/Views/HelpAndSupport/AboutView.axaml
  WalletWasabi.Fluent/Views/Login/LoginView.axaml
  WalletWasabi.Fluent/Views/Login/PasswordFinder/ContainsNumbersView.axaml
  WalletWasabi.Fluent/Views/Login/PasswordFinder/ContainsSymbolsView.axaml
  WalletWasabi.Fluent/Views/Login/PasswordFinder/PasswordFinderIntroduceView.axaml
  WalletWasabi.Fluent/Views/Login/PasswordFinder/PasswordFoundView.axaml
  WalletWasabi.Fluent/Views/Login/PasswordFinder/PasswordNotFoundView.axaml
  WalletWasabi.Fluent/Views/Login/PasswordFinder/SearchPasswordView.axaml
  WalletWasabi.Fluent/Views/Login/PasswordFinder/SelectCharsetView.axaml
  WalletWasabi.Fluent/Views/MainView.axaml
  WalletWasabi.Fluent/Views/MainWindow.axaml
  WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
  WalletWasabi.Fluent/Views/Search/SearchPageView.axaml
  WalletWasabi.Fluent/Views/Settings/BitcoinTabSettingsView.axaml
  WalletWasabi.Fluent/Views/Settings/GeneralSettingsTabView.axaml
  WalletWasabi.Fluent/Views/Settings/NetworkSettingsTabView.axaml
  WalletWasabi.Fluent/Views/Settings/PrivacySettingsTabView.axaml
  WalletWasabi.Fluent/Views/Settings/SettingsPageView.axaml
  WalletWasabi.Fluent/Views/StatusBar.axaml
  WalletWasabi.Fluent/Views/TestLineChartView.axaml
  WalletWasabi.Fluent/Views/TransactionBroadcasting/BroadcastTransactionView.axaml
  WalletWasabi.Fluent/Views/TransactionBroadcasting/LoadTransactionView.axaml
  WalletWasabi.Fluent/Views/TransactionBroadcasting/SuccessBroadcastTransactionView.axaml
  WalletWasabi.Fluent/Views/Wallets/Actions/AdvancedWalletActionView.axaml
  WalletWasabi.Fluent/Views/Wallets/Actions/CoinJoinWalletActionView.axaml
  WalletWasabi.Fluent/Views/Wallets/Actions/ReceiveWalletActionView.axaml
  WalletWasabi.Fluent/Views/Wallets/ClosedWalletView.axaml
  WalletWasabi.Fluent/Views/Wallets/HardwareWallet/ClosedHardwareWalletView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Labels: size/M

#5149 [Fluent] Use using instead of clr-namespace
  WalletWasabi.Fluent/Controls/InfoMessage.axaml
  WalletWasabi.Fluent/Views/AddWallet/Create/ConfirmRecoveryWordsView.axaml
  WalletWasabi.Fluent/Views/AddWallet/Create/RecoveryWordsView.axaml
  WalletWasabi.Fluent/Views/AddWallet/HardwareWallet/ConnectHardwareWalletView.axaml
  WalletWasabi.Fluent/Views/AddWallet/HardwareWallet/DetectedHardwareWalletView.axaml
  WalletWasabi.Fluent/Views/AddWallet/LegalDocumentsView.axaml
  WalletWasabi.Fluent/Views/Dialogs/AboutAdvancedInfoView.axaml
  WalletWasabi.Fluent/Views/HelpAndSupport/AboutView.axaml
  WalletWasabi.Fluent/Views/Login/PasswordFinder/SelectCharsetView.axaml
  WalletWasabi.Fluent/Views/Settings/BitcoinTabSettingsView.axaml
  WalletWasabi.Fluent/Views/Settings/GeneralSettingsTabView.axaml
  WalletWasabi.Fluent/Views/Settings/NetworkSettingsTabView.axaml
  WalletWasabi.Fluent/Views/Settings/PrivacySettingsTabView.axaml
  WalletWasabi.Fluent/Views/Settings/SettingsPageView.axaml
  WalletWasabi.Fluent/Views/TransactionBroadcasting/BroadcastTransactionView.axaml
  WalletWasabi.Fluent/Views/TransactionBroadcasting/LoadTransactionView.axaml
  WalletWasabi.Fluent/Views/TransactionBroadcasting/SuccessBroadcastTransactionView.axaml
  WalletWasabi.Fluent/Views/Wallets/ClosedWalletView.axaml
  WalletWasabi.Fluent/Views/Wallets/HardwareWallet/ClosedHardwareWalletView.axaml
Labels: size/M

#5170 [Fluent] [LineChart] Add additional checks for Y axis value data
  WalletWasabi.Fluent/Controls/LineChart.cs
Labels: size/S

#5157 IoHelpers: Remove unused "CheckExpectedHash" method.
  WalletWasabi.Documentation/Guides/UpgradeTorDaemons.md
  WalletWasabi/Helpers/IoHelpers.cs
Labels: size/M

#5102 IHttpClient: Remove isolate stream parameter.
  WalletWasabi.Tests/UnitTests/Clients/MockTorHttpClient.cs
  WalletWasabi/CoinJoin/Client/Clients/AliceClientBase.cs
  WalletWasabi/Tor/Http/ClearnetHttpClient.cs
  WalletWasabi/Tor/Http/IHttpClient.cs
  WalletWasabi/Tor/Http/TorHttpClient.cs
Labels: size/L

#5155 Remove dead code
  WalletWasabi/Tor/Http/Helpers/HttpMessageHelper.cs
  WalletWasabi/Tor/Http/Helpers/HttpRequestUriBuilder.cs
Labels: size/L

#5154 Remove dead code
  WalletWasabi/Helpers/Guard.cs
  WalletWasabi/JsonConverters/GuidJsonConverter.cs
Labels: size/M

#5138 Remove ClearnetHttpClient from TorHttpClient
  WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs
  WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
  WalletWasabi/Tor/Http/TorHttpClient.cs
  WalletWasabi/WebClients/PayJoin/PayjoinClient.cs
  WalletWasabi/WebClients/Wasabi/HttpClientFactory.cs
Labels: size/L

#5125 TorProcessManager - more clear info about the current state
  WalletWasabi/Tor/TorMonitor.cs
  WalletWasabi/Tor/TorProcessManager.cs
Labels: size/S

#5160 SendUX part 2: Add label binding and some polish
  WalletWasabi.Fluent/Assets/TechnologyLogos/payjoin.png
  WalletWasabi.Fluent/Controls/ContentArea.axaml
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
  WalletWasabi.Fluent/Controls/TagControl.axaml
  WalletWasabi.Fluent/Controls/TagControl.axaml.cs
  WalletWasabi.Fluent/Controls/TagsBox.axaml
  WalletWasabi.Fluent/Controls/TagsBox.axaml.cs
  WalletWasabi.Fluent/Styles/Label.axaml
  WalletWasabi.Fluent/Styles/TextBox.axaml
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/Views/MainView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
  WalletWasabi.Gui/Converters/FeeTargetTimeConverter.cs
  WalletWasabi/Services/WasabiSynchronizer.cs
Labels: size/L

#5189 Send ux select pockets
  WalletWasabi.Fluent/ViewModels/Wallets/Send/OptimisePrivacyViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionInfo.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Send/OptimisePrivacyView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/OptimisePrivacyView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Send/PrivacyControlView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/PrivacyControlView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml.cs
Labels: size/L

#5129 [Fluent] [LineChart] New features
  WalletWasabi.Fluent/Controls/LineChart.Properties.cs
  WalletWasabi.Fluent/Controls/LineChart.cs
  WalletWasabi.Fluent/Views/TestLineChartView.axaml
Labels: size/L

#5168 [Fluent] Call InsertActions only when wallet is selected
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
Labels: size/S

#5150 [Flunet] [LineChart] Spline interpolation
  WalletWasabi.Fluent/MathNet/CubicSpline.cs
  WalletWasabi.Fluent/ViewModels/TestLineChartViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
Labels: size/L

#5191 [Fluent] Implement Send Navigation Logic
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
Labels: size/M

#5195 [Fluent] Track only selectable NavBarItemViewModel in wallet manager
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
Labels: size/XS

#5166 Remove dead code
  WalletWasabi/Helpers/IoHelpers.cs
  WalletWasabi/Hwi/HwiClient.cs
  WalletWasabi/Io/IoManager.cs
Labels: size/M

#5179 Remove dead code
  WalletWasabi/Gma/QrCodeNet/Encoding/DataEncodation/InputRecognition/ModeEncodeCheck.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/Masking/MatrixExtensions.cs
  WalletWasabi/Tor/Http/Helpers/HttpMessageHelper.cs
  WalletWasabi/Tor/Socks5/Models/Fields/ByteArrayFields/MethodsField.cs
Labels: size/M

#5186 Update Legal docs support
  WalletWasabi/Legal/Assets/LegalDocuments.txt
Labels: size/XS

#5207 Complete guarding of post requests
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/ConfirmConnectionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/RegisterInputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/RegisterOutputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/RemoveInputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/SignTransactionTests.cs
  WalletWasabi/WabiSabi/Backend/Models/Alice.cs
  WalletWasabi/WabiSabi/Backend/Models/WabiSabiProtocolErrorCode.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/PostRequestHandler.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
  WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
  WalletWasabi/WabiSabi/Models/InputsRemovalRequest.cs
Labels: size/L

#5178 Remove TorSocks5Client.Connected property
  WalletWasabi/Tor/Http/TorHttpClient.cs
  WalletWasabi/Tor/Socks5/TorSocks5Client.cs
Labels: size/M

#5206 [Fluent] TagsBox fixes part 4
  WalletWasabi.Fluent/Controls/TagsBox.axaml
Labels: size/M

#5193 [Fluent] [Trivial] Remove unused WalletWasabi.Gui.ViewModels using
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationManager.cs
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationStack.cs
  WalletWasabi.Fluent/ViewModels/Navigation/RoutableViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/SettingsTabViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
Labels: size/XS

#5192 Fluent - Add Validation to Send Page
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
  WalletWasabi.Fluent/Controls/TagControl.axaml
  WalletWasabi.Fluent/Controls/TagsBox.axaml
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Labels: size/M

#4994 Tor parallel bits - part 9: Clearnet and HttpClient as dependency.
  WalletWasabi.Tests/RegressionTests/BackendTests.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/RegressionTests/Common.cs
  WalletWasabi.Tests/RegressionTests/DosTests.cs
  WalletWasabi.Tests/XunitConfiguration/RegTestFixture.cs
  WalletWasabi/Tor/Http/ClearnetHttpClient.cs
  WalletWasabi/Tor/Http/TorHttpClient.cs
  WalletWasabi/WebClients/Wasabi/HttpClientFactory.cs
Labels: size/M

#5187 [Backport v1.1.12.4] Best Effort to connect
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Gui/packages.lock.json
  WalletWasabi.Packager/Program.cs
  WalletWasabi.Packager/packages.lock.json
  WalletWasabi.Tests/UnitTests/BestEffortEndpointConnectorTests.cs
  WalletWasabi/BestEffortEndpointConnector.cs
  WalletWasabi/OnionSeeds/MainOnionSeeds.txt
  WalletWasabi/OnionSeeds/TestNetOnionSeeds.txt
  WalletWasabi/WalletWasabi.csproj
  WalletWasabi/packages.lock.json
Labels: size/XXL

#5214 [Backport v1.1.12.4] Dump version
  WalletWasabi/Helpers/Constants.cs
Labels: size/XS

#5197 Simplify fee rate fetching
  WalletWasabi.Tests/UnitTests/AllFeeEstimateTests.cs
  WalletWasabi.Tests/UnitTests/BitcoinCore/RpcBasedTests.cs
  WalletWasabi.Tests/UnitTests/MockRpcClient.cs
  WalletWasabi/Blockchain/Analysis/FeesEstimation/AllFeeEstimate.cs
  WalletWasabi/Extensions/RPCClientExtensions.cs
  WalletWasabi/Helpers/Constants.cs
Labels: size/L

#5213 [Fluent] Currency Box Fixes part 2
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
  WalletWasabi.Fluent/Controls/TagsBox.axaml.cs
Labels: size/L

#5215 Dump version to v1.1.12.4
  WalletWasabi.Backend/wwwroot/index.html
  WalletWasabi/Helpers/Constants.cs
Labels: size/S

#5217 [Fluent] Currency Box part 3
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
Labels: size/XS

#5194 [Fluent] List base style
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/Styles/DataGrid.axaml
  WalletWasabi.Fluent/Styles/Styles.axaml
  WalletWasabi.Fluent/Styles/Themes/Base.axaml
  WalletWasabi.Fluent/Styles/Themes/BaseDark.axaml
  WalletWasabi.Fluent/Styles/Themes/BaseLight.axaml
  WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveAddressesView.axaml
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
Labels: size/L

#5182 Order element & rename method
  WalletWasabi/Extensions/NBitcoinExtensions.cs
  WalletWasabi/Hwi/HwiClient.cs
Labels: size/S

#5202 Remove dead code
  WalletWasabi/CoinJoin/Common/Crypto/SchnorrKey.cs
  WalletWasabi/CoinJoin/Common/Crypto/SchnorrPubKey.cs
  WalletWasabi/Crypto/SchnorrBlindingSignature.cs
Labels: size/S

#5201 Remove dead code
  WalletWasabi/Helpers/NBitcoinHelpers.cs
  WalletWasabi/Microservices/ProcessAsync.cs
  WalletWasabi/Tor/Http/Models/RequestLine.cs
Labels: size/M

#5146 Remove dead code
  WalletWasabi/BitcoinCore/Endpointing/EndPointStrategy.cs
  WalletWasabi/Helpers/EnvironmentHelpers.cs
Labels: size/S

#5208 Fix codefactor issues
  WalletWasabi.Gui/Dialogs/CannotCloseDialogViewModel.cs
  WalletWasabi.Packager/MacSignTools.cs
  WalletWasabi.Tests/UnitTests/Crypto/StrobeTests.cs
Labels: size/M

#5226 [Trivial] [CodeFactor] Start parameter on line after declaration
  WalletWasabi.Packager/MacSignTools.cs
Labels: size/XS

#5225 [CodeFactor] Order Elements
  WalletWasabi.Gui/Tabs/WalletManager/RecoverWallets/RecoverWalletViewModel.cs
  WalletWasabi/Crypto/SchnorrBlindingSignature.cs
Labels: size/L

#5219 Adding Gordon Ramsey's Kitchen to wallet
  WalletWasabi.Fluent/ViewModels/Login/LoginViewModel.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
  WalletWasabi/Wallets/Kitchen.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/L

#5228 Fix CcjTestsAsync test.
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
Labels: size/S

#5161 [Fluent] Show Legal
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/ConnectHardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/LegalDocumentsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/TermsAndConditionsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/DialogViewModelBaseOfTResult.cs
  WalletWasabi.Fluent/ViewModels/Login/LoginViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/RoutableViewModel.cs
  WalletWasabi.Fluent/ViewModels/Search/SearchPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/ClosedWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/HardwareWallet/ClosedHardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WatchOnlyWallet/ClosedWatchOnlyWalletViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/TermsAndConditionsView.axaml
  WalletWasabi/Services/LegalChecker.cs
Labels: size/L

#5203 [Fluent] [LineChart] Update
  WalletWasabi.Fluent/Controls/LineChart.Properties.cs
  WalletWasabi.Fluent/Controls/LineChart.cs
  WalletWasabi.Fluent/ViewModels/LineChartDemo/SendLineChartViewModel.cs
  WalletWasabi.Fluent/ViewModels/LineChartDemo/XYLineChartViewModel.cs
  WalletWasabi.Fluent/Views/LineChartDemo/SendLineChartView.axaml
  WalletWasabi.Fluent/Views/LineChartDemo/SendLineChartView.axaml.cs
  WalletWasabi.Fluent/Views/LineChartDemo/XYLineChartView.axaml
  WalletWasabi.Fluent/Views/LineChartDemo/XYLineChartView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Labels: size/XL

#5231 [Fluent] Spline interpolation update
  WalletWasabi.Fluent/MathNet/CubicSpline.cs
  WalletWasabi.Fluent/MathNet/Precision.Equality.cs
  WalletWasabi.Fluent/MathNet/Precision.cs
  WalletWasabi.Fluent/MathNet/SplineBoundaryCondition.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
Labels: size/XL

#5210 Make sure some checks are the responsibility of the round
  WalletWasabi.Tests/Helpers/BitcoinFactory.cs
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/Crypto/ProofSystemTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/ConfirmConnectionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/MockArena.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/RegisterInputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/RegisterOutputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/RemoveInputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/RequestHandlerDisposeTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/SignTransactionTests.cs
  WalletWasabi/Crypto/CredentialIssuerParameters.cs
  WalletWasabi/Crypto/ZeroKnowledge/ProofSystem.cs
  WalletWasabi/Extensions/NBitcoinExtensions.cs
  WalletWasabi/WabiSabi/Backend/Models/Alice.cs
  WalletWasabi/WabiSabi/Backend/Models/Bob.cs
  WalletWasabi/WabiSabi/Backend/Models/WabiSabiProtocolErrorCode.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/PostRequestHandler.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Rounds/IArena.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
  WalletWasabi/WabiSabi/Backend/Rounds/RoundParameters.cs
  WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
  WalletWasabi/WabiSabi/CoordinatorParameters.cs
  WalletWasabi/WabiSabi/Crypto/CredentialIssuer.cs
  WalletWasabi/WabiSabi/Crypto/WabiSabiClient.cs
  WalletWasabi/WabiSabi/Models/InputWitnessPair.cs
  WalletWasabi/WabiSabi/Models/InputsRemovalRequest.cs
  WalletWasabi/WabiSabi/Models/OutputRegistrationRequest.cs
  WalletWasabi/WabiSabi/Models/TransactionSignaturesRequest.cs
  WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
Labels: size/XXL

#5238 remove XamBehaviors nuget feed.
  NuGet.Config
Labels: size/XS

#5243 Clean up after cooking
  WalletWasabi/Wallets/Kitchen.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/S

#5235 [trivial] CoinJoinTests: Remove unused code.
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
Labels: size/XS

#5244 [Fluent][Trivial] Rename inStack to isInHistory
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/ConnectHardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/DetectedHardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/SearchPasswordViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/RoutableViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/SettingsPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/TriggerCommandViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressesViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
Labels: size/M

#5247 [Fluent] Do not pass KeyManager to a converter
  WalletWasabi.Fluent/Converters/HardwareWalletIconConverter.cs
  WalletWasabi.Fluent/Converters/WalletIconConverter.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/AddedWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/LoginViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/AddedWalletPageView.axaml
  WalletWasabi.Fluent/Views/Login/LoginView.axaml
  WalletWasabi/Wallets/WalletType.cs
Labels: size/L

#5234 [WabiSabi] Handle Alice if already registered
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/RegisterInputTests.cs
  WalletWasabi/WabiSabi/Backend/Models/WabiSabiProtocolErrorCode.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/InputRegistrationHandler.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/PostRequestHandler.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
Labels: size/XL

#5220 [Fluent] Unused addresses list
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/Styles/DataGrid.axaml
  WalletWasabi.Fluent/ViewModels/Dialogs/ConfirmHideAddressViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/AddressViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressesViewModel.cs
  WalletWasabi.Fluent/Views/Dialogs/ConfirmHideAddressView.axaml
  WalletWasabi.Fluent/Views/Dialogs/ConfirmHideAddressView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveAddressesView.axaml
Labels: size/L

#5233 [Fluent] Move password check to wallet
  WalletWasabi.Fluent/ViewModels/Login/LoginViewModel.cs
  WalletWasabi.Fluent/Views/Login/LoginView.axaml
  WalletWasabi/Wallets/Wallet.cs
Labels: size/L

#5250 [Fluent] Keep NavBarItem height when login inicator is visible
  WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
Labels: size/XS

#5251 [WabiSabi Protocol] Continue
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/AliceTimeoutTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/ConfirmConnectionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/RegisterInputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/RegisterOutputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/RemoveInputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/RoundCreationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/SignTransactionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/StepInputRegistrationTests.cs
  WalletWasabi/WabiSabi/Backend/Models/Alice.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/InputRegistrationHandler.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/PostRequestHandler.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
  WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
  WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
Labels: size/XL

#5260 Return an interface rather than the real thing
  WalletWasabi/WabiSabi/Backend/PostRequests/InputRegistrationHandler.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/PostRequestHandler.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/XS

#5256 Reduce RPC calls in coinjoins
  WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
Labels: size/XS

#5252 Fix duplicate item exception in GetFeeEstimations
  WalletWasabi/Extensions/RPCClientExtensions.cs
Labels: size/XS

#5232 [Fluent] Smooth fee estimates
  WalletWasabi.Fluent/Controls/LineChart.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
Labels: size/L

#5262 [WabiSabi Protocol] Implement Moving to OutputRegistration
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/AliceTimeoutTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/ConfirmConnectionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/RegisterInputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/RegisterOutputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/RemoveInputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/RoundCreationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/SignTransactionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/StepConnectionConfirmationTests.cs
  WalletWasabi/WabiSabi/Backend/Banning/Prison.cs
  WalletWasabi/WabiSabi/Backend/Models/Alice.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/InputRegistrationHandler.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
  WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
Labels: size/L

#5254 WalletManager: Nits
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/XS

#5269 Add GetPockets method
  WalletWasabi.Fluent/Helpers/CoinPocketHelper.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
Labels: size/M

#5263 Instructions to update Knots
  WalletWasabi.Documentation/BackendDeployment.md
Labels: size/XS

#5271 [Fluent] [Trivial] Improve a bit Receive view button feedback
  WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveAddressView.axaml
Labels: size/XS

#5266 [WabiSabi Protocol] Implement Moving from OutputRegistration
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/StepConnectionConfirmationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/StepOutputRegistrationTests.cs
  WalletWasabi/Extensions/NBitcoinExtensions.cs
  WalletWasabi/JsonConverters/Bitcoin/DefaultValueScriptAttribute.cs
  WalletWasabi/JsonConverters/Bitcoin/ScriptJsonConverter.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
Labels: size/L

#5275 Create tx broadcaster in global ctor
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Tests/RegressionTests/BuildTests.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs
Labels: size/M

#5218 Fluent: Send Optimise privacy screen UX implementation
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
  WalletWasabi.Fluent/Converters/PrivacyOptimisationLevelConverters.cs
  WalletWasabi.Fluent/Helpers/CurrencyUtils.cs
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/Styles/Themes/Base.axaml
  WalletWasabi.Fluent/Validation/Validations.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/DetectedHardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/CreatePasswordDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/EnterPasswordDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/LoginViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/PasswordFinderIntroduceViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/RoutableViewModel.cs
  WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/BroadcastTransactionViewModel.cs
  WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/LoadTransactionViewModel.cs
  WalletWasabi.Fluent/ViewModels/ViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/HardwareWallet/HardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/OptimisePrivacyViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacySuggestionControlViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WatchOnlyWallet/WatchOnlyWalletViewModel.cs
  WalletWasabi.Fluent/Views/Dialogs/CreatePasswordDialogView.axaml
  WalletWasabi.Fluent/Views/Dialogs/CreatePasswordDialogView.axaml.cs
  WalletWasabi.Fluent/Views/Dialogs/EnterPasswordDialogView.axaml
  WalletWasabi.Fluent/Views/Dialogs/EnterPasswordDialogView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Send/OptimisePrivacyView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/PrivacySuggestionControl.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/PrivacySuggestionControl.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml
  WalletWasabi/Wallets/Wallet.cs
Labels: size/XL
