Repository WalletWasabi/WalletWasabi, pull requests merged in 2021-03, with the labels that each got.

#5273 [WabiSabi Protocol] Step TransactionSigning phase
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/MockRpcClient.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/AliceTimeoutTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/ConfirmConnectionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/RegisterInputFailureTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/RegisterInputSuccessTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/RegisterInputToBlameRoundTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/RegisterOutputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/RemoveInputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/RoundCreationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/SignTransactionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/StepInputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/StepTransactionSigningTests.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/InputRegistrationHandler.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Phase.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
  WalletWasabi/WabiSabi/Backend/Rounds/RoundParameters.cs
  WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
Labels: size/XXL

#5286 Organize tests into folders
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepConnectionConfirmationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepInputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/ConfirmConnectionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputSuccessTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputToBlameRoundTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterOutputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RemoveInputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/SignTransactionTests.cs
Labels: size/S

#5280 Use MemberNotNullWhen attribute
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
  WalletWasabi/WebClients/Wasabi/HttpClientFactory.cs
Labels: size/XS

#5283 [Fluent] Organize 'ViewModels\Dialogs' folder
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/TermsAndConditionsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/AboutAdvancedInfoViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/AdvancedRecoveryOptionsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/Base/DialogResult.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/Base/DialogResultKind.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/Base/DialogScreenViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/Base/DialogViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/Base/DialogViewModelBaseOfTResult.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/Base/IDialogHost.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/ConfirmHideAddressViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/CreatePasswordDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/EnterPasswordDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/ShowErrorDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/PasswordFinderIntroduceViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationState.cs
  WalletWasabi.Fluent/ViewModels/Navigation/RoutableViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/TargettedNavigationStack.cs
  WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/LoadTransactionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
Labels: size/M

#5276 [Fluent] Disable CurrencyEntryBox's conversion when exchange rate is empty.
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
Labels: size/S

#5211 Remove text-decoration and color from social hyperlinks
  WalletWasabi.Backend/wwwroot/index.html
Labels: size/XS

#5291 [Fluent] Change coinjoin icon
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveAddressesView.axaml
Labels: size/XS

#5140 Add status checks to BackendDeployment.md
  WalletWasabi.Documentation/BackendDeployment.md
Labels: size/S

#5282 [Fluent] Send authorization dialogs
  WalletWasabi.Fluent/Helpers/AuthorizationHelpers.cs
  WalletWasabi.Fluent/Model/TransactionAuthorizationInfo.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/Authorization/AuthorizationDialogBase.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/Authorization/HardwareWalletAuthDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/Authorization/PasswordAuthDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/EnterPasswordDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Fluent/Views/Dialogs/Authorization/HardwareWalletAuthDialogView.axaml
  WalletWasabi.Fluent/Views/Dialogs/Authorization/HardwareWalletAuthDialogView.axaml.cs
  WalletWasabi.Fluent/Views/Dialogs/Authorization/PasswordAuthDialogView.axaml
  WalletWasabi.Fluent/Views/Dialogs/Authorization/PasswordAuthDialogView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml
Labels: size/L

#5297 Add encrypted unsigned coinjoin
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
  WalletWasabi/WabiSabi/Models/OutputRegistrationResponse.cs
Labels: size/S

#5236 TorMonitor: Use HttpClientFactory.
  WalletWasabi.Gui/Global.cs
  WalletWasabi/Tor/Http/TorHttpClient.cs
  WalletWasabi/Tor/TorMonitor.cs
Labels: size/M

#5298 Fix anonymity set bug
  WalletWasabi.Tests/Helpers/BitcoinFactory.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/UnitTests/BlockchainAnalysis/CoinJoinAnonscoreTests.cs
  WalletWasabi.Tests/UnitTests/BlockchainAnalysis/NormalSpendAnonScoreTests.cs
  WalletWasabi.Tests/UnitTests/BlockchainAnalysis/PubKeyReuseAnonScoreTests.cs
  WalletWasabi.Tests/UnitTests/BlockchainAnalysis/SelfSpendAnonScoreTests.cs
  WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs
  WalletWasabi/Blockchain/Keys/HdPubKey.cs
Labels: size/L

#5292 Use FriendlyName attribute instead of Description attribute
  WalletWasabi/CoinJoin/Client/Clients/Queuing/DequeueReason.cs
  WalletWasabi/Extensions/EnumExtension.cs
  WalletWasabi/Hwi/Models/HardwareWalletModels.cs
  WalletWasabi/Models/FriendlyNameAttribute.cs
  WalletWasabi/Wallets/PasswordFinder/PasswordFinderCharset.cs
Labels: size/M

#5300 Add Logging in Signing and Broadcasting phase
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/LoggerTools.cs
Labels: size/M

#5301 Remove ugliSolution var from tests
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
Labels: size/L

#5295 Fix line endings in Tor sh file
  .gitattributes
  WalletWasabi/Microservices/Binaries/osx64/Tor/tor
Labels: size/XS

#5306 Replace L with UL in AllFeeEstimateTests.cs
  WalletWasabi.Tests/UnitTests/AllFeeEstimateTests.cs
Labels: size/XS

#5305 [easy] Add HttpClientFactory to Global.
  WalletWasabi.Gui/Global.cs
Labels: size/XS

#5302 Potentially fix anonySet decrease bug
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
  WalletWasabi/Bases/NotifyPropertyChangedBase.cs
  WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
Labels: size/M

#5310 Fix validations, fix warnings
  WalletWasabi.Fluent/Validation/Validations.cs
  WalletWasabi.Fluent/ViewModels/ViewModelBase.cs
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Labels: size/M

#5290 Use Isolation library
  WalletWasabi.Tests/Helpers/ServiceFactory.cs
  WalletWasabi.Tests/UnitTests/AllFeeEstimateTests.cs
  WalletWasabi.Tests/UnitTests/Clients/MockTorHttpClient.cs
  WalletWasabi.Tests/UnitTests/Clients/WasabiClientTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/CredentialIssuerKeyTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/RandomTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/TranscriptTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/KnowledgeOfDlogTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/KnowledgeOfRepTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/PayjoinTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionStoreMock.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionStoreTests.cs
  WalletWasabi.Tests/WalletWasabi.Tests.csproj
  WalletWasabi/Blockchain/Transactions/AllTransactionStoreMock.cs
  WalletWasabi/Crypto/Randomness/MockRandom.cs
  WalletWasabi/Crypto/Randomness/WasabiRandom.cs
Labels: size/XL

#5303 [Fluent] Send view X value cursor calculation
  WalletWasabi.Fluent/Controls/LineChart.Properties.cs
  WalletWasabi.Fluent/Controls/LineChart.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/Views/LineChartDemo/SendLineChartView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Labels: size/L

#5314 Alternative solution for AnonSet bug
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
  WalletWasabi/Bases/NotifyPropertyChangedBase.cs
  WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
Labels: size/S

#5312 Ownership proofs - Part 1
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/Crypto/Bip322SignatureTest.cs
  WalletWasabi.Tests/UnitTests/Crypto/OwnershipProofTest.cs
  WalletWasabi/Crypto/Bip322Signature.cs
  WalletWasabi/Crypto/OwnershipProof.cs
  WalletWasabi/Extensions/NBitcoinExtensions.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/InputRegistrationHandler.cs
Labels: size/L

#5315 Use Global.HttpClientFactory instead of Synchronizer.HttpClientFactory
  WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Tests/IntegrationTests/P2pTests.cs
  WalletWasabi.Tests/RegressionTests/BuildTests.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi.Tests/RegressionTests/WalletTests.cs
  WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs
  WalletWasabi/Wallets/P2pBlockProvider.cs
Labels: size/M

#5268 Privacy Control
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
  WalletWasabi.Fluent/Helpers/CoinPocketHelper.cs
  WalletWasabi.Fluent/Styles/DataGrid.axaml
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PocketViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Send/PrivacyControlView.axaml
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
Labels: size/L

#5321 MempoolNotifiesAsync times out often.
  WalletWasabi.Tests/UnitTests/BitcoinCore/P2pBasedTests.cs
Labels: size/XS

#5311 remove all the excess code for dialog over dialog.
  WalletWasabi.Fluent.Generators/NavigationMetaDataGenerator.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/Authorization/PasswordAuthDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/Base/DialogViewModelBaseOfTResult.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/Base/IDialogHost.cs
  WalletWasabi.Fluent/ViewModels/HelpAndSupport/AboutViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationState.cs
  WalletWasabi.Fluent/ViewModels/Navigation/RoutableViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Fluent/Views/MainView.axaml
Labels: size/L

#5272 [Fluent] Receive view copy button animation
  WalletWasabi.Fluent/Behaviors/AddClassAction.cs
  WalletWasabi.Fluent/Controls/AnimatedButton.axaml
  WalletWasabi.Fluent/Controls/AnimatedButton.axaml.cs
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/Styles/Styles.axaml
  WalletWasabi.Fluent/Views/HelpAndSupport/AboutView.axaml
  WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveAddressView.axaml
  WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveAddressesView.axaml
Labels: size/L

#5270 Add support for Ledger Nano X
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/DetectedHardwareWalletViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/HardwareWallets/ConnectHardwareWalletView.xaml
  WalletWasabi.Tests/AcceptanceTests/HwiKatas.cs
  WalletWasabi.Tests/UnitTests/Hwi/HwiProcessBridgeMock.cs
  WalletWasabi.Tests/UnitTests/Hwi/MockedDeviceTests.cs
  WalletWasabi.Tests/UnitTests/WalletDirTests.cs
  WalletWasabi/Hwi/Models/HardwareWalletModels.cs
Labels: size/L

#5327 SLIP-0021 Implementation
  WalletWasabi.Tests/UnitTests/Crypto/Slip21NodeTests.cs
  WalletWasabi/Crypto/Slip21Node.cs
Labels: size/M

#5328 [Fluent] Show HW wallet auth dialog in CompactDialogScreen
  WalletWasabi.Fluent/Controls/Dialog.axaml
  WalletWasabi.Fluent/ViewModels/Dialogs/Authorization/HardwareWalletAuthDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/Base/DialogScreenViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/Views/Dialogs/Authorization/HardwareWalletAuthDialogView.axaml
  WalletWasabi.Fluent/Views/MainView.axaml
Labels: size/M

#5320 TransactionProcessorTests: Fix missing disposal of TransactionStore
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
  WalletWasabi/Blockchain/Transactions/TransactionStore.cs
Labels: size/L

#5332 [Trivial] Use block body for constructor
  WalletWasabi/Crypto/Slip21Node.cs
Labels: size/S

#5334 Provide useful info about invalid transactions
  WalletWasabi.Tests/UnitTests/InvalidTxExceptionTests.cs
  WalletWasabi/Exceptions/InvalidTxException.cs
Labels: size/M

#5304 [Fleunt] Transaction confirmation time
  WalletWasabi.Fluent/Helpers/TextHelpers.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/SearchPasswordViewModel.cs
  WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/BroadcastTransactionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionInfo.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
Labels: size/L

#5309 [Fleunt] Send canExecute
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
Labels: size/S

#5337 [Fluent] Make PasswordAuthDialogView's size fixed
  WalletWasabi.Fluent/Views/Dialogs/Authorization/PasswordAuthDialogView.axaml
Labels: size/XS

#5322 Fix spent rbf
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
  WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
  WalletWasabi/Blockchain/Transactions/SmartTransaction.cs
Labels: size/L

#5323 [Fluent] Insufficient balance handling
  WalletWasabi.Fluent/Helpers/TransactionHelpers.cs
  WalletWasabi.Fluent/Model/BalanceType.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/InsufficientBalanceDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/INavigationStack.cs
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationStack.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/Views/Dialogs/InsufficientBalanceDialogView.axaml
  WalletWasabi.Fluent/Views/Dialogs/InsufficientBalanceDialogView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
  WalletWasabi.Fluent/Views/Wallets/WalletView.axaml.cs
Labels: size/L

#5338 [Fluent] Fix password for hw wallets
  WalletWasabi/Wallets/Wallet.cs
Labels: size/XS

#5341 Navigation fixes
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationStack.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Actions/AdvancedWalletActionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Actions/CoinJoinWalletActionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/ClosedWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModelBase.cs
Labels: size/M

#5343 Send Page Titles
  WalletWasabi.Fluent/Views/Wallets/Send/OptimisePrivacyView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/PrivacyControlView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml
Labels: size/XS

#5342 privacy control - pre-select if there is only 1 item.
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
Labels: size/XS

#5336 Mempool-based minimum fee rates 2
  WalletWasabi.Tests/Helpers/MempoolInfoGenerator.cs
  WalletWasabi.Tests/Helpers/RandomExtensions.cs
  WalletWasabi.Tests/UnitTests/AllFeeEstimateTests.cs
  WalletWasabi.Tests/UnitTests/Data/MempoolInfoWithHistogram.json
  WalletWasabi.Tests/WalletWasabi.Tests.csproj
  WalletWasabi/BitcoinCore/Rpc/RpcClientBase.cs
  WalletWasabi/Blockchain/Analysis/FeesEstimation/AllFeeEstimate.cs
  WalletWasabi/Extensions/LinqExtensions.cs
  WalletWasabi/Extensions/RPCClientExtensions.cs
Labels: size/XL

#5340 Eliminated warnings in BlockchainController
  WalletWasabi.Backend/Controllers/BlockchainController.cs
Labels: size/S

#5353 Fix nullability warnings in HwiClient
  WalletWasabi.Tests/UnitTests/Hwi/DefaultResponseTests.cs
  WalletWasabi/Hwi/HwiClient.cs
  WalletWasabi/Hwi/Parsers/HwiParser.cs
Labels: size/M

#5307 TorHttpClient and absolute HTTP requests
  WalletWasabi.Gui/Global.cs
  WalletWasabi/Tor/Http/IHttpClient.cs
  WalletWasabi/Tor/Http/TorHttpClient.cs
  WalletWasabi/WebClients/Wasabi/HttpClientFactory.cs
Labels: size/M

#5354 Fixed logic in BuildOptions in HwiClient.cs
  WalletWasabi/Hwi/HwiClient.cs
Labels: size/XS

#5349 Force wallet rescan after import
  WalletWasabi/Helpers/ImportWalletHelper.cs
Labels: size/XS

#5344 [Fluent] Fix Receive Address back button color
  WalletWasabi.Fluent/Controls/AnimatedButton.axaml
  WalletWasabi.Fluent/Controls/AnimatedButton.axaml.cs
  WalletWasabi.Fluent/Styles/IconButton.axaml
  WalletWasabi.Fluent/Styles/Styles.axaml
  WalletWasabi.Fluent/Views/HelpAndSupport/AboutView.axaml
  WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveAddressView.axaml
  WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveAddressesView.axaml
Labels: size/M

#5345 [Fluent] Clip ContentArea scroll viewer using outer panel
  WalletWasabi.Fluent/Controls/ContentArea.axaml
Labels: size/M

#5348 [Fluent] Restore DataGrid default sorting indicator
  WalletWasabi.Fluent/Styles/DataGrid.axaml
Labels: size/M

#5351 [Fluent] DataGrid hide row selection
  WalletWasabi.Fluent/Styles/DataGrid.axaml
  WalletWasabi.Fluent/Styles/Themes/Base.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/PrivacyControlView.axaml
Labels: size/S

#5352 [Fluent] Fix normal dialog visibility when fullscreen dialog is visible
  WalletWasabi.Fluent/Views/MainView.axaml
Labels: size/S

#5356 Vdg/fix escape button in send process
  WalletWasabi.Fluent/Views/Wallets/Send/OptimisePrivacyView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/PrivacyControlView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml
Labels: size/XS

#5357 Transitive Dialogs for Send / Rx
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/HelpAndSupport/AboutViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/Views/Dialogs/AdvancedRecoveryOptionsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/OptimisePrivacyView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/PrivacyControlView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml
Labels: size/S

#5360 [Fluent] Smooth Send
  WalletWasabi.Fluent/ViewModels/Wallets/Send/OptimisePrivacyViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Send/OptimisePrivacyView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/PrivacyControlView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Labels: size/M

#5339 [Trivial] Fix naming violation
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
Labels: size/XS

#4951 Prepare Deterministic build check for Fluent
  WalletWasabi.Fluent.Generators/WalletWasabi.Fluent.Generators.csproj
  WalletWasabi.Fluent.Generators/packages.lock.json
  azure-pipelines-detbuild.yml
Labels: size/L

#5366 Fix NRE in CoordinatorTests
  WalletWasabi.Tests/UnitTests/Wabisabi/Backend/CoordinatorTests.cs
Labels: size/S

#5184 Change support links
  WalletWasabi.Fluent/ViewModels/HelpAndSupport/AboutViewModel.cs
  WalletWasabi.Gui/Shell/Commands/HelpCommands.cs
  WalletWasabi.Gui/Tabs/AboutViewModel.cs
  WalletWasabi.WindowsInstaller/Product.wxs
Labels: size/XS

#5358 WabiSabi refactoring I
  WalletWasabi/WabiSabi/Backend/Banning/Inmate.cs
  WalletWasabi/WabiSabi/Backend/Models/Bob.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
  WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
  WalletWasabi/WabiSabi/Models/ConnectionConfirmationRequest.cs
  WalletWasabi/WabiSabi/Models/ConnectionConfirmationResponse.cs
  WalletWasabi/WabiSabi/Models/InputRoundSignaturePair.cs
  WalletWasabi/WabiSabi/Models/InputWitnessPair.cs
  WalletWasabi/WabiSabi/Models/InputsRegistrationRequest.cs
  WalletWasabi/WabiSabi/Models/InputsRegistrationResponse.cs
  WalletWasabi/WabiSabi/Models/InputsRemovalRequest.cs
  WalletWasabi/WabiSabi/Models/OutputRegistrationRequest.cs
  WalletWasabi/WabiSabi/Models/OutputRegistrationResponse.cs
  WalletWasabi/WabiSabi/Models/TransactionSignaturesRequest.cs
Labels: size/L

#5379 Backport v1.1.12.5 fix
  WalletWasabi.Packager/Program.cs
  WalletWasabi/TorDaemons/digests.txt
Labels: size/XXL

#5380 Do not delete digest file when packaging
  WalletWasabi.Packager/Program.cs
  WalletWasabi.Tests/UnitTests/Hwi/HwiProcessBridgeMock.cs
Labels: size/S

#5381 Bump version to 1.1.12.5
  WalletWasabi.Backend/wwwroot/index.html
  WalletWasabi/Helpers/Constants.cs
Labels: size/S

#5324 [GitHub] create Issue template with external links
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/general-issue.md
Labels: size/M

#5325 Add log in arena's ActionAsync
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
Labels: size/M

#5384 Fix mnemonic phrase length (GUI only)
  WalletWasabi.Gui/Tabs/WalletManager/RecoverWallets/RecoverWalletViewModel.cs
Labels: size/XS

#5376 Fix anon set calculation at address reuse
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/UnitTests/BlockchainAnalysis/PubKeyReuseAnonScoreTests.cs
  WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs
  WalletWasabi/Blockchain/Keys/HdPubKey.cs
Labels: size/M

#5388 Prevent some duplicated tx processing
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
  WalletWasabi/Wallets/Wallet.cs
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/M

#5391 More node parameters
  WalletWasabi.Tests/Helpers/TestNodeBuilder.cs
  WalletWasabi/BitcoinCore/CoreNode.cs
  WalletWasabi/BitcoinCore/CoreNodeParams.cs
Labels: size/M

#5401 Disable CD build for PR-s
  azure-pipelines-cd.yml
Labels: size/XS

#5404 [Trivial] Fix typos
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
  WalletWasabi.Fluent/ViewModels/Navigation/RoutableViewModel.cs
  WalletWasabi.Tests/UnitTests/AbandonedTasksTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepInputRegistrationTests.cs
  WalletWasabi/Nito/AsyncEx/AbandonedTasks.cs
Labels: size/S

#5408 Remove super noisy logs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/XS

#5410 [Fluent] Source generators small fixes
  WalletWasabi.Fluent.Generators/AutoNotifyGenerator.cs
  WalletWasabi.Fluent.Generators/NavigationMetaDataGenerator.cs
  WalletWasabi.Fluent.Generators/PropertyGenerator.cs
  WalletWasabi.Fluent.Generators/StaticViewLocatorGenerator.cs
  WalletWasabi.Fluent.Generators/WalletWasabi.Fluent.Generators.csproj
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
Labels: size/S

#5390 [Fluent] Fix separator color on light theme
  WalletWasabi.Fluent/Styles/Themes/BaseLight.axaml
Labels: size/XS

#5378 [Fleunt] Fix Optimise Privacy layout
  WalletWasabi.Fluent/Views/Wallets/Send/OptimisePrivacyView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/PrivacySuggestionControl.axaml
Labels: size/S

#5370 [Fleunt] ContentArea title wrap
  WalletWasabi.Fluent/Controls/ContentArea.axaml
Labels: size/XS

#5361 [Fluent] Fix clipping of X axis of line chart
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Labels: size/XS

#5347 [Fluent] Fix move window when dialog screen is open
  WalletWasabi.Fluent/Controls/Dialog.axaml
  WalletWasabi.Fluent/Controls/Dialog.axaml.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/Views/MainView.axaml
Labels: size/M

#5346 [Fluent] Add wallet page first time navigation fixes
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
Labels: size/XS

#5364 [Fluent] Textbox integrated checkmark
  WalletWasabi.Fluent/Styles/TextBox.axaml
  WalletWasabi.Fluent/Validation/CheckMarkStatus.cs
  WalletWasabi.Fluent/Views/AddWallet/Create/ConfirmRecoveryWordsView.axaml
  WalletWasabi.Fluent/Views/Dialogs/AdvancedRecoveryOptionsView.axaml
  WalletWasabi.Fluent/Views/Dialogs/CreatePasswordDialogView.axaml
Labels: size/L

#5385 [Fluent] Send view layout optimization
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Labels: size/XS

#5313 [Fluent] Refactor command execute actions to methods
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/AddedWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/ConfirmRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/RecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/ConnectHardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/DetectedHardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/TermsAndConditionsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/LoginViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/PasswordFinderIntroduceViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/PasswordNotFoundViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Search/SearchItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/BroadcastTransactionViewModel.cs
  WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/LoadTransactionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/ClosedWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/OptimisePrivacyViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
Labels: size/XL

#5411 [Backport v1.1.12.6] Tor install fix
  WalletWasabi.Packager/Program.cs
  WalletWasabi/TorDaemons/digests.txt
  WalletWasabi/TorSocks5/TorProcessManager.cs
Labels: size/S

#5413 [Backport v1.1.12.6] Bump version
  WalletWasabi/Helpers/Constants.cs
Labels: size/XS

#5414 Bump version to v1.1.12.6
  WalletWasabi.Backend/wwwroot/index.html
  WalletWasabi/Helpers/Constants.cs
Labels: size/S

#5415 Bump version to v1.1.12.6
  WalletWasabi.Backend/wwwroot/index.html
Labels: size/XS

#5359 [Fluent] Insufficient balance better ux
  WalletWasabi.Fluent/Controls/QuestionControl.axaml
  WalletWasabi.Fluent/ViewModels/Dialogs/InsufficientBalanceDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/Views/Dialogs/InsufficientBalanceDialogView.axaml
Labels: size/M

#5416 [Fluent] More light theme fixes
  WalletWasabi.Fluent/Styles/Themes/BaseDark.axaml
  WalletWasabi.Fluent/Styles/Themes/BaseLight.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/OptimisePrivacyView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/PrivacySuggestionControl.axaml
Labels: size/XS

#5383 [Fluent] Reselect already selected NavBarListBox item
  WalletWasabi.Fluent/Controls/NavBarListBox.cs
Labels: size/M

#5368 [Fluent] Fix up CurrencyEntryBox
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
Labels: size/M

#5420 [Fluent] fix decimal input issue in currencybox
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
Labels: size/XS

#5419 [Fluent] Dialog min size
  WalletWasabi.Fluent/Controls/Dialog.axaml
  WalletWasabi.Fluent/Views/Dialogs/Authorization/HardwareWalletAuthDialogView.axaml
  WalletWasabi.Fluent/Views/Dialogs/Authorization/PasswordAuthDialogView.axaml
Labels: size/S

#5421 [Fluent] Animated paste button on send page
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Labels: size/S

#5422 Clicking on linchart or slider will accept any label typed but not al…
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Labels: size/XS

#5367 Support taproot script in filters
  WalletWasabi.Tests/UnitTests/BitcoinCore/IndexBuilderServiceTests.cs
  WalletWasabi.Tests/UnitTests/Data/VerboseBlock.json
  WalletWasabi.Tests/WalletWasabi.Tests.csproj
  WalletWasabi/BitcoinCore/Rpc/Models/RpcPubkeyType.cs
  WalletWasabi/BitcoinCore/Rpc/RpcParser.cs
  WalletWasabi/Blockchain/BlockFilters/IndexBuilderService.cs
Labels: size/L

#5425 Wallet: Remove always-true if statement
  WalletWasabi/Wallets/Wallet.cs
Labels: size/XS

#5427 [Trivial] Use expression body for lambda expressions
  WalletWasabi.Fluent/Behaviors/FocusOnAttachedBehavior.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/S

#5403 Wabisabi review ii
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/S

#5432 Wallet & superfluous Nodes
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Tests/IntegrationTests/P2pTests.cs
  WalletWasabi.Tests/RegressionTests/BuildTests.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi.Tests/RegressionTests/WalletTests.cs
  WalletWasabi/Wallets/Wallet.cs
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/M

#5435 Static -2^i * Gh generators
  WalletWasabi.Tests/UnitTests/Crypto/ProofSystemTests.cs
  WalletWasabi/Crypto/Groups/Generators.cs
  WalletWasabi/Crypto/ZeroKnowledge/ProofSystem.cs
Labels: size/M

#5443 Wallet: Remove extra initialization check.
  WalletWasabi/Stores/BitcoinStore.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/S

#5444 IndexStore: Remove extra "IoHelpers.EnsureDirectoryExists(WorkFolderPath);".
  WalletWasabi/Stores/IndexStore.cs
Labels: size/XS

#5436 Add broadcast tx hex to RPC
  WalletWasabi.Gui/Rpc/WasabiJsonRpcService.cs
Labels: size/S

#5445 SafeIoManager: Remove extra "new"
  WalletWasabi/Io/SafeIoManager.cs
Labels: size/XS

#5429 [WabiSabi] API Client
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/AliceTimeoutTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/ConfirmConnectionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputSuccessTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputToBlameRoundTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterOutputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RemoveInputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/SignTransactionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/RequestHandlerDisposeTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/ArenaRequestHandler.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/IArenaRequestHandler.cs
  WalletWasabi/WabiSabi/Client/ArenaClient.cs
  WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
Labels: size/L

#5450 Show BLockHeight in logs
  WalletWasabi/Wallets/P2pBlockProvider.cs
Labels: size/XS

#5458 [Fluent} Send prevent UI freeze
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
Labels: size/XS

#5456 [WabiSabi] Trivial: Remove EncryptedCoinJoin round property for now
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterOutputTests.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
  WalletWasabi/WabiSabi/Models/OutputRegistrationResponse.cs
Labels: size/XS

#5453 [WabiSabi] Only allow standard outputs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterOutputTests.cs
  WalletWasabi/WabiSabi/Backend/Models/WabiSabiProtocolErrorCode.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/ArenaRequestHandler.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/M

#5463 Convert obvious `class` to `record`
  WalletWasabi/Crypto/CoinJoinInputCommitmentData.cs
  WalletWasabi/Crypto/CredentialIssuerParameters.cs
  WalletWasabi/Crypto/CredentialIssuerSecretKey.cs
  WalletWasabi/Crypto/Mac.cs
  WalletWasabi/Crypto/OwnershipIdentifier.cs
  WalletWasabi/Crypto/OwnershipProof.cs
  WalletWasabi/Crypto/ProofBody.cs
  WalletWasabi/Crypto/ProofBodyFlags.cs
  WalletWasabi/Crypto/ZeroKnowledge/Credential.cs
  WalletWasabi/Crypto/ZeroKnowledge/CredentialPresentation.cs
  WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Knowledge.cs
  WalletWasabi/Crypto/ZeroKnowledge/Proof.cs
  WalletWasabi/WabiSabi/Crypto/IssuanceRequest.cs
  WalletWasabi/WabiSabi/Crypto/IssuanceValidationData.cs
Labels: size/L

#5460 [Fluent] Preview item control
  WalletWasabi.Fluent/App.axaml
  WalletWasabi.Fluent/Controls/PreviewItem.axaml
  WalletWasabi.Fluent/Controls/PreviewItem.axaml.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/InsufficientBalanceDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Fluent/Views/Dialogs/InsufficientBalanceDialogView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml
Labels: size/L

#5407 Make timeouts of WW1 coinjoins equally spread across time
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/UnitTests/CoordinatorRoundTests.cs
  WalletWasabi/CoinJoin/Coordinator/Coordinator.cs
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
Labels: size/M

#5468 HwiProcesssBridgeMock refactor
  WalletWasabi.Tests/UnitTests/Hwi/HwiProcessBridgeMock.cs
Labels: size/L

#5434 [Fluent] PW finder intro text font size adjusment
  WalletWasabi.Fluent/Views/Login/PasswordFinder/PasswordFinderIntroduceView.axaml
Labels: size/XS

#5478 [Fluent] Fix text on preview screen
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml
Labels: size/XS

#5477 [Fluent] Send success page
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendSuccessViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Send/SendSuccessView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/SendSuccessView.axaml.cs
Labels: size/M

#5480 Trezor T Kata fix for TestNet
  WalletWasabi.Tests/AcceptanceTests/HwiKatas.cs
Labels: size/S

#5461 [WabiSabi] Add SignTransactionAsync
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi/WabiSabi/Client/ArenaClient.cs
Labels: size/M

#5475 [Fluent] Don't authorize when there is no password
  WalletWasabi.Fluent/ViewModels/Dialogs/Authorization/PasswordAuthDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
Labels: size/M

#5495 Fix backend log message "two rounds"
  WalletWasabi.Backend/Global.cs
Labels: size/XS

#5481 Bump version to v1.1.12.7
  WalletWasabi.Backend/wwwroot/index.html
  WalletWasabi/Helpers/Constants.cs
Labels: size/S

#5484 [Trivial] Fix comments
  WalletWasabi.Tests/AcceptanceTests/HwiKatas.cs
Labels: size/XS
