Repository WalletWasabi/WalletWasabi, pull requests merged in 2021-07, with the labels that each got.

#5970 [Fluent] Status flyout - fix scrollbar visibility
  WalletWasabi.Fluent/Views/StatusBar/StatusBar.axaml
Labels: size/XS

#5964 [WabiSabi] Remove all ulong and use long
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/CredentialDependencyTests.cs
  WalletWasabi/Crypto/Extensions.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
  WalletWasabi/WabiSabi/Client/CredentialDependencies/CredentialDependency.cs
  WalletWasabi/WabiSabi/Client/CredentialDependencies/CredentialEdgeSet.cs
  WalletWasabi/WabiSabi/Client/CredentialDependencies/DependencyGraph.cs
  WalletWasabi/WabiSabi/Crypto/CredentialIssuer.cs
  WalletWasabi/WabiSabi/Crypto/WabiSabiClient.cs
  WalletWasabi/WabiSabi/Models/RoundState.cs
Labels: size/L

#5955 [Fluent] PSBT workflow
  WalletWasabi.Fluent/Helpers/FileDialogHelper.cs
  WalletWasabi.Fluent/Helpers/TransactionHelpers.cs
  WalletWasabi.Fluent/ViewModels/SuccessViewModel.cs
  WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/BroadcastTransactionViewModel.cs
  WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/LoadTransactionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletInfoViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/HardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModelBase.cs
  WalletWasabi.Fluent/Views/Settings/GeneralSettingsTabView.axaml
  WalletWasabi.Fluent/Views/SuccessView.axaml
  WalletWasabi.Fluent/Views/SuccessView.axaml.cs
  WalletWasabi.Fluent/Views/TransactionBroadcasting/SuccessBroadcastTransactionView.axaml
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletInfoView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml
  WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
  WalletWasabi.Gui/UiConfig.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/L

#5983 fix crash in tagsbox control caused by invisible concatenated control.
  WalletWasabi.Fluent/Controls/TagsBox.axaml
Labels: size/M

#5988 [WabiSabi] Remove obsolete `ConfirmConnectionAsync` method
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/AliceClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
  WalletWasabi/WabiSabi/Client/AliceClient.cs
Labels: size/M

#5948 [Trivial] Remove unnecessary suppression
  WalletWasabi.Backend/Program.cs
  WalletWasabi.Packager/Program.cs
  WalletWasabi/Tor/Control/Messages/CircuitStatus/CircStatus.cs
Labels: size/XS

#5984 [Fluent] Fix action center box shadow clipping for items
  WalletWasabi.Fluent/Views/Search/SearchPageView.axaml
Labels: size/S

#5759 [Fluent] Most frequently used labels
  WalletWasabi.Fluent/Controls/TagsBox.axaml
  WalletWasabi.Fluent/Controls/TagsBox.axaml.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/SuggestionLabelViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveView.axaml
Labels: size/L

#5999 [Fluent] Fix `TagsBox` wrapping
  WalletWasabi.Fluent/Controls/TagsBox.axaml
Labels: size/XS

#5998 [Fluent] Wallet settings
  WalletWasabi.Fluent/Styles/SettingsLayout.axaml
  WalletWasabi.Fluent/Styles/Styles.axaml
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletInfoViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletSettingsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/Views/Settings/BitcoinTabSettingsView.axaml
  WalletWasabi.Fluent/Views/Settings/GeneralSettingsTabView.axaml
  WalletWasabi.Fluent/Views/Settings/NetworkSettingsTabView.axaml
  WalletWasabi.Fluent/Views/Settings/PrivacySettingsTabView.axaml
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletInfoView.axaml
  WalletWasabi.Fluent/Views/Wallets/WalletSettingsView.axaml
  WalletWasabi.Fluent/Views/Wallets/WalletSettingsView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
Labels: size/L

#6026 [Fluent] [Trivial] Add RemoveClassAction action
  WalletWasabi.Fluent/Behaviors/RemoveClassAction.cs
Labels: size/M

#5993 Move a part of `TorMonitor` functionality to `TorProcessManager`.
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Tests/IntegrationTests/BlockstreamInfoTests.cs
  WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
  WalletWasabi.Tests/IntegrationTests/TorTests.cs
  WalletWasabi.Tests/UnitTests/Tor/CancellationTokenExtensions.cs
  WalletWasabi.Tests/UnitTests/Tor/Control/TorControlClientTests.cs
  WalletWasabi.Tests/UnitTests/Tor/TorProcessManagerTests.cs
  WalletWasabi/Microservices/ProcessAsync.cs
  WalletWasabi/Tor/Control/TorControlClient.cs
  WalletWasabi/Tor/Control/TorControlReplyReader.cs
  WalletWasabi/Tor/TorMonitor.cs
  WalletWasabi/Tor/TorProcessManager.cs
Labels: size/L

#6027 Do not save `KeyManager` on Wallet Settings opening
  WalletWasabi.Fluent/ViewModels/Wallets/WalletSettingsViewModel.cs
Labels: size/XS

#5982 Fix label show in history for >1 & <100 confirmations
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
Labels: size/M

#6003 [Fluent] New brand colours (light theme only)
  WalletWasabi.Fluent/Controls/NavBarItem.axaml
  WalletWasabi.Fluent/Controls/QuestionControl.axaml
  WalletWasabi.Fluent/Styles/BalanceLineChart.axaml
  WalletWasabi.Fluent/Styles/Button.axaml
  WalletWasabi.Fluent/Styles/Checkmark.axaml
  WalletWasabi.Fluent/Styles/Themes/Base.axaml
  WalletWasabi.Fluent/Styles/Themes/BaseDark.axaml
  WalletWasabi.Fluent/Styles/Themes/BaseLight.axaml
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletPieChartTileViewModel.cs
  WalletWasabi.Fluent/Views/LineChartDemo/SendLineChartView.axaml
  WalletWasabi.Fluent/Views/Login/PasswordFinder/PasswordFoundView.axaml
  WalletWasabi.Fluent/Views/MainView.axaml
  WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceChart/WalletBalanceChartLargeTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceChart/WalletBalanceChartMediumTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceChart/WalletBalanceChartWideTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Labels: size/XXL

#6014 [Fluent] About - Layout fixes
  WalletWasabi.Fluent/Behaviors/RemoveClassAction.cs
  WalletWasabi.Fluent/ViewModels/HelpAndSupport/AboutViewModel.cs
  WalletWasabi.Fluent/ViewModels/HelpAndSupport/LinkViewModel.cs
  WalletWasabi.Fluent/ViewModels/HelpAndSupport/SeparatorViewModel.cs
  WalletWasabi.Fluent/Views/Dialogs/AboutAdvancedInfoView.axaml
  WalletWasabi.Fluent/Views/HelpAndSupport/AboutView.axaml
  WalletWasabi.Fluent/Views/HelpAndSupport/LinkView.axaml
  WalletWasabi.Fluent/Views/HelpAndSupport/LinkView.axaml.cs
Labels: size/L

#6025 [Fluent] Increase minimum window size
  WalletWasabi.Fluent/Views/MainWindow.axaml
Labels: size/XS

#6009 [Fluent] Send - Layout fixes part 1
  WalletWasabi.Fluent/Views/Wallets/Send/OptimisePrivacyView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/PrivacyControlView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/SendSuccessView.axaml
Labels: size/XS

#6010 [Fluent] Dialog to fullwindow on small resolution
  WalletWasabi.Fluent/Controls/Dialog.axaml
  WalletWasabi.Fluent/Controls/Dialog.axaml.cs
  WalletWasabi.Fluent/Styles/Themes/Base.axaml
Labels: size/M

#5943 [Fluent] Send Fee chart resizing / layout
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Labels: size/L

#6005 Feature/separate fee slider page
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendFeeViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Send/SendFeeView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/SendFeeView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Labels: size/XXL

#6028 [Fluent] NavBar - Layout fixes
  WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
Labels: size/S

#6032 [Trivial] Remove leftover field
  WalletWasabi.Gui/UiConfig.cs
Labels: size/XS

#6004 [Fluent] Receive - Layout fixes
  WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveAddressView.axaml
Labels: size/M

#5997 [Fluent] Transaction Broadcaster - Load transaction layout fix
  WalletWasabi.Fluent/Views/TransactionBroadcasting/LoadTransactionView.axaml
Labels: size/M

#6011 [Fluent] Send - line chart labels crossing each other - Layout fixes
  WalletWasabi.Fluent/Views/Wallets/Send/SendFeeView.axaml
Labels: size/M

#5960 Start Wasabi on Windows Startup
  WalletWasabi.Fluent/Helpers/StartupHelper.cs
  WalletWasabi.Fluent/ViewModels/Settings/GeneralSettingsTabViewModel.cs
  WalletWasabi.Fluent/Views/Settings/GeneralSettingsTabView.axaml
  WalletWasabi.Gui/UiConfig.cs
  WalletWasabi.Packager/Program.cs
  WalletWasabi.Tests/UnitTests/StartWasabiOnSystemStartupTests.cs
  WalletWasabi/Helpers/Constants.cs
  WalletWasabi/Helpers/EnvironmentHelpers.cs
Labels: size/L

#6036 TorProcessManager: Do not log exception.
  WalletWasabi/Tor/TorProcessManager.cs
Labels: size/XS

#5977 Add auto coinjoin setting (UI)
  WalletWasabi.Fluent/ViewModels/Wallets/WalletSettingsViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/WalletSettingsView.axaml
  WalletWasabi/Blockchain/Keys/KeyManager.cs
Labels: size/S

#6037 [WabiSabi] Make status requests concurrency safe
  WalletWasabi.Backend/Controllers/WabiSabiController.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/ArenaRequestHandler.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/S

#6045 [Trivial] Remove unused member
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
Labels: size/XS

#6039 [Fluent] Update Avalonia Behaviors package and use new responsive behavior
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/Behaviors/AddClassAction.cs
  WalletWasabi.Fluent/Behaviors/RemoveClassAction.cs
  WalletWasabi.Fluent/Views/HelpAndSupport/AboutView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/SendFeeView.axaml
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
Labels: size/L

#5941 [Fluent] Show labels in transaction history
  WalletWasabi.Fluent/Controls/TagsBox.axaml
  WalletWasabi.Fluent/Styles/Button.axaml
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItemViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
Labels: size/M

#6042 [Fluent] Adjust toggleswitch colors to match accents
  WalletWasabi.Fluent/Styles/Themes/Base.axaml
  WalletWasabi.Fluent/Styles/Themes/BaseDark.axaml
  WalletWasabi.Fluent/Styles/Themes/BaseLight.axaml
Labels: size/S

#6034 [Fluent] Replace icon in theme change view
  WalletWasabi.Fluent/Views/Settings/ThemeChangeView.axaml
Labels: size/M

#6012 [Fluent] Fix Privacy Status
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletPieChartTileViewModel.cs
Labels: size/S

#5677 [Fluent] Trivial Refactoring
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
  WalletWasabi.Fluent/Controls/Dialog.axaml.cs
  WalletWasabi.Fluent/Controls/LineChart.cs
  WalletWasabi.Fluent/Helpers/StraightLineFormula.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/InsufficientBalanceDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacySuggestionControlViewModel.cs
Labels: size/M

#5423 [Fluent] Replace satoshis with sats
  WalletWasabi.Fluent/ViewModels/Dialogs/InsufficientBalanceDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml
Labels: size/XS

#5893 [Fluent] Implement Pie Chart tiles
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletPieChart/WalletPieChartLargeTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletPieChart/WalletPieChartMediumTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletPieChart/WalletPieChartWideTileView.axaml
Labels: size/L

#6046 Remove ConfigureAwait(false) from Tests project
  WalletWasabi.Tests/UnitTests/Clients/WasabiClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/AliceTimeoutTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/ConfirmConnectionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputSuccessTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterOutputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RemoveInputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/SignTransactionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/RoundCreationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
Labels: size/L

#6008 [WabiSabi] Multi client test
  WalletWasabi.Tests/Helpers/HttpClientWrapper.cs
  WalletWasabi.Tests/Helpers/TestNodeBuilder.cs
  WalletWasabi.Tests/UnitTests/MockRpcClient.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/Participant.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiApiApplicationFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi.Tests/WalletWasabi.Tests.csproj
  WalletWasabi/BitcoinCore/CoreNode.cs
  WalletWasabi/BitcoinCore/CoreNodeParams.cs
Labels: size/L

#6041 Start Wasabi on macOS login
  WalletWasabi.Fluent/Helpers/StartupHelper.cs
  WalletWasabi.Fluent/ViewModels/Settings/GeneralSettingsTabViewModel.cs
  WalletWasabi.Packager/MacSignTools.cs
  WalletWasabi.Tests/UnitTests/StartWasabiOnSystemStartupTests.cs
  WalletWasabi/Helpers/Constants.cs
Labels: size/M

#6038 [WabiSabi] Clientside blame round support
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepConnectionConfirmationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepInputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/RoundStateUpdaterTests.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Phase.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
  WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/DependencyGraphTaskScheduler.cs
  WalletWasabi/WabiSabi/Client/WabiSabiHttpApiClient.cs
  WalletWasabi/WabiSabi/Models/RoundState.cs
Labels: size/L

#5996 [Fluent] Add Wallet - Layout fixes
  WalletWasabi.Fluent/Behaviors/DynamicHeightBehavior.cs
  WalletWasabi.Fluent/Views/AddWallet/Create/ConfirmRecoveryWordsView.axaml
  WalletWasabi.Fluent/Views/AddWallet/Create/RecoveryWordsView.axaml
  WalletWasabi.Fluent/Views/AddWallet/HardwareWallet/ConnectHardwareWalletView.axaml
Labels: size/M

#6087 [WabiSabi] Calculate AliceId without using backend class
  WalletWasabi/WabiSabi/Backend/Models/Alice.cs
  WalletWasabi/WabiSabi/Client/AliceClient.cs
Labels: size/S

#6096 Remove offending line
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendFeeViewModel.cs
Labels: size/XS

#6097 [Fluent] [Trivial] Fix SendFeeViewModel
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendFeeViewModel.cs
Labels: size/XS

#6075 [WabiSabi] Better wallet distribution for multi-client CJ test
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/Participant.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
Labels: size/M

#6099 [Fluent] Send - fix tab key navigation
  WalletWasabi.Fluent/Controls/ContentArea.axaml
  WalletWasabi.Fluent/Controls/TagsBox.axaml.cs
Labels: size/M

#6098 [Trivial] Remove unnecessary suppression + fix typos
  WalletWasabi.Fluent/Views/Login/PasswordFinder/ContainsNumbersView.axaml
  WalletWasabi.Fluent/Views/Login/PasswordFinder/ContainsSymbolsView.axaml
  WalletWasabi.Tests/TestableRpcService.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
Labels: size/S

#6088 [WabiSabi] Round property for Alice
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/AliceTimeoutTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepConnectionConfirmationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepInputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/ConfirmConnectionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputSuccessTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputToBlameRoundTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterOutputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RemoveInputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/SignTransactionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/RoundCreationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/MultipartyTransactionTests.cs
  WalletWasabi/WabiSabi/Backend/Models/Alice.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/InputRegistrationHandler.cs
Labels: size/L

#6093 [WabiSabi] Wait or detect connection confirmation
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/AliceClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
  WalletWasabi/WabiSabi/Client/AliceClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/DependencyGraphTaskScheduler.cs
  WalletWasabi/WabiSabi/Client/SmartRequestNode.cs
Labels: size/M

#6086 [WabiSabi] Make CredentialIssuer concurrency safe
  WalletWasabi/WabiSabi/Crypto/CredentialIssuer.cs
Labels: size/L

#6103 [WabiSabi] Pass cancellationToken down
  WalletWasabi.Tests/Helpers/ArenaRequestHandlerAdapter.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/ArenaRequestHandler.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/InputRegistrationHandler.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/M

#6110 `RoundStateUpdater`: Simplify
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/RoundStateUpdaterTests.cs
  WalletWasabi/WabiSabi/Client/RoundStateUpdater.cs
Labels: size/S

#6111 [WabiSabi] Disable ASP.NET logs in tests
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiApiApplicationFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
Labels: size/XS

#6109 [Fluent] fix dialog overlay issue
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
Labels: size/S

#5942 [Fluent] New empty wallet home screen placeholders
  WalletWasabi.Fluent/Converters/BoolConverters.cs
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/Styles/Label.axaml
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTablePlaceholder.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTablePlaceholder.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Home/WalletTiles.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/WalletTiles.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Home/WalletTilesPlaceholder.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/WalletTilesPlaceholder.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
Labels: size/L

#6040 [Fluent] History table - Layout fixes
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
Labels: size/L

#6119 [Fluent] Clear compact dialog navigation stack too
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
Labels: size/XS

#6095 [Fluent] Privacy mode
  WalletWasabi.Fluent/App.axaml
  WalletWasabi.Fluent/Controls/PrivacyContentControl.axaml
  WalletWasabi.Fluent/Controls/PrivacyContentControl.axaml.cs
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/ViewModels/Settings/PrivacyModeViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletInfoView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/TransactionDetailsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalance/WalletBalanceLargeTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalance/WalletBalanceMediumTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalance/WalletBalanceWideTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceChart/WalletBalanceChartLargeTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceChart/WalletBalanceChartMediumTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceChart/WalletBalanceChartWideTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletPieChart/WalletPieChartLargeTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletPieChart/WalletPieChartMediumTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletPieChart/WalletPieChartWideTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveAddressView.axaml
  WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveAddressesView.axaml
  WalletWasabi.Gui/UiConfig.cs
Labels: size/XL

#5934 [Fluent] If Backend is down
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/Models/StatusBarState.cs
  WalletWasabi.Fluent/ViewModels/Login/LoginViewModel.cs
  WalletWasabi.Fluent/ViewModels/StatusBar/StatusBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/ClosedHardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/ClosedWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/ClosedWatchOnlyWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/LoadingControlViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/LoadingViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/Views/StatusBar/StatusBar.axaml
  WalletWasabi.Fluent/Views/Wallets/LoadingControl.axaml
Labels: size/L

#6122 consistent cancelling of send and receive dialog.
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendFeeViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Labels: size/S

#6089 [Fluent] Colour rebrand redux
  WalletWasabi.Fluent/Controls/TagControl.axaml
  WalletWasabi.Fluent/Controls/TileButton.axaml
  WalletWasabi.Fluent/Styles/Themes/Base.axaml
  WalletWasabi.Fluent/Styles/Themes/BaseDark.axaml
  WalletWasabi.Fluent/Styles/Themes/BaseLight.axaml
  WalletWasabi.Fluent/Views/StatusBar/StatusBar.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/SendFeeView.axaml
Labels: size/L

#6115 [Fluent] Fix multiple dialog closing
  WalletWasabi.Fluent/Controls/Dialog.axaml.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/RoutableViewModel.cs
  WalletWasabi.Fluent/Views/MainView.axaml
Labels: size/M

#6123 [Fluent] do not allow to click through on the compact dialog's overlay
  WalletWasabi.Fluent/Controls/ContentArea.axaml
Labels: size/XS
