Repository WalletWasabi/WalletWasabi, pull requests merged in 2021-04, with the labels that each got.

#5499 change preview item emphasis
  WalletWasabi.Fluent/Controls/PreviewItem.axaml
Labels: size/M

#5497 Improve Optimise Privacy Screen
  WalletWasabi.Fluent/Converters/PrivacyOptimisationLevelConverters.cs
  WalletWasabi.Fluent/Helpers/TextHelpers.cs
  WalletWasabi.Fluent/Styles/Themes/Base.axaml
  WalletWasabi.Fluent/ViewModels/Dialogs/InsufficientBalanceDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/OptimisePrivacyViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacySuggestionControlViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Fluent/Views/Dialogs/InsufficientBalanceDialogView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/OptimisePrivacyView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/PrivacySuggestionControl.axaml
Labels: size/M

#5506 checkboxes not keyboard focusable on privacy control screen. allows e…
  WalletWasabi.Fluent/Views/Wallets/Send/PrivacyControlView.axaml
Labels: size/XS

#5469 [Fluent] Send view fee chart updates
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Labels: size/XS

#5510 [Backport] Fix recovery recovery word bug
  WalletWasabi.Gui/Tabs/WalletManager/RecoverWallets/RecoverWalletViewModel.cs
Labels: size/XS

#5511 Inject `CredentialPool`
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi/WabiSabi/Crypto/WabiSabiClient.cs
Labels: size/S

#5513 Bump client version to v1.1.12.8
  WalletWasabi.Backend/wwwroot/index.html
  WalletWasabi/Helpers/Constants.cs
Labels: size/S

#5517 [Fluent] Fix SendViewModel.cs label sources
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
Labels: size/S

#5520 [WabiSabi] `ArenaClient` creates `WabiSabiClient`s
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi/WabiSabi/Client/ArenaClient.cs
Labels: size/M

#5508 Autorescan wallets when internal data structure corrups.
  WalletWasabi.Gui/Global.cs
Labels: size/S

#5516 Fluent: SendUX - Tidy and fix Privacy Control
  WalletWasabi.Fluent/Styles/Themes/Base.axaml
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Send/PrivacyControlView.axaml
Labels: size/S

#5518 [Fluent] Send auto paste
  WalletWasabi.Fluent/Behaviors/ExecuteCommandOnClickBehavior.cs
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Labels: size/M

#5393 Tor pool feature
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
  WalletWasabi.Tests/IntegrationTests/TorTests.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/UnitTests/Tor/Socks5/TorHttpPoolTests.cs
  WalletWasabi.Tests/UnitTests/Tor/Socks5/TorTcpConnectionFactoryTests.cs
  WalletWasabi.Tests/XunitConfiguration/LiveServerTestsFixture.cs
  WalletWasabi/Blockchain/Blocks/SmartHeader.cs
  WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs
  WalletWasabi/CoinJoin/Client/Clients/AliceClientBase.cs
  WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
  WalletWasabi/CoinJoin/Client/Rounds/ClientRound.cs
  WalletWasabi/CoinJoin/Client/Rounds/ClientRoundRegistration.cs
  WalletWasabi/CoinJoin/Client/Rounds/ClientState.cs
  WalletWasabi/Tor/Http/ClearnetHttpClient.cs
  WalletWasabi/Tor/Http/IHttpClient.cs
  WalletWasabi/Tor/Http/TorHttpClient.cs
  WalletWasabi/Tor/Socks5/Exceptions/TorConnectionWriteException.cs
  WalletWasabi/Tor/Socks5/Pool/TorHttpPool.cs
  WalletWasabi/Tor/Socks5/TorTcpConnection.cs
  WalletWasabi/Tor/Socks5/TorTcpConnectionFactory.cs
  WalletWasabi/Tor/TorMonitor.cs
  WalletWasabi/Tor/TorProcessManager.cs
  WalletWasabi/Wallets/WalletDirectories.cs
  WalletWasabi/WebClients/Wasabi/HttpClientFactory.cs
Labels: size/XXL

#5521 [Fluent] Fix send view graph text out of bounds
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Labels: size/XS

#5519 [WabiSabi] Fix NRE in WabiSabi ConfigTests
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/ConfigTests.cs
Labels: size/S

#5535 Vdg/fix privacy optimisation
  WalletWasabi.Fluent/Helpers/TextHelpers.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/OptimisePrivacyViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacySuggestionControlViewModel.cs
Labels: size/M

#5507 [Fluent] Show selected pocket labels too on the preview screen
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PocketViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionInfo.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
Labels: size/M

#5537 Don't have a problem for OperationCancelledException
  WalletWasabi.Gui/Global.cs
Labels: size/XS

#5527 Bring out property check to the constructor
  WalletWasabi.Tests/UnitTests/Hwi/DefaultResponseTests.cs
  WalletWasabi.Tests/UnitTests/Tor/Socks5/TorHttpPoolTests.cs
  WalletWasabi/Tor/Socks5/TorTcpConnectionFactory.cs
Labels: size/S

#5532 [WabiSabi] `CredentialClient` methods return record type
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi/WabiSabi/Client/ArenaClient.cs
  WalletWasabi/WabiSabi/Crypto/CredentialRequesting/CredentialsResponseValidation.cs
  WalletWasabi/WabiSabi/Crypto/CredentialRequesting/RealCredentialsRequestData.cs
  WalletWasabi/WabiSabi/Crypto/CredentialRequesting/ZeroCredentialsRequestData.cs
  WalletWasabi/WabiSabi/Crypto/WabiSabiClient.cs
Labels: size/M

#5539 Fix RegTest
  WalletWasabi.Gui/Global.cs
Labels: size/XS

#5538 [Trivial] Fix summary comment
  WalletWasabi.Tests/UnitTests/Microservices/ProcessAsyncTest.cs
Labels: size/XS

#5540 [Fluent] Add delay for EnableCancelOnPressed dialog feature
  WalletWasabi.Fluent/Controls/Dialog.axaml.cs
Labels: size/M

#5542 [Fluent] Add multiple recovery words limit from Gui project
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/RecoverWalletView.axaml
Labels: size/XS

#5528 The estimation fee doesnt show anymore in Regtest
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
  WalletWasabi/Extensions/RPCClientExtensions.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/S

#5509 [WabiSabi] Arena client methods
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi/Helpers/Constants.cs
  WalletWasabi/Helpers/Guard.cs
  WalletWasabi/WabiSabi/Backend/Models/Alice.cs
  WalletWasabi/WabiSabi/Backend/Models/Bob.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/InputRegistrationHandler.cs
  WalletWasabi/WabiSabi/Client/ArenaClient.cs
  WalletWasabi/WabiSabi/Crypto/WabiSabiClient.cs
Labels: size/L

#5548 Fix tests
  WalletWasabi/Extensions/RPCClientExtensions.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/XS

#5536 Make TagsBox suggestions case insensitive.
  WalletWasabi.Fluent/Controls/TagsBox.axaml.cs
Labels: size/XS

#5471 [Fluent] PayJoin
  WalletWasabi.Fluent/Helpers/TransactionHelpers.cs
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionInfo.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml
Labels: size/L

#5546 SendUX: dont show cancel buttons until we get to the end.
  WalletWasabi.Fluent/ViewModels/Wallets/Send/OptimisePrivacyViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Send/OptimisePrivacyView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/PrivacyControlView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Labels: size/XS

#5549 Vdg/fluent privacy control warning message tidy
  WalletWasabi.Fluent/Controls/InfoMessage.axaml
  WalletWasabi.Fluent/Styles/Themes/BaseDark.axaml
  WalletWasabi.Fluent/Styles/Themes/BaseLight.axaml
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PocketViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Send/PrivacyControlView.axaml
Labels: size/L

#5424 [Fluent] Make wallet actions horizontal
  WalletWasabi.Fluent/Converters/NavBarActionsOrientationConverter.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Actions/AdvancedWalletActionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Actions/CoinJoinWalletActionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
Labels: size/L

#5550 Update index.html
  WalletWasabi.Backend/wwwroot/index.html
Labels: size/S

#5552 Fix XxAsync and SsAsync tests
  WalletWasabi.Tests/UnitTests/CoordinatorRoundTests.cs
Labels: size/S

#5558 Update README.md
  README.md
Labels: size/M

#5547 Improve block parsing
  WalletWasabi.Tests/UnitTests/BitcoinCore/IndexBuilderServiceTests.cs
  WalletWasabi.Tests/UnitTests/BitcoinCore/RpcBasedTests.cs
  WalletWasabi/BitcoinCore/Rpc/Models/TransactionBlockInfo.cs
  WalletWasabi/BitcoinCore/Rpc/Models/VerboseInputInfo.cs
  WalletWasabi/BitcoinCore/Rpc/Models/VerboseOutputInfo.cs
  WalletWasabi/BitcoinCore/Rpc/Models/VerboseTransactionInfo.cs
  WalletWasabi/BitcoinCore/Rpc/RpcClientBase.cs
  WalletWasabi/BitcoinCore/Rpc/RpcParser.cs
Labels: size/L

#5560 [Fluent] ResponsivePanel control for wallet home page tiles
  WalletWasabi.Fluent/Controls/ResponsivePanel.cs
  WalletWasabi.Fluent/Views/ResponsivePanelDemo/ResponsivePanelDemoView.axaml
  WalletWasabi.Fluent/Views/ResponsivePanelDemo/ResponsivePanelDemoView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
Labels: size/L

#5563 [Fluent] [Trivial] Format ResponsivePanel code
  WalletWasabi.Fluent/Controls/ResponsivePanel.cs
Labels: size/L

#5554 [Fluent] Transaction History
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WatchOnlyWallet/WatchOnlyWalletViewModel.cs
  WalletWasabi.Fluent/Views/ResponsivePanelDemo/ResponsivePanelDemoView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
Labels: size/L

#5564 Vdg/fluent home screen tiles
  WalletWasabi.Fluent/Controls/RingChartControl.cs
  WalletWasabi.Fluent/Converters/ColorStringConverters.cs
  WalletWasabi.Fluent/Converters/MoneyConverters.cs
  WalletWasabi.Fluent/ViewModels/LineChartDemo/XYLineChartViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletBalanceTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletPieChartTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceChartTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceChartTileView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceChartTileViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceTileView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletPieChartTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletPieChartTileView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
Labels: size/XL

#5504 [WabiSabi] Split `CredentialIssuer.HandleRequest` into two phases
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/ConfirmConnectionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/CredentialTests.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/InputRegistrationHandler.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Crypto/CredentialIssuer.cs
Labels: size/L

#5553 fix invalid text showing on the fee slider.
  WalletWasabi.Gui/Converters/FeeTargetTimeConverter.cs
  WalletWasabi/Helpers/Constants.cs
Labels: size/S

#5572 Use better names for UTs
  WalletWasabi.Tests/UnitTests/CoordinatorRoundTests.cs
Labels: size/XS

#5562 [Fluent] Do not store default labels
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionInfo.cs
Labels: size/S

#5565 [Fluent] Responsive panel update
  WalletWasabi.Fluent/Controls/ResponsivePanel.cs
  WalletWasabi.Fluent/Views/ResponsivePanelDemo/ResponsivePanelDemoView.axaml
  WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
Labels: size/M

#5569 [Fluent] Transaction History - store CJ filter in the UiConfig
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Gui/UiConfig.cs
Labels: size/S

#5575 [Fluent] [Trivial] Fix naming rule violation in ResponsivePanel
  WalletWasabi.Fluent/Controls/ResponsivePanel.cs
Labels: size/XS

#5544 [WabiSabi] Add AliceClient
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/AliceClientTests.cs
  WalletWasabi/WabiSabi/Client/AliceClient.cs
  WalletWasabi/WabiSabi/Client/ArenaClient.cs
Labels: size/L

#5534 [WabiSabi] Model for transaction state
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/MultipartyTransactionTests.cs
  WalletWasabi/WabiSabi/Backend/Models/WabiSabiProtocolErrorCode.cs
  WalletWasabi/WabiSabi/Models/MoneyRange.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/ConstructionState.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/IState.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/IStateExtensions.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/MultipartyTransactionParameters.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/SigningState.cs
Labels: size/XL

#5579 [WabiSabi] Fix inputRemainingWeights in AliceClient
  WalletWasabi/WabiSabi/Client/AliceClient.cs
Labels: size/XS

#5586 Remove unused class
  WalletWasabi/Backend/Models/Requests/BroadcastRequest.cs
Labels: size/S

#5573 [WabiSabi] Remove delegate from `CredentialIssuer`
  WalletWasabi/WabiSabi/Backend/PostRequests/InputRegistrationHandler.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Crypto/CredentialIssuer.cs
  WalletWasabi/WabiSabi/Crypto/ICommitableCredentialsResponse.cs
Labels: size/M

#5581 [WabiSabi] Inject CredentialPool into ArenaClient
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/AliceClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi/WabiSabi/Client/ArenaClient.cs
Labels: size/M

#5578 [Fluent] Transaction history update
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/TransactionDetailsViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/TransactionDetailsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/TransactionDetailsView.axaml.cs
Labels: size/L

#5588 [Fluent] [LineChart] Fix YAxisLabels rendering order
  WalletWasabi.Fluent/Controls/LineChart.cs
Labels: size/XS

#5587 VDG Homescreen - Balance / Balance Chart
  WalletWasabi.Fluent/Controls/ContentArea.axaml
  WalletWasabi.Fluent/Controls/LineChart.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/TileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletBalanceChartTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletBalanceTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletPieChartTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/Views/MainView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceChartTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceChartTileViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletPieChartTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
  WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
Labels: size/L

#5576 [Fluent] ResponsivePanel scroll support
  WalletWasabi.Fluent/Controls/ResponsivePanel.cs
  WalletWasabi.Fluent/Converters/ColumnHintsConverter.cs
  WalletWasabi.Fluent/Converters/WidthTriggersConverter.cs
  WalletWasabi.Fluent/Styles/SplitView.axaml
  WalletWasabi.Fluent/ViewModels/ResponsivePanelDemo/ResponsivePanelDemoViewModel.cs
  WalletWasabi.Fluent/Views/ResponsivePanelDemo/ResponsivePanelDemoView.axaml
  WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
Labels: size/L

#5590 [Fluent] Transaction details update
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/TransactionDetailsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/TransactionDetailsView.axaml
Labels: size/L

#5551 [WabiSabi] Constrain registration vsize
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputSuccessTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RemoveInputTests.cs
  WalletWasabi/WabiSabi/Backend/Models/WabiSabiProtocolErrorCode.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/InputRegistrationHandler.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
  WalletWasabi/WabiSabi/Backend/Rounds/RoundParameters.cs
  WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
Labels: size/M

#5577 [WabiSabi] Add BobClient
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/AliceClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
  WalletWasabi/WabiSabi/Client/BobClient.cs
Labels: size/L

#5600 [WabiSabi ]Fix typo in Alice
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepConnectionConfirmationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/ConfirmConnectionTests.cs
  WalletWasabi/WabiSabi/Backend/Models/Alice.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/M

#5603 Improve HostedServices
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
  WalletWasabi.Tests/RegressionTests/BackendTests.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/UnitTests/BitcoinCore/P2pBasedTests.cs
  WalletWasabi/BitcoinCore/CoreNode.cs
  WalletWasabi/Services/HostedServices.cs
Labels: size/M

#5594 [WabiSabi] Replace `weight` with `vsize`
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/ConfirmConnectionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputSuccessTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterOutputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/AliceClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
  WalletWasabi/Extensions/NBitcoinExtensions.cs
  WalletWasabi/Helpers/Constants.cs
  WalletWasabi/WabiSabi/Backend/Models/Alice.cs
  WalletWasabi/WabiSabi/Backend/Models/Bob.cs
  WalletWasabi/WabiSabi/Backend/Models/WabiSabiProtocolErrorCode.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/ArenaRequestHandler.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/InputRegistrationHandler.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
  WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
  WalletWasabi/WabiSabi/Client/AliceClient.cs
  WalletWasabi/WabiSabi/Client/ArenaClient.cs
  WalletWasabi/WabiSabi/Client/BobClient.cs
  WalletWasabi/WabiSabi/Models/ConnectionConfirmationRequest.cs
  WalletWasabi/WabiSabi/Models/ConnectionConfirmationResponse.cs
  WalletWasabi/WabiSabi/Models/InputsRegistrationRequest.cs
  WalletWasabi/WabiSabi/Models/InputsRegistrationResponse.cs
  WalletWasabi/WabiSabi/Models/OutputRegistrationRequest.cs
  WalletWasabi/WabiSabi/Models/OutputRegistrationResponse.cs
  WalletWasabi/WabiSabi/ProtocolContants.cs
Labels: size/XL

#5597 [WabiSabi] Simplify `RemoveDuplicatedAlices` method
  WalletWasabi/WabiSabi/Backend/PostRequests/InputRegistrationHandler.cs
Labels: size/S

#5607 Take out hosted services registration from core node
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Tests/Helpers/TestNodeBuilder.cs
  WalletWasabi.Tests/UnitTests/BitcoinCore/NodeBuildingTests.cs
  WalletWasabi.Tests/UnitTests/BitcoinCore/P2pBasedTests.cs
  WalletWasabi.Tests/UnitTests/BitcoinCore/RpcBasedTests.cs
  WalletWasabi.Tests/XunitConfiguration/RegTestFixture.cs
  WalletWasabi/BitcoinCore/CoreNode.cs
  WalletWasabi/BitcoinCore/CoreNodeParams.cs
Labels: size/M

#5596 [WabiSabi] Fix NRE in UTs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/ConfigTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/CoordinatorTests.cs
Labels: size/XS

#5606 Improve fee providing logic when full node
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Tests/IntegrationTests/P2pTests.cs
  WalletWasabi.Tests/RegressionTests/BuildTests.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi.Tests/RegressionTests/WalletTests.cs
  WalletWasabi/BitcoinCore/Monitoring/RpcFeeProvider.cs
  WalletWasabi/Blockchain/Analysis/FeesEstimation/AllFeeEstimate.cs
  WalletWasabi/Blockchain/Analysis/FeesEstimation/FeeProviders.cs
  WalletWasabi/Blockchain/Analysis/FeesEstimation/HybridFeeProvider.cs
  WalletWasabi/Blockchain/Analysis/FeesEstimation/IFeeProvider.cs
  WalletWasabi/Services/WasabiSynchronizer.cs
  WalletWasabi/Wallets/Wallet.cs
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/L

#5610 [WabiSabi] Missing weight renaming
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/ConfirmConnectionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RemoveInputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi/WabiSabi/Backend/Models/WabiSabiProtocolErrorCode.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/InputRegistrationHandler.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Client/ArenaClient.cs
Labels: size/M

#5614 Further lean down Synchronizer
  WalletWasabi/Backend/Models/Responses/SynchronizeResponse.cs
  WalletWasabi/Blockchain/Analysis/FeesEstimation/HybridFeeProvider.cs
  WalletWasabi/Services/WasabiSynchronizer.cs
Labels: size/S

#5609 Adjust impossible exception messages
  WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
  WalletWasabi.Gui/Controls/WalletExplorer/CoinViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
  WalletWasabi/Blockchain/TransactionBuilding/PaymentIntent.cs
  WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/Masking/PatternFactory.cs
  WalletWasabi/Services/SingleInstanceChecker.cs
Labels: size/S

#5620 [Trivial] Modify impossibru log message
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
Labels: size/XS

#5624 Fix backend micro unresponsiveness
  WalletWasabi.Backend/Controllers/BatchController.cs
  WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
  WalletWasabi/CoinJoin/Coordinator/Coordinator.cs
Labels: size/M

#5617 Take filter creation out of synchronizer
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Gui/Rpc/WasabiJsonRpcService.cs
  WalletWasabi.Tests/IntegrationTests/P2pTests.cs
  WalletWasabi.Tests/RegressionTests/BackendTests.cs
  WalletWasabi.Tests/RegressionTests/BuildTests.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/RegressionTests/DosTests.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi.Tests/RegressionTests/WalletTests.cs
  WalletWasabi.Tests/UnitTests/BitcoinCore/P2pBasedTests.cs
  WalletWasabi.Tests/UnitTests/BitcoinCore/RpcBasedTests.cs
  WalletWasabi.Tests/XunitConfiguration/RegTestFixture.cs
  WalletWasabi/BitcoinCore/Monitoring/RpcFeeProvider.cs
  WalletWasabi/BitcoinCore/Monitoring/RpcMonitor.cs
  WalletWasabi/Blockchain/Analysis/FeesEstimation/HybridFeeProvider.cs
  WalletWasabi/Blockchain/BlockFilters/FilterProcessor.cs
  WalletWasabi/Blockchain/Blocks/SmartHeaderChain.cs
  WalletWasabi/CoinJoin/Client/CoinJoinProcessor.cs
  WalletWasabi/Services/WasabiSynchronizer.cs
Labels: size/XL

#5601 [WabiSabi] Add Reissuance Request
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi/WabiSabi/Backend/Models/WabiSabiProtocolErrorCode.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/ArenaRequestHandler.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/IArenaRequestHandler.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Client/ArenaClient.cs
  WalletWasabi/WabiSabi/Crypto/WabiSabiClient.cs
  WalletWasabi/WabiSabi/Models/ReissueCredentialRequest.cs
  WalletWasabi/WabiSabi/Models/ReissueCredentialResponse.cs
Labels: size/L

#5589 [WabiSabi] Minor refactorings ii
  WalletWasabi/WabiSabi/Client/AliceClient.cs
Labels: size/XS

#5649 Nitpick on Tor stuff
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
  WalletWasabi.Tests/IntegrationTests/TorTests.cs
  WalletWasabi/Tor/TorMonitor.cs
  WalletWasabi/Tor/TorProcessManager.cs
  WalletWasabi/Tor/TorSettings.cs
Labels: size/M

#5650 Remove EnsureContainingDirectoryExists because it's the responsibility of someone else.
  WalletWasabi/Tor/TorProcessManager.cs
Labels: size/XS

#5651 Update NuGet packages
  WalletWasabi.Backend/WalletWasabi.Backend.csproj
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/packages.lock.json
  WalletWasabi.Gui/packages.lock.json
  WalletWasabi.Packager/packages.lock.json
  WalletWasabi.Tests/WalletWasabi.Tests.csproj
  WalletWasabi/WalletWasabi.csproj
  WalletWasabi/packages.lock.json
Labels: size/L

#5648 [WabiSabi] Fix range proof tests in Release builds
  WalletWasabi.Tests/UnitTests/Crypto/ProofSystemTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/KnowledgeOfRepTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/LinearRelationTests.cs
  WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Equation.cs
  WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Knowledge.cs
Labels: size/M

#5654 [Fluent] update to new 0.10.1 stable avalonia release.
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
Labels: size/L

#5531 [WabiSabi] Integrate tx state model into Arena code
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterOutputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/SignTransactionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/InputRegistrationHandler.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/ConstructionState.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/SigningState.cs
Labels: size/L

#5658 Improve tests
  WalletWasabi.Tests/UnitTests/BitcoinCore/P2pBasedTests.cs
Labels: size/XS

#5659 Simplify MempoolNotifiesAsync
  WalletWasabi.Tests/UnitTests/BitcoinCore/P2pBasedTests.cs
Labels: size/S

#5652 Make deleting multiple branches at once possible
  WalletWasabi.Documentation/WasabikaCodex.md
Labels: size/XS

#5660 Update WasabikaCodex.md
  WalletWasabi.Documentation/WasabikaCodex.md
Labels: size/XS

#5661 Bump Linux CI from Ubuntu 16.04 to 20.04.
  azure-pipelines-linux.yml
Labels: size/XS

#5662 Abstract away the Bitcoin P2P Network from the Global
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/BitcoinTabSettingsViewModel.cs
  WalletWasabi.Gui/Config.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Gui/Program.cs
  WalletWasabi.Gui/Rpc/WasabiJsonRpcService.cs
  WalletWasabi.Gui/Tabs/SettingsViewModel.cs
  WalletWasabi/BitcoinP2p/P2pNetwork.cs
Labels: size/L

#5644 [Fluent] Add copy button to `PreviewItem`
  WalletWasabi.Fluent/Controls/PreviewItem.axaml
  WalletWasabi.Fluent/Controls/PreviewItem.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/TransactionDetailsView.axaml
Labels: size/L

#5656 [WabiSabi] Allow only one input per alice for now
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/AliceTimeoutTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepInputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputSuccessTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputToBlameRoundTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterOutputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/SignTransactionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/AliceClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/MultipartyTransactionTests.cs
  WalletWasabi/WabiSabi/Backend/Banning/Prison.cs
  WalletWasabi/WabiSabi/Backend/Models/Alice.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/ArenaRequestHandler.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/IArenaRequestHandler.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/InputRegistrationHandler.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
  WalletWasabi/WabiSabi/Backend/Rounds/RoundParameters.cs
  WalletWasabi/WabiSabi/Client/AliceClient.cs
  WalletWasabi/WabiSabi/Client/ArenaClient.cs
  WalletWasabi/WabiSabi/Models/InputRegistrationRequest.cs
  WalletWasabi/WabiSabi/Models/InputRegistrationResponse.cs
  WalletWasabi/WabiSabi/Models/InputRoundSignaturePair.cs
Labels: size/XL

#5665 Refactoring
  WalletWasabi/BitcoinCore/P2pNode.cs
  WalletWasabi/BitcoinP2p/P2pBehavior.cs
  WalletWasabi/BitcoinP2p/TrustedP2pBehavior.cs
  WalletWasabi/BitcoinP2p/UntrustedP2pBehavior.cs
  WalletWasabi/Exceptions/NotSupportedNetworkException.cs
  WalletWasabi/Stores/BitcoinStore.cs
  WalletWasabi/Wallets/P2pBlockProvider.cs
Labels: size/S

#5666 Nullability fixes
  WalletWasabi/Bases/NotifyPropertyChangedBase.cs
  WalletWasabi/Nito/AsyncEx/IAsyncWaitQueue.cs
Labels: size/XS

#5664 [Fluent] Fix formatting
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
  WalletWasabi.Fluent/Controls/LineChart.cs
  WalletWasabi.Fluent/Controls/ProgressRingArc.axaml.cs
  WalletWasabi.Fluent/Controls/ResponsivePanel.cs
  WalletWasabi.Fluent/Controls/RingChartControl.cs
  WalletWasabi.Fluent/Controls/TagsBox.axaml.cs
  WalletWasabi.Fluent/Converters/WalletIconConverter.cs
  WalletWasabi.Fluent/MathNet/CubicSpline.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/CreatePasswordDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/SearchPasswordViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/SelectCharsetViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationManager.cs
  WalletWasabi.Fluent/ViewModels/Search/SearchPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/GeneralSettingsTabViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/SettingsTabViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/LoadTransactionViewModel.cs
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/ClosedWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/TransactionDetailsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletBalanceChartTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/OptimisePrivacyViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModelBase.cs
Labels: size/XXL

#5667 [Fluent] [Trivial] Set SelectedWallet after it is added to SelectedWallets collection
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
Labels: size/XS

#5669 Fix warnings
  .editorconfig
  Settings.StyleCop
  WalletWasabi.Fluent.Generators/AutoNotifyGenerator.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Tests/RegressionTests/BuildTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/GroupElements/GeneratorTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/CredentialTests.cs
  WalletWasabi/Blockchain/TransactionBuilding/BuildTransactionResult.cs
  WalletWasabi/Blockchain/TransactionBuilding/DestinationRequest.cs
  WalletWasabi/Blockchain/TransactionBuilding/FeeStrategy.cs
  WalletWasabi/Blockchain/TransactionBuilding/MoneyRequest.cs
  WalletWasabi/Blockchain/TransactionBuilding/PaymentIntent.cs
  WalletWasabi/Blockchain/TransactionBuilding/SmartCoinSelector.cs
  WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs
  WalletWasabi/Blockchain/Transactions/AllTransactionStore.cs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
  WalletWasabi/Blockchain/Transactions/TransactionStore.cs
  WalletWasabi/CoinJoin/Client/Clients/BobClient.cs
  WalletWasabi/CoinJoin/Coordinator/MixingLevels/MixingLevelCollection.cs
  WalletWasabi/Crypto/Groups/Generators.cs
  WalletWasabi/Crypto/Groups/GroupElement.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/EncodingRegion/FormatInformation.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/ReedSolomon/Polynomial.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/Versions/QRCodeVersion.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/L

#5623 [Fluent] Separate cancel options
  WalletWasabi.Fluent/Controls/Dialog.axaml.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/AddedWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/ConfirmRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/RecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/ConnectHardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/DetectedHardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/LegalDocumentsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/TermsAndConditionsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/AboutAdvancedInfoViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/AdvancedRecoveryOptionsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/Authorization/HardwareWalletAuthDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/Authorization/PasswordAuthDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/ConfirmHideAddressViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/CreatePasswordDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/InsufficientBalanceDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/ShowErrorDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/HelpAndSupport/AboutViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/ContainsNumbersViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/ContainsSymbolsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/PasswordFinderIntroduceViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/PasswordFoundViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/PasswordNotFoundViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/SearchPasswordViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/SelectCharsetViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/RoutableViewModel.cs
  WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/BroadcastTransactionViewModel.cs
  WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/LoadTransactionViewModel.cs
  WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/SuccessBroadcastTransactionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/TransactionDetailsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressesViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/OptimisePrivacyViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendSuccessViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
Labels: size/L

#5593 Vdg/fluent x axis plotting
  WalletWasabi.Fluent/Controls/ContentArea.axaml
  WalletWasabi.Fluent/Controls/LineChart.Properties.cs
  WalletWasabi.Fluent/Controls/LineChart.cs
  WalletWasabi.Fluent/Helpers/EnumerableExtensions.cs
  WalletWasabi.Fluent/Helpers/StraightLineFormula.cs
  WalletWasabi.Fluent/Styles/RadioButton.axaml
  WalletWasabi.Fluent/Styles/Styles.axaml
  WalletWasabi.Fluent/Styles/Themes/BaseDark.axaml
  WalletWasabi.Fluent/Styles/Themes/BaseLight.axaml
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletBalanceChartTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletPieChartTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/Views/MainView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceChartTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletPieChartTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
  WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
  WalletWasabi.Fluent/packages.lock.json
Labels: size/XL

#5668 [Fluent] NavBarItem control updates
  WalletWasabi.Fluent/Controls/NavBarItem.axaml
  WalletWasabi.Fluent/Controls/NavBarItem.axaml.cs
  WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
Labels: size/L

#5645 [draft] BlockstreamInfoClient with HttpClientFactory
  WalletWasabi.Tests/IntegrationTests/BlockstreamInfoTests.cs
  WalletWasabi/WebClients/BlockstreamInfo/BlockstreamInfoClient.cs
  WalletWasabi/WebClients/Wasabi/HttpClientFactory.cs
Labels: size/L

#5671 Fix test build error
  WalletWasabi.Tests/IntegrationTests/BlockstreamInfoTests.cs
Labels: size/XS

#5598 [WabiSabi] Arena HttpClient skeleton
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputSuccessTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/SerializationTests.cs
  WalletWasabi/Crypto/OwnershipProof.cs
  WalletWasabi/JsonConverters/OwnershipProofJsonConverter.cs
  WalletWasabi/JsonConverters/WitScriptJsonConverter.cs
  WalletWasabi/WabiSabi/Backend/Models/Alice.cs
  WalletWasabi/WabiSabi/Backend/Models/WabiSabiProtocolErrorCode.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/ArenaRequestHandler.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/InputRegistrationHandler.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Client/ArenaClient.cs
  WalletWasabi/WabiSabi/Client/HttpRequestHandlerProxy.cs
  WalletWasabi/WabiSabi/Crypto/CredentialRequesting/CredentialsRequest.cs
  WalletWasabi/WabiSabi/Models/InputRegistrationRequest.cs
Labels: size/L

#5672 Fix nullability warnings
  WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
  WalletWasabi/Blockchain/Transactions/SmartTransaction.cs
  WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
  WalletWasabi/CoinJoin/Client/Rounds/ClientState.cs
  WalletWasabi/CoinJoin/Coordinator/Banning/UtxoReferee.cs
  WalletWasabi/CoinJoin/Coordinator/Coordinator.cs
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
  WalletWasabi/Extensions/MemoryExtensions.cs
  WalletWasabi/Extensions/NBitcoinExtensions.cs
  WalletWasabi/Extensions/ReflectionExtensions.cs
  WalletWasabi/Extensions/TaskExtensions.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/DataEncodation/ECISet.cs
  WalletWasabi/Helpers/EnvironmentHelpers.cs
  WalletWasabi/Helpers/IoHelpers.cs
  WalletWasabi/Hwi/Models/HwiEnumerateEntry.cs
  WalletWasabi/Hwi/Parsers/HwiParser.cs
  WalletWasabi/Io/DigestableSafeIoManager.cs
  WalletWasabi/JsonConverters/EndPointJsonConverter.cs
  WalletWasabi/Nito/AsyncEx/DefaultAsyncWaitQueue.cs
  WalletWasabi/Nito/AsyncEx/IAsyncWaitQueue.cs
  WalletWasabi/Nito/Collections/Deque.cs
  WalletWasabi/Nito/Disposables/Internals/BoundAction.cs
  WalletWasabi/Tor/Http/Models/HeaderSection.cs
  WalletWasabi/Userfacing/EndPointParser.cs
  WalletWasabi/WebClients/PayJoin/IPayjoinClient.cs
  WalletWasabi/WebClients/PayJoin/PayjoinClient.cs
Labels: size/L

#5678 [Trivial] Use new()
  WalletWasabi.Fluent/ViewModels/LineChartDemo/XYLineChartViewModel.cs
  WalletWasabi.Tests/Helpers/MempoolInfoGenerator.cs
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/ConstructionState.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/SigningState.cs
Labels: size/S

#5676 [Trivial] Remove redundant cast
  WalletWasabi/WabiSabi/Client/AliceClient.cs
Labels: size/XS

#5670 Make RPC EstimateAllFee cancellable
  WalletWasabi.Tests/UnitTests/AllFeeEstimateTests.cs
  WalletWasabi.Tests/UnitTests/BitcoinCore/RpcBasedTests.cs
  WalletWasabi.Tests/UnitTests/MockRpcClient.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/ConfigTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/CoordinatorTests.cs
  WalletWasabi/BitcoinCore/Monitoring/RpcFeeProvider.cs
  WalletWasabi/BitcoinCore/Rpc/CachedRpcClient.cs
  WalletWasabi/BitcoinCore/Rpc/IRPCClient.cs
  WalletWasabi/BitcoinCore/Rpc/RpcClientBase.cs
  WalletWasabi/Extensions/RPCClientExtensions.cs
Labels: size/M

#5679 Fix null warnings
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressViewModel.cs
  WalletWasabi.Gui/ViewModels/AddressViewModel.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/QrCode.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/QrEncoder.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/TriStateMatrix.cs
  WalletWasabi/Tor/Http/Extensions/HttpRequestMessageExtensions.cs
  WalletWasabi/Tor/Http/Helpers/HttpMessageHelper.cs
  WalletWasabi/Tor/Http/Models/HeaderSection.cs
Labels: size/L

#5680 Wallet / Tiles activation / Deactivation - Some bonus tiles also
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/ViewModels/ActivatableViewModel.cs
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/TransactionDetailsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/BtcPriceTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/RoundStatusTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/TileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletBalanceChartTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletBalanceTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletPieChartTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModelBase.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/BtcPriceTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/BtcPriceTileView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/RoundStatusTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/RoundStatusTileView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
Labels: size/XL

#5686 Improve disposing of Tor items
  WalletWasabi.Fluent/Controls/LineChart.cs
  WalletWasabi.Fluent/Controls/TagControl.axaml.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Tests/IntegrationTests/BlockstreamInfoTests.cs
  WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
  WalletWasabi.Tests/IntegrationTests/P2pTests.cs
  WalletWasabi.Tests/IntegrationTests/TorTests.cs
  WalletWasabi.Tests/RegressionTests/BuildTests.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi.Tests/RegressionTests/WalletTests.cs
  WalletWasabi/Services/UpdateChecker.cs
  WalletWasabi/Services/WasabiSynchronizer.cs
  WalletWasabi/WebClients/Wasabi/HttpClientFactory.cs
Labels: size/M

#5673 [Fluent] [AnimatedButton] Use classes binding to trigger icon animations
  WalletWasabi.Fluent/Controls/AnimatedButton.axaml
  WalletWasabi.Fluent/Controls/AnimatedButton.axaml.cs
Labels: size/L

#5646 Get fees from BlockstreamInfo
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi/Blockchain/Analysis/FeesEstimation/HybridFeeProvider.cs
  WalletWasabi/Blockchain/Analysis/FeesEstimation/IThirdPartyFeeProvider.cs
  WalletWasabi/Blockchain/Analysis/FeesEstimation/ThirdPartyFeeProvider.cs
  WalletWasabi/Services/WasabiSynchronizer.cs
  WalletWasabi/WebClients/BlockstreamInfo/BlockstreamInfoFeeProvider.cs
Labels: size/L

#5702 Dispose TorHttpPool in HttpClientFactory.
  WalletWasabi/WebClients/Wasabi/HttpClientFactory.cs
Labels: size/XS

#5701 Tor: Add LICENSE file
  WalletWasabi/Microservices/Binaries/lin64/Tor/LICENSE
  WalletWasabi/Microservices/Binaries/osx64/Tor/LICENSE
  WalletWasabi/Microservices/Binaries/win64/Tor/LICENSE
Labels: size/XXL

#5703 TorProcessManager: Add cancellation token to `StartAsync`.
  WalletWasabi.Gui/Global.cs
  WalletWasabi/Tor/TorMonitor.cs
  WalletWasabi/Tor/TorProcessManager.cs
Labels: size/S

#5708 utilize is not null in some specific places
  WalletWasabi.Fluent/Controls/ContentArea.axaml.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/Base/DialogScreenViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
  WalletWasabi.Tests/UnitTests/Hwi/HwiProcessBridgeMock.cs
  WalletWasabi/BitcoinCore/CoreNode.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/Blockchain/Mempool/MempoolService.cs
  WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
  WalletWasabi/Extensions/NBitcoinExtensions.cs
  WalletWasabi/Hwi/Parsers/HwiParser.cs
  WalletWasabi/Wallets/Kitchen.cs
  WalletWasabi/WebClients/Wasabi/HttpClientFactory.cs
Labels: size/M

#5705 Nullable warning fixes
  WalletWasabi.Gui/Rpc/WasabiJsonRpcService.cs
  WalletWasabi/Blockchain/Blocks/SmartHeaderChain.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/M

#5709 is and is not null
  WalletWasabi.Fluent/Behaviors/CheckMarkVisibilityBehavior.cs
  WalletWasabi.Fluent/Behaviors/FocusBehavior.cs
  WalletWasabi.Fluent/Controls/ConcatenatingWrapPanel.cs
  WalletWasabi.Fluent/Controls/ResponsivePanel.cs
  WalletWasabi.Fluent/Helpers/PlatformExtension.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
  WalletWasabi/BestEffortEndpointConnector.cs
  WalletWasabi/Nito/Collections/Deque.cs
Labels: size/M

#5710 Use MemberNotNullWhen to fix null warnings
  WalletWasabi.Gui/Rpc/JsonRpcRequest.cs
  WalletWasabi/BitcoinCore/Rpc/Models/VerboseInputInfo.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/Nito/Disposables/Internals/BoundAction.cs
Labels: size/XS

#5693 [WabiSabi] Pre-GetStatus endpoint
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/Crypto/TestTranscript.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputToBlameRoundTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RemoveInputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/SignTransactionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/UtxoPrisonTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/UtxoPrisonWardenTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/AliceClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/SerializationTests.cs
  WalletWasabi/Crypto/StrobeProtocol/StrobeHasher.cs
  WalletWasabi/Crypto/ZeroKnowledge/Transcript.cs
  WalletWasabi/WabiSabi/Backend/Banning/Inmate.cs
  WalletWasabi/WabiSabi/Backend/Banning/Prison.cs
  WalletWasabi/WabiSabi/Backend/Models/Alice.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/InputRegistrationHandler.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
  WalletWasabi/WabiSabi/Client/AliceClient.cs
  WalletWasabi/WabiSabi/Client/ArenaClient.cs
  WalletWasabi/WabiSabi/Client/BobClient.cs
  WalletWasabi/WabiSabi/Models/ConnectionConfirmationRequest.cs
  WalletWasabi/WabiSabi/Models/InputRegistrationRequest.cs
  WalletWasabi/WabiSabi/Models/InputRegistrationResponse.cs
  WalletWasabi/WabiSabi/Models/InputsRemovalRequest.cs
  WalletWasabi/WabiSabi/Models/OutputRegistrationRequest.cs
  WalletWasabi/WabiSabi/Models/ReissueCredentialRequest.cs
  WalletWasabi/WabiSabi/Models/TransactionSignaturesRequest.cs
  WalletWasabi/WabiSabi/ProtocolContants.cs
Labels: size/L

#5696 [Fluent] Fluent remember window state
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/Views/MainWindow.axaml
  WalletWasabi.Gui/Converters/WindowStateAfterStartJsonConverter.cs
  WalletWasabi.Gui/MainWindow.xaml.cs
  WalletWasabi.Gui/UiConfig.cs
  WalletWasabi.Gui/ViewModels/MainWindowViewModel.cs
Labels: size/M

#5688 SendUX: add a watermark to labels to make it really obvious.
  WalletWasabi.Fluent/Controls/TagsBox.axaml
  WalletWasabi.Fluent/Controls/TagsBox.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Labels: size/L

#5706 Add `terminateOnExit` to `TorSettings`
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Tests/Helpers/Common.cs
  WalletWasabi.Tests/UnitTests/Tor/TorSettingsTests.cs
  WalletWasabi/Tor/TorProcessManager.cs
  WalletWasabi/Tor/TorSettings.cs
Labels: size/S

#5714 [Fluent] [Trivial] Fix name violation
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
  WalletWasabi.Fluent/Controls/QrCode.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/DetectedHardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/HelpAndSupport/AboutViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/LoginViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/PasswordFinderIntroduceViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationManager.cs
  WalletWasabi.Fluent/ViewModels/Navigation/RoutableViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/TargettedNavigationStack.cs
  WalletWasabi.Fluent/ViewModels/Search/SearchItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/BroadcastTransactionViewModel.cs
  WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/LoadTransactionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/TransactionDetailsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressesViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Tests/UnitTests/Transactions/PayjoinTests.cs
  WalletWasabi/Crypto/StrobeProtocol/StrobeHasher.cs
Labels: size/L

#5695 [Fluent] Add wallet in dialog
  WalletWasabi.Fluent/App.axaml
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/ConfirmRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/RecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/ConnectHardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/CreatePasswordDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/AddWalletPageView.axaml
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/L

#5687 [Fluent] Select last selected wallet
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Gui/UiConfig.cs
Labels: size/M

#5718 Fluent - update to 0.10.3 avalonia
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
Labels: size/L

#5719 [Fluent] [Trivial] Fix NavBar style class selectors
  WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
Labels: size/XS
