Repository WalletWasabi/WalletWasabi, pull requests merged in 2021-06, with the labels that each got.

#5870 [WabiSabi] Move `ConnectionConfirmationTimeOut` to `RoundState`
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/MultipartyTransactionTests.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/ConstructionState.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/MultipartyTransactionParameters.cs
  WalletWasabi/WabiSabi/Models/RoundState.cs
Labels: size/S

#5726 [WabiSabi] Add credential dependency resolution.
  WalletWasabi.Tests/Helpers/DependencyGraphExtensions.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/CredentialDependencyTests.cs
  WalletWasabi/WabiSabi/Client/CredentialDependencies/CredentialDependency.cs
  WalletWasabi/WabiSabi/Client/CredentialDependencies/CredentialEdgeSet.cs
  WalletWasabi/WabiSabi/Client/CredentialDependencies/CredentialType.cs
  WalletWasabi/WabiSabi/Client/CredentialDependencies/DependencyGraph.cs
  WalletWasabi/WabiSabi/Client/CredentialDependencies/RequestNode.cs
Labels: size/XXL

#5876 [WabiSabi] DependencyGraph format fixes
  WalletWasabi.Tests/Helpers/DependencyGraphExtensions.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/CredentialDependencyTests.cs
  WalletWasabi/WabiSabi/Client/CredentialDependencies/DependencyGraph.cs
Labels: size/M

#5873 [Fluent] Balance Chart - small, normal, wide
  WalletWasabi.Fluent/Model/TimePeriodOption.cs
  WalletWasabi.Fluent/Styles/BalanceLineChart.axaml
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/TimePeriodOptionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletBalanceChartTileViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceChart/WalletBalanceChartNormalTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceChart/WalletBalanceChartSmallTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceChart/WalletBalanceChartWideTileView.axaml
Labels: size/L

#5881 [Fluent] Balance Chart - short named days
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletBalanceChartTileViewModel.cs
Labels: size/XS

#5880 [Backport 1.1.12.9] Cherry-picking
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Gui/Tabs/WalletManager/RecoverWallets/RecoverWalletViewModel.cs
  WalletWasabi.Gui/packages.lock.json
  WalletWasabi.Packager/packages.lock.json
  WalletWasabi/Helpers/Constants.cs
  WalletWasabi/WalletWasabi.csproj
  WalletWasabi/packages.lock.json
  azure-pipelines-linux.yml
Labels: size/M

#5875 Fix IndexBuilderService Access to the path is denied
  WalletWasabi.Tests/UnitTests/BitcoinCore/IndexBuilderServiceTests.cs
  WalletWasabi/Blockchain/BlockFilters/IndexBuilderService.cs
Labels: size/S

#5885 [WabiSabi] Trivial cleanups
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi/WabiSabi/Client/AliceClient.cs
  WalletWasabi/WabiSabi/Client/ArenaClient.cs
Labels: size/M

#5882 Update version to 1.1.12.9
  WalletWasabi.Backend/wwwroot/index.html
  WalletWasabi/Helpers/Constants.cs
Labels: size/S

#5843 Remove unused parameter
  WalletWasabi/WabiSabi/Backend/PostRequests/InputRegistrationHandler.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/XS

#5877 [WabiSabi] Make `PerAliceVsizeAllocation` calculated
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/AliceClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiApiApplicationFactory.cs
  WalletWasabi/Crypto/StrobeProtocol/StrobeHasher.cs
  WalletWasabi/WabiSabi/Backend/Models/Alice.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/InputRegistrationHandler.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
  WalletWasabi/WabiSabi/Backend/Rounds/RoundParameters.cs
  WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
  WalletWasabi/WabiSabi/Client/AliceClient.cs
  WalletWasabi/WabiSabi/Client/ArenaClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Crypto/WabiSabiClient.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/MultipartyTransactionState.cs
  WalletWasabi/WabiSabi/Models/RoundState.cs
  WalletWasabi/WabiSabi/ProtocolContants.cs
Labels: size/L

#5888 [WabiSabi] Remove script from reissuance
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi/WabiSabi/Client/AliceClient.cs
  WalletWasabi/WabiSabi/Client/ArenaClient.cs
  WalletWasabi/WabiSabi/Client/BobClient.cs
Labels: size/M

#5871 Tor control: Support for async Tor events
  WalletWasabi.Tests/UnitTests/Tor/Control/TorControlClientTests.cs
  WalletWasabi.Tests/UnitTests/Tor/Control/TorControlFactoryTests.cs
  WalletWasabi/Tor/Control/ReplyCode.cs
  WalletWasabi/Tor/Control/TorControlClient.cs
  WalletWasabi/Tor/Control/TorControlClientFactory.cs
  WalletWasabi/Tor/TorProcessManager.cs
Labels: size/L

#5887 Logger: Add `CallerMemberName` information to logs
  WalletWasabi/Logging/Logger.cs
Labels: size/M

#5782 Fix warnings in SmartTransactionTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/SmartTransactionTests.cs
  WalletWasabi/Blockchain/Transactions/SmartTransaction.cs
Labels: size/S

#5896 Add batch acquiring txs from RPC
  WalletWasabi.Backend/Controllers/BlockchainController.cs
  WalletWasabi.Tests/UnitTests/BitcoinCore/RpcBasedTests.cs
  WalletWasabi.Tests/UnitTests/MockRpcClient.cs
  WalletWasabi/BitcoinCore/Rpc/IRPCClient.cs
  WalletWasabi/BitcoinCore/Rpc/RpcClientBase.cs
Labels: size/M

#5897 [WabiSabi] Improve Unit Test
  WalletWasabi.Tests/Helpers/ArenaRequestHandlerAdapter.cs
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/AliceTimeoutTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/ConfirmConnectionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputSuccessTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputToBlameRoundTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterOutputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/AliceClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/MultipartyTransactionTests.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/ArenaRequestHandler.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/XXL

#5899 [WabiSabi] Prevent DoS attacks
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputSuccessTests.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/InputRegistrationHandler.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/M

#5902 [WabiSabi] Replace Rounds dictionary by HashSet
  WalletWasabi.Backend/Controllers/WabiSabiController.cs
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepConnectionConfirmationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepInputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/ConfirmConnectionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterOutputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RemoveInputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/SignTransactionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/RoundCreationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/AliceClientTests.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/InputRegistrationHandler.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/M

#5910 [WabiSabi] Small refactoring to denomination generator
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/StandardDenominationsTests.cs
  WalletWasabi/WabiSabi/Models/Decomposition/BaseDenomGenerator.cs
  WalletWasabi/WabiSabi/Models/Decomposition/StandardDenomination.cs
Labels: size/M

#5890 update to avalonia 0.10.6
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
Labels: size/L

#5866 [Fluent] Wallet balance normal and wide tile
  WalletWasabi.Fluent/Controls/TileControl.axaml
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletBalanceTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalance/WalletBalanceLargeTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalance/WalletBalanceMediumTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalance/WalletBalanceWideTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceTileView.axaml
Labels: size/L

#5912 Add Cloudflare tutorial to BackendDeployment.md
  WalletWasabi.Documentation/BackendDeployment.md
Labels: size/M

#5915 Update .editorconfig for *.axaml files
  .editorconfig
Labels: size/XS

#5898 Mempool Mirror
  WalletWasabi.Backend/Controllers/BlockchainController.cs
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Tests/Helpers/BitcoinFactory.cs
  WalletWasabi.Tests/UnitTests/MempoolMirrorTests/MirrorMempoolTests.cs
  WalletWasabi/BitcoinCore/Mempool/MempoolMirror.cs
  WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs
Labels: size/L

#5921 [Fluent] Tweak infomessage in Settings page
  WalletWasabi.Fluent/Controls/InfoMessage.axaml
  WalletWasabi.Fluent/Views/Settings/SettingsPageView.axaml
Labels: size/M

#5920 [WabiSabi] Enforce range proof constraints in dependency graph
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/CredentialDependencyTests.cs
  WalletWasabi/WabiSabi/Client/CredentialDependencies/CredentialEdgeSet.cs
  WalletWasabi/WabiSabi/Client/CredentialDependencies/DependencyGraph.cs
  WalletWasabi/WabiSabi/ProtocolContants.cs
Labels: size/M

#5917 Fixes the clearnet icon in the footer of onion-index.html
  WalletWasabi.Backend/wwwroot/css/style.css
  WalletWasabi.Backend/wwwroot/images/icon-colored-clearnet.png
Labels: size/XS

#5886 [Fluent] Transaction broadcaster rework
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/BroadcastTransactionViewModel.cs
  WalletWasabi.Fluent/Views/TransactionBroadcasting/BroadcastTransactionView.axaml
Labels: size/L

#5919 [Fluent] Status bar
  WalletWasabi.Fluent.Desktop/Program.cs
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/App.axaml
  WalletWasabi.Fluent/Behaviors/ShowFlyoutOnPointerOverBehavior.cs
  WalletWasabi.Fluent/Controls/StatusItem.axaml
  WalletWasabi.Fluent/Controls/StatusItem.axaml.cs
  WalletWasabi.Fluent/Converters/StatusBarStateVisibilityConverter.cs
  WalletWasabi.Fluent/Converters/StatusConverters.cs
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/Models/StatusBarState.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/StatusBar/StatusBarViewModel.cs
  WalletWasabi.Fluent/Views/MainView.axaml
  WalletWasabi.Fluent/Views/StatusBar.axaml
  WalletWasabi.Fluent/Views/StatusBar/StatusBar.axaml
  WalletWasabi.Fluent/Views/StatusBar/StatusBar.axaml.cs
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
  WalletWasabi.Tests/WalletWasabi.Tests.csproj
Labels: size/XL

#5924 Tor control: Subscription API for events.
  WalletWasabi.Tests/UnitTests/Tor/Control/PipeWriterExtensions.cs
  WalletWasabi.Tests/UnitTests/Tor/Control/TorControlClientTests.cs
  WalletWasabi.Tests/UnitTests/Tor/Control/TorControlFactoryTests.cs
  WalletWasabi.Tests/UnitTests/Tor/Control/TorControlReplyReaderTests.cs
  WalletWasabi.Tests/UnitTests/Tor/Control/Utils/AsyncEventParserTests.cs
  WalletWasabi/Tor/Control/Messages/Events/IAsyncEvent.cs
  WalletWasabi/Tor/Control/TorControlClient.cs
  WalletWasabi/Tor/Control/Utils/AsyncEventParser.cs
Labels: size/L

#5930 trivial: Remove debug code
  WalletWasabi.Tests/IntegrationTests/BlockstreamInfoTests.cs
  WalletWasabi.Tests/UnitTests/Tor/Socks5/TorTcpConnectionFactoryTests.cs
Labels: size/XS

#5938 PipeWriterExtensions: Add missing `.ConfigureAwait(false)`.
  WalletWasabi.Tests/UnitTests/Tor/Control/PipeWriterExtensions.cs
  WalletWasabi.Tests/UnitTests/Tor/Control/TorControlClientTests.cs
  WalletWasabi/Tor/Control/TorControlClient.cs
Labels: size/S

#5951 [Trivial] Remove duplicate using directive
  WalletWasabi.Backend/Controllers/WabiSabiController.cs
Labels: size/XS

#5950 [Trivial] Remove unnecessary assignement
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/AliceClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
Labels: size/XS

#5949 [Trivial] Simplify 'new' expression
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi/WabiSabi/Models/RoundState.cs
Labels: size/S

#5940 [Fluent] Create Wallet - 3 words to confirm instead of 4
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/ConfirmRecoveryWordsViewModel.cs
Labels: size/XS

#5936 TorProcessManager: Split `StartAsync` method
  WalletWasabi/Tor/TorProcessManager.cs
Labels: size/L

#5844 [Fluent] Remove leftover code
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
Labels: size/M

#5953 [Fluent] Do not show the labels of a private coin
  WalletWasabi.Fluent/Helpers/CoinHelpers.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionInfo.cs
Labels: size/S

#5845 [Fluent] Remove unused parameter
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
Labels: size/S

#5895 [WabiSabi] Add graph resolution
  WalletWasabi.Backend/Controllers/WabiSabiController.cs
  WalletWasabi.Backend/Filters/ExceptionTranslateFilter.cs
  WalletWasabi.Tests/Helpers/ArenaRequestHandlerAdapter.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/GreedyDecomposerTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi/Extensions/NBitcoinExtensions.cs
  WalletWasabi/WabiSabi/Backend/Models/Alice.cs
  WalletWasabi/WabiSabi/Backend/Models/WabiSabiProtocolErrorCode.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/ArenaRequestHandler.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/IWabiSabiApiRequestHandler.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
  WalletWasabi/WabiSabi/Client/AliceClient.cs
  WalletWasabi/WabiSabi/Client/ArenaClient.cs
  WalletWasabi/WabiSabi/Client/BobClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CredentialDependencies/DependencyGraph.cs
  WalletWasabi/WabiSabi/Client/CredentialDependencies/DependencyGraphExtensions.cs
  WalletWasabi/WabiSabi/Client/CredentialDependencies/InputNode.cs
  WalletWasabi/WabiSabi/Client/CredentialDependencies/OutputNode.cs
  WalletWasabi/WabiSabi/Client/CredentialDependencies/ReissuanceNode.cs
  WalletWasabi/WabiSabi/Client/CredentialDependencies/RequestNode.cs
  WalletWasabi/WabiSabi/Client/DependencyGraphResolver.cs
  WalletWasabi/WabiSabi/Client/GreedyDecomposer.cs
  WalletWasabi/WabiSabi/Client/SmartRequestNode.cs
  WalletWasabi/WabiSabi/Client/WabiSabiHttpApiClient.cs
  WalletWasabi/WabiSabi/Crypto/ZeroCredentialPool.cs
  WalletWasabi/WabiSabi/Models/ReadyToSignRequestRequest.cs
Labels: size/XXL

#5958 Credential bikeshedding
  WalletWasabi.Tests/UnitTests/Crypto/ProofSystemTests.cs
  WalletWasabi/Crypto/ZeroKnowledge/Credential.cs
  WalletWasabi/Crypto/ZeroKnowledge/ProofSystem.cs
  WalletWasabi/WabiSabi/Client/ArenaClient.cs
  WalletWasabi/WabiSabi/Client/SmartRequestNode.cs
  WalletWasabi/WabiSabi/Crypto/IssuanceValidationData.cs
  WalletWasabi/WabiSabi/Crypto/WabiSabiClient.cs
  WalletWasabi/WabiSabi/Crypto/ZeroCredentialPool.cs
Labels: size/M

#5959 Add a test class for `TorProcessManager`.
  WalletWasabi.Tests/UnitTests/Tor/TorProcessManagerTests.cs
  WalletWasabi/Microservices/ProcessAsync.cs
  WalletWasabi/Tor/Socks5/TorTcpConnectionFactory.cs
  WalletWasabi/Tor/TorProcessManager.cs
Labels: size/M

#5929 [Fluent] Update app branding with the final logo (Part 1)
  WalletWasabi.Fluent.Desktop/Assets/WasabiLogo.ico
  WalletWasabi.Fluent/Assets/Fonts/Objectivity-Light.otf
  WalletWasabi.Fluent/Assets/Fonts/Objectivity-Regular.otf
  WalletWasabi.Fluent/Assets/Theme/wasabi_theme_change.png
  WalletWasabi.Fluent/Assets/WalletIcons/Dark/coldcard.png
  WalletWasabi.Fluent/Assets/WalletIcons/Dark/generic.png
  WalletWasabi.Fluent/Assets/WalletIcons/Dark/ledger.png
  WalletWasabi.Fluent/Assets/WalletIcons/Dark/normal.png
  WalletWasabi.Fluent/Assets/WalletIcons/Dark/trezor.png
  WalletWasabi.Fluent/Assets/WalletIcons/Light/coldcard.png
  WalletWasabi.Fluent/Assets/WalletIcons/Light/generic.png
  WalletWasabi.Fluent/Assets/WalletIcons/Light/ledger.png
  WalletWasabi.Fluent/Assets/WalletIcons/Light/normal.png
  WalletWasabi.Fluent/Assets/WalletIcons/Light/trezor.png
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/Styles/Styles.axaml
  WalletWasabi.Fluent/Styles/Themes/Base.axaml
  WalletWasabi.Fluent/Views/HelpAndSupport/AboutView.axaml
  WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
  WalletWasabi.Fluent/Views/Settings/ThemeChangeView.axaml
Labels: size/L

#5965 [WabiSabi] Remove ZeroCredentialPool
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputSuccessTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/AliceClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/CredentialTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiApiApplicationFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/SerializationTests.cs
  WalletWasabi/WabiSabi/Client/AliceClient.cs
  WalletWasabi/WabiSabi/Client/ArenaClient.cs
  WalletWasabi/WabiSabi/Client/ArenaResponse.cs
  WalletWasabi/WabiSabi/Client/BobClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/DependencyGraphResolver.cs
  WalletWasabi/WabiSabi/Client/SmartRequestNode.cs
  WalletWasabi/WabiSabi/Crypto/WabiSabiClient.cs
  WalletWasabi/WabiSabi/Crypto/ZeroCredentialPool.cs
  WalletWasabi/WabiSabi/Models/RoundState.cs
Labels: size/XL
