Repository WalletWasabi/WalletWasabi, pull requests merged in 2021-11, with the labels that each got.

#6593 Fluentish `UiConfig.cs`
  WalletWasabi.Fluent/Converters/SortingPreferenceJsonConverter.cs
  WalletWasabi.Fluent/Models/Sorting/SortOrder.cs
  WalletWasabi.Fluent/Models/Sorting/SortingPreference.cs
  WalletWasabi.Fluent/UiConfig.cs
Labels: size/L

#6612 Remove `ArenaRequestHandler`
  WalletWasabi.Backend/Controllers/BlockchainController.cs
  WalletWasabi.Backend/Controllers/WabiSabiController.cs
  WalletWasabi.Backend/Startup.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/AliceTimeoutTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/ConfirmConnectionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputToBlameRoundTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterOutputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RemoveInputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/SignTransactionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/RequestHandlerDisposeTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiApiApplicationFactory.cs
  WalletWasabi/CoinJoin/Coordinator/Coordinator.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/ArenaRequestHandler.cs
  WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
Labels: size/L

#6609 Bump client version to 1.1.13.0
  WalletWasabi.Backend/wwwroot/index.html
  WalletWasabi/Helpers/Constants.cs
Labels: size/S

#6620 Fix the links
  WalletWasabi.Backend/wwwroot/index.html
Labels: size/S

#6615 Backend: `Startup`: Switch from `IHostApplicationLifetime.ApplicationS…
  WalletWasabi.Backend/Startup.cs
Labels: size/XS

#6632 [VDG] fix hyperlink underline
  WalletWasabi.Fluent/Styles/HyperlinkButton.axaml
Labels: size/XS

#6626 [Fluent] Fix Null Exception on some cases in RandomizedWorldBehavior
  WalletWasabi.Fluent/Behaviors/RandomizedWorldPointsBehavior.cs
Labels: size/S

#6599 [VDG] Privacy optimization - hyperlink to icon
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml
Labels: size/L

#6591 Clarify notification title
  WalletWasabi.Fluent/Helpers/NotificationHelpers.cs
Labels: size/XS

#6590 [forward-port] Make HTTP header names case-insensitive
  WalletWasabi/Tor/Http/Models/HeaderSection.cs
Labels: size/S

#6633 Updated WasabikaCodex for non-devs
  WalletWasabi.Documentation/WasabikaCodex.md
Labels: size/M

#6554 [Trivial] Fix AreTransactionFeesEqual() logic
  WalletWasabi.Fluent/Helpers/TransactionFeeHelper.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
Labels: size/XS

#6550 Change KeyPath for TestNet
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/AdvancedRecoveryOptionsViewModel.cs
  WalletWasabi.Tests/AcceptanceTests/HwiKatas.cs
  WalletWasabi.Tests/Helpers/ServiceFactory.cs
  WalletWasabi.Tests/IntegrationTests/P2pTests.cs
  WalletWasabi.Tests/RegressionTests/BuildTests.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi.Tests/RegressionTests/WalletTests.cs
  WalletWasabi.Tests/UnitTests/Hwi/HwiProcessBridgeMock.cs
  WalletWasabi.Tests/UnitTests/Hwi/MockedDeviceTests.cs
  WalletWasabi.Tests/UnitTests/KeyManagementTests.cs
  WalletWasabi.Tests/UnitTests/SmartCoinTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/PayjoinTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
  WalletWasabi.Tests/UnitTests/Userfacing/PasswordTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/Participant.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi/Blockchain/Keys/BlockchainState.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/Blockchain/Keys/WalletGenerator.cs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
  WalletWasabi/Helpers/HardwareWalletOperationHelpers.cs
  WalletWasabi/Helpers/ImportWalletHelper.cs
Labels: size/L

#6648 Add `LogTrace` in catch block
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/SearchPasswordViewModel.cs
Labels: size/XS

#6641 [Trivial] Docs: Remove reference to Gui project
  WalletWasabi.Documentation/WasabiSetupRegtest.md
Labels: size/XS

#6652 [WabiSabi] Don't register inputs too close to the timeout
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/XS

#6587 [Trivial] Correct transaction fee message
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
Labels: size/XS

#6595 Fluentish `FileHelper.cs`
  WalletWasabi.Fluent/Helpers/FileHelpers.cs
  WalletWasabi.Fluent/ViewModels/OpenDirectory/OpenConfigFileViewModel.cs
  WalletWasabi.Fluent/ViewModels/OpenDirectory/OpenFileViewModel.cs
  WalletWasabi.Fluent/ViewModels/OpenDirectory/OpenLogsViewModel.cs
  WalletWasabi.Fluent/ViewModels/OpenDirectory/OpenTorLogsViewModel.cs
Labels: size/L

#6596 Fluentish `NotificationHelper.cs`
  WalletWasabi.Fluent/Helpers/NotificationHelpers.cs
Labels: size/M

#6676 Fix ZeroLink on Backend
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/RegressionTests/DosTests.cs
  WalletWasabi/CoinJoin/Client/Clients/AliceClient4.cs
  WalletWasabi/CoinJoin/Client/Clients/AliceClientBase.cs
  WalletWasabi/CoinJoin/Client/Clients/BobClient.cs
  WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
  WalletWasabi/CoinJoin/Client/Clients/SatoshiClient.cs
  WalletWasabi/CoinJoin/Client/Rounds/ClientRound.cs
  WalletWasabi/CoinJoin/Client/Rounds/ClientRoundRegistration.cs
  WalletWasabi/CoinJoin/Client/Rounds/ClientState.cs
  WalletWasabi/CoinJoin/Coordinator/Coordinator.cs
  WalletWasabi/CoinJoin/Coordinator/RoundBootstrapper.cs
Labels: size/XXL

#6678 Slow the growth of client side filters
  WalletWasabi.Tests/UnitTests/BitcoinCore/IndexBuilderServiceTests.cs
  WalletWasabi/Blockchain/BlockFilters/IndexBuilderService.cs
Labels: size/S

#6680 Fix coin may be null
  WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs
  WalletWasabi/Blockchain/TransactionOutputs/CoinsView.cs
  WalletWasabi/Blockchain/TransactionOutputs/ICoinsView.cs
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/S

#6649 [WabiSabi] Retry requests that fail due to transport errors
  WalletWasabi/WabiSabi/Client/WabiSabiHttpApiClient.cs
Labels: size/M

#6655 Remove weight bias, because it ruins the algorithm
  WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
Labels: size/S

#6686 Rename GetDenominationFrequency
  WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
Labels: size/XS

#6689 [WabiSabi] Fix blocked round updater
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/RoundStateUpdaterTests.cs
  WalletWasabi/WabiSabi/Client/RoundStateUpdater.cs
Labels: size/M

#6506 [Fluent] New DataGrid control for transaction history
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/Styles/DataBox.axaml
  WalletWasabi.Fluent/Styles/Styles.axaml
  WalletWasabi.Fluent/Styles/Themes/BaseDark.axaml
  WalletWasabi.Fluent/Styles/Themes/BaseLight.axaml
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
  WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveAddressesView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/PrivacyControlView.axaml
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
Labels: size/L

#6683 [Backport] Fix coin may be null
  WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs
  WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs
  WalletWasabi/Blockchain/TransactionOutputs/CoinsView.cs
  WalletWasabi/Blockchain/TransactionOutputs/ICoinsView.cs
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/M

#6645 Improve reliability for alices
  WalletWasabi/Tor/Socks5/TorTcpConnectionFactory.cs
Labels: size/XS

#6694 Split Arena in `PeriodicRunner` and `WabiSabiRequestHandler`
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/XL

#6697 Remove `ActiveRounds` property from arena
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepConnectionConfirmationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepInputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/Rounds/Utils/ArenaExtensions.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/M

#6672 Add documentation for `IHttpClient`.
  WalletWasabi/Tor/Http/IHttpClient.cs
Labels: size/XS

#6702 [Trivial] Fix CodeFactor issues in RingChartControl.cs
  WalletWasabi.Fluent/Controls/RingChartControl.cs
Labels: size/M

#6698 [Fluent] Hide private output descriptors
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletInfoView.axaml
Labels: size/XS

#6463 .net 6
  README.md
  WalletWasabi.Backend/WalletWasabi.Backend.csproj
  WalletWasabi.Documentation/BackendDeployment.md
  WalletWasabi.Documentation/Guides/HowToDebug.md
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent.Generators/WalletWasabi.Fluent.Generators.csproj
  WalletWasabi.Fluent.Generators/packages.lock.json
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
  WalletWasabi.Packager/WalletWasabi.Packager.csproj
  WalletWasabi.Packager/packages.lock.json
  WalletWasabi.Tests/UnitTests/Userfacing/BitcoinInputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/SerializationTests.cs
  WalletWasabi.Tests/WalletWasabi.Tests.csproj
  WalletWasabi/Userfacing/BitcoinInput.cs
  WalletWasabi/WalletWasabi.csproj
  WalletWasabi/packages.lock.json
  azure-pipelines-cd.yml
  azure-pipelines-detbuild.yml
  azure-pipelines-linux.yml
  azure-pipelines-osx.yml
  azure-pipelines-windows.yml
  global.json
Labels: size/L

#6714 Make problems more evident
  WalletWasabi/WabiSabi/Client/RoundStateAwaiter.cs
Labels: size/XS

#6707 explicitly specify one way bindings where string format is used.
  WalletWasabi.Fluent/Views/AddWallet/Create/ConfirmRecoveryWordsView.axaml
  WalletWasabi.Fluent/Views/AddWallet/Create/RecoveryWordsView.axaml
  WalletWasabi.Fluent/Views/Login/PasswordFinder/SearchPasswordView.axaml
  WalletWasabi.Fluent/Views/StatusBar/StatusBar.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/CoinJoinDetailsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/TransactionDetailsView.axaml
Labels: size/S

#6688 [VDG] Show privacy optimization option in self-spend case as well
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
Labels: size/XS

#6716 `HttpStatusCodeHelper`: Very minor optimization
  WalletWasabi.Tests/UnitTests/Tor/Http/Helpers/HttpStatusCodeHelperTests.cs
  WalletWasabi/Tor/Http/Helpers/HttpStatusCodeHelper.cs
Labels: size/S

#6534 `WalletManager`: Remove unused methods.
  WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/S

#6699 [Fluent] Add missing ForceShow to public output descriptors
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletInfoView.axaml
Labels: size/XS

#6665 Fix "Not the same type!" issue
  WalletWasabi/Blockchain/Transactions/TransactionHistoryBuilder.cs
Labels: size/XS

#6543 Fix nullability warnings
  WalletWasabi/Blockchain/Keys/KeyManager.cs
Labels: size/XS

#6725 `HeaderField`: Introduce `IsNameEqual`.
  WalletWasabi/Tor/Http/Helpers/HttpMessageHelper.cs
  WalletWasabi/Tor/Http/Models/HeaderField.cs
  WalletWasabi/Tor/Http/Models/HeaderSection.cs
Labels: size/M

#6666 [VDG] fix missing last CJ item in transaction history
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
Labels: size/S

#6659 More robust handling of idempotent requests
  WalletWasabi.Backend/Controllers/WabiSabi/IdempotencyRequestCache.cs
  WalletWasabi.Backend/Controllers/WabiSabiController.cs
  WalletWasabi.Backend/Filters/IdempotentActionFilterAttributeImpl.cs
  WalletWasabi.Backend/Filters/IdempotentAttribute.cs
  WalletWasabi.Backend/Startup.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/Controllers/IdempotencyRequestCacheTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/ReadyToSignRequestRequestTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/Startup.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/ConnectionConfirmationRequestTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/InputRegistrationRequestTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/InputsRemovalRequestTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/OutputRegistrationRequestTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/TransactionSignaturesRequestTests.cs
  WalletWasabi/Crypto/Bip322Signature.cs
  WalletWasabi/Crypto/GroupElementVector.cs
  WalletWasabi/Crypto/OwnershipIdentifier.cs
  WalletWasabi/Crypto/OwnershipProof.cs
  WalletWasabi/Crypto/ProofBody.cs
  WalletWasabi/Crypto/ScalarVector.cs
  WalletWasabi/Crypto/ZeroKnowledge/Proof.cs
  WalletWasabi/Nito/AsyncEx/AbandonedTasks.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/IWabiSabiApiRequestHandler.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
  WalletWasabi/WabiSabi/Client/WabiSabiHttpApiClient.cs
  WalletWasabi/WabiSabi/Crypto/CredentialRequesting/CredentialsRequest.cs
  WalletWasabi/WabiSabi/Crypto/IssuanceRequest.cs
  WalletWasabi/WabiSabi/Models/EmptyResponse.cs
  WalletWasabi/WabiSabi/Models/InputRegistrationRequest.cs
  WalletWasabi/WabiSabi/Models/OutputRegistrationRequest.cs
  WalletWasabi/WabiSabi/Models/ReadyToSignRequestRequest.cs
  WalletWasabi/WabiSabi/Models/TransactionSignaturesRequest.cs
Labels: size/XXL

#6736 Enumerable with value semantic
  WalletWasabi.Tests/UnitTests/ImmutableValueSequenceTests.cs
  WalletWasabi/Extensions/ImmutableValueSequenceExtensions.cs
  WalletWasabi/Models/ImmutableValueSequence.cs
  WalletWasabi/WabiSabi/Crypto/CredentialRequesting/CredentialsRequest.cs
  WalletWasabi/WabiSabi/Crypto/CredentialRequesting/RealCredentialsRequest.cs
  WalletWasabi/WabiSabi/Crypto/CredentialRequesting/ZeroCredentialsRequest.cs
Labels: size/L

#6737 Fix some null warnings
  WalletWasabi.Backend/Controllers/HomeController.cs
  WalletWasabi.Tests/UnitTests/Userfacing/ParserTests.cs
Labels: size/M

#6738 Catch OpenCV exception and show user friendly error message.
  WalletWasabi.Fluent/Models/WebcamQrReader.cs
Labels: size/XS

#6739 [WabiSabi] Split CredentialRequest types
  WalletWasabi.Tests/UnitTests/WabiSabi/SerializationTests.cs
  WalletWasabi/Models/ImmutableValueSequence.cs
  WalletWasabi/WabiSabi/Crypto/CredentialIssuer.cs
  WalletWasabi/WabiSabi/Crypto/CredentialRequesting/CredentialsRequest.cs
  WalletWasabi/WabiSabi/Crypto/CredentialRequesting/CredentialsRequestExtensions.cs
  WalletWasabi/WabiSabi/Crypto/CredentialRequesting/ICredentialsRequest.cs
  WalletWasabi/WabiSabi/Crypto/CredentialRequesting/RealCredentialsRequest.cs
  WalletWasabi/WabiSabi/Crypto/CredentialRequesting/ZeroCredentialsRequest.cs
Labels: size/L

#6723 Catch ArgumentException & EndOfStreamException if AddressManager gets corrupted
  WalletWasabi.Gui/Global.cs
Labels: size/S

#6742 MoneySatoshiJsonConverter: Fix warnings
  WalletWasabi/JsonConverters/Bitcoin/MoneySatoshiJsonConverter.cs
Labels: size/S

#6741 Switch 'EndPointJsonConverter' from 'JsonConverter' to 'JsonConverter<T>'
  WalletWasabi/JsonConverters/EndPointJsonConverter.cs
Labels: size/S

#6744 update avalonia to restore apple sillicon support.
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
Labels: size/L

#6745 Catch ArgumentException & EndOfStreamException if AddressManager gets corrupted
  WalletWasabi/BitcoinP2p/P2pNetwork.cs
Labels: size/S

#6481 .NET 6: `Task.WaitAsync` + `.editorconfig` changes
  .editorconfig
  WalletWasabi.Backend/GlobalUsings.cs
  WalletWasabi.Fluent.Desktop/GlobalUsings.cs
  WalletWasabi.Fluent.Generators/GlobalUsings.cs
  WalletWasabi.Fluent/GlobalUsings.cs
  WalletWasabi.Gui/GlobalUsings.cs
  WalletWasabi.Packager/GlobalUsings.cs
  WalletWasabi.Tests/GlobalUsings.cs
  WalletWasabi.Tests/UnitTests/AbandonedTasksTests.cs
  WalletWasabi.Tests/UnitTests/Tor/Socks5/TorTcpConnectionFactoryTests.cs
  WalletWasabi/Crypto/Extensions.cs
  WalletWasabi/Crypto/StringCipher.cs
  WalletWasabi/Extensions/TaskExtensions.cs
  WalletWasabi/GlobalUsings.cs
  WalletWasabi/Helpers/EventAwaiter.cs
  WalletWasabi/Helpers/EventsAwaiter.cs
  WalletWasabi/Helpers/ThreadingHelpers.cs
  WalletWasabi/Services/SingleInstanceChecker.cs
Labels: size/L

#6729 [VDG] Update Notifications
  WalletWasabi.Fluent/Helpers/NotificationHelpers.cs
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
Labels: size/M

#6718 [VDG] Separate auto copy/paste
  WalletWasabi.Fluent/Behaviors/AttachedToVisualTreeBehavior.cs
  WalletWasabi.Fluent/Behaviors/FocusOnAttachedBehavior.cs
  WalletWasabi.Fluent/Behaviors/PasteButtonFlashBehavior.cs
  WalletWasabi.Fluent/Controls/AnimatedButton.axaml
  WalletWasabi.Fluent/Controls/AnimatedButton.axaml.cs
  WalletWasabi.Fluent/UiConfig.cs
  WalletWasabi.Fluent/ViewModels/Settings/GeneralSettingsTabViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/Views/Settings/GeneralSettingsTabView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Labels: size/L

#6746 Do not deserialize `EmptyResponse` to unblock CJ
  WalletWasabi.Backend/Controllers/WabiSabiController.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/IWabiSabiApiRequestHandler.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
  WalletWasabi/WabiSabi/Client/WabiSabiHttpApiClient.cs
Labels: size/S

#6731 Typo fix-'To Bitcoin address' instead of 'Via'
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml
Labels: size/XS

#6755 Trivial - Transaction Preview wording
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml
Labels: size/S

#6756 [WabiSabi] Do not throw exceptions when no Alice is available
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/XS

#6760 [WabiSabi] Remove InputWitnessPair
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/SignTransactionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/SerializationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/TransactionSignaturesRequestTests.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
  WalletWasabi/WabiSabi/Client/ArenaClient.cs
  WalletWasabi/WabiSabi/Models/InputWitnessPair.cs
  WalletWasabi/WabiSabi/Models/TransactionSignaturesRequest.cs
Labels: size/L

#6701 Fix table layout
  WalletWasabi.Fluent/Behaviors/HistoryItemDetailsAdorner.cs
  WalletWasabi.Fluent/Behaviors/HistoryItemDetailsBehavior.cs
  WalletWasabi.Fluent/Controls/AdornerCanvas.cs
  WalletWasabi.Fluent/Controls/ContentArea.axaml
  WalletWasabi.Fluent/Styles/SplitView.axaml
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinsHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/TransactionHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletBalanceTileViewModel.cs
  WalletWasabi.Fluent/Views/MainView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
Labels: size/XL

#6696 [Fluent] WinUI-style Selection Indicator animations
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/Behaviors/NavBarSelectedIndicatorChildBehavior.cs
  WalletWasabi.Fluent/Behaviors/NavBarSelectedIndicatorParentBehavior.cs
  WalletWasabi.Fluent/Behaviors/NavBarSelectedIndicatorState.cs
  WalletWasabi.Fluent/Controls/NavBarItem.axaml
  WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
Labels: size/L
