Repository WalletWasabi/WalletWasabi, pull requests merged in 2021-09, with the labels that each got.

#6272 [Fluent] QR camera stays visible if content is not correct
  WalletWasabi.Fluent/ViewModels/Dialogs/ShowQrCameraDialogViewModel.cs
  WalletWasabi.Fluent/Views/Dialogs/ShowQrCameraDialogView.axaml
Labels: size/S

#6282 [Fluent] Make Settings tabs not draggable
  WalletWasabi.Fluent/Views/Settings/SettingsPageView.axaml
Labels: size/XS

#6287 [WabiSabi] Disable WabiSabi coinjoin manager on mainet
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Labels: size/XS

#6284 Create AliceClient with input registration
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/AliceTimeoutTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
  WalletWasabi/WabiSabi/Client/AliceClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/L

#5913 Load and Welcome screen
  WalletWasabi.Fluent/Assets/oobe.png
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/ViewModels/AddWallet/WelcomePageViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/TargettedNavigationStack.cs
  WalletWasabi.Fluent/Views/AddWallet/WelcomePageView.axaml
  WalletWasabi.Fluent/Views/AddWallet/WelcomePageView.axaml.cs
  WalletWasabi.Fluent/Views/MainView.axaml
  WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
  WalletWasabi.Gui/UiConfig.cs
Labels: size/XL

#6292 always show the oobe background during add wallet procedure.
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/Base/DialogViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/Base/DialogViewModelBaseOfTResult.cs
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationStack.cs
  WalletWasabi.Fluent/ViewModels/Navigation/TargettedNavigationStack.cs
Labels: size/M

#6250 [Fluent] Add restart button to settings
  WalletWasabi.Fluent/ViewModels/Settings/SettingsPageViewModel.cs
  WalletWasabi.Fluent/Views/Settings/SettingsPageView.axaml
Labels: size/S

#6289 Exceptions when application is shutting down (2)
  WalletWasabi/Extensions/StreamExtensions.cs
  WalletWasabi/Tor/Http/Extensions/HttpResponseMessageExtensions.cs
  WalletWasabi/Tor/Http/Helpers/HttpMessageHelper.cs
  WalletWasabi/Tor/Socks5/Exceptions/TorConnectionReadException.cs
  WalletWasabi/Tor/Socks5/Pool/TorHttpPool.cs
  WalletWasabi/Tor/Socks5/TorTcpConnection.cs
Labels: size/M

#6288 Exceptions when application is shutting down (1)
  WalletWasabi.Gui/Global.cs
  WalletWasabi/Services/WasabiSynchronizer.cs
  WalletWasabi/Tor/Http/Extensions/HttpResponseMessageExtensions.cs
  WalletWasabi/Tor/Http/Helpers/HttpMessageHelper.cs
Labels: size/M

#6295 Add manual CoinJoin codeonly
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/XS

#6293 `WasabiClient`: Add missing cancellation tokens.
  WalletWasabi/Tor/Http/Extensions/HttpResponseMessageExtensions.cs
  WalletWasabi/WebClients/Wasabi/WasabiClient.cs
Labels: size/S

#6296 Better naming for IsManualCoinJoinEnabled
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/XS

#6283 logger: Increase time granularity to milliseconds.
  WalletWasabi/Logging/Logger.cs
Labels: size/XS

#6314 Wire up DesktopOnShutdownRequested event handler
  WalletWasabi.Fluent/App.axaml.cs
  WalletWasabi.Fluent/ViewModels/ApplicationViewModel.cs
Labels: size/XS

#6305 cleanup: Fix a few warnings.
  WalletWasabi.Fluent/Models/WebcamQrReader.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletBalanceChartTileViewModel.cs
  WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/CredentialDependencyTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/StandardDenominationsTests.cs
  WalletWasabi/Extensions/LinqExtensions.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WebClients/PayJoin/PayjoinClient.cs
Labels: size/S

#6304 `WasabiSynchronizer`: Remove `WithAwaitCancellationAsync`
  WalletWasabi/Services/WasabiSynchronizer.cs
  WalletWasabi/WebClients/BlockstreamInfo/BlockstreamInfoClient.cs
Labels: size/XS

#6310 Safe app init & dispose
  WalletWasabi.Gui/Global.cs
  WalletWasabi/Services/Terminate/TerminateService.cs
Labels: size/L

#6297 Add HideOnClose setting on windows
  WalletWasabi.Fluent.Desktop/Program.cs
  WalletWasabi.Fluent/App.axaml.cs
  WalletWasabi.Fluent/Behaviors/HideShowBehavior.cs
  WalletWasabi.Fluent/Services.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/GeneralSettingsTabViewModel.cs
  WalletWasabi.Fluent/Views/MainWindow.axaml
  WalletWasabi.Fluent/Views/Settings/GeneralSettingsTabView.axaml
  WalletWasabi.Gui/UiConfig.cs
Labels: size/L

#6321 Evaluate if CoinJoin is in critical phase 2
  WalletWasabi.Gui/Global.cs
  WalletWasabi/Services/SystemAwakeChecker.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClientState.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Labels: size/L

#6327 [Fluent[ fix when empty wallet screen shows up for a moment
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
Labels: size/XS

#6298 [Fluent][Trivial] Match text with button
  WalletWasabi.Fluent/Views/AddWallet/RecoverWalletView.axaml
  WalletWasabi.Fluent/Views/Dialogs/AdvancedRecoveryOptionsView.axaml
Labels: size/XS

#6334 Mark coin as `InCoinJoin` only after registered
  WalletWasabi/WabiSabi/Client/AliceClient.cs
Labels: size/XS

#6331 Fix shutdown prevention logic for Preview
  WalletWasabi.Fluent/ViewModels/ApplicationViewModel.cs
Labels: size/S

#6330 [Fluent] Fix watch only wallet view
  WalletWasabi.Fluent/Views/Wallets/ClosedWatchOnlyWalletView.axaml
  WalletWasabi.Fluent/Views/Wallets/ClosedWatchOnlyWalletView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/WatchOnlyWalletView.axaml
  WalletWasabi.Fluent/Views/Wallets/WatchOnlyWalletView.axaml.cs
Labels: size/M

#6313 [Fluent] secure canceling on add wallet pages
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/ConfirmRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/RecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/ConnectHardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/DetectedHardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/SelectWalletCreationOptionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/CreatePasswordDialogViewModel.cs
Labels: size/S

#6316 [Fluent] Fix recover wallet issues
  WalletWasabi.Fluent/Controls/TagControl.axaml
  WalletWasabi.Fluent/Controls/TagControl.axaml.cs
  WalletWasabi.Fluent/Controls/TagsBox.axaml
  WalletWasabi.Fluent/Controls/TagsBox.axaml.cs
  WalletWasabi.Fluent/Views/AddWallet/RecoverWalletView.axaml
Labels: size/M

#6324 [Fluent] Home screen - Tile fixes
  WalletWasabi.Fluent/Helpers/TileHelper.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletPieChart/WalletPieChartWideTileView.axaml
Labels: size/L

#6346 [HouseKeeping] Fix a few warnings
  WalletWasabi.Tests/UnitTests/BitcoinCore/ConfigTranslatorTests.cs
  WalletWasabi.Tests/UnitTests/KeyManagementTests.cs
  WalletWasabi.Tests/UnitTests/SmartHeaderTests.cs
  WalletWasabi.Tests/UnitTests/SmartLabelTests.cs
  WalletWasabi.Tests/UnitTests/Userfacing/PasswordTests.cs
  WalletWasabi/Userfacing/PasswordHelper.cs
Labels: size/M

#6347 [Trivial] Prevent sleep in Critical CJ Phase
  WalletWasabi/Services/SystemAwakeChecker.cs
Labels: size/XS

#6338 Remove Unlock Keychain in macOS packager
  WalletWasabi.Packager/Content/Osx/addcert.sh
  WalletWasabi.Packager/MacSignTools.cs
Labels: size/S

#6376 [Fluent] Settings updates
  WalletWasabi.Fluent/ViewModels/Settings/SettingsPageViewModel.cs
  WalletWasabi.Fluent/Views/Settings/SettingsPageView.axaml
Labels: size/XS

#6375 [Fluent] Fix export of QR Code when Wasabi's in private mode
  WalletWasabi.Fluent/Controls/QrCode.cs
Labels: size/L

#6368 [Fluent] better icon for pending
  WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
Labels: size/XS

#6374 [Fluent] Correct function button disabled look
  WalletWasabi.Fluent/Styles/Button.axaml
Labels: size/XS

#6352 [Fluent] Improve homescreen loading time
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletBalanceChartTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletBalanceTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletPieChartTileViewModel.cs
Labels: size/S

#6373 [Fluent] close the dialog if the selected address gets used
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressViewModel.cs
Labels: size/M

#6357 Feature/tray icon
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/App.axaml
  WalletWasabi.Fluent/Assets/WasabiLogo.ico
  WalletWasabi.Fluent/ViewModels/ApplicationViewModel.cs
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
Labels: size/L

#6318 [Fluent] Add counter to recovery words
  WalletWasabi.Fluent/Controls/TagControl.axaml
  WalletWasabi.Fluent/Controls/TagControl.axaml.cs
  WalletWasabi.Fluent/Controls/TagsBox.axaml
  WalletWasabi.Fluent/Controls/TagsBox.axaml.cs
  WalletWasabi.Fluent/Views/AddWallet/RecoverWalletView.axaml
Labels: size/M

#6377 [WabiSabi] Fix corner case for partially discharged nodes
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/CredentialDependencyTests.cs
  WalletWasabi/WabiSabi/Client/CredentialDependencies/DependencyGraph.cs
Labels: size/M

#6342 [Fluent] Improve the look and feel of the Optimize Privacy screen
  WalletWasabi.Fluent/Models/PrivacySuggestionBenefit.cs
  WalletWasabi.Fluent/Styles/Themes/BaseDark.axaml
  WalletWasabi.Fluent/Styles/Themes/BaseLight.axaml
  WalletWasabi.Fluent/ViewModels/Wallets/Send/OptimisePrivacyViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacySuggestionControlViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Send/OptimisePrivacyView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/PrivacySuggestionControl.axaml
Labels: size/L

#6382 `WebCamQrReader`: Fix threading issue
  WalletWasabi.Fluent/Models/WebcamQrReader.cs
Labels: size/S

#6339 [WabiSabi] Basic Amount decomposer
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/GreedyDecomposerTests.cs
  WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/GreedyDecomposer.cs
Labels: size/L

#6392 [Trivial] Fix typo
  WalletWasabi.Fluent/ViewModels/ApplicationViewModel.cs
Labels: size/XS

#6395 Log change output count on the server
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/XS

#6391 [WabiSabi] Make sure to handle the faulted tasks
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Labels: size/M

#6390 [WabiSabi] Unmark coins as unavailable
  WalletWasabi/WabiSabi/Client/AliceClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/S

#6349 Remove Wasabi Inc label suggestion
  WalletWasabi.Fluent/Styles/Themes/Base.axaml
Labels: size/XS

#6399 [WabiSabi] Sort inputs and outputs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/SignTransactionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/MultipartyTransactionTests.cs
  WalletWasabi/Helpers/ByteArrayComparer.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/SigningState.cs
Labels: size/L

#6406 [WabiSabi] Fix test that was passing just by chance
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/MultipartyTransactionTests.cs
Labels: size/S

#6404 [WabiSabi] Implement proper Tor Isolation for Alice and Bob
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/Participant.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WebClients/Wasabi/HttpClientFactory.cs
  WalletWasabi/WebClients/Wasabi/IHttpClientFactory.cs
Labels: size/L

#6407 [WabiSabi] Shuflle selected coins
  WalletWasabi/Extensions/LinqExtensions.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/XS

#6179 Update to latest NBitcoin version (6.0.8)
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/packages.lock.json
  WalletWasabi.Gui/packages.lock.json
  WalletWasabi.Packager/packages.lock.json
  WalletWasabi.Tests/RegressionTests/BuildTests.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/RegressionTests/DosTests.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi.Tests/UnitTests/BitcoinCore/P2pBasedTests.cs
  WalletWasabi.Tests/UnitTests/BlockNotifierTests.cs
  WalletWasabi.Tests/UnitTests/CoordinatorRoundTests.cs
  WalletWasabi.Tests/UnitTests/InvalidTxExceptionTests.cs
  WalletWasabi.Tests/UnitTests/MockRpcClient.cs
  WalletWasabi.Tests/UnitTests/SmartBlockProviderTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/PayjoinTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
  WalletWasabi/BitcoinCore/Rpc/IRPCClient.cs
  WalletWasabi/BitcoinCore/Rpc/RpcClientBase.cs
  WalletWasabi/Blockchain/Keys/HdPubKey.cs
  WalletWasabi/Crypto/Bip322Signature.cs
  WalletWasabi/Extensions/RPCClientExtensions.cs
  WalletWasabi/JsonConverters/BitcoinEncryptedSecretNoECJsonConverter.cs
  WalletWasabi/WabiSabi/Models/OutputRegistrationRequest.cs
  WalletWasabi/WalletWasabi.csproj
  WalletWasabi/packages.lock.json
Labels: size/L

#6408 Uncomment test commented by error
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
Labels: size/S

#6397 [Fluent] Refactor `TagsBox`
  WalletWasabi.Fluent/Controls/TagControl.axaml
  WalletWasabi.Fluent/Controls/TagControl.axaml.cs
  WalletWasabi.Fluent/Controls/TagsBox.axaml
  WalletWasabi.Fluent/Controls/TagsBox.axaml.cs
  WalletWasabi.Fluent/Converters/IntConverter.cs
  WalletWasabi.Fluent/Views/AddWallet/RecoverWalletView.axaml
Labels: size/L

#6386 [Fluent] add captions for buttons that open websites
  WalletWasabi.Fluent/ViewModels/HelpAndSupport/BugReportLinkViewModel.cs
  WalletWasabi.Fluent/ViewModels/HelpAndSupport/DocsLinkViewModel.cs
  WalletWasabi.Fluent/ViewModels/HelpAndSupport/UserSupportViewModel.cs
Labels: size/S

#6389 [Fluent] make private key icon different from public key icon
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletInfoView.axaml
Labels: size/S

#6384 [Fluent] Make texts selectable
  WalletWasabi.Fluent/Styles/TextBox.axaml
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/TransactionDetailsViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/TransactionDetailsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveAddressView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml
Labels: size/M

#6393 Fix logging logic in WindowsPowerAvailability
  WalletWasabi/Helpers/PowerSaving/WindowsPowerAvailabilityTask.cs
Labels: size/S

#6348 Clean up in SystemAwakeChecker
  WalletWasabi.Gui/Global.cs
  WalletWasabi/Services/SleepInhibitor.cs
Labels: size/L

#6380 `ShowQrCameraDialogViewModel`: Move code to `OnNavigatedTo` and add dispose logic
  WalletWasabi.Fluent/ViewModels/Dialogs/ShowQrCameraDialogViewModel.cs
Labels: size/M

#6411 Make all RPC calls cancellable
  WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/AllFeeEstimateTests.cs
  WalletWasabi.Tests/UnitTests/BitcoinCore/RpcBasedTests.cs
  WalletWasabi.Tests/UnitTests/MockRpcClient.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/ConfigTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/CoordinatorTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepInputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/Participant.cs
  WalletWasabi/BitcoinCore/CoreNode.cs
  WalletWasabi/BitcoinCore/Mempool/MempoolMirror.cs
  WalletWasabi/BitcoinCore/Monitoring/RpcFeeProvider.cs
  WalletWasabi/BitcoinCore/Processes/BitcoindRpcProcessBridge.cs
  WalletWasabi/BitcoinCore/Rpc/CachedRpcClient.cs
  WalletWasabi/BitcoinCore/Rpc/IRPCClient.cs
  WalletWasabi/BitcoinCore/Rpc/RpcClientBase.cs
  WalletWasabi/Blockchain/Blocks/BlockNotifier.cs
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
  WalletWasabi/Extensions/RPCClientExtensions.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/Wallets/P2pBlockProvider.cs
Labels: size/XL

#6421 [Fluent] Wrap receive addresses view labels
  WalletWasabi.Fluent/Styles/Button.axaml
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/AddressViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
  WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveAddressesView.axaml
Labels: size/M

#6400 [Fluent] Enter labels without pressing ENTER
  WalletWasabi.Fluent/Controls/TagsBox.axaml.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Labels/SuggestionLabelsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Labels: size/M

#6423 [WabiSabi] Use `OwnershipIdentifier`
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/Crypto/OwnershipProofTest.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/AliceTimeoutTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputSuccessTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi/Crypto/OwnershipIdentifier.cs
  WalletWasabi/Crypto/OwnershipProof.cs
  WalletWasabi/WabiSabi/Client/AliceClient.cs
  WalletWasabi/WabiSabi/Client/ArenaClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/L

#6414 [Fluent] Fix missing delete button on long Label
  WalletWasabi.Fluent/Controls/TagControl.axaml
Labels: size/XS

#6415 [Fluent] Navigation bar - Expand/Collapse manually
  WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
Labels: size/M

#6419 [Fluent] Recover wallet fixes
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
Labels: size/S

#6431 [Fluent][Trivial] Fix recovery words message
  WalletWasabi.Fluent/Views/AddWallet/RecoverWalletView.axaml
Labels: size/XS

#6434 `Wallet`: Make it impossible to stop twice
  WalletWasabi/Wallets/Wallet.cs
Labels: size/S

#6428 [Fluent] Add output descriptors
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletInfoViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletInfoView.axaml
  WalletWasabi.Tests/UnitTests/Blockchain/Keys/WpkhOutputDescriptorHelperTests.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/Blockchain/Keys/WpkhOutputDescriptorHelper.cs
Labels: size/L

#6435 Fix `CoinJoinManager` stopped
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Labels: size/XS

#6432 Add Wallet CoinJoin status
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WabiSabi/Client/WalletStatusChangedEventArgs.cs
Labels: size/S

#6436 Add CoinRefrigerator to CoinJoinManager
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WabiSabi/Client/CoinRefrigerator.cs
Labels: size/M

#6430 [WabiSabi] Compute round hash
  WalletWasabi/Crypto/StrobeProtocol/StrobeHasher.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
  WalletWasabi/WabiSabi/Crypto/RoundHasher.cs
  WalletWasabi/WabiSabi/Models/RoundState.cs
  WalletWasabi/WabiSabi/ProtocolContants.cs
Labels: size/L

#6425 [Fluent] Labels length limitation
  WalletWasabi.Fluent/Controls/TagsBox.axaml
  WalletWasabi.Fluent/Controls/TagsBox.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Labels: size/M
