Repository WalletWasabi/WalletWasabi, pull requests merged in 2021-05, with the labels that each got.

#5720 Fix null warnings
  WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoViewModel.cs
  WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletViewModel.cs
  WalletWasabi.Tests/UnitTests/Transactions/AllTransactionStoreTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionStoreTests.cs
  WalletWasabi.Tests/UnitTests/Userfacing/PasswordTests.cs
  WalletWasabi/Userfacing/PasswordHelper.cs
Labels: size/M

#5723 TorHttpPool: Add logs for OperationCanceledException.
  WalletWasabi/Tor/Socks5/Pool/TorHttpPool.cs
Labels: size/S

#5725 Remove unused parameter
  WalletWasabi.Tests/UnitTests/Transactions/PayjoinTests.cs
Labels: size/XS

#5731 Remove unused variable in MockedDeviceTests
  WalletWasabi.Tests/UnitTests/Hwi/MockedDeviceTests.cs
Labels: size/XS

#5733 Make Telementry disabling obvious
  README.md
Labels: size/XS

#5724 Tor control: Add Tokenizer and TorControlReplyReader.
  WalletWasabi.Tests/UnitTests/Tor/Control/Messages/ProtocolInfoReplyTests.cs
  WalletWasabi.Tests/UnitTests/Tor/Control/PipeWriterExtensions.cs
  WalletWasabi.Tests/UnitTests/Tor/Control/TorControlReplyReaderTests.cs
  WalletWasabi/Tor/Control/Exceptions/TorControlException.cs
  WalletWasabi/Tor/Control/Exceptions/TorControlReplyParseException.cs
  WalletWasabi/Tor/Control/Messages/ProtocolInfoReply.cs
  WalletWasabi/Tor/Control/Messages/TorControlReply.cs
  WalletWasabi/Tor/Control/PipeReaderLineReaderExtension.cs
  WalletWasabi/Tor/Control/ReplyCode.cs
  WalletWasabi/Tor/Control/TorControlReplyReader.cs
  WalletWasabi/Tor/Control/Utils/Tokenizer.cs
Labels: size/XL

#5737 Refactor EncodationStruct
  WalletWasabi/Gma/QrCodeNet/Encoding/DataEncodation/DataEncode.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/DataEncodation/EncodationStruct.cs
Labels: size/XS

#5736 Minor cleanup in Bob
  WalletWasabi/WabiSabi/Backend/Models/Bob.cs
Labels: size/S

#5689 [WabiSabi] Network messages serialization & Integration test
  WalletWasabi.Backend/Controllers/WabiSabiController.cs
  WalletWasabi.Backend/Startup.cs
  WalletWasabi.Tests/Helpers/HttpClientWrapper.cs
  WalletWasabi.Tests/RegressionTests/WabiSabi/IntegrationTest.cs
  WalletWasabi.Tests/RegressionTests/WabiSabi/WabiSabiApiApplicationFactory.cs
  WalletWasabi.Tests/RegressionTests/WabiSabi/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/AliceTimeoutTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/ConfirmConnectionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputSuccessTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputToBlameRoundTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterOutputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RemoveInputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/SignTransactionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/RequestHandlerDisposeTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/AliceClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/SerializationTests.cs
  WalletWasabi.Tests/WalletWasabi.Tests.csproj
  WalletWasabi/Tor/Http/Extensions/HttpResponseMessageExtensions.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/ArenaRequestHandler.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/IArenaRequestHandler.cs
  WalletWasabi/WabiSabi/Client/AliceClient.cs
  WalletWasabi/WabiSabi/Client/ArenaClient.cs
  WalletWasabi/WabiSabi/Client/BobClient.cs
  WalletWasabi/WabiSabi/Client/HttpRequestHandlerProxy.cs
  WalletWasabi/WabiSabi/Client/WabiSabiHttpApiClient.cs
  WalletWasabi/WabiSabi/Models/Serialization/JsonSerializationOptions.cs
  WalletWasabi/WabiSabi/Models/Serialization/OwnershipProofJsonConverter.cs
  WalletWasabi/WabiSabi/Models/Serialization/WitScriptJsonConverter.cs
Labels: size/XL

#5727 Produce coverage reports in Linux & OSX Azure pipelines
  azure-pipelines-linux.yml
  azure-pipelines-osx.yml
Labels: size/M

#5739 [WabiSabi] Create AliceClient w/o backend
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/AliceClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
  WalletWasabi/WabiSabi/Client/AliceClient.cs
Labels: size/M

#5595 [Fluent] Add ResponsiveLayout for ItemsRepeater
  WalletWasabi.Fluent/Controls/NonVirtualizingResponsiveLayout.cs
  WalletWasabi.Fluent/Controls/ResponsivePanel.cs
  WalletWasabi.Fluent/Controls/ResponsivePanelState.cs
  WalletWasabi.Fluent/Converters/ColumnHintsConverter.cs
  WalletWasabi.Fluent/Converters/WidthTriggersConverter.cs
  WalletWasabi.Fluent/ViewModels/ResponsivePanelDemo/ResponsiveLayoutDemoViewModel.cs
  WalletWasabi.Fluent/ViewModels/ResponsivePanelDemo/TestTileItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/TileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/Views/ResponsivePanelDemo/ResponsiveLayoutDemoView.axaml
  WalletWasabi.Fluent/Views/ResponsivePanelDemo/ResponsiveLayoutDemoView.axaml.cs
  WalletWasabi.Fluent/Views/ResponsivePanelDemo/ResponsivePanelDemoView.axaml
  WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
Labels: size/XL

#5740 Uppercase QR encoded bech32 addresses
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressViewModel.cs
  WalletWasabi.Gui/ViewModels/AddressViewModel.cs
Labels: size/XS

#5744 Remove warnings related to FileSystemBlockRepository
  WalletWasabi/Wallets/CachedBlockProvider.cs
  WalletWasabi/Wallets/FileSystemBlockRepository.cs
  WalletWasabi/Wallets/IRepository.cs
Labels: size/XS

#5746 Rename GetAsync related to IRepository
  WalletWasabi/Wallets/CachedBlockProvider.cs
  WalletWasabi/Wallets/FileSystemBlockRepository.cs
  WalletWasabi/Wallets/IRepository.cs
Labels: size/XS

#5697 Vdg/fluent polish receive
  WalletWasabi.Fluent/App.axaml
  WalletWasabi.Fluent/Controls/AdorningContentControl.axaml
  WalletWasabi.Fluent/Controls/AdorningContentControl.axaml.cs
  WalletWasabi.Fluent/Controls/AnimatedButton.axaml.cs
  WalletWasabi.Fluent/Controls/ConcatenatingWrapPanel.cs
  WalletWasabi.Fluent/Controls/QuestionControl.axaml
  WalletWasabi.Fluent/Controls/QuestionControl.axaml.cs
  WalletWasabi.Fluent/Controls/TagControl.axaml
  WalletWasabi.Fluent/Controls/TagsBox.axaml
  WalletWasabi.Fluent/Controls/TagsBox.axaml.cs
  WalletWasabi.Fluent/Helpers/AdornerHelper.cs
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/Styles/DataGrid.axaml
  WalletWasabi.Fluent/Styles/TextBox.axaml
  WalletWasabi.Fluent/Styles/Themes/Base.axaml
  WalletWasabi.Fluent/ViewModels/Dialogs/ConfirmHideAddressViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/AddressViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressesViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/HardwareWallet/DetectedHardwareWalletView.axaml
  WalletWasabi.Fluent/Views/Dialogs/AboutAdvancedInfoView.axaml
  WalletWasabi.Fluent/Views/Dialogs/ConfirmHideAddressView.axaml
  WalletWasabi.Fluent/Views/Dialogs/InsufficientBalanceDialogView.axaml
  WalletWasabi.Fluent/Views/HelpAndSupport/AboutView.axaml
  WalletWasabi.Fluent/Views/Login/PasswordFinder/ContainsNumbersView.axaml
  WalletWasabi.Fluent/Views/Login/PasswordFinder/ContainsSymbolsView.axaml
  WalletWasabi.Fluent/Views/Login/PasswordFinder/PasswordNotFoundView.axaml
  WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveAddressView.axaml
  WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveAddressesView.axaml
  WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Labels: size/XL

#5735 [Fluent] Transaction History finishing off tasks
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
Labels: size/M

#5738 [Fluent] Fix dialog closing when changing window state
  WalletWasabi.Fluent/Controls/Dialog.axaml.cs
Labels: size/XS

#5754 [Fluent] Fix DataGrid sorting on SmartLabels
  WalletWasabi/Blockchain/Analysis/Clustering/SmartLabel.cs
Labels: size/S

#5753 [Fluent] Receive autocopy
  WalletWasabi.Fluent/Controls/AnimatedButton.axaml.cs
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/AddressViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressesViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveAddressView.axaml
Labels: size/M

#5755 Implement TorControlClient and test.
  WalletWasabi.Backend/Controllers/BlockchainController.cs
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Tests/UnitTests/Tor/Control/TorControlFactoryTests.cs
  WalletWasabi/BitcoinCore/Mempool/MempoolMirror.cs
  WalletWasabi/BitcoinCore/P2pNode.cs
  WalletWasabi/BitcoinP2p/TrustedP2pBehavior.cs
  WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs
  WalletWasabi/Tor/Control/TorControlClient.cs
  WalletWasabi/Tor/Control/TorControlClientFactory.cs
Labels: size/XL

#5763 Revert "Implement TorControlClient and test."
  WalletWasabi.Backend/Controllers/BlockchainController.cs
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Tests/UnitTests/Tor/Control/TorControlFactoryTests.cs
  WalletWasabi/BitcoinCore/Mempool/MempoolMirror.cs
  WalletWasabi/BitcoinCore/P2pNode.cs
  WalletWasabi/BitcoinP2p/TrustedP2pBehavior.cs
  WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs
  WalletWasabi/Tor/Control/TorControlClient.cs
  WalletWasabi/Tor/Control/TorControlClientFactory.cs
Labels: size/XL

#5770 Fix backend
  WalletWasabi.Backend/Controllers/WabiSabiController.cs
Labels: size/S

#5771 Use 'using' keyword to dispose objects and fix warnings
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/UnitTests/CoordinatorRoundTests.cs
Labels: size/XS

#5769 Fix WabiSabiController
  WalletWasabi.Backend/Controllers/WabiSabiController.cs
  WalletWasabi.Backend/Startup.cs
Labels: priority, size/S

#5750 [WabiSabi] IdempotentAttribute for WabiSabi API actions
  WalletWasabi.Backend/Controllers/WabiSabiController.cs
  WalletWasabi.Backend/Filters/IdempotentActionFilterAttributeImpl.cs
  WalletWasabi.Backend/Filters/IdempotentAttribute.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/Filters/IdempotencyActionFilterTests.cs
Labels: size/L

#5776 Fix null warning
  WalletWasabi.Gui/Controls/ExtendedTextBox.cs
Labels: size/XS

#5781 Resolve null warning in BitcoinAddressJsonConverter.cs
  WalletWasabi/JsonConverters/BitcoinAddressJsonConverter.cs
Labels: size/XS

#5784 Fix warning in TransactionFactoryTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
Labels: size/XS

#5783 Update NBitcoin (Tails Fix)
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/packages.lock.json
  WalletWasabi.Gui/packages.lock.json
  WalletWasabi.Packager/packages.lock.json
  WalletWasabi/WalletWasabi.csproj
  WalletWasabi/packages.lock.json
Labels: size/M

#5787 Move FilterProcessor inside the Synchronizer
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Tests/RegressionTests/BuildTests.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi.Tests/RegressionTests/WalletTests.cs
  WalletWasabi/Blockchain/BlockFilters/FilterProcessor.cs
  WalletWasabi/Services/WasabiSynchronizer.cs
Labels: size/M

#5772 [Fluent] Notifications
  WalletWasabi.Fluent/Behaviors/RegisterNotificationHostBehavior.cs
  WalletWasabi.Fluent/Converters/MoneyConverters.cs
  WalletWasabi.Fluent/Helpers/NotificationHelpers.cs
  WalletWasabi.Fluent/Helpers/TextHelpers.cs
  WalletWasabi.Fluent/Styles/Themes/Base.axaml
  WalletWasabi.Fluent/Styles/Themes/BaseDark.axaml
  WalletWasabi.Fluent/Styles/Themes/BaseLight.axaml
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/Views/MainWindow.axaml
Labels: size/L

#5780 Send / Receive Buttons in Wallet Home Page
  WalletWasabi.Fluent/Controls/ContentArea.axaml
  WalletWasabi.Fluent/Controls/ContentArea.axaml.cs
  WalletWasabi.Fluent/Styles/ActionButton.axaml
  WalletWasabi.Fluent/Styles/Button.axaml
  WalletWasabi.Fluent/Styles/InvisibleButton.axaml
  WalletWasabi.Fluent/Styles/PlainButton.axaml
  WalletWasabi.Fluent/Styles/Styles.axaml
  WalletWasabi.Fluent/Styles/Themes/BaseDark.axaml
  WalletWasabi.Fluent/Styles/Themes/BaseLight.axaml
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/HardwareWallet/HardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WatchOnlyWallet/WatchOnlyWalletViewModel.cs
  WalletWasabi.Fluent/Views/MainView.axaml
  WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
Labels: size/L

#5792 [Trivial] [Fluent] Fix formatting and use tabs instead of spaces
  WalletWasabi.Fluent/Controls/ResponsivePanelState.cs
  WalletWasabi.Fluent/Controls/TagsBox.axaml.cs
  WalletWasabi.Fluent/Helpers/AdornerHelper.cs
  WalletWasabi.Fluent/Helpers/EnumerableExtensions.cs
  WalletWasabi.Fluent/Helpers/StraightLineFormula.cs
  WalletWasabi.Fluent/Helpers/TextHelpers.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletBalanceChartTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletPieChartTileViewModel.cs
Labels: size/M

#5791 [Trivial] Remove Async prefix from method
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
Labels: size/XS

#5793 Fix null warnings
  WalletWasabi/JsonConverters/FilterModelJsonConverter.cs
  WalletWasabi/JsonConverters/KeyJsonConverter.cs
  WalletWasabi/JsonConverters/NetworkJsonConverter.cs
  WalletWasabi/JsonConverters/Uint256JsonConverter.cs
Labels: size/XS

#5794 Update NBitcoin (Up-to-date Seeds)
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/packages.lock.json
  WalletWasabi.Gui/packages.lock.json
  WalletWasabi.Packager/packages.lock.json
  WalletWasabi/WalletWasabi.csproj
  WalletWasabi/packages.lock.json
Labels: size/M

#5762 [Fluent] Draggable wallets
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/Controls/NavBarItem.axaml
  WalletWasabi.Fluent/Converters/NavBarActionsOrientationConverter.cs
  WalletWasabi.Fluent/Converters/NavBarItemsListBoxAlignmentConverter.cs
  WalletWasabi.Fluent/Styles/Themes/BaseDark.axaml
  WalletWasabi.Fluent/Styles/Themes/BaseLight.axaml
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Actions/AdvancedWalletActionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Actions/CoinJoinWalletActionViewModel.cs
  WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
  WalletWasabi.Fluent/Views/Settings/SettingsPageView.axaml
  WalletWasabi.Fluent/Views/Wallets/Actions/AdvancedWalletActionView.axaml
  WalletWasabi.Fluent/Views/Wallets/Actions/AdvancedWalletActionView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Actions/CoinJoinWalletActionView.axaml
  WalletWasabi.Fluent/Views/Wallets/Actions/CoinJoinWalletActionView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Actions/ReceiveWalletActionView.axaml
  WalletWasabi.Fluent/Views/Wallets/Actions/ReceiveWalletActionView.axaml.cs
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
Labels: size/XL

#5786 Fix some null warnings in CoinJoinTests.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
Labels: size/XS

#5798 minor navbar polish
  WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
Labels: size/M

#5797 [Fluent] QuestionControl fixes
  WalletWasabi.Fluent/Controls/QuestionControl.axaml
  WalletWasabi.Fluent/Controls/QuestionControl.axaml.cs
  WalletWasabi.Fluent/Views/AddWallet/HardwareWallet/DetectedHardwareWalletView.axaml
  WalletWasabi.Fluent/Views/Dialogs/ConfirmHideAddressView.axaml
  WalletWasabi.Fluent/Views/Dialogs/InsufficientBalanceDialogView.axaml
  WalletWasabi.Fluent/Views/Login/PasswordFinder/ContainsNumbersView.axaml
  WalletWasabi.Fluent/Views/Login/PasswordFinder/ContainsSymbolsView.axaml
  WalletWasabi.Fluent/Views/Login/PasswordFinder/PasswordNotFoundView.axaml
Labels: size/M

#5795 [Fluent] Address label edit
  WalletWasabi.Fluent/Controls/TagsBox.axaml.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/AddressLabelEditViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/AddressViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressesViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Receive/AddressLabelEditView.axaml
  WalletWasabi.Fluent/Views/Wallets/Receive/AddressLabelEditView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveAddressesView.axaml
Labels: size/L

#5800 Update NBitcoin
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/packages.lock.json
  WalletWasabi.Gui/packages.lock.json
  WalletWasabi.Packager/packages.lock.json
  WalletWasabi/WalletWasabi.csproj
  WalletWasabi/packages.lock.json
Labels: size/M

#5801 [Fluent] Add Services class to fluent project
  WalletWasabi.Fluent.Desktop/Program.cs
  WalletWasabi.Fluent/App.axaml.cs
  WalletWasabi.Fluent/Services.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/AddedWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/ConfirmRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/RecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/ConnectHardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/DetectedHardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/LoginViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/OpenDirectory/OpenConfigFileViewModel.cs
  WalletWasabi.Fluent/ViewModels/OpenDirectory/OpenDataFolderViewModel.cs
  WalletWasabi.Fluent/ViewModels/OpenDirectory/OpenTorLogsViewModel.cs
  WalletWasabi.Fluent/ViewModels/OpenDirectory/OpenWalletsFolderViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/BitcoinTabSettingsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/GeneralSettingsTabViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/NetworkSettingsTabViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/PrivacyModeViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/PrivacySettingsTabViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/SettingsPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/SettingsTabViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/BroadcastTransactionViewModel.cs
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/ClosedWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/HardwareWallet/HardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/AddressViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressesViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/OptimisePrivacyViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WatchOnlyWallet/WatchOnlyWalletViewModel.cs
Labels: size/XL

#5799 Fix home screen hw wallet
  WalletWasabi.Fluent/ViewModels/Wallets/ClosedHardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/ClosedWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/ClosedWatchOnlyWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/HardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WatchOnlyWalletViewModel.cs
  WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
  WalletWasabi.Fluent/Views/Wallets/ClosedHardwareWalletView.axaml
  WalletWasabi.Fluent/Views/Wallets/ClosedHardwareWalletView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/HardwareWalletView.axaml
  WalletWasabi.Fluent/Views/Wallets/HardwareWalletView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
Labels: size/M

#5802 add a guard to services.
  WalletWasabi.Fluent/Services.cs
Labels: size/S

#5803 Fluent UiServices
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/ConnectHardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/UiServices.cs
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/AddressViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressesViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/OptimisePrivacyViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendSuccessViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
Labels: size/L

#5796 Fix warning in TransactionStoreTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionStoreTests.cs
Labels: size/XS

#5807 Fix line endings
  WalletWasabi.Fluent/Behaviors/AddClassAction.cs
  WalletWasabi.Fluent/Controls/AnimatedButton.axaml.cs
  WalletWasabi.Fluent/Controls/NonVirtualizingResponsiveLayout.cs
  WalletWasabi.Fluent/Controls/ResponsivePanel.cs
  WalletWasabi.Fluent/Controls/ResponsivePanelState.cs
  WalletWasabi.Fluent/Helpers/AuthorizationHelpers.cs
  WalletWasabi.Fluent/MathNet/CubicSpline.cs
  WalletWasabi.Fluent/MathNet/SplineBoundaryCondition.cs
  WalletWasabi.Fluent/Model/TransactionAuthorizationInfo.cs
  WalletWasabi.Fluent/Services.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/Authorization/AuthorizationDialogBase.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/Authorization/HardwareWalletAuthDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/ConfirmHideAddressViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/InsufficientBalanceDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/AddressViewModel.cs
  WalletWasabi.Fluent/Views/ResponsivePanelDemo/ResponsiveLayoutDemoView.axaml.cs
  WalletWasabi.Fluent/Views/ResponsivePanelDemo/ResponsivePanelDemoView.axaml.cs
  WalletWasabi/Models/FriendlyNameAttribute.cs
Labels: size/M

#5811 Fix null warning
  WalletWasabi.Tests/RegressionTests/BuildTests.cs
Labels: size/XS

#5767 [WabiSabi] GetStatus API and End-to-End integration test as template.
  WalletWasabi.Backend/Controllers/WabiSabiController.cs
  WalletWasabi.Backend/Filters/ExceptionTranslateFilter.cs
  WalletWasabi.Backend/Filters/IdempotentActionFilterAttributeImpl.cs
  WalletWasabi.Backend/Startup.cs
  WalletWasabi.Tests/Helpers/BitcoinFactory.cs
  WalletWasabi.Tests/Helpers/HttpClientWrapper.cs
  WalletWasabi.Tests/Helpers/HttpRequestMessageExtensions.cs
  WalletWasabi.Tests/RegressionTests/WabiSabi/IntegrationTest.cs
  WalletWasabi.Tests/RegressionTests/WabiSabi/WabiSabiApiApplicationFactory.cs
  WalletWasabi.Tests/RegressionTests/WabiSabi/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/Filters/IdempotencyActionFilterTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/AliceClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/BackgroundServiceStarter.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/Startup.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiApiApplicationFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/SerializationTests.cs
  WalletWasabi/JsonConverters/Bitcoin/FeeRateJsonConverter.cs
  WalletWasabi/Tor/Http/Extensions/HttpResponseMessageExtensions.cs
  WalletWasabi/WabiSabi/Backend/Models/WabiSabiProtocolException.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/ArenaRequestHandler.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/IWabiSabiApiRequestHandler.cs
  WalletWasabi/WabiSabi/Client/ArenaClient.cs
  WalletWasabi/WabiSabi/Client/WabiSabiHttpApiClient.cs
  WalletWasabi/WabiSabi/Models/Error.cs
  WalletWasabi/WabiSabi/Models/RoundState.cs
  WalletWasabi/WabiSabi/Models/Serialization/IStateJsonConverter.cs
  WalletWasabi/WabiSabi/Models/Serialization/JsonSerializationOptions.cs
  WalletWasabi/WabiSabi/ProtocolContants.cs
Labels: size/XL

#5806 [Fluent] NavBar wallet icons by type
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/RoutableViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/ClosedWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModelBase.cs
Labels: size/M

#5813 Fix some null warnings
  WalletWasabi.Tests/UnitTests/Userfacing/ParserTests.cs
Labels: size/XS

#5814 Update YouTube url
  README.md
Labels: size/XS

#5817 [WabiSabi] IState rename & refactoring
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/SignTransactionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/InputRegistrationHandler.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
  WalletWasabi/WabiSabi/Backend/Rounds/RoundParameters.cs
  WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/ConstructionState.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/IState.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/IStateExtensions.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/MultipartyTransactionParameters.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/MultipartyTransactionState.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/SigningState.cs
  WalletWasabi/WabiSabi/Models/RoundState.cs
  WalletWasabi/WabiSabi/Models/Serialization/JsonSerializationOptions.cs
  WalletWasabi/WabiSabi/Models/Serialization/MultipartyTransactionStateJsonConverter.cs
  WalletWasabi/WabiSabi/ProtocolContants.cs
Labels: size/L

#5818 make iconname protected setter.
  WalletWasabi.Fluent/ViewModels/Navigation/RoutableViewModel.cs
Labels: size/XS

#5826 [Trivial] Fix naming violations
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/BackgroundServiceStarter.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/ConstructionState.cs
Labels: size/S

#5828 [Fluent] Update Avalonia to 0.10.5
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
Labels: size/L

#5820 [Fluent] Wallet home page tile control redesign
  WalletWasabi.Fluent/Behaviors/BoundsObserverBehavior.cs
  WalletWasabi.Fluent/Behaviors/HorizontalScrollViewerBehavior.cs
  WalletWasabi.Fluent/Controls/BindableGrid.cs
  WalletWasabi.Fluent/Converters/TilesPositionConverter.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/TileLayoutViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/TilePresetViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/TileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
  WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
Labels: size/XL

#5836 [Trivial][Fluent] Set binding in style
  WalletWasabi.Fluent/Views/AddWallet/AddWalletPageView.axaml
Labels: size/S

#5834 [WabiSabi] Add alternative stateless decomposer
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/GreedyDecomposerTests.cs
  WalletWasabi/WabiSabi/Client/GreedyDecomposer.cs
Labels: size/L

#5842 [Trivial] Remove unused variable
  WalletWasabi.Backend/Filters/ExceptionTranslateFilter.cs
  WalletWasabi.Backend/Filters/IdempotentActionFilterAttributeImpl.cs
Labels: size/S

#5846 Remove unused parameter
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi/WabiSabi/Client/AliceClient.cs
  WalletWasabi/WabiSabi/Client/ArenaClient.cs
Labels: size/S

#5592 [Fluent] QRCodeReader implementation
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/QRCodeDecoder/Corner.cs
  WalletWasabi.Fluent/QRCodeDecoder/EncodingMode.cs
  WalletWasabi.Fluent/QRCodeDecoder/ErrorCorrection.cs
  WalletWasabi.Fluent/QRCodeDecoder/Finder.cs
  WalletWasabi.Fluent/QRCodeDecoder/QRDecoder.cs
  WalletWasabi.Fluent/QRCodeDecoder/ReedSolomon.cs
  WalletWasabi.Fluent/QRCodeDecoder/StaticTables.cs
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
  WalletWasabi.Tests/UnitTests/QrCode/QrCodeDecodingTests.cs
  WalletWasabi.Tests/UnitTests/QrCode/QrTestResources/AddressTest1.png
  WalletWasabi.Tests/UnitTests/QrCode/QrTestResources/AddressTest2.png
  WalletWasabi.Tests/UnitTests/QrCode/QrTestResources/DoubleQRCode.png
  WalletWasabi.Tests/UnitTests/QrCode/QrTestResources/NotBitcoinAddress.jpg
  WalletWasabi.Tests/UnitTests/QrCode/QrTestResources/Payment_details_included.jpg
  WalletWasabi.Tests/UnitTests/QrCode/QrTestResources/QRBrick.jpg
  WalletWasabi.Tests/UnitTests/QrCode/QrTestResources/QRwithZebraBackground.png
  WalletWasabi.Tests/UnitTests/QrCode/QrTestResources/QrByPhone.jpg
  WalletWasabi.Tests/UnitTests/QrCode/QrTestResources/Random_address_starting_with_1.png
  WalletWasabi.Tests/UnitTests/QrCode/QrTestResources/Text_QR-code.png
  WalletWasabi.Tests/UnitTests/QrCode/QrTestResources/mouseOverQR.jpg
  WalletWasabi.Tests/WalletWasabi.Tests.csproj
Labels: feature/enhancement

#5851 [Fluent] Remove CJ filter leftover code
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
  WalletWasabi.Gui/UiConfig.cs
Labels: size/M

#5835 [Fluent] Fix `Generic` wallet icon
  WalletWasabi.Fluent/Converters/WalletIconConverter.cs
  WalletWasabi.Fluent/Helpers/WalletHelpers.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/AddedWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/Authorization/HardwareWalletAuthDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/LoginViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/AddedWalletPageView.axaml
  WalletWasabi.Fluent/Views/Dialogs/Authorization/HardwareWalletAuthDialogView.axaml
  WalletWasabi.Fluent/Views/Login/LoginView.axaml
Labels: size/L

#5694 [WabiSabi] CoinJoinClient skeleton
  WalletWasabi.Backend/Filters/IdempotentActionFilterAttributeImpl.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/CoinJoinClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/SerializationTests.cs
  WalletWasabi/Extensions/LinqExtensions.cs
  WalletWasabi/WabiSabi/Client/AliceClient.cs
  WalletWasabi/WabiSabi/Client/BobClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/ConstructionState.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/SigningState.cs
  WalletWasabi/WabiSabi/Models/RoundState.cs
  WalletWasabi/WabiSabi/Models/Serialization/MultipartyTransactionStateJsonConverter.cs
Labels: size/XL

#5833 [WabiSabi] Generate the base denominations
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/AmountDecompositionTests.cs
  WalletWasabi/WabiSabi/Models/Decomposition/BaseDenomGenerator.cs
Labels: size/M

#5819 Use fixed Tor socks to ensure launching our own Tor process
  WalletWasabi.Documentation/Ports.md
  WalletWasabi.Fluent/ViewModels/Settings/NetworkSettingsTabViewModel.cs
  WalletWasabi.Fluent/Views/Settings/NetworkSettingsTabView.axaml
  WalletWasabi.Gui/Config.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Gui/Tabs/SettingsView.xaml
  WalletWasabi.Gui/Tabs/SettingsViewModel.cs
  WalletWasabi.Tests/Helpers/Common.cs
  WalletWasabi.Tests/IntegrationTests/BlockstreamInfoTests.cs
  WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
  WalletWasabi.Tests/IntegrationTests/TorTests.cs
  WalletWasabi.Tests/UnitTests/Tor/Control/TorControlReplyReaderTests.cs
  WalletWasabi.Tests/UnitTests/Tor/TorSettingsTests.cs
  WalletWasabi/Helpers/Constants.cs
  WalletWasabi/Tor/Control/ReplyCode.cs
  WalletWasabi/Tor/Control/TorControlClient.cs
  WalletWasabi/Tor/TorProcessManager.cs
  WalletWasabi/Tor/TorSettings.cs
Labels: size/L

#5848 Tor control & protocol info reply parsing
  WalletWasabi.Tests/UnitTests/Tor/Control/Messages/GetInfoCircuitStatusReplyTests.cs
  WalletWasabi/Tor/Control/Messages/CircuitStatus/BuildFlag.cs
  WalletWasabi/Tor/Control/Messages/CircuitStatus/CircPath.cs
  WalletWasabi/Tor/Control/Messages/CircuitStatus/CircStatus.cs
  WalletWasabi/Tor/Control/Messages/CircuitStatus/CircuitInfo.cs
  WalletWasabi/Tor/Control/Messages/CircuitStatus/HsState.cs
  WalletWasabi/Tor/Control/Messages/CircuitStatus/Purpose.cs
  WalletWasabi/Tor/Control/Messages/CircuitStatus/Reason.cs
  WalletWasabi/Tor/Control/Messages/GetInfoCircuitStatusReply.cs
  WalletWasabi/Tor/Control/Messages/ProtocolInfoReply.cs
  WalletWasabi/Tor/Control/Messages/TorControlReply.cs
  WalletWasabi/Tor/Control/TorControlClient.cs
  WalletWasabi/Tor/Control/Utils/Tokenizer.cs
Labels: size/XL

#5855 [Fluent] Create Wallet - separate wallet name and options
  WalletWasabi.Fluent/Controls/TileButton.axaml
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/SelectWalletCreationOptionViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/AddWalletPageView.axaml
  WalletWasabi.Fluent/Views/AddWallet/SelectWalletCreationOptionView.axaml
  WalletWasabi.Fluent/Views/AddWallet/SelectWalletCreationOptionView.axaml.cs
Labels: size/L

#5852 [WabiSabi] Add RoundStatusUpdater
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/CoinJoinClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/RoundStatusUpdaterTests.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/RoundStateAwaiter.cs
  WalletWasabi/WabiSabi/Client/RoundStateUpdater.cs
Labels: size/L

#5853 [Fluent] Transaction History - flash row on receive
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
Labels: size/S

#5857 [WabiSabi] Simplify RoundStateUpdater
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/RoundStateUpdaterTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/RoundStatusUpdaterTests.cs
  WalletWasabi/WabiSabi/Client/RoundStateAwaiter.cs
  WalletWasabi/WabiSabi/Client/RoundStateUpdater.cs
Labels: size/L

#5751 TorHttpClient with better Tor circuit selection support
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
  WalletWasabi.Gui/Global.cs
  WalletWasabi.Tests/IntegrationTests/TorTests.cs
  WalletWasabi.Tests/UnitTests/Tor/Socks5/TorHttpPoolTests.cs
  WalletWasabi.Tests/UnitTests/Tor/Socks5/TorTcpConnectionFactoryTests.cs
  WalletWasabi/AssemblyInfo.cs
  WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs
  WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
  WalletWasabi/Tor/Http/TorHttpClient.cs
  WalletWasabi/Tor/Socks5/Models/Fields/ByteArrayFields/MethodsField.cs
  WalletWasabi/Tor/Socks5/Pool/Circuits/DefaultCircuit.cs
  WalletWasabi/Tor/Socks5/Pool/Circuits/ICircuit.cs
  WalletWasabi/Tor/Socks5/Pool/Circuits/Mode.cs
  WalletWasabi/Tor/Socks5/Pool/Circuits/OneOffCircuit.cs
  WalletWasabi/Tor/Socks5/Pool/Circuits/PersonCircuit.cs
  WalletWasabi/Tor/Socks5/Pool/TorHttpPool.cs
  WalletWasabi/Tor/Socks5/TorTcpConnection.cs
  WalletWasabi/Tor/Socks5/TorTcpConnectionFactory.cs
  WalletWasabi/WebClients/BlockstreamInfo/BlockstreamInfoClient.cs
  WalletWasabi/WebClients/Wasabi/HttpClientFactory.cs
Labels: size/L

#5815 Fix null warnings
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
  WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
  WalletWasabi/Extensions/NBitcoinExtensions.cs
Labels: size/M

#5865 [Fluent] Add small, normal and wide tile views
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/TilePresetViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/TileSize.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/TileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/BtcPrice/BtcPriceNormalTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/BtcPrice/BtcPriceNormalTileView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/BtcPrice/BtcPriceSmallTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/BtcPrice/BtcPriceSmallTileView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/BtcPrice/BtcPriceWideTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/BtcPrice/BtcPriceWideTileView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/BtcPriceTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/RoundStatus/RoundStatusNormalTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/RoundStatus/RoundStatusNormalTileView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/RoundStatus/RoundStatusSmallTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/RoundStatus/RoundStatusSmallTileView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/RoundStatus/RoundStatusWideTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/RoundStatus/RoundStatusWideTileView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/RoundStatusTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalance/WalletBalanceNormalTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalance/WalletBalanceNormalTileView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalance/WalletBalanceSmallTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalance/WalletBalanceSmallTileView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalance/WalletBalanceWideTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalance/WalletBalanceWideTileView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceChart/WalletBalanceChartNormalTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceChart/WalletBalanceChartNormalTileView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceChart/WalletBalanceChartSmallTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceChart/WalletBalanceChartSmallTileView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceChart/WalletBalanceChartWideTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceChart/WalletBalanceChartWideTileView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceChartTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletPieChart/WalletPieChartNormalTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletPieChart/WalletPieChartNormalTileView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletPieChart/WalletPieChartSmallTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletPieChart/WalletPieChartSmallTileView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletPieChart/WalletPieChartWideTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletPieChart/WalletPieChartWideTileView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletPieChartTileView.axaml
Labels: size/XXL

#5867 Remove Ubuntu 16.04 from compatibility list
  WalletWasabi.Documentation/WasabiCompatibility.md
Labels: size/XS

#5854 [WabiSabi] Remove CoinJoinClient background service
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/AliceClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/CoinJoinClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/MultipartyTransactionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/RoundStateUpdaterTests.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
  WalletWasabi/WabiSabi/Client/AliceClient.cs
  WalletWasabi/WabiSabi/Client/ArenaClient.cs
  WalletWasabi/WabiSabi/Client/BobClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/ConstructionState.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/MultipartyTransactionParameters.cs
Labels: size/L

#5868 [WabiSabi] Fix Timouting RoundStateUpdaterTestsAsync
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/RoundStateUpdaterTests.cs
Labels: size/S
