Repository WalletWasabi/WalletWasabi, pull requests merged in 2022-08, with the labels that each got.

#8813 [VDG] Simplify AnySelected in Coins List
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/WalletCoinsView.axaml
Labels: size/S

#7837 `Packager`: Fix for WSL2
  WalletWasabi.Packager/Program.cs
  WalletWasabi.Packager/Tools.cs
Labels: size/M

#8821 `WasabiSynchronizer`: Fix exception being handled.
  WalletWasabi/Services/WasabiSynchronizer.cs
Labels: size/XS

#8809 [VDG] Trace all info in exception on app crash
  WalletWasabi.Fluent.Desktop/Program.cs
  WalletWasabi.Fluent/CrashReport/ViewModels/CrashReportWindowViewModel.cs
  WalletWasabi/Models/SerializableException.cs
Labels: size/S

#8828 [VDG] remove unnecessary using directive in AddressViewmodel
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/AddressViewModel.cs
Labels: size/XS

#8829 [VDG] lowercase writing not coinjoining tooltip
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/Columns/IndicatorsColumnView.axaml
Labels: size/XS

#8810 `HttpMessageHelper`: Change exception being thrown
  WalletWasabi/Tor/Http/Helpers/HttpMessageHelper.cs
  WalletWasabi/Tor/Socks5/Pool/TorHttpPool.cs
Labels: size/M

#8845 [VDG] [Trivial] Replace coinjoin icon
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/Columns/IndicatorsColumnView.axaml
Labels: size/XS

#8741 Make software update flow better
  WalletWasabi.Fluent.Desktop/Program.cs
  WalletWasabi.Fluent/Config.cs
  WalletWasabi.Fluent/Global.cs
  WalletWasabi.Fluent/Services.cs
  WalletWasabi.Fluent/ViewModels/Settings/GeneralSettingsTabViewModel.cs
  WalletWasabi.Fluent/ViewModels/StatusIcon/StatusIconViewModel.cs
  WalletWasabi.Fluent/Views/Settings/GeneralSettingsTabView.axaml
  WalletWasabi.Fluent/Views/StatusIcon/StatusIcon.axaml
  WalletWasabi/Models/UpdateStatus.cs
  WalletWasabi/Services/UpdateManager.cs
Labels: size/L

#8844 [VDG] CurrencyEntryBox - fix divide by zero crash
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
Labels: size/XS

#8847 [VDG] Fix DualCurrencyEntryBox bug when ConversionRate is zero
  WalletWasabi.Fluent/Controls/DualCurrencyEntryBox.axaml
  WalletWasabi.Fluent/Controls/DualCurrencyEntryBox.axaml.cs
Labels: size/M

#8801 Add support for Ledger Nano S+
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/DetectedHardwareWalletViewModel.cs
  WalletWasabi.Tests/AcceptanceTests/HwiKatas.cs
  WalletWasabi/Hwi/Models/HardwareWalletModels.cs
Labels: size/M

#8342 [VDG] Add Enable GPU setting
  WalletWasabi.Fluent.Desktop/Extensions/AppBuilderExtension.cs
  WalletWasabi.Fluent/Config.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/Sources/SettingsSource.cs
  WalletWasabi.Fluent/ViewModels/Settings/AdvancedSettingsTabViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/BitcoinTabSettingsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/SettingsPageViewModel.cs
  WalletWasabi.Fluent/Views/Settings/AdvancedSettingsTabView.axaml
  WalletWasabi.Fluent/Views/Settings/AdvancedSettingsTabView.axaml.cs
  WalletWasabi.Fluent/Views/Settings/SettingsPageView.axaml
Labels: size/L

#8849 [VDG] Add Coinjoin Settings dialog
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinSettingsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendFeeViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletSettingsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/CoinJoinSettingsView.axaml
  WalletWasabi.Fluent/Views/Wallets/CoinJoinSettingsView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/WalletSettingsView.axaml
  WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
Labels: size/L

#8861 Simplify `TorHttpPool.CreateNewConnectionAsync`
  WalletWasabi/Tor/Socks5/Pool/TorHttpPool.cs
Labels: size/S

#8437 [VDG] Searchbar Flyout logic Review & Fix
  WalletWasabi.Fluent/Behaviors/SearchBarBehavior.cs
  WalletWasabi.Fluent/Behaviors/ShowAttachedFlyoutWhenFocusedBehavior.cs
  WalletWasabi.Fluent/Behaviors/TextBoxAutoSelectTextBehavior.cs
  WalletWasabi.Fluent/Extensions/AvaloniaMixin.cs
  WalletWasabi.Fluent/Helpers/FlyoutShowController.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/SearchBarViewModel.cs
  WalletWasabi.Fluent/Views/MainWindow.axaml
  WalletWasabi.Fluent/Views/SearchBar/SearchBar.axaml
  WalletWasabi.Fluent/Views/SearchBar/SearchBarDropdown.axaml
Labels: size/L

#8822 [VDG] Improve Coin List
  WalletWasabi.Fluent/Extensions/DynamicDataMixin.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/WalletCoinsView.axaml
Labels: size/L

#8826 [Trivial] Add latest Bitcoin Core version to Constants.UserAgents
  WalletWasabi/Helpers/Constants.cs
Labels: size/M

#8872 [Trivial] Fix CodeFactor issues
  WalletWasabi.Fluent/Controls/FadeOutTextBlock.cs
Labels: size/M

#8871 Display user friendly exception message
  WalletWasabi.Fluent/Helpers/TransactionHelpers.cs
Labels: size/XS

#8853 [Trivial] Hide overwhelming `SocketExceptions`
  WalletWasabi.Fluent.Desktop/Program.cs
Labels: size/S

#8864 Introduce CancellationToken to UpdateManager
  WalletWasabi.Fluent/Global.cs
  WalletWasabi/Services/UpdateManager.cs
Labels: size/S

#8846 [Tor] Experiment no.1
  WalletWasabi/WabiSabi/Client/ArenaClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/S

#8860 [Tor] Experiment - Set shorter `SocksTimeout`
  WalletWasabi.Tests/UnitTests/Tor/TorSettingsTests.cs
  WalletWasabi/Tor/TorSettings.cs
Labels: size/XS

#8879 [VDG] Show formatted "until" date for banned coins
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinViewModel.cs
Labels: size/XS

#8867 [VDG] Change the wallet creation ux to set the password later
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/ConfirmRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/RecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/WalletNamePageViewModel.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/Blockchain/Keys/WalletGenerator.cs
Labels: size/L

#8836 More user friendly error message for Invalid Hex String error
  WalletWasabi/Backend/Models/FilterModel.cs
Labels: size/M

#8888 Fixup Support DnsEndpoint for Tor
  WalletWasabi.Tests/IntegrationTests/TorTests.cs
  WalletWasabi.Tests/UnitTests/Tor/TorProcessManagerTests.cs
  WalletWasabi/Tor/Control/TorControlClientFactory.cs
  WalletWasabi/Tor/Http/TorHttpClient.cs
  WalletWasabi/Tor/Socks5/Pool/TorHttpPool.cs
  WalletWasabi/Tor/Socks5/TcpClientSocks5Connector.cs
  WalletWasabi/Tor/Socks5/TorTcpConnectionFactory.cs
  WalletWasabi/Tor/TcpClientConnector.cs
  WalletWasabi/Tor/TorMonitor.cs
  WalletWasabi/Tor/TorProcessManager.cs
  WalletWasabi/Tor/TorSettings.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WabiSabi/Client/CoinJoinTrackerFactory.cs
  WalletWasabi/Wallets/IWallet.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/L

#8891 [VDG] Update % when AnonScore changes in CJ settings
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinSettingsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletSettingsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
Labels: size/S

#8875 [VDG] Remove OAPH from SearchBar
  WalletWasabi.Fluent/ViewModels/SearchBar/SearchBarViewModel.cs
  WalletWasabi.Fluent/Views/SearchBar/SearchBarDropdown.axaml
Labels: size/S

#8874 [VDG] Remove OAPH from Coin List
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/WalletCoinsView.axaml
Labels: size/M

#8878 [Tor] Add timeout to GetStatus request
  WalletWasabi.Fluent/Global.cs
  WalletWasabi/WabiSabi/Client/RoundStateAwaiters/RoundStateUpdater.cs
Labels: size/S

#8689 Implement Virtual Coins
  WalletWasabi.Tests/Helpers/BitcoinFactory.cs
  WalletWasabi.Tests/Helpers/ServiceFactory.cs
  WalletWasabi.Tests/UnitTests/Transactions/SmartTransactionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/CoinJoinCoinSelectionTests.cs
  WalletWasabi/Blockchain/TransactionOutputs/ForeignVirtualOutput.cs
  WalletWasabi/Blockchain/TransactionOutputs/WalletVirtualInput.cs
  WalletWasabi/Blockchain/TransactionOutputs/WalletVirtualOutput.cs
  WalletWasabi/Blockchain/Transactions/SmartTransaction.cs
  WalletWasabi/Extensions/NBitcoinExtensions.cs
Labels: size/L

#8895 [VDG] Fix scrolling issues with mouse wheel in UTXO list (and other lists) when labels are under mouse
  WalletWasabi.Fluent/Controls/LabelControl.axaml
  WalletWasabi.Fluent/Controls/LabelsListBox.axaml
Labels: size/M

#8907 Better log messages when round aborted with not enough alices
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/S

#8610 [VDG] Fee Chart dialog + custom fee rate input
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/CustomFeeRateDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendFeeViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Send/CustomFeeRateDialogView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/CustomFeeRateDialogView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Send/SendFeeView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Labels: size/L

#8912 Support taproot (coordinator side)
  WalletWasabi.Tests/Helpers/BitcoinFactory.cs
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/Bip322SignatureTest.cs
  WalletWasabi.Tests/UnitTests/Crypto/OwnershipProofTest.cs
  WalletWasabi.Tests/UnitTests/TestWallet.cs
  WalletWasabi.Tests/UnitTests/Transactions/PayjoinTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputSuccessTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterOutputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/SignTransactionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Crypto/OwnershipProofTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/InputRegistrationRequestTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/MultipartyTransactionTests.cs
  WalletWasabi/Blockchain/Keys/HdPubKey.cs
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRoundConfig.cs
  WalletWasabi/Crypto/Bip322Signature.cs
  WalletWasabi/Crypto/OwnershipProof.cs
  WalletWasabi/Extensions/NBitcoinExtensions.cs
  WalletWasabi/Helpers/Constants.cs
  WalletWasabi/Helpers/ScriptSizeHelpers.cs
  WalletWasabi/WabiSabi/Backend/Models/WabiSabiProtocolErrorCode.cs
  WalletWasabi/WabiSabi/Backend/Rounds/RoundParameters.cs
  WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
  WalletWasabi/WabiSabi/Client/BaseKeyChain.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/KeyChain.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/ConstructionState.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/SigningState.cs
Labels: size/XL

#8898 Add retry timeouts to CoinJoin requests
  WalletWasabi/WabiSabi/Client/WabiSabiHttpApiClient.cs
Labels: size/M

#8909 [VDG] Optimize LabelsListBox - and rename to LabelsItemsPresenter
  WalletWasabi.Fluent/App.axaml
  WalletWasabi.Fluent/Controls/LabelControl.axaml
  WalletWasabi.Fluent/Controls/LabelControl.axaml.cs
  WalletWasabi.Fluent/Controls/LabelsItemsPresenter.axaml
  WalletWasabi.Fluent/Controls/LabelsItemsPresenter.axaml.cs
  WalletWasabi.Fluent/Controls/LabelsListBox.axaml
  WalletWasabi.Fluent/Controls/LabelsListBox.axaml.cs
  WalletWasabi.Fluent/Views/Dialogs/ConfirmHideAddressView.axaml
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/Columns/LabelsColumnView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/Columns/LabelsColumnView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/Details/TransactionDetailsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Receive/Columns/LabelsColumnView.axaml
  WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveAddressView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionSummary.axaml
Labels: size/L

#8911 `TorTcpConnectionFactory`: Add missing cancellation token
  WalletWasabi/Tor/Socks5/TorTcpConnectionFactory.cs
Labels: size/S

#8897 Tor SOCKS5: Remove "keepalive" functionality
  WalletWasabi/Tor/Socks5/TcpClientSocks5Connector.cs
  WalletWasabi/Tor/Socks5/TorTcpConnectionFactory.cs
  WalletWasabi/Tor/TcpClientConnector.cs
Labels: size/M

#8869 [VDG] Send preview - fix button is not clickable
  WalletWasabi.Fluent/Extensions/ObservableExtension.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
Labels: size/M

#8803 [VDG] Fee Chart - fix crash
  WalletWasabi.Fluent/Helpers/TransactionFeeHelper.cs
  WalletWasabi.Fluent/ViewModels/Navigation/RoutableViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendFeeViewModel.cs
Labels: size/L

#8790 Refactor SmartCoinSelector tests
  WalletWasabi.Tests/UnitTests/Wallet/SmartCoinSelectorTests.cs
Labels: size/L

#8919 Add total timeout for one coinjoin round
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/S

#8922 Bump version to v2.0.1.4
  WalletWasabi.Backend/wwwroot/index.html
  WalletWasabi/Helpers/Constants.cs
Labels: size/S

#8908 Fix CI - Wait a bit more for the CoinJoin
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/Participant.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi/BitcoinCore/Rpc/RpcClientBase.cs
Labels: size/L

#8927 `WabiSabiHttpApiClient`: Remove extra `catch`
  WalletWasabi/Tor/Socks5/Pool/TorHttpPool.cs
  WalletWasabi/WabiSabi/Client/WabiSabiHttpApiClient.cs
Labels: size/M

#8929 [VDG] Optimize PrivacyContentControl template
  WalletWasabi.Fluent/Controls/PrivacyContentControl.axaml
Labels: size/M

#8928 Use virtual wallet input and outputs concepts
  WalletWasabi.Tests/UnitTests/BlockchainAnalysis/PubKeyReuseAnonScoreTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/SmartTransactionTests.cs
  WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs
  WalletWasabi/Blockchain/TransactionOutputs/WalletVirtualInput.cs
  WalletWasabi/Blockchain/TransactionOutputs/WalletVirtualOutput.cs
  WalletWasabi/Blockchain/Transactions/SmartTransaction.cs
Labels: size/L

#8933 Anonymity improvement tests
  WalletWasabi.Tests/Helpers/AnalyzedTransaction/AnalyzedTransaction.cs
  WalletWasabi.Tests/Helpers/AnalyzedTransaction/ForeignOutput.cs
  WalletWasabi.Tests/Helpers/AnalyzedTransaction/WalletOutput.cs
  WalletWasabi.Tests/UnitTests/BlockchainAnalysis/CoinJoinAnonscoreTests.cs
  WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs
  WalletWasabi/Blockchain/Analysis/CoinjoinAnalyzer.cs
  WalletWasabi/Blockchain/TransactionOutputs/WalletVirtualInput.cs
Labels: size/L

#8939 [GitHub Action] Add issues automatically to the project board
  .github/workflows/auto-add-to-projcet.yml
Labels: size/S

#8946 [VDG] Remove unused BlurBehind control
  WalletWasabi.Fluent/Controls/BlurBehind.cs
Labels: size/L

#8948 Revert "Anonymity improvement tests"
  WalletWasabi.Tests/Helpers/AnalyzedTransaction/AnalyzedTransaction.cs
  WalletWasabi.Tests/Helpers/AnalyzedTransaction/ForeignOutput.cs
  WalletWasabi.Tests/Helpers/AnalyzedTransaction/WalletOutput.cs
  WalletWasabi.Tests/UnitTests/BlockchainAnalysis/CoinJoinAnonscoreTests.cs
  WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs
  WalletWasabi/Blockchain/Analysis/CoinjoinAnalyzer.cs
  WalletWasabi/Blockchain/TransactionOutputs/WalletVirtualInput.cs
Labels: size/L

#8944 [Trivial] Fix some typos
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/IWebHostBuilderExtensions.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi/Exceptions/TransactionSizeException.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/S

#8955 Add RPC `Start` and `Stop` coinjoin
  WalletWasabi.Fluent/Rpc/WasabiJsonRpcService.cs
Labels: size/S

#8850 Compatibility update 2
  WalletWasabi.Documentation/WasabiCompatibility.md
Labels: size/XS

#8966 Prioritize warning
  WalletWasabi.Fluent/Views/StatusIcon/StatusIcon.axaml
Labels: size/XS

#8957 Update to Avalonia 0.10.18
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
Labels: size/XL

#8971 Add CoinVerifier
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/CoinVerifierTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/UtxoWhitelistTests.cs
  WalletWasabi/CoinJoin/Coordinator/Banning/UtxoReferee.cs
  WalletWasabi/CoinJoin/Coordinator/Coordinator.cs
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRoundConfig.cs
  WalletWasabi/WabiSabi/Backend/Banning/ApiResponseItem.cs
  WalletWasabi/WabiSabi/Backend/Banning/CoinVerifier.cs
  WalletWasabi/WabiSabi/Backend/Banning/CoinVerifierApiClient.cs
  WalletWasabi/WabiSabi/Backend/Banning/Innocent.cs
  WalletWasabi/WabiSabi/Backend/Banning/Whitelist.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Rounds/CoinJoinStorage/CoinJoinIdStore.cs
  WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
  WalletWasabi/WabiSabi/CoordinatorParameters.cs
  WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
Labels: size/XL

#8962 Add password parameter
  WalletWasabi.Fluent/Rpc/WasabiJsonRpcService.cs
Labels: size/S

#8923 [WasabikaCodex] Extend git scripts
  WalletWasabi.Documentation/WasabikaCodex.md
Labels: size/XS

#8978 [VDG] tx broadcast caption text
  WalletWasabi.Fluent/Views/TransactionBroadcasting/LoadTransactionView.axaml
Labels: size/XS

#8980 Fix namespace of `ReadyToSignRequestRequest`
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/ReadyToSignRequestRequestTests.cs
  WalletWasabi/WabiSabi/Models/ReadyToSignRequestRequest.cs
Labels: size/XS

#8377 Update WW2 legal docs
  WalletWasabi/Legal/Assets/LegalDocumentsWw2.txt
Labels: size/S

#8977 Add a message when the history table is empty
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
Labels: size/S

#8984 [VDG] custom fee CurrencyEntryBox improvement
  WalletWasabi.Fluent/Views/Wallets/Send/CustomFeeRateDialogView.axaml
Labels: size/XS

#8968 [VDG] SendViewModel - fix reentrance problem in TryParseUrl()
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
Labels: size/S

#8960 [VDG] DualCurrencyEntryBox - small layout correction for readonly style
  WalletWasabi.Fluent/Controls/DualCurrencyEntryBox.axaml
Labels: size/XS

#8981 Adjust Timeouts + fix backend bug
  WalletWasabi/WabiSabi/Backend/Banning/CoinVerifier.cs
  WalletWasabi/WabiSabi/Backend/Banning/CoinVerifierApiClient.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/XS

#8982 tor: Remove unused macOS script that is not a part of the official distribution
  WalletWasabi/Microservices/Binaries/README.md
  WalletWasabi/Microservices/Binaries/osx64/Tor/tor
Labels: size/S

#8970 [VDG] Set focus away when activating actionable item
  WalletWasabi.Fluent/Behaviors/ShowAttachedFlyoutWhenFocusedBehavior.cs
  WalletWasabi.Fluent/Helpers/ApplicationHelper.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/SearchBarDesignViewModel.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/SearchBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/SearchItems/ActionableItem.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/SearchItems/AutocloseActionableItem.cs
  WalletWasabi.Fluent/Views/SearchBar/SearchBarDropdown.axaml
Labels: size/L

#8974 Remove Instagram, Facebook from footer
  WalletWasabi.Backend/wwwroot/index.html
Labels: size/S

#8827 Tor circuit prebuilding
  WalletWasabi.Fluent/Global.cs
  WalletWasabi.Tests/IntegrationTests/BlockstreamInfoClientTests.cs
  WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
  WalletWasabi.Tests/IntegrationTests/P2pTests.cs
  WalletWasabi.Tests/IntegrationTests/TorTests.cs
  WalletWasabi.Tests/RegressionTests/BuildTests.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi.Tests/RegressionTests/WalletTests.cs
  WalletWasabi.Tests/UnitTests/Tor/Socks5/Pool/TorHttpPoolTests.cs
  WalletWasabi/Tor/Control/TorControlClient.cs
  WalletWasabi/Tor/Http/TorHttpClient.cs
  WalletWasabi/Tor/Socks5/Pool/Circuits/AnyOneOffCircuit.cs
  WalletWasabi/Tor/Socks5/Pool/Circuits/OneOffCircuit.cs
  WalletWasabi/Tor/Socks5/Pool/TorHttpPool.cs
  WalletWasabi/Tor/TorMonitor.cs
  WalletWasabi/WebClients/Wasabi/HttpClientFactory.cs
Labels: size/XL

#8979 Subscribe Tor Control `STREAM` events
  WalletWasabi.Tests/UnitTests/Tor/Control/Messages/Events/StreamEventTests.cs
  WalletWasabi.Tests/UnitTests/Tor/Control/Utils/AsyncEventParserTests.cs
  WalletWasabi/Tor/Control/Messages/CircuitStatus/BuildFlag.cs
  WalletWasabi/Tor/Control/Messages/CircuitStatus/CircStatus.cs
  WalletWasabi/Tor/Control/Messages/CircuitStatus/CircuitInfo.cs
  WalletWasabi/Tor/Control/Messages/CircuitStatus/HsState.cs
  WalletWasabi/Tor/Control/Messages/CircuitStatus/Purpose.cs
  WalletWasabi/Tor/Control/Messages/CircuitStatus/Reason.cs
  WalletWasabi/Tor/Control/Messages/Events/StreamEvent.cs
  WalletWasabi/Tor/Control/Messages/StreamStatus/ClientProtocol.cs
  WalletWasabi/Tor/Control/Messages/StreamStatus/IsoFieldFlag.cs
  WalletWasabi/Tor/Control/Messages/StreamStatus/Purpose.cs
  WalletWasabi/Tor/Control/Messages/StreamStatus/Reason.cs
  WalletWasabi/Tor/Control/Messages/StreamStatus/StreamInfo.cs
  WalletWasabi/Tor/Control/Messages/StreamStatus/StreamStatusFlag.cs
  WalletWasabi/Tor/Control/TorControlClientFactory.cs
  WalletWasabi/Tor/Control/Utils/AsyncEventParser.cs
  WalletWasabi/Tor/Control/Utils/Tokenizer.cs
  WalletWasabi/Tor/TorMonitor.cs
Labels: size/XL

#8990 [Trivial] Bump VS version
  WalletWasabi.sln
Labels: size/XS

#8992 Update NuGets
  WalletWasabi.Backend/WalletWasabi.Backend.csproj
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent.Generators/WalletWasabi.Fluent.Generators.csproj
  WalletWasabi.Fluent.Generators/packages.lock.json
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
  WalletWasabi.Packager/packages.lock.json
  WalletWasabi.Tests/WalletWasabi.Tests.csproj
  WalletWasabi/WalletWasabi.csproj
  WalletWasabi/packages.lock.json
Labels: size/L

#8989 coinjoin icons change
  WalletWasabi.Fluent/Icons/Icons.axaml
Labels: size/XS

#8547 Script to upgrade Tor binaries
  WalletWasabi/Microservices/Binaries/UpgradeTorBinaries.ps1
Labels: size/L

#8996 [Taproot support] Separate persistent methods
  WalletWasabi.Fluent/Rpc/WasabiJsonRpcService.cs
  WalletWasabi.Tests/Helpers/ServiceFactory.cs
  WalletWasabi.Tests/UnitTests/KeyManagementTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
  WalletWasabi.Tests/UnitTests/UserInterfaceTest/LabelTestExtensions.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
  WalletWasabi/WabiSabi/Client/InternalDestinationProvider.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/M

#9005 Tiny changes to clean the `KeyManager`
  WalletWasabi/Blockchain/Keys/KeyManager.cs
Labels: size/M

#8993 hardwallet design changes
  WalletWasabi.Fluent/Assets/WalletIcons/Dark/coldcard.png
  WalletWasabi.Fluent/Assets/WalletIcons/Dark/generic.png
  WalletWasabi.Fluent/Assets/WalletIcons/Dark/ledger.png
  WalletWasabi.Fluent/Assets/WalletIcons/Dark/normal.png
  WalletWasabi.Fluent/Assets/WalletIcons/Dark/trezor.png
  WalletWasabi.Fluent/Assets/WalletIcons/Light/coldcard.png
  WalletWasabi.Fluent/Assets/WalletIcons/Light/generic.png
  WalletWasabi.Fluent/Assets/WalletIcons/Light/ledger.png
  WalletWasabi.Fluent/Assets/WalletIcons/Light/normal.png
  WalletWasabi.Fluent/Assets/WalletIcons/Light/trezor.png
Labels: size/XS

#9001 [VDG] Send - fix paste button flashing after pasting PayJoin address
  WalletWasabi.Fluent/Behaviors/PasteButtonFlashBehavior.cs
Labels: size/XS

#9011 [TRIVIAL] Fix incorrect icon on HW wallet page
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/ConnectHardwareWalletViewModel.cs
Labels: size/XS

#9007 Do not log `System.OperationCanceledException: The peer has been disconnected` on debug level
  WalletWasabi.Fluent.Desktop/Program.cs
Labels: size/XS

#9006 [trivial] Remove benchmark code
  WalletWasabi.Fluent/Global.cs
Labels: size/M

#9016 Enable "skip" for seed confirmation in debug mode
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/ConfirmRecoveryWordsViewModel.cs
Labels: size/XS

#9017 Tor: Fix use of `AnyOneOffCircuit`
  WalletWasabi.Tests/UnitTests/Tor/Socks5/Pool/TorHttpPoolTests.cs
  WalletWasabi/Tor/Control/Messages/StreamStatus/StreamStatusFlag.cs
  WalletWasabi/Tor/Socks5/Pool/Circuits/AnyOneOffCircuit.cs
  WalletWasabi/Tor/Socks5/Pool/TorHttpPool.cs
  WalletWasabi/Tor/Socks5/TorTcpConnectionFactory.cs
  WalletWasabi/Tor/TorProcessManager.cs
Labels: size/M

#8100 Fix warnings in Backend project (take 2)
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Backend/InitConfigStartupTask.cs
  WalletWasabi.Backend/Startup.cs
Labels: size/L

#9021 Fix taproot test warnings
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
Labels: size/S

#9027 Revert "Fix warnings in Backend project (take 2)"
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Backend/InitConfigStartupTask.cs
  WalletWasabi.Backend/Startup.cs
Labels: size/L

#9029 [Trivial] Edit command for faster cloning of the repo (README.md)
  README.md
Labels: size/XS

#9020 Tor: Proper matching of `TorTcpConnection`s and Tor's streams (circuits)
  WalletWasabi/Tor/Socks5/Pool/TorHttpPool.cs
  WalletWasabi/Tor/Socks5/TorTcpConnection.cs
  WalletWasabi/Tor/TorMonitor.cs
Labels: size/L

#8969 Check if cts is disposed
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
Labels: size/S

#9019 [Trivial] LogInfo for NoEstimationException
  WalletWasabi/BitcoinCore/Monitoring/RpcFeeProvider.cs
Labels: size/XS

#8956 [VDG] Privacy bar
  WalletWasabi.Fluent/Behaviors/FadeInBehavior.cs
  WalletWasabi.Fluent/Behaviors/ItemsPresenterAnimationBehavior.cs
  WalletWasabi.Fluent/Behaviors/ListBoxPreviewBehavior.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/IPrivacyRingPreviewItem.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyBarItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyControlTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyRing/PrivacyRingView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyRing/PrivacyRingView.axaml.cs
Labels: size/XL

#9030 Small changes in `KeyManager`
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/Blockchain/Keys/WalletGenerator.cs
Labels: size/M

#9023 Log on Trace level when every coin is mixed
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WabiSabi/LoggerTools.cs
Labels: size/XS

#9022 Fix namespace of `RPCClientExtensions`
  WalletWasabi.Backend/Controllers/BlockchainController.cs
  WalletWasabi.Tests/UnitTests/AllFeeEstimateTests.cs
  WalletWasabi.Tests/UnitTests/BitcoinCore/RpcBasedTests.cs
  WalletWasabi/BitcoinCore/CoreNode.cs
  WalletWasabi/BitcoinCore/Monitoring/RpcFeeProvider.cs
  WalletWasabi/BitcoinCore/Monitoring/RpcMonitor.cs
  WalletWasabi/CoinJoin/Client/CoinJoinProcessor.cs
  WalletWasabi/Extensions/RPCClientExtensions.cs
  WalletWasabi/WabiSabi/Backend/Statistics/CoinJoinFeeRateStatStore.cs
Labels: size/S

#8997 [MusicBox] Don't display "Round finished..." when user presses pause during InputRegPhase
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/MusicControlsView.axaml
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinProgressEvents/RoundEnded.cs
  WalletWasabi/WabiSabi/Client/CoinJoinTracker.cs
Labels: size/M

#9031 Act on reviews of 8994
  WalletWasabi/Blockchain/Keys/KeyManager.cs
Labels: size/M

#7577 [VDG] Improve UX of Send/QRCode
  WalletWasabi.Fluent/ViewModels/Dialogs/ShowQrCameraDialogViewModel.cs
  WalletWasabi.Fluent/Views/Dialogs/ShowQrCameraDialogView.axaml
Labels: size/M

#8691 [VDG] Discreet Mode for BitcoinP2PEndPoint in Settings
  WalletWasabi.Fluent/Views/Settings/BitcoinTabSettingsView.axaml
Labels: size/XS
