Repository WalletWasabi/WalletWasabi, pull requests merged in 2022-03, with the labels that each got.

#7326 [VDG] Add scroll hints to ScrollViewers
  WalletWasabi.Fluent/Styles/ScrollViewer.axaml
  WalletWasabi.Fluent/Styles/Styles.axaml
Labels: size/L

#7366 [VDG] [Trivial] Clarify wallet loading text
  WalletWasabi.Fluent/Views/Wallets/LoadingControl.axaml
Labels: size/S

#7340 [VDG] Welcome Page Improvements
  WalletWasabi.Fluent/Controls/ContentArea.axaml
  WalletWasabi.Fluent/ViewModels/AddWallet/WelcomePageViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/WelcomePageView.axaml
Labels: size/L

#7414 Revert "[VDG] Add scroll hints to ScrollViewers"
  WalletWasabi.Fluent/Styles/ScrollViewer.axaml
  WalletWasabi.Fluent/Styles/Styles.axaml
Labels: size/L

#7194 Fixing CheckIsCurrentTextValid execution when the dialog is closing (Results in crash)
  WalletWasabi.Fluent/Controls/TagsBox.axaml.cs
Labels: size/XS

#7347 [VDG] Auto pocket selection fix
  WalletWasabi.Fluent/Models/Pocket.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/LabelSelectionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
  WalletWasabi.Tests/UnitTests/UserInterfaceTest/PocketSelectionTests.cs
Labels: size/L

#7399 Fix/Suppress null warnings in DirectShow.cs
  WalletWasabi.Fluent/Models/Windows/DirectShow.cs
Labels: size/S

#7405 Fix WindowsCapture.cs warnings
  WalletWasabi.Fluent/Models/Windows/DirectShow.cs
  WalletWasabi.Fluent/Models/Windows/WindowsCapture.cs
Labels: size/M

#7416 [VDG] Show oobe background during add wallet
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
Labels: size/XS

#7410 [VDG] [Fluent] Update TreeDataGridRow template
  WalletWasabi.Fluent/Styles/TreeDataGrid.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
Labels: size/M

#7385 [VDG] Insufficient balance - Silent handling
  WalletWasabi.Fluent/Helpers/TransactionFeeHelper.cs
  WalletWasabi.Fluent/Models/BuildTransactionReason.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/FeeChartViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionInfo.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
Labels: size/L

#7418 Fix remaining warnings from Wasabi.Fluent
  WalletWasabi.Fluent/Global.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/ConfirmRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletStatsViewModel.cs
  WalletWasabi/CoinJoin/Client/CoinJoinProcessor.cs
Labels: size/M

#7419 Lower DefaultPlebStopThreshold on Client side
  WalletWasabi/Blockchain/Keys/KeyManager.cs
Labels: size/XS

#7420 [VDG] show version number on about page
  WalletWasabi.Fluent/Views/HelpAndSupport/AboutView.axaml
Labels: size/XS

#7411 Feature/music box
  WalletWasabi.Fluent.Desktop/Program.cs
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/Controls/BlurBehind.cs
  WalletWasabi.Fluent/Controls/ContentArea.axaml
  WalletWasabi.Fluent/Controls/Spectrum/AuraSpectrumDataSource.cs
  WalletWasabi.Fluent/Controls/Spectrum/SpectrumControl.cs
  WalletWasabi.Fluent/Controls/Spectrum/SpectrumDataSource.cs
  WalletWasabi.Fluent/Controls/Spectrum/SplashEffectDataSource.cs
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/State/StateMachine.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/MusicControlsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/MusicStatusMessageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModelBase.cs
  WalletWasabi.Fluent/Views/MainView.axaml
  WalletWasabi.Fluent/Views/MainWindow.axaml
  WalletWasabi.Fluent/Views/StatusBar/StatusBar.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyControlTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/MusicControlsView.axaml
  WalletWasabi.Fluent/Views/Wallets/MusicControlsView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WabiSabi/Client/StatusChangedEventArgs.cs
Labels: size/XXL

#7407 Preparation for TestNet release
  WalletWasabi.Fluent/Config.cs
  WalletWasabi/Helpers/Constants.cs
Labels: size/L

#7423 [VDG] Coinjoin writing ToolTip
  WalletWasabi.Fluent/Views/Wallets/Home/History/Columns/IndicatorsColumnView.axaml
Labels: size/XS

#7426 Fix coinjoin tracking
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Labels: size/XS

#7437 [VDG] PrivacyControlTile - Cleanup
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
Labels: size/S

#7433 [VDG] Improved StateMachine
  WalletWasabi.Fluent/State/StateMachine.cs
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi.Tests/UnitTests/StateMachineTests.cs
Labels: size/L

#7438 use official release of latest avalonia 0.10.13
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
Labels: size/L

#7439 Fix bad StateMachine configuration
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
Labels: size/XS

#7440 Change WabiSabi coordinator xpub
  WalletWasabi/Helpers/Constants.cs
Labels: size/XS

#7403 Add latest Bitcoin Core versions to constants
  WalletWasabi/Helpers/Constants.cs
Labels: size/XS

#7435 Make TestWallet behave like a HD wallet
  WalletWasabi.Tests/UnitTests/TestWallet.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/Participant.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
Labels: size/L

#7441 [VDG] Privacy tile improvements
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
Labels: size/S

#7444 Properly handling blame rounds with checks
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/M

#7447 [VDG] Trivial: Fix music box TimeSpan format
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
Labels: size/S

#7457 Mark destinations used when CJ successfully finished
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WabiSabi/Client/CoinJoinTracker.cs
Labels: size/S

#7472 [Trivial] [VDG] Add space to separate the amount and unit
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
Labels: size/XS

#7477 Use simple using statement
  WalletWasabi.Fluent/Controls/BlurBehind.cs
  WalletWasabi.Fluent/Controls/Spectrum/SpectrumControl.cs
Labels: size/M

#7482 [VDG] [Trivial] Action Center - About - Add ToolTip for link
  WalletWasabi.Fluent/Views/HelpAndSupport/LinkView.axaml
Labels: size/XS

#7479 [VDG] Add privacy for Music Box balance
  WalletWasabi.Fluent/Controls/PrivacyContentControl.axaml.cs
  WalletWasabi.Fluent/Helpers/TextHelpers.cs
  WalletWasabi.Fluent/ViewModels/UIConstants.cs
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
Labels: size/S

#7485 [Nullability] Fix Destinations in CoinJoinClient
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/XS

#7491 Add icon resources for Linux
  WalletWasabi.Fluent.Desktop/Assets/WasabiLogo16.png
  WalletWasabi.Fluent.Desktop/Assets/WasabiLogo24.png
  WalletWasabi.Fluent.Desktop/Assets/WasabiLogo256.png
  WalletWasabi.Fluent.Desktop/Assets/WasabiLogo32.png
  WalletWasabi.Fluent.Desktop/Assets/WasabiLogo48.png
Labels: size/XS

#7480 [VDG] Fix coinjoin autostart progress
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
Labels: size/XS

#7481 Do not indicate error on new round creation.
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/RoundStateUpdaterTests.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/RoundStateAwaiter.cs
  WalletWasabi/WabiSabi/Client/UnexpectedRoundPhaseException.cs
Labels: size/M

#7495 Fix wassabee permission on Linux distros
  WalletWasabi.Packager/Program.cs
Labels: size/XS

#7456 Add parallelization and timings to output registration
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi/Extensions/TimeSpanExtensions.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/DependencyGraphTaskScheduler.cs
Labels: size/L

#7476 [Trivial] [VDG] Hide music bow when the wallet balance is zero
  WalletWasabi.Fluent/ViewModels/Wallets/MusicControlsViewModel.cs
Labels: size/S

#7484 move the autostart delay from wabisabi code to ui code.
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WabiSabi/Client/StatusChangedEventArgs.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/M

#7497 [VDG] Fix Music Box balance privacy mode (alternate fix)
  WalletWasabi.Fluent/Views/Wallets/MusicControlsView.axaml
Labels: size/XS

#7503 [VDG] [Trivial] Add and edit keywords for action center
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/LegalDocumentsViewModel.cs
  WalletWasabi.Fluent/ViewModels/HelpAndSupport/AboutViewModel.cs
  WalletWasabi.Fluent/ViewModels/HelpAndSupport/DocsLinkViewModel.cs
  WalletWasabi.Fluent/ViewModels/HelpAndSupport/UserSupportViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/BitcoinTabSettingsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/GeneralSettingsTabViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/TorSettingsTabViewModel.cs
Labels: size/S

#7513 [VDG] [Trivial] Add coinjoining tooltip to CJ icon
  WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
Labels: size/XS

#7512 Tor: Add `ExtendedErrors`
  WalletWasabi.Tests/UnitTests/Tor/TorSettingsTests.cs
  WalletWasabi/Tor/Socks5/Models/Fields/OctetFields/RepField.cs
  WalletWasabi/Tor/Socks5/Models/ReplyType.cs
  WalletWasabi/Tor/TorSettings.cs
Labels: size/M

#7498 Move RoundState related code to a folder
  WalletWasabi.Fluent/Global.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/AliceTimeoutTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/Participant.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/RoundStateUpdaterTests.cs
  WalletWasabi/WabiSabi/Client/AliceClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WabiSabi/Client/CoinJoinTrackerFactory.cs
  WalletWasabi/WabiSabi/Client/RoundStateAwaiters/RoundStateAwaiter.cs
  WalletWasabi/WabiSabi/Client/RoundStateAwaiters/RoundStateUpdater.cs
  WalletWasabi/WabiSabi/Client/RoundStateAwaiters/UnexpectedRoundPhaseException.cs
Labels: size/S

#7504 Modify logic when committing changes to the mature and the immature i…
  WalletWasabi/Stores/IndexStore.cs
Labels: size/M

#7517 Remove dead code
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinTracker.cs
Labels: size/XS

#7041 [Fluent] Allow arbitrary case text on Labels
  WalletWasabi.Fluent/Controls/TagsBox.axaml
  WalletWasabi.Fluent/Controls/TagsBox.axaml.cs
Labels: size/M

#7521 Fixing wrong calculation of Output reg end time
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/S

#7506 [VDG] Add margin to adorner canvas
  WalletWasabi.Fluent/Converters/ThicknessConverters.cs
  WalletWasabi.Fluent/Views/MainView.axaml
Labels: size/S

#7524 [WabiSabi] Maximum Request Delay set to 10 secs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/S

#7525 [Trivial] Write code on separate lines
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/XS

#7212 Fee view improvements
  WalletWasabi.Fluent/Controls/LineChart.cs
  WalletWasabi.Fluent/Views/Wallets/Send/SendFeeView.axaml
Labels: size/M

#7499 Add PlebStopThreshold to Wallet Settings page
  WalletWasabi.Fluent/ViewModels/Wallets/WalletSettingsViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/WalletSettingsView.axaml
  WalletWasabi/Blockchain/Keys/KeyManager.cs
Labels: size/M

#7490 Simple warning fixes
  WalletWasabi/BitcoinCore/Rpc/CachedRpcClient.cs
  WalletWasabi/Blockchain/Blocks/BlockNotifier.cs
  WalletWasabi/Userfacing/AddressStringParser.cs
Labels: size/XS

#7522 Remove cross reference of GetDelaysForRequests
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/DependencyGraphTaskScheduler.cs
Labels: size/M

#7502 Fix more nullable warnings
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/Extensions/NBitcoinExtensions.cs
  WalletWasabi/Gma/QrCodeNet/Encoding/DataEncodation/ECISet.cs
  WalletWasabi/Helpers/ImportWalletHelper.cs
  WalletWasabi/Hwi/Models/HwiEnumerateEntry.cs
  WalletWasabi/Hwi/Parsers/HwiParser.cs
Labels: size/M

#7532 Fix rarely failing test AliceTimesoutAsync
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/AliceTimeoutTests.cs
Labels: size/S

#7529 Quick CoinJoinClient in Tests
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/Participant.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/M

#7538 The test should throw if nothing was throwen
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/AliceTimeoutTests.cs
Labels: size/XS

#7549 Add new fast decomposer
  WalletWasabi/Extensions/LinqExtensions.cs
  WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
  WalletWasabi/WabiSabi/Client/Decomposer.cs
Labels: size/L

#7533 Improve CoinJoinClient by extracting OutputRegistration Phase related progress
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/L

#7536 Improve CoinJoinClient by extracting Signing Phase related progress
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/M

#7458 Select a better set of coins
  WalletWasabi.Tests/UnitTests/Wallet/SmartCoinSelectorTests.cs
  WalletWasabi/Blockchain/TransactionBuilding/SmartCoinSelector.cs
Labels: size/L

#7537 Improve CoinJoinClient by extracting Input reg Phase related progress
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/S

#7560 Try more times before giving up
  WalletWasabi/WabiSabi/Client/WabiSabiHttpApiClient.cs
Labels: size/XS

#7454 [Trivial] [VDG] Add 'UTXOs' to wallet info dialog
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletStatsView.axaml
Labels: size/XS

#7559 Fluent warning fixes
  WalletWasabi.Fluent/Controls/BlurBehind.cs
  WalletWasabi.Fluent/Controls/Spectrum/SpectrumControl.cs
  WalletWasabi/BitcoinCore/CoreNode.cs
  WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
  WalletWasabi/Helpers/RuntimeParams.cs
  WalletWasabi/Nito/.editorconfig
Labels: size/M

#7571 Loglatefancy
  WalletWasabi.Backend/Controllers/WabiSabiController.cs
  WalletWasabi.Backend/Filters/LateResponseLoggerFilter.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/ConfirmConnectionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterOutputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RemoveInputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/SignTransactionTests.cs
  WalletWasabi/WabiSabi/Backend/Models/WrongPhaseException.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
  WalletWasabi/WabiSabi/Backend/Rounds/TimeFrame.cs
Labels: size/M

#7574 `IdempotencyRequestCache`: Await task so that it's observed
  WalletWasabi.Backend/Controllers/WabiSabi/IdempotencyRequestCache.cs
Labels: size/XS

#7585 [VDG] Fix Downloading map resize issue
  WalletWasabi.Fluent/Views/Wallets/LoadingControl.axaml
Labels: size/XS

#7584 [VDG] Fixed fee slider keyboard behavior
  WalletWasabi.Fluent/Behaviors/ExecuteCommandOnKeyDownBehavior.cs
  WalletWasabi.Fluent/Views/Wallets/Send/SendFeeView.axaml
Labels: size/S

#7583 Remove EventSourcing code
  WalletWasabi.Tests/UnitTests/EventSourcing/InMemoryEventRepositoryTests.cs
  WalletWasabi.Tests/UnitTests/EventSourcing/TestDomain/TestInMemoryEventRepository.cs
  WalletWasabi.Tests/UnitTests/EventSourcing/TestDomain/TestWrappedEvent.cs
  WalletWasabi/EventSourcing/AggregateEvents.cs
  WalletWasabi/EventSourcing/AggregateTypeIds.cs
  WalletWasabi/EventSourcing/InMemoryEventRepository.cs
  WalletWasabi/EventSourcing/WrappedEvent.cs
  WalletWasabi/Exceptions/OptimisticConcurrencyException.cs
  WalletWasabi/Exceptions/TransientException.cs
  WalletWasabi/Interfaces/EventSourcing/IEventRepository.cs
Labels: size/XL

#7582 Minor changes regarding `IndexStore`
  WalletWasabi/Blockchain/BlockFilters/FilterProcessor.cs
  WalletWasabi/Blockchain/Blocks/SmartHeaderChain.cs
  WalletWasabi/Io/DigestableSafeIoManager.cs
  WalletWasabi/Io/IoManager.cs
  WalletWasabi/Io/SafeIoManager.cs
  WalletWasabi/Stores/IndexStore.cs
Labels: size/M

#7591 [VDG] Rename Fee display format to Fee display unit
  WalletWasabi.Fluent/Extensions/TransactionSummaryExtension.cs
  WalletWasabi.Fluent/Models/FeeDisplayUnit.cs
  WalletWasabi.Fluent/UiConfig.cs
  WalletWasabi.Fluent/ViewModels/Settings/GeneralSettingsTabViewModel.cs
  WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/BroadcastTransactionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/CoinJoinDetailsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionSummaryViewModel.cs
  WalletWasabi.Fluent/Views/Settings/GeneralSettingsTabView.axaml
Labels: size/M

#7593 [VDG] [TRIVIAL] Help&Support - FAQ
  WalletWasabi.Fluent/ViewModels/HelpAndSupport/AboutViewModel.cs
Labels: size/XS

#7526 [VDG] Remember MainWindow Position
  WalletWasabi.Fluent/Behaviors/MainWindowPersistPositionBehavior.cs
  WalletWasabi.Fluent/UiConfig.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/Views/MainWindow.axaml
Labels: size/L, testnet-release

#7596 Bump version to v1.1.13.1
  WalletWasabi.Backend/wwwroot/index.html
Labels: size/S

#7578 [VDG] Fix non-awaited async calls
  WalletWasabi.Fluent/Behaviors/NumberBoxBehavior.cs
  WalletWasabi.Fluent/Behaviors/PasteButtonFlashBehavior.cs
  WalletWasabi.Fluent/Controls/PreviewItem.axaml.cs
  WalletWasabi.Fluent/Extensions/ObservableExtension.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/ShowQrCameraDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/HistoryItemViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/TransactionDetailsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/LoadingViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
Labels: size/M, testnet-release

#7475 [Trivial] [VDG] Display privacy level in format ##%
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyControlTileView.axaml
Labels: size/S, testnet-release

#7602 Remove OnionSeeds
  WalletWasabi/Tor/OnionSeeds/MainOnionSeeds.txt
  WalletWasabi/Tor/OnionSeeds/TestNetOnionSeeds.txt
  WalletWasabi/WalletWasabi.csproj
Labels: size/XL

#7603 [VDG] Allow labels dialog to be closed by pressing ESC
  WalletWasabi.Fluent/ViewModels/Wallets/Send/ConfirmLabelsDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
Labels: size/S

#7514 [VDG] Music box - only show privacy chars when balance is displayed
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/MusicControlsView.axaml
Labels: size/S, testnet-release

#7386 [VDG] Ask for the label on the first page
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
Labels: size/S, testnet-release

#7608 Use different AliceClients for every coin
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: priority, size/M

#7443 [VDG] Take into account the Recipient label during pocket selection
  WalletWasabi.Fluent/ViewModels/Wallets/Send/LabelSelectionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
  WalletWasabi.Tests/UnitTests/UserInterfaceTest/PocketSelectionTests.cs
Labels: size/L, testnet-release

#7611 [VDG] [TRIVIAL] Coinjoin Details- Coinjoin writing
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/CoinJoinDetailsViewModel.cs
Labels: size/XS

#7616 [VDG] do not mark item as selected if cancellation happened
  WalletWasabi.Fluent/Behaviors/NavBarSelectedIndicatorState.cs
Labels: size/XS

#7570 [VDG] Fix labels in fee rate graph
  WalletWasabi.Fluent/Converters/FeeTargetTimeConverter.cs
  WalletWasabi.Fluent/Extensions/TimeSpanMixin.cs
  WalletWasabi.Fluent/Helpers/ConfirmationTimeLabel.cs
  WalletWasabi.Fluent/Helpers/TimeSpanFormatter.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/FeeChartViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Send/SendFeeView.axaml
  WalletWasabi.Tests/UnitTests/Extensions/TimeSpanMixinTests.cs
Labels: size/L, testnet-release

#7544 `TorHttpPool`: Support circuit close messages
  WalletWasabi.Fluent/Global.cs
  WalletWasabi.Tests/UnitTests/Tor/Control/Messages/Events/CircEventTests.cs
  WalletWasabi/Tor/Control/Messages/Events/CircEvent.cs
  WalletWasabi/Tor/Socks5/Pool/TorHttpPool.cs
  WalletWasabi/Tor/Socks5/TorTcpConnection.cs
  WalletWasabi/Tor/TorMonitor.cs
  WalletWasabi/WebClients/Wasabi/HttpClientFactory.cs
Labels: size/M

#7624 [VDG] Improved rounding
  WalletWasabi.Fluent/Extensions/TimeSpanMixin.cs
  WalletWasabi.Fluent/Helpers/MathUtils.cs
  WalletWasabi.Tests/UnitTests/Extensions/TimeSpanMixinTests.cs
  WalletWasabi.Tests/UnitTests/Helpers/MathUtilsTests.cs
Labels: size/M

#7627 Update the required macOS version on website
  WalletWasabi.Backend/wwwroot/index.html
Labels: size/XS

#7572 Unify source of coinjoin related events
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WabiSabi/Client/WalletStatusChangedEventArgs.cs
Labels: size/S

#7641 [VDG] [Trivial] Unify capitalization
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletStatsView.axaml
  WalletWasabi.Fluent/Views/Wallets/WalletSettingsView.axaml
Labels: size/S

#7576 `TorProcessManager`: If Tor control auth cookie is missing, restart Tor process
  WalletWasabi.Fluent/Global.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/UnitTests/UserInterfaceTest/PocketSelectionTests.cs
  WalletWasabi/Rpc/JsonRpcRequestHandler.cs
  WalletWasabi/Tor/Control/TorControlClient.cs
  WalletWasabi/Tor/TorProcessManager.cs
  WalletWasabi/Tor/TorSettings.cs
Labels: size/M

#7613 [Trivial] Correct calculation for cj debug information
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/S

#7630 CONTRIBUTING.md - Add section for automatic code cleanup for Rider
  CONTRIBUTING.md
Labels: size/S

#7601 Optimize mature index appending
  WalletWasabi/Io/DigestableSafeIoManager.cs
  WalletWasabi/Io/SafeIoManager.cs
  WalletWasabi/Stores/IndexStore.cs
Labels: size/L

#7628 Add tx id to CJ success log
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/XS

#7612 [Trivial] Improve logs in CoinJoinClient & AliceClient
  WalletWasabi/WabiSabi/Client/AliceClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/M

#7152 [Trivial] Rename tests
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/CoinJoinCoinSelectionTests.cs
Labels: size/S

#7631 [VDG] Make usd price whole number
  WalletWasabi.Fluent/Helpers/CurrencyUtils.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/BtcPriceTileViewModel.cs
Labels: size/XS

#7646 [WabiSabi] Reduce the `RangeProof` by 5 bits
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/AmountDecomposerTests.cs
  WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
  WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/ProtocolContants.cs
Labels: size/S

#7637 [Trivial] Fix warnings and formatting
  WalletWasabi.Fluent/Controls/Spectrum/SpectrumDataSource.cs
  WalletWasabi.Fluent/State/StateMachine.cs
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi/WabiSabi/Client/StatusChangedEventArgs.cs
Labels: size/M

#7654 Thread safe random number generator
  WalletWasabi/Crypto/Randomness/InsecureRandom.cs
Labels: size/XS

#7655 [VDG] Call BnB cancellation when it is safe
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
Labels: size/XS

#7650 Fixing CoinJoin UI state machine
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
Labels: size/S

#7660 Makes sure to stop StartAutomaticallyAsync
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Labels: size/S

#7657 Replace `new Random()` with `Random.Shared`
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/ConfirmRecoveryWordsViewModel.cs
  WalletWasabi.Tests/Helpers/CryptoHelpers.cs
  WalletWasabi.Tests/Helpers/MempoolInfoGenerator.cs
  WalletWasabi.Tests/UnitTests/IoTests.cs
  WalletWasabi.Tests/UnitTests/KeyManagementTests.cs
  WalletWasabi.Tests/UnitTests/Tor/Socks5/Pool/TorHttpPoolTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/CredentialDependencyTests.cs
  WalletWasabi.Tests/UnitTests/Wallet/LockTimeSelectorTests.cs
  WalletWasabi/Blockchain/TransactionBuilding/BranchAndBound.cs
  WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
  WalletWasabi/Extensions/LinqExtensions.cs
  WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
  WalletWasabi/Wallets/LockTimeSelector.cs
Labels: size/M

#7659 [Trivial] Change namespace to match folder structure
  WalletWasabi.Tests/Helpers/TransactionProcessorExtensions.cs
  WalletWasabi.Tests/UnitTests/Tor/Control/Messages/GetInfoCircuitStatusReplyTests.cs
  WalletWasabi.Tests/UnitTests/Tor/Control/Messages/ProtocolInfoReplyTests.cs
  WalletWasabi.Tests/UnitTests/Userfacing/BitcoinInputTests.cs
  WalletWasabi.Tests/UnitTests/Userfacing/ParserTests.cs
  WalletWasabi.Tests/UnitTests/Userfacing/PasswordTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepConnectionConfirmationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepInputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/Rounds/Utils/ArenaExtensions.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/Rounds/Utils/CoinJoinTransactionArchiverTests.cs
Labels: size/S

#7656 [VDG] [TRIVIAL] Transaction fee slider caption better wording
  WalletWasabi.Fluent/Views/Wallets/Send/SendFeeView.axaml
Labels: size/XS
