Repository WalletWasabi/WalletWasabi, pull requests merged in 2022-11, with the labels that each got.

#9418 [VDG] Fix `IsSemiPrivate()` method
  WalletWasabi.Fluent/Helpers/CoinHelpers.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyBarItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingItemViewModel.cs
Labels: size/S

#9399 [VDG] Transaction Preview: Hide fiat amounts when exchange rate is zero
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionSummaryViewModel.cs
Labels: size/S

#9459 Loading page
  WalletWasabi.Backend/wwwroot/cloudflare.html
Labels: size/M

#9401 [VDG] Fix SearchBar flyout issue on theme change
  WalletWasabi.Fluent/Behaviors/ShowAttachedFlyoutWhenFocusedBehavior.cs
Labels: size/XS

#9394 [VDG] Only recreate mnemonics if the user start everything over
  WalletWasabi.Fluent/ViewModels/AddWallet/WalletNamePageViewModel.cs
Labels: size/XS

#9421 fix empty history style
  WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
Labels: size/S

#9461 [VDG] Add Wallet - fix delay after password
  WalletWasabi.Fluent/Views/AddWallet/Create/ConfirmRecoveryWordsView.axaml
Labels: size/XS

#9440 [VDG] [trivial] broadast TX caption typo
  WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/BroadcasterViewModel.cs
Labels: size/XS

#9460 [VDG] Discreet Mode - fix hover on empty labels in Wallet Coins
  WalletWasabi.Fluent/Controls/PrivacyContentControl.axaml
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/Columns/LabelsColumnView.axaml
Labels: size/S

#9475 [VDG] Discreet control alignment
  WalletWasabi.Fluent/Controls/PrivacyContentControl.axaml
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/Columns/LabelsColumnView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/Columns/LabelsColumnView.axaml
Labels: size/S

#9482 `IdempotencyRequestCache`: Add test: 2 requests, first one throws an ex…
  WalletWasabi.Tests/UnitTests/Cache/IdempotencyRequestCacheTests.cs
  WalletWasabi/Cache/IdempotencyRequestCache.cs
Labels: size/M

#9396 Add cancellation token to Controllers #1
  WalletWasabi.Backend/Controllers/BatchController.cs
  WalletWasabi.Backend/Controllers/BlockchainController.cs
  WalletWasabi.Backend/Controllers/LegacyController.cs
  WalletWasabi.Backend/Controllers/OffchainController.cs
  WalletWasabi.Backend/Controllers/WasabiController.cs
  WalletWasabi.Tests/IntegrationTests/ExternalApiTests.cs
  WalletWasabi/Interfaces/IExchangeRateProvider.cs
  WalletWasabi/WebClients/Bitstamp/BitstampExchangeRateProvider.cs
  WalletWasabi/WebClients/BlockchainInfo/BlockchainInfoExchangeRateProvider.cs
  WalletWasabi/WebClients/CoinGecko/CoinGeckoExchangeRateProvider.cs
  WalletWasabi/WebClients/Coinbase/CoinbaseExchangeRateProvider.cs
  WalletWasabi/WebClients/ExchangeRateProviders.cs
  WalletWasabi/WebClients/Gemini/GeminiExchangeRateProvider.cs
  WalletWasabi/WebClients/ItBit/ItBitExchangeRateProvider.cs
Labels: size/L

#9470 Add test for preventing double output registration
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
Labels: size/L

#9442 rename and change order WalletView menu items
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletStatsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
Labels: size/S

#9382 [VDG] Privacy Ring Details Layout
  WalletWasabi.Fluent/Controls/LabelsItemsPresenter.axaml
  WalletWasabi.Fluent/Converters/StringConverters.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyRing/PrivacyRingDetailsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyRing/PrivacyRingDetailsView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyRing/PrivacyRingItemDetailsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyRing/PrivacyRingItemDetailsView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyRing/PrivacyRingView.axaml
Labels: size/L

#9486 [VDG] Hide edit pockets button on Preview transactions
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionSummary.axaml
Labels: size/XS

#9448 `MempollMirror`: Improve effectiveness of `EvictSpendersNoLock`
  WalletWasabi/BitcoinCore/Mempool/MempoolMirror.cs
Labels: size/M

#9491 UpdateManager: typo fixes
  WalletWasabi/Services/UpdateManager.cs
Labels: size/XS

#9355 [Trivial][VDG] Disable back button for privacy ring dialog
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyRing/PrivacyRingView.axaml
Labels: size/XS

#9487 Remove `default` CTs from Tor code (2)
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi/Tor/Http/Extensions/HttpRequestMessageExtensions.cs
  WalletWasabi/Tor/Http/Helpers/HttpMessageHelper.cs
  WalletWasabi/Tor/TorProcessManager.cs
Labels: size/M

#9488 Remove `HttpClientWrapper`
  WalletWasabi.Tests/Helpers/HttpClientWrapper.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/StuttererHttpClient.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiApiApplicationFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi/Tor/Http/ClearnetHttpClient.cs
Labels: size/M

#9483 [Trivial] Fix obsolete warning
  WalletWasabi/WabiSabi/Client/LiquidityClueProvider.cs
Labels: size/XS

#9457 [VDG] fix calculation of `AreAllCoinsPrivate`
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
Labels: size/XS

#9497 Enable auto add action for PRs
  .github/workflows/auto-add-to-project.yml
Labels: size/XS

#9500 [VDG] Decrease prebuilds
  WalletWasabi.Fluent/ViewModels/Wallets/Send/LabelSelectionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Tests/UnitTests/UserInterfaceTest/PocketSelectionTests.cs
Labels: size/S

#9511 Order settings
  WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
Labels: size/XS

#9509 Revert "Enable auto add action for PRs"
  .github/workflows/auto-add-to-projcet.yml
Labels: size/XS

#9499 Use LogInfo in UpdateManager if it's called from Linux distro
  WalletWasabi/Services/UpdateManager.cs
Labels: size/XS

#9472 [Trivial] simplify backup message
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/ConfirmRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/Create/RecoveryWordsView.axaml
Labels: size/XS

#9515 Packager SHA256SUMS.asc
  WalletWasabi.Packager/ArgsProcessor.cs
  WalletWasabi.Packager/Program.cs
  WalletWasabi/Helpers/Constants.cs
  WalletWasabi/Helpers/WasabiSignerHelpers.cs
Labels: size/L

#9524 Auto-add discussions to project board
  .github/workflows/auto-add-to-projcet.yml
Labels: size/XS

#9526 Revert "Auto-add discussions to project board"
  .github/workflows/auto-add-to-projcet.yml
Labels: size/XS

#9530 Tolerate some missing fee rate
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/ConstructionState.cs
Labels: size/XS

#9531 Increase fee rate tolerance
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/ConstructionState.cs
Labels: size/XS

#9510 [VDG] Double shield coinjoin icon
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinsHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/HistoryItemViewModelBase.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/Columns/IndicatorsColumnView.axaml
Labels: size/S

#9431 [VDG] improve connect hww & enter pin message
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/ConnectHardwareWalletViewModel.cs
Labels: size/XS

#9533 [Packager] Skip MSI creation if already exists
  WalletWasabi.Packager/Program.cs
Labels: size/S

#9514 [VDG] Add PlainTextColumn for TreeDataGrid
  WalletWasabi.Fluent/TreeDataGrid/PlainTextCell.cs
  WalletWasabi.Fluent/TreeDataGrid/PlainTextColumn.cs
  WalletWasabi.Fluent/TreeDataGrid/PlainTextElementFactory.cs
  WalletWasabi.Fluent/TreeDataGrid/PrivacyElementFactory.cs
  WalletWasabi.Fluent/TreeDataGrid/TreeDataGridPlainTextCell.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
Labels: size/L

#9550 [Trivial] Fix lambda consistency
  WalletWasabi.Fluent/ViewModels/SearchBar/SettingsSearchSource.cs
Labels: size/XS

#9556 Relax mining fee rate diff.
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/ConstructionState.cs
Labels: size/XS

#9555 Coin selection improvement
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/M

#9561 Use .NET 5's HEX function
  WalletWasabi/Helpers/ByteHelpers.cs
Labels: size/S

#9493 [VDG] Tile system refactoring
  WalletWasabi.Fluent/Controls/TileControl.axaml
  WalletWasabi.Fluent/Controls/TileControl.axaml.cs
  WalletWasabi.Fluent/Helpers/TileHelper.cs
  WalletWasabi.Fluent/Models/TileSize.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/BtcPriceTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/TileLayoutViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/TilePresetViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/TileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletBalanceTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/BtcPriceTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyBar/PrivacyBar.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyControlTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/WalletTiles.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
  WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
Labels: size/XL

#9554 [Documentation] [Trivial] Update manual steps for RegTest setup
  WalletWasabi.Documentation/WasabiSetupRegtest.md
Labels: size/M

#9538 [VDG] Add support for double-click to show details
  WalletWasabi.Fluent/Behaviors/ExecuteCommandOnDoubleTapped.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/WalletCoinsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
  WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveAddressesView.axaml
Labels: size/L

#9569 Clarify break condition
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/XS

#9574 [Trivial] Update supported OS
  WalletWasabi.Documentation/WasabiCompatibility.md
Labels: size/XS

#9582 [VDG] [Trivial] Fix different sort ordering in items between searches
  WalletWasabi.Fluent/ViewModels/SearchBar/SearchBarViewModel.cs
Labels: size/XS

#9397 [VDG] Privacy ring reordering
  WalletWasabi.Fluent/Helpers/CoinHelpers.cs
  WalletWasabi.Fluent/Models/PrivacyLevel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingViewModel.cs
Labels: size/L

#9428 MirrorMempool: Swap old mempool snapshot for a new mempool snapshot
  WalletWasabi.Tests/UnitTests/BitcoinCore/MempoolMirrorTests.cs
  WalletWasabi.Tests/UnitTests/BitcoinCore/MempoolTests.cs
  WalletWasabi/BitcoinCore/Mempool/Mempool.cs
  WalletWasabi/BitcoinCore/Mempool/MempoolMirror.cs
Labels: size/L

#9585 [minor] `CoinJoinClient`: Simplify a line
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/XS

#9465 [VDG] Privacy Bar reordering
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyBarItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyBarViewModel.cs
Labels: size/M

#9528 Remove fallback mechanism
  WalletWasabi.Fluent/Config.cs
  WalletWasabi.Fluent/Global.cs
  WalletWasabi/Tor/TorMonitor.cs
Labels: size/L

#9579 `MempoolNotifiesAsync`: Fix test
  WalletWasabi.Tests/UnitTests/BitcoinCore/P2pBasedTests.cs
  WalletWasabi/Helpers/EventAwaiter.cs
  WalletWasabi/Helpers/EventsAwaiter.cs
Labels: size/M

#9577 [trivial] `IdempotencyRequestCache`: Preparation work
  WalletWasabi.Backend/Controllers/WabiSabiController.cs
  WalletWasabi/Cache/IdempotencyRequestCache.cs
  WalletWasabi/Wallets/P2pBlockProvider.cs
Labels: size/S

#9588 Fix Max Privacy profile equality
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/PrivateCoinJoinProfileViewModel.cs
Labels: size/XS

#9596 [VDG] Recovery words - 3 column layout
  WalletWasabi.Fluent/Views/AddWallet/Create/RecoveryWordsView.axaml
Labels: size/S

#9466 [VDG] Privacy Ring References fix
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingItemViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyRing/PrivacyRingView.axaml
Labels: size/S

#9601 [VDG] Fix LabelsItemsPresenter HorizontalAlignment
  WalletWasabi.Fluent/Controls/LabelsItemsPresenter.axaml
Labels: size/XS

#9604 [Trivial] Improve recovery words warning text
  WalletWasabi.Fluent/Views/AddWallet/Create/RecoveryWordsView.axaml
Labels: size/XS

#9603 [VDG] Update history on new filter
  WalletWasabi.Fluent/Models/UiTriggers.cs
Labels: size/XS

#9417 [VDG] Coin Control - Stage 1
  WalletWasabi.Fluent/Behaviors/ExecuteCommandOnKeyDownBehavior.cs
  WalletWasabi.Fluent/Behaviors/HoldKeyBehavior.cs
  WalletWasabi.Fluent/Controls/LabelsItemsPresenter.axaml
  WalletWasabi.Fluent/Controls/LabelsItemsPresenter.axaml.cs
  WalletWasabi.Fluent/Converters/IndentToBrushConverter.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/Core/CoinCoinControlItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/Core/CoinControlItemViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/Core/PocketCoinControlItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/SelectCoinsDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionSummaryViewModel.cs
  WalletWasabi.Fluent/Views/CoinControl/Core/Cells/IndicatorsCellView.axaml
  WalletWasabi.Fluent/Views/CoinControl/Core/Cells/IndicatorsCellView.axaml.cs
  WalletWasabi.Fluent/Views/CoinControl/Core/Cells/LabelsCellView.axaml
  WalletWasabi.Fluent/Views/CoinControl/Core/Cells/LabelsCellView.axaml.cs
  WalletWasabi.Fluent/Views/CoinControl/Core/Headers/AnonymityScoreHeaderView.axaml
  WalletWasabi.Fluent/Views/CoinControl/Core/Headers/AnonymityScoreHeaderView.axaml.cs
  WalletWasabi.Fluent/Views/CoinControl/SelectCoinsDialogView.axaml
  WalletWasabi.Fluent/Views/CoinControl/SelectCoinsDialogView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionSummary.axaml
Labels: size/XL

#9597 `Arena`: Remove unused `Network` parameter
  WalletWasabi.Tests/Helpers/ArenaBuilder.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
Labels: size/XS

#9123 Select coins for round abstraction
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/CoinJoinCoinSelectionTests.cs
  WalletWasabi/Blockchain/TransactionOutputs/ISmartCoin.cs
  WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
  WalletWasabi/Crypto/Bip322Signature.cs
  WalletWasabi/Crypto/OwnershipProof.cs
  WalletWasabi/Extensions/NBitcoinExtensions.cs
  WalletWasabi/WabiSabi/Backend/Rounds/UtxoSelectionParameters.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/L

#9618 Fix negative OutgoingAmount in History
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinsHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/HistoryItemViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/TransactionHistoryItemViewModel.cs
Labels: size/M

#9070 Support taproot
  WalletWasabi.Fluent/Helpers/KeyManagerExtensions.cs
  WalletWasabi.Fluent/Rpc/WasabiJsonRpcService.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/AdvancedRecoveryOptionsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletInfoViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletStatsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressesViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/VerifyRecoveryWordsViewModel.cs
  WalletWasabi.Tests/AcceptanceTests/HwiKatas.cs
  WalletWasabi.Tests/Helpers/BitcoinFactory.cs
  WalletWasabi.Tests/Helpers/ServiceFactory.cs
  WalletWasabi.Tests/UnitTests/Hwi/MockedDeviceTests.cs
  WalletWasabi.Tests/UnitTests/KeyManagementTests.cs
  WalletWasabi.Tests/UnitTests/LinqExtensionsTests.cs
  WalletWasabi.Tests/UnitTests/TestWallet.cs
  WalletWasabi.Tests/UnitTests/Transactions/PayjoinTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
  WalletWasabi.Tests/UnitTests/UserInterfaceTest/PocketSelectionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/KeyChainTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi.Tests/UnitTests/Wallet/SmartCoinSelectorTests.cs
  WalletWasabi/Blockchain/Keys/BlockchainState.cs
  WalletWasabi/Blockchain/Keys/HdPubKey.cs
  WalletWasabi/Blockchain/Keys/HdPubKeyCache.cs
  WalletWasabi/Blockchain/Keys/HdPubKeyGenerator.cs
  WalletWasabi/Blockchain/Keys/HdPubKeyGlobalView.cs
  WalletWasabi/Blockchain/Keys/HdPubKeyPathView.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
  WalletWasabi/Extensions/LinqExtensions.cs
  WalletWasabi/Extensions/NBitcoinExtensions.cs
  WalletWasabi/Helpers/HardwareWalletOperationHelpers.cs
  WalletWasabi/Helpers/ImportWalletHelper.cs
  WalletWasabi/JsonConverters/HeightJsonConverter.cs
  WalletWasabi/JsonConverters/WalletHeightJsonConverter.cs
  WalletWasabi/WabiSabi/Client/AliceClient.cs
  WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
  WalletWasabi/WabiSabi/Client/ArenaClient.cs
  WalletWasabi/WabiSabi/Client/BaseKeyChain.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WabiSabi/Client/IDestinationProvider.cs
  WalletWasabi/WabiSabi/Client/IKeyChain.cs
  WalletWasabi/WabiSabi/Client/InternalDestinationProvider.cs
  WalletWasabi/WabiSabi/Client/KeyChain.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/SigningState.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/XXL

#9636 [Trivial] Separate DoS classes from utxo whitelisting
  WalletWasabi.Tests/Helpers/ArenaBuilder.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepConnectionConfirmationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputToBlameRoundTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/UtxoPrisonTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/UtxoPrisonWardenTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiApiApplicationFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi/WabiSabi/Backend/DoSPrevention/Inmate.cs
  WalletWasabi/WabiSabi/Backend/DoSPrevention/Prison.cs
  WalletWasabi/WabiSabi/Backend/DoSPrevention/Punishment.cs
  WalletWasabi/WabiSabi/Backend/DoSPrevention/Warden.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
Labels: size/M

#9630 `FilterModel`: Faster implementation
  WalletWasabi/Backend/Models/FilterModel.cs
Labels: size/S

#9610 [minor] Use static instances if available
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/Crypto/RandomTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputSuccessTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiApiApplicationFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/SerializationTests.cs
  WalletWasabi/Tor/Control/TorControlClientFactory.cs
  WalletWasabi/WabiSabi/Crypto/WabiSabiClient.cs
Labels: size/M

#9589 Small website fixes
  WalletWasabi.Backend/wwwroot/about.html
  WalletWasabi.Backend/wwwroot/contribution.html
  WalletWasabi.Backend/wwwroot/css/style.css
  WalletWasabi.Backend/wwwroot/faq.html
  WalletWasabi.Backend/wwwroot/index.html
  WalletWasabi.Backend/wwwroot/onion-index.html
  WalletWasabi.Backend/wwwroot/robots.txt
  WalletWasabi.Backend/wwwroot/sitemap.xml
Labels: size/L

#9629 `CoinJoinClient`: public -> private
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/S

#9631 [VDG] fix discreet mode in privacy ring
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyRing/PrivacyRingDetailsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyRing/PrivacyRingView.axaml
Labels: size/XS

#9593 Maximize Privacy CJ Profile Anonscore display fix
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/CoinJoinProfilesViewModel.cs
Labels: size/XS

#9658 [VDG] [trivial] remove handcursor for MaxPrivacy flyout at TX Preview
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml
Labels: size/XS

#9607 [VDG] [Trivial] Improve captions for SearchBar elements
  WalletWasabi.Fluent/ViewModels/AddWallet/LegalDocumentsViewModel.cs
  WalletWasabi.Fluent/ViewModels/HelpAndSupport/AboutViewModel.cs
  WalletWasabi.Fluent/ViewModels/HelpAndSupport/BugReportLinkViewModel.cs
  WalletWasabi.Fluent/ViewModels/HelpAndSupport/DocsLinkViewModel.cs
  WalletWasabi.Fluent/ViewModels/HelpAndSupport/UserSupportViewModel.cs
Labels: size/S

#9659 [VDG] [Trivial] Fix Privacy center margins
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyRing/PrivacyRingItemDetailsView.axaml
Labels: size/XS

#9660 [VDG] TreeDataGrid PrivacyTextCell - Add Transparent background
  WalletWasabi.Fluent/TreeDataGrid/TreeDataGridPrivacyTextCell.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
Labels: size/S

#9536 Fix unnecessary inputs bug
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
  WalletWasabi.Tests/UnitTests/Wallet/SmartCoinSelectorTests.cs
  WalletWasabi/Blockchain/TransactionBuilding/SmartCoinSelector.cs
Labels: size/L

#9648 [VDG] [Trivial] TagsBox height fix
  WalletWasabi.Fluent/Controls/TagsBox.axaml
Labels: size/XS

#9634 Remove possible null reference for `ToFeeDisplayUnitString`
  WalletWasabi.Fluent/Extensions/TransactionSummaryExtensions.cs
  WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/BroadcastTransactionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/CoinJoinDetailsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/CoinJoinsDetailsViewModel.cs
Labels: size/S

#9581 `IdempotentRequestCache`: Remove request timeout
  WalletWasabi.Backend/Controllers/WabiSabiController.cs
  WalletWasabi/Cache/IdempotencyRequestCache.cs
Labels: size/M

#9650 Change setting properties's names after the fallback mechanism removal
  WalletWasabi.Fluent/Config.cs
  WalletWasabi.Fluent/Global.cs
Labels: size/S

#9535 Add file verifying to UpdateManager
  WalletWasabi/Helpers/WasabiSignerHelpers.cs
  WalletWasabi/Services/UpdateManager.cs
Labels: size/L

#9664 `SingleInstanceCheckerTests.OtherInstanceStartedTestsAsync`: Add missing test multiplier
  WalletWasabi.Tests/UnitTests/Clients/SingleInstanceCheckerTests.cs
Labels: size/XS

#9654 [VDG] [Trivial] Coin control. Fix bad confirmation count
  WalletWasabi.Fluent/ViewModels/CoinControl/Core/PocketCoinControlItemViewModel.cs
Labels: size/XS

#9670 Fix Coinjoin default set upon not changing anything
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/CoinJoinProfilesViewModel.cs
Labels: size/XS

#9669 [VDG] [Trivial] Increase PrivacyRing adaptive threshold
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyRing/PrivacyRingView.axaml
Labels: size/XS

#9657 Don't allow to select coins if they are registered to a CJ round
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/Columns/SelectionColumnView.axaml
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/WalletCoinsView.axaml
Labels: size/XS
