Repository WalletWasabi/WalletWasabi, pull requests merged in 2022-04, with the labels that each got.

#7675 [VDG] Help&Support - Move Advanded Information to the bottom
  WalletWasabi.Fluent/Views/HelpAndSupport/AboutView.axaml
Labels: size/S

#7664 More correct `.editorconfig` for `WalletWasabi/Nito`
  WalletWasabi/Nito/.editorconfig
Labels: size/S

#7677 More correct `.editorconfig` for `zXing`
  WalletWasabi.Fluent/ZXing/.editorconfig
Labels: size/S

#7687 Add `.editorconfig` for the external `Gma` library
  WalletWasabi/Gma/.editorconfig
Labels: size/S

#7692 [VDG] [Trivial] Terms and Conditions - next on enter key
  WalletWasabi.Fluent/Views/AddWallet/TermsAndConditionsView.axaml
Labels: size/XS

#7693 [VDG] [Trivial] Fixes Paste command not working in CurrencyEntryBox
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
Labels: size/XS

#7684 [VDG] Transaction History - huge cleanup
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinsHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/HistoryItemViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
Labels: size/M

#7510 [VDG] [Fluent] Allow Coinjoins to be expanded in the TreeDataGrid
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinsHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/HistoryItemViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
Labels: size/L

#7695 [VDG] [Fluent] Set hand cursor for Coinjoins expander in history table
  WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
Labels: size/XS

#7666 Switch JsonConverters from 'JsonConverter' to 'JsonConverter<T>'
  WalletWasabi.Fluent/Converters/WindowStateAfterStartJsonConverter.cs
  WalletWasabi/JsonConverters/KeyPathJsonConverter.cs
  WalletWasabi/JsonConverters/NetworkJsonConverter.cs
  WalletWasabi/JsonConverters/OutPointAsTxoRefJsonConverter.cs
  WalletWasabi/JsonConverters/OutPointJsonConverter.cs
  WalletWasabi/JsonConverters/PubKeyJsonConverter.cs
  WalletWasabi/JsonConverters/SmartLabelJsonConverter.cs
  WalletWasabi/JsonConverters/Timing/TimeSpanJsonConverter.cs
  WalletWasabi/JsonConverters/TransactionJsonConverter.cs
  WalletWasabi/JsonConverters/Uint256JsonConverter.cs
  WalletWasabi/JsonConverters/UnblindedSignatureJsonConverter.cs
  WalletWasabi/WabiSabi/Crypto/Serialization/GroupElementJsonConverter.cs
  WalletWasabi/WabiSabi/Crypto/Serialization/ScalarJsonConverter.cs
  WalletWasabi/WabiSabi/Models/Serialization/OwnershipProofJsonConverter.cs
  WalletWasabi/WabiSabi/Models/Serialization/WitScriptJsonConverter.cs
Labels: size/L

#7649 [VDG] Fix SubscribeAsync workaround in PreviewItem
  WalletWasabi.Fluent/App.axaml
  WalletWasabi.Fluent/Controls/ClipboardCopyButton.axaml
  WalletWasabi.Fluent/Controls/ClipboardCopyButton.axaml.cs
  WalletWasabi.Fluent/Controls/PreviewItem.axaml
  WalletWasabi.Fluent/Controls/PreviewItem.axaml.cs
  WalletWasabi.Fluent/Views/TransactionBroadcasting/BroadcastTransactionView.axaml
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletInfoView.axaml
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletStatsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/CoinJoinDetailsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/TransactionDetailsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionSummary.axaml
Labels: size/L

#7710 [VDG] [Fluent] [Trivial] Move TreeDataGridItemDetailsAdorner to Controls folder
  WalletWasabi.Fluent/Controls/TreeDataGridItemDetailsAdorner.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
Labels: size/XS

#7588 [VDG] Fluent Navigation Redesign
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/Behaviors/NavBarSelectedIndicatorChildBehavior.cs
  WalletWasabi.Fluent/Behaviors/NavBarSelectedIndicatorState.cs
  WalletWasabi.Fluent/Behaviors/ShowFlyoutOnPointerOverBehavior.cs
  WalletWasabi.Fluent/Controls/BlurBehind.cs
  WalletWasabi.Fluent/Controls/ContentArea.axaml
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml
  WalletWasabi.Fluent/Controls/Dialog.axaml
  WalletWasabi.Fluent/Controls/FadeOutTextBlock.cs
  WalletWasabi.Fluent/Controls/NavBarItem.axaml
  WalletWasabi.Fluent/Controls/PreviewItem.axaml
  WalletWasabi.Fluent/Controls/PrivacyContentControl.axaml
  WalletWasabi.Fluent/Controls/QuestionControl.axaml
  WalletWasabi.Fluent/Controls/QuestionControl.axaml.cs
  WalletWasabi.Fluent/Controls/Spectrum/SpectrumControl.cs
  WalletWasabi.Fluent/Controls/TagsBox.axaml
  WalletWasabi.Fluent/Controls/TileButton.axaml
  WalletWasabi.Fluent/Controls/TileControl.axaml
  WalletWasabi.Fluent/CrashReport/Views/CrashReportWindow.axaml
  WalletWasabi.Fluent/Helpers/PlatformExtension.cs
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/Styles/FontSizes.axaml
  WalletWasabi.Fluent/Styles/HyperlinkButton.axaml
  WalletWasabi.Fluent/Styles/NotificationCard.axaml
  WalletWasabi.Fluent/Styles/Styles.axaml
  WalletWasabi.Fluent/Styles/TextBox.axaml
  WalletWasabi.Fluent/Styles/Themes/Base.axaml
  WalletWasabi.Fluent/Styles/Themes/BaseDark.axaml
  WalletWasabi.Fluent/Styles/Themes/BaseLight.axaml
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Search/SearchPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/PrivacyModeViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/SettingsPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModelBase.cs
  WalletWasabi.Fluent/Views/HelpAndSupport/AboutView.axaml
  WalletWasabi.Fluent/Views/HelpAndSupport/LinkView.axaml
  WalletWasabi.Fluent/Views/Login/PasswordFinder/ContainsNumbersView.axaml
  WalletWasabi.Fluent/Views/Login/PasswordFinder/ContainsSymbolsView.axaml
  WalletWasabi.Fluent/Views/MainView.axaml
  WalletWasabi.Fluent/Views/MainWindow.axaml
  WalletWasabi.Fluent/Views/MainWindow.axaml.cs
  WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
  WalletWasabi.Fluent/Views/StatusBar/StatusBar.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyControlTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/LoadingControl.axaml
  WalletWasabi.Fluent/Views/Wallets/MusicControlsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/PocketSuggestionControl.axaml
  WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
Labels: size/XXL

#7711 [VDG] Loading screen - disable scrollbar
  WalletWasabi.Fluent/Views/Wallets/LoadingControl.axaml
Labels: size/XS

#7709 Improve CoinJoinManager CodeScene score
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Labels: size/L

#7714 Improve output decomposition
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/AmountDecomposerTests.cs
  WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/M

#7707 `ChaumianCoinJoinController`: Suppress warnings.
  WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
Labels: size/XS

#7706 Fix a few warnings in `HwiParser`
  WalletWasabi/Helpers/JsonHelpers.cs
  WalletWasabi/Hwi/Parsers/HwiParser.cs
Labels: size/M

#7724 Introduce IDisposable to Backend `Global`
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Backend/Startup.cs
Labels: size/M

#7723 Adjust wallet header text fade out
  WalletWasabi.Fluent/Controls/FadeOutTextBlock.cs
  WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
Labels: size/XS

#7725 Add warning suppress in `Startup.cs`
  WalletWasabi.Backend/Startup.cs
Labels: size/XS

#7716 Simplify CoinJoinRestart logic
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Labels: size/M

#7690 [VDG] Send View - BTC and Fiat currency inputs
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
  WalletWasabi.Fluent/Controls/DualCurrencyEntryBox.axaml
  WalletWasabi.Fluent/Controls/DualCurrencyEntryBox.axaml.cs
  WalletWasabi.Fluent/Styles/Styles.axaml
  WalletWasabi.Fluent/UiConfig.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Labels: size/XL

#7717 [VDG] Fix case sensitive label issue
  WalletWasabi.Fluent/ViewModels/Wallets/Send/LabelSelectionViewModel.cs
  WalletWasabi.Tests/UnitTests/UserInterfaceTest/PocketSelectionTests.cs
Labels: size/S

#7039 [VDG] [Fluent] Improve Labels column in transaction history table
  WalletWasabi.Fluent/App.axaml
  WalletWasabi.Fluent/Controls/LabelControl.axaml
  WalletWasabi.Fluent/Controls/LabelControl.axaml.cs
  WalletWasabi.Fluent/Controls/LabelsItemsPresenter.cs
  WalletWasabi.Fluent/Controls/LabelsListBox.axaml
  WalletWasabi.Fluent/Controls/LabelsListBox.axaml.cs
  WalletWasabi.Fluent/Controls/LabelsPanel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinsHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/HistoryItemViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/TransactionHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/AddressViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PocketSuggestionViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/Columns/LabelsColumnView.axaml
  WalletWasabi.Fluent/Views/Wallets/Receive/Columns/LabelsColumnView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/PocketSuggestionControl.axaml
Labels: size/L

#7728 Rename P2wpkhOutputSizeInBytes to P2wpkhOutputVirtualSize
  WalletWasabi.Tests/UnitTests/TestWallet.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/AmountDecomposerTests.cs
  WalletWasabi/Helpers/Constants.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/S

#7734 [VDG] Fix DualCurrencyInput not properly updating text value
  WalletWasabi.Fluent/Controls/DualCurrencyEntryBox.axaml.cs
Labels: size/XS

#7737 [VDG] [Fluent] [Trivial] Fix xaml errors
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/BtcPriceTileView.axaml
Labels: size/XS

#7700 `AmountDecomposer`: Pass `Random` via ctor
  WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
Labels: size/S

#7726 Add `CoinJoinIdStore` to store old and new coinjoins at one place
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Tests/Helpers/ArenaBuilder.cs
  WalletWasabi.Tests/UnitTests/CoinjoinIdStoreTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/ConfigTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/CoordinatorTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputSuccessTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/RoundCreationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiApiApplicationFactory.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Rounds/CoinJoinStorage/CoinJoinIdStore.cs
  WalletWasabi/WabiSabi/Backend/Rounds/CoinJoinStorage/ICoinJoinIdStore.cs
  WalletWasabi/WabiSabi/Backend/Rounds/CoinJoinStorage/InMemoryCoinJoinIdStore.cs
  WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
Labels: size/L

#7670 [Trivial] Move restart automatically log message
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Labels: size/XS

#7715 Add Wallet coin list dump RPC
  WalletWasabi.Fluent/Rpc/WasabiJsonRpcService.cs
Labels: size/S

#7757 [VDG] SearchBar - Warning fixes and simplification
  WalletWasabi.Fluent/Behaviors/SearchBarBehavior.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/SearchBarViewModel.cs
Labels: size/M

#7772 [VDG] Hand Cursor for Searchbar dropdown items
  WalletWasabi.Fluent/Views/SearchBar/SearchBarDropdown.axaml
Labels: size/XS

#7743 [VDG] Receive addresses - Enable sorting on label column
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/AddressViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressesViewModel.cs
Labels: size/S

#7742 [VDG] Improve error message
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
Labels: size/XS

#7741 [VDG] Use `SmartLabel` in `HistoryItemViewModelBase.cs`
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinsHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/HistoryItemViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/TransactionHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
  WalletWasabi/Blockchain/Analysis/Clustering/SmartLabel.cs
Labels: size/S

#7746 [VDG] make `LabelsPanel` compatible with `SmartLabel`
  WalletWasabi.Fluent/Controls/LabelsItemsPresenter.cs
Labels: size/XS

#7768 [Trivial] Remove unused code
  WalletWasabi.Fluent/ViewModels/SearchBar/SearchItemProvider.cs
Labels: size/S

#7688 Re-implement `SecureRandom`
  WalletWasabi/Crypto/Randomness/InsecureRandom.cs
  WalletWasabi/Crypto/Randomness/SecureRandom.cs
Labels: size/M

#7758 [VDG] Retry after wrong password entry for wallet authorization
  WalletWasabi.Fluent/ViewModels/Dialogs/Authorization/AuthorizationDialogBase.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/Authorization/HardwareWalletAuthDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/Authorization/PasswordAuthDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/Views/Dialogs/Authorization/HardwareWalletAuthDialogView.axaml
  WalletWasabi.Fluent/Views/Dialogs/Authorization/PasswordAuthDialogView.axaml
Labels: size/M

#7735 Update to NBitcoin 7.0.6 (take 2)
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/packages.lock.json
  WalletWasabi.Packager/packages.lock.json
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/UnitTests/JsonConverters/ByteArrayJsonConverterTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/JsonConverters/CompactSignatureJsonConverterTests.cs
  WalletWasabi/CoinJoin/Common/Models/InputProofModel.cs
  WalletWasabi/Extensions/NBitcoinExtensions.cs
  WalletWasabi/JsonConverters/CompactSignatureJsonConverter.cs
  WalletWasabi/WalletWasabi.csproj
  WalletWasabi/packages.lock.json
Labels: size/L

#7785 [VDG] Add custom logic to display OOBE background on Add Wallet from SearchBar
  WalletWasabi.Fluent/ViewModels/SearchBar/SearchItemProvider.cs
Labels: size/S

#7783 [VDG] Add SearchBar TextBox behavior to select text on focus
  WalletWasabi.Fluent/Behaviors/TextBoxAutoSelectTextBehavior.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/SearchBarViewModel.cs
  WalletWasabi.Fluent/Views/SearchBar/SearchBar.axaml
Labels: size/M

#7787 Add WabiSabi CoinJoin monitor to status request API
  WalletWasabi.Backend/Controllers/BlockchainController.cs
  WalletWasabi.Backend/Global.cs
  WalletWasabi/Backend/Models/Responses/StatusResponse.cs
  WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
Labels: size/S

#7788 [VDG] [Fluent] Xaml cleanup
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml
  WalletWasabi.Fluent/Controls/HistoryPlaceholderPanel.axaml
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/Styles/FlyoutPresenter.axaml
  WalletWasabi.Fluent/Styles/TextBox.axaml
  WalletWasabi.Fluent/Views/AddWallet/Create/ConfirmRecoveryWordsView.axaml
  WalletWasabi.Fluent/Views/AddWallet/WelcomePageView.axaml
  WalletWasabi.Fluent/Views/Dialogs/ShowQrCameraDialogView.axaml
  WalletWasabi.Fluent/Views/HelpAndSupport/LinkView.axaml
  WalletWasabi.Fluent/Views/MainView.axaml
  WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
  WalletWasabi.Fluent/Views/SearchBar/SearchBarDropdown.axaml
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/Columns/AnonymitySetHeaderView.axaml
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletStatsView.axaml
  WalletWasabi.Fluent/Views/Wallets/HardwareWalletView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/Columns/IndicatorsColumnView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
  WalletWasabi.Fluent/Views/Wallets/LoadingControl.axaml
  WalletWasabi.Fluent/Views/Wallets/Receive/Columns/ActionsColumnView.axaml
  WalletWasabi.Fluent/Views/Wallets/Receive/Columns/AddressColumnView.axaml
  WalletWasabi.Fluent/Views/Wallets/Receive/Columns/LabelsColumnView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/PrivacyControlView.axaml
  WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
  WalletWasabi.Fluent/Views/Wallets/WatchOnlyWalletView.axaml
Labels: size/M

#7784 [VDG] [Fluent] Don't register Global with locator
  WalletWasabi.Fluent.Desktop/Program.cs
Labels: size/XS

#7776 [VDG] [Fluent] Use TreeDataGrid from official NuGet
  NuGet.Config
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
Labels: size/S

#7691 [VDG] [Trivial] SendView - To input max height
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Labels: size/XS

#7749 [VDG] Ignore case during pocket selection
  WalletWasabi.Fluent/Helpers/CoinPocketHelper.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
Labels: size/S

#7748 Add SuggestedMaxAmount
  WalletWasabi.Tests/Helpers/ArenaBuilder.cs
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/Rounds/MultipartyTransactionStateTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/CoinJoinCoinSelectionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/MultipartyTransactionTests.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Rounds/MaxSuggestedAmountProvider.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
  WalletWasabi/WabiSabi/Backend/Rounds/RoundParameters.cs
  WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Crypto/RoundHasher.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/MultipartyTransactionParameters.cs
  WalletWasabi/WabiSabi/Models/RoundState.cs
  WalletWasabi/WabiSabi/ProtocolContants.cs
Labels: size/L

#7779 Fix start up Window State
  WalletWasabi.Fluent.Desktop/Program.cs
  WalletWasabi.Fluent/Helpers/LinuxStartupHelper.cs
  WalletWasabi.Fluent/Helpers/StartupHelper.cs
  WalletWasabi.Fluent/Helpers/WindowsStartupHelper.cs
  WalletWasabi.Tests/Helpers/LinuxStartupTestHelper.cs
Labels: size/S

#7782 Specify blame rounds in logs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/LoggerTools.cs
Labels: size/M

#7810 [VDG] Put back correct margin to AdornerCanvas
  WalletWasabi.Fluent/Views/MainView.axaml
Labels: size/XS

#7811 [VDG] Fix wrong dialog behavior
  WalletWasabi.Fluent/Views/MainView.axaml
Labels: size/XS

#7816 [VDG] Fix missing error message in Dual Currency Input
  WalletWasabi.Fluent/Controls/DualCurrencyEntryBox.axaml
Labels: size/XS

#7818 [VDG] Take private pocket into account when it was autoselected
  WalletWasabi.Fluent/ViewModels/Wallets/Send/LabelSelectionViewModel.cs
  WalletWasabi.Tests/UnitTests/UserInterfaceTest/PocketSelectionTests.cs
Labels: size/L

#7813 [VDG] Fix flickering button
  WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
Labels: size/XS

#7815 [VDG] Fix dialog border on full screen
  WalletWasabi.Fluent/Controls/Dialog.axaml
Labels: size/XS

#7774 Correct password before checking
  WalletWasabi/Wallets/Wallet.cs
Labels: size/S

#7823 Fix missing icon in Pocket Selection
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/ChangeAvoidanceSuggestionControl.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/PocketSuggestionControl.axaml
Labels: size/S

#7793 [VDG] Coinjoin Profiles screen rework
  WalletWasabi.Fluent/Assets/CoinJoinProfiles/cost.png
  WalletWasabi.Fluent/Assets/CoinJoinProfiles/private.png
  WalletWasabi.Fluent/Assets/CoinJoinProfiles/speed.png
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/CoinJoinProfileViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/EconomicCoinJoinProfileViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/PrivateCoinJoinProfileViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/SpeedyCoinJoinProfileViewModel.cs
  WalletWasabi.Fluent/Views/CoinJoinProfiles/CoinJoinProfileControl.axaml
  WalletWasabi.Fluent/Views/CoinJoinProfiles/CoinJoinProfilesView.axaml
Labels: size/M

#7830 Vsize credentials fix
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/CredentialReissuanceTests.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
  WalletWasabi/WabiSabi/Client/ArenaClient.cs
Labels: size/L

#7756 Consider sybils for anonymity score calculation
  WalletWasabi.Tests/Helpers/BitcoinFactory.cs
  WalletWasabi.Tests/UnitTests/BlockchainAnalysis/CoinJoinAnonscoreTests.cs
  WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs
  WalletWasabi/Blockchain/Transactions/SmartTransaction.cs
Labels: size/L

#7833 [VDG] Improve private pocket autoselection logic
  WalletWasabi.Fluent/Helpers/EnumerableExtensions.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/LabelSelectionViewModel.cs
  WalletWasabi.Tests/UnitTests/UserInterfaceTest/PocketSelectionTests.cs
Labels: size/M

#7835 [VDG] [Trivial] Add missing icon back (used by SearchBar)
  WalletWasabi.Fluent/Icons/Icons.axaml
Labels: size/XS

#7826 Update the list of coins with the successfully registered ones.
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/XS

#7827 Add runtime support for Apple Silicon.
  WalletWasabi.Backend/WalletWasabi.Backend.csproj
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent.Generators/WalletWasabi.Fluent.Generators.csproj
  WalletWasabi.Fluent.Generators/packages.lock.json
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
  WalletWasabi.Packager/Program.cs
  WalletWasabi.Packager/WalletWasabi.Packager.csproj
  WalletWasabi.Packager/packages.lock.json
  WalletWasabi.Tests/WalletWasabi.Tests.csproj
  WalletWasabi/WalletWasabi.csproj
  WalletWasabi/packages.lock.json
Labels: size/XXL

#7842 [VDG] Loading wallet - no seconds displayed when more than 1 hr
  WalletWasabi.Fluent/ViewModels/Wallets/LoadingViewModel.cs
Labels: size/XS

#7846 [Trivial] Remove unnecessary null check
  WalletWasabi.Fluent/ViewModels/Wallets/Send/LabelSelectionViewModel.cs
  WalletWasabi.Tests/UnitTests/UserInterfaceTest/PocketSelectionTests.cs
Labels: size/S

#7839 Make AutoCoinJoin business logic more robust
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Labels: size/M

#7847 `WasabiRandom` is no longer `IDisposable`
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/PrivateCoinJoinProfileViewModel.cs
  WalletWasabi.Tests/UnitTests/Crypto/MacTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/ProofSystemTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/RandomTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/TranscriptTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/KnowledgeOfDlogTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/KnowledgeOfRepTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/CredentialTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/SerializationTests.cs
  WalletWasabi/Crypto/Randomness/InsecureRandom.cs
  WalletWasabi/Crypto/Randomness/RandomString.cs
  WalletWasabi/Crypto/Randomness/SecureRandom.cs
  WalletWasabi/Crypto/Randomness/WasabiRandom.cs
  WalletWasabi/Crypto/StringCipher.cs
  WalletWasabi/Extensions/TimeSpanExtensions.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/L

#7855 [TRIVIAL] WabiSabi Client coinjoin writing
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Labels: size/XS

#7856 [VDG] Remove dead code
  WalletWasabi.Fluent/Views/Wallets/Home/History/CoinJoinDetailsView.axaml
Labels: size/XS

#7838 `UiConfig`: Switch from `TaskPoolScheduler` to `MainThreadScheduler`
  WalletWasabi.Fluent/UiConfig.cs
Labels: size/XS

#7845 `Packager`: Minor changes regarding documentation and minor improvements
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Packager/ArgsProcessor.cs
  WalletWasabi.Packager/Program.cs
Labels: size/L

#7869 [Packager] Use macOS instead of OSX
  WalletWasabi.Packager/MacSignTools.cs
  WalletWasabi.Packager/Program.cs
Labels: size/S

#7868 [Packager] Add feature to pass appleId in CLI
  WalletWasabi.Packager/ArgsProcessor.cs
  WalletWasabi.Packager/MacSignTools.cs
  WalletWasabi.Packager/Program.cs
Labels: size/M

#7854 [Arena] Get the status from RoundStates instead of Rounds
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterOutputTests.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Models/RoundState.cs
Labels: size/M

#7881 Waiting for Blame round never times out
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/M

#7885 [TRIVIAL] WabiSabi backend coinjoin writing
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Rounds/CoinJoinStorage/CoinJoinTransactionArchiver.cs
Labels: size/XS
