Repository WalletWasabi/WalletWasabi, pull requests merged in 2022-05, with the labels that each got.

#7894 [trivial] Fix warnings and a typo
  WalletWasabi/Blockchain/Analysis/Clustering/Cluster.cs
  WalletWasabi/WabiSabi/Crypto/WabiSabiClient.cs
Labels: size/XS

#7900 Only stop restarting if round was intentionally stopped
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WabiSabi/Client/CoinJoinTracker.cs
Labels: size/S

#7901 Add test to verify round awaiter can be cancelled
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/RoundStateUpdaterTests.cs
Labels: size/S

#7888 Fix warnings in blinding tests.
  WalletWasabi.Tests/UnitTests/Crypto/BlindingTests.cs
Labels: size/S

#7887 [Trivial] Fix CodeFactor issues
  WalletWasabi.Tests/UnitTests/Crypto/MacTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/ProofSystemTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/CredentialReissuanceTests.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/S

#7867 [VDG] [Trivial] Unset default monospaced font for Flyouts
  WalletWasabi.Fluent/Styles/FlyoutPresenter.axaml
  WalletWasabi.Fluent/Views/SearchBar/SearchBarDropdown.axaml
Labels: size/XS

#7825 [VDG] Add wallet name to Loading screen
  WalletWasabi.Fluent/ViewModels/Wallets/LoadingViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/LoadingControl.axaml
Labels: size/S

#7792 [VDG] New Add Wallet options screen
  WalletWasabi.Fluent/Models/AddWalletPageOption.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/AddWalletPageView.axaml
Labels: size/L

#7731 [VDG] Dual Currency Input Minor layout improvement
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
  WalletWasabi.Fluent/Controls/DualCurrencyEntryBox.axaml
  WalletWasabi.Fluent/Controls/DualCurrencyEntryBox.axaml.cs
Labels: size/M

#7640 [VDG] Correct music status message
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
Labels: size/XS

#7781 [VDG] [Fluent] Log platform renderer
  WalletWasabi.Fluent.Desktop/Program.cs
Labels: size/S

#7886 BnB: Do not allow modifying BTC/USD exchange rate during computations
  WalletWasabi.Fluent/ViewModels/Wallets/Send/ChangeAvoidanceSuggestionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacySuggestionsFlyoutViewModel.cs
  WalletWasabi/Services/WasabiSynchronizer.cs
Labels: size/M

#7905 [Trivial] Place elements in correct order
  WalletWasabi.Fluent/ViewModels/SearchBar/Patterns/ComposedKey.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/SearchBarDesignViewModel.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/SearchItems/ActionableItem.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/SearchItems/NonActionableSearchItem.cs
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/RoundStateUpdaterTests.cs
Labels: size/L

#7904 [Trivial] Fix CodeFactor issues
  WalletWasabi.Fluent/ViewModels/SearchBar/Patterns/ComposedKey.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/SearchBarDesignViewModel.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/SearchItems/ActionableItem.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/SearchItems/NonActionableSearchItem.cs
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/RoundStateUpdaterTests.cs
Labels: size/M

#7807 [VDG] NavBar - HandCursor for Wallets & Items
  WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
Labels: size/XS

#7860 [WabiSabi] Lock-Free coordinator (part 1)
  WalletWasabi.Tests/Helpers/ArenaBuilder.cs
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/ConfirmConnectionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/CredentialReissuanceTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterOutputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/RoundCreationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/Rounds/MultipartyTransactionStateTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/CoinJoinCoinSelectionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiApiApplicationFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/MultipartyTransactionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/RoundStateUpdaterTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/SerializationTests.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Rounds/BlameRound.cs
  WalletWasabi/WabiSabi/Backend/Rounds/MaxSuggestedAmountProvider.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
  WalletWasabi/WabiSabi/Backend/Rounds/RoundParameterFactory.cs
  WalletWasabi/WabiSabi/Backend/Rounds/RoundParameters.cs
  WalletWasabi/WabiSabi/Client/AliceClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/ConstructionState.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/MultipartyTransactionParameters.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/MultipartyTransactionState.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/SigningState.cs
  WalletWasabi/WabiSabi/Models/RoundState.cs
  WalletWasabi/WabiSabi/Models/Serialization/CoinJoinEventJsonConverter.cs
  WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
Labels: size/XL

#7902 BnB: Restrict number of coins
  WalletWasabi.Fluent/ViewModels/Wallets/Send/ChangeAvoidanceSuggestionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacySuggestionsFlyoutViewModel.cs
  WalletWasabi.Tests/UnitTests/Blockchain/TransactionBuilding/BranchAndBoundTests.cs
  WalletWasabi.Tests/UnitTests/Blockchain/TransactionBuilding/ChangelessTransactionCoinSelectorTests.cs
  WalletWasabi/Blockchain/TransactionBuilding/BnB/CoinSelection.cs
  WalletWasabi/Blockchain/TransactionBuilding/BnB/LessSelectionStrategy.cs
  WalletWasabi/Blockchain/TransactionBuilding/BnB/MoreSelectionStrategy.cs
  WalletWasabi/Blockchain/TransactionBuilding/BnB/SelectionStrategy.cs
  WalletWasabi/Blockchain/TransactionBuilding/BnB/StrategyParameters.cs
  WalletWasabi/Blockchain/TransactionBuilding/ChangelessTransactionCoinSelector.cs
Labels: size/L

#7907 Tune down consolidation penalty in coinjoins
  WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs
Labels: size/XS

#7910 [VDG] decrease CPU & GPU usage
  WalletWasabi.Fluent/Views/Wallets/MusicControlsView.axaml
Labels: size/XS

#7915 Do not coinjoin insignificant amounts
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/M

#7914 [trivial] Shorten music box message
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
Labels: size/XS

#7906 Fix `isLongBan` missing after restart
  WalletWasabi/WabiSabi/Backend/Banning/Inmate.cs
Labels: size/XS

#7870 Prevent BnB to offer the same suggestion by amount
  WalletWasabi.Fluent/ViewModels/Wallets/Send/ChangeAvoidanceSuggestionViewModel.cs
Labels: size/S

#7899 [VDG] Remove fee from self transfer notifications
  WalletWasabi.Fluent/Helpers/NotificationHelpers.cs
Labels: size/XS

#7917 BnB: Fix bug in LessSelectionStrategy where `MinPaymentThreshold` paramete…
  WalletWasabi.Tests/UnitTests/Blockchain/TransactionBuilding/BranchAndBoundTests.cs
  WalletWasabi/Blockchain/TransactionBuilding/BnB/CoinSelection.cs
  WalletWasabi/Blockchain/TransactionBuilding/BnB/LessSelectionStrategy.cs
  WalletWasabi/Blockchain/TransactionBuilding/BnB/MoreSelectionStrategy.cs
  WalletWasabi/Blockchain/TransactionBuilding/BnB/SelectionStrategy.cs
Labels: size/M

#7918 `Wallet`: Remove unused code
  WalletWasabi.Tests/UnitTests/IoTests.cs
  WalletWasabi/Wallets/Wallet.cs
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/S

#7928 Lower min and max non-private UTXO target from 35 to 21 and from 150 to 100
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/XS

#7930 It's confusing if we trim
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/TransactionDetailsViewModel.cs
Labels: size/XS

#7936 Cleanup coin selection
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/M

#7933 [Trivial] Fix CodeFactor issues
  WalletWasabi.Fluent/Controls/Spectrum/SpectrumControl.cs
  WalletWasabi.Fluent/Controls/Spectrum/SpectrumDataSource.cs
Labels: size/M

#7934 [VDG] Adjust navbar tint colors & Fix icon foreground
  WalletWasabi.Fluent/Styles/Themes/BaseDark.axaml
  WalletWasabi.Fluent/Styles/Themes/BaseLight.axaml
  WalletWasabi.Fluent/Views/MainView.axaml
  WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
Labels: size/S

#7925 [Trivial] Fix CodeFactor issues
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi/Blockchain/TransactionBuilding/BnB/StrategyParameters.cs
  WalletWasabi/Blockchain/TransactionBuilding/ChangelessTransactionCoinSelector.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WabiSabi/Client/Events/CompletedEventArgs.cs
  WalletWasabi/WabiSabi/Client/Events/LoadedEventArgs.cs
  WalletWasabi/WabiSabi/Client/Events/StartErrorEventArgs.cs
  WalletWasabi/WabiSabi/Client/Events/StartedEventArgs.cs
  WalletWasabi/WabiSabi/Client/Events/StatusChangedEventArgs.cs
  WalletWasabi/WabiSabi/Client/Events/StoppedEventArgs.cs
  WalletWasabi/WabiSabi/Client/RoundStateAwaiters/RoundStateUpdater.cs
  WalletWasabi/WabiSabi/Client/StatusChangedEventArgs.cs
Labels: size/L

#7952 [VDG] Remove decimals from Balance Tile fiat amount when >= 10
  WalletWasabi.Fluent/Helpers/TextHelpers.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletBalanceTileViewModel.cs
Labels: size/S

#7950 Let CoinJoinClient communicate using events
  WalletWasabi/Extensions/EventHandlerExtensions.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WabiSabi/Client/CoinJoinProgressEventArgs.cs
  WalletWasabi/WabiSabi/Client/CoinJoinTracker.cs
  WalletWasabi/WabiSabi/Client/Events/CoinJoinStatusEventArgs.cs
Labels: size/L

#7951 Add possibility to get latest status of rounds
  WalletWasabi/WabiSabi/Client/RoundStateAwaiters/RoundStateAwaiter.cs
  WalletWasabi/WabiSabi/Client/RoundStateAwaiters/RoundStateUpdater.cs
Labels: size/S

#7955 [Trivial] Move classes to separate files to fix CodeFactor
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WabiSabi/Client/CoinJoinProgressEventArgs.cs
  WalletWasabi/WabiSabi/Client/CoinJoinProgressEvents/CoinJoinProgressEventArgs.cs
  WalletWasabi/WabiSabi/Client/CoinJoinProgressEvents/EnteringInputRegistrationPhase.cs
  WalletWasabi/WabiSabi/Client/CoinJoinProgressEvents/EnteringOutputRegistrationPhase.cs
  WalletWasabi/WabiSabi/Client/CoinJoinProgressEvents/EnteringSigningPhase.cs
  WalletWasabi/WabiSabi/Client/CoinJoinProgressEvents/RoundEnded.cs
  WalletWasabi/WabiSabi/Client/CoinJoinProgressEvents/RoundStateChanged.cs
  WalletWasabi/WabiSabi/Client/CoinJoinProgressEvents/WaitingForBlameRound.cs
  WalletWasabi/WabiSabi/Client/CoinJoinProgressEvents/WaitingForRound.cs
  WalletWasabi/WabiSabi/Client/CoinJoinTracker.cs
  WalletWasabi/WabiSabi/Client/Events/CoinJoinStatusEventArgs.cs
Labels: size/L

#7957 [Trivial] Edit folder name
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WabiSabi/Client/StatusChangedEvents/CoinJoinStatusEventArgs.cs
  WalletWasabi/WabiSabi/Client/StatusChangedEvents/CompletedEventArgs.cs
  WalletWasabi/WabiSabi/Client/StatusChangedEvents/LoadedEventArgs.cs
  WalletWasabi/WabiSabi/Client/StatusChangedEvents/StartErrorEventArgs.cs
  WalletWasabi/WabiSabi/Client/StatusChangedEvents/StartedEventArgs.cs
  WalletWasabi/WabiSabi/Client/StatusChangedEvents/StatusChangedEventArgs.cs
  WalletWasabi/WabiSabi/Client/StatusChangedEvents/StoppedEventArgs.cs
Labels: size/S

#7958 Coinjoin Phase event nits
  WalletWasabi/WabiSabi/Client/CoinJoinProgressEvents/EnteringInputRegistrationPhase.cs
  WalletWasabi/WabiSabi/Client/CoinJoinProgressEvents/EnteringOutputRegistrationPhase.cs
  WalletWasabi/WabiSabi/Client/CoinJoinProgressEvents/EnteringSigningPhase.cs
  WalletWasabi/WabiSabi/Client/CoinJoinProgressEvents/RoundStateChanged.cs
  WalletWasabi/WabiSabi/Client/CoinJoinProgressEvents/WaitingForBlameRound.cs
  WalletWasabi/WabiSabi/Client/StatusChangedEvents/CoinJoinStatusEventArgs.cs
Labels: size/S

#7959 Musicbox - make countdown reusable
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
Labels: size/M

#7963 Musicbox - do not run timer when it is not necessary
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
Labels: size/S

#7954 [VDG] [Trivial] Fix SearchBar caret brush in Light Mode
  WalletWasabi.Fluent/Views/SearchBar/SearchBar.axaml
Labels: size/XS

#7965 [TRIVIAL] simplify condition
  WalletWasabi.Fluent/ViewModels/Wallets/Send/LabelSelectionViewModel.cs
Labels: size/XS

#7966 [VDG] Music Box - fire like animation in critical phase
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi.Fluent/Views/MainView.axaml
  WalletWasabi/WabiSabi/Client/CoinJoinProgressEvents/CoinJoinProgressEventArgs.cs
  WalletWasabi/WabiSabi/Client/CoinJoinTracker.cs
Labels: size/S

#7969 [VDG] Use the colored version of TrayIcon in all platforms.
  WalletWasabi.Fluent/ViewModels/ApplicationViewModel.cs
Labels: size/S

#7970 Fixes/deterministic build
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/Behaviors/MainWindowPersistPositionBehavior.cs
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
Labels: size/L

#7968 set `IsInCriticalPhase` at the proper places
  WalletWasabi/WabiSabi/Client/CoinJoinProgressEvents/CoinJoinProgressEventArgs.cs
  WalletWasabi/WabiSabi/Client/CoinJoinProgressEvents/EnteringOutputRegistrationPhase.cs
  WalletWasabi/WabiSabi/Client/CoinJoinProgressEvents/EnteringSigningPhase.cs
  WalletWasabi/WabiSabi/Client/CoinJoinTracker.cs
Labels: size/XS

#7962 Add timeout for connection confirmation phase as well
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/S

#7976 [VDG] Fix dialog VM being retained in memory
  WalletWasabi.Fluent/ViewModels/ApplicationViewModel.cs
Labels: size/S

#7980 [Trivial] Rename CancellationTokenSource variables
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/S

#7971 potential coinslist mem leak fix.
  WalletWasabi.Fluent/Extensions/ObservableExtension.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
Labels: size/M

#7919 Set Coinjoin profile when WW1 wallet is opened first time in WW2
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/ConfirmRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/CoinJoinProfilesViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/LoginViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/RoutableViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletSettingsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/RecoverWalletView.axaml
  WalletWasabi.Fluent/Views/Wallets/WalletSettingsView.axaml
  WalletWasabi/Blockchain/Keys/KeyManager.cs
Labels: size/L

#7973 [VDG] MusicBox - show coinjoin phases
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/MusicControlsView.axaml
  WalletWasabi/WabiSabi/Client/CoinJoinProgressEvents/EnteringConnectionConfirmationPhase.cs
Labels: size/L

#7975 [VDG] Dont use monospace on all text in TileControl
  WalletWasabi.Fluent/Controls/TileControl.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/BtcPriceTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceTileView.axaml
Labels: size/XS

#7990 Debug-only `<PackageReference>` and packages.lock.json files
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Packager/Program.cs
  azure-pipelines-linux.yml
  azure-pipelines-osx.yml
  azure-pipelines-windows.yml
Labels: size/M

#7987 [Trivial] Clarify log message
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Labels: size/XS

#7985 Fix some Fluent warnings
  WalletWasabi.Fluent/Behaviors/HistoryItemDetailsBehavior.cs
  WalletWasabi.Fluent/Behaviors/ShowFlyoutOnPointerOverBehavior.cs
  WalletWasabi.Fluent/Rpc/WasabiJsonRpcService.cs
  WalletWasabi.Tests/UnitTests/KeyManagementTests.cs
  WalletWasabi/Backend/Models/ExchangeRate.cs
  WalletWasabi/Backend/Models/Responses/FiltersResponse.cs
  WalletWasabi/Backend/Models/Responses/SynchronizeResponse.cs
  WalletWasabi/Blockchain/Keys/HdPubKey.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/Crypto/Bip322Signature.cs
  WalletWasabi/Rpc/JsonRpcServer.cs
Labels: size/M

#8010 [VDG] [TRIVIAL] Better wallet loading text
  WalletWasabi.Fluent/Views/Wallets/LoadingControl.axaml
Labels: size/XS

#7993 Set CoinJoinInProgress false before report RoundEnded
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WabiSabi/Client/CoinJoinProgressEvents/RoundEnded.cs
Labels: size/M

#7991 [VDG] Handle long balance text
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceTileView.axaml
Labels: size/S

#8016 [VDG] [Trivial] Set initial value of SearchText to empty string
  WalletWasabi.Fluent/ViewModels/SearchBar/SearchBarViewModel.cs
Labels: size/XS

#8014 [VDG] HandCursor ToggleSwitch
  WalletWasabi.Fluent/Styles/Styles.axaml
  WalletWasabi.Fluent/Styles/ToggleSwitch.axaml
Labels: size/XS

#7801 [VDG] [Fluent] Group pending transactions
  WalletWasabi.Fluent/Behaviors/PendingHistoryItemSeparatorBehavior.cs
  WalletWasabi.Fluent/Converters/BoolToGenericConverter.cs
  WalletWasabi.Fluent/Converters/BooleanValueConverters.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/HistoryItemViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/TransactionHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
Labels: size/L

#7977 [VDG] [Fluent] Set SelectedIndex for TreeDataGrid from UIThread
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
Labels: size/XS

#7920 [VDG] Fix CPU & GPU usage when idle
  WalletWasabi.Fluent/Controls/ProgressRing.axaml
  WalletWasabi.Fluent/Controls/Spectrum/AuraSpectrumDataSource.cs
  WalletWasabi.Fluent/Controls/Spectrum/SpectrumControl.cs
  WalletWasabi.Fluent/Controls/Spectrum/SpectrumDataSource.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
Labels: size/M

#8019 Trivial: dont show release name in titlebar.
  WalletWasabi.Fluent/Views/Shell/TitleBarView.axaml
Labels: size/XS

#7988 [VDG] Add every disposable to the "disposables" list
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
Labels: size/M

#7964 Differentiate normal and long ban
  WalletWasabi.Backend/Filters/ExceptionTranslateFilter.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/UtxoPrisonTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi/Tor/Http/Extensions/HttpResponseMessageExtensions.cs
  WalletWasabi/WabiSabi/Backend/Banning/Inmate.cs
  WalletWasabi/WabiSabi/Backend/Banning/Prison.cs
  WalletWasabi/WabiSabi/Backend/Banning/Punishment.cs
  WalletWasabi/WabiSabi/Backend/Models/ExceptionData.cs
  WalletWasabi/WabiSabi/Backend/Models/InputBannedExceptionData.cs
  WalletWasabi/WabiSabi/Backend/Models/WabiSabiProtocolErrorCode.cs
  WalletWasabi/WabiSabi/Backend/Models/WabiSabiProtocolException.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
  WalletWasabi/WabiSabi/Client/AliceClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WabiSabi/Models/Error.cs
  WalletWasabi/WabiSabi/Models/Serialization/ExceptionDataJsonConverter.cs
  WalletWasabi/WabiSabi/Models/Serialization/JsonSerializationOptions.cs
Labels: size/L

#7996 Disable `AutoCoinJoin` when coinjoin profile is not selected
  WalletWasabi.Fluent/ViewModels/Login/LoginViewModel.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
Labels: size/M

#7892 [Backport] Suggest same words multiple times when typing recovery words
  WalletWasabi.Gui/Tabs/WalletManager/RecoverWallets/RecoverWalletViewModel.cs
Labels: size/XS

#8035 Use Interlocked to prevent multiple invocations
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/M

#8027 Do not try to use immature coins for coinjoins
  WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WabiSabi/Client/StatusChangedEvents/StatusChangedEventArgs.cs
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/S

#8025 Use weighted average for consolidation in coinjoin
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/CoinJoinProfileViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/CoinJoinProfilesViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/ManualCoinJoinProfileViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/PrivateCoinJoinProfileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/ManualCoinJoinProfileDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletBalanceTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacySuggestionsFlyoutViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionInfo.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletSettingsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/Views/Dialogs/ManualCoinJoinProfileDialogView.axaml
  WalletWasabi.Fluent/Views/Wallets/WalletSettingsView.axaml
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/CoinJoinCoinSelectionTests.cs
  WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/CoinJoin/Client/Rounds/ClientState.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WabiSabi/Client/CoinJoinTrackerFactory.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: debug, question/research, feature/enhancement, priority, size/L

#8041 [VDG] [TRIVIAL] Update CanUserSort
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
Labels: size/XS

#8022 [VDG] [Fluent] Show history details button without adorner
  WalletWasabi.Fluent/Behaviors/HistoryItemDetailsBehavior.cs
  WalletWasabi.Fluent/Controls/AdornerCanvas.cs
  WalletWasabi.Fluent/Controls/TreeDataGridItemDetailsAdorner.cs
  WalletWasabi.Fluent/Views/Shell/ShellView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/Columns/IndicatorsColumnView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
Labels: size/L

#7972 Add possiblity to continue when PlebStop 2
  WalletWasabi.Fluent/State/StateMachine.cs
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi.Tests/UnitTests/StateMachineTests.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WabiSabi/Client/CoinJoinTracker.cs
  WalletWasabi/WabiSabi/Client/CoinJoinTrackerFactory.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/XL

#8017 [VDG] MusicBox - disable indeterminate progressbar when counting has finished
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
Labels: size/XS

#8046 Fix coin selector bug
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/S

#8037 [Trivial] Fix typo
  WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
  WalletWasabi/Blockchain/Transactions/SmartTransaction.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Labels: size/S

#8047 [VDG] Enter correct state in ApplicationStateManager
  WalletWasabi.Fluent/ApplicationStateManager.cs
Labels: size/XS

#8045 remove state machine hacks
  WalletWasabi.Fluent/State/StateMachine.cs
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi.Tests/UnitTests/StateMachineTests.cs
Labels: size/M

#8048 Statemachine hacks followup
  WalletWasabi.Fluent/ApplicationStateManager.cs
  WalletWasabi.Fluent/State/StateMachine.cs
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
Labels: size/S

#8038 [WabiSabi] Allow to distinguish round failing reasons
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Models/RoundState.cs
Labels: size/L

#8036 Fix Backend.Global nullables
  WalletWasabi.Backend/Global.cs
Labels: size/M

#8033 [VDG] Fast loading for new wallets
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/LoadingViewModel.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
Labels: size/S

#8034 Further warning fixes
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/SearchBarDesignViewModel.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/SearchItems/IActionableItem.cs
  WalletWasabi/Bases/ConfigBase.cs
  WalletWasabi/CoinJoin/Coordinator/MixingLevels/MixingLevelCollection.cs
  WalletWasabi/Rpc/JsonRpcResponse.cs
  WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
Labels: size/M

#8055 Fix Backend Global
  WalletWasabi.Backend/Global.cs
Labels: size/S

#7994 [VDG] TreeDataGrid - adjust shorticon position
  WalletWasabi.Fluent/Styles/TreeDataGrid.axaml
Labels: size/XS

#8058 update avalonia to a new nightly build (0.10.x candidate) fixes osx r…
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
Labels: size/L

#8050 [VDG] Fix weird SearchBar state
  WalletWasabi.Fluent/Views/SearchBar/SearchBar.axaml
Labels: size/XS

#8060 Recovered wallet must be synchronized
  WalletWasabi/Blockchain/Keys/KeyManager.cs
Labels: size/XS

#8063 [VDG] Increase BTC columns width
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
Labels: size/S

#8029 [VDG] Widen up the navbar to accomodate the bottom menu text
  WalletWasabi.Fluent/Controls/NavBarItem.axaml
  WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
Labels: size/M

#8067 Fix StateMachine IsInState logic
  WalletWasabi.Fluent/State/StateMachine.cs
  WalletWasabi.Tests/UnitTests/StateMachineTests.cs
Labels: size/M

#8066 Make cj log better
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WabiSabi/LoggerTools.cs
Labels: size/M

#8070 Fix remaining time for IR
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/XS

#7802 [VDG] Put labels back onto the transaction preview screen
  WalletWasabi.Fluent/Helpers/CoinPocketHelper.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/ConfirmLabelsDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/LabelSelectionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PocketSuggestionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacySuggestionsFlyoutViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionInfo.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionSummaryViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Send/ConfirmLabelsDialogView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/ConfirmLabelsDialogView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Send/PocketSuggestionControl.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/PocketSuggestionControl.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionSummary.axaml
  WalletWasabi.Tests/UnitTests/UserInterfaceTest/PocketSelectionTests.cs
Labels: size/L

#8073 [WabiSabi] Do not try to register uneconomical inputs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/XS

#8076 Do not let and detect double start of CoinJoinClient
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Labels: size/S

#8082 [VDG] Remove window position behavior
  WalletWasabi.Fluent/Behaviors/MainWindowPersistPositionBehavior.cs
  WalletWasabi.Fluent/UiConfig.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/Views/MainWindow.axaml
Labels: size/L

#8079 Update README.md
  README.md
Labels: size/XS

#8057 [VDG] Show IsBanned property in CoinList
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/Columns/IndicatorsColumnView.axaml
Labels: size/S

#8088 Update CoinJoinProfilesView.axaml
  WalletWasabi.Fluent/Views/CoinJoinProfiles/CoinJoinProfilesView.axaml
Labels: size/XS

#8086 [VDG] Fix SearchBar Flyout that stays open-misplaced on taskbar click (Win10)
  WalletWasabi.Fluent/Behaviors/SearchBarBehavior.cs
Labels: size/S

#8056 [VDG] Fix termination threading issue
  WalletWasabi.Fluent.Desktop/Program.cs
  WalletWasabi/Services/Terminate/TerminateService.cs
Labels: size/S

#8092 [Trivial] Use DateTimeOffset.UtcNow instead of DateTimeOffset.Now
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
Labels: size/XS

#8087 [VDG] Wallet Coins - Increase Anonymity Score column width
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
Labels: size/S

#7843 [VDG] Correct icon & color for privacy threshold & sanity check
  WalletWasabi.Fluent/Views/Wallets/WalletSettingsView.axaml
Labels: size/XS

#8039 [VDG] Shutdown dialog improvements
  WalletWasabi.Fluent/ViewModels/ApplicationViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/ShuttingDownViewModel.cs
  WalletWasabi.Fluent/Views/Dialogs/ShuttingdownDialogView.axaml
Labels: size/M

#8065 [VDG] Fix splash animation triggered by the SearchBar
  WalletWasabi.Fluent/ViewModels/SearchBar/Sources/ActionsSource.cs
  WalletWasabi.Fluent/ViewModels/TriggerCommandViewModel.cs
Labels: size/S

#8083 [VDG] Show Block Hash in transaction details
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/TransactionDetailsViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/TransactionDetailsView.axaml
  WalletWasabi/Blockchain/Transactions/TransactionHistoryBuilder.cs
  WalletWasabi/Blockchain/Transactions/TransactionSummary.cs
Labels: size/S

#8090 Report AllCoinsPrivate
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WabiSabi/Client/StatusChangedEvents/StatusChangedEventArgs.cs
Labels: size/S

#8093 [VDG] Fix margins in PreviewItem
  WalletWasabi.Fluent/Controls/PreviewItem.axaml
Labels: size/XS

#8024 [VDG] [Fluent] Add additional context menu items for history table items
  WalletWasabi.Fluent/Behaviors/HistoryItemTypeClassBehavior.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/CoinJoinDetailsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/CoinJoinsDetailsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/TransactionDetailsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinsHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/HistoryItemViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/TransactionHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/Details/CoinJoinDetailsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/Details/CoinJoinDetailsView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/Details/CoinJoinsDetailsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/Details/CoinJoinsDetailsView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/Details/TransactionDetailsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/Details/TransactionDetailsView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
Labels: size/L

#8105 Update `AnonScoreTarget` upon opening Wallet Settings
  WalletWasabi.Fluent/ViewModels/Wallets/WalletSettingsViewModel.cs
Labels: debug, size/XS

#8106 [VDG] [TRIVIAL] Block hash wording
  WalletWasabi.Fluent/Views/Wallets/Home/History/Details/TransactionDetailsView.axaml
Labels: size/XS

#8117 Improve Coin Selection For Coinjoins
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/M

#8116 [VDG] Adjust status indicator margin
  WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
Labels: size/XS

#8104 Rename to AutoStartCoinjoin
  WalletWasabi.Fluent/Views/CoinJoinProfiles/CoinJoinProfilesView.axaml
  WalletWasabi.Fluent/Views/Dialogs/ManualCoinJoinProfileDialogView.axaml
  WalletWasabi.Fluent/Views/Wallets/MusicControlsView.axaml
  WalletWasabi.Fluent/Views/Wallets/WalletSettingsView.axaml
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Labels: size/S

#8118 Make NotEnoughAlicesMessage visible and clear
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/RoundStateAwaiters/RoundStateAwaiter.cs
  WalletWasabi/WabiSabi/Client/RoundStateAwaiters/UnexpectedRoundPhaseException.cs
Labels: size/M

#8119 [VDG] Set IsSearchPanelOpen flag in Show/Hide Flyout
  WalletWasabi.Fluent/Behaviors/SearchBarBehavior.cs
Labels: size/XS

#8122 [VDG] Hide title text on minimum width
  WalletWasabi.Fluent/Views/Shell/TitleBarView.axaml
Labels: size/S

#8123 [VDG] Improve MusicBox colors
  WalletWasabi.Fluent/Views/Wallets/MusicControlsView.axaml
Labels: size/S

#8128 [VDG] [Trivial] Enable Avalonia Previewer
  WalletWasabi.Fluent.Desktop/Program.cs
Labels: size/XS

#8127 [VDG] Don't use Oaph
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/Views/Shell/MainView.axaml
  WalletWasabi.Fluent/Views/Wallets/MusicControlsView.axaml
Labels: size/S

#8072 update avalonia with more osx regression fixes.
  NuGet.Config
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
Labels: size/L

#8129 [VDG] Update Avalonia.Controls.TreeDataGrid to version 0.10.14
  NuGet.Config
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
Labels: size/S

#8131 Add option to search Category in Searchbar
  WalletWasabi.Fluent/ViewModels/SearchBar/SearchBarViewModel.cs
Labels: size/XS

#8133 [VDG] [Trivial] Xaml cleanup
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml
  WalletWasabi.Fluent/Styles/TextBox.axaml
  WalletWasabi.Fluent/Views/AddWallet/AddWalletPageView.axaml
  WalletWasabi.Fluent/Views/CoinJoinProfiles/CoinJoinProfilesView.axaml
  WalletWasabi.Fluent/Views/MainWindow.axaml
  WalletWasabi.Fluent/Views/SearchBar/SearchBarDropdown.axaml
  WalletWasabi.Fluent/Views/Shell/ShellView.axaml
  WalletWasabi.Fluent/Views/Shell/TitleBarView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionSummary.axaml
Labels: size/S

#8136 Improve CoinJoinManager
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WabiSabi/Client/CoinJoinTracker.cs
Labels: size/L

#8141 [VDG] [Trivial] Make World Map animation don't disappear with enough size
  WalletWasabi.Fluent/Views/Wallets/LoadingControl.axaml
Labels: size/XS

#8142 Consolidate more heavily
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/S

#8144 [VDG] Adjust adaptive layout for LoadingControl
  WalletWasabi.Fluent/Views/Wallets/LoadingControl.axaml
Labels: size/M

#8110 [VDG] Copy coinjoin fee in sats
  WalletWasabi.Fluent/Views/Wallets/Home/History/Details/CoinJoinDetailsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/Details/CoinJoinsDetailsView.axaml
Labels: size/XS

#8139 [VDG] Move Tor settings to General settings
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/Sources/SettingsSource.cs
  WalletWasabi.Fluent/ViewModels/Settings/GeneralSettingsTabViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/SettingsPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/TorSettingsTabViewModel.cs
  WalletWasabi.Fluent/Views/Settings/GeneralSettingsTabView.axaml
  WalletWasabi.Fluent/Views/Settings/SettingsPageView.axaml
  WalletWasabi.Fluent/Views/Settings/TorSettingsTabView.axaml
  WalletWasabi.Fluent/Views/Settings/TorSettingsTabView.axaml.cs
Labels: size/L

#8140 Refactoring musicbox
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/MusicControlsView.axaml
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WabiSabi/Client/CoinJoinTracker.cs
  WalletWasabi/WabiSabi/Client/RoundStateAwaiters/NoCoinsToMixException.cs
  WalletWasabi/WabiSabi/Client/StatusChangedEvents/WalletStartedCoinJoinEventArgs.cs
  WalletWasabi/WabiSabi/Client/StatusChangedEvents/WalletStoppedCoinJoinEventArgs.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/XL

#8147 Make sure BnB uses coins only from the pockets that were used during transaction building
  WalletWasabi.Fluent/ViewModels/Wallets/Send/ChangeAvoidanceSuggestionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacySuggestionsFlyoutViewModel.cs
Labels: size/S

#8096 [VDG] Send specific coins
  WalletWasabi.Fluent/ViewModels/Dialogs/AddressEntryDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionInfo.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Fluent/Views/Dialogs/AddressEntryDialogView.axaml
  WalletWasabi.Fluent/Views/Dialogs/AddressEntryDialogView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/Columns/SelectionColumnView.axaml
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/Columns/SelectionColumnView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/WalletCoinsView.axaml
Labels: size/L

#8148 Bump testnet version to v.1.98.4.0
  WalletWasabi/Helpers/Constants.cs
Labels: size/XS

#8149 Bump Internal Main v1.99.1
  WalletWasabi.Fluent/Config.cs
  WalletWasabi/Helpers/Constants.cs
Labels: size/XS

#7995 [VDG] Make SearchBar handle window resize correctly
  WalletWasabi.Fluent/Behaviors/SearchBarBehavior.cs
Labels: size/XS

#8166 Change unobserved task exception logging level
  WalletWasabi.Backend/InitConfigStartupTask.cs
Labels: size/XS

#8179 [mostly trivial] Fix a few typos
  WalletWasabi.Fluent/Helpers/WalletHelpers.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/Authorization/PasswordAuthDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/LoginViewModel.cs
  WalletWasabi/Extensions/LinqExtensions.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/S

#8177 [trivial] Change namespace of `LinqExtensions` file
  WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
  WalletWasabi.Tests/UnitTests/LinqExtensionsTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/AllTransactionStoreTests.cs
  WalletWasabi/BitcoinCore/Rpc/RpcClientBase.cs
  WalletWasabi/BitcoinP2p/P2pNetwork.cs
  WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs
  WalletWasabi/Blockchain/TransactionBuilding/SmartCoinSelector.cs
  WalletWasabi/Blockchain/Transactions/AllTransactionStore.cs
  WalletWasabi/Blockchain/Transactions/TransactionHistoryBuilder.cs
  WalletWasabi/Blockchain/Transactions/TransactionStore.cs
  WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
  WalletWasabi/CoinJoin/Client/Rounds/ClientState.cs
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
  WalletWasabi/Exceptions/InvalidTxException.cs
  WalletWasabi/Extensions/LinqExtensions.cs
  WalletWasabi/Extensions/RPCClientExtensions.cs
  WalletWasabi/Tor/Http/Extensions/HttpRequestMessageExtensions.cs
  WalletWasabi/Tor/Http/Helpers/HttpMessageHelper.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
  WalletWasabi/Wallets/P2pBlockProvider.cs
  WalletWasabi/WebClients/Wasabi/WasabiClient.cs
Labels: size/S

#8175 [trivial] Remove unused method
  WalletWasabi.Fluent/Helpers/TransactionHelpers.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/ChangeAvoidanceSuggestionViewModel.cs
Labels: size/S

#8174 Add Win10+ checks
  WalletWasabi/Services/SleepInhibitor.cs
  WalletWasabi/Tor/Socks5/TorTcpConnectionFactory.cs
Labels: size/M

#8169 Improve message for entities that know about the tx
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionSummary.axaml
Labels: size/XS

#8159 [VDG] MusicBox - disable button instead of hide in critical phase
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/MusicControlsView.axaml
Labels: size/S

#8152 [Trivial] Change coinjoin messages
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
Labels: size/XS

#8186 [VDG] Privacy mode Amount Transaction Details
  WalletWasabi.Fluent/Views/Wallets/Home/History/Details/TransactionDetailsView.axaml
Labels: size/XS

#8187 Increase max anonscore from 150 to 300
  WalletWasabi.Fluent/Views/Dialogs/ManualCoinJoinProfileDialogView.axaml
  WalletWasabi.Fluent/Views/Wallets/WalletSettingsView.axaml
Labels: size/XS
