Repository WalletWasabi/WalletWasabi, pull requests merged in 2022-12, with the labels that each got.

#9673 [VDG] Theme change icon - adjust colors
  WalletWasabi.Fluent/Views/Settings/ThemeChangeView.axaml
Labels: size/S

#9684 Move input reg code into ProceedWithInputRegAndConfirmAsync
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/M

#9672 [VDG] Manual CJ profile selection - shortened condition
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/CoinJoinProfilesViewModel.cs
Labels: size/XS

#9676 `TransactionStore`: Cleanup
  WalletWasabi.Tests/UnitTests/Transactions/TransactionStoreTests.cs
  WalletWasabi/Blockchain/Transactions/AllTransactionStore.cs
  WalletWasabi/Blockchain/Transactions/TransactionStore.cs
  WalletWasabi/Stores/IndexStore.cs
Labels: size/M

#9696 Apple silicon
  WalletWasabi.Backend/wwwroot/css/style.css
  WalletWasabi.Backend/wwwroot/img/icon_apple_silicon.svg
  WalletWasabi.Backend/wwwroot/index.html
Labels: size/M

#9694 [trivial] A few typos & code style
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/SignTransactionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/MultipartyTransactionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/SerializationTests.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/ConstructionState.cs
Labels: size/M

#9671 Update Logs part of Issue creation
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: size/S

#9503 .NET 7
  README.md
  WalletWasabi.Backend/Dockerfile
  WalletWasabi.Backend/WalletWasabi.Backend.csproj
  WalletWasabi.Documentation/Guides/HowToDebug.md
  WalletWasabi.Documentation/WasabiCompatibility.md
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
  WalletWasabi.Packager/WalletWasabi.Packager.csproj
  WalletWasabi.Packager/packages.lock.json
  WalletWasabi.Tests/WalletWasabi.Tests.csproj
  WalletWasabi/WalletWasabi.csproj
  WalletWasabi/packages.lock.json
  azure-pipelines-cd.yml
  azure-pipelines-detbuild.yml
  azure-pipelines-linux.yml
  azure-pipelines-osx.yml
  azure-pipelines-windows.yml
  global.json
Labels: size/L

#9592 correct incoming notification
  WalletWasabi.Fluent/Helpers/NotificationHelpers.cs
Labels: size/XS

#9667 Verify back Installer's hashes in Packager
  WalletWasabi.Packager/Program.cs
  WalletWasabi/Helpers/WasabiSignerHelpers.cs
Labels: size/S

#9651 [VDG] Add Wallet - adjust buttons for narrow window size
  WalletWasabi.Fluent/Controls/TileButton.axaml
  WalletWasabi.Fluent/Views/AddWallet/AddWalletPageView.axaml
Labels: size/M

#9647 [VDG] Discreet mode autofill
  WalletWasabi.Fluent/Controls/PrivacyContentControl.axaml
  WalletWasabi.Fluent/Controls/PrivacyContentControl.axaml.cs
  WalletWasabi.Fluent/Controls/PrivacyTextPresenter.cs
  WalletWasabi.Fluent/Views/Settings/BitcoinTabSettingsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/Columns/AmountColumnView.axaml
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/Columns/LabelsColumnView.axaml
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletInfoView.axaml
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletStatsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/Columns/LabelsColumnView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/Details/CoinJoinDetailsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/Details/CoinJoinsDetailsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/Details/TransactionDetailsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyControlTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyRing/PrivacyRingDetailsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Receive/Columns/AddressColumnView.axaml
  WalletWasabi.Fluent/Views/Wallets/Receive/Columns/LabelsColumnView.axaml
  WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveAddressView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Labels: size/L

#9708 Make sure we never use other than segwit script for change outputs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
Labels: size/XS

#9712 move CJ started notification to where client actually started
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Labels: size/XS

#9707 macOS - sleep inhibiting II
  WalletWasabi.Tests/UnitTests/Clients/PreventSleepTests.cs
  WalletWasabi.Tests/UnitTests/Helpers/PowerSaving/BaseInhibitorTaskTests.cs
  WalletWasabi.Tests/UnitTests/Helpers/PowerSaving/LinuxInhibitorTaskTests.cs
  WalletWasabi/Helpers/EnvironmentHelpers.cs
  WalletWasabi/Helpers/PowerSaving/BaseInhibitorTask.cs
  WalletWasabi/Helpers/PowerSaving/LinuxInhibitorTask.cs
  WalletWasabi/Helpers/PowerSaving/MacOsInhibitorTask.cs
  WalletWasabi/Microservices/ProcessAsync.cs
  WalletWasabi/Services/SleepInhibitor.cs
  WalletWasabi/WabiSabi/Backend/Rounds/RoundParameters.cs
Labels: size/XL

#9714 Fix "Bitcoin Knots doesn't work" issue
  WalletWasabi.Fluent/Global.cs
  WalletWasabi.Tests/Helpers/TestNodeBuilder.cs
  WalletWasabi/BitcoinCore/CoreNode.cs
  WalletWasabi/BitcoinCore/CoreNodeParams.cs
Labels: size/S

#9701 Fix icon to adhere to standard macOS look.
  WalletWasabi.Packager/Content/Osx/WasabiLogo.icns
Labels: size/XS

#9717 [VDG] Disable style for NavBarItem as we do not have dragging enabled
  WalletWasabi.Fluent/Controls/NavBarItem.axaml
Labels: size/XS

#9705 Extract round related actions to method
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinResult.cs
Labels: size/L

#9732 AddOrReplace to fix ArgumentException
  WalletWasabi/Blockchain/Keys/HdPubKeyCache.cs
Labels: size/XS

#9740 [VDG] Remove key gap fields from Wallet Stats
  WalletWasabi.Fluent/Helpers/KeyManagerExtensions.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletStatsViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletStatsView.axaml
  WalletWasabi.Tests/UnitTests/KeyManagementTests.cs
Labels: size/M

#9744 [VDG] [Taproot UI support] #6 - Remove minimum gap limit reached notification
  WalletWasabi.Fluent/Rpc/WasabiJsonRpcService.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveViewModel.cs
  WalletWasabi.Tests/RegressionTests/BuildTests.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi.Tests/RegressionTests/WalletTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
Labels: size/M

#9704 Remove backward compatibility code
  WalletWasabi.Tests/UnitTests/Transactions/AllTransactionStoreTests.cs
  WalletWasabi/Blockchain/Transactions/AllTransactionStore.cs
  WalletWasabi/Stores/IndexStore.cs
  WalletWasabi/Wallets/FileSystemBlockRepository.cs
Labels: size/L

#9591 Revert "Reduce the `RangeProof` by 5 bits"
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/Rounds/MultipartyTransactionStateTests.cs
  WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
  WalletWasabi/WabiSabi/ProtocolConstants.cs
Labels: size/S

#9729 [VDG] Add confirmation count to CJ details view
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/CoinJoinDetailsViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/Details/CoinJoinDetailsView.axaml
Labels: size/S

#9721 Run Wasabi Wallet After Install
  WalletWasabi.WindowsInstaller/Product.wxs
Labels: size/S

#9747 [Housekeeping][Easy] Forward cancellation tokens
  WalletWasabi/BitcoinCore/CoreNode.cs
  WalletWasabi/Rpc/JsonRpcServer.cs
  WalletWasabi/Services/SingleInstanceChecker.cs
Labels: size/XS

#9746 [Tor] `HeaderSection`: Remove unused `ToString(bool endWithTwoCRLF)`
  WalletWasabi/Tor/Http/Extensions/HttpRequestMessageExtensions.cs
  WalletWasabi/Tor/Http/Models/HeaderSection.cs
Labels: size/S

#9722 Handle wallets separately when are in send workflow
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Labels: size/S

#9742 [VDG] Taproot UI support] #4 - Remove Remove zprv and zpub from Wallet Info
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletInfoViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletInfoView.axaml
Labels: size/S

#9716 GitHub Workflows security hardening
  .github/workflows/auto-add-to-projcet.yml
Labels: size/XS

#9772 [Trivial] Fix DeterministicBuildGuide's formatting
  WalletWasabi.Documentation/Guides/DeterministicBuildGuide.md
Labels: size/XS

#9743 [VDG] [Taproot UI support] #5 - Remove Custom Derivation Path from Wallet Recovery flow
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/AdvancedRecoveryOptionsViewModel.cs
  WalletWasabi.Fluent/Views/Dialogs/AdvancedRecoveryOptionsView.axaml
Labels: size/M

#9718 [Trivial] Update supported OS
  WalletWasabi.Documentation/WasabiCompatibility.md
Labels: size/XS

#9775 [VDG] Fix copy content of fees
  WalletWasabi.Fluent/Extensions/TransactionSummaryExtensions.cs
  WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/BroadcastTransactionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/CoinJoinDetailsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/CoinJoinsDetailsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionSummaryViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/Details/CoinJoinDetailsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/Details/CoinJoinsDetailsView.axaml
Labels: size/M

#9776 [VDG] reset empty local BTC core path when enabled
  WalletWasabi.Fluent/ViewModels/Settings/BitcoinTabSettingsViewModel.cs
Labels: size/XS

#9784 Remove unused `OwnershipProof` from `IKeyChain`
  WalletWasabi.Tests/UnitTests/TestWallet.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/KeyChainTests.cs
  WalletWasabi/WabiSabi/Client/AliceClient.cs
  WalletWasabi/WabiSabi/Client/ArenaClient.cs
  WalletWasabi/WabiSabi/Client/BaseKeyChain.cs
  WalletWasabi/WabiSabi/Client/IKeyChain.cs
Labels: size/M

#9787 Store the MasterKey in KeyManager
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/KeyChain.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/L

#9810 [VDG] add missing permit in auto start state
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
Labels: size/XS

#9821 Increase version number + update website links
  WalletWasabi.Backend/wwwroot/index.html
  WalletWasabi/Helpers/Constants.cs
Labels: size/S

#9808 [website] Mobile fixes
  WalletWasabi.Backend/wwwroot/about.html
  WalletWasabi.Backend/wwwroot/css/style.css
  WalletWasabi.Backend/wwwroot/faq.html
  WalletWasabi.Backend/wwwroot/index.html
Labels: size/M

#9828 [trivial] `ByteHelpers`: Fix namespace
  WalletWasabi.Tests/UnitTests/BitcoinCore/BitcoindBinaryHashesTests.cs
  WalletWasabi.Tests/UnitTests/Blockchain/Keys/WpkhOutputDescriptorHelperTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/GroupElements/GeneralTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/GroupElements/GeneratorTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/StrobeTests.cs
  WalletWasabi.Tests/UnitTests/Hwi/HwiBinaryHashesTests.cs
  WalletWasabi.Tests/UnitTests/Tor/Control/TorControlFactoryTests.cs
  WalletWasabi.Tests/UnitTests/Tor/TorBinaryHashesTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/JsonConverters/CompactSignatureJsonConverterTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/SerializationTests.cs
  WalletWasabi/Crypto/HashHelpers.cs
  WalletWasabi/Helpers/ByteHelpers.cs
  WalletWasabi/JsonConverters/HDFingerprintJsonConverter.cs
  WalletWasabi/JsonConverters/UnblindedSignatureJsonConverter.cs
  WalletWasabi/Tor/Control/TorControlClientFactory.cs
  WalletWasabi/Tor/Http/Helpers/HttpMessageHelper.cs
  WalletWasabi/Tor/Socks5/Models/Bases/ByteArraySerializableBase.cs
  WalletWasabi/Tor/Socks5/Models/Bases/OctetSerializableBase.cs
  WalletWasabi/Tor/TorProcessManager.cs
  WalletWasabi/WabiSabi/Crypto/Serialization/GroupElementJsonConverter.cs
  WalletWasabi/WabiSabi/Crypto/Serialization/ScalarJsonConverter.cs
  WalletWasabi/WabiSabi/Models/Serialization/OwnershipProofJsonConverter.cs
  WalletWasabi/WabiSabi/Models/Serialization/WitScriptJsonConverter.cs
Labels: size/S

#9829 `Guard.NotNull`: Make sure analyzers will know that T was not `null`
  WalletWasabi/Helpers/Guard.cs
Labels: size/XS

#9832 Minor log improvement in Warden
  WalletWasabi/WabiSabi/Backend/DoSPrevention/Prison.cs
  WalletWasabi/WabiSabi/Backend/DoSPrevention/Warden.cs
Labels: size/S

#9831 [Trivial] WasabiSetupRegtest.md: Update CcjRoundsConfig by WabiSabiConfig
  WalletWasabi.Documentation/WasabiSetupRegtest.md
Labels: size/XS

#9825 Add Github vulnerability reporting
  SECURITY.md
Labels: size/XS

#9842 [Trivial] Fix some namespaces
  WalletWasabi.Fluent/Controls/DualCurrencyEntryBox.axaml.cs
  WalletWasabi.Fluent/CrashReport/ViewModels/CrashReportWindowViewModel.cs
  WalletWasabi.Fluent/Helpers/WalletHelpers.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/AddressEntryDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/HelpAndSupport/AboutViewModel.cs
  WalletWasabi.Fluent/ViewModels/HelpAndSupport/BugReportLinkViewModel.cs
  WalletWasabi.Fluent/ViewModels/HelpAndSupport/DocsLinkViewModel.cs
  WalletWasabi.Fluent/ViewModels/HelpAndSupport/LinkViewModel.cs
  WalletWasabi.Fluent/ViewModels/HelpAndSupport/UserSupportViewModel.cs
  WalletWasabi.Fluent/ViewModels/OpenDirectory/OpenDataFolderViewModel.cs
  WalletWasabi.Fluent/ViewModels/OpenDirectory/OpenWalletsFolderViewModel.cs
  WalletWasabi.Fluent/ViewModels/StatusIcon/StatusIconViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Tests/UnitTests/Filters/IndexStoreTests.cs
  WalletWasabi.Tests/UnitTests/IoTests.cs
  WalletWasabi.Tests/UnitTests/LegalTests.cs
  WalletWasabi.Tests/UnitTests/ListExtensionTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
  WalletWasabi.Tests/UnitTests/Userfacing/BitcoinInputTests.cs
  WalletWasabi.Tests/UnitTests/Userfacing/ParserTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/ConfigTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/CoordinatorTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/UtxoPrisonWardenTests.cs
  WalletWasabi.Tests/UnitTests/WalletDirTests.cs
  WalletWasabi/Blockchain/BlockFilters/IndexBuilderService.cs
  WalletWasabi/Blockchain/Blocks/BlockNotifier.cs
  WalletWasabi/Crypto/Randomness/MockRandom.cs
  WalletWasabi/Extensions/ListExtensions.cs
  WalletWasabi/Extensions/ReflectionExtensions.cs
  WalletWasabi/Extensions/StringExtensions.cs
  WalletWasabi/Extensions/SystemNetExtensions.cs
  WalletWasabi/Extensions/TextReaderExtensions.cs
  WalletWasabi/Extensions/TimeSpanExtensions.cs
  WalletWasabi/Helpers/ByteArrayBuilder.cs
  WalletWasabi/Helpers/EnvironmentHelpers.cs
  WalletWasabi/Helpers/IoHelpers.cs
  WalletWasabi/Hwi/Parsers/HwiParser.cs
  WalletWasabi/Rpc/JsonRpcRequestHandler.cs
  WalletWasabi/Stores/IndexStore.cs
  WalletWasabi/Tor/Http/Models/HeaderField.cs
  WalletWasabi/Tor/Http/Models/HeaderSection.cs
  WalletWasabi/Tor/TorSettings.cs
  WalletWasabi/Userfacing/BitcoinInput.cs
  WalletWasabi/Userfacing/EndPointParser.cs
  WalletWasabi/Userfacing/PasswordHelper.cs
  WalletWasabi/WabiSabi/Backend/Banning/Whitelist.cs
  WalletWasabi/WabiSabi/Backend/DoSPrevention/Warden.cs
  WalletWasabi/WabiSabi/Backend/Rounds/CoinJoinStorage/CoinJoinIdStore.cs
  WalletWasabi/WabiSabi/Backend/Rounds/CoinJoinStorage/CoinJoinTransactionArchiver.cs
  WalletWasabi/WabiSabi/CoordinatorParameters.cs
  WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
  WalletWasabi/Wallets/FileSystemBlockRepository.cs
Labels: size/M

#9692 [VDG] Fix exception of Ctrl+C
  WalletWasabi.Fluent/ViewModels/ApplicationViewModel.cs
Labels: size/S
