Repository WalletWasabi/WalletWasabi, pull requests merged in 2022-07, with the labels that each got.

#8178 Preparation for anonymity calculation improvement
  WalletWasabi.Tests/Helpers/BitcoinFactory.cs
  WalletWasabi.Tests/UnitTests/BlockchainAnalysis/CoinJoinAnonscoreTests.cs
  WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs
  WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
  WalletWasabi/Blockchain/Transactions/SmartTransaction.cs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
Labels: size/L

#8526 [VDG] Bitcoin Network Badge
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/Views/Shell/NetworkBadgeView.axaml
  WalletWasabi.Fluent/Views/Shell/NetworkBadgeView.axaml.cs
  WalletWasabi.Fluent/Views/Shell/TitleBarView.axaml
Labels: size/M

#8593 Clarify a sentence in website text.
  WalletWasabi.Backend/wwwroot/index.html
  WalletWasabi.Backend/wwwroot/onion-index.html
Labels: size/XS

#8591 Remove leftover
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/XS

#8574 [VDG] limit btc value decimals
  WalletWasabi.Fluent/Views/Settings/BitcoinTabSettingsView.axaml
  WalletWasabi.Fluent/Views/Wallets/WalletSettingsView.axaml
Labels: size/XS

#8530 Remove dead code
  WalletWasabi/Services/Terminate/TerminateService.cs
Labels: size/XS

#8601 Tests: AliceTimeoutTests - minor improvements
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/AliceTimeoutTests.cs
Labels: size/S

#8600 Filter out WW2.0.0 Clients in the First Round
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepConnectionConfirmationTests.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
Labels: size/S

#8592 Measure arena period as well
  WalletWasabi.Backend/Controllers/WabiSabiController.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Statistics/RequestTimeStatista.cs
Labels: size/M

#8611 Only logtrace OperationCanceledException
  WalletWasabi/WabiSabi/Client/WabiSabiHttpApiClient.cs
Labels: size/S

#8612 Elevate some log messages from Debug to Info
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/DependencyGraphTaskScheduler.cs
Labels: size/S

#8605 Abort registrations on ended rounds
  WalletWasabi/WabiSabi/Client/AliceClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/S

#8614 Improve cancellation logic and logs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/AliceTimeoutTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi/WabiSabi/Client/AliceClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/WabiSabiHttpApiClient.cs
Labels: size/XL

#8599 Update NewtonSoft
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/packages.lock.json
  WalletWasabi.Packager/packages.lock.json
  WalletWasabi/WalletWasabi.csproj
  WalletWasabi/packages.lock.json
Labels: size/M

#8606 [VDG] Settings dialog
  WalletWasabi.Fluent/Styles/SettingsLayout.axaml
  WalletWasabi.Fluent/ViewModels/Settings/SettingsPageViewModel.cs
  WalletWasabi.Fluent/Views/Settings/SettingsPageView.axaml
Labels: size/M

#8577 [VDG] Add implicit zero for decimal numbers
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
Labels: size/M

#8557 [VDG] Fix resource icons
  WalletWasabi.Fluent.Desktop/Assets/WasabiLogo.ico
  WalletWasabi.Fluent.Desktop/Assets/WasabiLogo16.png
  WalletWasabi.Fluent.Desktop/Assets/WasabiLogo24.png
  WalletWasabi.Fluent.Desktop/Assets/WasabiLogo256.png
  WalletWasabi.Fluent.Desktop/Assets/WasabiLogo32.png
  WalletWasabi.Fluent.Desktop/Assets/WasabiLogo48.png
Labels: size/XS

#8608 [VDG] LabelsList scroll fix
  WalletWasabi.Fluent/Behaviors/HorizontalScrollViewerBehavior.cs
  WalletWasabi.Fluent/Controls/LabelsListBox.axaml
Labels: size/S

#8595 Bias random coin selection towards larger amounts
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/S

#8621 Avoid always punishing WW2 denom outputs
  WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs
Labels: size/M

#8620 Fix of CombinationsWithoutRepetition()
  WalletWasabi.Tests/AssertAsync.cs
  WalletWasabi.Tests/UnitTests/LinqExtensionsTests.cs
  WalletWasabi/Extensions/LinqExtensions.cs
Labels: size/M

#8623 Bump version to v2.0.1.1
  WalletWasabi.Backend/wwwroot/index.html
  WalletWasabi/Helpers/Constants.cs
Labels: size/S

#8627 [VDG] Fix possibly null reference in QrCode
  WalletWasabi.Fluent/Controls/QrCode.cs
  WalletWasabi.Fluent/Helpers/FileDialogHelper.cs
  WalletWasabi.Fluent/Helpers/TransactionHelpers.cs
Labels: size/M

#8553 `TorHttpPool`: Catch even `TorConnectCommandFailedException` without `TtlExpired` flag.
  WalletWasabi.Tests/UnitTests/Tor/Socks5/Pool/TorHttpPoolTests.cs
  WalletWasabi/Tor/Socks5/Pool/TorHttpPool.cs
Labels: size/S

#8629 `TorTcpConnectionFactory`: Log only on trace level
  WalletWasabi/Tor/Socks5/TorTcpConnectionFactory.cs
Labels: size/XS

#8624 Remove unnecessary logging to console
  WalletWasabi.Tests/UnitTests/Crypto/Bip322SignatureTest.cs
Labels: size/XS

#8639 Remove WW1 *client* code.
  WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/RegressionTests/DosTests.cs
  WalletWasabi/CoinJoin/Client/Clients/AliceClient4.cs
  WalletWasabi/CoinJoin/Client/Clients/AliceClientBase.cs
  WalletWasabi/CoinJoin/Client/Clients/BobClient.cs
  WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
  WalletWasabi/CoinJoin/Client/Clients/Queuing/DequeueReason.cs
  WalletWasabi/CoinJoin/Client/Clients/Queuing/DequeueResult.cs
  WalletWasabi/CoinJoin/Client/Clients/SatoshiClient.cs
  WalletWasabi/CoinJoin/Client/Rounds/ClientRound.cs
  WalletWasabi/CoinJoin/Client/Rounds/ClientRoundRegistration.cs
  WalletWasabi/CoinJoin/Client/Rounds/ClientState.cs
  WalletWasabi/Wallets/Wallet.cs
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/XXL

#8633 Fix rounding error in anonscore calculation
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinViewModel.cs
  WalletWasabi.Tests/UnitTests/BlockchainAnalysis/CoinJoinAnonscoreTests.cs
  WalletWasabi.Tests/UnitTests/BlockchainAnalysis/PubKeyReuseAnonScoreTests.cs
  WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs
  WalletWasabi/Blockchain/Keys/HdPubKey.cs
Labels: size/M

#7478 [VDG] Modify `RxApp.DefaultExceptionHandler`
  WalletWasabi.Fluent.Desktop/Program.cs
Labels: size/S

#8522 Add RedCoinIsolation
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/CoinJoinProfileViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/CoinJoinProfilesViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/ManualCoinJoinProfileViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/PrivateCoinJoinProfileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/ManualCoinJoinProfileDialogViewModel.cs
  WalletWasabi.Fluent/Views/Dialogs/ManualCoinJoinProfileDialogView.axaml
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/CoinJoinCoinSelectionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/Participant.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinTrackerFactory.cs
Labels: feature/enhancement, size/M

#8643 Update CoinJoinProfile equalities + remove redundant code
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/CoinJoinProfileViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/PrivateCoinJoinProfileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/ManualCoinJoinProfileDialogViewModel.cs
Labels: size/XS

#8640 `WasabiSynchronizer`: Remove request blocking
  WalletWasabi/Services/WasabiSynchronizer.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/M

#8651 [VDG] WalletViewModelBase - Cleanup
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModelBase.cs
Labels: size/S

#8660 Use `NoAuthenticationRequired` for DefaultCircuit
  WalletWasabi.Tests/UnitTests/Tor/Socks5/TorTcpConnectionFactoryTests.cs
  WalletWasabi/Tor/Socks5/TorTcpConnectionFactory.cs
Labels: size/M

#8658 [Trivial] Fix Codefactor issues
  WalletWasabi.Backend/Startup.cs
  WalletWasabi.Tests/UnitTests/Crypto/CredentialIssuerKeyTests.cs
  WalletWasabi.Tests/UnitTests/StateMachineTests.cs
  WalletWasabi/Io/DigestableSafeIoManager.cs
  WalletWasabi/WabiSabi/Client/Decomposer.cs
  WalletWasabi/WabiSabi/Client/RoundStateAwaiters/RoundStateUpdater.cs
  WalletWasabi/WabiSabi/Client/WabiSabiHttpApiClient.cs
  WalletWasabi/WabiSabi/Models/Serialization/MultipartyTransactionStateJsonConverter.cs
Labels: size/M

#8663 [VDG] Update to Avalonia 0.10.16
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
Labels: size/L

#8671 Revert "Return ownership proofs"
  WalletWasabi.Fluent/Config.cs
  WalletWasabi.Fluent/Global.cs
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputSuccessTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/SignTransactionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/Rounds/MultipartyTransactionStateTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Crypto/OwnershipProofTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiApiApplicationFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/InputRegistrationRequestTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/MultipartyTransactionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/SerializationTests.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
  WalletWasabi/WabiSabi/Backend/Rounds/RoundParameters.cs
  WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
  WalletWasabi/WabiSabi/Client/AliceClient.cs
  WalletWasabi/WabiSabi/Client/ArenaClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WabiSabi/Client/CoinJoinTrackerFactory.cs
  WalletWasabi/WabiSabi/Crypto/RoundHasher.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/ConstructionState.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/MultipartyTransactionState.cs
  WalletWasabi/WabiSabi/ProtocolConstants.cs
Labels: size/L

#8673 Don't swallow exception
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/S

#8675 Make AliceClient handle Protocol exceptions
  WalletWasabi/WabiSabi/Client/AliceClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/M

#8666 [VDG] NavBarViewModel - cleanup
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
Labels: size/M

#8641 `WasabiSynchronizer`: Improve exception handling
  WalletWasabi/Services/WasabiSynchronizer.cs
  WalletWasabi/Tor/Socks5/Exceptions/TorConnectCommandFailedException.cs
  WalletWasabi/Tor/Socks5/Models/ReplyType.cs
Labels: size/M

#8683 [VDG] Fix LabelsPanel not displaying all items
  WalletWasabi.Fluent/Controls/LabelsPanel.cs
Labels: size/XS

#8686 [VDG] wallet stats lowercase writing
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletStatsView.axaml
Labels: size/XS

#8667 [VDG] NavBarItemViewModel - cleanup
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
Labels: size/XS

#8659 Weakly consider AS for coin selection
  WalletWasabi/Extensions/LinqExtensions.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/M

#8669 `TorMonitor`: Add restarting capability
  WalletWasabi/Tor/TorMonitor.cs
Labels: size/L

#8594 Allow only single run of `PrivacySuggestionsFlyoutViewModel.BuildPrivacySuggestionsAsync`
  WalletWasabi.Fluent.Desktop/Program.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/ChangeAvoidanceSuggestionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacySuggestionsFlyoutViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
Labels: size/M

#8702 Update Website main image
  WalletWasabi.Backend/wwwroot/img/screenshots/webpage_ui_compilation-02.png
Labels: size/XS

#8700 [draft] macOS: Tor control failed to initialize
  WalletWasabi/Tor/TorProcessManager.cs
  WalletWasabi/Tor/TorSettings.cs
Labels: size/S

#8706 [VDG] Remove null style setter
  WalletWasabi.Fluent/Views/Shell/DialogsView.axaml
Labels: size/XS

#8707 Bump version to v2.0.1.2 website
  WalletWasabi.Backend/wwwroot/index.html
Labels: size/S

#8184 [trivial] Fix namespace for `NBitcoinExtension` class and `Extensions` class
  WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
  WalletWasabi.Fluent/Helpers/TransactionHelpers.cs
  WalletWasabi.Fluent/Rpc/WasabiJsonRpcService.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/Authorization/HardwareWalletAuthDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/LoadTransactionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletInfoViewModel.cs
  WalletWasabi.Tests/UnitTests/Blockchain/TransactionBuilding/ChangelessTransactionCoinSelectorTests.cs
  WalletWasabi.Tests/UnitTests/NBitcoinTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/AmountDecomposerTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/Participant.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/MultipartyTransactionTests.cs
  WalletWasabi/Blockchain/TransactionBuilding/ChangelessTransactionCoinSelector.cs
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
  WalletWasabi/CoinJoin/Coordinator/Coordinator.cs
  WalletWasabi/Crypto/Bip322Signature.cs
  WalletWasabi/Crypto/Extensions.cs
  WalletWasabi/Crypto/OwnershipProof.cs
  WalletWasabi/Crypto/ZeroKnowledge/ProofSystem.cs
  WalletWasabi/Extensions/NBitcoinExtensions.cs
  WalletWasabi/Hwi/HwiClient.cs
  WalletWasabi/JsonConverters/OutPointJsonConverter.cs
  WalletWasabi/WabiSabi/Backend/Models/Alice.cs
  WalletWasabi/WabiSabi/Backend/Models/Bob.cs
  WalletWasabi/WabiSabi/Backend/Statistics/RequestTimeStatista.cs
  WalletWasabi/WabiSabi/Client/AliceClient.cs
  WalletWasabi/WabiSabi/Client/CredentialDependencies/DependencyGraph.cs
  WalletWasabi/WabiSabi/Client/DependencyGraphTaskScheduler.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/ConstructionState.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/MultipartyTransactionState.cs
  WalletWasabi/WebClients/PayJoin/PayjoinClient.cs
Labels: size/M

#8721 Change WW2 monitor timeout from 1h to 3h
  WalletWasabi.Backend/Controllers/BlockchainController.cs
Labels: size/XS

#8726 [Trivial] Improve message to detect HW
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/ConnectHardwareWalletViewModel.cs
Labels: size/XS

#8728 [VDG] Add HasChildren method to history item
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinsHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/HistoryItemViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
Labels: size/S

#8749 [VDG] tooltip coinjoin time preference
  WalletWasabi.Fluent/Views/Dialogs/ManualCoinJoinProfileDialogView.axaml
Labels: size/XS

#8679 [Trivial] Move classes into there own files
  WalletWasabi.Tests/UnitTests/UserInterfaceTest/LabelTestExtensions.cs
  WalletWasabi.Tests/UnitTests/UserInterfaceTest/PocketSelectionTests.cs
  WalletWasabi/Extensions/LinqExtensions.cs
  WalletWasabi/WabiSabi/Client/Decomposer.cs
  WalletWasabi/WabiSabi/Client/ReverseComparer.cs
Labels: size/L

#8756 Fix logs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/XS

#8638 update README Download image
  README.md
Labels: size/XS

#8752 [VDG] Round to significant figures in Change Avoidance Suggestions
  WalletWasabi.Fluent/Extensions/TimeSpanMixin.cs
  WalletWasabi.Fluent/Helpers/MathUtils.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/ChangeAvoidanceSuggestionViewModel.cs
  WalletWasabi.Tests/UnitTests/Helpers/MathUtilsTests.cs
  WalletWasabi/Helpers/MathUtils.cs
Labels: size/M

#8367 Fix infinite loop in CoinSelector
  WalletWasabi.Tests/Helpers/BitcoinFactory.cs
  WalletWasabi.Tests/Helpers/ServiceFactory.cs
  WalletWasabi.Tests/UnitTests/Transactions/DemoCoinSets.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
  WalletWasabi/Blockchain/TransactionBuilding/SmartCoinSelector.cs
  WalletWasabi/Exceptions/TransactionSizeException.cs
Labels: size/XXL

#8704 [VDG] Fee Slider - full labels
  WalletWasabi.Fluent/Helpers/ConfirmationTimeLabel.cs
  WalletWasabi.Fluent/Helpers/TimeSpanFormatter.cs
  WalletWasabi.Fluent/Views/Wallets/Send/SendFeeView.axaml
Labels: size/S

#8650 [VDG] Remember window size
  WalletWasabi.Fluent/Behaviors/WindowSizeBehavior.cs
  WalletWasabi.Fluent/UiConfig.cs
  WalletWasabi.Fluent/Views/MainWindow.axaml
Labels: size/M

#8563 [VDG] Recipient on txn preview
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionSummaryViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionSummary.axaml
Labels: size/S

#8711 `TorMonitor`: Report that "we are no longer confident that we can build Tor circuits"
  WalletWasabi/Tor/Control/Messages/Events/StatusEvents/StatusEvent.cs
  WalletWasabi/Tor/TorMonitor.cs
Labels: size/S

#8760 [VDG] Add ability to sort coins in Coin List by indicators
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
Labels: size/S

#8762 Add original round id to log message when creating blame round
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/XS

#8692 [VDG] WalletManagerViewModel - simplification
  WalletWasabi.Fluent/ViewModels/AddWallet/AddedWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
Labels: size/M

#8759 [VDG] Fix for focus loss after window becomes inactive
  WalletWasabi.Fluent/Behaviors/SearchBarBehavior.cs
Labels: size/S

#8236 [VDG] MainViewModel - cleanup & simplification
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/BroadcastTransactionViewModel.cs
  WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/BroadcasterViewModel.cs
  WalletWasabi.Fluent/Views/Shell/DialogsView.axaml
  WalletWasabi.Fluent/Views/Shell/MainView.axaml
  WalletWasabi.Fluent/Views/Shell/ShellView.axaml
  WalletWasabi.Fluent/Views/TransactionBroadcasting/BroadcastTransactionView.axaml
Labels: size/L

#8755 Remove unused methods from LinqExtensions.cs
  WalletWasabi/Extensions/LinqExtensions.cs
Labels: size/M

#8782 [VDG] hww not connected text wording
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressViewModel.cs
Labels: size/XS

#8776 [VDG] Use ItemTemplate instead of DataTemplates
  WalletWasabi.Fluent/Views/CoinJoinProfiles/CoinJoinProfilesView.axaml
Labels: size/XS

#8708 Return ownership proofs
  WalletWasabi.Fluent/Config.cs
  WalletWasabi.Fluent/Global.cs
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputSuccessTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/SignTransactionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/Rounds/MultipartyTransactionStateTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Crypto/OwnershipProofTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiApiApplicationFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/InputRegistrationRequestTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/MultipartyTransactionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/SerializationTests.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
  WalletWasabi/WabiSabi/Backend/Rounds/RoundParameters.cs
  WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
  WalletWasabi/WabiSabi/Client/AliceClient.cs
  WalletWasabi/WabiSabi/Client/ArenaClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WabiSabi/Client/CoinJoinTrackerFactory.cs
  WalletWasabi/WabiSabi/Crypto/RoundHasher.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/ConstructionState.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/MultipartyTransactionState.cs
  WalletWasabi/WabiSabi/ProtocolConstants.cs
Labels: size/L

#8768 Target low UTXO count
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/CoinJoinCoinSelectionTests.cs
  WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs
  WalletWasabi/Extensions/LinqExtensions.cs
  WalletWasabi/Helpers/Constants.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinTrackerFactory.cs
Labels: size/L

#8795 [VDG] Fee Chart - Fix labels plural form
  WalletWasabi.Fluent/Helpers/ConfirmationTimeLabel.cs
Labels: size/XS

#8804 Bump version to v2.0.1.3
  WalletWasabi.Backend/wwwroot/index.html
  WalletWasabi/Helpers/Constants.cs
Labels: size/S

#8743 Update compatibiltiy information
  WalletWasabi.Documentation/WasabiCompatibility.md
Labels: size/S

#8819 `TorSettings`: Use `KeepAliveIsolateSOCKSAuth` flag
  WalletWasabi.Tests/UnitTests/Tor/TorSettingsTests.cs
  WalletWasabi/Tor/TorSettings.cs
Labels: size/XS
