Repository WalletWasabi/WalletWasabi, pull requests merged in 2022-01, with the labels that each got.

#6949 Throw exception if value is null (JsonConverters)
  WalletWasabi/JsonConverters/Bitcoin/FeeRateJsonConverter.cs
  WalletWasabi/JsonConverters/Bitcoin/MoneyBtcJsonConverter.cs
  WalletWasabi/JsonConverters/Bitcoin/MoneySatoshiJsonConverter.cs
  WalletWasabi/JsonConverters/Bitcoin/ScriptJsonConverter.cs
  WalletWasabi/JsonConverters/BitcoinAddressJsonConverter.cs
  WalletWasabi/JsonConverters/BitcoinEncryptedSecretNoECJsonConverter.cs
  WalletWasabi/JsonConverters/EndPointJsonConverter.cs
Labels: size/M

#6916 `RpcClientBase`: Fix nullability warnings
  WalletWasabi/BitcoinCore/Rpc/RpcClientBase.cs
Labels: size/S

#6868 Remove unused method
  WalletWasabi/Helpers/NBitcoinHelpers.cs
Labels: size/XS

#6955 [Trivial] Edit compatible full node version text
  WalletWasabi.Fluent/Views/Dialogs/AboutAdvancedInfoView.axaml
Labels: size/XS

#6976 [VDG] [Fluent] Update Avalonia and DataBox packages
  NuGet.Config
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
Labels: size/L

#6967 Improve StringCipher code and correctness
  WalletWasabi.Tests/UnitTests/Crypto/StringCipherTests.cs
  WalletWasabi/Crypto/StringCipher.cs
Labels: size/L

#6898 [Experimental] Compact password dialog
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/SelectWalletCreationOptionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/CreatePasswordDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/PasswordFinderIntroduceViewModel.cs
  WalletWasabi.Fluent/Views/Dialogs/CreatePasswordDialogView.axaml
  WalletWasabi.Fluent/Views/MainView.axaml
  WalletWasabi/Userfacing/PasswordHelper.cs
Labels: size/L

#6873 Move hide address button to the Left side
  WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveAddressesView.axaml
Labels: size/S

#6969 Switch DateTimeOffsetUnixSecondsConverter from 'JsonConverter' to 'JsonConverter<T>'
  WalletWasabi/JsonConverters/DateTimeOffsetUnixSecondsConverter.cs
Labels: size/S

#6970 Move Rpc plumbing to WalletWasabi lib project
  WalletWasabi.Fluent/Global.cs
  WalletWasabi.Fluent/Models/JsonRpcServerConfiguration.cs
  WalletWasabi.Fluent/Rpc/WasabiJsonRpcService.cs
  WalletWasabi.Tests/RpcTests.cs
  WalletWasabi.Tests/TestableRpcService.cs
  WalletWasabi/Rpc/IJsonRpcService.cs
  WalletWasabi/Rpc/JsonRpcErrorCodes.cs
  WalletWasabi/Rpc/JsonRpcMethodAttribute.cs
  WalletWasabi/Rpc/JsonRpcMethodMetadata.cs
  WalletWasabi/Rpc/JsonRpcRequest.cs
  WalletWasabi/Rpc/JsonRpcRequestHandler.cs
  WalletWasabi/Rpc/JsonRpcResponse.cs
  WalletWasabi/Rpc/JsonRpcServer.cs
  WalletWasabi/Rpc/JsonRpcServerConfiguration.cs
  WalletWasabi/Rpc/JsonRpcService.cs
  WalletWasabi/Rpc/PaymentInfo.cs
Labels: size/M

#6979 Fix some warnings in tests
  WalletWasabi.Tests/AcceptanceTests/HwiKatas.cs
  WalletWasabi.Tests/Helpers/HttpClientWrapper.cs
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/RegressionTests/Common.cs
  WalletWasabi.Tests/RegressionTests/DosTests.cs
  WalletWasabi.Tests/RpcTests.cs
  WalletWasabi.Tests/TestableRpcService.cs
  WalletWasabi.Tests/UnitTests/AllFeeEstimateTests.cs
  WalletWasabi.Tests/UnitTests/Clients/WasabiClientTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/OwnershipProofTest.cs
  WalletWasabi.Tests/UnitTests/Crypto/StrobeTests.cs
  WalletWasabi.Tests/UnitTests/InputsResponseTests.cs
  WalletWasabi.Tests/UnitTests/ListExtensionTests.cs
  WalletWasabi.Tests/UnitTests/MockRpcClient.cs
  WalletWasabi.Tests/UnitTests/Transactions/AllTransactionStoreTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/SmartTransactionTests.cs
Labels: size/L

#6981 Implement Amount Decomposition
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/AmountDecomposerTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/StandardDenominationsTests.cs
  WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CredentialDependencies/DependencyGraph.cs
  WalletWasabi/WabiSabi/Models/Decomposition/StandardDenomination.cs
Labels: feature/enhancement, size/L

#6984 [Trivial] Cleanup
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/UnitTests/MockRpcClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/S

#6902 Increase the log size in case of TraceLevel
  WalletWasabi/Logging/Logger.cs
Labels: size/XS

#6983 Fix more IDisposables and nulls
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Fluent/Global.cs
  WalletWasabi.Packager/MacSignTools.cs
  WalletWasabi.Tests/UnitTests/BitcoinCore/P2pBasedTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/RandomTests.cs
  WalletWasabi.Tests/UnitTests/MempoolMirrorTests/MirrorMempoolTests.cs
  WalletWasabi/Crypto/Randomness/RandomString.cs
  WalletWasabi/Crypto/Randomness/SecureRandom.cs
  WalletWasabi/Crypto/Randomness/WasabiRandom.cs
  WalletWasabi/JsonConverters/Bitcoin/FeeRateJsonConverter.cs
  WalletWasabi/JsonConverters/Bitcoin/MoneyBtcJsonConverter.cs
  WalletWasabi/JsonConverters/Bitcoin/MoneySatoshiJsonConverter.cs
  WalletWasabi/JsonConverters/Bitcoin/ScriptJsonConverter.cs
  WalletWasabi/JsonConverters/BitcoinAddressJsonConverter.cs
  WalletWasabi/JsonConverters/BitcoinEncryptedSecretNoECJsonConverter.cs
  WalletWasabi/JsonConverters/HeightJsonConverter.cs
  WalletWasabi/Rpc/JsonRpcRequestHandler.cs
  WalletWasabi/Services/HostedServices.cs
  WalletWasabi/Tor/Http/Extensions/HttpContentExtensions.cs
  WalletWasabi/Tor/Http/Extensions/HttpStatusCodeExtensions.cs
  WalletWasabi/Tor/Http/Models/HeaderSection.cs
  WalletWasabi/Tor/Http/Models/HttpRequestContentHeaders.cs
  WalletWasabi/Tor/Http/Models/HttpResponseContentHeaders.cs
Labels: size/L

#6993 Implement Coinjoin Coin Selection
  WalletWasabi.Fluent.Desktop/Program.cs
  WalletWasabi.Fluent/Config.cs
  WalletWasabi.Fluent/Helpers/CoinHelpers.cs
  WalletWasabi.Fluent/ViewModels/Settings/PrivacySettingsTabViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletBalanceTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionInfo.cs
  WalletWasabi.Fluent/Views/Settings/PrivacySettingsTabView.axaml
  WalletWasabi.Tests/IntegrationTests/P2pTests.cs
  WalletWasabi.Tests/RegressionTests/Common.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/AmountDecomposerTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/Participant.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi/Helpers/Constants.cs
  WalletWasabi/Models/ServiceConfiguration.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: feature/enhancement, size/L

#6997 Delay sanity check
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: debug, good first issue, size/S

#7001 Dispose SingleInstanceChecker in synchronously
  WalletWasabi.Fluent.Desktop/Program.cs
  WalletWasabi/Services/SingleInstanceChecker.cs
Labels: size/M

#7004 Switch FilterModelJsonConverter from 'JsonConverter' to 'JsonConverter<T>'
  WalletWasabi/JsonConverters/FilterModelJsonConverter.cs
Labels: size/S

#7006 Switch HDFingerprintJsonConverter from 'JsonConverter' to 'JsonConverter<T>'
  WalletWasabi/JsonConverters/HDFingerprintJsonConverter.cs
Labels: size/S

#7005 Switch GuidJsonConverter from 'JsonConverter' to 'JsonConverter<T>'
  WalletWasabi/JsonConverters/GuidJsonConverter.cs
Labels: size/M

#7010 Fix ReadJson method in HDFingerprintJsonConverter
  WalletWasabi/JsonConverters/HDFingerprintJsonConverter.cs
Labels: size/XS

#7011 fix missing txn chars in coinjoin details dialog
  WalletWasabi.Fluent/Views/Wallets/Home/History/CoinJoinDetailsView.axaml
Labels: UI, size/XS

#7014 Fix incorrect check variable
  WalletWasabi/Crypto/SchnorrBlindingSignature.cs
Labels: size/XS

#7002 Switch ExtPubKeyJsonConverter from 'JsonConverter' to 'JsonConverter<T>'
  WalletWasabi/JsonConverters/ExtPubKeyJsonConverter.cs
Labels: size/S

#7003 Make Tor circuits disposable so that their lifetime is explicit (2nd attempt)
  WalletWasabi.Fluent/Global.cs
  WalletWasabi.Tests/UnitTests/Tor/Socks5/Pool/TorHttpPoolTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/Participant.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs
  WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
  WalletWasabi/Logging/Logger.cs
  WalletWasabi/Tor/Http/TorHttpClient.cs
  WalletWasabi/Tor/Socks5/Exceptions/TorCircuitExpiredException.cs
  WalletWasabi/Tor/Socks5/Exceptions/TorException.cs
  WalletWasabi/Tor/Socks5/Pool/Circuits/DefaultCircuit.cs
  WalletWasabi/Tor/Socks5/Pool/Circuits/ICircuit.cs
  WalletWasabi/Tor/Socks5/Pool/Circuits/OneOffCircuit.cs
  WalletWasabi/Tor/Socks5/Pool/Circuits/PersonCircuit.cs
  WalletWasabi/Tor/Socks5/Pool/TorHttpPool.cs
  WalletWasabi/Tor/Socks5/TorTcpConnection.cs
  WalletWasabi/Tor/Socks5/TorTcpConnectionFactory.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WebClients/Wasabi/HttpClientFactory.cs
  WalletWasabi/WebClients/Wasabi/IHttpClientFactory.cs
  WalletWasabi/WebClients/Wasabi/IWasabiHttpClientFactory.cs
Labels: size/L

#7019 Fix a few nullability warnings in `Config` classes
  WalletWasabi.Backend/Config.cs
  WalletWasabi.Fluent/Config.cs
  WalletWasabi/Bases/ConfigBase.cs
Labels: size/M

#6940 add wallet name in logs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi/Wallets/Wallet.cs
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/S

#7024 Fix warnings: Use expression body for lambda expressions
  WalletWasabi.Backend/Startup.cs
  WalletWasabi.Fluent.Generators/NavigationMetaDataGenerator.cs
  WalletWasabi.Fluent.Generators/StaticViewLocatorGenerator.cs
  WalletWasabi.Fluent/Behaviors/ButtonExecuteCommandOnKeyDownBehavior.cs
  WalletWasabi.Fluent/Behaviors/HistoryItemDetailsBehavior.cs
  WalletWasabi.Fluent/Behaviors/RandomizedWorldPointsBehavior.cs
  WalletWasabi.Fluent/CrashReport/ViewModels/CrashReportWindowViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/ShowQrCameraDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/AddressViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendFeeViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionSummaryViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/Startup.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiApiApplicationFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
Labels: size/L

#7027 Implement code review suggestions
  WalletWasabi.Tests/UnitTests/Crypto/CredentialIssuerKeyTests.cs
  WalletWasabi.Tests/UnitTests/Crypto/RandomTests.cs
  WalletWasabi/Crypto/CredentialIssuerSecretKey.cs
  WalletWasabi/Crypto/Randomness/WasabiRandom.cs
  WalletWasabi/Crypto/ZeroKnowledge/SyntheticSecretNonceProvider.cs
  WalletWasabi/Crypto/ZeroKnowledge/Transcript.cs
  WalletWasabi/WabiSabi/Crypto/WabiSabiClient.cs
Labels: size/L

#6929 [Trivial] Make methods synchronous to fix warnings
  WalletWasabi/Wallets/Wallet.cs
Labels: size/XS

#6819 Display fees in btc instead of sats
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionSummaryViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Send/SendFeeView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionSummary.axaml
Labels: size/XS

#7021 [Trivial] Fix Typos
  WalletWasabi.Fluent/Models/WebcamQrReader.cs
  WalletWasabi.Fluent/Morph/PolyLine.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/DetectedHardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/ShowQrCameraDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/SearchPasswordViewModel.cs
  WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/M

#6968 [Fluent] Remove USD & Percentage options as fee display formats
  WalletWasabi.Fluent/Models/FeeDisplayFormat.cs
Labels: size/XS

#7018 Change the default fallback address
  WalletWasabi/Helpers/Constants.cs
Labels: size/XS

#7032 Fix macOS CI pipeline
  azure-pipelines-osx.yml
Labels: size/XS

#7012 Speed up transaction building by disabling the signing
  WalletWasabi.Fluent/Helpers/TransactionHelpers.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: feature/enhancement, size/M

#7037 Change Login to Open.
  WalletWasabi.Fluent/Views/Login/LoginView.axaml
Labels: size/S

#7040 Change Login to Open
  WalletWasabi.Fluent/ViewModels/Login/LoginViewModel.cs
Labels: size/XS

#7035 Remove EffectiveValue calculation form AmoutDecomposer
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/AmountDecomposerTests.cs
  WalletWasabi/WabiSabi/Client/AliceClient.cs
  WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/M

#7034 Do not sign Change Avoidence Suggestions when created
  WalletWasabi.Fluent/ViewModels/Wallets/Send/ChangeAvoidanceSuggestionViewModel.cs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
Labels: size/S

#7046 Switch HDFingerprintJsonConverter from 'JsonConverter<T>' to 'JsonConverter<T?>'
  WalletWasabi/JsonConverters/HDFingerprintJsonConverter.cs
Labels: size/S

#7049 [Fluent] Add a unique icon for wallet settings menu item.
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
Labels: size/XS

#7031 [Fluent] Persist Fiat to BTC setting on CurrencyEntryBox
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Labels: size/S

#6805 Switch BlockCypherDateTimeOffsetJsonConverter from 'JsonConverter' to 'JsonConverter<T>'
  WalletWasabi/JsonConverters/BlockCypherDateTimeOffsetJsonConverter.cs
Labels: size/S

#7064 Fix ownership proofs
  WalletWasabi.Tests/UnitTests/Crypto/OwnershipProofTest.cs
  WalletWasabi/Crypto/ProofBody.cs
Labels: size/S

#7055 [WabiSabi] Ban alices that are clearly cheating.
  WalletWasabi.Tests/Helpers/ArenaBuilder.cs
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/AliceTimeoutTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepConnectionConfirmationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepInputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/ConfirmConnectionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputSuccessTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputToBlameRoundTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterOutputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RemoveInputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/SignTransactionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
  WalletWasabi/WabiSabi/Backend/Banning/Prison.cs
  WalletWasabi/WabiSabi/Backend/Models/WabiSabiProtocolErrorCode.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
Labels: size/L

#7053 Welcome Screen
  WalletWasabi.Fluent/Views/AddWallet/WelcomePageView.axaml
Labels: size/S

#6953 [WabiSabi] Coordination fees
  WalletWasabi.Tests/Helpers/ArenaBuilder.cs
  WalletWasabi.Tests/Helpers/BitcoinFactory.cs
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/ConfigTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputSuccessTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterOutputTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/RoundCreationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/Rounds/Utils/CoinJoinTransactionArchiverTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/AmountDecomposerTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiApiApplicationFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/MultipartyTransactionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/SerializationTests.cs
  WalletWasabi/Bases/ConfigBase.cs
  WalletWasabi/Crypto/StrobeProtocol/StrobeHasher.cs
  WalletWasabi/Extensions/NBitcoinExtensions.cs
  WalletWasabi/Helpers/Constants.cs
  WalletWasabi/JsonConverters/DefaultValueCoordinatorFeeRateAttribute.cs
  WalletWasabi/WabiSabi/Backend/Models/Alice.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Rounds/CoinJoinStorage/CoinJoinTransactionArchiver.cs
  WalletWasabi/WabiSabi/Backend/Rounds/CoinJoinStorage/InMemoryCoinJoinIdStore.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
  WalletWasabi/WabiSabi/Backend/Rounds/RoundParameters.cs
  WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
  WalletWasabi/WabiSabi/Client/AliceClient.cs
  WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
  WalletWasabi/WabiSabi/Client/ArenaClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CredentialDependencies/DependencyGraph.cs
  WalletWasabi/WabiSabi/CoordinatorParameters.cs
  WalletWasabi/WabiSabi/Crypto/RoundHasher.cs
  WalletWasabi/WabiSabi/Models/CoordinationFeeRate.cs
  WalletWasabi/WabiSabi/Models/InputRegistrationResponse.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/ConstructionState.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/MultipartyTransactionParameters.cs
  WalletWasabi/WabiSabi/Models/RoundState.cs
  WalletWasabi/WabiSabi/Models/Serialization/JsonSerializationOptions.cs
  WalletWasabi/WabiSabi/ProtocolContants.cs
  WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
Labels: size/XL

#7066 Branch and bound coin selector
  WalletWasabi.Tests/UnitTests/Blockchain/TransactionBuilding/BranchAndBoundTests.cs
  WalletWasabi.Tests/UnitTests/Blockchain/TransactionBuilding/ChangelessTransactionCoinSelectorTests.cs
  WalletWasabi/Blockchain/TransactionBuilding/BnB/CheapestSelectionStrategy.cs
  WalletWasabi/Blockchain/TransactionBuilding/BnB/EvaluationResult.cs
  WalletWasabi/Blockchain/TransactionBuilding/BnB/NextAction.cs
  WalletWasabi/Blockchain/TransactionBuilding/BranchAndBound.cs
  WalletWasabi/Blockchain/TransactionBuilding/ChangelessTransactionCoinSelector.cs
  WalletWasabi/Extensions/NBitcoinExtensions.cs
Labels: size/XL

#6937 Fix tx labels
  WalletWasabi.Tests/Helpers/ArenaBuilder.cs
  WalletWasabi/BitcoinP2p/P2pBehavior.cs
  WalletWasabi/Blockchain/Mempool/MempoolService.cs
  WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs
  WalletWasabi/Blockchain/Transactions/TransactionBroadcastEntry.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: priority, size/L

#6960 [WabiSabi] CoinJoinClient interface simplification
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/AliceTimeoutTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/KeyChainTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/Participant.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
  WalletWasabi/WabiSabi/Client/AliceClient.cs
  WalletWasabi/WabiSabi/Client/ArenaClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WabiSabi/Client/IDestinationProvider.cs
  WalletWasabi/WabiSabi/Client/IKeyChain.cs
  WalletWasabi/WabiSabi/Client/InternalDestinationProvider.cs
  WalletWasabi/WabiSabi/Client/KeyChain.cs
Labels: size/L

#7099 [Trivial] Correct variable name for clarification
  WalletWasabi.Tests/UnitTests/Blockchain/TransactionBuilding/ChangelessTransactionCoinSelectorTests.cs
  WalletWasabi/Blockchain/TransactionBuilding/ChangelessTransactionCoinSelector.cs
Labels: size/S

#7093 `WabiSabiHttpApiIntegrationTests`: Fix NSE in `MultiClientsCoinJoinTestAsync`
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiApiApplicationFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
Labels: size/XS

#7095 [trivial] Add missing nullability info
  WalletWasabi.Tests/Helpers/ArenaBuilder.cs
Labels: size/XS

#7101 [VDG] Send address input fixes
  WalletWasabi.Fluent/Behaviors/PasteButtonFlashBehavior.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
Labels: size/S

#7062 [Fluent] Feature/verify seed words
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/ConfirmRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/RecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/VerifyRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletSettingsViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/Create/ConfirmRecoveryWordsView.axaml
  WalletWasabi.Fluent/Views/AddWallet/Create/RecoveryWordsView.axaml
  WalletWasabi.Fluent/Views/AddWallet/RecoverWalletView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/TransactionDetailsView.axaml
  WalletWasabi.Fluent/Views/Wallets/VerifyRecoveryWordsView.axaml
  WalletWasabi.Fluent/Views/Wallets/VerifyRecoveryWordsView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/WalletSettingsView.axaml
Labels: size/L

#7076 `Global`: Fix a few warnings
  WalletWasabi.Fluent/Global.cs
  WalletWasabi.Tests/IntegrationTests/P2pTests.cs
  WalletWasabi.Tests/UnitTests/BitcoinCore/P2pBasedTests.cs
  WalletWasabi/BitcoinCore/CoreNodeParams.cs
  WalletWasabi/Stores/BitcoinStore.cs
Labels: size/M

#7086 [trivial] Convert to file-scoped namespaces.
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/KeyChainTests.cs
  WalletWasabi/WabiSabi/Client/IDestinationProvider.cs
  WalletWasabi/WabiSabi/Client/IKeyChain.cs
  WalletWasabi/WabiSabi/Client/InternalDestinationProvider.cs
  WalletWasabi/WabiSabi/Client/KeyChain.cs
Labels: size/L

#7114 Better logs in AddBlameScript
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/S

#7112 Do not serialize redundant properties in `NBitcoin.Coin`
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/SerializationTests.cs
  WalletWasabi/JsonConverters/Bitcoin/CoinJsonConverter.cs
  WalletWasabi/WabiSabi/Models/Serialization/JsonSerializationOptions.cs
Labels: size/M

#7080 [WabiSabi] Refactor MultiClient test and fix bug
  WalletWasabi.Tests/UnitTests/TestWallet.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/Participant.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/L

#7058 `SmartHeaderChain`: Refactor and clean up.
  WalletWasabi.Fluent/Global.cs
  WalletWasabi.Tests/UnitTests/Blockchain/Blocks/SmarthHeaderChainTests.cs
  WalletWasabi.Tests/UnitTests/HashChainTests.cs
  WalletWasabi/Backend/Models/FilterModel.cs
  WalletWasabi/Blockchain/BlockFilters/FilterProcessor.cs
  WalletWasabi/Blockchain/Blocks/SmartHeaderChain.cs
  WalletWasabi/Stores/IndexStore.cs
Labels: size/XL

#7115 Increase a 10% the `SoloCoinJoinTest` timeout
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
Labels: size/XS

#7087 Fix typos in test files
  WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
  WalletWasabi.Tests/UnitTests/BlockchainAnalysis/CoinJoinAnonscoreTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
Labels: size/S

#7089 Fix typos in WabiSabi and CoinJoin folders
  WalletWasabi/CoinJoin/Client/Clients/AliceClientBase.cs
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/L

#7119 [Fluent] Fix not catching the OperationCancelledException that crashes app in some cases.
  WalletWasabi.Fluent/Behaviors/RandomizedWorldPointsBehavior.cs
Labels: size/XS

#7090 Fix more typos
  WalletWasabi.Backend/wwwroot/index.html
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent/Views/Wallets/Send/PrivacyControlView.axaml
  WalletWasabi.Packager/Program.cs
  WalletWasabi/Services/SleepInhibitor.cs
Labels: size/S

#7091 Fix payjoin typos
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml
  WalletWasabi.Packager/Program.cs
Labels: size/S

#7123 Separate WalletTrackingData
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinsHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/TransactionHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WabiSabi/Client/CoinJoinTracker.cs
  WalletWasabi/WabiSabi/Client/CoinJoinTrackerFactory.cs
Labels: size/L

#7129 update avalonia to 0.10.12 with critical fixes
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
Labels: size/L

#7125 [Trivial] Remove unnecessary const and Assert
  WalletWasabi.Tests/UnitTests/Blockchain/Blocks/SmarthHeaderChainTests.cs
  WalletWasabi.Tests/UnitTests/TestWallet.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/IKeyChain.cs
Labels: size/S

#7124 When To Mix - Delay AutoCoinJoin
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/XS

#7137 Pass wallet passphrase to KeyChain
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/AliceTimeoutTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/KeyChainTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi/WabiSabi/Client/CoinJoinTrackerFactory.cs
  WalletWasabi/WabiSabi/Client/KeyChain.cs
  WalletWasabi/Wallets/Kitchen.cs
Labels: size/M

#7085 [Trivial] Fix typos and rename file
  WalletWasabi.Tests/Helpers/ArenaBuilder.cs
  WalletWasabi/Blockchain/TransactionBuilding/ChangelessTransactionCoinSelector.cs
  WalletWasabi/JsonConverters/DefaultValueCoordinationFeeRateAttribute.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
  WalletWasabi/WabiSabi/Client/CredentialDependencies/DependencyGraph.cs
Labels: size/S

#7133 [WabiSabi] Some UTs for `SelectCoinsForRound`
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/CoinJoinCoinSelectionTests.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/L

#7138 Remove unnecessary time padding and fix format
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/XS

#7131 When To Mix - Last minute
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinTrackerFactory.cs
Labels: size/S

#7088 Fix typos in backend files
  WalletWasabi.Backend/Controllers/BlockchainController.cs
  WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
  WalletWasabi.Backend/wwwroot/css/style.css
  WalletWasabi.Backend/wwwroot/index.html
Labels: size/M

#7149 [Trivial] Remove unnecessary const
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/XS

#7126 When To Mix - PlebStop feature
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/S

#7109 Proper backend log message when the round is free for everyone
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/S

#7116 Adding some debug information into sanity check
  WalletWasabi/WabiSabi/Client/AliceClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/M

#7130 Fix LineChart.DrawYAxisLabels after 0.10.12 Avalonia update
  WalletWasabi.Fluent/Controls/LineChart.cs
Labels: size/XS

#7142 Switch HeightJsonConverter from 'JsonConverter' to 'JsonConverter<T>'
  WalletWasabi/JsonConverters/HeightJsonConverter.cs
Labels: size/S

#7143 Switch KeyJsonConverter from 'JsonConverter' to 'JsonConverter<T>'
  WalletWasabi/JsonConverters/KeyJsonConverter.cs
Labels: size/S

#7157 Fix Packager if Git is missing
  WalletWasabi.Packager/Program.cs
Labels: size/M
