Repository WalletWasabi/WalletWasabi, pull requests merged in 2022-06, with the labels that each got.

#8198 [VDG] Make recovery word validation case insensitive
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/RecoveryWordViewModel.cs
Labels: size/XS

#8203 Sign all but one input in case inconsistent coordinator.
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/S

#8229 [VDG] Tray - fix hide
  WalletWasabi.Fluent/App.axaml
  WalletWasabi.Fluent/ApplicationStateManager.cs
  WalletWasabi.Fluent/Providers/IMainWindowService.cs
  WalletWasabi.Fluent/ViewModels/ApplicationViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
Labels: size/L

#8241 Change client version back to 1.1.13.1
  WalletWasabi/Helpers/Constants.cs
Labels: size/XS

#8245 [VDG] Remove tooltip NavBar
  WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
Labels: size/XS

#8240 [VDG] [Trivial] Fix flicking "No results" title in SearchBar
  WalletWasabi.Fluent/Views/SearchBar/SearchBarDropdown.axaml
Labels: size/XS

#8227 [VDG] Fix amount/fee formatting in TxnPreview
  WalletWasabi.Fluent/Extensions/TransactionSummaryExtension.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/ChangeAvoidanceSuggestionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionSummaryViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionSummary.axaml
Labels: size/M

#8194 [VDG] new desktop icon
  WalletWasabi.Fluent/Assets/WasabiLogo.ico
  WalletWasabi.Packager/Content/Osx/WasabiLogo.icns
Labels: size/XS

#8193 [VDG] Better wallet icon
  WalletWasabi.Fluent/Assets/WalletIcons/Dark/normal.png
  WalletWasabi.Fluent/Assets/WalletIcons/Light/normal.png
Labels: size/XS

#8242 [Trivial] Use LogInfo to be able to see successful CoinJoin txid
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/XS

#8248 [VDG] Receive - label is not visible fix
  WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveAddressView.axaml
Labels: size/XS

#8215 [VDG] Check two instances sooner
  WalletWasabi.Fluent.Desktop/Extensions/AppBuilderExtension.cs
  WalletWasabi.Fluent.Desktop/Program.cs
  WalletWasabi.Fluent/Services.cs
  WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs
Labels: size/L

#8255 Forget clusters when no unique outputs created in coinjoins
  WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs
Labels: size/XS

#8246 [VDG] [trivial] Handcursor tx broadcaster
  WalletWasabi.Fluent/Controls/TileButton.axaml
Labels: size/XS

#8256 Solve problem with small denominations in change.
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
Labels: size/M

#8263 Rename Privacy Mode to Discreet Mode
  WalletWasabi.Fluent/ViewModels/Settings/PrivacyModeViewModel.cs
  WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
Labels: size/S

#8272 Improve coinjoin summary
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/CoinJoinsDetailsViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/Details/CoinJoinsDetailsView.axaml
Labels: size/M

#8276 [VDG] Fix enter key in password finder
  WalletWasabi.Fluent/Views/Login/PasswordFinder/PasswordFinderIntroduceView.axaml
Labels: size/XS

#8275 [VDG] Password finder crash fix
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/SearchPasswordViewModel.cs
Labels: size/XS

#8270 [VDG] Receive Address - Edit Label - Suggestions
  WalletWasabi.Fluent/ViewModels/Wallets/Labels/SuggestionLabelsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/AddressLabelEditViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressesViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Receive/AddressLabelEditView.axaml
Labels: size/M

#8266 [VDG] CoinjoinProfile drop shadow clip fix
  WalletWasabi.Fluent/Views/CoinJoinProfiles/CoinJoinProfilesView.axaml
Labels: size/XS

#8264 [trivial] TileButton code layout improvement
  WalletWasabi.Fluent/Controls/TileButton.axaml
Labels: size/XS

#8262 [VDG] Fix wallet ordering
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModelBase.cs
Labels: size/S

#8265 [VDG] Single click add wallet UI
  WalletWasabi.Fluent/Controls/TileButton.axaml
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/AddWalletPageView.axaml
Labels: size/L

#8268 [VDG] Password finder improvements
  WalletWasabi.Fluent/Assets/PasswordFinder/Dark/numbers.png
  WalletWasabi.Fluent/Assets/PasswordFinder/Dark/symbols.png
  WalletWasabi.Fluent/Assets/PasswordFinder/Light/numbers.png
  WalletWasabi.Fluent/Assets/PasswordFinder/Light/symbols.png
  WalletWasabi.Fluent/Controls/TileButton.axaml
  WalletWasabi.Fluent/Converters/EnumConverters.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/CharsetViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/ContainsNumbersViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/ContainsSymbolsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/SelectCharsetViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/AddWalletPageView.axaml
  WalletWasabi.Fluent/Views/Login/PasswordFinder/ContainsNumbersView.axaml
  WalletWasabi.Fluent/Views/Login/PasswordFinder/ContainsSymbolsView.axaml
  WalletWasabi.Fluent/Views/Login/PasswordFinder/PasswordFinderIntroduceView.axaml
  WalletWasabi.Fluent/Views/Login/PasswordFinder/SelectCharsetView.axaml
Labels: size/L

#8279 Remove obsolated hack
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Labels: size/XS

#8238 Update to stable release of Avalonia
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
Labels: size/L

#8223 Differentiate between 1.0 and 2.0 Legal docs (client and backend)
  WalletWasabi.Backend/Controllers/SoftwareController.cs
  WalletWasabi.Backend/Controllers/WasabiController.cs
  WalletWasabi/Backend/Models/Responses/VersionsResponse.cs
  WalletWasabi/Helpers/Constants.cs
  WalletWasabi/Legal/Assets/LegalDocumentsWw1.txt
  WalletWasabi/Legal/Assets/LegalDocumentsWw2.txt
  WalletWasabi/Legal/LegalDocuments.cs
  WalletWasabi/Services/LegalChecker.cs
  WalletWasabi/WalletWasabi.csproj
  WalletWasabi/WebClients/Wasabi/WasabiClient.cs
Labels: size/L

#8200 [VDG] Remove white space and returns from address upon paste
  WalletWasabi.Fluent/Behaviors/PasteButtonFlashBehavior.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
Labels: size/XS

#8261 [VDG] make T&C available from the SearchBar
  WalletWasabi.Fluent/ViewModels/AddWallet/LegalDocumentsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/TermsAndConditionsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/LoginViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/LegalDocumentsView.axaml
  WalletWasabi/Services/LegalChecker.cs
Labels: size/M

#8260 [VDG] Bring Wasabi front on the second start
  WalletWasabi.Fluent.Desktop/Program.cs
  WalletWasabi.Fluent/ApplicationStateManager.cs
  WalletWasabi.Fluent/Services.cs
Labels: size/S

#8282 Allow unauthenticated access to RPC
  WalletWasabi/Rpc/JsonRpcServer.cs
Labels: size/S

#8277 [VDG] Label fixes
  WalletWasabi.Fluent/Controls/LabelControl.axaml
  WalletWasabi.Fluent/Controls/LabelsListBox.axaml
  WalletWasabi.Fluent/Styles/Button.axaml
Labels: size/M

#8303 [VDG] [TRIVIAL] Fix history placeholder column widths
  WalletWasabi.Fluent/Controls/HistoryPlaceholderPanel.axaml
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
Labels: size/XS

#8293 [VDG] Remove the Icon workaround on Search Bar
  WalletWasabi.Fluent/Views/SearchBar/SearchBarDropdown.axaml
Labels: size/XS

#8302 [VDG] Fix ordering of history list
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
Labels: size/XS

#7415 [VDG] Improve NavBar scroll UX
  WalletWasabi.Fluent/Styles/CuedScrollViewer.axaml
  WalletWasabi.Fluent/Styles/Styles.axaml
  WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
Labels: size/L

#8311 [VDG] Simplify layout for SearchBar dropdown results (icon)
  WalletWasabi.Fluent/Views/SearchBar/SearchBarDropdown.axaml
Labels: size/XS

#8296 [trivial] unify manualCJprofile & settings
  WalletWasabi.Fluent/Views/Dialogs/ManualCoinJoinProfileDialogView.axaml
Labels: size/XS

#8298 Recovery Words - caption text
  WalletWasabi.Fluent/Views/AddWallet/Create/RecoveryWordsView.axaml
Labels: size/XS

#8322 Add label suggestion exceptions
  WalletWasabi.Fluent/ViewModels/Wallets/Labels/SuggestionLabelsViewModel.cs
Labels: size/S

#8237 [WabiSabi] Do not reveal common ownership in case of errors
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/ConfigTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/CoordinatorTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiApiApplicationFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi/Tor/Http/Extensions/HttpResponseMessageExtensions.cs
  WalletWasabi/WabiSabi/Backend/Statistics/CoinJoinScriptStore.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/DependencyGraphTaskScheduler.cs
  WalletWasabi/WabiSabi/Client/WabiSabiHttpApiClient.cs
  WalletWasabi/WabiSabi/LoggerTools.cs
  WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
Labels: size/L

#8305 [VDG] AutoPaste - fix NRE when trimming
  WalletWasabi.Fluent/Behaviors/PasteButtonFlashBehavior.cs
Labels: size/XS

#8327 Revert "[WabiSabi] Do not reveal common ownership in case of errors"
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/ConfigTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/CoordinatorTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiApiApplicationFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi/Tor/Http/Extensions/HttpResponseMessageExtensions.cs
  WalletWasabi/WabiSabi/Backend/Statistics/CoinJoinScriptStore.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/DependencyGraphTaskScheduler.cs
  WalletWasabi/WabiSabi/Client/WabiSabiHttpApiClient.cs
  WalletWasabi/WabiSabi/LoggerTools.cs
  WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
Labels: size/L

#8329 Make suggestions hopefully useful
  WalletWasabi.Fluent/Behaviors/PasteButtonFlashBehavior.cs
  WalletWasabi.Fluent/Helpers/WalletHelpers.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/LabelEntryDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Labels/SuggestionLabelsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/AddressLabelEditViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveViewModel.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/Blockchain/Transactions/AllTransactionStore.cs
Labels: size/M

#8328 Create blame round only when appropiated
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/XS

#8313 [VDG] Fix double paste address
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
Labels: size/S

#8317 [VDG] Fix `QuestionControl` highlight button
  WalletWasabi.Fluent/Controls/QuestionControl.axaml
Labels: size/XS

#8338 Bnb Input count limiting
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacySuggestionsFlyoutViewModel.cs
Labels: size/XS

#8267 [VDG] Wallet Settings + Coinjoin Profiles (Take 2)
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/CoinJoinProfileViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/CoinJoinProfilesViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/ManualCoinJoinProfileViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/PrivateCoinJoinProfileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/ManualCoinJoinProfileDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletSettingsViewModel.cs
  WalletWasabi.Fluent/Views/Dialogs/ManualCoinJoinProfileDialogView.axaml
  WalletWasabi.Fluent/Views/Wallets/WalletSettingsView.axaml
Labels: size/L

#8334 Unit test to verify we don't reveal common ownership of inputs
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/ConfigTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/CoordinatorTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/IWebHostBuilderExtensions.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiApiApplicationFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi/WabiSabi/Backend/Statistics/CoinJoinScriptStore.cs
  WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
Labels: size/L

#8337 Participate in blame round with signers only
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/XS

#8318 [VDG] Fix wallet settings for HW wallets
  WalletWasabi.Fluent/Views/Wallets/WalletSettingsView.axaml
Labels: size/XS

#8344 [VDG] Semi private pocket
  WalletWasabi.Fluent/Helpers/CoinHelpers.cs
  WalletWasabi.Fluent/Helpers/CoinPocketHelper.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/LabelSelectionViewModel.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
  WalletWasabi.Tests/UnitTests/UserInterfaceTest/PocketSelectionTests.cs
Labels: size/L

#8348 Add key stats for wallet stats
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletStatsViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletStatsView.axaml
  WalletWasabi.Tests/UnitTests/KeyManagementTests.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
Labels: size/L

#8350 Remove MinGapLimit from Wallet Stats
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletStatsViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletStatsView.axaml
Labels: size/XS

#8349 Improve locked key usage
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/M

#8352 [VDG] Welcome Page design refresh
  WalletWasabi.Fluent/Assets/WelcomeScreen/Dark/anonymous.png
  WalletWasabi.Fluent/Assets/WelcomeScreen/Dark/opensource.png
  WalletWasabi.Fluent/Assets/WelcomeScreen/Dark/trustless.png
  WalletWasabi.Fluent/Assets/WelcomeScreen/Dark/welcome.png
  WalletWasabi.Fluent/Assets/WelcomeScreen/Light/anonymous.png
  WalletWasabi.Fluent/Assets/WelcomeScreen/Light/opensource.png
  WalletWasabi.Fluent/Assets/WelcomeScreen/Light/trustless.png
  WalletWasabi.Fluent/Assets/WelcomeScreen/Light/welcome.png
  WalletWasabi.Fluent/ViewModels/AddWallet/WelcomePageViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/WelcomePageView.axaml
Labels: size/L

#8355 `StreamExtensions`: Improve cancellation.
  WalletWasabi/Extensions/StreamExtensions.cs
  WalletWasabi/Tor/Socks5/TorTcpConnectionFactory.cs
Labels: size/S

#8319 [VDG][TempFix] Make WalletInfo usable for WatchOnly wallets
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletInfoViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletInfoView.axaml
Labels: size/M

#8353 [VDG] Make styles of NavBar's ScrollBar more restrictive
  WalletWasabi.Fluent/Styles/CuedScrollViewer.axaml
Labels: size/XS

#8345 [VDG] Disable scrollviewer scrollbars in the send address textbox
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Labels: size/XS

#8357 increase the amount of gpu memory allowable for assets.
  WalletWasabi.Fluent.Desktop/Extensions/AppBuilderExtension.cs
Labels: size/XS

#8356 Move FilePath setting in RecoverWalletViewModel
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
Labels: size/XS

#8362 Don't use weighted anonscore for change outputs (WW1 anonscore fix)
  WalletWasabi.Tests/UnitTests/BlockchainAnalysis/CoinJoinAnonscoreTests.cs
  WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs
Labels: size/M

#8368 Use very small texture for Aura
  WalletWasabi.Fluent/Controls/Spectrum/SpectrumControl.cs
Labels: size/L

#8366 Add simple lock to ConfigBase
  WalletWasabi/Bases/ConfigBase.cs
Labels: size/S

#8364 Materilize sequences to prevent multiple evaluations
  WalletWasabi.Tests/UnitTests/Wallet/SmartCoinSelectorTests.cs
  WalletWasabi/Blockchain/TransactionBuilding/SmartCoinSelector.cs
Labels: size/S

#8361 Update WW2 legal docs
  WalletWasabi/Helpers/Constants.cs
  WalletWasabi/Legal/Assets/LegalDocumentsWw2.txt
Labels: size/L

#8369 [VDG] Welcome Page corrections
  WalletWasabi.Fluent/Views/AddWallet/WelcomePageView.axaml
Labels: size/S

#8370 [VDG] New icons part 2
  WalletWasabi.Fluent/Assets/WasabiLogo.ico
  WalletWasabi.Packager/Content/Osx/WasabiLogo.icns
Labels: size/XS

#8371 WW2 Legal docs small typo
  WalletWasabi/Legal/Assets/LegalDocumentsWw2.txt
Labels: size/XS

#8372 Bump version to 2.0.0.0
  WalletWasabi/Helpers/Constants.cs
Labels: size/XS

#8374 Change App icon as well on OSX
  WalletWasabi.Packager/Content/Osx/App/Contents/Resources/WasabiLogo.icns
Labels: size/XS

#8389 Improve backend log a bit
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/XS

#8390 Optimize MaxSuggestedAmount variation
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/Rounds/MultipartyTransactionStateTests.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Rounds/MaxSuggestedAmountProvider.cs
Labels: size/S

#8391 Add Human readable round information API
  WalletWasabi.Backend/Controllers/WabiSabiController.cs
  WalletWasabi/WabiSabi/Models/HumanMonitorResponse.cs
  WalletWasabi/WabiSabi/Models/HumanMonitorRoundResponse.cs
Labels: size/M

#8392 Fix LegalDocs link in website
  WalletWasabi.Backend/wwwroot/index.html
  WalletWasabi.Backend/wwwroot/onion-index.html
Labels: size/M

#8393 Keep largest MaxSuggestedAmount until successful input reg
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/Rounds/MultipartyTransactionStateTests.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Rounds/MaxSuggestedAmountProvider.cs
  WalletWasabi/WabiSabi/Backend/Rounds/RoundParameterFactory.cs
Labels: size/L

#8397 Add log for possible blame failure catch
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/XS

#8401 Remove nonimportant tohashsets those might ruin things
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/XS

#8402 Log witness count
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/XS

#8403 Add more log
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/XS

#8404 Add more logs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/XS

#8407 Remove unnecessary log
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/XS

#8410 Add wabisabi request statista
  WalletWasabi.Backend/Controllers/WabiSabi/RequestTimeStatista.cs
  WalletWasabi.Backend/Controllers/WabiSabiController.cs
  WalletWasabi/Crypto/Extensions.cs
Labels: size/L

#8411 Increase statista time to 60 minutes
  WalletWasabi.Backend/Controllers/WabiSabi/RequestTimeStatista.cs
Labels: size/XS

#8417 [Fix] Registration halt
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/XS

#8418 If someone didnt confirm fail and blame
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepConnectionConfirmationTests.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Labels: size/S

#8432 Add back output reg step for blame rounds
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/S

#8433 Add buffer times
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
  WalletWasabi/WabiSabi/Backend/Rounds/TimeFrame.cs
Labels: size/M

#8441 Reduce buffer of signing to zero
  WalletWasabi/WabiSabi/Backend/Rounds/TimeFrame.cs
Labels: size/XS

#8442 Send NotAllAlicesSign so people get into blame round
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
  WalletWasabi/WabiSabi/Backend/Rounds/TimeFrame.cs
Labels: size/S

#8443 Revert blame round creation
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
Labels: size/S

#8444 Fix order
  WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
Labels: size/XS

#8445 Add buffer for output reg
  WalletWasabi/WabiSabi/Backend/Rounds/TimeFrame.cs
Labels: size/XS

#8464 Timeout fast when previous phase failed
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
  WalletWasabi/WabiSabi/Backend/Rounds/RoundParameters.cs
  WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
Labels: size/S

#8465 Revert buffer time
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
  WalletWasabi/WabiSabi/Backend/Rounds/TimeFrame.cs
Labels: size/M

#8466 Fix unit test
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
Labels: size/XS

#8431 Never release during a Tor network disruption
  WalletWasabi.Documentation/ClientDeployment.md
Labels: size/XS

#8469 TorHttpPool: Split lock to allow concurrent Tor circuits creation [dev 2.0.1]
  WalletWasabi/Tor/Socks5/Pool/Circuits/DefaultCircuit.cs
  WalletWasabi/Tor/Socks5/Pool/Circuits/ICircuit.cs
  WalletWasabi/Tor/Socks5/Pool/Circuits/PersonCircuit.cs
  WalletWasabi/Tor/Socks5/Pool/TorHttpPool.cs
  WalletWasabi/Tor/TorMonitor.cs
  WalletWasabi/WabiSabi/Client/WabiSabiHttpApiClient.cs
Labels: size/M

#8472 Decrease input reg available time, so the clients hurry up.
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/XS

#8471 Log phase duration in case of late requests, so we can analyze it
  WalletWasabi.Backend/Filters/LateResponseLoggerFilter.cs
  WalletWasabi/WabiSabi/Backend/Models/WrongPhaseException.cs
Labels: size/S

#8486 Implement parallel rounds
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Rounds/TimeFrame.cs
  WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
  WalletWasabi/WabiSabi/Client/RoundStateAwaiters/RoundStateAwaiter.cs
  WalletWasabi/WabiSabi/Client/RoundStateAwaiters/RoundStateUpdater.cs
Labels: size/S

#8495 Implement WW2.0.0 Compatible CJ Load Balancer
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
Labels: size/M

#8499 Improve DDoS Protection
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/XS

#8481 `TorMonitor`: Verify using software-versions API [dev 2.0.1]
  WalletWasabi/Tor/Http/TorHttpClient.cs
  WalletWasabi/Tor/TorMonitor.cs
Labels: size/S

#8489 Abort pending requests when we are late
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/AliceTimeoutTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi/WabiSabi/Backend/Models/WrongPhaseException.cs
  WalletWasabi/WabiSabi/Backend/Models/WrongPhaseExceptionData.cs
  WalletWasabi/WabiSabi/Client/AliceClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Models/Serialization/ExceptionDataJsonConverter.cs
Labels: size/M

#8504 Continue retrying requests until the phase finishes
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi/WabiSabi/Client/WabiSabiHttpApiClient.cs
Labels: size/S

#8507 Upgrade xUnit to get NRT support
  WalletWasabi.Tests/WalletWasabi.Tests.csproj
Labels: size/XS

#8509 `.editorconfig`: Insert final newline to all files
  .editorconfig
Labels: size/XS

#8493 Do not unregister wrong phase
  WalletWasabi/WabiSabi/Client/AliceClient.cs
Labels: size/XS

#8512 Try fix tokens around registration
  WalletWasabi/WabiSabi/Client/AliceClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/L

#8474 [trivial] Fix analyzer error.
  WalletWasabi/WabiSabi/Client/DependencyGraphTaskScheduler.cs
Labels: size/S

#8476 [VDG] Add Tor Status Checker
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/AppServices/Tor/Issue.cs
  WalletWasabi.Fluent/AppServices/Tor/StatusChecker.cs
  WalletWasabi.Fluent/AppServices/Tor/TorNetwork.cs
  WalletWasabi.Fluent/AppServices/Tor/XmlIssueListParser.cs
  WalletWasabi.Fluent/Controls/StatusItem.axaml
  WalletWasabi.Fluent/Controls/StatusItem.axaml.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/StatusIcon/HttpGetStringReader.cs
  WalletWasabi.Fluent/ViewModels/StatusIcon/IStatusIconViewModel.cs
  WalletWasabi.Fluent/ViewModels/StatusIcon/StatusIconDesignViewModel.cs
  WalletWasabi.Fluent/ViewModels/StatusIcon/StatusIconViewModel.cs
  WalletWasabi.Fluent/Views/StatusIcon/StatusIcon.axaml
  WalletWasabi.Fluent/Views/StatusIcon/TorIssuesControl.axaml
  WalletWasabi.Fluent/Views/StatusIcon/TorIssuesControl.axaml.cs
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
  WalletWasabi.Tests/UnitTests/Tor/NetworkChecker/XmlIssueListParserTests.cs
Labels: size/L

#8524 Clarify wording + Increase Time
  WalletWasabi/Tor/TorMonitor.cs
Labels: size/XS

#8520 Cancel when not conn conf
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/S

#8521 Make WW2.0.0 client most preferred round to be the last
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/M

#8533 Avoid exit nodes
  WalletWasabi.Fluent/Global.cs
  WalletWasabi/Tor/TorMonitor.cs
Labels: size/M

#8532 trivial - typo fix
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/XS

#8534 Fix for Tor Checker preventing application from closing normally
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
Labels: size/XS

#8539 [VDG] Make TorIssuesControl have a proper size in StatusIcon
  WalletWasabi.Fluent/Controls/StatusItem.axaml
  WalletWasabi.Fluent/Controls/StatusItem.axaml.cs
  WalletWasabi.Fluent/Views/StatusIcon/TorIssuesControl.axaml
Labels: size/M

#8536 Use PeriodicRunner for Tor Status Checker
  WalletWasabi.Fluent/AppServices/Tor/StatusChecker.cs
  WalletWasabi.Fluent/AppServices/Tor/TorNetwork.cs
  WalletWasabi.Fluent/AppServices/Tor/TorStatusCheckerWrapper.cs
  WalletWasabi.Fluent/Global.cs
  WalletWasabi.Fluent/Services.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/StatusIcon/HttpGetStringReader.cs
  WalletWasabi.Fluent/ViewModels/StatusIcon/IStatusIconViewModel.cs
  WalletWasabi.Fluent/ViewModels/StatusIcon/StatusIconDesignViewModel.cs
  WalletWasabi.Fluent/ViewModels/StatusIcon/StatusIconViewModel.cs
  WalletWasabi.Fluent/Views/StatusIcon/TorIssuesControl.axaml
  WalletWasabi.Tests/UnitTests/Services/Tor/XmlIssueListParserTests.cs
  WalletWasabi/Tor/StatusChecker/Issue.cs
  WalletWasabi/Tor/StatusChecker/TorStatusChecker.cs
  WalletWasabi/Tor/StatusChecker/XmlIssueListParser.cs
Labels: size/L

#8542 Keep retrying for any transport exception
  WalletWasabi/WabiSabi/Client/WabiSabiHttpApiClient.cs
Labels: debug, priority, size/XS

#8552 Firefox blur effect fixes
  WalletWasabi.Backend/wwwroot/css/style.css
Labels: size/S

#8554 2.0.1 download links
  WalletWasabi.Backend/wwwroot/index.html
  WalletWasabi.Backend/wwwroot/onion-index.html
Labels: size/M

#8555 Update version to 2.0.1
  WalletWasabi/Helpers/Constants.cs
Labels: size/XS

#8558 [VDG] Fix bad StatusIcon icon
  WalletWasabi.Fluent/Views/StatusIcon/StatusIcon.axaml
Labels: size/XS

#8343 [VDG] Fix bad flyout behavior after theme switch
  WalletWasabi.Fluent/Behaviors/SearchBarBehavior.cs
Labels: size/XS

#8320 [VDG] Remove hyperlink from add HW wallet
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/ConnectHardwareWalletViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/HardwareWallet/ConnectHardwareWalletView.axaml
Labels: size/XS

#8560 [VDG] Enable Go Back in Welcome Screen
  WalletWasabi.Fluent/ViewModels/AddWallet/WelcomePageViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/WelcomePageView.axaml
Labels: size/M

#8561 [VDG] Display error in compact dialog if it happened there
  WalletWasabi.Fluent/ViewModels/Dialogs/ShowQrCameraDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/RoutableViewModel.cs
Labels: size/S

#8564 [VDG] add confirmation numbers
  WalletWasabi.Fluent/Extensions/TransactionSummaryExtension.cs
  WalletWasabi.Fluent/Helpers/CoinHelpers.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/TransactionDetailsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/HistoryItemViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/TransactionHistoryItemViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/Columns/IndicatorsColumnView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/Columns/IndicatorsColumnView.axaml
Labels: size/S

#8559 Bump version on the website
  WalletWasabi.Backend/wwwroot/index.html
Labels: size/XS

#8414 Allow override of backend url
  WalletWasabi.Backend/Program.cs
Labels: size/XS

#8568 [VDG] Sort coins in Coin List by amount
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
Labels: size/XS
