Repository WalletWasabi/WalletWasabi, pull requests merged in 2022-02, with the labels that each got.

#7048 [Fluent] Disable suggestions that changes amount from a payment URL.
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacySuggestionsFlyoutViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
Labels: size/S

#7163 Run git on Solution directory
  WalletWasabi.Packager/Program.cs
Labels: size/XS

#7166 Copy Git dir as well
  azure-pipelines-detbuild.yml
Labels: size/XS

#7159 When To Mix - Do not start while sending
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Labels: size/S

#7068 Wire up ChanglessCoinSelector to UI
  WalletWasabi.Fluent/ViewModels/Wallets/Send/ChangeAvoidanceSuggestionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/LoadingSuggestionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacySuggestionsFlyoutViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionInfo.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Send/LoadingSuggestionView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/LoadingSuggestionView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml
  WalletWasabi.Tests/UnitTests/Blockchain/TransactionBuilding/ChangelessTransactionCoinSelectorTests.cs
  WalletWasabi/Blockchain/TransactionBuilding/ChangelessTransactionCoinSelector.cs
Labels: size/L

#7155 Decrease MaxLength to 50 characters, at add wallet
  WalletWasabi.Fluent/Views/AddWallet/AddWalletPageView.axaml
Labels: size/XS

#7098 bitcoin at preview transaction
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionSummaryViewModel.cs
Labels: size/XS

#7175 Move AnonScore target into a Wallet level settings
  WalletWasabi.Fluent/Config.cs
  WalletWasabi.Fluent/Helpers/CoinHelpers.cs
  WalletWasabi.Fluent/ViewModels/Settings/PrivacySettingsTabViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletBalanceTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacySuggestionsFlyoutViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionInfo.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletSettingsViewModel.cs
  WalletWasabi.Fluent/Views/Settings/PrivacySettingsTabView.axaml
  WalletWasabi.Fluent/Views/Wallets/WalletSettingsView.axaml
  WalletWasabi.Tests/IntegrationTests/P2pTests.cs
  WalletWasabi.Tests/RegressionTests/Common.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/Models/ServiceConfiguration.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WabiSabi/Client/CoinJoinTrackerFactory.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/L

#7190 set `IsUserInSendWorkflow` when sending
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
Labels: size/S

#7189 Changed StaticResource to DynamicResource in Button.axaml
  WalletWasabi.Fluent/Styles/Button.axaml
Labels: size/XS

#7200 [Trivial] Remove leftover code of #7175
  WalletWasabi.Fluent/ViewModels/Settings/PrivacySettingsTabViewModel.cs
  WalletWasabi/Models/ServiceConfiguration.cs
Labels: size/XS

#7203 Fix Anon Score Targets crash
  WalletWasabi.Fluent/ViewModels/Wallets/WalletSettingsViewModel.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
Labels: size/S

#7192 Small fixes when generating suggestions
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacySuggestionsFlyoutViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
Labels: size/M

#7196 [WabiSabi] Stream status 4
  WalletWasabi.Backend/Controllers/WabiSabiController.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/Rounds/MultipartyTransactionStateTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiApiApplicationFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/MultipartyTransactionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/RoundStateUpdaterTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/SerializationTests.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/IWabiSabiApiRequestHandler.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Client/ArenaClient.cs
  WalletWasabi/WabiSabi/Client/RoundStateUpdater.cs
  WalletWasabi/WabiSabi/Client/WabiSabiHttpApiClient.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/ConstructionState.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/MultipartyTransactionState.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/SigningState.cs
  WalletWasabi/WabiSabi/Models/RoundState.cs
  WalletWasabi/WabiSabi/Models/RoundStateRequest.cs
  WalletWasabi/WabiSabi/Models/Serialization/CoinJoinEventJsonConverter.cs
  WalletWasabi/WabiSabi/Models/Serialization/GenericInterfaceJsonConverter.cs
  WalletWasabi/WabiSabi/Models/Serialization/JsonSerializationOptions.cs
  WalletWasabi/WabiSabi/Models/Serialization/MultipartyTransactionStateJsonConverter.cs
Labels: size/L

#7120 [PoC] Add new QR reader logic / Remove OpenCVSharp
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/GlobalSuppressions.cs
  WalletWasabi.Fluent/Models/WebcamQrReader.cs
  WalletWasabi.Fluent/Models/Windows/DirectShow.cs
  WalletWasabi.Fluent/Models/Windows/WindowsCapture.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/ShowQrCameraDialogViewModel.cs
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/ZXing/AlignmentPattern.cs
  WalletWasabi.Fluent/ZXing/AlignmentPatternFinder.cs
  WalletWasabi.Fluent/ZXing/BarcodeFormat.cs
  WalletWasabi.Fluent/ZXing/BaseLuminanceSource.cs
  WalletWasabi.Fluent/ZXing/Binarizer.cs
  WalletWasabi.Fluent/ZXing/BinaryBitmap.cs
  WalletWasabi.Fluent/ZXing/BitArray.cs
  WalletWasabi.Fluent/ZXing/BitMatrix.cs
  WalletWasabi.Fluent/ZXing/BitMatrixParser.cs
  WalletWasabi.Fluent/ZXing/BitSource.cs
  WalletWasabi.Fluent/ZXing/BitmapLuminanceSource.cs
  WalletWasabi.Fluent/ZXing/CharacterSetECI.cs
  WalletWasabi.Fluent/ZXing/DataBlock.cs
  WalletWasabi.Fluent/ZXing/DataMask.cs
  WalletWasabi.Fluent/ZXing/DecodeHintType.cs
  WalletWasabi.Fluent/ZXing/DecodedBitStreamParser.cs
  WalletWasabi.Fluent/ZXing/Decoder.cs
  WalletWasabi.Fluent/ZXing/DecoderResult.cs
  WalletWasabi.Fluent/ZXing/DefaultGridSampler.cs
  WalletWasabi.Fluent/ZXing/Detector.cs
  WalletWasabi.Fluent/ZXing/DetectorResult.cs
  WalletWasabi.Fluent/ZXing/ECI.cs
  WalletWasabi.Fluent/ZXing/ErrorCorrectionLevel.cs
  WalletWasabi.Fluent/ZXing/FinderPattern.cs
  WalletWasabi.Fluent/ZXing/FinderPatternFinder.cs
  WalletWasabi.Fluent/ZXing/FinderPatternInfo.cs
  WalletWasabi.Fluent/ZXing/FormatInformation.cs
  WalletWasabi.Fluent/ZXing/GenericGF.cs
  WalletWasabi.Fluent/ZXing/GenericGFPoly.cs
  WalletWasabi.Fluent/ZXing/GlobalHistogramBinarizer.cs
  WalletWasabi.Fluent/ZXing/GridSampler.cs
  WalletWasabi.Fluent/ZXing/HybridBinarizer.cs
  WalletWasabi.Fluent/ZXing/InvertedLuminanceSource.cs
  WalletWasabi.Fluent/ZXing/LICENSE.md
  WalletWasabi.Fluent/ZXing/LuminanceSource.cs
  WalletWasabi.Fluent/ZXing/MathUtils.cs
  WalletWasabi.Fluent/ZXing/Mode.cs
  WalletWasabi.Fluent/ZXing/PerspectiveTransform.cs
  WalletWasabi.Fluent/ZXing/QRCodeDecoderMetaData.cs
  WalletWasabi.Fluent/ZXing/QRCodeReader.cs
  WalletWasabi.Fluent/ZXing/Reader.cs
  WalletWasabi.Fluent/ZXing/ReedSolomonDecoder.cs
  WalletWasabi.Fluent/ZXing/Result.cs
  WalletWasabi.Fluent/ZXing/ResultMetadataType.cs
  WalletWasabi.Fluent/ZXing/ResultPoint.cs
  WalletWasabi.Fluent/ZXing/ResultPointCallback.cs
  WalletWasabi.Fluent/ZXing/StringUtils.cs
  WalletWasabi.Fluent/ZXing/SupportClass.cs
  WalletWasabi.Fluent/ZXing/Version.cs
  WalletWasabi.Fluent/packages.lock.json
  WalletWasabi.Tests/UnitTests/QrDecode/QrCodeDecodingTests.cs
Labels: size/XXL

#7205 [VDG] Show wallet coins on key combination press
  WalletWasabi.Fluent/Behaviors/ShowWalletCoinsOnKeyCombinationBehavior.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/Views/MainWindow.axaml
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/WalletCoinsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/WalletCoinsView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
Labels: size/L

#7195 Do not wait for a Round Phase that is already Ended
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/RoundStateUpdaterTests.cs
  WalletWasabi/WabiSabi/Client/AliceClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/RoundStateAwaiter.cs
  WalletWasabi/WabiSabi/Client/RoundStateUpdater.cs
Labels: size/L

#7209 Add log to `SoloCoinjoinTestAsync`
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
Labels: size/XS

#7136 Upgrade NBitcoin to `6.0.19` from `6.0.8`
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/packages.lock.json
  WalletWasabi.Packager/packages.lock.json
  WalletWasabi/BestEffortEndpointConnector.cs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/ConstructionState.cs
  WalletWasabi/WalletWasabi.csproj
  WalletWasabi/Wallets/PasswordFinder/PasswordFinderHelper.cs
  WalletWasabi/packages.lock.json
Labels: size/M

#7222 Execute 'builder.CoinFinder' when payjoin tx only
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
Labels: size/XS

#7225 Fix default values
  WalletWasabi/Blockchain/Keys/KeyManager.cs
Labels: size/S

#7191 Optimize startup time a bit more
  WalletWasabi.Tests/UnitTests/Filters/IndexStoreTests.cs
  WalletWasabi/Backend/Models/FilterModel.cs
  WalletWasabi/Blockchain/BlockFilters/StartingFilters.cs
  WalletWasabi/Blockchain/Blocks/SmartHeader.cs
Labels: size/M

#7229 Use variable length integer in CoinJoinInputCommitmentData
  WalletWasabi/Crypto/CoinJoinInputCommitmentData.cs
Labels: size/XS

#7070 [VDG] Refactor pocket selection ux
  WalletWasabi.Fluent/App.axaml
  WalletWasabi.Fluent/Behaviors/BindPointerOverBehavior.cs
  WalletWasabi.Fluent/Controls/QuestionControl.axaml
  WalletWasabi.Fluent/Controls/SuggestionItem.axaml
  WalletWasabi.Fluent/Controls/SuggestionItem.axaml.cs
  WalletWasabi.Fluent/Converters/BoolToBrushConverter.cs
  WalletWasabi.Fluent/Models/Pocket.cs
  WalletWasabi.Fluent/Styles/Themes/Base.axaml
  WalletWasabi.Fluent/Styles/Themes/BaseDark.axaml
  WalletWasabi.Fluent/Styles/Themes/BaseLight.axaml
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/PrivacySettingsTabViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/SettingsPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/ConfirmLabelsDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/LabelSelectionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/LabelViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PocketViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacySuggestionsFlyoutViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Fluent/Views/Settings/PrivacySettingsTabView.axaml
  WalletWasabi.Fluent/Views/Settings/SettingsPageView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/ChangeAvoidanceSuggestionControl.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/ConfirmLabelsDialogView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/ConfirmLabelsDialogView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Send/PocketSuggestionControl.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/PrivacyControlView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml
  WalletWasabi.Tests/UnitTests/UserInterfaceTest/PocketSelectionTests.cs
Labels: size/XXL

#6992 [VDG] [Fluent] Disable status bar loading animation when not visible
  WalletWasabi.Fluent/Views/StatusBar/StatusBar.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyControlTileView.axaml
Labels: size/XS

#7176 [VDG] [Fluent] Fix SendView YAxisLabelOffset
  WalletWasabi.Fluent/Views/Wallets/Send/SendFeeView.axaml
Labels: size/XS

#7228 Reverse byte order of round id in commitment data
  WalletWasabi/Crypto/CoinJoinInputCommitmentData.cs
Labels: size/XS

#7206 [Fluent] Beautify wallet settings dialog
  WalletWasabi.Fluent/Views/Wallets/WalletSettingsView.axaml
Labels: size/XS

#7078 Txfee slider: Name vertical axis "Fee Rate"
  WalletWasabi.Fluent/Views/Wallets/Send/SendFeeView.axaml
Labels: size/XS

#7215 Improve `isLikelyCoinjoin`
  WalletWasabi/Blockchain/TransactionProcessing/ProcessedResult.cs
  WalletWasabi/Blockchain/Transactions/TransactionHistoryBuilder.cs
  WalletWasabi/Extensions/NBitcoinExtensions.cs
Labels: size/S

#7236 Add missing output check
  WalletWasabi/Extensions/NBitcoinExtensions.cs
Labels: size/XS

#7237 Change key combo for Coinlist
  WalletWasabi.Documentation/DeveloperFeatures.md
  WalletWasabi.Fluent/Views/MainWindow.axaml
Labels: size/XS

#7238 Make autoCJ default sophisticated
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/Blockchain/Keys/WalletGenerator.cs
Labels: size/XS

#7239 generate suggestions even if user doesn't change the pockets
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
Labels: size/XS

#7230 Get rid of most of DirectShow warnings
  WalletWasabi.Fluent/Models/Windows/DirectShow.cs
  WalletWasabi.Fluent/Models/Windows/WindowsCapture.cs
Labels: size/XL

#7247 [VDG] Fix `EnoughSelected` calculation
  WalletWasabi.Fluent/ViewModels/Wallets/Send/LabelSelectionViewModel.cs
  WalletWasabi.Tests/UnitTests/UserInterfaceTest/PocketSelectionTests.cs
Labels: size/S

#7244 [VDG] Handle the unlabelled pockets
  WalletWasabi.Fluent/Helpers/CoinHelpers.cs
  WalletWasabi.Fluent/Helpers/CoinPocketHelper.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/LabelSelectionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/LabelViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Send/PrivacyControlView.axaml
  WalletWasabi.Tests/UnitTests/UserInterfaceTest/PocketSelectionTests.cs
Labels: size/L

#7250 Update NetworkSettingsTabViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/NetworkSettingsTabViewModel.cs
Labels: size/XS

#7253 [VDG] [Fluent] [Trivial] Remove empty WalletTilesPlaceholder.axaml.cs file
  WalletWasabi.Fluent/Views/Wallets/Home/WalletTilesPlaceholder.axaml.cs
Labels: size/XS

#7204 [Fluent] Implement Wallet Stats
  WalletWasabi.Fluent/Controls/PreviewItem.axaml
  WalletWasabi.Fluent/Controls/PreviewItem.axaml.cs
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletStatsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletStatsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletStatsView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
Labels: size/L

#7252 [Trivial] Remove redundant casts
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinsHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/TransactionHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
Labels: size/S

#7260 [VDG] Custom Fee - accept chars but show error
  WalletWasabi.Fluent/ViewModels/Wallets/Send/AdvancedSendOptionsViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Send/AdvancedSendOptionsView.axaml
Labels: size/XS

#7264 Add .editorconfig in ZXing folder
  WalletWasabi.Fluent/GlobalSuppressions.cs
  WalletWasabi.Fluent/ZXing/.editorconfig
Labels: size/S

#7273 [Trivial] Fix typos
  WalletWasabi.Fluent/Models/Windows/DirectShow.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/Blockchain/Transactions/SmartTransaction.cs
  WalletWasabi/WabiSabi/Models/Serialization/GenericInterfaceJsonConverter.cs
Labels: size/S

#7274 [Trivial] Convert to file-scoped namespaces
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/WalletCoinsView.axaml.cs
Labels: size/L

#7276 Update supported operating systems
  WalletWasabi.Documentation/WasabiCompatibility.md
Labels: size/XS

#7284 [Trivial] Improve confusing log message
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Labels: size/XS

#7267 Update PrivacyLevel on Anon Score Target change
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
Labels: size/XS

#7272 [Trivial] Mark method as a fact
  WalletWasabi.Tests/UnitTests/UserInterfaceTest/PocketSelectionTests.cs
Labels: size/M

#7288 [`SoloCoinJoinTestAsync`] Bump timeout.
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
Labels: size/S

#7295 [Trivial] User 'Assert.Equal' instead of 'Assert.True'
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
Labels: size/XS

#7283 Update bug-report.md
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: size/XS

#7287 [VDG] Wallet coins - Remove redundant scrollbars
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/WalletCoinsView.axaml
Labels: size/XS

#7162 [Fluent] macOS/KDE-Linux default AppMenu items replacement
  WalletWasabi.Fluent/App.axaml
  WalletWasabi.Fluent/ViewModels/ApplicationViewModel.cs
  WalletWasabi.Fluent/ViewModels/HelpAndSupport/AboutViewModel.cs
  WalletWasabi.Fluent/Views/HelpAndSupport/AboutView.axaml
Labels: size/M

#6961 [VDG] [Fluent] Optimize HistoryTable and ReceiveAddresses labels column
  WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
  WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveAddressesView.axaml
Labels: size/M

#7265 Add CoinJoinFeeRateAverage API request
  WalletWasabi.Backend/Controllers/WabiSabiController.cs
  WalletWasabi.Backend/Startup.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiApiApplicationFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/RoundStateUpdaterTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/SerializationTests.cs
  WalletWasabi/WabiSabi/Backend/PostRequests/IWabiSabiApiRequestHandler.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Statistics/CoinJoinFeeRateStat.cs
  WalletWasabi/WabiSabi/Backend/Statistics/CoinJoinFeeRateStatStore.cs
  WalletWasabi/WabiSabi/Client/ArenaClient.cs
  WalletWasabi/WabiSabi/Client/RoundStateUpdater.cs
  WalletWasabi/WabiSabi/Client/WabiSabiHttpApiClient.cs
  WalletWasabi/WabiSabi/CoordinatorParameters.cs
  WalletWasabi/WabiSabi/Models/CoinJoinFeeRateAverage.cs
  WalletWasabi/WabiSabi/Models/RoundStateResponse.cs
  WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
Labels: size/L

#7303 IsLikelyCoinjoin -> IsOwnCoinjoin
  WalletWasabi.Fluent/Rpc/WasabiJsonRpcService.cs
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinsHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
  WalletWasabi/Blockchain/TransactionProcessing/ProcessedResult.cs
  WalletWasabi/Blockchain/Transactions/SmartTransaction.cs
  WalletWasabi/Blockchain/Transactions/TransactionHistoryBuilder.cs
  WalletWasabi/Blockchain/Transactions/TransactionSummary.cs
  WalletWasabi/Extensions/NBitcoinExtensions.cs
Labels: size/M

#7168 [Fluent] Redesign TagControl delete button.
  WalletWasabi.Fluent/Controls/TagControl.axaml
  WalletWasabi.Fluent/Controls/TagsBox.axaml
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/Styles/Themes/Base.axaml
Labels: size/L

#7304 [VDG] Start generating suggestion before dialog is closing
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
Labels: size/XS

#7294 Ignore rounds w/ too high min allowed output
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/XS

#7307 Fix Send Address white space issue
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
Labels: size/XS

#7296 [VDG] Send - reset when the user navigates back from preview screen
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionInfo.cs
Labels: size/S

#7258 Move Wallet Creation options to the beginning of the Add wallet flow
  WalletWasabi.Fluent/Helpers/WalletHelpers.cs
  WalletWasabi.Fluent/Models/WalletCreationOption.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/SelectWalletCreationOptionViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/WalletNamePageViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/AddWalletPageView.axaml
  WalletWasabi.Fluent/Views/AddWallet/SelectWalletCreationOptionView.axaml
  WalletWasabi.Fluent/Views/AddWallet/WalletNamePageView.axaml
  WalletWasabi.Fluent/Views/AddWallet/WalletNamePageView.axaml.cs
Labels: size/L

#7289 [Trivial] Remove Width/Height cap in CrashReportWindow
  WalletWasabi.Fluent/CrashReport/Views/CrashReportWindow.axaml
Labels: size/XS

#7281 Update TransactionPreviewViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
Labels: size/XS

#7323 Fix NRE when sending
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
Labels: size/XS

#7322 do not block dialog while BnB is running
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
Labels: size/XS

#7314 "Rescan" instead of "Continue" in Add HW Wallet view
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/ConnectHardwareWalletViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/HardwareWallet/ConnectHardwareWalletView.axaml
Labels: size/XS

#7220 Introduce "Lesser" suggestions
  WalletWasabi.Fluent/ViewModels/Wallets/Send/ChangeAvoidanceSuggestionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacySuggestionsFlyoutViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Tests/UnitTests/Blockchain/TransactionBuilding/BranchAndBoundTests.cs
  WalletWasabi.Tests/UnitTests/Blockchain/TransactionBuilding/ChangelessTransactionCoinSelectorTests.cs
  WalletWasabi/Blockchain/TransactionBuilding/BnB/LessSelectionStrategy.cs
  WalletWasabi/Blockchain/TransactionBuilding/BnB/MoreSelectionStrategy.cs
  WalletWasabi/Blockchain/TransactionBuilding/BnB/SelectionStrategy.cs
  WalletWasabi/Blockchain/TransactionBuilding/BranchAndBound.cs
  WalletWasabi/Blockchain/TransactionBuilding/ChangelessTransactionCoinSelector.cs
Labels: size/L

#7257 Fix WW 2.0 backend never connects with Tor on (Windows 7)
  WalletWasabi/Tor/Socks5/TorTcpConnectionFactory.cs
Labels: size/S

#7316 Add coord script if all alices ready
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
  WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
Labels: size/M

#7285 [VDG] Hide Send button for watch only wallets
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
Labels: size/XS

#7348 Fix self coinjoining with multiple wallets display
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
Labels: size/S

#7343 [VDG] ContentArea Layout problem fix
  WalletWasabi.Fluent/Controls/ContentArea.axaml
Labels: size/XS

#7349 Rename Privacy Boost label to Coinjoins
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinsHistoryItemViewModel.cs
Labels: size/XS

#7351 Simplify condition of checking coord fee script reuse
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/XS

#7346 [Fluent] Use monospaced font for legal text.
  WalletWasabi.Fluent/Views/AddWallet/LegalDocumentsView.axaml
Labels: size/XS

#7332 Bnb: Throw exception at cancellation request
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacySuggestionsFlyoutViewModel.cs
  WalletWasabi/Blockchain/TransactionBuilding/BranchAndBound.cs
  WalletWasabi/Blockchain/TransactionBuilding/ChangelessTransactionCoinSelector.cs
Labels: size/M

#7353 Password finder
  WalletWasabi.Fluent/Views/Login/PasswordFinder/PasswordFinderIntroduceView.axaml
  WalletWasabi.Fluent/Views/Login/PasswordFinder/SearchPasswordView.axaml
Labels: size/XS

#7352 [VDG] Terms & Conditions - Polite caption
  WalletWasabi.Fluent/Views/AddWallet/TermsAndConditionsView.axaml
Labels: size/XS

#7358 Delete empty GlobalUsings.cs file
  WalletWasabi.Fluent.Generators/GlobalUsings.cs
Labels: size/XS

#7354 [VDG] History - Fix out of range ex
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinsHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/HistoryItemViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/TransactionHistoryItemViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
Labels: size/S

#7312 Added application-wide style for ToolTip to prevent text clipping
  WalletWasabi.Fluent/Styles/Styles.axaml
  WalletWasabi.Fluent/Styles/ToolTip.axaml
Labels: size/XS

#7368 [VDG] [Fluent] Update Avalonia behaviors package to latest 0.10.12.2 release
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/Behaviors/AttachedToVisualTreeBehavior.cs
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
Labels: size/M

#7342 [VDG] Add new wallet - Automatically generated default wallet name
  WalletWasabi.Fluent/Behaviors/TextBoxSelectAllTextBehavior.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/WalletNamePageViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/WalletNamePageView.axaml
Labels: size/S

#7334 [VDG] Remove redundant captions and labels
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/WalletNamePageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/CreatePasswordDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/LoginViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/PasswordFinderIntroduceViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/VerifyRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/Create/ConfirmRecoveryWordsView.axaml
  WalletWasabi.Fluent/Views/AddWallet/RecoverWalletView.axaml
  WalletWasabi.Fluent/Views/AddWallet/WalletNamePageView.axaml
  WalletWasabi.Fluent/Views/Dialogs/AdvancedRecoveryOptionsView.axaml
  WalletWasabi.Fluent/Views/HelpAndSupport/AboutView.axaml
  WalletWasabi.Fluent/Views/Login/LoginView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
  WalletWasabi.Fluent/Views/Wallets/VerifyRecoveryWordsView.axaml
Labels: size/M

#7365 Fix server-side exception
  WalletWasabi/BitcoinCore/Mempool/MempoolMirror.cs
Labels: size/XS

#7374 Fix the CoinJoinWithBlameRoundTestAsync
  WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
Labels: size/XS

#7306 When To Mix - CoinJoin Profiles
  WalletWasabi.Backend/Controllers/WabiSabiController.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/ConfirmRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/CoinJoinProfileViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/CoinJoinProfilesViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/EconomyCoinJoinProfile.cs
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/ManualCoinJoinProfile.cs
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/PrivateCoinJoinProfile.cs
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/SpeedyCoinJoinProfile.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/ManualCoinJoinProfileDialogViewModel.cs
  WalletWasabi.Fluent/Views/CoinJoinProfiles/CoinJoinProfileControl.axaml
  WalletWasabi.Fluent/Views/CoinJoinProfiles/CoinJoinProfileControl.axaml.cs
  WalletWasabi.Fluent/Views/CoinJoinProfiles/CoinJoinProfilesView.axaml
  WalletWasabi.Fluent/Views/CoinJoinProfiles/CoinJoinProfilesView.axaml.cs
  WalletWasabi.Fluent/Views/Dialogs/ManualCoinJoinProfileDialogView.axaml
  WalletWasabi.Fluent/Views/Dialogs/ManualCoinJoinProfileDialogView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/WalletSettingsView.axaml
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/RoundStateUpdaterTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/SerializationTests.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/Helpers/Constants.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
  WalletWasabi/WabiSabi/Backend/Statistics/CoinJoinFeeRateStatStore.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinTrackerFactory.cs
  WalletWasabi/WabiSabi/Client/RoundStateUpdater.cs
  WalletWasabi/WabiSabi/Models/CoinJoinFeeRateAverage.cs
  WalletWasabi/WabiSabi/Models/CoinJoinFeeRateMedian.cs
  WalletWasabi/WabiSabi/Models/RoundStateResponse.cs
Labels: size/XL

#7367 Check end of stream in `HttpMessageHelper`.
  WalletWasabi/Tor/Http/Helpers/HttpMessageHelper.cs
Labels: size/S

#7372 [VDG] [Fluent] Remove wallet balance chart tile view model
  WalletWasabi.Fluent/Helpers/TileHelper.cs
  WalletWasabi.Fluent/Models/TimePeriodOption.cs
  WalletWasabi.Fluent/Morph/PolyLine.cs
  WalletWasabi.Fluent/Morph/PolyLineMorph.cs
  WalletWasabi.Fluent/Styles/BalanceLineChart.axaml
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/LineChartAnimatorViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/LineChartPlaceholderViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/TimePeriodOptionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletBalanceChartTileViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceChart/WalletBalanceChartLargeTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceChart/WalletBalanceChartLargeTileView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceChart/WalletBalanceChartMediumTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceChart/WalletBalanceChartMediumTileView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceChart/WalletBalanceChartWideTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceChart/WalletBalanceChartWideTileView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceChartTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceChartTileView.axaml.cs
Labels: size/XL

#7383 Increase MinGapLimit from 63 to 100 at recovery
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
Labels: size/XS

#7388 Mark FN integration EXPERIMENTAL
  WalletWasabi.Fluent/Views/Settings/BitcoinTabSettingsView.axaml
Labels: size/XS

#7391 [VDG] [Trivial] Reorder items for wallet stats
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletStatsView.axaml
Labels: size/S

#7377 Simple warning fixes
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/CoinJoinDetailsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
Labels: size/XS

#7381 De-select at Privacy Toggle
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
Labels: size/S

#7394 Fix CA1416 Validate platform compatibility warnings
  WalletWasabi.Fluent/Models/WebcamQrReader.cs
  WalletWasabi.Fluent/Models/Windows/DirectShow.cs
  WalletWasabi.Fluent/Models/Windows/WindowsCapture.cs
Labels: size/S

#7398 Wallet Stats - null warning fixes
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletStatsViewModel.cs
Labels: size/XS

#7400 Trivial: fix design time.
  WalletWasabi.Fluent/App.axaml.cs
Labels: size/S

#7393 Add proper images to CoinJoin profiles
  WalletWasabi.Fluent/Assets/CoinJoinProfiles/cost.png
  WalletWasabi.Fluent/Assets/CoinJoinProfiles/private.png
  WalletWasabi.Fluent/Assets/CoinJoinProfiles/speed.png
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/CoinJoinProfileViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/CoinJoinProfilesViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/EconomicCoinJoinProfileViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/ManualCoinJoinProfileViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/PrivateCoinJoinProfileViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/SpeedyCoinJoinProfileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/ManualCoinJoinProfileDialogViewModel.cs
  WalletWasabi.Fluent/Views/CoinJoinProfiles/CoinJoinProfileControl.axaml
  WalletWasabi.Fluent/Views/CoinJoinProfiles/CoinJoinProfilesView.axaml
  WalletWasabi.Fluent/Views/Dialogs/ManualCoinJoinProfileDialogView.axaml
Labels: size/L

#7397 [VDG] Wallet Stats copy
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletStatsViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletStatsView.axaml
Labels: size/S

#7389 [VDG] Forgot password visible after incorrect password
  WalletWasabi.Fluent/ViewModels/Login/LoginViewModel.cs
  WalletWasabi.Fluent/Views/Login/LoginView.axaml
Labels: size/XS

#7409 [VDG] fix logic for `SetUsedLabel()`
  WalletWasabi.Fluent/ViewModels/Wallets/Send/LabelSelectionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
Labels: size/S

#7402 [VDG] [Fluent] Fix small tiles layout
  WalletWasabi.Fluent/Helpers/TileHelper.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
Labels: size/XS
