Repository WalletWasabi/WalletWasabi, pull requests merged in 2022-10, with the labels that each got.

#9240 Disable Tor's `UseEntryGuards` feature
  WalletWasabi.Tests/UnitTests/Tor/TorSettingsTests.cs
  WalletWasabi/Tor/TorSettings.cs
Labels: size/XS

#9035 Revert "[Tor] Experiment no.1"
  WalletWasabi/WabiSabi/Client/ArenaClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/S

#9233 [VDG] Dont add spacing on TitleBarView on linuxes
  WalletWasabi.Fluent/Views/Shell/TitleBarView.axaml
Labels: size/S

#9244 [VDG] MusicBox - simplify messages
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
Labels: size/S

#9219 compatibility: update Tails & Whonix
  WalletWasabi.Documentation/WasabiCompatibility.md
Labels: size/XS

#9247 [Backend] Increase Fee cache expiration time
  WalletWasabi/BitcoinCore/Rpc/CachedRpcClient.cs
Labels: size/XS

#9222 [Trivial] Update Wasabi dependencies
  WalletWasabi.Documentation/WasabiCompatibility.md
Labels: size/XS

#9207 Add a link collection about useful status pages
  WalletWasabi.Documentation/ServiceStatus.md
Labels: size/S

#9256 Revert "Disable Tor's `UseEntryGuards` feature"
  WalletWasabi.Tests/UnitTests/Tor/TorSettingsTests.cs
  WalletWasabi/Tor/TorSettings.cs
Labels: size/XS

#9255 When load balancing make 2.0.0 select the wrong round so newer versions prioritize the good one
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/S

#9195 Liquidity clue abstraction
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinTrackerFactory.cs
  WalletWasabi/WabiSabi/Client/LiquidityClueHelper.cs
Labels: size/L

#9281 [Trivial] Fix tooltip about auto-coinjoin start if the balance is less than PlebStopThreshold
  WalletWasabi.Fluent/Views/Wallets/CoinJoinSettingsView.axaml
  WalletWasabi/Blockchain/Keys/KeyManager.cs
Labels: size/XS

#9254 [VDG] move things to `TransactionInfo.cs`
  WalletWasabi.Fluent/Helpers/TransactionHelpers.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/AddressEntryDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/LabelEntryDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/ChangeAvoidanceSuggestionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacySuggestionsFlyoutViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionInfo.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionSummaryViewModel.cs
Labels: size/L

#9232 [VDG] Fix privacy bar showing as empty space if there's no privacy data.
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyBarViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyBar/PrivacyBar.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyControlTileView.axaml
Labels: size/M

#9288 Updated docs links
  WalletWasabi.Backend/wwwroot/index.html
Labels: size/S

#9265 Minor refactor and remove leftovers.
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi/Helpers/TxOutEqualityComparer.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinTrackerFactory.cs
  WalletWasabi/WabiSabi/Client/LiquidityClueHelper.cs
  WalletWasabi/WabiSabi/Client/LiquidityClueProvider.cs
Labels: size/L

#9293 Remove unused StringFormat in LoadingControl StatusText binding.
  WalletWasabi.Fluent/ViewModels/Wallets/LoadingViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/LoadingControl.axaml
Labels: size/XS

#9302 [VDG] Update TreeDataGrid to NuGet version 0.10.18
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
Labels: size/S

#9301 [Trivial] Fix some links on the website
  WalletWasabi.Backend/wwwroot/about.html
  WalletWasabi.Backend/wwwroot/contribution.html
  WalletWasabi.Backend/wwwroot/faq.html
Labels: size/XS

#9297 Fix broken link on website
  WalletWasabi.Backend/wwwroot/contribution.html
Labels: size/M

#9304 Log less in tx build - it is called a many times
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
Labels: size/S

#9290 Revert "Updated docs links"
  WalletWasabi.Backend/wwwroot/index.html
Labels: size/S

#9307 [Trivial] Clarify tx build log message
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
Labels: size/XS

#9264 Tor: Increase `MaxCircuitDirtiness`
  WalletWasabi.Tests/UnitTests/Tor/TorSettingsTests.cs
  WalletWasabi/Tor/TorSettings.cs
Labels: size/XS

#9313 Slow down requests when not CoinJoining
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WabiSabi/Client/RoundStateAwaiters/RoundStateUpdater.cs
Labels: size/S

#9306 Adjust MemoryCache expire dates
  WalletWasabi/BitcoinCore/Rpc/CachedRpcClient.cs
Labels: size/S

#9150 [VDG] Refactor UI update triggers
  WalletWasabi.Fluent/Helpers/TileHelper.cs
  WalletWasabi.Fluent/Models/UiTriggers.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/TransactionDetailsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinsHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/TransactionHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletBalanceTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
Labels: size/L

#9289 [VDG] Prebuild txn during pocket selection
  WalletWasabi.Fluent/Extensions/PocketExtensions.cs
  WalletWasabi.Fluent/Helpers/TransactionHelpers.cs
  WalletWasabi.Fluent/Models/Pocket.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/LabelSelectionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Tests/UnitTests/UserInterfaceTest/PocketSelectionTests.cs
  WalletWasabi/Blockchain/Transactions/AllTransactionStore.cs
  WalletWasabi/Blockchain/Transactions/EmptyTransactionStore.cs
  WalletWasabi/Blockchain/Transactions/ITransactionStore.cs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
  WalletWasabi/Extensions/NBitcoinExtensions.cs
Labels: size/L

#9305 [VDG] Make USD amounts coherent
  WalletWasabi.Fluent/Controls/DualCurrencyEntryBox.axaml.cs
  WalletWasabi.Fluent/Converters/MoneyConverters.cs
  WalletWasabi.Fluent/Extensions/CurrencyExtensions.cs
  WalletWasabi.Fluent/Helpers/TextHelpers.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/BtcPriceTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletBalanceTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/ChangeAvoidanceSuggestionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionSummaryViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/BtcPriceTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/ChangeAvoidanceSuggestionControl.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Labels: size/L

#9226 [VDG] fix privacy suggestions crash
  WalletWasabi.Fluent/Behaviors/BindableFlyoutOpenBehavior.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/LoadingSuggestionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacySuggestionsFlyoutViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Send/LoadingSuggestionView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/LoadingSuggestionView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml
Labels: size/L

#9319 [VDG] [Trivial] Set the payment amount instead of zero as default during prebuild
  WalletWasabi.Fluent/Helpers/TransactionHelpers.cs
Labels: size/XS

#9326 Remove unused property and parameters
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/Wallets/IWallet.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/XS

#9327 Replace Identifier with WalletName in IWallet
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WabiSabi/LoggerTools.cs
  WalletWasabi/Wallets/IWallet.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/S

#9325 Use Wallet.AnonScoreTarget instead of KeyManager.AnonScoreTarget
  WalletWasabi.Fluent/Helpers/CoinPocketHelper.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinSettingsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyBarItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletBalanceTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/M

#9283 Remove old NuGet source for Avalonia
  NuGet.Config
Labels: size/XS

#9303 Implement CancellationToken in StepTransactionSigningTests,StepOutputRegistrationTests and BobClientTests
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
  WalletWasabi/Bases/PeriodicRunner.cs
  WalletWasabi/Helpers/EventAwaiter.cs
  WalletWasabi/Helpers/EventsAwaiter.cs
Labels: size/L

#9320 Use fallback mechanism by default
  WalletWasabi.Fluent/Global.cs
Labels: size/S

#9333 [VDG] Hide MusicBox always if the wallet is watch-only
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
Labels: size/XS

#9198 [VDG] Fix hidden pocket handling
  WalletWasabi.Fluent/ViewModels/Wallets/Send/LabelSelectionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
  WalletWasabi.Tests/UnitTests/UserInterfaceTest/PocketSelectionTests.cs
Labels: size/L

#9343 Update NBitcoin version
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/Helpers/TransactionHelpers.cs
  WalletWasabi.Fluent/packages.lock.json
  WalletWasabi.Packager/packages.lock.json
  WalletWasabi.Tests/Helpers/BitcoinFactory.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/PayjoinTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi/Blockchain/Analysis/CoinjoinAnalyzer.cs
  WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs
  WalletWasabi/Blockchain/TransactionOutputs/CoinsView.cs
  WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
  WalletWasabi/Blockchain/Transactions/SmartTransaction.cs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
  WalletWasabi/WabiSabi/Client/AliceClient.cs
  WalletWasabi/WalletWasabi.csproj
  WalletWasabi/packages.lock.json
Labels: size/L

#9341 [VDG] fix visibility of musicbox on hover
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
Labels: size/XS

#9112 Packager: Make packaging work on linux
  WalletWasabi.Packager/Program.cs
Labels: size/S

#9364 [VDG] improve Coinjoin Strategy Settings title
  WalletWasabi.Fluent/ViewModels/Dialogs/ManualCoinJoinProfileDialogViewModel.cs
Labels: size/XS

#9367 [CI] Increase timeouts
  WalletWasabi.Tests/UnitTests/BitcoinCore/P2pBasedTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/CredentialDependencyTests.cs
Labels: size/XS

#9363 Replace `AtomicGetOrCreate` with `IdempotenceRequestCache` (take 2)
  WalletWasabi.Backend/Controllers/BlockchainController.cs
  WalletWasabi.Backend/Controllers/WabiSabi/IdempotencyRequestCache.cs
  WalletWasabi.Backend/Controllers/WabiSabiController.cs
  WalletWasabi.Backend/Startup.cs
  WalletWasabi.Tests/RegressionTests/BackendTests.cs
  WalletWasabi.Tests/RegressionTests/IdempotencyRequestCacheStressTests.cs
  WalletWasabi.Tests/UnitTests/Cache/IdempotencyRequestCacheTests.cs
  WalletWasabi.Tests/UnitTests/MemoryTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/Startup.cs
  WalletWasabi/BitcoinCore/Rpc/CachedRpcClient.cs
  WalletWasabi/BitcoinCore/Rpc/RpcClientBase.cs
  WalletWasabi/Blockchain/Blocks/BlockNotifier.cs
  WalletWasabi/Cache/IdempotencyRequestCache.cs
  WalletWasabi/Extensions/MemoryExtensions.cs
  WalletWasabi/Wallets/SmartBlockProvider.cs
Labels: size/XL

#9368 Store MasterKey instead of Decrypt every time
  WalletWasabi/WabiSabi/Client/KeyChain.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/S

#9366 [Trivial] Rename `UserLabels` to `Recipient`
  WalletWasabi.Fluent/Helpers/TransactionHelpers.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/ChangeAvoidanceSuggestionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/LabelSelectionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionInfo.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionSummaryViewModel.cs
  WalletWasabi.Tests/UnitTests/UserInterfaceTest/PocketSelectionTests.cs
Labels: size/M

#9372 [Trivial] Clarify using Wasabi on Tails
  WalletWasabi.Documentation/WasabiCompatibility.md
Labels: size/XS

#9317 [VDG] PrivacyBar - fine tuning
  WalletWasabi.Fluent/Styles/Themes/Base.axaml
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyBarViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyBar/PrivacyBar.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyControlTileView.axaml
Labels: size/L

#9149 deb package: Recommend `policykit-1`
  WalletWasabi.Packager/Program.cs
Labels: size/XS

#9373 [VDG] Remove `Throttle` from `UiTriggers`
  WalletWasabi.Fluent/Models/UiTriggers.cs
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinSettingsViewModel.cs
Labels: size/S

#9359 [VDG] Fix privacy bar not updating on wallet open
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyBarViewModel.cs
Labels: size/M

#9371 [Trivial] Edit message when adding password
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/ConfirmRecoveryWordsViewModel.cs
Labels: size/XS

#9358 [VDG][Trivial] Remove dead code in WalletBalanceTileViewModel.cs
  WalletWasabi.Fluent/Extensions/CurrencyExtensions.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletBalanceTileViewModel.cs
Labels: size/M

#9360 [VDG] Fix privacy ring rendering twice
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingViewModel.cs
Labels: size/M

#9381 [VDG] Prevent privacy ring dialog from opening for an empty wallet
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
Labels: size/XS

#9383 [VDG] Fix Privacy Ring References layout problem
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyRing/PrivacyRingView.axaml
Labels: size/XS

#9380 fix minor typo
  WalletWasabi.Backend/wwwroot/faq.html
Labels: size/XS

#9387 [VDG] Reduce Privacy Ring Preview Delay
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyRing/PrivacyRingView.axaml
Labels: size/XS

#9385 [Trivial] Rename variable
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
Labels: size/XS

#9388 [VDG] Fix transaction doesn't appear (only notification)
  WalletWasabi.Fluent/Models/UiTriggers.cs
Labels: size/XS

#9392 [VDG] fix possible called from invalid thread
  WalletWasabi.Fluent/Models/UiTriggers.cs
Labels: size/XS

#9378 UnexpectedRoundPhaseException shouldn't be a warning
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/M

#9407 Update version and website v2.0.2
  WalletWasabi.Backend/wwwroot/index.html
  WalletWasabi/Helpers/Constants.cs
Labels: size/S

#9410 Add SemiPrivateThreshold constant
  WalletWasabi.Fluent/Helpers/CoinHelpers.cs
  WalletWasabi.Fluent/Helpers/CoinPocketHelper.cs
  WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs
  WalletWasabi/Helpers/Constants.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/S

#9391 [Trivial][VDG] Remove empty wallet message
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
Labels: size/S

#9374 Fix MempoolMirror's ArgumentException
  WalletWasabi.Tests/UnitTests/MempoolMirrorTests/MempoolMirrorTests.cs
  WalletWasabi/BitcoinCore/Mempool/MempoolMirror.cs
Labels: size/L

#9413 Correct log message when building transaction
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
Labels: size/XS
