Repository WalletWasabi/WalletWasabi, pull requests merged in 2022-09, with the labels that each got.

#9028 Fix warnings in Backend project (take 3)
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Backend/InitConfigStartupTask.cs
  WalletWasabi.Backend/Startup.cs
Labels: size/L

#8905 [VDG] Reveal privacy item when mouse is over it for a while
  WalletWasabi.Fluent/Controls/PrivacyContentControl.axaml
  WalletWasabi.Fluent/Controls/PrivacyContentControl.axaml.cs
  WalletWasabi.Fluent/Extensions/ObservableExtension.cs
  WalletWasabi.Fluent/Extensions/ObservableMixin.cs
  WalletWasabi.Fluent/Extensions/PrivacyModeHelper.cs
  WalletWasabi.Fluent/TreeDataGrid/TreeDataGridPrivacyTextCell.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletBalanceTileViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/Columns/LabelsColumnView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceTileView.axaml
Labels: size/L

#9045 [VDG] [Trivial] Use ObserveOn correctly
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
Labels: size/XS

#9037 [VDG] Privacy Ring + Privacy Bar improvements
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyControlTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyRing/PrivacyRingView.axaml
Labels: size/M

#9050 Remove unused Wallet.InitializingChanged static event
  WalletWasabi/Wallets/Wallet.cs
Labels: size/XS

#9043 [Trivial] Use expression body for lambda expressions
  WalletWasabi.Fluent/Global.cs
  WalletWasabi.Fluent/Models/Windows/DirectShow.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/ShowQrCameraDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/StatusIcon/StatusIconViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModelBase.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/IWebHostBuilderExtensions.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiApiApplicationFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
Labels: size/M

#9057 Bypass WitnessAlreadyProvided exception
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/S

#9053 [backend] Make sure address reused coins won't cause an error
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/CoinVerifierTests.cs
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
  WalletWasabi/WabiSabi/Backend/Banning/CoinVerifier.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/M

#9033 Make sure timeouts are not kicking in early
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/XS

#9067 `TorTcpConnectionFactory`: Improve logging. TTL expired is not an err…
  WalletWasabi/Tor/Socks5/TorTcpConnectionFactory.cs
Labels: size/XS

#9068 [VDG] Hide MusicBox when wallet is private
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
Labels: size/M

#9054 Anonymity computation again
  WalletWasabi.Tests/Helpers/AnalyzedTransaction/AnalyzedTransaction.cs
  WalletWasabi.Tests/Helpers/AnalyzedTransaction/ForeignOutput.cs
  WalletWasabi.Tests/Helpers/AnalyzedTransaction/WalletOutput.cs
  WalletWasabi.Tests/UnitTests/BlockchainAnalysis/CoinJoinAnonscoreTests.cs
  WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs
  WalletWasabi/Blockchain/Analysis/CoinjoinAnalyzer.cs
  WalletWasabi/Blockchain/TransactionOutputs/WalletVirtualInput.cs
  WalletWasabi/Extensions/LinqExtensions.cs
Labels: size/L

#9034 Remove `default` CTs from Tor code
  WalletWasabi/Tor/Control/TorControlClient.cs
  WalletWasabi/Tor/Control/TorControlReplyReader.cs
  WalletWasabi/Tor/Http/Extensions/HttpResponseMessageExtensions.cs
  WalletWasabi/Tor/Http/Helpers/HttpMessageHelper.cs
  WalletWasabi/Tor/Http/IHttpClient.cs
  WalletWasabi/Tor/Socks5/TorTcpConnectionFactory.cs
  WalletWasabi/Tor/TorProcessManager.cs
  WalletWasabi/WebClients/Wasabi/WasabiClient.cs
Labels: size/M

#9059 [trivial] improve coinjoin strategy text a bit
  WalletWasabi.Fluent/Views/CoinJoinProfiles/CoinJoinProfilesView.axaml
Labels: size/XS

#9086 Remove unused `GetExchangeRateAsync` method
  WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
  WalletWasabi/WebClients/Wasabi/WasabiClient.cs
Labels: size/M

#9077 [VDG] Correctly hide MusicBox controls when wallet is private
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/MusicControlsView.axaml
Labels: size/M

#9072 `UpgradeTorBinaries`: Add support for GEOIP upgrade
  WalletWasabi.Documentation/Guides/UpgradeTorDaemons.md
  WalletWasabi/Microservices/Binaries/UpgradeTorBinaries.ps1
Labels: size/M

#9079 [BLOCKS DL] Decrease min p2p dl timeout
  WalletWasabi/Helpers/RuntimeParams.cs
  WalletWasabi/Wallets/P2pBlockProvider.cs
Labels: size/S

#8924 Support Taproot filter building
  WalletWasabi.Backend/Controllers/BatchController.cs
  WalletWasabi.Backend/Controllers/BlockchainController.cs
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Fluent/Global.cs
  WalletWasabi.Fluent/ViewModels/Wallets/LoadingViewModel.cs
  WalletWasabi.Tests/RegressionTests/BackendTests.cs
  WalletWasabi.Tests/UnitTests/BitcoinCore/IndexBuilderServiceTests.cs
  WalletWasabi.Tests/UnitTests/SmartHeaderTests.cs
  WalletWasabi/BitcoinCore/Rpc/CachedRpcClient.cs
  WalletWasabi/BitcoinCore/Rpc/RpcClientBase.cs
  WalletWasabi/Blockchain/BlockFilters/IndexBuilderService.cs
  WalletWasabi/Blockchain/BlockFilters/IndexType.cs
  WalletWasabi/Blockchain/BlockFilters/IndexTypeConverter.cs
  WalletWasabi/Blockchain/BlockFilters/StartingFilters.cs
  WalletWasabi/Blockchain/Blocks/SmartHeader.cs
Labels: size/L

#8916 [VDG] Add transaction search to SearchBar
  WalletWasabi.Fluent/Behaviors/ScrollToSelectedItemBehavior.cs
  WalletWasabi.Fluent/Controls/PrivacyContentControl.axaml.cs
  WalletWasabi.Fluent/Extensions/AvaloniaExtensions.cs
  WalletWasabi.Fluent/Extensions/DynamicDataExtensions.cs
  WalletWasabi.Fluent/Extensions/ObservableExtensions.cs
  WalletWasabi.Fluent/Extensions/TimeSpanExtensions.cs
  WalletWasabi.Fluent/Extensions/TransactionSummaryExtensions.cs
  WalletWasabi.Fluent/Helpers/PrivacyModeHelper.cs
  WalletWasabi.Fluent/TreeDataGrid/TreeDataGridPrivacyTextCell.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/SearchBarDesignViewModel.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/SearchBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/SearchItemGroup.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/SettingsSearchSource.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/Sources/ActionsSearchSource.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/Sources/CompositeSearchSource.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/Sources/ISearchSource.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/Sources/SearchSource.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/Sources/TransactionsSearchSource.cs
  WalletWasabi.Fluent/Views/SearchBar/SearchBarDropdown.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
Labels: size/L

#9097 Fix tx processing
  WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs
  WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
Labels: size/XS

#9064 [VDG] Recovery Words improvements
  WalletWasabi.Fluent/Views/AddWallet/Create/RecoveryWordsView.axaml
Labels: size/M

#9119 [VDG] clarify coinjoin ban tooltip
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinViewModel.cs
Labels: size/XS

#9117 use BTC as unit in CoinJoinClient Log
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/XS

#9129 [trivial] `WabiSabiHttpApiClient`: Add info about action
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/CredentialDependencyTests.cs
  WalletWasabi/WabiSabi/Client/CredentialDependencies/DependencyGraph.cs
  WalletWasabi/WabiSabi/Client/WabiSabiHttpApiClient.cs
Labels: size/S

#9096 [VDG] Privacy bar and Privacy Ring render threshold
  WalletWasabi.Fluent/ViewModels/UIConstants.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyBarItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyBar/PrivacyBar.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyBar/PrivacyBar.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyControlTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyRing/PrivacyRingView.axaml
Labels: size/L

#9138 [VDG] Fix Avalonia previewer
  WalletWasabi.Fluent.Desktop/Extensions/AppBuilderExtension.cs
Labels: size/XS

#9139 Delete BackendDeployment.md
  WalletWasabi.Documentation/BackendDeployment.md
Labels: size/XL

#9094 Put flags into the Config file
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/CoinVerifierTests.cs
  WalletWasabi/WabiSabi/Backend/Banning/CoinVerifier.cs
  WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
Labels: size/M

#9142 Fix `SocketException`s being thrown when using `DefaultCircuit`
  WalletWasabi/Tor/Socks5/Pool/TorHttpPool.cs
  WalletWasabi/Tor/Socks5/TorTcpConnectionFactory.cs
  WalletWasabi/Tor/TorMonitor.cs
Labels: size/S

#9128 `TorHttpPool`: Do not log OperationCancelledException
  WalletWasabi/Tor/Socks5/Pool/TorHttpPool.cs
Labels: size/XS

#9121 wix3: Bugfix to avoid VS2022 crash
  WalletWasabi.WindowsInstaller/WalletWasabi.WindowsInstaller.wixproj
Labels: size/XS

#9144 Improve logging with regard to TTL expired.
  WalletWasabi/Tor/Socks5/Pool/TorHttpPool.cs
Labels: size/XS

#9133 [VDG] Restart with shutdown prevention
  WalletWasabi.Fluent/ApplicationStateManager.cs
  WalletWasabi.Fluent/CrashReport/ViewModels/CrashReportWindowViewModel.cs
  WalletWasabi.Fluent/Helpers/AppLifetimeHelper.cs
  WalletWasabi.Fluent/Providers/IMainWindowService.cs
  WalletWasabi.Fluent/ViewModels/ApplicationViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/ShuttingDownViewModel.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/Settings/RestartViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/SettingsPageViewModel.cs
Labels: size/M

#9137 throttle newfilterprocessed event
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
Labels: size/S

#9147 [VDG] [trivial] lowercase writing in cj details
  WalletWasabi.Fluent/Views/Wallets/Home/History/Details/CoinJoinsDetailsView.axaml
Labels: size/XS

#9140 [VDG] make PrivacyBar not clickable when wallet is empty
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyBarViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyBar/PrivacyBar.axaml
Labels: size/XS

#9116 Make sure the test CombinationsWithoutRepetition can finish on CI
  WalletWasabi.Tests/UnitTests/LinqExtensionsTests.cs
Labels: size/XS

#9159 [VDG] Remove Automatically start coinjoin toggle from the coinjoin profile settings
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/CoinJoinProfilesViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/ManualCoinJoinProfileDialogViewModel.cs
  WalletWasabi.Fluent/Views/Dialogs/ManualCoinJoinProfileDialogView.axaml
Labels: size/S

#9170 Fix namespace for `ExceptionExtensions`
  WalletWasabi.Fluent/CrashReport/CrashReporter.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/WalletNamePageViewModel.cs
  WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/BroadcastTransactionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/HardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Tests/UnitTests/SerializableExceptionTests.cs
  WalletWasabi/Bases/PeriodicRunner.cs
  WalletWasabi/Extensions/ExceptionExtensions.cs
  WalletWasabi/Services/Terminate/TerminateService.cs
Labels: size/S

#9166 [Backend] Fix swagger
  WalletWasabi.Backend/Controllers/BlockchainController.cs
Labels: size/XS

#9172 Promiscuous Bobs disabled
  WalletWasabi.Tests/UnitTests/TestWallet.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
Labels: size/S

#9186 Use explicit json converter for Risk flags
  WalletWasabi.Backend/Global.cs
  WalletWasabi/JsonConverters/DefaultValueIntegerArrayAttribute.cs
  WalletWasabi/JsonConverters/IntegerArrayJsonConverter.cs
  WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
Labels: size/M

#9173 Fix AutoSelectPockets
  WalletWasabi.Fluent/ViewModels/Wallets/Send/LabelSelectionViewModel.cs
  WalletWasabi.Tests/UnitTests/UserInterfaceTest/PocketSelectionTests.cs
Labels: size/L

#9188 Use vs2022 for building the MSI
  WalletWasabi.Packager/scripts/Wasabi_release.ps1
Labels: size/XS

#9126 [VDG] Take FeeRate into account during pocket selection
  WalletWasabi.Fluent/Extensions/PocketExtensions.cs
  WalletWasabi.Fluent/Models/Pocket.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/LabelSelectionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Tests/UnitTests/UserInterfaceTest/PocketSelectionTests.cs
  WalletWasabi.Tests/UnitTests/UserInterfaceTest/PocketTests.cs
Labels: size/L

#9161 Update DeterministicBuildGuide.md
  WalletWasabi.Documentation/Guides/DeterministicBuildGuide.md
Labels: size/S

#9185 [VDG] Do not call SetWindowSize when windows state is Maximized
  WalletWasabi.Fluent/ApplicationStateManager.cs
  WalletWasabi.Fluent/Behaviors/WindowSizeBehavior.cs
  WalletWasabi.Fluent/Views/MainWindow.axaml
Labels: size/M

#9187 [VDG] fix `IsOtherSelectionPossible`
  WalletWasabi.Fluent/ViewModels/Wallets/Send/LabelSelectionViewModel.cs
  WalletWasabi.Tests/UnitTests/UserInterfaceTest/PocketSelectionTests.cs
Labels: size/S

#9190 [VDG] Fix `TryGetBestKnownByRecipientPockets`
  WalletWasabi.Fluent/ViewModels/Wallets/Send/LabelSelectionViewModel.cs
  WalletWasabi.Tests/UnitTests/UserInterfaceTest/PocketSelectionTests.cs
Labels: size/M

#9196 Use lock when we remove Alices, fix backend bug
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
Labels: size/S

#9199 Revert "Use lock when we remove Alices, fix backend bug"
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
Labels: size/S

#9200 ToArray to not have collection modified error
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
Labels: size/XS

#9202 [Trivial] Fix warning
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
Labels: size/XS

#9201 Updated docs links
  WalletWasabi.Backend/wwwroot/faq.html
Labels: size/XS

#9168 [trivial] improve TransactionSizeException message
  WalletWasabi/Exceptions/TransactionSizeException.cs
Labels: size/XS

#9111 TorHttpPool: Force different Tor circuit after failure.
  WalletWasabi.Tests/UnitTests/Tor/Socks5/Pool/TorHttpPoolTests.cs
  WalletWasabi.Tests/UnitTests/Tor/Socks5/TorTcpConnectionFactoryTests.cs
  WalletWasabi/Tor/Socks5/Pool/Circuits/AnyOneOffCircuit.cs
  WalletWasabi/Tor/Socks5/Pool/Circuits/DefaultCircuit.cs
  WalletWasabi/Tor/Socks5/Pool/Circuits/ICircuit.cs
  WalletWasabi/Tor/Socks5/Pool/Circuits/INamedCircuit.cs
  WalletWasabi/Tor/Socks5/Pool/Circuits/OneOffCircuit.cs
  WalletWasabi/Tor/Socks5/Pool/Circuits/PersonCircuit.cs
  WalletWasabi/Tor/Socks5/Pool/TorHttpPool.cs
  WalletWasabi/Tor/Socks5/TorTcpConnection.cs
  WalletWasabi/Tor/Socks5/TorTcpConnectionFactory.cs
Labels: size/L

#9209 Remove redundant timeot
  WalletWasabi/WabiSabi/Client/WabiSabiHttpApiClient.cs
Labels: size/XS

#9214 Updated guide links at download section
  WalletWasabi.Backend/wwwroot/index.html
Labels: size/S

#9194 remove old version command from issue template
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: size/XS

#9206 [Fix CI] Increase SingleInstanceChecker timeouts for CI
  WalletWasabi.Tests/UnitTests/Clients/SingleInstanceCheckerTests.cs
  WalletWasabi/Services/SingleInstanceChecker.cs
Labels: size/M

#9220 [Trivial] Change Info log to Warning when API call is late
  WalletWasabi/WabiSabi/Backend/Banning/CoinVerifierApiClient.cs
Labels: size/XS
