Repository WalletWasabi/WalletWasabi, pull requests merged in 2023-10, with the labels that each got.

#11506 [VDG] Unify amount display
  WalletWasabi.Fluent/App.axaml
  WalletWasabi.Fluent/Controls/AmountControl.axaml
  WalletWasabi.Fluent/Controls/AmountControl.axaml.cs
  WalletWasabi.Fluent/Controls/CopyableItem.axaml
  WalletWasabi.Fluent/Extensions/CurrencyExtensions.cs
  WalletWasabi.Fluent/Infrastructure/ClipboardObserver.cs
  WalletWasabi.Fluent/Infrastructure/ExchangeRateProvider.cs
  WalletWasabi.Fluent/Infrastructure/IExchangeRateProvider.cs
  WalletWasabi.Fluent/Models/UI/UiContext.cs
  WalletWasabi.Fluent/Models/Wallets/AmountProvider.cs
  WalletWasabi.Fluent/Models/Wallets/WalletModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Amount.cs
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/CoinJoinDetailsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/CoinJoinsDetailsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/TransactionDetailsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Features/CancelTransactionDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Features/SpeedUpTransactionDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinsHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/BtcPriceTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletBalanceTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/IWalletBalancesModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionSummaryViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletBalancesModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/Details/CoinJoinDetailsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/Details/CoinJoinsDetailsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/Details/TransactionDetailsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/Features/CancelTransactionDialogView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/Features/SpeedUpTransactionDialogView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionSummary.axaml
  WalletWasabi.Tests/UnitTests/ViewModels/AmountTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/Extensions.cs
  WalletWasabi.Tests/UnitTests/ViewModels/Mocks.cs
  WalletWasabi.Tests/UnitTests/ViewModels/ReceiveAddressViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/ReceiveViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/SuggestionLabelsViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/UiContextBuilder.cs
Labels: size/XL

#11609 [VDG] Verify seed words - add `canExecute` to verify button
  WalletWasabi.Fluent/ViewModels/Wallets/VerifyRecoveryWordsViewModel.cs
Labels: size/XS

#11497 [VDG] UI Decoupling #43
  WalletWasabi.Fluent/Models/Wallets/CoinModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletCoinjoinModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletCoinsModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletModel.cs
  WalletWasabi.Fluent/TreeDataGrid/Selectable.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/AddressEntryDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/Columns/AnonymitySetColumnView.axaml
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/Columns/IndicatorsColumnView.axaml
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/Columns/LabelsColumnView.axaml
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/WalletCoinsView.axaml
  WalletWasabi.Tests/UnitTests/ViewModels/ReceiveAddressViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/ReceiveViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/SuggestionLabelsViewModelTests.cs
Labels: size/L

#11509 [VDG] UI Decoupling #44
  WalletWasabi.Fluent/Models/Wallets/WalletCoinsModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletPrivacyModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletTransactionsModel.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/SelectCoinsDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Tests/UnitTests/ViewModels/ReceiveAddressViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/ReceiveViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/SuggestionLabelsViewModelTests.cs
Labels: size/L

#11510 [VDG] UI Decoupling #45
  WalletWasabi.Fluent/Models/Wallets/WalletTransactionsModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/TransactionDetailsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/TransactionHistoryItemViewModel.cs
Labels: size/M

#11565 [VDG] UI Decoupling #46
  WalletWasabi.Fluent/Models/Pocket.cs
  WalletWasabi.Fluent/Models/Wallets/CoinModel.cs
  WalletWasabi.Fluent/Models/Wallets/ScriptType.cs
  WalletWasabi.Fluent/Models/Wallets/WalletCoinsModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletModelExtensions.cs
  WalletWasabi.Fluent/Models/Wallets/WalletTransactionsModel.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/Core/CoinCoinControlItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/Core/CoinControlItemViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/Core/PocketCoinControlItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/SelectCoinsDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
Labels: size/L

#11566 [VDG] UI Decoupling #47
  WalletWasabi.Fluent/App.axaml.cs
  WalletWasabi.Fluent/Models/TransactionBroadcastInfo.cs
  WalletWasabi.Fluent/Models/TransactionBroadcasterModel.cs
  WalletWasabi.Fluent/Models/UI/UiContext.cs
  WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/BroadcastTransactionViewModel.cs
  WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/BroadcasterViewModel.cs
  WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/LoadTransactionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/HardwareWalletViewModel.cs
  WalletWasabi.Tests/UnitTests/ViewModels/Mocks.cs
  WalletWasabi.Tests/UnitTests/ViewModels/UiContextBuilder.cs
Labels: size/L

#11618 `CoinsRegistry`: Optimize `GetMyInputs`
  WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs
Labels: size/XS

#11610 [VDG] Privacy Warning - change final message
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml
Labels: size/XS

#11619 `CoinsRegistry` Add a unit test
  WalletWasabi.Tests/Helpers/TransactionProcessorExtensions.cs
  WalletWasabi.Tests/UnitTests/Blockchain/TransactionOutputs/CoinsRegistryTests.cs
Labels: size/L

#11616 [VDG] UI Decoupling #48
  WalletWasabi.Fluent/App.axaml.cs
  WalletWasabi.Fluent/Helpers/AuthorizationHelpers.cs
  WalletWasabi.Fluent/Models/UI/UiContext.cs
  WalletWasabi.Fluent/Models/Wallets/HardwareWalletModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletRepository.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Features/CancelTransactionDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Features/SpeedUpTransactionDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Tests/UnitTests/ViewModels/Mocks.cs
  WalletWasabi.Tests/UnitTests/ViewModels/ReceiveAddressViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/ReceiveViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/SuggestionLabelsViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/UiContextBuilder.cs
Labels: size/M

#11617 [VDG] UI Decoupling #49
  WalletWasabi.Fluent/Controls/AmountControl.axaml.cs
  WalletWasabi.Fluent/Infrastructure/ClipboardObserver.cs
  WalletWasabi.Fluent/Models/Wallets/Amount.cs
  WalletWasabi.Fluent/Models/Wallets/WalletModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/CoinJoinDetailsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/CoinJoinsDetailsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletBalanceTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionSummaryViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Tests/UnitTests/ViewModels/ReceiveAddressViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/ReceiveViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/SuggestionLabelsViewModelTests.cs
Labels: size/M

#11602 Remove http status reason part as required
  WalletWasabi/Tor/Http/Models/StatusLine.cs
Labels: size/XS

#11623 [VDG] Remove checkmark for verify recovery words dialog
  WalletWasabi.Fluent/ViewModels/Wallets/VerifyRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/VerifyRecoveryWordsView.axaml
Labels: size/S

#11595 [VDG] Temporarily disabling the running in background on macOS
  WalletWasabi.Fluent/App.axaml
  WalletWasabi.Fluent/App.axaml.cs
  WalletWasabi.Fluent/ApplicationStateManager.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/SettingsSearchSource.cs
  WalletWasabi.Fluent/Views/Settings/GeneralSettingsTabView.axaml
Labels: size/M

#11634 [vdg] clarify Transaction Broadcaster dialog caption
  WalletWasabi.Fluent/Views/TransactionBroadcasting/LoadTransactionView.axaml
Labels: size/XS

#11633 [VDG] Fix empty searchbar dropdown
  WalletWasabi.Fluent/ViewModels/SearchBar/SearchBarViewModel.cs
  WalletWasabi.Fluent/Views/SearchBar/SearchBarDropdown.axaml
Labels: size/S

#11607 [VDG] Add/remove Search API to modify items dynamically
  WalletWasabi.Fluent/App.axaml.cs
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/Models/UI/UiContext.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/Sources/EditableSearchSourceSource.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/Sources/IEditableSearchSource.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletInfoViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletStatsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinSettingsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletSettingsViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
  WalletWasabi.Tests/UnitTests/ViewModels/Mocks.cs
  WalletWasabi.Tests/UnitTests/ViewModels/UiContextBuilder.cs
Labels: size/L

#11629 [Trivial] Reduce log level when Warden stops
  WalletWasabi/WabiSabi/Backend/DoSPrevention/Warden.cs
Labels: size/XS

#11639 `CoinsRegistry`: Extract `UpdateSnapshotsNoLock`
  WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs
Labels: size/S

#11640 [trivial] `CoinsRegistry`: Rename methods
  WalletWasabi.Tests/UnitTests/Blockchain/TransactionOutputs/CoinsRegistryTests.cs
  WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
Labels: size/M

#11540 Add `excludefromcoinjoin` from RPC
  WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/S

#11646 `TransactionProcessor`: Remove extra `.ToArray`
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
Labels: size/XS

#11645 `CoinsRegistry`: Optimize `TryGetByOutPoint` method
  WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs
Labels: size/S

#11650 [Trivial] Fix CoderFactor
  WalletWasabi.Fluent/App.axaml.cs
  WalletWasabi.Tests/UnitTests/AllFeeEstimateTests.cs
  WalletWasabi.Tests/UnitTests/Helpers/PowerSaving/BaseInhibitorTaskTests.cs
  WalletWasabi.Tests/UnitTests/MockIHttpClient.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/CoordinatorTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/UtxoPrisonWardenTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/Wallet/WalletBuilder.cs
  WalletWasabi/BitcoinCore/Configuration/Whitening/WhiteEntry.cs
  WalletWasabi/WebClients/Wasabi/WasabiHttpClientFactory.cs
Labels: size/M

#11189 [Trivial][VDG] Rename Incoming and Outgoing columns to Received and Sent amounts
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/TransactionDetailsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
Labels: size/S

#11662 Fix .txn file import for ColdCards
  WalletWasabi.Fluent/Helpers/TransactionHelpers.cs
  WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/LoadTransactionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/HardwareWalletViewModel.cs
Labels: size/S

#10910 Skip rounds randomly depending on network conditions
  WalletWasabi.Fluent/Models/Wallets/WalletSettingsModel.cs
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/CoinJoinProfileViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/CoinJoinProfilesViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/EconomicCoinJoinProfileViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/ManualCoinJoinProfileViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/PrivateCoinJoinProfileViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/SpeedyCoinJoinProfileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/ManualCoinJoinProfileDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/CoinjoinSkipFactorsTests.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/JsonConverters/CoinjoinSkipFactorsJsonConverter.cs
  WalletWasabi/Models/CoinjoinSkipFactors.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinTrackerFactory.cs
  WalletWasabi/WabiSabi/Client/StatusChangedEvents/StatusChangedEventArgs.cs
  WalletWasabi/Wallets/IWallet.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/L

#11667 Add `feeRate` to `build` and `send` rpc interface
  WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
  WalletWasabi.Tests/UnitTests/RpcTests.cs
  WalletWasabi/Helpers/Constants.cs
  WalletWasabi/Rpc/JsonRpcRequestHandler.cs
Labels: size/M

#11620 [VDG] Optimize transaction get by id
  WalletWasabi.Fluent.Generators/Generators/AutoInterfaceGenerator.cs
  WalletWasabi.Fluent/Models/Wallets/WalletTransactionsModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/TransactionDetailsViewModel.cs
Labels: size/M

#11683 [VDG][Trivial] Order bitcoin node settings
  WalletWasabi.Fluent/Views/Settings/BitcoinTabSettingsView.axaml
Labels: size/S

#11680 [Trivial] Add missing Exception logging on tx import
  WalletWasabi.Fluent/Helpers/TransactionHelpers.cs
Labels: size/XS

#11635 Fix coinjoins shared overhead calculation
  WalletWasabi/Helpers/ScriptSizeHelpers.cs
  WalletWasabi/Helpers/VirtualSizeHelpers.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/MultipartyTransactionParameters.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/SigningState.cs
Labels: size/M

#11686 Implement coinjoin to other wallet with daemon
  WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
  WalletWasabi.Fluent/Models/Wallets/WalletCoinjoinModel.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WabiSabi/Client/CoinJoinTracker.cs
  WalletWasabi/WabiSabi/Client/CoinJoinTrackerFactory.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/L

#11693 Update exclusion.dic
  exclusion.dic
Labels: size/XS

#11701 Add `listwallets` rpc call
  WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
Labels: size/S

#11702 Fix generator namespaces
  WalletWasabi.Fluent.Generators/Abstractions/CombinedGenerator.cs
  WalletWasabi.Fluent.Generators/Abstractions/GeneratorStep.cs
  WalletWasabi.Fluent.Generators/Abstractions/GeneratorStepContext.cs
  WalletWasabi.Fluent.Generators/Abstractions/GeneratorStep`1.cs
  WalletWasabi.Fluent.Generators/Abstractions/IsExternalInit.cs
  WalletWasabi.Fluent.Generators/Abstractions/StaticFileGenerator.cs
  WalletWasabi.Fluent.Generators/AnalyzerExtensions.cs
  WalletWasabi.Fluent.Generators/Analyzers/UIContextUsageInConstructorAnalyzer.cs
  WalletWasabi.Fluent.Generators/Generators/AutoInterfaceAttributeGenerator.cs
  WalletWasabi.Fluent.Generators/Generators/AutoInterfaceGenerator.cs
  WalletWasabi.Fluent.Generators/Generators/AutoNotifyAttributeGenerator.cs
  WalletWasabi.Fluent.Generators/Generators/AutoNotifyGenerator.cs
  WalletWasabi.Fluent.Generators/Generators/FluentNavigationGenerator.cs
  WalletWasabi.Fluent.Generators/Generators/MainGenerator.cs
  WalletWasabi.Fluent.Generators/Generators/UiContextConstructorGenerator.cs
Labels: size/M

#11125 Display custom fee rate dialog directly if a custom fee rate was used
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
Labels: size/XS

#11517 [VDG] Improve settings
  WalletWasabi.Fluent/App.axaml.cs
  WalletWasabi.Fluent/Models/UI/ApplicationSettings.cs
  WalletWasabi.Fluent/Services.cs
  WalletWasabi.Fluent/Styles/ToggleSwitch.axaml
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/SearchItems/ContentSearchItem.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/SearchItems/ContentSearchItemNode.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/SearchItems/IContentSearchItem.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/SearchItems/SearchItemNode.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/SettingsSearchSource.cs
  WalletWasabi.Fluent/ViewModels/Settings/AdvancedSettingsTabViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/BitcoinTabSettingsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/GeneralSettingsTabViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/SettingsPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/Views/SearchBar/SearchBarDropdown.axaml
  WalletWasabi.Fluent/Views/Settings/SettingsPageView.axaml
  WalletWasabi.Tests/UnitTests/ViewModels/UiContext/NullApplicationSettings.cs
Labels: size/L

#11706 [Contrib/CLI] update getwalletinfo example
  Contrib/CLI/README.md
Labels: size/XS

#11671 Improve amount decomposer fail condition for Trezor integration tests
  WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
Labels: size/XS

#11715 Revert "Improve amount decomposer fail condition for Trezor integration tests"
  WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
Labels: size/XS

#11716 `ServiceFactory`: Fix whitespace
  WalletWasabi.Tests/UnitTests/Transactions/PayjoinTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
Labels: size/L

#11719 Add Condition For Non Existent Denominations
  WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
Labels: size/XS

#11734 [vdg] Preview TX screen: put address as second item
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionSummary.axaml
Labels: size/S

#11735 [VDG] Performance tuning
  WalletWasabi.Fluent/Extensions/ObservableExtensions.cs
  WalletWasabi.Fluent/Models/Wallets/WalletCoinsModel.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/LabelEntryDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingViewModel.cs
Labels: size/L

#11714 Expose the RPC Server as an onion service
  WalletWasabi.Daemon/Config.cs
  WalletWasabi.Daemon/Global.cs
  WalletWasabi/Tor/Control/TorControlClient.cs
  WalletWasabi/Tor/TorSettings.cs
Labels: size/M

#11707 [VDG] Add estimated confirmation time to coinjoins in Transaction Summary
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/CoinJoinDetailsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/CoinJoinsDetailsViewModel.cs
Labels: size/XS

#11744 [VDG] Restore padding fix for TextBox.monoSpaced style
  WalletWasabi.Fluent/Styles/TextBox.axaml
Labels: size/XS

#11750 `CoinsRegistry`: Remove `KnownTransactions`
  WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs
Labels: size/S

#11757 [UI] Wallet Coins - fix unnecessary refreshes
  WalletWasabi.Fluent/Models/Wallets/WalletCoinsModel.cs
Labels: size/XS

#11733 [VDG] Fix LabelsItemsPresenter layout algorithm after update to Avalonia 11
  WalletWasabi.Fluent/Controls/LabelsItemsPresenter.axaml
  WalletWasabi.Fluent/Controls/LabelsPanel.cs
Labels: size/L

#11704 [VDG] Add colorful diffs in Transaction Preview
  WalletWasabi.Fluent/Converters/DiffToBrushConverter.cs
  WalletWasabi.Fluent/Converters/MoneyConverters.cs
  WalletWasabi.Fluent/Extensions/CurrencyExtensions.cs
  WalletWasabi.Fluent/Helpers/AmountExtensions.cs
  WalletWasabi.Fluent/Helpers/TextHelpers.cs
  WalletWasabi.Fluent/Styles/Themes/ThemeVariants.axaml
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionSummaryViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionSummary.axaml
  WalletWasabi.Tests/UnitTests/Helpers/AmountExtensionsTests.cs
  WalletWasabi.Tests/UnitTests/Helpers/FormattingTests.cs
Labels: size/L

#11762 Make StopWhenAllMixed work
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/CoinJoinCoinSelectionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/Participant.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinCoinSelector.cs
  WalletWasabi/WabiSabi/Client/CoinJoinTracker.cs
Labels: size/M

#11782 Fix countdown when error
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
Labels: size/XS

#11773 [VDG] Add missing themes to CrashReportApp
  WalletWasabi.Fluent/CrashReport/CrashReportApp.axaml
Labels: size/XS

#11770 [VDG] Fix MenuItem spacing in flyouts and context menus
  WalletWasabi.Fluent/Styles/ContextMenu.axaml
  WalletWasabi.Fluent/Styles/MenuFlyoutPresenter.axaml
Labels: size/S

#11769 [VDG] Workaround for invalid caption buttons theme
  WalletWasabi.Fluent/Controls/CaptionButtons.axaml
  WalletWasabi.Fluent/Styles/Themes/Fluent.axaml
Labels: size/L

#11774 [VDG] Remove unused old theme files not needed after Avalonia 11 update
  WalletWasabi.Fluent/Styles/Themes/Base.axaml
  WalletWasabi.Fluent/Styles/Themes/BaseDark.axaml
  WalletWasabi.Fluent/Styles/Themes/BaseLight.axaml
  WalletWasabi.Fluent/Styles/Themes/ThemeVariants.axaml
Labels: size/S

#11775 [VFG] Migrate AmountControl to control themes
  WalletWasabi.Fluent/App.axaml
  WalletWasabi.Fluent/Controls/AmountControl.axaml
  WalletWasabi.Fluent/Styles/Themes/Fluent.axaml
Labels: size/M

#11793 `LineChart` Remove unused parameter
  WalletWasabi.Fluent/Controls/LineChart.cs
Labels: size/L

#11792 [Trivial] Fix Codefactor
  WalletWasabi.Daemon/Global.cs
  WalletWasabi.Fluent/Controls/LineChart.cs
  WalletWasabi.Fluent/Controls/QrCode.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/HistoryItemViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
Labels: size/L

#11778 [VDG] Make password button texts depends on intent
  WalletWasabi.Fluent/Helpers/AuthorizationHelpers.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/Authorization/PasswordAuthDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Features/CancelTransactionDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Features/SpeedUpTransactionDialogViewModel.cs
  WalletWasabi.Fluent/Views/Dialogs/Authorization/PasswordAuthDialogView.axaml
Labels: size/S

#11767 [VDG] Fix NavBar item font and icon color is different when it is disabled
  WalletWasabi.Fluent/Controls/NavBarItem.axaml
Labels: size/XS

#11787 [VDG] Fix amount copy on Transaction Preview dialog
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionSummary.axaml
Labels: size/XS

#11789 Fix change avoidance giving back two Less/More suggestion
  WalletWasabi.Fluent/Models/Transactions/PrivacySuggestion.cs
  WalletWasabi.Fluent/Models/Transactions/PrivacySuggestionsModel.cs
Labels: size/S

#11797 Set PreferPsbtWorkflow true when importing ColdCard HW
  WalletWasabi/Helpers/ImportWalletHelper.cs
Labels: size/XS

#11644 [VDG] UI Decoupling #50
  WalletWasabi.Fluent.Generators/Generators/AutoInterfaceGenerator.cs
  WalletWasabi.Fluent/Behaviors/PendingHistoryItemSeparatorBehavior.cs
  WalletWasabi.Fluent/Controls/TreeDataGrid.axaml
  WalletWasabi.Fluent/Converters/TransactionHistoryItemToolTipConverter.cs
  WalletWasabi.Fluent/Extensions/ObservableExtensions.cs
  WalletWasabi.Fluent/Helpers/SignaledFetcher.cs
  WalletWasabi.Fluent/Helpers/TextHelpers.cs
  WalletWasabi.Fluent/Models/Wallets/CoinModel.cs
  WalletWasabi.Fluent/Models/Wallets/TransactionModel.cs
  WalletWasabi.Fluent/Models/Wallets/TransactionTreeBuilder.cs
  WalletWasabi.Fluent/Models/Wallets/WalletCoinsModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletTransactionsModel.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/Sources/TransactionsSearchSource.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletStatsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/CoinJoinDetailsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/CoinJoinsDetailsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/TransactionDetailsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinsHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/HistoryItemViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/SpeedUpHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/TransactionHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/Columns/IndicatorsColumnView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/Columns/LabelsColumnView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
Labels: size/XXL

#11791 Only update amount if coin is added
  WalletWasabi.Tests/UnitTests/Blockchain/TransactionOutputs/CoinsRegistryTests.cs
  WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs
Labels: size/M

#11753 [UI] Recovery words - fix message and improve UX
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
Labels: size/S

#11772 [VDG] Fix PasswordFoundView reveal password button
  WalletWasabi.Fluent/Views/Login/PasswordFinder/PasswordFoundView.axaml
Labels: size/S

#11665 [VDG] UI Decoupling #51
  WalletWasabi.Fluent/Models/Wallets/CancellingTransaction.cs
  WalletWasabi.Fluent/Models/Wallets/SpeedupTransaction.cs
  WalletWasabi.Fluent/Models/Wallets/TransactionModel.cs
  WalletWasabi.Fluent/Models/Wallets/TransactionStatus.cs
  WalletWasabi.Fluent/Models/Wallets/TransactionType.cs
  WalletWasabi.Fluent/Models/Wallets/WalletAuthModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletTransactionsModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Features/CancelTransactionDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Features/SpeedUpTransactionDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/TransactionHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
Labels: size/L

#11805 [UI] Remove leftover
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
Labels: size/L

#11799 Fix Codefactor
  WalletWasabi.Fluent/Controls/LineChart.cs
  WalletWasabi.Tests/UnitTests/Helpers/PowerSaving/BaseInhibitorTaskTests.cs
  WalletWasabi.Tests/UnitTests/Helpers/PowerSaving/MockProcessAsync.cs
  WalletWasabi.Tests/UnitTests/MockHttpClient.cs
  WalletWasabi.Tests/UnitTests/MockHttpClientExtensions.cs
  WalletWasabi.Tests/UnitTests/MockIHttpClient.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/MockWasabiHttpClientFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi.Tests/UnitTests/Wallet/MockBlockRepository.cs
  WalletWasabi.Tests/UnitTests/Wallet/WalletBuilder.cs
Labels: size/L

#11795 Don't skip blame rounds
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/LoggerTools.cs
  WalletWasabi/WabiSabi/Models/RoundState.cs
Labels: size/S

#11807 [VDG] Use fetcher for addresses
  WalletWasabi.Fluent/Models/Wallets/WalletCoinsModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletModelExtensions.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressViewModel.cs
  WalletWasabi.Tests/UnitTests/ViewModels/ReceiveAddressViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/ReceiveViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/SuggestionLabelsViewModelTests.cs
Labels: size/M

#11813 Prison inheritance performance improvement
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepConnectionConfirmationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputToBlameRoundTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PrisonTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/UtxoPrisonWardenTests.cs
  WalletWasabi/WabiSabi/Backend/DoSPrevention/Prison.cs
  WalletWasabi/WabiSabi/Backend/DoSPrevention/Warden.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
  WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
Labels: size/L

#11820 Do not ban coinjoin outputs
  WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
Labels: size/XS

#11815 [Trivial] Fix CodeFactor
  WalletWasabi.Fluent/Models/Wallets/WalletStatsModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
Labels: size/M

#11822 Fix ban double spenders
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
Labels: size/S

#11816 [VDG] Fix Wallet Dialogs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
Labels: size/XS

#11828 [VDG] Use AdornerLayer.SetAdorner to add and remove adorner in AdorningContentControl
  WalletWasabi.Fluent/Controls/AdorningContentControl.axaml.cs
  WalletWasabi.Fluent/Helpers/AdornerHelper.cs
Labels: size/M

#11827 [VDG] Fix PrivacyRing loading animation showing twice when opened
  WalletWasabi.Fluent/Behaviors/ItemsPresenterAnimationBehavior.cs
Labels: size/XS

#11829 [VDG] Fix usd formatting in tiles
  WalletWasabi.Fluent/Converters/MoneyConverters.cs
  WalletWasabi.Fluent/Extensions/CurrencyExtensions.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/BtcPriceTileView.axaml
Labels: size/S

#11831 [VDG] Fix setting classes for history items
  WalletWasabi.Fluent/Behaviors/HistoryItemTypeClassBehavior.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
Labels: size/M

#11826 [VDG] [Trivial] Fix FadeInBehavior property registration
  WalletWasabi.Fluent/Behaviors/FadeInBehavior.cs
Labels: size/XS

#11810 [VDG] Optimize Receive flow
  WalletWasabi.Fluent/Extensions/DynamicDataExtensions.cs
  WalletWasabi.Fluent/Models/Wallets/Address.cs
  WalletWasabi.Fluent/Models/Wallets/AddressesModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletModelExtensions.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressesViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveView.axaml
  WalletWasabi.Tests/UnitTests/ViewModels/AddressViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/ReceiveAddressViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/ReceiveViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/SuggestionLabelsViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/TestDoubles/AddressTestingMocks.cs
  WalletWasabi.Tests/UnitTests/ViewModels/TestDoubles/MockUtils.cs
Labels: size/L

#11801 [VDG] UI Decoupling #53
  Directory.Packages.props
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/App.axaml.cs
  WalletWasabi.Fluent/Extensions/DynamicDataExtensions.cs
  WalletWasabi.Fluent/Models/UI/ApplicationSettings.cs
  WalletWasabi.Fluent/Models/UI/TorStatusCheckerModel.cs
  WalletWasabi.Fluent/Models/UI/UiContext.cs
  WalletWasabi.Fluent/Models/Wallets/WalletCoinjoinModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletTransactionsModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModelExtensions.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/StatusIcon/StatusIconViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
  WalletWasabi.Tests/UnitTests/ViewModels/TestDoubles/MockUtils.cs
  WalletWasabi.Tests/UnitTests/ViewModels/UiContext/NullApplicationSettings.cs
  WalletWasabi.Tests/UnitTests/ViewModels/UiContextBuilder.cs
Labels: size/L

#11808 [VDG] UI Decoupling #54
  WalletWasabi.Fluent/Models/Wallets/WalletRepository.cs
Labels: size/M

#11811 [VDG] UI Decoupling #55
  WalletWasabi.Fluent/Helpers/NotificationHelpers.cs
  WalletWasabi.Fluent/Models/Wallets/AmountProvider.cs
  WalletWasabi.Fluent/Models/Wallets/WalletModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletTransactionsModel.cs
  WalletWasabi.Fluent/UiServices.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/INavigate.cs
  WalletWasabi.Fluent/ViewModels/Navigation/IWalletNavigation.cs
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationState.cs
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Features/CancelTransactionDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Features/SpeedUpTransactionDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Notifications/WalletNotificationsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendSuccessViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Tests/UnitTests/ViewModels/ReceiveAddressViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/SuggestionLabelsViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/TestDoubles/AddressTestingMocks.cs
  WalletWasabi.Tests/UnitTests/ViewModels/TestDoubles/MockUtils.cs
  WalletWasabi.Tests/UnitTests/ViewModels/TestDoubles/NavigationMock.cs
Labels: size/L

#11839 [UI] History - fix CJ group amounts (alternative)
  WalletWasabi.Fluent/Models/Wallets/TransactionModel.cs
  WalletWasabi.Fluent/Models/Wallets/TransactionTreeBuilder.cs
Labels: size/XS

#11817 [VDG] UI Decoupling #56
  WalletWasabi.Fluent/Models/Wallets/WalletTransactionsModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/CoinJoinDetailsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/CoinJoinsDetailsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/TransactionDetailsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinsHistoryItemViewModel.cs
  WalletWasabi.Tests/UnitTests/ViewModels/SuggestionLabelsViewModelTests.cs
Labels: size/M

#11825 [VDG] UI Decoupling #57
  WalletWasabi.Fluent/App.axaml.cs
  WalletWasabi.Fluent/Models/UI/UiContext.cs
  WalletWasabi.Fluent/Models/Wallets/LegalDocumentsProvider.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/LegalDocumentsViewModel.cs
  WalletWasabi.Tests/UnitTests/ViewModels/TestDoubles/MockUtils.cs
  WalletWasabi.Tests/UnitTests/ViewModels/UiContextBuilder.cs
Labels: size/M

#11837 [VDG] UI Decoupling #58
  WalletWasabi.Fluent/App.axaml.cs
  WalletWasabi.Fluent/Models/UI/UiContext.cs
  WalletWasabi.Fluent/Models/Wallets/CoinjoinModel.cs
  WalletWasabi.Fluent/ViewModels/ApplicationViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/ShuttingDownViewModel.cs
  WalletWasabi.Tests/UnitTests/ViewModels/TestDoubles/MockUtils.cs
  WalletWasabi.Tests/UnitTests/ViewModels/UiContextBuilder.cs
Labels: size/L

#11846 Fix synchronization issue
  WalletWasabi/WabiSabi/Backend/DoSPrevention/Prison.cs
  WalletWasabi/WabiSabi/Backend/Models/WabiSabiProtocolErrorCode.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/XS

#11841 Added 1 more Exchange rate provider
  WalletWasabi.Tests/IntegrationTests/ExternalApiTests.cs
  WalletWasabi/WebClients/Coingate/CoingateExchangeRateProvider.cs
  WalletWasabi/WebClients/ExchangeRateProviders.cs
Labels: size/M
