Repository WalletWasabi/WalletWasabi, pull requests merged in 2023-09, with the labels that each got.

#11407 Flake for safer deployments
  deps.nix
  flake.lock
  flake.nix
Labels: size/L

#11412 `Prison`: fix lock
  WalletWasabi/WabiSabi/Backend/DoSPrevention/Prison.cs
Labels: size/XS

#11405 [VDG] ...and AutoInterfaces for all
  WalletWasabi.Fluent.Generators/Abstractions/CombinedGenerator.cs
  WalletWasabi.Fluent.Generators/Abstractions/GeneratorStep.cs
  WalletWasabi.Fluent.Generators/Abstractions/GeneratorStepContext.cs
  WalletWasabi.Fluent.Generators/Abstractions/GeneratorStep`1.cs
  WalletWasabi.Fluent.Generators/Abstractions/IsExternalInit.cs
  WalletWasabi.Fluent.Generators/Abstractions/StaticFileGenerator.cs
  WalletWasabi.Fluent.Generators/AnalyzerExtensions.cs
  WalletWasabi.Fluent.Generators/Analyzers/UIContextUsageInConstructorAnalyzer.cs
  WalletWasabi.Fluent.Generators/Generators/AutoInterfaceAttributeGenerator.cs
  WalletWasabi.Fluent.Generators/Generators/AutoInterfaceGenerator.cs
  WalletWasabi.Fluent.Generators/Generators/AutoNotifyAttributeGenerator.cs
  WalletWasabi.Fluent.Generators/Generators/AutoNotifyGenerator.cs
  WalletWasabi.Fluent.Generators/Generators/FluentNavigationGenerator.cs
  WalletWasabi.Fluent.Generators/Generators/MainGenerator.cs
  WalletWasabi.Fluent.Generators/Generators/UiContextConstructorGenerator.cs
  WalletWasabi.Fluent.Generators/UIContextGenerator.cs
  WalletWasabi.Fluent/App.axaml.cs
  WalletWasabi.Fluent/Models/UI/ApplicationSettings.cs
  WalletWasabi.Fluent/Models/UI/IApplicationSettings.cs
  WalletWasabi.Fluent/Models/UI/IQrCodeGenerator.cs
  WalletWasabi.Fluent/Models/UI/IQrCodeReader.cs
  WalletWasabi.Fluent/Models/UI/IUiClipboard.cs
  WalletWasabi.Fluent/Models/UI/QrCodeGenerator.cs
  WalletWasabi.Fluent/Models/UI/QrCodeReader.cs
  WalletWasabi.Fluent/Models/UI/UiClipboard.cs
  WalletWasabi.Fluent/Models/Wallets/CoinModel.cs
  WalletWasabi.Fluent/Models/Wallets/HardwareWalletInterface.cs
  WalletWasabi.Fluent/Models/Wallets/ICoinModel.cs
  WalletWasabi.Fluent/Models/Wallets/IHardwareWalletInterface.cs
  WalletWasabi.Fluent/Models/Wallets/IPasswordFinderModel.cs
  WalletWasabi.Fluent/Models/Wallets/IWalletAuthModel.cs
  WalletWasabi.Fluent/Models/Wallets/IWalletCoinjoinModel.cs
  WalletWasabi.Fluent/Models/Wallets/IWalletInfoModel.cs
  WalletWasabi.Fluent/Models/Wallets/IWalletLoadWorkflow.cs
  WalletWasabi.Fluent/Models/Wallets/IWalletModel.cs
  WalletWasabi.Fluent/Models/Wallets/IWalletPrivacyModel.cs
  WalletWasabi.Fluent/Models/Wallets/IWalletRepository.cs
  WalletWasabi.Fluent/Models/Wallets/IWalletSettingsModel.cs
  WalletWasabi.Fluent/Models/Wallets/PasswordFinderModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletAuthModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletCoinjoinModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletInfoModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletLoadWorkflow.cs
  WalletWasabi.Fluent/Models/Wallets/WalletModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletPrivacyModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletRepository.cs
  WalletWasabi.Fluent/Models/Wallets/WalletSettingsModel.cs
  WalletWasabi.Tests/UnitTests/Fluent.Generators/AutoNotifyGeneratorTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/UiContext/NullApplicationSettings.cs
Labels: size/XXL

#11415 Add deploy script and version
  Contrib/deploy.sh
  flake.nix
Labels: size/S

#11390 [VDG] Auto login after Create New Wallet / Recover Wallet
  WalletWasabi.Fluent/Models/Wallets/WalletAuthModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/AddedWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/ConfirmRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/DetectedHardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/TermsAndConditionsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/WalletNamePageViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/CoinJoinProfilesViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/LoginViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/AddedWalletPageView.axaml
Labels: size/L

#11427 [VDG] Combined SourceGenerator: Fix sporadic build error in Visual Studio
  WalletWasabi.Fluent.Generators/Abstractions/GeneratorStep.cs
Labels: size/XS

#11382 TX History Refinement fix: Icon + Tooltip of normal transactions
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/HistoryItemViewModelBase.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/Columns/IndicatorsColumnView.axaml
Labels: size/M

#11422 "Failed to signal ready to sign" - Prison extension
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/OffenderSerializationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PrisonTests.cs
  WalletWasabi/WabiSabi/Backend/DoSPrevention/DoSConfiguration.cs
  WalletWasabi/WabiSabi/Backend/DoSPrevention/Offender.cs
  WalletWasabi/WabiSabi/Backend/DoSPrevention/Prison.cs
  WalletWasabi/WabiSabi/Backend/DoSPrevention/Warden.cs
  WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
Labels: size/S

#11431 Fast signing banning
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
Labels: size/L

#11429 Fix crash during HW import
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/DetectedHardwareWalletViewModel.cs
Labels: size/XS

#11433 [VDG] Fix HistoryViewModelBase error
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/HistoryItemViewModelBase.cs
Labels: size/XS

#10874 [VDG] Bring window to front when shutdown is prevented
  WalletWasabi.Fluent/ApplicationStateManager.cs
  WalletWasabi.Fluent/Extensions/AvaloniaExtensions.cs
Labels: size/M

#11434 [VDG] Use file-scoped namespaces in source generators
  WalletWasabi.Fluent.Generators/Generators/AutoInterfaceAttributeGenerator.cs
  WalletWasabi.Fluent.Generators/Generators/AutoInterfaceGenerator.cs
  WalletWasabi.Fluent.Generators/Generators/AutoNotifyAttributeGenerator.cs
  WalletWasabi.Fluent.Generators/Generators/AutoNotifyGenerator.cs
  WalletWasabi.Fluent.Generators/Generators/FluentNavigationGenerator.cs
  WalletWasabi.Fluent.Generators/Generators/UiContextConstructorGenerator.cs
  WalletWasabi.Fluent.Generators/NavigationMetaDataGenerator.cs
  WalletWasabi.Fluent.Generators/StaticViewLocatorGenerator.cs
Labels: size/L

#11445 New scripts for deploying
  WalletWasabi.Documentation/HowToDeploy.md
  flake.nix
Labels: size/M

#11447 [Trivial] Change namespace to match folder structure
  WalletWasabi.Tests/UnitTests/ViewModels/Mocks.cs
  WalletWasabi.Tests/UnitTests/ViewModels/UiContext/NullApplicationSettings.cs
  WalletWasabi.Tests/UnitTests/ViewModels/UiContext/NullClientConfig.cs
  WalletWasabi.Tests/UnitTests/ViewModels/UiContext/NullClipboard.cs
  WalletWasabi.Tests/UnitTests/ViewModels/UiContext/NullFileSystem.cs
  WalletWasabi.Tests/UnitTests/ViewModels/UiContext/NullHardwareWalletInterface.cs
  WalletWasabi.Tests/UnitTests/ViewModels/UiContext/NullWalletRepository.cs
  WalletWasabi.Tests/UnitTests/ViewModels/UiContextBuilder.cs
Labels: size/S

#11432 [VDG] Privacy Warning: Transaction Known as yours by
  WalletWasabi.Fluent/Models/Transactions/PrivacySuggestionsModel.cs
  WalletWasabi.Fluent/Models/Transactions/PrivacyWarning.cs
  WalletWasabi.Fluent/Views/Wallets/Send/PrivacyWarningsView.axaml
Labels: size/M

#11461 [VDG] Critical privacy warnings
  WalletWasabi.Fluent/Models/Transactions/PrivacySuggestionsModel.cs
  WalletWasabi.Fluent/Models/Transactions/PrivacyWarning.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacySuggestionsFlyoutViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Send/PrivacyWarningsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml
Labels: size/M

#11468 [VDG] Re-enable mark as locked
  WalletWasabi.Fluent/Models/Wallets/Address.cs
Labels: size/XS

#11470 [VDG] Allow only 2 decimals instead of 3 in custom fee rate view
  WalletWasabi.Fluent/Views/Wallets/Send/CustomFeeRateDialogView.axaml
Labels: size/XS

#11456 Install diagnostic tools
  flake.nix
Labels: size/M

#11036 Stop application if CTLR+C is requested early
  WalletWasabi.Daemon/Global.cs
  WalletWasabi.Daemon/WasabiAppBuilder.cs
  WalletWasabi.Fluent.Desktop/Program.cs
  WalletWasabi/Services/Terminate/TerminateService.cs
Labels: size/M

#11453 Fix Smartcoin.IsImmature
  WalletWasabi.Tests/UnitTests/SmartCoinTests.cs
  WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
Labels: size/M

#9695 Remove WW1 code
  WalletWasabi.Backend/Controllers/BatchController.cs
  WalletWasabi.Backend/Controllers/BlockchainController.cs
  WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Backend/InitConfigStartupTask.cs
  WalletWasabi.Daemon/Global.cs
  WalletWasabi.Tests/RegressionTests/RegTestSetup.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi.Tests/UnitTests/CoordinatorRoundTests.cs
  WalletWasabi.Tests/UnitTests/InputsResponseTests.cs
  WalletWasabi.Tests/UnitTests/UtxoRefereeTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/JsonConverters/CompactSignatureJsonConverterTests.cs
  WalletWasabi.Tests/XunitConfiguration/RegTestFixture.cs
  WalletWasabi/Backend/Models/Responses/SynchronizeResponse.cs
  WalletWasabi/CoinJoin/Client/CoinJoinProcessor.cs
  WalletWasabi/CoinJoin/Common/Crypto/SchnorrKey.cs
  WalletWasabi/CoinJoin/Common/Crypto/SchnorrPubKey.cs
  WalletWasabi/CoinJoin/Common/Models/ActiveOutput.cs
  WalletWasabi/CoinJoin/Common/Models/BlindedOutputWithNonceIndex.cs
  WalletWasabi/CoinJoin/Common/Models/ConnectionConfirmationResponse.cs
  WalletWasabi/CoinJoin/Common/Models/HdPubKeyBlindedPair.cs
  WalletWasabi/CoinJoin/Common/Models/InputProofModel.cs
  WalletWasabi/CoinJoin/Common/Models/InputsRequest4.cs
  WalletWasabi/CoinJoin/Common/Models/InputsRequestBase.cs
  WalletWasabi/CoinJoin/Common/Models/InputsResponse.cs
  WalletWasabi/CoinJoin/Common/Models/OutputRequest.cs
  WalletWasabi/CoinJoin/Common/Models/PublicNonceWithIndex.cs
  WalletWasabi/CoinJoin/Common/Models/RoundPhase.cs
  WalletWasabi/CoinJoin/Common/Models/RoundStateResponse4.cs
  WalletWasabi/CoinJoin/Common/Models/RoundStateResponseBase.cs
  WalletWasabi/CoinJoin/Coordinator/Banning/BannedUtxo.cs
  WalletWasabi/CoinJoin/Coordinator/Banning/UtxoReferee.cs
  WalletWasabi/CoinJoin/Coordinator/Coordinator.cs
  WalletWasabi/CoinJoin/Coordinator/MixingLevels/MixingLevel.cs
  WalletWasabi/CoinJoin/Coordinator/MixingLevels/MixingLevelCollection.cs
  WalletWasabi/CoinJoin/Coordinator/Participants/Alice.cs
  WalletWasabi/CoinJoin/Coordinator/Participants/AliceState.cs
  WalletWasabi/CoinJoin/Coordinator/Participants/Bob.cs
  WalletWasabi/CoinJoin/Coordinator/RoundBootstrapper.cs
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRoundConfig.cs
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRoundStatus.cs
  WalletWasabi/CoinJoin/Coordinator/Rounds/RoundNonceProvider.cs
  WalletWasabi/Extensions/NBitcoinExtensions.cs
  WalletWasabi/JsonConverters/CompactSignatureJsonConverter.cs
  WalletWasabi/JsonConverters/RoundStateResponseJsonConverter.cs
  WalletWasabi/Tor/Http/Extensions/HttpContentExtensions.cs
  WalletWasabi/WabiSabi/Backend/Rounds/CoinJoinStorage/CoinJoinIdStore.cs
Labels: size/XXL

#11377 `WalletLoadWorkflow`: Remove active waiting
  WalletWasabi.Fluent/Models/Wallets/WalletLoadWorkflow.cs
  WalletWasabi/Blockchain/Blocks/SmartHeaderChain.cs
  WalletWasabi/Stores/IndexStore.cs
Labels: size/M

#11484 Use build parameters instead of running `git`
  WalletWasabi/WalletWasabi.csproj
  flake.nix
Labels: size/XS

#11471 [refactoring] Move methods out of `TransactionHistoryBuilder`
  WalletWasabi/Blockchain/Transactions/SmartTransactionExtensions.cs
  WalletWasabi/Blockchain/Transactions/TransactionHistoryBuilder.cs
Labels: size/L

#11452 [VDG] Coinjoin profiles: Fix wrong item activation area.
  WalletWasabi.Fluent/Views/CoinJoinProfiles/CoinJoinProfileControl.axaml
  WalletWasabi.Fluent/Views/CoinJoinProfiles/CoinJoinProfilesView.axaml
Labels: size/S

#11485 Change log level from Warning to Error in case of RPCException
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/XS

#11494 Move stand-alone method to CurrencyExtenstion
  WalletWasabi.Fluent/Extensions/CurrencyExtensions.cs
  WalletWasabi.Fluent/Extensions/FeeDisplayUnitExtension.cs
Labels: size/S

#11495 Change logs to Debug when "No suitable coins available"
  WalletWasabi/WabiSabi/Client/CoinJoinCoinSelector.cs
Labels: size/XS

#11473 Abort round by `Arena`
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
Labels: size/M, affiliate

#11508 [VDG] Do not set transaction displayed state if it's coinjoin as it sets two icon styles in indicators column
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/HistoryItemViewModelBase.cs
Labels: size/XS

#11475 [VDG] UI Decoupling #36
  WalletWasabi.Fluent/Extensions/ObservableExtensions.cs
  WalletWasabi.Fluent/Models/Wallets/CoinModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletCoinsModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletModel.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/SelectCoinsDialogViewModel.cs
  WalletWasabi.Tests/UnitTests/ViewModels/ReceiveAddressViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/ReceiveViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/SuggestionLabelsViewModelTests.cs
Labels: size/L

#11476 [VDG] UI Decoupling #37
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyBarItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyBarViewModel.cs
Labels: size/M

#11520 Step forward to Remove `TransactionSummary` (1/n)
  WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
  WalletWasabi.Fluent/Extensions/TransactionSummaryExtensions.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/TransactionDetailsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinsHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/TransactionHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
  WalletWasabi/Blockchain/Transactions/SmartTransactionExtensions.cs
  WalletWasabi/Blockchain/Transactions/TransactionHistoryBuilder.cs
  WalletWasabi/Blockchain/Transactions/TransactionSummary.cs
  WalletWasabi/Extensions/LinqExtensions.cs
Labels: size/M

#11523 better icon for discreet mode
  WalletWasabi.Fluent/ViewModels/Settings/PrivacyModeViewModel.cs
Labels: size/XS

#11512 Pre-calculate Privacy Suggestions for changeless transaction
  WalletWasabi.Fluent/Models/Transactions/PrivacySuggestionsModel.cs
  WalletWasabi.Fluent/Models/Transactions/PrivacySuggestionsResult.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacySuggestionsFlyoutViewModel.cs
Labels: size/L

#11522 [trivial] `Services`: Add `SmartHeaderChain`
  WalletWasabi.Fluent/Extensions/TransactionSummaryExtensions.cs
  WalletWasabi.Fluent/Helpers/CoinHelpers.cs
  WalletWasabi.Fluent/Models/Wallets/WalletLoadWorkflow.cs
  WalletWasabi.Fluent/Models/Wallets/WalletRepository.cs
  WalletWasabi.Fluent/Services.cs
Labels: size/S

#11524 [VDG] Use new discreet mode icon everywhere
  WalletWasabi.Fluent/Controls/PrivacyContentControl.axaml
  WalletWasabi.Fluent/Icons/Icons.axaml
Labels: size/XS

#11530 `TransactionSummary` refactoring (2/n): Remove computations of destination addresses.
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/TransactionDetailsViewModel.cs
  WalletWasabi/Blockchain/Transactions/SmartTransactionExtensions.cs
  WalletWasabi/Blockchain/Transactions/TransactionHistoryBuilder.cs
  WalletWasabi/Blockchain/Transactions/TransactionSummary.cs
Labels: size/S

#11478 [VDG] UI Decoupling #38
  WalletWasabi.Fluent/Extensions/ObservableExtensions.cs
  WalletWasabi.Fluent/Models/Wallets/CoinModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletModelExtensions.cs
  WalletWasabi.Fluent/Models/Wallets/WalletPrivacyModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
Labels: size/M

#11507 TransactionFactory - Fix fee percentage calculation for self spend
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
Labels: size/S

#11545 [VDG] UI Decoupling #39
  WalletWasabi.Fluent/Models/Wallets/CoinModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyRing/PrivacyRingItemDetailsView.axaml
Labels: size/L

#11543 Extract `TransactionSummary.Fee` to an extension method
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/TransactionDetailsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinsHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/TransactionHistoryItemViewModel.cs
  WalletWasabi/Blockchain/Transactions/SmartTransactionExtensions.cs
  WalletWasabi/Blockchain/Transactions/TransactionSummary.cs
Labels: size/M

#11486 [VDG] UI Decoupling #40
  WalletWasabi.Fluent/Models/Wallets/WalletAuthModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletCoinsModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/VerifyRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletSettingsViewModel.cs
Labels: size/M

#11491 [VDG] UI Decoupling #41
  WalletWasabi.Fluent/Models/UI/UiClipboard.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/AddressEntryDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/ShowQrCameraDialogViewModel.cs
  WalletWasabi/Userfacing/Bip21/Bip21UriParser.cs
Labels: size/M

#11492 [VDG] UI Decoupling #42
  WalletWasabi.Fluent/ViewModels/Dialogs/LabelEntryDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
Labels: size/S

#11541 [rpc] `PaymentInfo`: Fix warnings
  WalletWasabi/Rpc/PaymentInfo.cs
Labels: size/XS

#11329 Add words to exclusion.dic
  exclusion.dic
Labels: size/M

#11535 Add `recoverwallet` RPC call
  WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
Labels: size/XS

#11551 Remove obsolete API
  README.md
  WalletWasabi.Backend/Controllers/BatchController.cs
  WalletWasabi.Backend/Controllers/BlockchainController.cs
  WalletWasabi.Backend/Controllers/HomeController.cs
  WalletWasabi.Backend/Controllers/LegacyController.cs
  WalletWasabi.Backend/Controllers/OffchainController.cs
  WalletWasabi.Backend/README.md
  WalletWasabi.Backend/wwwroot/index.html
  WalletWasabi.Tests/RegressionTests/BackendTests.cs
  webpage_ui_compilation-02.png
Labels: size/L

#11555 Speed up transaction processing by 20%
  WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
Labels: size/M

#11561 Speed up transaction processing by 44%
  WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
Labels: size/S

#11550 [Trivial] Add non-words to their group in the spell checker file exclusion.dic
  exclusion.dic
Labels: size/S

#11548 [VDG] Fix for projections of lists that have no items
  WalletWasabi.Fluent/Extensions/ObservableExtensions.cs
  WalletWasabi.Fluent/Models/Wallets/WalletCoinsModel.cs
Labels: size/S

#11529 [VDG] Add confirmation time for coinjoins placeholders
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/CoinJoinDetailsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/CoinJoinsDetailsViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/Details/CoinJoinDetailsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/Details/CoinJoinsDetailsView.axaml
Labels: size/M

#11553 `OffchainController`: Fix warnings
  WalletWasabi.Backend/Controllers/OffchainController.cs
Labels: size/XS

#11572 [trivial] `TransactionProcessor`: Fix accessibility modifiers
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
Labels: size/S

#11574 Clean up useless properties in TransactionProcessor
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
Labels: size/M

#11576 Set `SpenderTransaction` to null in Undo
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
  WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs
Labels: size/XS

#11537 Add `speeduptransaction` RPC method
  WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
Labels: size/S

#11536 Add `canceltransaction` RPC method
  WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
Labels: size/S

#11580 Introduce IsUsed in the CoinsRegistry
  WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
Labels: size/S

#11584 Remove web static content
  WalletWasabi.Backend/Startup.cs
  WalletWasabi.Backend/WalletWasabi.Backend.csproj
Labels: size/XS

#11579 Add `loadwallet` RPC method
  WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
Labels: size/XS

#11578 Punish remixers linearly
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PrisonTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/UtxoPrisonWardenTests.cs
  WalletWasabi/WabiSabi/Backend/DoSPrevention/Prison.cs
Labels: size/S

#11569 [Trivial] Fix typos
  WalletWasabi.Daemon/Config.cs
  WalletWasabi.Daemon/Global.cs
  WalletWasabi.Fluent.Generators/Generators/AutoNotifyGenerator.cs
  WalletWasabi.Fluent.Generators/NavigationMetaDataGenerator.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi.Tests/UnitTests/StartWasabiOnSystemStartupTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
  WalletWasabi/Blockchain/Transactions/SmartTransaction.cs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
  WalletWasabi/Extensions/RPCClientExtensions.cs
Labels: size/L

#11585 [Trivial] Rename image
  README.md
  ui-ww.png
Labels: size/XS

#11575 Fix CPFP + Cancel Regression Tests
  WalletWasabi.Tests/RegressionTests/CancelTests.cs
  WalletWasabi.Tests/RegressionTests/ReceiveSpeedupTests.cs
  WalletWasabi.Tests/RegressionTests/SelfSpendSpeedupTests.cs
Labels: size/S

#11601 Allow decompress Brotli responses automatically
  WalletWasabi/WebClients/Wasabi/WasabiHttpClientFactory.cs
Labels: size/XS

#11606 [Trivial] Fix CodeFactor
  WalletWasabi.Tests/UnitTests/Affiliation/ServerStatusUpdaterTests.cs
  WalletWasabi.Tests/UnitTests/Helpers/PowerSaving/BaseInhibitorTaskTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/UtxoPrisonWardenTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/RoundStateUpdaterTests.cs
Labels: size/S

#11596 [VDG] Use enum for history item status and type
  WalletWasabi.Fluent/Converters/EnumToBoolConverter.cs
  WalletWasabi.Fluent/Converters/TransactionHistoryItemToolTipConverter.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinsHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/HistoryItemViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/SpeedUpHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/TransactionHistoryItemViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/Columns/IndicatorsColumnView.axaml
Labels: size/L

#11603 More descriptive error message when recovering wallet rpc
  WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
Labels: size/S
