Repository WalletWasabi/WalletWasabi, pull requests merged in 2023-11, with the labels that each got.

#11842 [VDG] UI Decoupling #59
  WalletWasabi.Fluent/App.axaml.cs
  WalletWasabi.Fluent/Converters/HealthMonitorStateVisibilityConverter.cs
  WalletWasabi.Fluent/Models/HealthMonitorState.cs
  WalletWasabi.Fluent/Models/UI/ApplicationSettings.cs
  WalletWasabi.Fluent/Models/UI/UiContext.cs
  WalletWasabi.Fluent/Models/Wallets/HealthMonitor.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/StatusIcon/IStatusIconViewModel.cs
  WalletWasabi.Fluent/ViewModels/StatusIcon/StatusIconDesignViewModel.cs
  WalletWasabi.Fluent/ViewModels/StatusIcon/StatusIconViewModel.cs
  WalletWasabi.Fluent/Views/StatusIcon/StatusIcon.axaml
  WalletWasabi.Fluent/Views/StatusIcon/TorIssues.axaml
  WalletWasabi.Tests/UnitTests/ViewModels/TestDoubles/MockUtils.cs
  WalletWasabi.Tests/UnitTests/ViewModels/UiContext/NullApplicationSettings.cs
  WalletWasabi.Tests/UnitTests/ViewModels/UiContextBuilder.cs
Labels: size/XL

#11814 RPC service refactoring
  WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
Labels: size/L

#11739 Add some help to the command line
  WalletWasabi.Daemon/Config.cs
  WalletWasabi.Daemon/WasabiAppBuilder.cs
  WalletWasabi/Extensions/StringExtensions.cs
Labels: size/L

#11850 [VDG] [Trivial] Simplify balances
  WalletWasabi.Fluent/Models/Wallets/WalletModel.cs
Labels: size/XS

#11852 [VDG] Split theme variant resources
  WalletWasabi.Fluent/Styles/Themes/Dark.axaml
  WalletWasabi.Fluent/Styles/Themes/Fluent.axaml
  WalletWasabi.Fluent/Styles/Themes/Light.axaml
  WalletWasabi.Fluent/Styles/Themes/ThemeVariants.axaml
Labels: size/XL

#11851 Don't use PubKey.Hash in HdPubKey equality comparer
  WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
  WalletWasabi.Tests/UnitTests/Transactions/SmartTransactionTests.cs
  WalletWasabi/Blockchain/Keys/HdPubKey.cs
  WalletWasabi/Blockchain/Transactions/SmartTransaction.cs
Labels: size/S

#11855 [Trivial] Use expression body for lambda expressions
  WalletWasabi.Fluent.Desktop/Program.cs
  WalletWasabi.Fluent/Behaviors/DialogTransitionAttachedBehavior.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/ShowQrCameraDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/SettingsPageViewModel.cs
  WalletWasabi.Tests/UnitTests/ViewModels/ReceiveViewModelTests.cs
  WalletWasabi.Tests/UnitTests/Wallet/WalletFilterProcessorTests.cs
Labels: size/M

#11862 Add log when we reject an input for been banned
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
Labels: size/XS

#11845 [VDG] Improvements/use caches
  WalletWasabi.Fluent/Extensions/DynamicDataExtensions.cs
  WalletWasabi.Fluent/Extensions/ObservableExtensions.cs
  WalletWasabi.Fluent/Helpers/SignaledFetcher.cs
  WalletWasabi.Fluent/Models/Wallets/AddressesModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletCoinsModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletRepository.cs
  WalletWasabi.Fluent/Models/Wallets/WalletStatsModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletTransactionsModel.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/LabelEntryDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Features/CancelTransactionDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Features/SpeedUpTransactionDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Notifications/WalletNotificationsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressesViewModel.cs
  WalletWasabi.Tests/UnitTests/ViewModels/ReceiveAddressViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/SuggestionLabelsViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/TestDoubles/AddressTestingMocks.cs
  WalletWasabi.Tests/UnitTests/ViewModels/UiContext/NullWalletRepository.cs
Labels: size/L

#11874 [VDG] [Mobile] Add single lifetime clipboard support
  WalletWasabi.Fluent/Helpers/ApplicationHelper.cs
Labels: size/S

#11771 [VDG] Introduce MaxPrivacyChars for PrivacyContentControl
  WalletWasabi.Fluent/Controls/PrivacyContentControl.axaml
  WalletWasabi.Fluent/Controls/PrivacyContentControl.axaml.cs
  WalletWasabi.Fluent/Controls/PrivacyTextPresenter.cs
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/Columns/LabelsColumnView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/Columns/LabelsColumnView.axaml
  WalletWasabi.Fluent/Views/Wallets/Receive/Columns/LabelsColumnView.axaml
Labels: size/S

#11877 Fix 'addresses awaiting payment' link not displayed when creating new addresses
  WalletWasabi.Fluent/Models/Wallets/AddressesModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletModel.cs
Labels: size/S

#11879 [VDG] Fix wallet info bypass
  WalletWasabi.Fluent/ViewModels/Wallets/WalletPageViewModel.cs
Labels: size/XS

#11880 [UI] fix lag
  WalletWasabi.Fluent/Models/Wallets/WalletModel.cs
Labels: size/XS

#11878 [VDG] Fix "Send" is available even when no balance in Search Bar.
  WalletWasabi.Fluent/Extensions/CommandExtension.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/SearchItems/NestedItemConfiguration.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/SearchItems/SearchItemNode.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/SettingsSearchSource.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/Sources/EditableSearchSourceExtensions.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
Labels: size/L

#11899 [UI] remove leftover
  WalletWasabi.Fluent/Models/Wallets/CoinjoinModel.cs
Labels: size/XS

#11882 [UI] refactor to remove `TransactionSummary` from `TransactionModel`
  WalletWasabi.Fluent/Converters/TransactionHistoryItemToolTipConverter.cs
  WalletWasabi.Fluent/Models/Wallets/TransactionModel.cs
  WalletWasabi.Fluent/Models/Wallets/TransactionTreeBuilder.cs
  WalletWasabi.Fluent/Models/Wallets/WalletTransactionsModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/CoinJoinDetailsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/CoinJoinsDetailsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/TransactionDetailsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/TransactionHistoryItemViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/Columns/IndicatorsColumnView.axaml
  WalletWasabi/Blockchain/Transactions/SmartTransactionExtensions.cs
Labels: size/L

#11853 [VDG] Add blur effect to background when dialog is shown
  WalletWasabi.Fluent/Views/Shell/Shell.axaml
Labels: size/M

#11847 [VDG] Add headless unit testing
  Directory.Packages.props
  WalletWasabi.Tests/UnitTests/Fluent/App.axaml
  WalletWasabi.Tests/UnitTests/Fluent/App.axaml.cs
  WalletWasabi.Tests/UnitTests/Fluent/Controls/AmountControlTests/AmountControlTests.cs
  WalletWasabi.Tests/UnitTests/Fluent/Controls/AmountControlTests/AmountControl_Defaults.axaml
  WalletWasabi.Tests/UnitTests/Fluent/Controls/AmountControlTests/AmountControl_Defaults.axaml.cs
  WalletWasabi.Tests/UnitTests/Fluent/Controls/AnimatedButtonTests/AnimatedButtonTests.cs
  WalletWasabi.Tests/UnitTests/Fluent/Controls/AnimatedButtonTests/AnimatedButton_Defaults.axaml
  WalletWasabi.Tests/UnitTests/Fluent/Controls/AnimatedButtonTests/AnimatedButton_Defaults.axaml.cs
  WalletWasabi.Tests/UnitTests/Fluent/HeadlessWindowExtensions.cs
  WalletWasabi.Tests/UnitTests/Fluent/TestAppBuilder.cs
  WalletWasabi.Tests/WalletWasabi.Tests.csproj
Labels: size/L

#11906 [VDG] Use EffectTransition instead of Animations for dialog background blur
  WalletWasabi.Fluent/Views/Shell/Shell.axaml
Labels: size/M

#11894 Expose poisson scheduling in DateTimeOffset extension method
  WalletWasabi/Extensions/DateTimeOffsetExtensions.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/M

#11912 [VDG] [Mobile] Use built-in OnPlatform extension
  WalletWasabi.Fluent/Helpers/PlatformExtension.cs
  WalletWasabi.Fluent/Views/Shell/TitleBar.axaml
Labels: size/M

#11932 [VDG] Quick fix for TreeDataGrid.ShowColumnHeaders=false
  WalletWasabi.Fluent/Controls/LabelsPanel.cs
Labels: size/XS

#11939 Keep offenders grouped by txid.
  WalletWasabi/WabiSabi/Backend/DoSPrevention/Prison.cs
Labels: size/M

#11940 Reduce the punishment by half for offenders who spent.
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PrisonTests.cs
  WalletWasabi/WabiSabi/Backend/DoSPrevention/Prison.cs
Labels: size/M

#11937 [VDG] Fix NavBar issues
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
Labels: size/XS

#11943 [Trivial] Remove redundant WW1 status property
  WalletWasabi/Backend/Models/Responses/StatusResponse.cs
Labels: size/XS

#11952 Fix Analyzer version
  Directory.Packages.props
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent.Generators/packages.lock.json
  WalletWasabi.Fluent/packages.lock.json
Labels: size/M

#11953 [VDG] Add Fee Rate to Transaction Details
  WalletWasabi.Fluent/Models/Wallets/TransactionModel.cs
  WalletWasabi.Fluent/Models/Wallets/TransactionTreeBuilder.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/TransactionDetailsViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/Details/TransactionDetailsView.axaml
  WalletWasabi/Blockchain/Transactions/TransactionSummary.cs
Labels: size/S

#11968 [UI] correct FeeRate unit
  WalletWasabi.Fluent/Converters/FeeRateConverters.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/Details/TransactionDetailsView.axaml
Labels: size/S

#11969 [VDG] Correct units for Fee Rate
  WalletWasabi.Fluent/Converters/FeeRateConverters.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/Details/TransactionDetailsView.axaml
Labels: size/S

#11891 ISSUE_TEMPLATE: comment out example/help text
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: size/S

#11946 Detecting and (avoid) Banning Wasabi coinjoins
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/CoordinatorTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/OffenderSerializationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PrisonTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/UtxoPrisonWardenTests.cs
  WalletWasabi/Extensions/LinqExtensions.cs
  WalletWasabi/WabiSabi/Backend/DoSPrevention/Offender.cs
  WalletWasabi/WabiSabi/Backend/DoSPrevention/Prison.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
  WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
Labels: size/L

#11977 Changed string format to 1 number after dot.
  WalletWasabi.Fluent/Views/Wallets/Home/History/Details/TransactionDetailsView.axaml
Labels: size/XS

#11958 Reduce and randomize local banning time if the banning time is absurdly long
  WalletWasabi.Daemon/Global.cs
  WalletWasabi/WabiSabi/Client/Banning/CoinPrison.cs
Labels: size/M

#11981 [v2.0.4.1 Silent Release] Local Prison invalidation
  WalletWasabi.Daemon/Global.cs
  WalletWasabi/WabiSabi/Client/Banning/CoinPrison.cs
Labels: size/M

#11980 [v2.0.4.1 Silent Release] Bump version to 2.0.4.1
  WalletWasabi/Helpers/Constants.cs
Labels: size/XS

#11983 Bump version to 2.0.4.1 on master
  WalletWasabi/Helpers/Constants.cs
Labels: size/XS

#11970 [VDG] Add new Privacy Bar
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyControlTileView.axaml
Labels: size/M

#11986 Shutdown Wasabi with Ctrl-C even when "Run in background" is enabled | Take 2
  WalletWasabi.Fluent/ApplicationStateManager.cs
  WalletWasabi.Fluent/Providers/ICanShutdownProvider.cs
  WalletWasabi.Fluent/ViewModels/ApplicationViewModel.cs
Labels: size/M

#11987 Use `TransactionFactoryParameters` in tests
  WalletWasabi.Tests/Helpers/ServiceFactory.cs
  WalletWasabi.Tests/Helpers/TransactionParametersBuilder.cs
  WalletWasabi.Tests/UnitTests/Transactions/PayjoinTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
  WalletWasabi/Blockchain/TransactionBuilding/TransactionBuilderWalletExtensions.cs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
Labels: size/L

#12004 Add Login logic and test
  WalletWasabi.Tests/IntegrationTests/ShopWareApiClientTests.cs
  WalletWasabi/BuyAnything/BuyAnythingManager.cs
  WalletWasabi/WebClients/BuyAnything/BuyAnythingClient.cs
  WalletWasabi/WebClients/ShopWare/Models/Customer.cs
  WalletWasabi/WebClients/ShopWare/ShopWareApiClient.cs
Labels: size/M

#12006 Make sure we all use the same C# lang version
  WalletWasabi.Backend/WalletWasabi.Backend.csproj
  WalletWasabi.Daemon/WalletWasabi.Daemon.csproj
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent.Generators/WalletWasabi.Fluent.Generators.csproj
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Packager/WalletWasabi.Packager.csproj
  WalletWasabi.Tests/WalletWasabi.Tests.csproj
  WalletWasabi/WalletWasabi.csproj
Labels: size/S
