Repository WalletWasabi/WalletWasabi, pull requests merged in 2023-08, with the labels that each got.

#11164 Fix Tor tests
  WalletWasabi.Tests/IntegrationTests/TorTests.cs
  WalletWasabi/Tor/Http/TorHttpClient.cs
Labels: size/L

#11086 Use NoCoinsEligibleToMix instead of AllCoinsPrivate if all candidates are private
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Labels: size/XS

#11185 Truncate `TorLogs.txt` when Tor starts
  WalletWasabi.Tests/UnitTests/Tor/TorSettingsTests.cs
  WalletWasabi/Tor/TorSettings.cs
Labels: size/XS

#11166 [VDG] Go back when transaction is confirmed
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Features/CancelTransactionDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Features/SpeedUpTransactionDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/TransactionHistoryItemViewModel.cs
Labels: UI, size/M

#11178 Fix LiveServer tests
  WalletWasabi.Daemon/PersistentConfig.cs
  WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
  WalletWasabi.Tests/XunitConfiguration/LiveServerTestsFixture.cs
  WalletWasabi/Helpers/Constants.cs
Labels: size/L

#11065 Redesign filter processing
  WalletWasabi.Fluent/Models/UiTriggers.cs
  WalletWasabi.Tests/RegressionTests/BuildTransactionReorgsTest.cs
  WalletWasabi.Tests/RegressionTests/BuildTransactionValidationsTest.cs
  WalletWasabi.Tests/RegressionTests/CancelTests.cs
  WalletWasabi.Tests/RegressionTests/FilterDownloaderTest.cs
  WalletWasabi.Tests/RegressionTests/ReceiveSpeedupTests.cs
  WalletWasabi.Tests/RegressionTests/RegTestSetup.cs
  WalletWasabi.Tests/RegressionTests/ReorgTest.cs
  WalletWasabi.Tests/RegressionTests/ReplaceByFeeTxTest.cs
  WalletWasabi.Tests/RegressionTests/SelfSpendSpeedupTests.cs
  WalletWasabi.Tests/RegressionTests/SendSpeedupTests.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi.Tests/RegressionTests/SpendUnconfirmedTxTests.cs
  WalletWasabi.Tests/RegressionTests/WalletTests.cs
  WalletWasabi.Tests/UnitTests/Wallet/WalletBuilder.cs
  WalletWasabi.Tests/UnitTests/Wallet/WalletFilterProcessorTests.cs
  WalletWasabi.Tests/UnitTests/Wallet/WalletSynchronizationTests.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/Stores/IndexStore.cs
  WalletWasabi/Wallets/Wallet.cs
  WalletWasabi/Wallets/WalletFilterProcessor.cs
Labels: size/XL

#11182 Remove `selectwallet` rpc call
  WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
Labels: size/XS

#11200 Fix BuildTransactionValidationsTestAsync
  WalletWasabi.Tests/RegressionTests/BuildTransactionValidationsTest.cs
Labels: size/XS

#11211 Get txs with witness data
  WalletWasabi/BitcoinP2p/P2pBehavior.cs
Labels: size/XS

#11170 Refine detection of who's paying
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Features/SpeedUpTransactionDialogViewModel.cs
Labels: size/S

#11168 Reintroduce CoinGecko rate provider
  WalletWasabi.Tests/IntegrationTests/ExternalApiTests.cs
  WalletWasabi/WebClients/CoinGecko/CoinGeckoExchangeRate.cs
  WalletWasabi/WebClients/CoinGecko/CoinGeckoExchangeRateProvider.cs
  WalletWasabi/WebClients/ExchangeRateProviders.cs
Labels: size/M

#11155 [Trivial] Unify warning messages for the Cancel/Speed up dialogs
  WalletWasabi.Fluent/Controls/QuestionControl.axaml
  WalletWasabi.Fluent/Controls/QuestionControl.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/Features/CancelTransactionDialogView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/Features/SpeedUpTransactionDialogView.axaml
  WalletWasabi/Blockchain/TransactionBuilding/TransactionModifierWalletExtensions.cs
  WalletWasabi/Services/SingleInstanceChecker.cs
Labels: size/M

#11210 [VDG] Speed-up / Cancel: Make transaction lookup fail-safe
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Features/CancelTransactionDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Features/SpeedUpTransactionDialogViewModel.cs
Labels: size/S

#11216 [VDG] [trivial] remove CopyableContent from confirmation time
  WalletWasabi.Fluent/Views/Wallets/Home/History/Details/TransactionDetailsView.axaml
Labels: size/XS

#11212 [VDG] SpeedUp&Cancel - use compact dialogs and `ContentArea`
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Features/CancelTransactionDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Features/SpeedUpTransactionDialogViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/Features/CancelTransactionDialogView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/Features/SpeedUpTransactionDialogView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/SendSuccessView.axaml
Labels: size/L

#11197 [VDG] Set the slider value only once
  WalletWasabi.Fluent/ViewModels/Wallets/Send/FeeChartViewModel.cs
Labels: size/XS

#11221 Fix SpentCoinsByOutPoint is not updated
  WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
Labels: size/M

#11217 Cache slow `synchronize` response
  WalletWasabi.Backend/Controllers/BatchController.cs
Labels: size/M

#11223 `AllFeeEstimate`: Fix parameter name
  WalletWasabi/Blockchain/Analysis/FeesEstimation/AllFeeEstimate.cs
Labels: size/XS

#11218 [VDG] Change success dialog wording for cancel and speedup
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Features/CancelTransactionDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Features/SpeedUpTransactionDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendSuccessViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Send/SendSuccessView.axaml
Labels: size/S

#11163 [VDG] Change PrivacyWarnings to IAsyncEnumerable
  WalletWasabi.Fluent/Extensions/EnumerableExtension.cs
  WalletWasabi.Fluent/Models/Transactions/PrivacyItem.cs
  WalletWasabi.Fluent/Models/Transactions/PrivacySuggestion.cs
  WalletWasabi.Fluent/Models/Transactions/PrivacySuggestionsModel.cs
  WalletWasabi.Fluent/Models/Transactions/PrivacySuggestionsResult.cs
  WalletWasabi.Fluent/Models/Transactions/PrivacyWarning.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacySuggestionsFlyoutViewModel.cs
Labels: size/L

#11201 Fix authentication in wcli.sh
  Contrib/CLI/wcli.sh
Labels: size/XS

#11213 [VDG] Fee Chart - fix mid value
  WalletWasabi.Fluent/ViewModels/Wallets/Send/FeeChartViewModel.cs
Labels: size/XS

#11187 [VDG] Remove WatchOnlyWalletViewModel
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WatchOnlyWalletViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/WatchOnlyWalletView.axaml
  WalletWasabi.Fluent/Views/Wallets/WatchOnlyWalletView.axaml.cs
Labels: size/M

#11083 [VDG] MusicBox - Fix confusing messages
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WabiSabi/Client/StatusChangedEvents/StatusChangedEventArgs.cs
Labels: size/M

#11229 [VDG] Fixes NullReferenceException exception in ContextFlyoutWorkaroundBehavior
  WalletWasabi.Fluent/Behaviors/ContextFlyoutWorkaroundBehavior.cs
Labels: size/S

#11228 temp fix: make `CoinJoinClient started` debug log level
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Labels: size/XS

#11080 Use same json serialization settings on client and server
  WalletWasabi.Backend/Startup.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/Startup.cs
  WalletWasabi/Tor/Http/Extensions/HttpResponseMessageExtensions.cs
Labels: size/S

#11232 Change wrong usage of containingTx by spendingTx
  WalletWasabi/Blockchain/Transactions/TransactionHistoryBuilder.cs
Labels: size/XS

#11237 Bump version to v2.0.4
  WalletWasabi.Backend/wwwroot/index.html
  WalletWasabi/Helpers/Constants.cs
Labels: size/S

#11238 Revert "Bump version to v2.0.4"
  WalletWasabi.Backend/wwwroot/index.html
  WalletWasabi/Helpers/Constants.cs
Labels: size/S

#11174 [VDG] CurrencyEntryBox - Improve ContextMenu's Paste
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
  WalletWasabi.Fluent/Controls/DualCurrencyEntryBox.axaml
  WalletWasabi.Fluent/Controls/DualCurrencyEntryBox.axaml.cs
  WalletWasabi.Fluent/Infrastructure/ClipboardObserver.cs
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Labels: size/L

#11234 Starter script for `wassabeed`
  WalletWasabi.Packager/Program.cs
Labels: size/XS

#11078 Fix warnings in `VersionsResponse`
  WalletWasabi/Backend/Models/Responses/VersionsResponse.cs
Labels: size/S

#11247 `IndexBuilderService`: Remove `RpcClient.GetBlockHashAsync` from the critical section
  WalletWasabi/Blockchain/BlockFilters/IndexBuilderService.cs
Labels: size/M

#11236 Cancellation TX to reset input AS
  WalletWasabi.Tests/RegressionTests/CancelTests.cs
  WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs
Labels: size/M

#11063 Update low-risk dependencies
  Directory.Packages.props
  WalletWasabi.Daemon/packages.lock.json
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent.Generators/packages.lock.json
  WalletWasabi.Fluent/packages.lock.json
  WalletWasabi.Packager/packages.lock.json
  WalletWasabi/packages.lock.json
Labels: size/L

#11248 Fix build
  WalletWasabi.Fluent.Generators/UIContextGenerator.cs
Labels: size/XS

#11251 [2.0.4] Create script wassabeed
  WalletWasabi.Packager/Program.cs
Labels: size/XS

#10885 Coins those aren't sufficiently distanced from external keys shall not be considered private
  WalletWasabi.Fluent/Helpers/CoinHelpers.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingItemViewModel.cs
  WalletWasabi.Tests/Helpers/BitcoinFactory.cs
  WalletWasabi.Tests/RegressionTests/SendSpeedupTests.cs
  WalletWasabi.Tests/UnitTests/SmartCoinTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/CoinJoinCoinSelectionTests.cs
  WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs
  WalletWasabi/Blockchain/TransactionOutputs/ISmartCoin.cs
  WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
  WalletWasabi/Helpers/CoinHelpers.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/L

#11064 Update NBitcoin + coverlet dependencies
  Directory.Packages.props
  WalletWasabi.Daemon/packages.lock.json
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent.Generators/packages.lock.json
  WalletWasabi.Fluent/packages.lock.json
  WalletWasabi.Packager/packages.lock.json
  WalletWasabi/Crypto/OwnershipIdentifier.cs
  WalletWasabi/Crypto/ProofBody.cs
  WalletWasabi/packages.lock.json
Labels: size/L

#11260 Pause CJ after recovery
  WalletWasabi.Fluent/Models/Wallets/IWalletSettingsModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletRepository.cs
  WalletWasabi.Fluent/Models/Wallets/WalletSettingsModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
Labels: size/M

#11249 Remove Moq
  WalletWasabi.Tests/Helpers/ArenaBuilder.cs
  WalletWasabi.Tests/Helpers/ServiceFactory.cs
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/RegressionTests/CoinVerifierApiClientStressTests.cs
  WalletWasabi.Tests/UnitTests/Affiliation/ServerStatusUpdaterTests.cs
  WalletWasabi.Tests/UnitTests/AllFeeEstimateTests.cs
  WalletWasabi.Tests/UnitTests/Clients/WasabiClientTests.cs
  WalletWasabi.Tests/UnitTests/Helpers/PowerSaving/BaseInhibitorTaskTests.cs
  WalletWasabi.Tests/UnitTests/MockIHttpClient.cs
  WalletWasabi.Tests/UnitTests/MockTorTcpConnectionFactory.cs
  WalletWasabi.Tests/UnitTests/Tor/Socks5/Pool/TorHttpPoolTests.cs
  WalletWasabi.Tests/UnitTests/Tor/TorProcessManagerTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/PayjoinTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/CoinVerifierTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/ConfigTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/CoordinatorTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepInputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/IWebHostBuilderExtensions.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiApiApplicationFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/RoundStateUpdaterTests.cs
  WalletWasabi.Tests/UnitTests/Wallet/WalletBuilder.cs
  WalletWasabi.Tests/UnitTests/Wallets/SmartBlockProviderTests.cs
  WalletWasabi/BitcoinCore/Mempool/IMempoolMirror.cs
  WalletWasabi/BitcoinCore/Mempool/MempoolMirror.cs
  WalletWasabi/WabiSabi/Backend/CoinJoinMempoolManager.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WebClients/Wasabi/IWasabiHttpClientFactory.cs
Labels: size/XXL

#11242 [VDG] Fix wrong algorithm to create pockets
  WalletWasabi.Fluent/Helpers/CoinPocketHelper.cs
  WalletWasabi.Fluent/Helpers/LabelsComparer.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
Labels: size/M

#11280 Revert "Use same json serialization settings on client and server"
  WalletWasabi.Backend/Startup.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/Startup.cs
  WalletWasabi/Tor/Http/Extensions/HttpResponseMessageExtensions.cs
Labels: size/S

#11284 [2.0.4] Fix pocket generation
  WalletWasabi.Fluent/Helpers/CoinPocketHelper.cs
  WalletWasabi.Fluent/Helpers/LabelsComparer.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
Labels: size/M

#10756 [VDG] UI Decoupling #29
  WalletWasabi.Fluent/ViewModels/AddWallet/WelcomePageViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
Labels: size/S

#10821 [VDG] UI Decoupling #30
  WalletWasabi.Fluent.Generators/UIContextGenerator.cs
  WalletWasabi.Fluent/Models/ClientConfig/ClientConfig.cs
  WalletWasabi.Fluent/Models/ClientConfig/IClientConfig.cs
  WalletWasabi.Fluent/Models/ClientConfig/NullClientConfig.cs
  WalletWasabi.Fluent/Models/FileSystem/FileSystemModel.cs
  WalletWasabi.Fluent/Models/FileSystem/IFileSystem.cs
  WalletWasabi.Fluent/Models/FileSystem/NullFileSystem.cs
  WalletWasabi.Fluent/Models/UI/UiContext.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/OpenDirectory/OpenConfigFileViewModel.cs
  WalletWasabi.Fluent/ViewModels/OpenDirectory/OpenDataFolderViewModel.cs
  WalletWasabi.Fluent/ViewModels/OpenDirectory/OpenFileViewModel.cs
  WalletWasabi.Fluent/ViewModels/OpenDirectory/OpenLogsViewModel.cs
  WalletWasabi.Fluent/ViewModels/OpenDirectory/OpenTorLogsViewModel.cs
  WalletWasabi.Fluent/ViewModels/OpenDirectory/OpenWalletsFolderViewModel.cs
  WalletWasabi.Tests/UnitTests/ViewModels/Mocks.cs
  WalletWasabi.Tests/UnitTests/ViewModels/UiContextBuilder.cs
Labels: size/L

#10822 [VDG] UI Decoupling #31
  WalletWasabi.Fluent/Models/FileSystem/FileSystemModel.cs
  WalletWasabi.Fluent/Models/FileSystem/IFileSystem.cs
  WalletWasabi.Fluent/Models/FileSystem/NullFileSystem.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/AboutAdvancedInfoViewModel.cs
  WalletWasabi.Fluent/ViewModels/HelpAndSupport/AboutViewModel.cs
  WalletWasabi.Fluent/ViewModels/HelpAndSupport/BugReportLinkViewModel.cs
  WalletWasabi.Fluent/ViewModels/HelpAndSupport/DocsLinkViewModel.cs
  WalletWasabi.Fluent/ViewModels/HelpAndSupport/LinkViewModel.cs
  WalletWasabi.Fluent/ViewModels/HelpAndSupport/UserSupportViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
Labels: size/L

#11274 Make filter migration cancellable
  WalletWasabi/Stores/IndexStore.cs
Labels: size/S

#11290 [v2.0.4] Make filter migration cancellable
  WalletWasabi/Stores/IndexStore.cs
Labels: size/S

#11291 [trivial] bump Fedora minimal version requirement
  WalletWasabi.Documentation/WasabiCompatibility.md
Labels: size/XS

#11292 [v2.0.4] tx details: clarify expected confirmation time
  WalletWasabi.Fluent/Views/Wallets/Home/History/Details/TransactionDetailsView.axaml
Labels: size/XS

#11188 [VDG] UI Decoupling #34
  WalletWasabi.Fluent/Models/Wallets/IWalletInfoModel.cs
  WalletWasabi.Fluent/Models/Wallets/IWalletModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletInfoModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletInfoViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletInfoView.axaml
  WalletWasabi.Tests/UnitTests/ViewModels/ReceiveAddressViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/ReceiveViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/SuggestionLabelsViewModelTests.cs
Labels: size/L

#11282 Cache big responses
  WalletWasabi.Backend/Controllers/BlockchainController.cs
  WalletWasabi.Backend/Controllers/OffchainController.cs
Labels: size/XS

#11272 Ellipsis for long text
  WalletWasabi.Fluent/Views/SearchBar/SearchBarDropdown.axaml
Labels: size/S

#11288 [VDG] Preview Transaction: update confirmation time label text
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionSummary.axaml
Labels: size/XS

#11283 [VDG] UI Decoupling #35
  WalletWasabi.Fluent/Models/Wallets/IWalletCoinjoinModel.cs
  WalletWasabi.Fluent/Models/Wallets/IWalletModel.cs
  WalletWasabi.Fluent/Models/Wallets/IWalletPrivacyModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletCoinjoinModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletPrivacyModel.cs
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/CoinJoinProfilesViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Tests/UnitTests/ViewModels/ReceiveAddressViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/ReceiveViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/SuggestionLabelsViewModelTests.cs
Labels: size/L

#11169 Hardcode delay before signing
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi/Extensions/TimeSpanExtensions.cs
  WalletWasabi/WabiSabi/Backend/Rounds/RoundParameters.cs
  WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/M, affiliate

#11305 Fix: Add TurboSyncHeight reset to SetMaxBestHeight
  WalletWasabi/Blockchain/Keys/KeyManager.cs
Labels: size/S

#11299 [v2.0.4] Preview Transaction: update confirmation time label text
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionSummary.axaml
Labels: size/XS

#11306 Process filters while downloading them
  WalletWasabi.Fluent/Models/Wallets/WalletLoadWorkflow.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/S

#11324 [v2.0.4] Process filters while downloading them from turbolay
  WalletWasabi.Fluent/Models/Wallets/WalletLoadWorkflow.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/S

#11330 [Trivial] Fix repo image
  README.md
  WalletWasabi.Backend/wwwroot/webpage_ui_compilation-02.png
Labels: size/XS

#11307 Rename `HttpClientFactory` to `WasabiHttpClientFactory` and introduce `CreateLongLivedHttpClient` helper
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Daemon/Global.cs
  WalletWasabi.Fluent/Services.cs
  WalletWasabi.Tests/IntegrationTests/BlockstreamInfoClientTests.cs
  WalletWasabi.Tests/IntegrationTests/P2pTests.cs
  WalletWasabi.Tests/RegressionTests/BuildTransactionReorgsTest.cs
  WalletWasabi.Tests/RegressionTests/BuildTransactionValidationsTest.cs
  WalletWasabi.Tests/RegressionTests/CancelTests.cs
  WalletWasabi.Tests/RegressionTests/FilterDownloaderTest.cs
  WalletWasabi.Tests/RegressionTests/ReceiveSpeedupTests.cs
  WalletWasabi.Tests/RegressionTests/ReorgTest.cs
  WalletWasabi.Tests/RegressionTests/ReplaceByFeeTxTest.cs
  WalletWasabi.Tests/RegressionTests/SelfSpendSpeedupTests.cs
  WalletWasabi.Tests/RegressionTests/SendSpeedupTests.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi.Tests/RegressionTests/SpendUnconfirmedTxTests.cs
  WalletWasabi.Tests/RegressionTests/WalletTests.cs
  WalletWasabi.Tests/UnitTests/Wallet/WalletBuilder.cs
  WalletWasabi/Blockchain/Mempool/MempoolService.cs
  WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs
  WalletWasabi/Services/WasabiSynchronizer.cs
  WalletWasabi/Tor/Http/IHttpClient.cs
  WalletWasabi/Tor/TorMonitor.cs
  WalletWasabi/WebClients/BlockstreamInfo/BlockstreamInfoClient.cs
  WalletWasabi/WebClients/Wasabi/WasabiHttpClientFactory.cs
  exclusion.dic
Labels: size/L

#11320 `Wallet`: Variable is casted anyway
  WalletWasabi/Wallets/Wallet.cs
Labels: size/XS

#11336 Bump version on master
  WalletWasabi/Helpers/Constants.cs
Labels: size/XS

#10888 Disable WW1 gracefully
  WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
  WalletWasabi.Backend/Filters/DeprecatedAttibute.cs
Labels: size/S

#11308 [VDG] Decouple view models from Avalonia platform interface IClipboard
  WalletWasabi.Fluent/App.axaml.cs
  WalletWasabi.Fluent/Models/UI/IUiClipboard.cs
  WalletWasabi.Fluent/Models/UI/NullClipboard.cs
  WalletWasabi.Fluent/Models/UI/UiClipboard.cs
  WalletWasabi.Fluent/Models/UI/UiContext.cs
  WalletWasabi.Tests/UnitTests/ViewModels/Mocks.cs
  WalletWasabi.Tests/UnitTests/ViewModels/ReceiveAddressViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/UiContextBuilder.cs
Labels: size/L

#11351 Add AnonScoreTarget to RPC call getwalletinfo
  WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
Labels: size/XS

#11350 Add RPC fee rates
  WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
Labels: size/S

#11246 Update the current tip height in WalletLoadWorkflow
  WalletWasabi.Fluent/Models/Wallets/WalletLoadWorkflow.cs
Labels: size/S

#11357 Bump required .NET SDK version to 7.0.200
  global.json
Labels: size/XS

#11359 Fix broken music box
  WalletWasabi.Fluent/Models/Wallets/WalletCoinjoinModel.cs
Labels: size/XS

#11360 [VDG] Fix dark mode toggle
  WalletWasabi.Fluent/ViewModels/Settings/GeneralSettingsTabViewModel.cs
  WalletWasabi.Fluent/Views/Settings/GeneralSettingsTabView.axaml
Labels: size/XS

#11338 Fix Wasabi crash if exception happens after PreviewTx screen
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
Labels: size/M

#11371 [VDG] Remove PrivacyBar Segments
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyBarViewModel.cs
Labels: size/M

#11302 [VDG] Fix WalletModel multiple instances
  WalletWasabi.Fluent/Models/Wallets/IWalletRepository.cs
  WalletWasabi.Fluent/Models/Wallets/IWalletSettingsModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletRepository.cs
  WalletWasabi.Fluent/Models/Wallets/WalletSettingsModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Tests/UnitTests/ViewModels/UiContext/NullWalletRepository.cs
Labels: size/M

#11348 [VDG] Fix fee chart when there is only one fee estimation
  WalletWasabi.Fluent/Controls/LineChart.Properties.cs
  WalletWasabi.Fluent/Controls/LineChart.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/FeeChartViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Send/SendFeeView.axaml
Labels: size/M

#11369 [VDG] Skip wallet name page for first wallet creation
  WalletWasabi.Fluent/ViewModels/AddWallet/WalletNamePageViewModel.cs
Labels: size/S

#11364 Punish descendants
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/OffenderSerializationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PrisonTests.cs
  WalletWasabi/WabiSabi/Backend/DoSPrevention/Offender.cs
  WalletWasabi/WabiSabi/Backend/DoSPrevention/Prison.cs
  WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
Labels: size/L

#11372 Ban doublespenders
  WalletWasabi.Backend/Global.cs
  WalletWasabi/BitcoinCore/P2pNode.cs
  WalletWasabi/BitcoinP2p/P2pBehavior.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
  WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
Labels: size/M

#11392 [VDG] MusicBox - remove fade out on messages
  WalletWasabi.Fluent/Views/Wallets/MusicControlsView.axaml
Labels: size/S

#11387 Create ReleaseNotesTemplate.md
  WalletWasabi.Documentation/ClientRelease/ClientDeployment.md
  WalletWasabi.Documentation/ClientRelease/ReleaseNotesTemplate.md
Labels: size/M

#11395 Revert `RoundParameter` that made clients to trust
  WalletWasabi/WabiSabi/Backend/Rounds/RoundParameters.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/S
