Repository WalletWasabi/WalletWasabi, pull requests merged in 2023-07, with the labels that each got.

#10963 Fixed a crash on Ctrl+C termination
  WalletWasabi.Fluent.Desktop/Program.cs
Labels: size/XS

#10962 [VDG] Used ZXing from QRackers
  Directory.Packages.props
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/Models/UI/QrCodeReader.cs
  WalletWasabi.Fluent/ZXing/.editorconfig
  WalletWasabi.Fluent/ZXing/AlignmentPattern.cs
  WalletWasabi.Fluent/ZXing/AlignmentPatternFinder.cs
  WalletWasabi.Fluent/ZXing/BarcodeFormat.cs
  WalletWasabi.Fluent/ZXing/BaseLuminanceSource.cs
  WalletWasabi.Fluent/ZXing/Binarizer.cs
  WalletWasabi.Fluent/ZXing/BinaryBitmap.cs
  WalletWasabi.Fluent/ZXing/BitArray.cs
  WalletWasabi.Fluent/ZXing/BitMatrix.cs
  WalletWasabi.Fluent/ZXing/BitMatrixParser.cs
  WalletWasabi.Fluent/ZXing/BitSource.cs
  WalletWasabi.Fluent/ZXing/CharacterSetECI.cs
  WalletWasabi.Fluent/ZXing/DataBlock.cs
  WalletWasabi.Fluent/ZXing/DataMask.cs
  WalletWasabi.Fluent/ZXing/DecodeHintType.cs
  WalletWasabi.Fluent/ZXing/DecodedBitStreamParser.cs
  WalletWasabi.Fluent/ZXing/Decoder.cs
  WalletWasabi.Fluent/ZXing/DecoderResult.cs
  WalletWasabi.Fluent/ZXing/DefaultGridSampler.cs
  WalletWasabi.Fluent/ZXing/Detector.cs
  WalletWasabi.Fluent/ZXing/DetectorResult.cs
  WalletWasabi.Fluent/ZXing/ECI.cs
  WalletWasabi.Fluent/ZXing/ErrorCorrectionLevel.cs
  WalletWasabi.Fluent/ZXing/FinderPattern.cs
  WalletWasabi.Fluent/ZXing/FinderPatternFinder.cs
  WalletWasabi.Fluent/ZXing/FinderPatternInfo.cs
  WalletWasabi.Fluent/ZXing/FormatInformation.cs
  WalletWasabi.Fluent/ZXing/GenericGF.cs
  WalletWasabi.Fluent/ZXing/GenericGFPoly.cs
  WalletWasabi.Fluent/ZXing/GlobalHistogramBinarizer.cs
  WalletWasabi.Fluent/ZXing/GridSampler.cs
  WalletWasabi.Fluent/ZXing/HybridBinarizer.cs
  WalletWasabi.Fluent/ZXing/InvertedLuminanceSource.cs
  WalletWasabi.Fluent/ZXing/LICENSE.md
  WalletWasabi.Fluent/ZXing/LuminanceSource.cs
  WalletWasabi.Fluent/ZXing/MathUtils.cs
  WalletWasabi.Fluent/ZXing/Mode.cs
  WalletWasabi.Fluent/ZXing/PerspectiveTransform.cs
  WalletWasabi.Fluent/ZXing/QRCodeDecoderMetaData.cs
  WalletWasabi.Fluent/ZXing/QRCodeReader.cs
  WalletWasabi.Fluent/ZXing/Reader.cs
  WalletWasabi.Fluent/ZXing/ReedSolomonDecoder.cs
  WalletWasabi.Fluent/ZXing/Result.cs
  WalletWasabi.Fluent/ZXing/ResultMetadataType.cs
  WalletWasabi.Fluent/ZXing/ResultPoint.cs
  WalletWasabi.Fluent/ZXing/ResultPointCallback.cs
  WalletWasabi.Fluent/ZXing/SKBitmapLuminanceSource.cs
  WalletWasabi.Fluent/ZXing/StringUtils.cs
  WalletWasabi.Fluent/ZXing/SupportClass.cs
  WalletWasabi.Fluent/ZXing/Version.cs
  WalletWasabi.Fluent/packages.lock.json
  WalletWasabi.Tests/UnitTests/QrDecode/QrCodeDecodingTests.cs
Labels: size/XXL

#10753 [VDG] UI Decoupling #27
  WalletWasabi.Fluent/Models/AddWalletPageOption.cs
  WalletWasabi.Fluent/Models/UI/NullWalletRepository.cs
  WalletWasabi.Fluent/Models/WalletCreationOption.cs
  WalletWasabi.Fluent/Models/WalletCreationOptions.cs
  WalletWasabi.Fluent/Models/Wallets/IWalletRepository.cs
  WalletWasabi.Fluent/Models/Wallets/WalletRepository.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/ConfirmRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/RecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/ConnectHardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/WalletNamePageViewModel.cs
Labels: size/L

#10914 Do not remove alices.
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/M, affiliate

#10894 Reduce log levels of common errors in the Log
  WalletWasabi/Affiliation/AffiliateServerStatusUpdater.cs
  WalletWasabi/Extensions/EventHandlerExtensions.cs
  WalletWasabi/WabiSabi/Backend/Banning/CoinVerifier.cs
Labels: size/S, affiliate

#10931 Improve destination addresses algorithm
  WalletWasabi/Blockchain/Transactions/TransactionHistoryBuilder.cs
Labels: size/M

#10967 Speed Up Wallet Load
  WalletWasabi/Blockchain/Analysis/CoinjoinAnalyzer.cs
Labels: size/XS

#10972 Prevent using the mempool info too early
  WalletWasabi.Tests/UnitTests/AllFeeEstimateTests.cs
  WalletWasabi/Extensions/RPCClientExtensions.cs
Labels: size/S

#10951 Add comments for HandleFiltersLock usage
  WalletWasabi/Wallets/Wallet.cs
Labels: size/XS

#10983 [trivial] typo searchbar
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveViewModel.cs
Labels: size/XS

#10956 Get unconfirmed CoinJoins from the coordinator
  WalletWasabi.Backend/Controllers/BatchController.cs
  WalletWasabi.Backend/Controllers/WabiSabiController.cs
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Backend/Startup.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/CoinJoinMempoolManagerTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiApiApplicationFactory.cs
  WalletWasabi/BitcoinCore/Mempool/IMempoolMirror.cs
  WalletWasabi/BitcoinCore/Mempool/MempoolMirror.cs
  WalletWasabi/WabiSabi/Backend/CoinJoinMempoolManager.cs
Labels: size/L, affiliate

#10989 [VDG] fix OOBE background on add wallet from searchbar
  WalletWasabi.Fluent/ViewModels/SearchBar/Sources/ActionsSearchSource.cs
Labels: size/XS

#10942 [VDG] new onboarding
  WalletWasabi.Fluent/Views/AddWallet/AddWalletPageView.axaml
  WalletWasabi.Fluent/Views/AddWallet/WelcomePageView.axaml
Labels: size/L

#10992 Welcome Page: tweak wording coinjoin fees page
  WalletWasabi.Fluent/Views/AddWallet/WelcomePageView.axaml
Labels: size/S

#10998 Disable C# Analyzer
  .deepsource.toml
Labels: size/XS

#11006 [VDG] QuestionControl - fix default button on ENTER
  WalletWasabi.Fluent/Controls/QuestionControl.axaml
  WalletWasabi.Fluent/Controls/QuestionControl.axaml.cs
Labels: size/XS

#11011 [VDG] [Trivial] Fix label sorting
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/AddressViewModel.cs
Labels: size/XS

#11007 [Trivial] Add arm64 to 'Officially Supported Architectures'
  WalletWasabi.Documentation/WasabiCompatibility.md
Labels: size/XS

#11005 [VDG] Select correct wallet when clicking notification
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
Labels: size/XS

#10754 [VDG] UI Decoupling #28
  WalletWasabi.Fluent/Models/UI/NullWalletRepository.cs
  WalletWasabi.Fluent/Models/UI/UiContext.cs
  WalletWasabi.Fluent/Models/Wallets/HardwareWalletInterface.cs
  WalletWasabi.Fluent/Models/Wallets/IHardwareWalletInterface.cs
  WalletWasabi.Fluent/Models/Wallets/IWalletRepository.cs
  WalletWasabi.Fluent/Models/Wallets/NullHardwareWalletInterface.cs
  WalletWasabi.Fluent/Models/Wallets/WalletRepository.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/ConnectHardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/DetectedHardwareWalletViewModel.cs
  WalletWasabi.Tests/UnitTests/ViewModels/Mocks.cs
  WalletWasabi.Tests/UnitTests/ViewModels/UiContextBuilder.cs
  WalletWasabi/Hwi/Models/HwiEnumerateEntry.cs
Labels: size/L

#11023 add walletname to fully synced log message
  WalletWasabi/Wallets/Wallet.cs
Labels: size/XS

#10921 [VDG] Fix GUI freeze in Linux after setting WindowState=Normal
  WalletWasabi.Fluent/Behaviors/RestartRendererInLinuxBehavior.cs
  WalletWasabi.Fluent/Views/MainWindow.axaml
Labels: size/M

#11048 [VDG] Transaction preview - use capital initials
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionSummary.axaml
Labels: size/S

#11051 [VDG] Fix crash on privacy warnings flyout
  WalletWasabi.Fluent/Behaviors/BindableFlyoutOpenBehavior.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacySuggestionsFlyoutViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml
Labels: size/M

#11058 `FilterProcessor`: Remove lock
  WalletWasabi/Blockchain/BlockFilters/FilterProcessor.cs
Labels: size/M

#11022 Fix internal address re-use destination amount calculation
  WalletWasabi.Fluent/Extensions/CurrencyExtensions.cs
  WalletWasabi.Fluent/Models/Transactions/PrivacySuggestion.cs
  WalletWasabi.Fluent/Models/Transactions/PrivacySuggestionsModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionSummaryViewModel.cs
Labels: size/S

#11001 add issues to project board on reopening too
  .github/workflows/auto-add-to-projcet.yml
Labels: size/XS

#11066 Add `EnforceExtendedAnalyzerRules` to `WalletWasabi.Fluent.Generators` project
  WalletWasabi.Fluent.Generators/WalletWasabi.Fluent.Generators.csproj
Labels: size/XS

#10988 Use corrected estimations for coinjoins
  WalletWasabi.Tests/Helpers/BitcoinFactory.cs
  WalletWasabi.Tests/UnitTests/CoordinatorRoundTests.cs
  WalletWasabi.Tests/UnitTests/MockRpcClient.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/RoundCreationTests.cs
  WalletWasabi/Extensions/RPCClientExtensions.cs
Labels: size/M

#11055 [VDG] PrivacySuggestions: add warning for spending coinjoining coins
  WalletWasabi.Fluent/Models/Transactions/PrivacySuggestionsModel.cs
  WalletWasabi.Fluent/Models/Transactions/PrivacyWarning.cs
  WalletWasabi.Fluent/Views/Wallets/Send/PrivacyWarningsView.axaml
  WalletWasabi/Blockchain/TransactionBuilding/BuildTransactionResult.cs
Labels: size/M

#11077 [simple] Fix warnings
  WalletWasabi.Fluent/Models/UI/NullWalletRepository.cs
  WalletWasabi.Fluent/Models/Wallets/WalletRepository.cs
Labels: size/S

#11059 `Wallet`: Remove `NewBlockProcessed` event
  WalletWasabi/Wallets/Wallet.cs
Labels: size/XS

#11047 [VDG] Fix coin selection sort order
  WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorDataGridSource.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorViewModel.cs
Labels: size/XS

#11075 [VDG] Increase hover zones for copy buttons
  WalletWasabi.Fluent/Views/Wallets/Home/History/Details/CoinJoinDetailsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/Details/TransactionDetailsView.axaml
Labels: size/S

#11081 Always log that CoinJoinClient starts
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Labels: size/XS

#10964 Store banned coins in file
  WalletWasabi.Daemon/Global.cs
  WalletWasabi/WabiSabi/Client/Banning/CoinPrison.cs
  WalletWasabi/WabiSabi/Client/Banning/PrisonedCoinRecord.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WabiSabi/Client/CoinJoinProgressEvents/CoinBanned.cs
  WalletWasabi/WabiSabi/Client/CoinJoinTracker.cs
Labels: size/L

#11091 `FilterModel`: Nits
  WalletWasabi/Backend/Models/FilterModel.cs
Labels: size/XS

#11067 Minor improvement & bugfix for `BlockFilterSqliteStorage`
  WalletWasabi.Tests/UnitTests/Stores/BlockFilterSqliteStorageTests.cs
  WalletWasabi/Stores/BlockFilterSqliteStorage.cs
Labels: size/S

#11090 `TransactionProcessor`: Remove guards
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
Labels: size/XS

#11094 [Trivial] Remove unused parameter
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
Labels: size/XS

#11096 [VDG] Privacy Warning - decerase the opacity of icons of the suggestions
  WalletWasabi.Fluent/Views/Wallets/Send/PrivacyWarningsView.axaml
Labels: size/XS

#11098 [VDG] Fix sorting for non-private pockets
  WalletWasabi.Fluent/ViewModels/CoinControl/CoinControlLabelComparer.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorDataGridSource.cs
Labels: size/M

#11099 [VDG] Fix fontsize for Label Management suggestion item
  WalletWasabi.Fluent/Views/Wallets/Send/PrivacyWarningsView.axaml
Labels: size/XS

#11074 [VDG] [trivial] rename Funds to Coins for Pocket
  WalletWasabi.Fluent/Helpers/CoinPocketHelper.cs
Labels: size/XS

#10982 [VDG] Show edit fee button always
  WalletWasabi.Fluent/Helpers/TransactionFeeHelper.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/FeeChartViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionSummary.axaml
Labels: size/M

#11089 Minor spellchecker workflow improvement
  WalletWasabi.sln
  exclusion.dic
Labels: size/XS

#11102 [VDG] PrivacySuggestions: ToolTip with consequences and explanation
  WalletWasabi.Fluent/Views/Wallets/Send/PrivacyWarningsView.axaml
Labels: size/S

#11113 [VDG] Fix unconfirmed coins warning
  WalletWasabi.Fluent/Models/Transactions/PrivacyWarning.cs
  WalletWasabi.Fluent/Views/Wallets/Send/PrivacyWarningsView.axaml
Labels: size/S

#11092 [VDG] Add Confirmation Time to Transaction Details
  WalletWasabi.Fluent/Converters/TimeSpanConverter.cs
  WalletWasabi.Fluent/Helpers/TransactionFeeHelper.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/TransactionDetailsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendFeeViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionSummaryViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/Details/TransactionDetailsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionSummary.axaml
  WalletWasabi.Tests/UnitTests/AllFeeEstimateTests.cs
  WalletWasabi/Blockchain/Analysis/FeesEstimation/AllFeeEstimate.cs
  WalletWasabi/Blockchain/Transactions/SmartTransaction.cs
  WalletWasabi/Blockchain/Transactions/TransactionHistoryBuilder.cs
  WalletWasabi/Blockchain/Transactions/TransactionSummary.cs
Labels: size/L

#11116 [VDG] Notify property updates for Confirmation Time and Labels
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/TransactionDetailsViewModel.cs
Labels: UI, size/XS

#11129 Have The Witness
  WalletWasabi/BitcoinP2p/P2pBehavior.cs
  WalletWasabi/BitcoinP2p/TrustedP2pBehavior.cs
  WalletWasabi/BitcoinP2p/UntrustedP2pBehavior.cs
  WalletWasabi/Extensions/NBitcoinExtensions.cs
Labels: size/S

#11121 Request tx with witness data and ignore txs without it.
  WalletWasabi/BitcoinP2p/P2pBehavior.cs
Labels: size/S

#11136 Fix "CPFP grouping doesn't always work properly"
  WalletWasabi/Blockchain/Transactions/SmartTransaction.cs
Labels: size/XS

#11052 [PoC] Redo prison
  WalletWasabi.Tests/Helpers/ArenaBuilder.cs
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/ConfigTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepConnectionConfirmationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputToBlameRoundTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/UtxoPrisonTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/UtxoPrisonWardenTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiApiApplicationFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi/WabiSabi/Backend/DoSPrevention/DoSConfiguration.cs
  WalletWasabi/WabiSabi/Backend/DoSPrevention/Inmate.cs
  WalletWasabi/WabiSabi/Backend/DoSPrevention/Offender.cs
  WalletWasabi/WabiSabi/Backend/DoSPrevention/Prison.cs
  WalletWasabi/WabiSabi/Backend/DoSPrevention/Warden.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Rounds/TimeFrame.cs
  WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
  WalletWasabi/WabiSabi/CoordinatorParameters.cs
  WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
  WalletWasabi/WalletWasabi.csproj
Labels: size/XL

#11137 [VDG] Fix missing wallet tile on small screen
  WalletWasabi.Fluent/Views/Wallets/Home/WalletTiles.axaml
Labels: size/XS

#11088 `IndexStoreTests`: Clean up the test
  WalletWasabi.Tests/UnitTests/Stores/IndexStoreTests.cs
Labels: size/S

#11142 Don't Use Witness Txs/Blocks over the Network
  WalletWasabi/BitcoinP2p/P2pBehavior.cs
  WalletWasabi/BitcoinP2p/TrustedP2pBehavior.cs
  WalletWasabi/BitcoinP2p/UntrustedP2pBehavior.cs
  WalletWasabi/Extensions/NBitcoinExtensions.cs
Labels: size/S

#11131 Cancel previous task before running new privacy calculation
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
Labels: size/XS

#11167 [VDG] Fix PrivacyBarSegment width calculation
  WalletWasabi.Fluent/Controls/PrivacyBar.axaml.cs
Labels: size/XS

#11157 [Trivial] Hide TXID separator if tx is not confirmed
  WalletWasabi.Fluent/Views/Wallets/Home/History/Details/TransactionDetailsView.axaml
Labels: size/XS

#11165 Fix prison tests & a few minor improvements
  .editorconfig
  WalletWasabi.Fluent/Models/Wallets/IWalletModel.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PrisonTests.cs
  WalletWasabi/BitcoinCore/Mempool/IMempoolMirror.cs
  WalletWasabi/Blockchain/Transactions/ITransactionStore.cs
  WalletWasabi/Extensions/RPCClientExtensions.cs
Labels: size/M
