Repository WalletWasabi/WalletWasabi, pull requests merged in 2023-12, with the labels that each got.

#12014 Use IHttpClient + Misc
  WalletWasabi.Daemon/Global.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/BuyViewModel.cs
  WalletWasabi.Tests/IntegrationTests/ShopWareApiClientTests.cs
  WalletWasabi/BuyAnything/BuyAnythingManager.cs
  WalletWasabi/BuyAnything/ConversationExtensions.cs
  WalletWasabi/BuyAnything/ConversationUpdateTrack.cs
  WalletWasabi/WebClients/ShopWare/ShopWareApiClient.cs
Labels: size/M

#12015 ReAdd GetCustomerProfile and message fetch
  WalletWasabi.Tests/IntegrationTests/ShopWareApiClientTests.cs
  WalletWasabi.Tests/UnitTests/BuyAnything/BuyAnythingManagerTests.cs
  WalletWasabi.Tests/UnitTests/MockShopWareApiClient.cs
  WalletWasabi/BuyAnything/BuyAnythingManager.cs
  WalletWasabi/WebClients/BuyAnything/BuyAnythingClient.cs
  WalletWasabi/WebClients/ShopWare/IShopWareApiClient.cs
  WalletWasabi/WebClients/ShopWare/ShopWareApiClient.cs
Labels: size/M

#12021 Add failback mechanism when couldn't load countries
  WalletWasabi/BuyAnything/BuyAnythingManager.cs
  WalletWasabi/WebClients/BuyAnything/BuyAnythingClient.cs
Labels: size/M

#12023 Adapt to Figma designs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/Initial/Validators/ProductInputValidator.cs
  WalletWasabi.Fluent/Views/Wallets/Buy/OrderMessagesView.axaml
Labels: size/S

#12018 BAB: Small cleanups + Add a test setup
  WalletWasabi.Tests/IntegrationTests/ShopWareApiClientTests.cs
Labels: size/M

#12030 Trigger event upon new conversation
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/BuyViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/ShopinBitWorkflowManager.cs
  WalletWasabi/BuyAnything/BuyAnythingManager.cs
Labels: size/S

#12031 Sort orders by title, descending.
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/BuyViewModel.cs
Labels: size/XS

#12038 Fix bugs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/ShopinBitWorkflowManager.cs
  WalletWasabi/BuyAnything/BuyAnythingManager.cs
  WalletWasabi/BuyAnything/ConversationExtensions.cs
  WalletWasabi/WebClients/ShopWare/ShopWareRequestFactory.cs
Labels: size/S

#12040 Add track link to offer
  WalletWasabi/BuyAnything/BuyAnythingManager.cs
Labels: size/XS

#12044 Mark *new* messages from selected conversation as "read"
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/BuyViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/OrderViewModel.cs
Labels: size/S

#12049 Fix wallet gets stuck after offer recieved
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/Delivery/Validators/StateInputValidator.cs
Labels: size/XS

#12056 ChatMessage Tags
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/BuyViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Messages/AssistantMessageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Messages/MessageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Messages/UserMessageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/OrderViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/InputValidator.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/Common/TextInputInputValidator.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/Delivery/DeliveryWorkflow.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/Delivery/DeliveryWorkflowRequest.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/Delivery/Validators/CityInputValidator.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/Delivery/Validators/ConfirmTosInputValidator.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/Delivery/Validators/DeliverySummaryInputValidator.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/Delivery/Validators/FirstNameInputValidator.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/Delivery/Validators/HouseNumberInputValidator.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/Delivery/Validators/LastNameInputValidator.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/Delivery/Validators/PostalCodeInputValidator.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/Delivery/Validators/StateInputValidator.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/Delivery/Validators/StreetNameInputValidator.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/Initial/InitialWorkflow.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/Initial/InitialWorkflowRequest.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/Initial/Validators/ConfirmPrivacyPolicyInputValidator.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/Initial/Validators/InitialSummaryInputValidator.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/Initial/Validators/LocationInputValidator.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/Initial/Validators/ProductInputValidator.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/Initial/Validators/RequestInputValidator.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/Package/PackageWorkflow.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/Payment/PaymentWorkflow.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/ShopinBitWorkflowManager.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/SupportChat/ChatMessageInputValidator.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/SupportChat/SupportChatWorkflow.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/SupportChat/SupportChatWorkflowRequest.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/Workflow.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/WorkflowManager.cs
  WalletWasabi.Tests/UnitTests/BuyAnything/BuyAnythingManagerTests.cs
  WalletWasabi/BuyAnything/BuyAnythingManager.cs
  WalletWasabi/BuyAnything/Conversation.cs
Labels: size/XL

#12064 Fix unit/total price
  WalletWasabi/BuyAnything/BuyAnythingManager.cs
  WalletWasabi/WebClients/ShopWare/Models/Order.cs
Labels: size/XS

#12041 Jade wallet implement
  WalletWasabi.Documentation/WasabiCompatibility.md
  WalletWasabi.Tests/AcceptanceTests/HwiKatas.cs
  WalletWasabi.Tests/Helpers/HwiValidationHelper.cs
  WalletWasabi.Tests/UnitTests/Hwi/HwiProcessBridgeMock.cs
  WalletWasabi.Tests/UnitTests/Hwi/MockedDeviceTests.cs
  WalletWasabi.Tests/UnitTests/WalletDirTests.cs
  WalletWasabi/Hwi/Models/HardwareWalletModels.cs
  WalletWasabi/Hwi/Models/HwiEnumerateEntry.cs
  WalletWasabi/Wallets/WalletType.cs
Labels: size/L

#12069 Separate links into their own bubbles
  WalletWasabi/BuyAnything/BuyAnythingManager.cs
Labels: size/M

#12070 Better offer display
  WalletWasabi/BuyAnything/BuyAnythingManager.cs
Labels: size/S

#12067 pay now
  WalletWasabi.Fluent/Helpers/TransactionHelpers.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Messages/MessageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Messages/PayNowAssistantMessageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/OrderViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Buy/OrderMessagesView.axaml
  WalletWasabi/Blockchain/TransactionBuilding/TransactionBuilderWalletExtensions.cs
  WalletWasabi/BuyAnything/BuyAnythingManager.cs
  WalletWasabi/BuyAnything/ChatMessage.cs
  WalletWasabi/BuyAnything/ConversationUpdateTrack.cs
Labels: size/L

#11976 Add `listpaymentsincoinjoin` and `cancelpaymentincoinjoin` RPC calls
  WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
  WalletWasabi/WabiSabi/Client/Batching/FinishedPayment.cs
  WalletWasabi/WabiSabi/Client/Batching/InProgressPayment.cs
  WalletWasabi/WabiSabi/Client/Batching/Payment.cs
  WalletWasabi/WabiSabi/Client/Batching/PaymentBatch.cs
  WalletWasabi/WabiSabi/Client/Batching/PaymentSet.cs
  WalletWasabi/WabiSabi/Client/Batching/PendingPayment.cs
Labels: size/L

#12074 Buy anything new message types
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Messages/UrlListMessageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/OrderViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Buy/OrderMessagesView.axaml
  WalletWasabi/BuyAnything/ChatMessage.cs
Labels: size/L

#11897 .NET 8
  .github/workflows/codeql.yml
  Contrib/AffiliationServer/revenue.fsx
  Contrib/Containers/Dockerfile
  Directory.Build.props
  Directory.Packages.props
  README.md
  WalletWasabi.Backend/WalletWasabi.Backend.csproj
  WalletWasabi.Daemon/WalletWasabi.Daemon.csproj
  WalletWasabi.Daemon/packages.lock.json
  WalletWasabi.Documentation/Guides/HowToDebug.md
  WalletWasabi.Documentation/WasabiCompatibility.md
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent.Generators/WalletWasabi.Fluent.Generators.csproj
  WalletWasabi.Fluent.Generators/packages.lock.json
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
  WalletWasabi.Packager/WalletWasabi.Packager.csproj
  WalletWasabi.Packager/packages.lock.json
  WalletWasabi.Tests/UnitTests/Tor/Socks5/TorTcpConnectionFactoryTests.cs
  WalletWasabi.Tests/WalletWasabi.Tests.csproj
  WalletWasabi/BitcoinCore/Endpointing/PortFinder.cs
  WalletWasabi/WalletWasabi.csproj
  WalletWasabi/packages.lock.json
  azure-pipelines-cd.yml
  azure-pipelines-detbuild.yml
  azure-pipelines-linux.yml
  azure-pipelines-osx.yml
  azure-pipelines-windows.yml
  deps.nix
  flake.lock
  flake.nix
  global.json
Labels: size/XXL

#12093 store IsPaid in Invoice
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Messages/PayNowAssistantMessageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/OrderViewModel.cs
  WalletWasabi/BuyAnything/BuyAnythingManager.cs
  WalletWasabi/BuyAnything/ChatMessage.cs
  WalletWasabi/BuyAnything/Conversation.cs
Labels: size/M

#12100 Buy anything cordoba edition
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/OrderViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/1 - Initial/StartConversationStep.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/2 - Delivery/AcceptOfferStep.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/2 - Delivery/SaveConversationStep.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/3 - Support/SupportChatStep.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/Workflow.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/WorkflowStep.cs
  WalletWasabi/BuyAnything/BuyAnythingManager.cs
Labels: size/L

#12104 Ignore OperationCancelledException
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/OrderViewModel.cs
Labels: size/S

#12095 Attempt to use new Windows RID
  WalletWasabi.Packager/Program.cs
  WalletWasabi.WindowsInstaller/WalletWasabi.WindowsInstaller.wixproj
  azure-pipelines-detbuild.yml
Labels: size/S

#12108 Rename pay now to pay
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Messages/PayNowAssistantMessageViewModel.cs
Labels: size/XS

#12105 [Trivial] Simplify the wording and remove unnecessary text
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/1 - Initial/CountryStep.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/1 - Initial/RequestedItemStep.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/1 - Initial/StartConversationStep.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/1 - Initial/WelcomeStep.cs
  WalletWasabi.Fluent/Views/Wallets/Buy/BuyView.axaml
  WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
Labels: size/S

#12101 `ByteHelpers.ToHex`: Use .NET implementation
  WalletWasabi/Helpers/ByteHelpers.cs
Labels: size/M

#12110 Fix tests build
  WalletWasabi.Tests/IntegrationTests/ShopWareApiClientTests.cs
  WalletWasabi.Tests/UnitTests/BuyAnything/BuyAnythingManagerTests.cs
  WalletWasabi.Tests/UnitTests/BuyAnything/BuyAnythingSerializationTests.cs
Labels: size/M

#12096 `AllTransactionStore`: Fix accessibility modifiers
  WalletWasabi/Blockchain/Transactions/AllTransactionStore.cs
Labels: size/M

#12114 bump supported OS versions with .NET 8
  WalletWasabi.Documentation/ClientRelease/ReleaseNotesTemplate.md
  WalletWasabi.Documentation/WasabiCompatibility.md
Labels: size/S

#12111 [VDG] Update to latest Avalonia 11 NuGet packages
  Directory.Packages.props
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
Labels: size/XL

#12128 Bump version to 2.0.5 on master
  WalletWasabi/Helpers/Constants.cs
Labels: size/XS

#11784 Remove all `WithAwaitCancellationAsync` extension methods
  WalletWasabi.Tests/UnitTests/BlockNotifierTests.cs
  WalletWasabi/BitcoinCore/P2pNode.cs
  WalletWasabi/Cache/IdempotencyRequestCache.cs
  WalletWasabi/Extensions/TaskExtensions.cs
  WalletWasabi/Helpers/EventAwaiter.cs
  WalletWasabi/Helpers/EventsAwaiter.cs
  WalletWasabi/Tor/TorProcessManager.cs
Labels: size/M
