Repository WalletWasabi/WalletWasabi, pull requests merged in 2023-04, with the labels that each got.

#10411 WasabiGPT
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/App.axaml
  WalletWasabi.Fluent/App.axaml.cs
  WalletWasabi.Fluent/Config.cs
  WalletWasabi.Fluent/CrashReport/CrashReportApp.axaml.cs
  WalletWasabi.Fluent/Styles/PathIcon.axaml
  WalletWasabi.Fluent/UiConfig.cs
  WalletWasabi.Fluent/ViewModels/ChatGPT/AssistantResult.cs
  WalletWasabi.Fluent/ViewModels/ChatGPT/ChatAssistantScriptGlobals.cs
  WalletWasabi.Fluent/ViewModels/ChatGPT/ChatAssistantViewModel.Directions.cs
  WalletWasabi.Fluent/ViewModels/ChatGPT/ChatAssistantViewModel.cs
  WalletWasabi.Fluent/ViewModels/ChatGPT/Messages/Actions/BalanceActionMessageViewModel.cs
  WalletWasabi.Fluent/ViewModels/ChatGPT/Messages/Actions/ReceiveActionMessageViewModel.cs
  WalletWasabi.Fluent/ViewModels/ChatGPT/Messages/Actions/SendActionMessageViewModel.cs
  WalletWasabi.Fluent/ViewModels/ChatGPT/Messages/AssistantMessageViewModel.cs
  WalletWasabi.Fluent/ViewModels/ChatGPT/Messages/ErrorMessageViewModel.cs
  WalletWasabi.Fluent/ViewModels/ChatGPT/Messages/MessageViewModel.cs
  WalletWasabi.Fluent/ViewModels/ChatGPT/Messages/UserMessageViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/Settings/Setting.cs
  WalletWasabi.Fluent/ViewModels/Settings/AdvancedSettingsTabViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/BitcoinTabSettingsViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/WelcomePageView.axaml
  WalletWasabi.Fluent/Views/ChatGPT/ChatAssistant.axaml
  WalletWasabi.Fluent/Views/ChatGPT/ChatAssistant.axaml.cs
  WalletWasabi.Fluent/Views/ChatGPT/ChatAssistantDropdown.axaml
  WalletWasabi.Fluent/Views/ChatGPT/ChatAssistantDropdown.axaml.cs
  WalletWasabi.Fluent/Views/MainWindow.axaml
  WalletWasabi.Fluent/Views/Settings/AdvancedSettingsTabView.axaml
  WalletWasabi.Fluent/Views/Shell/TitleBar.axaml
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
  WalletWasabi.Tests/WalletWasabi.Tests.csproj
Labels: size/XXL

#10231 [VDG] Fix history table selection jumping
  WalletWasabi.Fluent/Behaviors/ScrollToSelectedItemBehavior.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
Labels: size/S

#10417 [VDG] Fix suggestions out of sync
  WalletWasabi.Fluent/Behaviors/FlyoutSuggestionBehavior.cs
Labels: size/S

#9691 [VDG] Escape button goes back
  WalletWasabi.Fluent/Controls/ContentArea.axaml
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/CoinJoinProfilesViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/RoutableViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressesViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendFeeViewModel.cs
Labels: size/S

#10137 [website] Google meta, email signature, 404 page
  WalletWasabi.Backend/wwwroot/.htaccess
  WalletWasabi.Backend/wwwroot/404.html
  WalletWasabi.Backend/wwwroot/cloudflare.html
  WalletWasabi.Backend/wwwroot/faq.html
  WalletWasabi.Backend/wwwroot/img/email/email_gh.png
  WalletWasabi.Backend/wwwroot/img/email/email_li.png
  WalletWasabi.Backend/wwwroot/img/email/email_tw.png
  WalletWasabi.Backend/wwwroot/img/email/wasabi_email.png
  WalletWasabi.Backend/wwwroot/img/wasabi_logo.png
  WalletWasabi.Backend/wwwroot/index.html
Labels: size/L

#10400 Make CoinJoinClientState available per wallet in CoinJoinManager
  WalletWasabi.Fluent/ViewModels/ApplicationViewModel.cs
  WalletWasabi/Services/SleepInhibitor.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClientState.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Labels: size/M

#10420 [trivial] Fix filename
  WalletWasabi.Tests/UnitTests/Blockchain/Blocks/SmartHeaderChainTests.cs
Labels: size/XS

#10425 Make Output a record
  WalletWasabi/WabiSabi/Client/Output.cs
Labels: size/S

#10239 [VDG] UI Decoupling #8
  WalletWasabi.Fluent/Models/UI/NullClipboard.cs
  WalletWasabi.Fluent/Models/UI/UiContext.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/INavigate.cs
  WalletWasabi.Fluent/ViewModels/Navigation/INavigationStack.cs
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationExtensions.cs
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationStack.cs
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationState.cs
  WalletWasabi.Fluent/ViewModels/Navigation/RoutableViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/TargettedNavigationStack.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/Sources/ActionsSearchSource.cs
  WalletWasabi.Fluent/ViewModels/ViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinsHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/TransactionHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
Labels: size/L

#10429 Revert "[VDG] UI Decoupling #8"
  WalletWasabi.Fluent/Models/UI/NullClipboard.cs
  WalletWasabi.Fluent/Models/UI/UiContext.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/INavigate.cs
  WalletWasabi.Fluent/ViewModels/Navigation/INavigationStack.cs
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationExtension.cs
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationExtensions.cs
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationStack.cs
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationState.cs
  WalletWasabi.Fluent/ViewModels/Navigation/RoutableViewModel.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/Sources/ActionsSearchSource.cs
  WalletWasabi.Fluent/ViewModels/ViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinsHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/TransactionHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
Labels: size/L

#10432 [VDG] UI Decoupling #8 fixed
  WalletWasabi.Fluent/Models/UI/NullClipboard.cs
  WalletWasabi.Fluent/Models/UI/UiContext.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/INavigate.cs
  WalletWasabi.Fluent/ViewModels/Navigation/INavigationStack.cs
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationExtension.cs
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationExtensions.cs
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationStack.cs
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationState.cs
  WalletWasabi.Fluent/ViewModels/Navigation/RoutableViewModel.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/Sources/ActionsSearchSource.cs
  WalletWasabi.Fluent/ViewModels/ViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinsHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/TransactionHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
Labels: size/L

#10311 [Trivial] Add Spell Checker rules to '.editorconfig'
  .editorconfig
  exclusion.dic
Labels: size/XS

#10406 Use Func<> to get up-to-date coin candidates in CoinJoinClient
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/Participant.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WabiSabi/Client/CoinJoinTracker.cs
  WalletWasabi/WabiSabi/Client/CoinJoinTrackerFactory.cs
  WalletWasabi/Wallets/IWallet.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/L

#10381 Fail to signal readiness
  WalletWasabi.Backend/Filters/ExceptionTranslateFilter.cs
  WalletWasabi/Affiliation/AffiliationConstants.cs
  WalletWasabi/Affiliation/AffiliationException.cs
  WalletWasabi/Tor/Http/Extensions/HttpResponseMessageExtensions.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
Labels: size/S

#10428 Exception when closing the wallet fast
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Labels: size/XS

#10392 Don't wait indefinitely for a Round
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/XS

#10443 [Trivial] Fix CodeFactor
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationStack.cs
  WalletWasabi.Tests/UnitTests/Affiliation/AffiliateDataUpdaterTests.cs
  WalletWasabi/Tor/Http/Extensions/HttpResponseMessageExtensions.cs
Labels: size/S

#10434 [Trivial] Use TryGetValue
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Labels: size/XS

#10444 Fix typos
  WalletWasabi.Fluent.Desktop/Program.cs
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationStack.cs
  WalletWasabi.Tests/Helpers/ServiceFactory.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
  WalletWasabi/Tor/TorMonitor.cs
  WalletWasabi/WabiSabi/Backend/Banning/CoinVerifier.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  exclusion.dic
Labels: size/L

#10441 Sanity checks before and after we found a round
  WalletWasabi/Exceptions/CoinJoinClientException.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WabiSabi/Client/RoundStateAwaiters/NoCoinsToMixException.cs
  WalletWasabi/Wallets/IWallet.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/L

#10449 [website] minor fixes
  WalletWasabi.Backend/wwwroot/about.html
  WalletWasabi.Backend/wwwroot/faq.html
  WalletWasabi.Backend/wwwroot/index.html
  WalletWasabi.Backend/wwwroot/onion-index.html
Labels: size/S

#10471 Changed user facing date time formats to ISO like
  WalletWasabi.Fluent/Extensions/DateTimeExtensions.cs
  WalletWasabi.Fluent/Extensions/DateTimeOffsetExtensions.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/TransactionDetailsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinsHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/TransactionHistoryItemViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/Details/TransactionDetailsView.axaml
Labels: size/S

#10465 [Trivial] Remove unused parameter
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinTrackerFactory.cs
  WalletWasabi/WabiSabi/Client/CredentialDependencies/DependencyGraph.cs
  WalletWasabi/WabiSabi/Client/LiquidityClueProvider.cs
Labels: size/XS

#10472 Removed S.D.Bitmap from dependencies
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/Models/WebcamQrReader.cs
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/ZXing/BitmapLuminanceSource.cs
  WalletWasabi.Fluent/ZXing/QRCodeReader.cs
  WalletWasabi.Fluent/ZXing/SKBitmapLuminanceSource.cs
  WalletWasabi.Fluent/packages.lock.json
Labels: size/XL

#10480 [Trivial] Update file name in Contrib.WalletDiagnostic.README
  Contrib/WalletDiagnostic/README.md
Labels: size/XS

#10476 remove backend deployment instructions link from backend README
  WalletWasabi.Backend/README.md
Labels: size/XS

#10430 [VDG] fix Preview TX: shield_regular & shield_good displayed simultaniously
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml
Labels: size/XS

#10442 Add extra info into the coinjoin notification request
  WalletWasabi.Tests/UnitTests/Affiliation/AffiliateDataUpdaterTests.cs
  WalletWasabi.Tests/UnitTests/Affiliation/CanonicalSerializationTests.cs
  WalletWasabi.Tests/UnitTests/Affiliation/RoundDataTests.cs
  WalletWasabi/Affiliation/AffiliateDataCollector.cs
  WalletWasabi/Affiliation/AffiliateDataUpdater.cs
  WalletWasabi/Affiliation/AffiliateInput.cs
  WalletWasabi/Affiliation/BuiltTransactionData.cs
  WalletWasabi/Affiliation/Models/CoinjoinNotification/Body.cs
  WalletWasabi/Affiliation/Models/CoinjoinNotification/Input.cs
  WalletWasabi/Affiliation/RoundData.cs
Labels: size/M

#10489 Fix Common.fsx script for big amount values
  Contrib/WalletDiagnostic/common.fsx
Labels: size/XS

#10468 Reduce MaxAnonScore of PrivateCoinJoinProfile for new wallets
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/PrivateCoinJoinProfileViewModel.cs
Labels: size/XS

#10496 Make recovery words copyable
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/RecoveryWordsViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/Create/RecoveryWordsView.axaml
Labels: size/M

#10293 Wasabi Daemon
  WalletWasabi.Daemon/Config.cs
  WalletWasabi.Daemon/Global.cs
  WalletWasabi.Daemon/PersistentConfig.cs
  WalletWasabi.Daemon/Program.cs
  WalletWasabi.Daemon/README.md
  WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
  WalletWasabi.Daemon/WalletWasabi.Daemon.csproj
  WalletWasabi.Daemon/WasabiAppBuilder.cs
  WalletWasabi.Daemon/packages.lock.json
  WalletWasabi.Fluent.Desktop/Extensions/AppBuilderExtension.cs
  WalletWasabi.Fluent.Desktop/Program.cs
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/Services.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/OpenDirectory/OpenConfigFileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/AdvancedSettingsTabViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/BitcoinTabSettingsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/GeneralSettingsTabViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/SettingsTabViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/StatusIcon/StatusIconViewModel.cs
  WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/BroadcasterViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
  WalletWasabi.Tests/UnitTests/Clients/SingleInstanceCheckerTests.cs
  WalletWasabi.sln
  WalletWasabi/Services/SingleInstanceChecker.cs
  WalletWasabi/Services/Terminate/TerminateService.cs
Labels: size/XXL

#10508 [Trivial] Fix CodeFactor issues
  WalletWasabi/Hwi/Parsers/HwiParser.cs
  WalletWasabi/Rpc/JsonRpcRequestHandler.cs
Labels: size/M

#10438 Fixed crash on Linux machines without default font by Skia
  WalletWasabi.Fluent.Desktop/Extensions/AppBuilderExtension.cs
Labels: size/S

#10427 Simplified logging of Avalonia renderer
  WalletWasabi.Fluent.Desktop/Program.cs
Labels: size/XS

#10501 Revert breaking changes in IWallet interface
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/Participant.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WabiSabi/Client/CoinJoinTracker.cs
  WalletWasabi/WabiSabi/Client/CoinJoinTrackerFactory.cs
  WalletWasabi/Wallets/IWallet.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/M

#10512 User friendly exception on PSBT saving
  WalletWasabi.Fluent/Extensions/FriendlyExceptionMessageExtensions.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
Labels: size/S

#10491 Revenue sharing calculation script
  Contrib/AffiliationServer/README.md
  Contrib/AffiliationServer/notification/README.md
  Contrib/AffiliationServer/notification/n1.txt
  Contrib/AffiliationServer/notification/n2.txt
  Contrib/AffiliationServer/notification/n3.txt
  Contrib/AffiliationServer/revenue.fsx
Labels: size/L

#10499 TorControl: Complete writer when we know that no message will be send in the future
  WalletWasabi/Tor/Control/TorControlClient.cs
Labels: size/S

#10433 [VDG] do not use same icon for coinjoin indicator and anonymity score indicator
  WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorDataGridSource.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
  WalletWasabi.Fluent/Views/CoinControl/Core/Headers/AnonymityScoreHeaderView.axaml
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/Columns/AnonymitySetHeaderView.axaml
Labels: size/S

#10515 Use the TXID as the initial file name for PSBT
  WalletWasabi.Fluent/Helpers/TransactionHelpers.cs
Labels: size/XS

#10346 [VDG] UI Decoupling #11
  CONTRIBUTING.md
  WalletWasabi.Fluent.Generators/AnalyzerExtensions.cs
  WalletWasabi.Fluent.Generators/NavigationMetaDataGenerator.cs
  WalletWasabi.Fluent.Generators/Properties/launchSettings.json
  WalletWasabi.Fluent.Generators/UIContextGenerator.cs
  WalletWasabi.Fluent.Generators/UIContextUsageInConstructorAnalyzer.cs
  WalletWasabi.Fluent/UiServices.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/FluentNavigate.cs
  WalletWasabi.Fluent/ViewModels/Navigation/INavigationStack.cs
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationStack.cs
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationState.cs
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/HardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinsHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/TransactionHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WatchOnlyWalletViewModel.cs
Labels: size/XL

#10347 [VDG] UI Decoupling #12
  WalletWasabi.Fluent.Generators/UIContextGenerator.cs
Labels: size/M

#10532 Start wallets automatically after daemon starts
  WalletWasabi.Daemon/ArgumentHelpers.cs
  WalletWasabi.Daemon/Config.cs
  WalletWasabi.Daemon/README.md
  WalletWasabi.Daemon/WasabiAppBuilder.cs
Labels: size/M

#10522 Specify wallet in the request path
  WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
  WalletWasabi.Tests/RpcTests.cs
  WalletWasabi/Rpc/JsonRpcInitializationAttribute.cs
  WalletWasabi/Rpc/JsonRpcMethodAttribute.cs
  WalletWasabi/Rpc/JsonRpcMethodMetadata.cs
  WalletWasabi/Rpc/JsonRpcRequestHandler.cs
  WalletWasabi/Rpc/JsonRpcServer.cs
  WalletWasabi/Rpc/JsonRpcService.cs
Labels: size/L

#10537 Display software version
  WalletWasabi.Daemon/README.md
  WalletWasabi.Daemon/WasabiAppBuilder.cs
  WalletWasabi.Fluent.Desktop/Program.cs
  WalletWasabi.Fluent/Services.cs
Labels: size/S

#10540 Remove comma copy recovery words
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/RecoveryWordsViewModel.cs
Labels: size/XS

#10549 [Trivial] Correct link for API
  README.md
Labels: size/XS

#10555 Fix comparison
  WalletWasabi.Daemon/ArgumentHelpers.cs
Labels: size/XS

#10272 Introduce sqlite for storing of filters for `IndexStore`.
  WalletWasabi.Daemon/packages.lock.json
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/packages.lock.json
  WalletWasabi.Packager/packages.lock.json
  WalletWasabi.Tests/UnitTests/SafeIoManagerTests.cs
  WalletWasabi.Tests/UnitTests/Stores/BlockFilterSqliteStorageTests.cs
  WalletWasabi.Tests/UnitTests/Stores/IndexStoreTests.cs
  WalletWasabi/Backend/Models/FilterModel.cs
  WalletWasabi/Blockchain/BlockFilters/FilterProcessor.cs
  WalletWasabi/Io/DigestableSafeIoManager.cs
  WalletWasabi/Stores/BlockFilterSqliteStorage.cs
  WalletWasabi/Stores/IndexStore.cs
  WalletWasabi/WalletWasabi.csproj
  WalletWasabi/packages.lock.json
Labels: size/XXL

#10527 Fix CjManager Notification flow
  WalletWasabi/WabiSabi/Client/CoinJoinCoinSelector.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Labels: size/M

#10553 Fixed view model constructors according guidelines
  WalletWasabi.Fluent/ViewModels/Dialogs/AddressEntryDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/ShowQrCameraDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
Labels: size/S

#10454 [Trivial] Fix CS-R1067 issues for Deepsource
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi/Extensions/SystemNetExtensions.cs
  WalletWasabi/WabiSabi/Backend/Banning/CoinVerifier.cs
  WalletWasabi/WebClients/PayJoin/PayjoinClient.cs
Labels: size/S

#10525 update Backend README
  WalletWasabi.Backend/README.md
Labels: size/M

#10548 Fix typos & add word to exclusion.dic
  WalletWasabi.Fluent/Validation/IValidations.cs
  WalletWasabi.Fluent/Validation/Validations.cs
  WalletWasabi.Packager/Program.cs
  WalletWasabi/Services/UpdateManager.cs
  WalletWasabi/Userfacing/PasswordHelper.cs
  WalletWasabi/WabiSabi/Client/CoinJoinCoinSelector.cs
  exclusion.dic
Labels: size/M

#10388 [VDG] UI Decoupling - Receive #1
  WalletWasabi.Fluent/Helpers/LabelHelpers.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/LabelEntryDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Labels/SuggestionLabelsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/AddressLabelEditViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveViewModel.cs
  WalletWasabi.Tests/UnitTests/ViewModels/SuggestionLabelsViewModelTests.cs
Labels: size/L
