Repository WalletWasabi/WalletWasabi, pull requests merged in 2023-03, with the labels that each got.

#10166 [VDG] UI Decoupling #2
  WalletWasabi/Wallets/Wallet.cs
Labels: size/S

#9995 Change default backend URIs to new API hostnames
  WalletWasabi.Fluent.Desktop/Program.cs
  WalletWasabi.Fluent/Config.cs
Labels: size/M

#10214 [VDG] Ask user to check the hardware wallet when confirming
  WalletWasabi.Fluent/Views/Dialogs/Authorization/HardwareWalletAuthDialogView.axaml
Labels: size/XS

#10100 Use less strict condition in anonymity computation
  WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs
Labels: size/S

#10153 Maximize parallel request to 30 (take 2)
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Tests/RegressionTests/CoinVerifierApiClientStressTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/CoinVerifierTests.cs
  WalletWasabi/WabiSabi/Backend/Banning/CoinVerifier.cs
  WalletWasabi/WabiSabi/Backend/Banning/CoinVerifierApiClient.cs
Labels: size/L

#10223 Limit parallels reissuance requests to 10
  WalletWasabi/WabiSabi/Client/SmartRequestNode.cs
Labels: size/S

#10071 Amountdecomposer with Taproot
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/AmountDecomposerTests.cs
  WalletWasabi/Extensions/NBitcoinExtensions.cs
  WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/Output.cs
Labels: size/L

#10237 [Trivial] Simplify 'new' expression
  WalletWasabi.Tests/UnitTests/Affiliation/AffiliateDataUpdaterTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
Labels: size/S

#10241 Bump version to v2.0.3
  WalletWasabi.Backend/wwwroot/index.html
  WalletWasabi/Helpers/Constants.cs
Labels: size/S

#10242 Revert "Bump version to v2.0.3"
  WalletWasabi.Backend/wwwroot/index.html
  WalletWasabi/Helpers/Constants.cs
Labels: size/S

#10167 [VDG] UI Decoupling #3
  WalletWasabi.Fluent/Helpers/LabelHelpers.cs
Labels: size/M

#10251 [VDG] Rename cc title
  WalletWasabi.Fluent/ViewModels/CoinControl/SelectCoinsDialogViewModel.cs
Labels: size/XS

#10245 Add sample for tx history update event on new filter
  WalletWasabi.Fluent/Models/UiTriggers.cs
Labels: size/XS

#10253 [VDG] Coin Control - fix column width
  WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorDataGridSource.cs
  WalletWasabi.Fluent/Views/CoinControl/SelectCoinsDialogView.axaml
Labels: size/XS

#9586 [VDG] Prevent window closing when dialog is open
  WalletWasabi.Fluent/ApplicationStateManager.cs
  WalletWasabi.Fluent/Controls/Dialog.axaml
  WalletWasabi.Fluent/Controls/Dialog.axaml.cs
  WalletWasabi.Fluent/Styles/Themes/BaseDark.axaml
  WalletWasabi.Fluent/Styles/Themes/BaseLight.axaml
  WalletWasabi.Fluent/ViewModels/ApplicationViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/Base/DialogScreenViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/Views/Shell/Dialogs.axaml
Labels: size/L

#10271 [Trivial] Use Count property instead of Enumerable.Count method
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/XS

#10141 [VDG] Fix address reuse coin selection
  WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/Core/CoinControlItemViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/Core/PocketCoinControlItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
Labels: size/M

#10255 [VDG] Coin Control - fix sorting #2
  WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorDataGridSource.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/Core/CoinControlItemViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/Core/PocketCoinControlItemViewModel.cs
Labels: size/S

#10276 [Release] CC fix 1
  WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/Core/CoinControlItemViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/Core/PocketCoinControlItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
Labels: size/M

#10277 [Release] cc fix 2
  WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorDataGridSource.cs
  WalletWasabi.Fluent/Views/CoinControl/SelectCoinsDialogView.axaml
Labels: size/XS

#10278 [Release] fix cc 3
  WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorDataGridSource.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/Core/CoinControlItemViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/Core/PocketCoinControlItemViewModel.cs
Labels: size/S

#10264 [VDG] Fix "All coins confirmed" for single coin
  WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorDataGridSource.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/Core/CoinCoinControlItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/Core/PocketCoinControlItemViewModel.cs
Labels: size/M

#10285 [VDG] Coin Control - fix non relevant cluster gets expanded
  WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/Core/CoinControlItemViewModelBase.cs
Labels: size/S

#10283 [VDG] Prevent dialog cancel on pointer pressed when window is activated
  WalletWasabi.Fluent/Controls/Dialog.axaml.cs
Labels: size/M

#10284 [Release] cc fix 4
  WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorDataGridSource.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/Core/CoinCoinControlItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/Core/PocketCoinControlItemViewModel.cs
Labels: size/M

#10289 Fix output address generation and add test
  WalletWasabi.Tests/Helpers/ServiceFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/CoinJoinClientTests.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/M

#10298 [release] Fix output address generation and add test
  WalletWasabi.Tests/Helpers/ServiceFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/CoinJoinClientTests.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/M

#10295 [Release] cc fix 5
  WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/Core/CoinControlItemViewModelBase.cs
Labels: size/S

#10296 [Release] dialog close prevention
  WalletWasabi.Fluent/Controls/Dialog.axaml.cs
Labels: size/M

#10168 [VDG] UI Decoupling #4
  WalletWasabi.Fluent/Models/Wallets/IWalletModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletModel.cs
Labels: size/M

#10266 Refactor Schedule method
  WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/CoinVerifierTests.cs
  WalletWasabi/WabiSabi/Backend/Banning/CoinVerifier.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
Labels: size/M

#10273 [BnB] Spend address re-used coins together
  WalletWasabi.Fluent/ViewModels/Wallets/Send/ChangeAvoidanceSuggestionViewModel.cs
  WalletWasabi.Tests/UnitTests/Blockchain/TransactionBuilding/ChangelessTransactionCoinSelectorTests.cs
  WalletWasabi/Blockchain/TransactionBuilding/ChangelessTransactionCoinSelector.cs
Labels: size/L

#10294 [Trivial] Fix formatting
  WalletWasabi.Fluent/Behaviors/FlyoutSuggestionBehavior.cs
  WalletWasabi.Fluent/Extensions/FunctionalExtensions.cs
  WalletWasabi.Fluent/Global.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/AdvancedRecoveryOptionsViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/Affiliation/AffiliateDataUpdaterTests.cs
  WalletWasabi.Tests/UnitTests/Affiliation/ReadyToSingRequestRequestCompatibilityTests.cs
  WalletWasabi/Affiliation/AffiliateDataCollector.cs
  WalletWasabi/Affiliation/AffiliateDataUpdater.cs
  WalletWasabi/Affiliation/AffiliateServerStatusUpdater.cs
  WalletWasabi/Affiliation/Extensions/NBitcoinExtensions.cs
  WalletWasabi/Affiliation/RoundData.cs
  WalletWasabi/Bases/ConfigBase.cs
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
  WalletWasabi/Helpers/CoinHelpers.cs
  WalletWasabi/Logging/Logger.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WabiSabi/Client/CoinJoinResult.cs
  WalletWasabi/WabiSabi/Client/SmartRequestNode.cs
  WalletWasabi/WabiSabi/Models/ReadyToSignRequestRequest.cs
  WalletWasabi/Wallets/P2PBlockProvider.cs
  WalletWasabi/Wallets/P2PNodesManager.cs
  WalletWasabi/Wallets/RpcBlockProvider.cs
  WalletWasabi/Wallets/SmartBlockProvider.cs
Labels: size/L

#10120 Fix adding wallet to startup upon start
  WalletWasabi.Fluent/Global.cs
  WalletWasabi.Fluent/Helpers/MacOsStartupHelper.cs
  WalletWasabi.Fluent/Helpers/WindowsStartupHelper.cs
  WalletWasabi.Fluent/UiConfig.cs
  WalletWasabi.Tests/UnitTests/StartWasabiOnSystemStartupTests.cs
  WalletWasabi/Helpers/EnvironmentHelpers.cs
Labels: size/M

#10305 Use block height from response (take 2)
  WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
  WalletWasabi.Tests/Helpers/BitcoinFactory.cs
  WalletWasabi.Tests/UnitTests/MockRpcClient.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/CoinVerifierTests.cs
  WalletWasabi/WabiSabi/Backend/Banning/CoinVerifier.cs
  WalletWasabi/WabiSabi/Backend/Banning/CoinVerifierLogger.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
Labels: size/M

#9236 [VDG] Layout and input diagnostics
  WalletWasabi.Fluent/Controls/XamlAdornerLayer.cs
  WalletWasabi.Fluent/Diagnostics/DiagnosticsExtensions.cs
  WalletWasabi.Fluent/Diagnostics/DiagnosticsWindow.axaml
  WalletWasabi.Fluent/Diagnostics/DiagnosticsWindow.axaml.cs
  WalletWasabi.Fluent/Views/MainWindow.axaml.cs
Labels: size/XL

#10124 Improve Renewal documentation
  WalletWasabi.Documentation/ClientDeployment.md
Labels: size/S

#10243 Bump version to v2.0.3
  WalletWasabi.Backend/wwwroot/index.html
  WalletWasabi/Helpers/Constants.cs
Labels: size/S

#10232 [VDG] Focus dialog when it's opening
  WalletWasabi.Fluent/Controls/Dialog.axaml
  WalletWasabi.Fluent/Controls/Dialog.axaml.cs
Labels: size/M

#10287 [VDG] Make USD amount clipboard suggestions smarter in Send flow
  WalletWasabi.Fluent/Extensions/FunctionalExtensions.cs
  WalletWasabi.Fluent/Infrastructure/ClipboardObserver.cs
  WalletWasabi/Helpers/MathUtils.cs
Labels: size/M

#10265 [VDG] Ignore whitespace to compare incoming and current content
  WalletWasabi.Fluent/Behaviors/FlyoutSuggestionBehavior.cs
  WalletWasabi.Fluent/Helpers/AmountStringComparer.cs
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Labels: size/M

#10229 [VDG] Labels fixes
  WalletWasabi.Fluent/Controls/LabelsItemsPresenter.axaml
  WalletWasabi.Fluent/Controls/LabelsItemsPresenter.axaml.cs
  WalletWasabi.Fluent/Controls/LabelsPanel.cs
  WalletWasabi.Fluent/Controls/TagControl.axaml
  WalletWasabi.Fluent/Styles/Styles.axaml
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/Columns/LabelsColumnView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/Columns/LabelsColumnView.axaml
Labels: size/M

#10342 [VDG] Fix many selected wallet at the same time
  WalletWasabi.Fluent/Models/NavBarSelectedIndicatorState.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
Labels: size/S

#10207 [VDG] Dont copy negative values on Transaction Details's amount.
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/TransactionDetailsViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/Details/TransactionDetailsView.axaml
Labels: size/S

#10331 [VDG] Confirm recovery words - alphabetical instead of random
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/ConfirmRecoveryWordsViewModel.cs
Labels: size/XS

#10352 [VDG] [TRIVIAL] SearchBar: minor wording improvement
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletInfoViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletStatsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinSettingsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletSettingsViewModel.cs
Labels: size/S

#10338 Downgrade warning message to debug
  WalletWasabi/WabiSabi/Client/AliceClient.cs
Labels: size/S

#10354 Add Deepsource analyzer to the repo
  .deepsource.toml
Labels: size/XS

#10351 `NBitcoinExtensions`: Remove unused methods
  WalletWasabi.Tests/UnitTests/NBitcoinTests.cs
  WalletWasabi/Extensions/NBitcoinExtensions.cs
Labels: size/M

#10350 [VDG] Confirm recovery words - adjust layout
  WalletWasabi.Fluent/Views/AddWallet/Create/ConfirmRecoveryWordsView.axaml
Labels: size/XS

#10194 [VDG] Add fiat conversion in notification cards
  WalletWasabi.Fluent/Helpers/NotificationHelpers.cs
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
Labels: size/M

#10355 [Trivial] Fix small issues/recommendations according to deepsource
  WalletWasabi.Fluent/Infrastructure/ClipboardObserver.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/WalletNamePageViewModel.cs
  WalletWasabi/Extensions/TextReaderExtensions.cs
Labels: size/S

#10357 [Trivial] Remove unused method
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
Labels: size/M

#10337 [Clean up] Remove unnecessary local variables
  WalletWasabi.Backend/Global.cs
Labels: size/S

#10336 [Trivial] Instantiate argument exception with parameter name
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/XS

#10335 [Trivial] Remove unused parameter
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/XS

#10340 Make sure to try unregister when we can.
  WalletWasabi/WabiSabi/Client/AliceClient.cs
Labels: size/S

#10349 `HttpContentExtensions`: Cleanup + `CoinVerifierApiClient` cleanup
  WalletWasabi.Tests/UnitTests/Tor/Http/Extensions/HttpContentExtensionsTests.cs
  WalletWasabi/Tor/Http/Extensions/HttpContentExtensions.cs
  WalletWasabi/WabiSabi/Backend/Banning/CoinVerifierApiClient.cs
Labels: size/M

#10363 Make the test easier to understand and play with
  WalletWasabi.Tests/UnitTests/Affiliation/AffiliateDataUpdaterTests.cs
Labels: size/M

#10362 [Trivial] Fix CodeFactor issues
  WalletWasabi.Fluent/Controls/DualCurrencyEntryBox.axaml.cs
  WalletWasabi.Fluent/Controls/QrCode.cs
  WalletWasabi.Fluent/Controls/QuestionControl.axaml.cs
  WalletWasabi/Extensions/RPCClientExtensions.cs
Labels: size/S

#10360 [VDG] Update to Avalonia 0.10.19
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
Labels: size/L

#10359 [VDG] navbar - fix weird case
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
Labels: size/S

#10326 Let Alice timeout instead of remove.
  WalletWasabi/WabiSabi/Client/AliceClient.cs
Labels: size/S

#10369 [VDG] Make ScrollBar thumb more prominent
  WalletWasabi.Fluent/Styles/ScrollViewer.axaml
Labels: size/XS

#10318 Fixed USD parsing in the clipboard observer
  .editorconfig
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
  WalletWasabi.Fluent/Controls/DualCurrencyEntryBox.axaml.cs
  WalletWasabi.Fluent/Helpers/TextHelpers.cs
  WalletWasabi.Fluent/Infrastructure/ClipboardObserver.cs
  WalletWasabi.Tests/UnitTests/Userfacing/BitcoinInputTests.cs
  WalletWasabi.Tests/UnitTests/Userfacing/CurrencyInputTests.cs
  WalletWasabi/Tor/Control/TorControlClientFactory.cs
  WalletWasabi/Userfacing/CurrencyInput.cs
Labels: size/L

#10333 Mobile navgitation fix
  WalletWasabi.Backend/wwwroot/about.html
  WalletWasabi.Backend/wwwroot/contribution.html
  WalletWasabi.Backend/wwwroot/css/style.css
  WalletWasabi.Backend/wwwroot/faq.html
  WalletWasabi.Backend/wwwroot/index.html
  WalletWasabi.Backend/wwwroot/onion-index.html
Labels: size/M

#10364 Fix typos
  WalletWasabi/CoinJoin/Coordinator/Coordinator.cs
  WalletWasabi/Extensions/RPCClientExtensions.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/M

#10382 [Trivial] Fix CodeFactor issues
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
Labels: size/S

#10374 Clipboard text observables produce nullable values
  WalletWasabi.Fluent/Helpers/ApplicationHelper.cs
  WalletWasabi.Fluent/Infrastructure/ClipboardObserver.cs
Labels: size/XS

#10371 [VDG] Fix QR-core is cropped wrong
  WalletWasabi.Fluent/Controls/QrCode.cs
  WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveAddressView.axaml
Labels: size/S

#10373 [VDG] Fix ChangePocketCommand runs in the UI thread and has noticeable delay
  WalletWasabi.Fluent/ViewModels/Wallets/Send/LabelSelectionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/LabelViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Tests/UnitTests/UserInterfaceTest/PocketSelectionTests.cs
Labels: size/L

#10209 [VDG] UI Decoupling #5
  WalletWasabi.Fluent/Models/UI/IQrCodeGenerator.cs
  WalletWasabi.Fluent/Models/UI/QrGenerator.cs
  WalletWasabi.Fluent/Models/UI/UiContext.cs
Labels: size/M

#10390 Simplify LINQ calls
  WalletWasabi.Packager/ArgsProcessor.cs
  WalletWasabi/Blockchain/Analysis/CoinjoinAnalyzer.cs
  WalletWasabi/Services/UpdateManager.cs
Labels: size/S

#10370 [Trivial] Remove type specification
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/XS

#10383 [easy] `P2pNetwork`: Cleanup
  WalletWasabi/BitcoinP2p/P2pNetwork.cs
Labels: size/M

#10210 [VDG] UI Decoupling #6
  WalletWasabi.Fluent/Models/UI/UiContext.cs
  WalletWasabi.Fluent/ViewModels/Navigation/FluentNavigate.cs
  WalletWasabi.Fluent/ViewModels/Navigation/INavigate.cs
Labels: size/M

#10372 [VDG] Fix Send - ´To´ field cuts off some letters at bottom
  WalletWasabi.Fluent/Styles/TextBox.axaml
Labels: size/XS

#10332 [VDG] Fix less option sends the same amount
  WalletWasabi.Fluent/ViewModels/Wallets/Send/ChangeAvoidanceSuggestionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacySuggestionsFlyoutViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Send/ChangeAvoidanceSuggestionControl.axaml
Labels: size/M

#10396 PlebStop preventing log message to Trace
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Labels: size/XS

#10403 Extract SelectCoinsForRound to CoinJoinCoinSelector static class
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/CoinJoinCoinSelectionTests.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinCoinSelector.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WabiSabi/Client/CoinJoinTracker.cs
Labels: size/XL

#10397 Change HdPubKey Labels after Transaction is sent
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
  WalletWasabi/Blockchain/TransactionBuilding/BuildTransactionResult.cs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/M
