Repository WalletWasabi/WalletWasabi, pull requests merged in 2023-02, with the labels that each got.

#10022 Fix my mistake
  WalletWasabi/WabiSabi/Backend/Banning/CoinVerifierLogger.cs
Labels: size/XS

#10027 Retry API request
  WalletWasabi/WabiSabi/Backend/Banning/CoinVerifierApiClient.cs
Labels: size/S

#10001 [VDG] enable selection of CJing coins
  WalletWasabi.Fluent/ViewModels/CoinControl/Core/CoinCoinControlItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/Core/CoinControlItemViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/Columns/SelectionColumnView.axaml
Labels: size/S

#10036 [VDG] Fix FadeOutTextBlock not updating on text change.
  WalletWasabi.Fluent/Controls/FadeOutTextBlock.cs
Labels: size/XS

#8852 Separate wasabi and wabisabi clients
  WalletWasabi.Fluent/Config.cs
  WalletWasabi.Fluent/Global.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Labels: size/M

#10035 [VDG] fix balance format
  WalletWasabi.Fluent/Converters/MoneyConverters.cs
Labels: size/XS

#10042 Upgrade NBitcoin version from 7.0.14 to 7.0.24
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/packages.lock.json
  WalletWasabi.Packager/packages.lock.json
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
  WalletWasabi/WalletWasabi.csproj
  WalletWasabi/packages.lock.json
Labels: size/M

#10041 Fix coins dialog on address reuse
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
Labels: size/XS

#10039 Fix feature request workflow
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: size/S

#10046 Fix dust attack prevention logic
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
Labels: size/M

#10024 Fix relative path in uri
  WalletWasabi.Tests/XunitConfiguration/RegTestFixture.cs
  WalletWasabi/WebClients/Bitstamp/BitstampExchangeRateProvider.cs
  WalletWasabi/WebClients/CoinGecko/CoinGeckoExchangeRateProvider.cs
  WalletWasabi/WebClients/Wasabi/WasabiClient.cs
Labels: size/S

#10050 [VDG] Wallet Coins - fix memory leak
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
Labels: size/XS

#10026 [VDG] `CoinJoinStateViewModel` - Cleanup
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/MusicStatusMessageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletSettingsViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/MusicControlsView.axaml
Labels: size/L

#9998 [VDG] Recovery words option - cleanup
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/AdvancedRecoveryOptionsViewModel.cs
Labels: size/M

#9997 [VDG] Verify Recovery Words - cleanup
  WalletWasabi.Fluent/ViewModels/Wallets/VerifyRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/VerifyRecoveryWordsView.axaml
Labels: size/M

#9996 [VDG] Recover Wallet - cleanup
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/RecoverWalletView.axaml
Labels: size/L

#9625 TransactionSizeException - add failing test
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
  WalletWasabi/Blockchain/TransactionBuilding/SmartCoinSelector.cs
Labels: size/L

#10045 Non default ServiceConfiguration at client init
  WalletWasabi.Fluent/Config.cs
Labels: size/XS

#10054 [VDG] Fix HoldKeyBehavior stuck when MainWindow deactivated
  WalletWasabi.Fluent/Behaviors/HoldKeyBehavior.cs
  WalletWasabi.Fluent/Helpers/ApplicationHelper.cs
Labels: size/M

#9940 [Trivial] Use field
  WalletWasabi.Fluent/TreeDataGrid/TreeDataGridPlainTextCell.cs
Labels: size/S

#10073 Fix some CodeFactor issues
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Labels: size/L

#10077 `Config`: Merge load methods
  WalletWasabi.Backend/InitConfigStartupTask.cs
  WalletWasabi.Backend/Startup.cs
  WalletWasabi.Fluent.Desktop/Program.cs
  WalletWasabi.Fluent/Config.cs
  WalletWasabi.Tests/UnitTests/StartWasabiOnSystemStartupTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/ConfigTests.cs
  WalletWasabi/Bases/ConfigBase.cs
  WalletWasabi/Interfaces/IConfig.cs
  WalletWasabi/Services/ConfigWatcher.cs
  WalletWasabi/WabiSabi/CoordinatorParameters.cs
Labels: size/M

#10066 [VDG] Coin Control - Rebuild data source when coins change
  WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorDataGridSource.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/SelectCoinsDialogViewModel.cs
Labels: size/L

#10069 [Trivial] Add indentation preference in .editorconfig files
  WalletWasabi.Fluent/MathNet/.editorconfig
  WalletWasabi.Fluent/Models/Windows/.editorconfig
  WalletWasabi/Gma/.editorconfig
  WalletWasabi/Nito/.editorconfig
Labels: size/S

#9958 Remove `Config.TryEnsureBackwardsCompatibility`
  WalletWasabi.Backend/Config.cs
  WalletWasabi.Fluent/Config.cs
  WalletWasabi/Bases/ConfigBase.cs
Labels: size/L

#10075 Retry in case of exception/timeout of HttpClient
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/CoinVerifierTests.cs
  WalletWasabi/WabiSabi/Backend/Banning/CoinVerifierApiClient.cs
Labels: size/M

#10017 P2PBlockProvider refactor
  WalletWasabi.Fluent/Global.cs
  WalletWasabi.Tests/IntegrationTests/P2pTests.cs
  WalletWasabi.Tests/RegressionTests/BuildTests.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi.Tests/RegressionTests/WalletTests.cs
  WalletWasabi.Tests/UnitTests/SmartBlockProviderTests.cs
  WalletWasabi.Tests/UnitTests/TestBlockProvider.cs
  WalletWasabi/BitcoinCore/CoreNode.cs
  WalletWasabi/Wallets/CachedBlockProvider.cs
  WalletWasabi/Wallets/FileSystemBlockRepository.cs
  WalletWasabi/Wallets/IBlockProvider.cs
  WalletWasabi/Wallets/P2PBlockProvider.cs
  WalletWasabi/Wallets/P2PNodesManager.cs
  WalletWasabi/Wallets/P2pBlockProvider.cs
  WalletWasabi/Wallets/RpcBlockProvider.cs
  WalletWasabi/Wallets/SmartBlockProvider.cs
  WalletWasabi/Wallets/SpecificNodeBlockProvider.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/XXL

#10095 Quick fix for incorrect fee issue
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/ConstructionState.cs
Labels: size/S

#10087 [Trivial] Remove unnecessary dollar sign '$'
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Labels: size/S

#10070 [Trivial] Remove unnecessary suppressions
  WalletWasabi.Fluent/Models/Windows/DirectShow.cs
  WalletWasabi.Fluent/Models/Windows/WindowsCapture.cs
Labels: size/S

#10107 [Trivial] Fix CodeFactor issues
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Labels: size/S

#10098 Improve log message
  WalletWasabi/WabiSabi/Backend/Banning/CoinVerifier.cs
Labels: size/XS

#10110 Add request time statista for requests
  WalletWasabi/WabiSabi/Backend/Banning/CoinVerifier.cs
  WalletWasabi/WabiSabi/Backend/Banning/CoinVerifierApiClient.cs
Labels: size/S

#10062 Do not enforce identity change when connecting to p2p nodes
  WalletWasabi/BestEffortEndpointConnector.cs
Labels: size/XS

#10009 remove local from InvalidOperationException
  WalletWasabi/Extensions/NBitcoinExtensions.cs
Labels: size/XS

#10113 [Trivial] Fix CodeFactor issues
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
  WalletWasabi/Extensions/NBitcoinExtensions.cs
  WalletWasabi/WabiSabi/Client/RoundStateAwaiters/RoundStateUpdater.cs
Labels: size/S

#10116 Add missing equality comparer
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/XS

#10117 Fix the impossible :)
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/XS

#10121 Fix missing navbar wallet icon resources
  WalletWasabi.Fluent/Icons/Icons.axaml
Labels: size/XS

#10074 [VDG] Coin freeze - remove leftover
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/WalletCoinsView.axaml
Labels: size/S

#10082 [VDG] Close address displaying dialog when received funds
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressViewModel.cs
Labels: size/XS

#10109 [VDG] Send - fix labels for coin list
  WalletWasabi.Fluent/ViewModels/CoinControl/Core/CoinCoinControlItemViewModel.cs
Labels: size/XS

#10089 [VDG] Fix splash animation
  WalletWasabi.Fluent/Controls/Spectrum/AuraSpectrumDataSource.cs
  WalletWasabi.Fluent/Controls/Spectrum/SpectrumControl.cs
  WalletWasabi.Fluent/Controls/Spectrum/SpectrumDataSource.cs
  WalletWasabi.Fluent/Controls/Spectrum/SplashEffectDataSource.cs
Labels: size/L

#10115 Fix removal of items when task is completed
  WalletWasabi/WabiSabi/Backend/Banning/CoinVerifier.cs
Labels: size/S

#10125 [Trivial] Fix CodeFactor issues
  WalletWasabi/Extensions/NBitcoinExtensions.cs
  WalletWasabi/Tor/Http/Helpers/HttpMessageHelper.cs
Labels: size/XS

#10118 [trivial] `IndexBuilderService`: nits
  WalletWasabi/Blockchain/BlockFilters/IndexBuilderService.cs
  WalletWasabi/Blockchain/BlockFilters/StartingFilters.cs
  WalletWasabi/Stores/BitcoinStore.cs
Labels: size/S

#10128 [Trivial] Fix CodeFactor issues in ApplicationStateManager.cs
  WalletWasabi.Fluent/ApplicationStateManager.cs
Labels: size/M

#10059 State machine will follow the business logic (continuation)
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Labels: size/M

#10032 State machine will follow the business logic
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
Labels: size/S

#10134 BnB: Trivial changes
  WalletWasabi.Fluent/Helpers/TransactionHelpers.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorDataGridSource.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/ChangeAvoidanceSuggestionViewModel.cs
  WalletWasabi.Tests/UnitTests/Blockchain/TransactionBuilding/ChangelessTransactionCoinSelectorTests.cs
  WalletWasabi/Blockchain/TransactionBuilding/BnB/LessSelectionStrategy.cs
  WalletWasabi/Blockchain/TransactionBuilding/BnB/MoreSelectionStrategy.cs
  WalletWasabi/Blockchain/TransactionBuilding/BranchAndBound.cs
  WalletWasabi/Blockchain/TransactionBuilding/ChangelessTransactionCoinSelector.cs
Labels: size/M

#10140 Add comment for future debugs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/XS

#10143 [VDG] Disable splash animation on full private wallets
  WalletWasabi.Fluent/Views/Shell/MainScreen.axaml
Labels: size/XS

#10123 Fix wallet start hidden
  WalletWasabi.Fluent/ApplicationStateManager.cs
Labels: size/S

#10163 Creates UT to verify script type of change outputs
  WalletWasabi.Tests/UnitTests/KeyManagementTests.cs
Labels: size/S

#10169 [Affiliate server] Fix flaky `AffiliateServerStatusUpdaterTests.GetStatusTestAsync` test
  WalletWasabi.Tests/UnitTests/Affiliation/ServerStatusUpdaterTests.cs
Labels: size/XS

#10138 Updated PGP until 2028.02.24.
  PGP.txt
Labels: size/L

#10174 Move CTS to caller
  WalletWasabi/WabiSabi/Backend/Banning/CoinVerifier.cs
  WalletWasabi/WabiSabi/Backend/Banning/CoinVerifierApiClient.cs
Labels: size/S

#10176 Key generator for affiliation server
  Contrib/AffiliationServer/README.md
  Contrib/AffiliationServer/signerkeygen.fsx
Labels: size/S

#10179 [Trivial] Fix typos
  Contrib/AffiliationServer/README.md
Labels: size/XS

#10157 [VDG] Fix copy button
  WalletWasabi.Fluent/Controls/PreviewItem.axaml.cs
Labels: size/S

#10161 [VDG] Privacy Ring - attempt to fix double animation
  WalletWasabi.Fluent/Behaviors/ItemsPresenterAnimationBehavior.cs
Labels: size/XS

#10146 [VDG] fix confusing wrong message about passphrase
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/ConnectHardwareWalletViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/HardwareWallet/ConnectHardwareWalletView.axaml
Labels: size/M

#10197 [silent release] Add softwareexpiry=0 to knots parameters
  WalletWasabi/BitcoinCore/CoreNode.cs
Labels: size/XS

#10151 Fix coinjoin EffectiveFeeRate issue with reverse calculation
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/MultipartyTransactionTests.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/ConstructionState.cs
Labels: size/M

#10196 [silent release] Upgrade NBitcoin version from 7.0.14 to 7.0.24
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/packages.lock.json
  WalletWasabi.Packager/packages.lock.json
  WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
  WalletWasabi/WalletWasabi.csproj
  WalletWasabi/packages.lock.json
Labels: size/S

#10199 [silent release] Bump client version to 2.0.2.2
  WalletWasabi.Backend/wwwroot/index.html
  WalletWasabi/Helpers/Constants.cs
Labels: size/S

#10201 Bump client version to 2.0.2.2
  WalletWasabi.Backend/wwwroot/index.html
  WalletWasabi/Helpers/Constants.cs
Labels: size/S

#10204 Orgainize contrib
  Contrib/Containers/.dockerignore
  Contrib/Containers/Dockerfile
  Contrib/Containers/README.md
  Contrib/Containers/docker-compose.yml
  Contrib/WalletDiagnostic/README.md
  Contrib/WalletDiagnostic/common.fsx
  Contrib/WalletDiagnostic/img/txgraph.png
  Contrib/WalletDiagnostic/img/walletkeys.png
  Contrib/WalletDiagnostic/keygraph.fsx
  Contrib/WalletDiagnostic/txgraph.fsx
Labels: size/L
