Repository WalletWasabi/WalletWasabi, pull requests merged in 2023-06, with the labels that each got.

#10697 [VDG] Fix CoinjoinError.NoCoinsToMix message in music box
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WabiSabi/Client/StatusChangedEvents/StatusChangedEventArgs.cs
Labels: size/S

#10655 wcli+taproot
  Contrib/CLI/README.md
  Contrib/CLI/wcli.sh
  WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
Labels: size/L

#10827 [Trivial] Clean up for documentation
  Contrib/CLI/README.md
  WalletWasabi.Documentation/HowToDeploy.md
Labels: size/XS

#10386 [VDG] UI Decoupling - Receive #3
  WalletWasabi.Fluent/Models/Wallets/Address.cs
  WalletWasabi.Fluent/Models/Wallets/WalletModelExtensions.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/ConfirmHideAddressViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/AddressLabelEditViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/AddressViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressesDataGridSource.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressesViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Receive/Columns/AddressColumnView.axaml
  WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveView.axaml
  WalletWasabi.Tests/UnitTests/ViewModels/AddressViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/Extensions.cs
  WalletWasabi.Tests/UnitTests/ViewModels/Mocks.cs
  WalletWasabi.Tests/UnitTests/ViewModels/ReceiveAddressViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/ReceiveViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/TestDoubles/NavigationMock.cs
  WalletWasabi.Tests/UnitTests/ViewModels/UiContextBuilder.cs
Labels: size/XL

#10824 Ensure min output amount is economical in coinjoins
  WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
Labels: size/S

#10782 [Trivial] Fixes warnings
  WalletWasabi.Tests/UnitTests/Affiliation/AffiliateDataUpdaterTests.cs
  WalletWasabi/Helpers/ScriptSizeHelpers.cs
Labels: size/XS, affiliate

#10783 [Trivial] Fix whitespaces and formatting
  WalletWasabi.Fluent.Generators/AnalyzerExtensions.cs
  WalletWasabi.Fluent.Generators/UIContextGenerator.cs
  WalletWasabi.Fluent/Behaviors/ButtonExecuteCommandOnKeyDownBehavior.cs
  WalletWasabi.Fluent/Behaviors/ExecuteCommandOnKeyDownBehavior.cs
  WalletWasabi.Fluent/Behaviors/ListBoxPreviewBehavior.cs
  WalletWasabi.Fluent/Models/Wallets/WalletModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/ConfirmRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/Base/DialogViewModelBaseOfTResult.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/ShuttingDownViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingViewModel.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/Participant.cs
  WalletWasabi/Blockchain/Analysis/Clustering/LabelsArray.cs
  WalletWasabi/Blockchain/Analysis/Clustering/LabelsArrayComparer.cs
  WalletWasabi/Crypto/StrobeProtocol/StrobeHasherExtensions.cs
  WalletWasabi/Extensions/EnumExtension.cs
  WalletWasabi/Extensions/RPCClientExtensions.cs
  WalletWasabi/Helpers/RuntimeParams.cs
  WalletWasabi/Stores/IndexStore.cs
  WalletWasabi/Tor/Control/Messages/Events/StatusEvents/BootstrapStatusEvent.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Crypto/RoundHasher.cs
  WalletWasabi/Wallets/Wallet.cs
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/L

#10840 Decouple stuff from Amount Decomposer
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/AmountDecomposerTests.cs
  WalletWasabi/WabiSabi/Backend/Rounds/RoundParameters.cs
  WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
  WalletWasabi/WabiSabi/Client/DenominationBuilder.cs
  WalletWasabi/WabiSabi/Client/OutputProvider.cs
Labels: size/L

#10823 Alternative implementation for Combinations
  WalletWasabi/Extensions/LinqExtensions.cs
Labels: size/M

#10832 [VDG] Fix TagsBox
  WalletWasabi.Fluent/Controls/TagsBox.axaml.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/LabelEntryDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Labels/SuggestionLabelsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveViewModel.cs
  WalletWasabi.Fluent/Views/Dialogs/LabelEntryDialogView.axaml
  WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveView.axaml
Labels: size/M

#10818 Simplify fee estimations from mempool
  WalletWasabi.Tests/Helpers/MempoolInfoGenerator.cs
  WalletWasabi.Tests/UnitTests/AllFeeEstimateTests.cs
  WalletWasabi.Tests/UnitTests/Data/MempoolInfoWithHistogram.json
  WalletWasabi.Tests/UnitTests/Data/MempoolInfoWithHistogram1.json
  WalletWasabi.Tests/UnitTests/Data/MempoolInfoWithHistogram2.json
  WalletWasabi.Tests/WalletWasabi.Tests.csproj
  WalletWasabi/Extensions/RPCClientExtensions.cs
Labels: size/XXL

#10837 Remove unused members
  WalletWasabi.Fluent/ViewModels/Dialogs/ShowQrCameraDialogViewModel.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiApiApplicationFactory.cs
Labels: size/XS

#10834 [VDG] UI Decoupling - Balance and Price tiles
  WalletWasabi.Fluent/Infrastructure/ClipboardObserver.cs
  WalletWasabi.Fluent/Infrastructure/ExchangeRateProvider.cs
  WalletWasabi.Fluent/Infrastructure/IExchangeRateProvider.cs
  WalletWasabi.Fluent/Models/Wallets/IWalletModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/BtcPriceTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletBalanceTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/IWalletBalancesModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletBalances.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletBalancesModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
  WalletWasabi.Tests/UnitTests/ViewModels/ReceiveAddressViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/ReceiveViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/SuggestionLabelsViewModelTests.cs
Labels: size/L

#10846 RPC: rename anonymitySet to anonymityScore
  WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
Labels: size/XS

#10647 [VDG] UI Decoupling #17
  WalletWasabi.Fluent/Models/Wallets/IWalletAuthModel.cs
  WalletWasabi.Fluent/Models/Wallets/IWalletLoadWorkflow.cs
  WalletWasabi.Fluent/Models/Wallets/IWalletModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletAuthModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletLoadWorkflow.cs
  WalletWasabi.Fluent/Models/Wallets/WalletLoginResult.cs
  WalletWasabi.Fluent/Models/Wallets/WalletModel.cs
  WalletWasabi.Fluent/ViewModels/Login/LoginViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/LoadingViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletPageViewModel .cs
  WalletWasabi.Tests/UnitTests/ViewModels/ReceiveAddressViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/ReceiveViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/SuggestionLabelsViewModelTests.cs
Labels: size/XL

#10848 Do not pay too much
  WalletWasabi.Tests/UnitTests/AllFeeEstimateTests.cs
  WalletWasabi/Extensions/RPCClientExtensions.cs
Labels: size/M

#10853 `PlainTextElementFactory`: Fix nullability warning
  WalletWasabi.Fluent/TreeDataGrid/PlainTextElementFactory.cs
  WalletWasabi.Fluent/TreeDataGrid/PrivacyElementFactory.cs
Labels: size/XS

#10772 [VDG] Fix BTC format in send view for full balance paste
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
Labels: size/S

#10856 [VDG] make return type nullable
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/AddressLabelEditViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressesViewModel.cs
Labels: size/XS

#10819 [VDG] SearchBar - Press ENTER key to activate item
  WalletWasabi.Fluent/Behaviors/KeyDownTrigger.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/SearchBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/SearchItems/ActionableItem.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/SearchItems/IActionableItem.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/Sources/ActionsSearchSource.cs
  WalletWasabi.Fluent/Views/SearchBar/SearchBar.axaml
  WalletWasabi.Fluent/Views/SearchBar/SearchBarDropdown.axaml
Labels: size/M

#10658 Minor `WabiSabiProtocolException` usage refactor in Alice-/CoinJoinClient
  WalletWasabi/WabiSabi/Client/AliceClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/L

#10842 Add minimum input sum check
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/AmountDecomposerTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/CoinJoinCoinSelectionTests.cs
  WalletWasabi/WabiSabi/Backend/Rounds/RoundParameters.cs
  WalletWasabi/WabiSabi/Backend/Rounds/UtxoSelectionParameters.cs
  WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
  WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
  WalletWasabi/WabiSabi/Client/CoinJoinCoinSelector.cs
  WalletWasabi/WabiSabi/Client/DenominationBuilder.cs
  WalletWasabi/WabiSabi/Client/OutputProvider.cs
Labels: size/L

#10861 [VDG] Excluded VideoForWindows from web cam devices
  WalletWasabi.Fluent/Models/UI/QrCodeReader.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/ShowQrCameraDialogViewModel.cs
Labels: size/S

#10862 [VDG] Deduplication of suggested labels based on score
  WalletWasabi.Fluent/ViewModels/Wallets/Labels/SuggestionLabelsViewModel.cs
  WalletWasabi.Tests/UnitTests/ViewModels/SuggestionLabelsViewModelTests.cs
Labels: size/S

#10860 [VDG] Excluded fee from amount for outgoing transactions
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/TransactionDetailsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinsHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/HistoryItemViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/TransactionHistoryItemViewModel.cs
Labels: size/M

#10870 [VDG] close suggestions when input field is empty
  WalletWasabi.Fluent/Controls/TagsBox.axaml.cs
Labels: size/S

#10863 [VDG] Changed format of copied privacy balance
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyControlTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyRing/PrivacyRingDetailsView.axaml
Labels: size/S

#10873 [VDG] fix discreet mode cut off
  WalletWasabi.Fluent/ViewModels/Settings/PrivacyModeViewModel.cs
Labels: size/S

#10872 [VDG] Fix LastSelectedWallet
  WalletWasabi.Fluent/Models/UI/NullWalletList.cs
  WalletWasabi.Fluent/Models/Wallets/IWalletListModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletListModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
Labels: size/S

#10876 [VDG] Fix format for private amount of the privacy ring
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyRing/PrivacyRingDetailsView.axaml
Labels: size/XS

#10716 [VDG] UI Decoupling #22
  WalletWasabi.Fluent/Models/Wallets/IWalletModel.cs
  WalletWasabi.Fluent/Models/Wallets/IWalletSettingsModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletSettingsModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/AddedWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/ConfirmRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/CoinJoinProfilesViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/ManualCoinJoinProfileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinSettingsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletSettingsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Tests/UnitTests/ViewModels/ReceiveAddressViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/ReceiveViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/SuggestionLabelsViewModelTests.cs
Labels: size/L

#10875 [VDG] CurrencyEntryBox - do not allow space
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
  WalletWasabi.Fluent/Helpers/TextHelpers.cs
Labels: size/S

#10718 [VDG] UI Decoupling #23
  WalletWasabi.Fluent/Models/UI/NullWalletList.cs
  WalletWasabi.Fluent/Models/Wallets/IWalletListModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletListModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/AdvancedRecoveryOptionsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/CreatePasswordDialogViewModel.cs
Labels: size/L

#10869 [VDG] Fix NavBarItem stlye
  WalletWasabi.Fluent/Behaviors/NavBarSelectedIndicatorChildBehavior.cs
  WalletWasabi.Fluent/Controls/NavBarItem.axaml
  WalletWasabi.Fluent/Controls/NavBarItem.axaml.cs
  WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
Labels: size/L

#10607 Don't show CJ broadcasted if wallet had no input in the round
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/StatusChangedEvents/StatusChangedEventArgs.cs
Labels: size/XS

#10767 Close flyouts on window focus lose or resize
  WalletWasabi.Fluent/Behaviors/BindableFlyoutOpenBehavior.cs
  WalletWasabi.Fluent/Behaviors/ContextFlyoutWorkaroundBehavior.cs
  WalletWasabi.Fluent/Behaviors/FlyoutSuggestionBehavior.cs
  WalletWasabi.Fluent/Behaviors/ShowAttachedFlyoutWhenFocusedBehavior.cs
  WalletWasabi.Fluent/Behaviors/ShowFlyoutOnPointerOverBehavior.cs
  WalletWasabi.Fluent/Behaviors/ShowFlyoutWhenFocusedBehavior.cs
  WalletWasabi.Fluent/Helpers/FlyoutHelpers.cs
  WalletWasabi.Fluent/Helpers/FlyoutShowController.cs
  WalletWasabi.Fluent/Views/MainWindow.axaml
  WalletWasabi.Fluent/Views/SearchBar/SearchBar.axaml
Labels: size/XL

#10883 Packager: Rename Daemon + Fix for `Release` mode
  WalletWasabi.Daemon/WalletWasabi.Daemon.csproj
  WalletWasabi.Packager/Program.cs
  WalletWasabi/Helpers/Constants.cs
Labels: size/M

#10892 [VDG] [Trivial] Show anonscore for all items
  WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorDataGridSource.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/Core/CoinCoinControlItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/Core/CoinControlItemViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/Core/PocketCoinControlItemViewModel.cs
Labels: size/M

#10893 [VDG] Add destination address to transaction summary
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/TransactionDetailsViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/Details/TransactionDetailsView.axaml
  WalletWasabi/Blockchain/Transactions/Summary/ForeignOutput.cs
  WalletWasabi/Blockchain/Transactions/Summary/Output.cs
  WalletWasabi/Blockchain/Transactions/Summary/OwnOutput.cs
  WalletWasabi/Blockchain/Transactions/TransactionHistoryBuilder.cs
  WalletWasabi/Blockchain/Transactions/TransactionSummary.cs
Labels: size/M

#10730 [VDG] UI Decoupling #24
  WalletWasabi.Fluent/Models/UI/NullWalletList.cs
  WalletWasabi.Fluent/Models/Wallets/IPasswordFinderModel.cs
  WalletWasabi.Fluent/Models/Wallets/IWalletListModel.cs
  WalletWasabi.Fluent/Models/Wallets/IWalletModel.cs
  WalletWasabi.Fluent/Models/Wallets/IWalletSettingsModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletListModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletSettingsModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/AddedWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/ConfirmRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/DetectedHardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/WalletNamePageViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/CoinJoinProfilesViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/ManualCoinJoinProfileDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/LoginViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/PasswordFinderIntroduceViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinSettingsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletPageViewModel .cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
Labels: size/L

#10780 Make sure used keys are saved into a file.
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WabiSabi/Client/KeyChain.cs
Labels: size/XS

#10898 [VDG] Allow shutdown main view when no wallets are present
  WalletWasabi.Fluent/ViewModels/ApplicationViewModel.cs
Labels: size/XS

#10664 On shutdown prevention, stop the CJM to participate in new rounds. On cancel, restart them.
  WalletWasabi.Fluent/ViewModels/Dialogs/ShuttingDownViewModel.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WabiSabi/Client/CoinJoinTracker.cs
Labels: size/M

#10745 [VDG] UI Decoupling #25
  CONTRIBUTING.md
  WalletWasabi.Fluent/Models/UI/NullWalletRepository.cs
  WalletWasabi.Fluent/Models/UI/UiContext.cs
  WalletWasabi.Fluent/Models/Wallets/IWalletRepository.cs
  WalletWasabi.Fluent/Models/Wallets/WalletRepository.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/AddedWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/ConfirmRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/CoinJoinProfilesViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Tests/UnitTests/ViewModels/Mocks.cs
  WalletWasabi.Tests/UnitTests/ViewModels/UiContextBuilder.cs
Labels: size/M

#10933 Fix `FilterDownloaderTestAsync`
  WalletWasabi.Tests/RegressionTests/Common.cs
Labels: size/XS

#10907 [VDG] Copy individual address
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/TransactionDetailsViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/Details/TransactionDetailsView.axaml
Labels: size/M

#10932 [VDG][Trivial] Simplify text of Preview Transaction dialog
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionSummaryViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionSummary.axaml
Labels: UI, size/S

#10746 [VDG] UI Decoupling #26
  WalletWasabi.Fluent/ViewModels/AddWallet/AddedWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/INavigate.cs
  WalletWasabi.Fluent/ViewModels/Navigation/IWalletNavigation.cs
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationState.cs
  WalletWasabi.Fluent/ViewModels/Wallets/IWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Tests/UnitTests/ViewModels/Mocks.cs
  WalletWasabi.Tests/UnitTests/ViewModels/TestDoubles/NavigationMock.cs
Labels: size/L

#10896 TurboSync: Final
  WalletWasabi.Tests/UnitTests/TestWallet.cs
  WalletWasabi.Tests/UnitTests/Wallet/MockNode.cs
  WalletWasabi.Tests/UnitTests/Wallet/TestWalletExtensions.cs
  WalletWasabi.Tests/UnitTests/Wallet/WalletBuilder.cs
  WalletWasabi.Tests/UnitTests/Wallet/WalletSynchronizationTests.cs
  WalletWasabi/Blockchain/Keys/HdPubKey.cs
  WalletWasabi/Blockchain/Keys/HdPubKeyCache.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/Extensions/NBitcoinExtensions.cs
  WalletWasabi/Wallets/SyncType.cs
  WalletWasabi/Wallets/Wallet.cs
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/XL

#10935 [tests]: Introduce `RegTestSetup` & stabilize reg tests
  WalletWasabi.Tests/Helpers/BitcoinFactory.cs
  WalletWasabi.Tests/RegressionTests/BackendTests.cs
  WalletWasabi.Tests/RegressionTests/BuildTests.cs
  WalletWasabi.Tests/RegressionTests/Common.cs
  WalletWasabi.Tests/RegressionTests/RegTestSetup.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi.Tests/RegressionTests/WalletTests.cs
  WalletWasabi.Tests/XunitConfiguration/CollectionDefinitions.cs
  WalletWasabi.Tests/XunitConfiguration/RegTestCollectionDefinition.cs
  WalletWasabi.Tests/XunitConfiguration/RegTestFixture.cs
  WalletWasabi/Stores/IndexStore.cs
Labels: size/XL

#10949 TurboSync: Add missing namespace
  WalletWasabi.Tests/UnitTests/Wallet/MockNode.cs
Labels: size/XS

#10845 `PasswordFinderHelper`: Fix warnings
  WalletWasabi/Wallets/PasswordFinder/PasswordFinderHelper.cs
Labels: size/XS

#10950 TurboSync: Remove an extra `while`
  WalletWasabi/Wallets/Wallet.cs
Labels: size/S

#10953 [WabiSabi] Do not ban inputs without valid ownership proof
  WalletWasabi/WabiSabi/Backend/Models/WabiSabiProtocolErrorCode.cs
Labels: size/XS

#10952 [WabiSabi] Verify ownership proof before any other policies
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputToBlameRoundTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/ConstructionState.cs
Labels: size/L

#10961 Fix inconsistency in Github
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
Labels: size/XS
