Repository WalletWasabi/WalletWasabi, pull requests merged in 2023-05, with the labels that each got.

#10599 [trivial] improve wording crash report title
  WalletWasabi.Fluent.Desktop/Program.cs
Labels: size/XS

#10453 Monitoring the target fees when broadcasting CJ
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/S

#10557 [VDG] Improve Unused Receive Addresses wording
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressesViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveAddressesView.axaml
  WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveView.axaml
Labels: size/XS

#10551 SQLite migration code
  WalletWasabi/Backend/Models/FilterModel.cs
  WalletWasabi/Stores/BlockFilterSqliteStorage.cs
  WalletWasabi/Stores/IndexStore.cs
  exclusion.dic
Labels: size/L

#10603 [Payment in Coinjoin] Output provider
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/CoinJoinClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/CoinJoinCoinSelectionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/Participant.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinCoinSelector.cs
  WalletWasabi/WabiSabi/Client/CoinJoinTrackerFactory.cs
  WalletWasabi/WabiSabi/Client/OutputProvider.cs
Labels: size/L

#10594 [Trivial] Fix CodeFactor
  WalletWasabi.Fluent/Controls/LineChart.cs
  WalletWasabi/Blockchain/Blocks/BlockNotifier.cs
  WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
  WalletWasabi/Services/Terminate/TerminateService.cs
  WalletWasabi/WebClients/PayJoin/PayjoinClient.cs
Labels: size/M

#10623 Fixed DeepSource warnings
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
Labels: size/S

#10611 Removed logic duplication in sort methods
  WalletWasabi.Fluent/Helpers/Sort.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorDataGridSource.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/HistoryItemViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/AddressViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressesViewModel.cs
Labels: size/L

#10633 Height: Fix typos
  WalletWasabi/Models/Height.cs
Labels: size/S

#10617 [TurboSync] TurboSyncHeight: Set and Save
  WalletWasabi.Daemon/Global.cs
  WalletWasabi/Blockchain/Keys/BlockchainState.cs
  WalletWasabi/Blockchain/Keys/HdPubKey.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/Blockchain/Keys/WalletGenerator.cs
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
  WalletWasabi/Helpers/ImportWalletHelper.cs
  WalletWasabi/JsonConverters/HeightJsonConverter.cs
  WalletWasabi/JsonConverters/WalletHeightJsonConverter.cs
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/L

#10446 [VDG] UI Decoupling #13
  WalletWasabi.Fluent.Generators/UIContextGenerator.cs
  WalletWasabi.Fluent/App.axaml.cs
  WalletWasabi.Fluent/ApplicationStateManager.cs
  WalletWasabi.Fluent/ViewModels/ApplicationViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/INavigate.cs
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationState.cs
Labels: size/L

#10643 Removed useless allocations
  WalletWasabi.Fluent/Helpers/CoinPocketHelper.cs
Labels: size/XS

#10651 Fix parsing error reporting
  WalletWasabi/Rpc/JsonRpcServer.cs
Labels: size/S

#10592 Add words to exclusion.dic
  WalletWasabi.Fluent.Generators/UIContextGenerator.cs
  WalletWasabi/BitcoinCore/Rpc/RpcParser.cs
  WalletWasabi/BitcoinP2p/P2pNetwork.cs
  WalletWasabi/Blockchain/Blocks/BlockNotifier.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/Blockchain/TransactionOutputs/CoinsView.cs
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
  WalletWasabi/Tor/Control/Messages/CircuitStatus/CircuitInfo.cs
  exclusion.dic
Labels: size/L

#10387 [VDG] UI Decoupling - Receive #2
  WalletWasabi.Fluent/Controls/AnimatedButton.axaml.cs
  WalletWasabi.Fluent/Controls/QrCode.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/AddressViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressesViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveAddressView.axaml
  WalletWasabi.Tests/UnitTests/ViewModels/ReceiveAddressViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/TestDoubles/TestAddress.cs
Labels: size/L

#10652 http request better message
  WalletWasabi.Fluent/Extensions/FriendlyExceptionMessageExtensions.cs
Labels: size/S

#10671 Dont check `MainViewCanShutdown` in `ShuttingDownViewModel`
  WalletWasabi.Fluent/ViewModels/Dialogs/ShuttingDownViewModel.cs
Labels: size/XS

#10695 [VDG] Fix wallet navigation via Notification Click
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
Labels: size/XS

#10624 [VDG] Fix Amount Suggestion not showing
  WalletWasabi.Fluent/Helpers/ApplicationHelper.cs
  WalletWasabi.Fluent/Infrastructure/ClipboardObserver.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
Labels: size/M

#10721 [VDG] Fix CJ group child item selection from SearchBar result
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
Labels: size/S

#10723 [VDG] Improve history selection from SearchBar
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
Labels: size/XS

#10699 Refine AS Punishment Criteria
  WalletWasabi.Tests/Helpers/BitcoinFactory.cs
  WalletWasabi.Tests/UnitTests/BlockchainAnalysis/CoinJoinAnonscoreTests.cs
  WalletWasabi.Tests/UnitTests/BlockchainAnalysis/PubKeyReuseAnonScoreTests.cs
  WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs
  WalletWasabi/Blockchain/Analysis/StartingAnonScores.cs
Labels: size/L

#10725 [VDG] Disable Back in Dialogs when Escape is pressed
  WalletWasabi.Fluent/ViewModels/Navigation/RoutableViewModel.cs
Labels: size/XS

#10732 [VDG] Update to Avalonia 0.10.20
  WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Fluent/packages.lock.json
Labels: size/L

#10731 [Index][Migration] Remove old index data
  WalletWasabi/Stores/IndexStore.cs
Labels: size/S

#10711 [FireProofing] Mark output script as used if round signaled as ended
  WalletWasabi/Exceptions/UnknownRoundEndingException.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Labels: size/M

#10736 Reduce Non-Standard Changes
  WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
Labels: priority, size/XS

#10747 Prefer less change
  WalletWasabi.Fluent/test.bin
  WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
Labels: size/XS

#10748 Fix very old transition off by one bug from Sake
  WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
Labels: size/S

#10737 Add Code scanning
  .github/workflows/codeql.yml
Labels: size/M

#10722 [VDG] Unfocus SearchBar on Escape key
  WalletWasabi.Fluent/Behaviors/DisposingTrigger.cs
  WalletWasabi.Fluent/Behaviors/KeyDownTrigger.cs
  WalletWasabi.Fluent/Views/SearchBar/SearchBar.axaml
  WalletWasabi.Fluent/Views/SearchBar/SearchBar.axaml.cs
Labels: size/M

#10763 [VDG] Dispose ReceiveAddressViewModel subscription properly
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressViewModel.cs
  WalletWasabi.Tests/UnitTests/ViewModels/ReceiveAddressViewModelTests.cs
Labels: size/S

#10768 [VDG] [trivial] uppercase letter musicbox
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
Labels: size/XS

#10742 Make Naive Set truly naive
  WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
Labels: size/S

#10734 Calculate the min feerate
  WalletWasabi.Tests/Helpers/MempoolInfoGenerator.cs
  WalletWasabi.Tests/UnitTests/AllFeeEstimateTests.cs
  WalletWasabi/Extensions/RPCClientExtensions.cs
Labels: size/L, affiliate

#10673 Set BestHeight to last filter tested instead of last filter matched
  WalletWasabi/Stores/IndexStore.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/S

#10626 crash report: add tooltip to open GH report hyperlink
  WalletWasabi.Fluent/CrashReport/ViewModels/CrashReportWindowViewModel.cs
  WalletWasabi.Fluent/CrashReport/Views/CrashReportWindow.axaml
  WalletWasabi.Fluent/ViewModels/HelpAndSupport/AboutViewModel.cs
Labels: size/XS

#10777 If there are changeless candidates, don't even consider ones with change
  WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
Labels: size/XS

#10758 [VDG] Do not use RequestAdd property in TagsBox to proxy adding new labels
  WalletWasabi.Fluent/Controls/TagsBox.axaml.cs
Labels: size/M

#10714 Fix whitespaces
  WalletWasabi.Daemon/Config.cs
  WalletWasabi.Daemon/Global.cs
  WalletWasabi.Fluent.Desktop/Program.cs
  WalletWasabi.Fluent/Behaviors/ExecuteCommandOnDoubleTappedBehavior.cs
  WalletWasabi.Fluent/Behaviors/FlyoutSuggestionBehavior.cs
  WalletWasabi.Fluent/Behaviors/TextBoxSelectAllTextBehavior.cs
  WalletWasabi.Fluent/Controls/Spectrum/AuraSpectrumDataSource.cs
  WalletWasabi.Fluent/Controls/Spectrum/SplashEffectDataSource.cs
  WalletWasabi.Fluent/Models/DataLegend.cs
  WalletWasabi.Fluent/Models/UI/IQrCodeReader.cs
  WalletWasabi.Fluent/Models/UI/QrCodeReader.cs
  WalletWasabi.Fluent/Models/UiTriggers.cs
  WalletWasabi.Fluent/Providers/ICanShutdownProvider.cs
  WalletWasabi.Fluent/Screenshot/Capture.cs
  WalletWasabi.Fluent/TreeDataGrid/PlainTextCell.cs
  WalletWasabi.Fluent/TreeDataGrid/PlainTextElementFactory.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/ShowQrCameraDialogViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/Columns/IndicatorsColumnView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/Columns/LabelsColumnView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyControlTileView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionSummary.axaml.cs
  WalletWasabi.Fluent/ZXing/BinaryBitmap.cs
  WalletWasabi.Fluent/ZXing/DecodedBitStreamParser.cs
  WalletWasabi.Fluent/ZXing/DecoderResult.cs
  WalletWasabi.Fluent/ZXing/Detector.cs
  WalletWasabi.Fluent/ZXing/FinderPatternFinder.cs
  WalletWasabi.Fluent/ZXing/QRCodeReader.cs
  WalletWasabi.Tests/UnitTests/Userfacing/CurrencyInputTests.cs
  WalletWasabi/Affiliation/AffiliationConstants.cs
  WalletWasabi/Affiliation/Models/Unit.cs
  WalletWasabi/Blockchain/Keys/BlockchainState.cs
  WalletWasabi/Blockchain/Keys/HdPubKey.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
  WalletWasabi/Blockchain/Transactions/ITransactionStore.cs
  WalletWasabi/Crypto/Randomness/InsecureRandom.cs
  WalletWasabi/Helpers/CoinHelpers.cs
  WalletWasabi/Helpers/TxOutEqualityComparer.cs
  WalletWasabi/JsonConverters/ReflectionUtils.cs
  WalletWasabi/Rpc/JsonRpcMethodAttribute.cs
  WalletWasabi/Rpc/JsonRpcMethodMetadata.cs
  WalletWasabi/Rpc/JsonRpcRequestHandler.cs
  WalletWasabi/Rpc/JsonRpcService.cs
  WalletWasabi/Tor/Socks5/Pool/TcpConnectionState.cs
  WalletWasabi/Tor/Socks5/Pool/TorStreamInfo.cs
  WalletWasabi/WabiSabi/Client/AliceClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinCoinSelector.cs
  WalletWasabi/WabiSabi/Client/CoinJoinTrackerFactory.cs
  WalletWasabi/WabiSabi/Client/IWasabiBackendStatusProvider.cs
  WalletWasabi/WabiSabi/Client/OutputProvider.cs
  WalletWasabi/WabiSabi/Client/ReverseComparer.cs
  WalletWasabi/WabiSabi/Crypto/Serialization/JsonWriterExtensions.cs
  WalletWasabi/Wallets/RpcBlockProvider.cs
Labels: size/XL

#10770 Extract naive decomposition out into its own method
  WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
Labels: size/L, affiliate

#10784 [Trivial] Remove sort System using directives rule
  .editorconfig
Labels: size/XS

#10786 [Trivial] Remove unused variable
  WalletWasabi/Blockchain/Transactions/TransactionHistoryBuilder.cs
Labels: size/S

#10760 how to deploy
  WalletWasabi.Documentation/HowToDeploy.md
Labels: size/S

#10787 Extract changeless decomposition out into its own method
  WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
Labels: size/M

#10799 [trivial] Use new new
  CONTRIBUTING.md
  WalletWasabi/Blockchain/Analysis/FeesEstimation/HybridFeeProvider.cs
  WalletWasabi/Blockchain/Analysis/FeesEstimation/ThirdPartyFeeProvider.cs
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
  WalletWasabi/Helpers/RuntimeParams.cs
  WalletWasabi/Services/HostedServices.cs
  WalletWasabi/Wallets/Kitchen.cs
  WalletWasabi/WebClients/Wasabi/WasabiClient.cs
Labels: size/S

#10779 [website] Firefox color fixes
  WalletWasabi.Backend/wwwroot/css/style.css
Labels: size/XS

#10800 [Trivial] Use new new keyword
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
  WalletWasabi/Services/HostedServices.cs
Labels: size/XS

#10795 Introduce the concept of change tolerance
  WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
Labels: size/M

#10788 Introducing Pre-Decompositions to Enhance Decomposition Algorithms
  WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
Labels: size/M

#10813 Increase max out from 8 to 10
  WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
Labels: size/XS
