Repository WalletWasabi/WalletWasabi, pull requests merged in 2023-01, with the labels that each got.

#9848 [Trivial] Update license
  LICENSE.md
Labels: size/XS

#9849 [Trivial] Fix formatting
  WalletWasabi.Fluent/Behaviors/ShowAttachedFlyoutWhenFocusedBehavior.cs
  WalletWasabi.Fluent/Controls/BindableGrid.cs
  WalletWasabi.Fluent/Controls/Dialog.axaml.cs
  WalletWasabi.Fluent/Controls/LineChart.cs
  WalletWasabi.Fluent/Controls/PrivacyTextPresenter.cs
  WalletWasabi.Fluent/Controls/ProgressRingArc.axaml.cs
  WalletWasabi.Fluent/Controls/TagsBox.axaml.cs
  WalletWasabi.Fluent/Extensions/DynamicDataExtensions.cs
  WalletWasabi.Fluent/Screenshot/Capture.cs
  WalletWasabi.Fluent/TreeDataGrid/TreeDataGridPlainTextCell.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/Core/CoinCoinControlItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/Core/PocketCoinControlItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/Sources/ActionsSearchSource.cs
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi.Tests/Helpers/ServiceFactory.cs
  WalletWasabi.Tests/UnitTests/KeyManagementTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/ConstructionStateTests.cs
  WalletWasabi/BitcoinCore/Rpc/CachedRpcClient.cs
  WalletWasabi/Blockchain/Keys/HdPubKeyCache.cs
  WalletWasabi/Blockchain/Keys/HdPubKeyGenerator.cs
  WalletWasabi/Blockchain/Keys/HdPubKeyGlobalView.cs
  WalletWasabi/Blockchain/Keys/WalletGenerator.cs
  WalletWasabi/Helpers/HardwareWalletOperationHelpers.cs
  WalletWasabi/Helpers/ImportWalletHelper.cs
  WalletWasabi/Tor/Control/Utils/Tokenizer.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Rounds/UtxoSelectionParameters.cs
  WalletWasabi/WabiSabi/Client/BaseKeyChain.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WabiSabi/Client/DependencyGraphTaskScheduler.cs
  WalletWasabi/WabiSabi/Client/InternalDestinationProvider.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/ConstructionState.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/MultipartyTransactionState.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/SigningState.cs
  WalletWasabi/Wallets/P2pBlockProvider.cs
Labels: size/L

#9872 Add softwareexpiry=0 to knots parameters
  WalletWasabi/BitcoinCore/CoreNode.cs
Labels: size/XS

#9851 `P2pBlockProvider`: Minor changes
  WalletWasabi/Helpers/RuntimeParams.cs
  WalletWasabi/Wallets/P2pBlockProvider.cs
Labels: size/L

#9870 [website] Added sitemap to robots.txt
  WalletWasabi.Backend/wwwroot/robots.txt
Labels: size/XS

#9774 [VDG] Coin Control Stage 2
  WalletWasabi.Fluent/ViewModels/CoinControl/Core/CoinCoinControlItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/Core/CoinControlItemViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/Core/PocketCoinControlItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/SelectCoinsDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Fluent/Views/CoinControl/Core/Cells/SelectionCellView.axaml
  WalletWasabi.Fluent/Views/CoinControl/Core/Cells/SelectionCellView.axaml.cs
  WalletWasabi.Fluent/Views/CoinControl/SelectCoinsDialogView.axaml
Labels: size/L

#9782 Select coins from reused address
  WalletWasabi/Blockchain/TransactionOutputs/ISmartCoin.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/S

#9876 [Trivial] Make struct 'readonly'
  WalletWasabi.Fluent/ViewModels/Dialogs/Base/DialogResult.cs
  WalletWasabi/Models/ErrorDescriptor.cs
  WalletWasabi/Models/Height.cs
  WalletWasabi/WabiSabi/Models/CoordinationFeeRate.cs
Labels: size/XS

#9833 More friendly HWI error message on timeout
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressViewModel.cs
  WalletWasabi/Extensions/ExceptionExtensions.cs
Labels: size/S

#9700 [VDG] Add wallet items to search bar
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletInfoViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletStatsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinSettingsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletSettingsViewModel.cs
Labels: size/L

#9883 fix namespace
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyBar/PrivacyBar.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyBar/PrivacyBar.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyControlTileView.axaml
Labels: size/XS

#9890 [trivial] minor musicbox message improvement
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
Labels: size/XS

#9508 [VDG] Simplify insufficient balance handling
  WalletWasabi.Fluent/Helpers/TransactionFeeHelper.cs
  WalletWasabi.Fluent/Models/BuildTransactionReason.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/LabelSelectionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionInfo.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
Labels: size/L

#9725 [VDG] Refactor navbar
  WalletWasabi.Fluent/Controls/NavBarItem.axaml
  WalletWasabi.Fluent/Controls/NavBarItem.axaml.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/AddedWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/ConnectHardwareWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/ClosedWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModelBase.cs
  WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
Labels: size/XL

#9905 [VDG] [Trivial] Remove unused control NavBarListBox
  WalletWasabi.Fluent/Controls/NavBarListBox.cs
Labels: size/M

#9710 Re-enable coinjoins with taproot outputs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/InternalDestinationProvider.cs
Labels: size/S

#9903 [VDG] [Trivial] Remove unused control BindableGrid
  WalletWasabi.Fluent/Controls/BindableGrid.cs
Labels: size/M

#9902 [VDG] [Trivial] Remove unused control NavBarTreeView
  WalletWasabi.Fluent/Controls/NavBarTreeView.cs
Labels: size/S

#9892 Signs even in when receives more money than excpected
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/CoinJoinClientTests.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/M

#9913 [VDG] Remove unused icon assets.
  WalletWasabi.Fluent/Controls/PrivacyContentControl.axaml
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionSummary.axaml
Labels: size/L

#9912 [VDG] Disable ToggleSwitch knobs transitions to fix delay of switch toggle as settings
  WalletWasabi.Fluent/Styles/ToggleSwitch.axaml
Labels: size/XS

#9910 `TorProcessManager`: Re-throw exception
  WalletWasabi/Tor/TorProcessManager.cs
Labels: size/S

#9874 Rename fallback to blame in music box
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
Labels: size/XS

#9726 [VDG] Fix memory leak and navigation issue during loading
  WalletWasabi.Fluent/ViewModels/Login/LoginViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/ClosedWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/LoadingViewModel.cs
Labels: size/M

#9918 [VDG] Add TryGetSelectedWalletViewModel to WalletManagerViewModel
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
Labels: size/S

#9922 [VDG] Remove unused DataTemplateSelector class
  WalletWasabi.Fluent/DataTemplateSelector.cs
Labels: size/S

#9820 [VDG] Add paste suggestion flyout
  WalletWasabi.Fluent/Behaviors/FlyoutSuggestionBehavior.cs
  WalletWasabi.Fluent/Behaviors/Suggestion.cs
  WalletWasabi.Fluent/Controls/DualCurrencyEntryBox.axaml.cs
  WalletWasabi.Fluent/Converters/BooleanConverter.cs
  WalletWasabi.Fluent/Extensions/FunctionalExtensions.cs
  WalletWasabi.Fluent/Helpers/ApplicationHelper.cs
  WalletWasabi.Fluent/Infrastructure/ClipboardObserver.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletBalances.cs
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Labels: size/L

#9932 [VDG] Move global static classes to root folder
  WalletWasabi.Fluent/Controls/PrivacyTextPresenter.cs
  WalletWasabi.Fluent/Helpers/TextHelpers.cs
  WalletWasabi.Fluent/UiConstants.cs
  WalletWasabi.Fluent/UiServices.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingViewModel.cs
Labels: size/S

#9930 [VDG] Cleanup behaviors naming and move types to models
  WalletWasabi.Fluent/Behaviors/ExecuteCommandOnActivatedBehavior.cs
  WalletWasabi.Fluent/Behaviors/ExecuteCommandOnDoubleTappedBehavior.cs
  WalletWasabi.Fluent/Behaviors/FlyoutSuggestionBehavior.cs
  WalletWasabi.Fluent/Behaviors/FocusNextWhenValidBehavior.cs
  WalletWasabi.Fluent/Behaviors/NavBarSelectedIndicatorParentBehavior.cs
  WalletWasabi.Fluent/Models/NavBarSelectedIndicatorState.cs
  WalletWasabi.Fluent/Models/Suggestion.cs
  WalletWasabi.Fluent/Views/Dialogs/AddressEntryDialogView.axaml
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/WalletCoinsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
  WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveAddressesView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Labels: size/M

#9923 [VDG] Remove redundant this qualifier
  WalletWasabi.Fluent/Behaviors/RandomizedWorldPointsBehavior.cs
  WalletWasabi.Fluent/TreeDataGrid/TreeDataGridPrivacyTextCell.cs
Labels: size/S

#9909 Remove segwit limitation for change outputs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
Labels: size/XS

#9934 [Trivial] Remove unnecessary curly brackets
  WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
  WalletWasabi.Fluent/Extensions/DynamicDataExtensions.cs
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
Labels: size/L

#9926 `IndexStore`: Simplify `ForeachFiltersAsync`
  WalletWasabi/Stores/IndexStore.cs
Labels: size/M

#9950 [VDG] [Trivial] Remove unused NavBarTreeItem control
  WalletWasabi.Fluent/App.axaml
  WalletWasabi.Fluent/Controls/NavBarTreeItem.axaml
  WalletWasabi.Fluent/Controls/NavBarTreeItem.axaml.cs
Labels: size/L

#9946 [VDG] Fix Wallet Coins view discrete mode
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/Columns/AmountColumnView.axaml
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/Columns/AmountColumnView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/Columns/LabelsColumnView.axaml
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/WalletCoinsView.axaml
Labels: size/L

#9949 [VDG] Refactor TreeDataGrid column creation into methods
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressesViewModel.cs
Labels: size/L

#8192 Update WW1 Legal docs
  WalletWasabi/Helpers/Constants.cs
  WalletWasabi/Legal/Assets/LegalDocumentsWw1.txt
Labels: size/M

#9935 [Trivial] Fix name violation
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarItemViewModel.cs
Labels: size/XS

#9938 [Trivial] Use expression body
  WalletWasabi.Fluent/Infrastructure/ClipboardObserver.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/Patterns/ValueObject.cs
Labels: size/S

#9941 Remove unused parameters
  WalletWasabi.Fluent/ViewModels/Wallets/Send/LabelSelectionViewModel.cs
Labels: size/XS

#9961 `ProcessAsync`: Cleanup
  WalletWasabi.Tests/UnitTests/Helpers/PowerSaving/BaseInhibitorTaskTests.cs
  WalletWasabi.Tests/UnitTests/Tor/TorProcessManagerTests.cs
  WalletWasabi/Microservices/ProcessAsync.cs
Labels: size/M

#9969 `CoreNode`: Remove a few more warnings
  WalletWasabi/BitcoinCore/CoreNode.cs
Labels: size/M

#9973 Fix randomization of output types
  WalletWasabi/WabiSabi/Client/InternalDestinationProvider.cs
Labels: size/XS

#9963 Refactor WhiteList
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/WhitelistTests.cs
  WalletWasabi/WabiSabi/Backend/Banning/CoinVerifier.cs
  WalletWasabi/WabiSabi/Backend/Banning/Whitelist.cs
Labels: size/L

#9967 Small preparation for payments in coinjoins
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/WabiSabi/Client/CoinJoinResult.cs
Labels: size/M

#9979 [VDG] Remove unused controls
  WalletWasabi.Fluent/Controls/NonVirtualizingResponsiveLayout.cs
  WalletWasabi.Fluent/Controls/ResponsivePanel.cs
  WalletWasabi.Fluent/Controls/ResponsivePanelState.cs
  WalletWasabi.Fluent/Controls/RingChartControl.cs
Labels: size/XL

#9937 [VDG] Copy balance from tile
  WalletWasabi.Fluent/App.axaml
  WalletWasabi.Fluent/Controls/ClipboardCopyButton.axaml.cs
  WalletWasabi.Fluent/Controls/CopyableItem.axaml
  WalletWasabi.Fluent/Controls/CopyableItem.axaml.cs
  WalletWasabi.Fluent/Converters/BooleanConverters.cs
  WalletWasabi.Fluent/Converters/MoneyConverters.cs
  WalletWasabi.Fluent/Extensions/CurrencyExtensions.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletBalanceTileViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyControlTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceTileView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Labels: size/L

#9933 [VDG] Fix CS0420 for _isLoading field in loading view model
  WalletWasabi.Fluent/ViewModels/Wallets/LoadingViewModel.cs
Labels: size/XS

#9741 [VDG] [Taproot UI support] #3 - Display Taproot ExtPubKey and DerivationPath in Wallet Info
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletInfoViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Advanced/WalletInfoView.axaml
Labels: size/M

#9928 Remove `GetBitcoinCoreVersionAsync`
  WalletWasabi.Tests/UnitTests/BitcoinCore/NodeBuildingTests.cs
  WalletWasabi/BitcoinCore/CoreNode.cs
  WalletWasabi/Blockchain/Transactions/AllTransactionStore.cs
  WalletWasabi/Logging/BenchmarkLogger.cs
  WalletWasabi/Stores/BitcoinStore.cs
  WalletWasabi/Stores/IndexStore.cs
  WalletWasabi/Wallets/FileSystemBlockRepository.cs
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/XL

#9986 [VDG] Realign NavBarItem element margins and heights.
  WalletWasabi.Fluent/Controls/NavBarItem.axaml
  WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
Labels: size/XS

#9974 Add round independent
  WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/CoinVerifierTests.cs
  WalletWasabi/CoinJoin/Coordinator/Coordinator.cs
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
  WalletWasabi/Extensions/EventHandlerExtensions.cs
  WalletWasabi/WabiSabi/Backend/Banning/CoinVerifier.cs
  WalletWasabi/WabiSabi/Backend/Banning/CoinVerifierApiClient.cs
  WalletWasabi/WabiSabi/Backend/Banning/CoinVerifyItem.cs
  WalletWasabi/WabiSabi/Backend/Banning/CoinVerifyResult.cs
  WalletWasabi/WabiSabi/Backend/DoSPrevention/Prison.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
Labels: size/XL

#9990 Fix Whitelist LastSavedChangeId property
  WalletWasabi/WabiSabi/Backend/Banning/Whitelist.cs
Labels: size/XS

#8074 `ConfigBase` with file read & write synchronization
  WalletWasabi/Bases/ConfigBase.cs
  WalletWasabi/Interfaces/IConfig.cs
Labels: size/L

#9975 [VDG] Coin Control Stage 3
  WalletWasabi.Fluent/Converters/IndentConverter.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/Core/CoinCoinControlItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/Core/CoinControlItemViewModelBase.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/Core/PocketCoinControlItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/Core/ScriptType.cs
  WalletWasabi.Fluent/ViewModels/CoinControl/SelectCoinsDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Fluent/Views/CoinControl/Core/Cells/IndicatorsCellView.axaml
  WalletWasabi.Fluent/Views/CoinControl/Core/Cells/SelectionCellView.axaml
  WalletWasabi.Fluent/Views/CoinControl/SelectCoinsDialogView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml
Labels: feature/enhancement, size/XL

#9877 Use IDictionary.TryGetValue(TKey, out TValue) method
  WalletWasabi.Fluent/Controls/LineChart.cs
  WalletWasabi.Fluent/Models/Windows/DirectShow.cs
  WalletWasabi.Fluent/State/StateMachine.cs
  WalletWasabi.Fluent/Validation/Validations.cs
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationManager.cs
  WalletWasabi/Blockchain/Analysis/CoinjoinAnalyzer.cs
  WalletWasabi/WabiSabi/Backend/Statistics/RequestTimeStatista.cs
Labels: size/M

#9989 [VDG] Authorize wallet info when navigated from search bar
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
Labels: size/S

#9881 [Trivial] Use local function
  WalletWasabi.Fluent/Models/Windows/WindowsCapture.cs
  WalletWasabi.Fluent/Validation/Validations.cs
Labels: size/S

#9853 [VDG] [Trivial] Enable clipboard copy item in Transaction Preview
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionSummaryViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionSummary.axaml
Labels: size/S

#9943 [VDG] Use BindPointerOverBehavior in MusicControlsView
  WalletWasabi.Fluent/Views/Wallets/MusicControlsView.axaml
Labels: size/XS

#10007 Remove unecessary Task.Run
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressViewModel.cs
Labels: size/M

#10000 [VDG] replace `Select(_ => Unit.Default)` with `ToSignal()`
  WalletWasabi.Fluent/Behaviors/CheckMarkVisibilityBehavior.cs
  WalletWasabi.Fluent/Behaviors/FocusNextWhenValidBehavior.cs
  WalletWasabi.Fluent/Behaviors/PasteButtonFlashBehavior.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/LabelEntryDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/Settings/Setting.cs
  WalletWasabi.Fluent/ViewModels/StatusIcon/StatusIconViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Labels/SuggestionLabelsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveViewModel.cs
Labels: size/M

#10008 Start CJ with only pending coins
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Labels: size/XS

#9981 [VDG] PrivacyBar refactor into Custom Control
  WalletWasabi.Fluent/App.axaml
  WalletWasabi.Fluent/Controls/PrivacyBar.axaml
  WalletWasabi.Fluent/Controls/PrivacyBar.axaml.cs
  WalletWasabi.Fluent/Controls/PrivacyBarSegment.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyBarItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyBarViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyBar/PrivacyBar.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyBar/PrivacyBarView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyBar/PrivacyBarView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyControlTileView.axaml
Labels: size/L

#10018 Check address used
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/CoinVerifierTests.cs
  WalletWasabi/WabiSabi/Backend/Banning/CoinVerifier.cs
Labels: size/S

#10020 Improve logging
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/CoinVerifierTests.cs
  WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
  WalletWasabi/WabiSabi/Backend/Banning/AuditEventType.cs
  WalletWasabi/WabiSabi/Backend/Banning/CoinVerifier.cs
  WalletWasabi/WabiSabi/Backend/Banning/CoinVerifierLogger.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/L

#10019 CoinHelpers and starting CJ with empty coins consistency
  WalletWasabi/Helpers/CoinHelpers.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/M
