Repository WalletWasabi/WalletWasabi, pull requests merged in 2024-04, with the labels that each got.

#12687 Trezor Safe 3 implementation
  WalletWasabi.Documentation/WasabiCompatibility.md
  WalletWasabi.Tests/AcceptanceTests/HwiKatas.cs
  WalletWasabi.Tests/UnitTests/Hwi/HwiProcessBridgeMock.cs
  WalletWasabi.Tests/UnitTests/Hwi/MockedDeviceTests.cs
  WalletWasabi.Tests/UnitTests/WalletDirTests.cs
  WalletWasabi/Hwi/Models/HardwareWalletModels.cs
  WalletWasabi/Hwi/Models/HwiEnumerateEntry.cs
Labels: size/L

#12700 Fix html tag
  README.md
Labels: size/XS

#12756 Fix infinite loop when getting blocks from unavailable P2P
  WalletWasabi/Wallets/WalletFilterProcessor.cs
Labels: size/M

#12753 [UI] Migrate TagsBox to ControlTheme
  WalletWasabi.Fluent/App.axaml
  WalletWasabi.Fluent/Controls/TagsBox.axaml
  WalletWasabi.Fluent/Controls/TagsBoxAutoCompleteBox.axaml
  WalletWasabi.Fluent/Styles/TagsBox.axaml
  WalletWasabi.Fluent/Styles/Themes/Fluent.axaml
  WalletWasabi.Tests/UnitTests/Fluent/App.axaml
Labels: size/L

#12750 [UI] Migrate PreviewMessageItem to ControlTheme
  WalletWasabi.Fluent/Controls/PreviewMessageItem.axaml
  WalletWasabi.Fluent/Controls/PreviewMessageItem.axaml.cs
  WalletWasabi.Fluent/Styles/Styles.axaml
  WalletWasabi.Fluent/Styles/Themes/Fluent.axaml
Labels: size/M

#12717 Add commit, merge related conventions
  CONTRIBUTING.md
Labels: size/M

#12696 Change mempool policy on local node
  Contrib/Containers/docker-compose.yml
  WalletWasabi.Daemon/Global.cs
  WalletWasabi/BitcoinCore/Configuration/CoreConfig.cs
  WalletWasabi/BitcoinCore/CoreNode.cs
  WalletWasabi/BitcoinCore/CoreNodeParams.cs
Labels: size/S

#12754 Disable StopWhenAllMixed feature
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/CoinJoinCoinSelectionTests.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Client/CoinJoinCoinSelector.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Manager/CoinJoinManager.cs
Labels: size/M

#12773 Fix NRE SingleInstanceChecker
  WalletWasabi.Fluent.Desktop/Program.cs
Labels: size/XS

#12721 [UI] BAB Workflow Lifecycle refactor
  WalletWasabi.Fluent/Models/Wallets/BuyAnythingModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/BuyViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/OrderViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/ShopinBitWorkflow.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/Workflow.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Tests/UnitTests/ViewModels/ReceiveAddressViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/SuggestionLabelsViewModelTests.cs
Labels: size/L

#12782 Change MaxDaysToTrustLocalPrison to 15 days and remove randomness
  WalletWasabi/WabiSabi/Client/Banning/CoinPrison.cs
Labels: size/S

#12787 [UI] Set CoinJoinSettingsCommand
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
Labels: size/S

#12783 [UI] Fix settings observability
  WalletWasabi.Fluent/ViewModels/SearchBar/SearchItems/ContentSearchItemNode.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/SearchItems/SearchItemNode.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/Settings/PropertyHelper.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/Settings/Setting.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/SettingsSearchSource.cs
Labels: size/M

#12772 OSX: Start Wasabi in the background during startup
  WalletWasabi.Fluent/Helpers/MacOsStartupHelper.cs
  WalletWasabi.Fluent/Helpers/StartupHelper.cs
  WalletWasabi.Fluent/UiConfig.cs
  WalletWasabi.Packager/Program.cs
  WalletWasabi.Tests/UnitTests/StartWasabiOnSystemStartupTests.cs
  WalletWasabi/Helpers/Constants.cs
Labels: size/M

#12789 [UI] UI-Refresh + Explicit Disposal
  WalletWasabi.Fluent/ApplicationStateManager.cs
  WalletWasabi.Fluent/Behaviors/CheckMarkVisibilityBehavior.cs
  WalletWasabi.Fluent/Controls/TextBox.axaml
  WalletWasabi.Fluent/Infrastructure/AppLifetimeAttribute.cs
  WalletWasabi.Fluent/Models/UI/ApplicationSettings.cs
  WalletWasabi.Fluent/Models/Wallets/AddressesModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletCoinjoinModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletSettingsModel.cs
  WalletWasabi.Fluent/TreeDataGrid/TreeDataGridPrivacyTextCell.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/ConfirmRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/ApplicationViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/Base/DialogScreenViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/SearchPasswordViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationState.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/SearchBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/SearchItemGroup.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/SearchItems/SearchItemNode.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/Sources/EditableSearchSourceSource.cs
  WalletWasabi.Fluent/ViewModels/Settings/AdvancedSettingsTabViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/BitcoinTabSettingsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/GeneralSettingsTabViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/PrivacyModeViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/SettingsPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/StatusIcon/StatusIconViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/BuyViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/OrderViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/1_Initial/WelcomeStep.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/Workflow.cs
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Coins/CoinListViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Labels/SuggestionLabelsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Notifications/WalletNotificationsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/AddressViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressesViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Settings/WalletSettingsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Tests/UnitTests/ViewModels/ReceiveAddressViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/SuggestionLabelsViewModelTests.cs
Labels: size/L

#12625 [UI] Explicit disposal of subscriptions
  WalletWasabi.Fluent/ApplicationStateManager.cs
  WalletWasabi.Fluent/Behaviors/CheckMarkVisibilityBehavior.cs
  WalletWasabi.Fluent/Controls/TextBox.axaml
  WalletWasabi.Fluent/Infrastructure/AppLifetimeAttribute.cs
  WalletWasabi.Fluent/Models/UI/ApplicationSettings.cs
  WalletWasabi.Fluent/Models/Wallets/AddressesModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletCoinjoinModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletSettingsModel.cs
  WalletWasabi.Fluent/TreeDataGrid/TreeDataGridPrivacyTextCell.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/ConfirmRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/ApplicationViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/Base/DialogScreenViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/SearchPasswordViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/Navigation/NavigationState.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/SearchBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/SearchItemGroup.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/SearchItems/SearchItemNode.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/Sources/EditableSearchSourceSource.cs
  WalletWasabi.Fluent/ViewModels/Settings/AdvancedSettingsTabViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/BitcoinTabSettingsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/GeneralSettingsTabViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/PrivacyModeViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/SettingsPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/StatusIcon/StatusIconViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/BuyViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/OrderViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/1_Initial/WelcomeStep.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/Workflow.cs
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Coins/CoinListViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Labels/SuggestionLabelsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Notifications/WalletNotificationsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/AddressViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressesViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Settings/WalletSettingsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Tests/UnitTests/ViewModels/ReceiveAddressViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/SuggestionLabelsViewModelTests.cs
Labels: size/L

#12713 [Trivial] Use ValidatePathString for other HW models
  WalletWasabi.Tests/AcceptanceTests/HwiKatas.cs
Labels: size/XS

#12792 Revert "[Trivial] Use ValidatePathString for other HW models"
  WalletWasabi.Tests/AcceptanceTests/HwiKatas.cs
Labels: size/XS

#12793 Fix CI due to broken tests
  WalletWasabi.Tests/UnitTests/ViewModels/SuggestionLabelsViewModelTests.cs
Labels: size/S

#12794 [UI] Send: Move Focus On Enter Key
  WalletWasabi.Fluent/Controls/DualCurrencyEntryBox.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Labels: size/S

#12795 [UI] Login: Fix focus after Incorrect Password message
  WalletWasabi.Fluent/Views/Login/LoginView.axaml
Labels: size/S

#12800 [UI] Send: Activate SuggestionLabelsViewModel
  WalletWasabi.Fluent/ViewModels/Dialogs/LabelEntryDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/AddressLabelEditViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
Labels: size/S

#12778 `TryRemoveLastFilterIfNewerThanAsync` should not throw
  WalletWasabi.Tests/UnitTests/Stores/IndexStoreTests.cs
  WalletWasabi/Stores/IndexStore.cs
Labels: size/S

#12804 Revert 12782
  WalletWasabi/WabiSabi/Client/Banning/CoinPrison.cs
Labels: size/S

#12802 Icons - Replaces icons for Mac and windows
  WalletWasabi.Fluent.Desktop/Assets/WasabiLogo.ico
  WalletWasabi.Fluent.Desktop/Assets/WasabiLogo16.png
  WalletWasabi.Fluent.Desktop/Assets/WasabiLogo24.png
  WalletWasabi.Fluent.Desktop/Assets/WasabiLogo256.png
  WalletWasabi.Fluent.Desktop/Assets/WasabiLogo32.png
  WalletWasabi.Fluent.Desktop/Assets/WasabiLogo48.png
  WalletWasabi.Packager/Content/Osx/App/Contents/Resources/WasabiLogo.icns
  WalletWasabi.Packager/Content/Osx/WasabiLogo.icns
Labels: size/XS

#12805 [UI] Always call ApplyUiConfigWindowState() before showing the window
  WalletWasabi.Fluent/ApplicationStateManager.cs
Labels: size/XS

#12811 [UI] Label - adjust margins to prevent shifting
  WalletWasabi.Fluent/Controls/TagControl.axaml
Labels: size/XS

#12816 [UI] Remove unused xmlns usages
  WalletWasabi.Fluent/Controls/TreeDataGrid.axaml
  WalletWasabi.Fluent/Controls/WalletIconControl.axaml
  WalletWasabi.Fluent/Views/Login/LoginView.axaml
  WalletWasabi.Fluent/Views/SearchBar/SearchBar.axaml
Labels: size/XS

#12810 Fix icons
  WalletWasabi.Documentation/Guides/MacOsSigning.md
  WalletWasabi.Fluent.Desktop/Assets/WasabiLogo16.png
  WalletWasabi.Fluent.Desktop/Assets/WasabiLogo24.png
  WalletWasabi.Fluent.Desktop/Assets/WasabiLogo32.png
  WalletWasabi.Fluent.Desktop/Assets/WasabiLogo48.png
  WalletWasabi.Packager/Content/Osx/App/Contents/Resources/WasabiLogo.icns
  WalletWasabi.Packager/Content/Osx/Dmg/.DS_Store.dat
  WalletWasabi.Packager/Content/Osx/Dmg/.background/Logo_with_text_small.png
  WalletWasabi.Packager/Content/Osx/WasabiLogo.icns
Labels: size/XS

#12819 [UI] [macOS] Do not call Hide when the MainWindow from lifetime is not present
  WalletWasabi.Fluent/ApplicationStateManager.cs
Labels: size/XS

#12821 [Release] Fix hide on Mac
  WalletWasabi.Fluent/ApplicationStateManager.cs
Labels: size/XS

#12820 [Release] fix icons
  WalletWasabi.Documentation/Guides/MacOsSigning.md
  WalletWasabi.Fluent.Desktop/Assets/WasabiLogo16.png
  WalletWasabi.Fluent.Desktop/Assets/WasabiLogo24.png
  WalletWasabi.Fluent.Desktop/Assets/WasabiLogo32.png
  WalletWasabi.Fluent.Desktop/Assets/WasabiLogo48.png
  WalletWasabi.Packager/Content/Osx/App/Contents/Resources/WasabiLogo.icns
  WalletWasabi.Packager/Content/Osx/Dmg/.DS_Store.dat
  WalletWasabi.Packager/Content/Osx/Dmg/.background/Logo_with_text_small.png
  WalletWasabi.Packager/Content/Osx/WasabiLogo.icns
Labels: size/XS

#12824 Add more statistics to backend
  WalletWasabi.Backend/Controllers/BlockchainController.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Statistics/RequestTimeStatista.cs
Labels: size/L

#12797 Introduce support for banning API
  .editorconfig
  BannedSymbols.txt
  Directory.Build.props
  Directory.Packages.props
  WalletWasabi.Daemon/packages.lock.json
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent.Generators/packages.lock.json
  WalletWasabi.Fluent/packages.lock.json
  WalletWasabi.Packager/packages.lock.json
  WalletWasabi.Tests/.editorconfig
  WalletWasabi/WebClients/Bitstamp/BitstampExchangeRateProvider.cs
  WalletWasabi/WebClients/BlockchainInfo/BlockchainInfoExchangeRateProvider.cs
  WalletWasabi/WebClients/CoinGecko/CoinGeckoExchangeRateProvider.cs
  WalletWasabi/WebClients/Coinbase/CoinbaseExchangeRateProvider.cs
  WalletWasabi/WebClients/Coingate/CoingateExchangeRateProvider.cs
  WalletWasabi/WebClients/Gemini/GeminiExchangeRateProvider.cs
  WalletWasabi/packages.lock.json
Labels: size/M

#12823 [Trivial] Small BAB cleanup
  WalletWasabi/BuyAnything/BuyAnythingManager.cs
  WalletWasabi/BuyAnything/ConversationTracking.cs
  WalletWasabi/WebClients/BuyAnything/BuyAnythingClient.cs
Labels: size/S

#12844 [Release] fix child date format
  WalletWasabi.Fluent/Models/Wallets/TransactionTreeBuilder.cs
Labels: size/S

#12847 Update dependencies for deterministic build
  WalletWasabi.sln
  deps.nix
Labels: size/XS

#12845 [Release] Fix SpeedUpGroup children transactions details
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/SpeedUpHistoryItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
Labels: size/XS

#12853 Use helper privacy functions in `GetPockets`
  WalletWasabi.Fluent/Helpers/CoinPocketHelper.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
Labels: size/S

#12857 [Release] Use helper privacy functions in `GetPockets`
  WalletWasabi.Fluent/Helpers/CoinPocketHelper.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
Labels: size/S

#12858 Bump version to v2.0.7.
  WalletWasabi/Helpers/Constants.cs
Labels: size/XS

#12850 Add response times
  WalletWasabi/BitcoinCore/Rpc/RpcClientBase.cs
Labels: size/L

#12859 Bump version to 2.0.7 on master as well
  WalletWasabi/Helpers/Constants.cs
Labels: size/XS

#12803 Mitigate bans because of coordinator lag
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepConnectionConfirmationTests.cs
  WalletWasabi/WabiSabi/Backend/DoSPrevention/Offender.cs
  WalletWasabi/WabiSabi/Backend/DoSPrevention/Prison.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/M

#12860 Update readme image
  README.md
  ui-ww.png
Labels: size/XS

#12864 Fix CI failing with ubuntu version increase
  azure-pipelines-linux.yml
Labels: size/XS

#12863 Fix duplicate image in README.md
  README.md
Labels: size/XS

#12318 Get unconfirmed tx chain - client business logic only
  WalletWasabi.Daemon/Global.cs
  WalletWasabi.Fluent/Extensions/TransactionSummaryExtensions.cs
  WalletWasabi.Fluent/Helpers/TransactionFeeHelper.cs
  WalletWasabi.Fluent/Models/Wallets/TransactionTreeBuilder.cs
  WalletWasabi.Fluent/Models/Wallets/WalletTransactionsModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/CoinJoinDetailsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/TransactionDetailsViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/Details/CoinJoinDetailsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Home/History/Details/TransactionDetailsView.axaml
  WalletWasabi.Tests/IntegrationTests/P2pTests.cs
  WalletWasabi.Tests/RegressionTests/BackendTests.cs
  WalletWasabi.Tests/RegressionTests/BuildTransactionReorgsTest.cs
  WalletWasabi.Tests/RegressionTests/BuildTransactionValidationsTest.cs
  WalletWasabi.Tests/RegressionTests/CancelTests.cs
  WalletWasabi.Tests/RegressionTests/MaxFeeTests.cs
  WalletWasabi.Tests/RegressionTests/ReceiveSpeedupTests.cs
  WalletWasabi.Tests/RegressionTests/ReplaceByFeeTxTest.cs
  WalletWasabi.Tests/RegressionTests/SelfSpendSpeedupTests.cs
  WalletWasabi.Tests/RegressionTests/SendSpeedupTests.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi.Tests/RegressionTests/SpendUnconfirmedTxTests.cs
  WalletWasabi.Tests/RegressionTests/WalletTests.cs
  WalletWasabi.Tests/UnitTests/UnconfirmedChainFeeRateTests.cs
  WalletWasabi.Tests/UnitTests/Wallet/WalletBuilder.cs
  WalletWasabi/Blockchain/Transactions/TransactionSummary.cs
  WalletWasabi/Helpers/FeeHelpers.cs
  WalletWasabi/Wallets/UnconfirmedTransactionChainProvider.cs
  WalletWasabi/Wallets/Wallet.cs
  WalletWasabi/Wallets/WalletFactory.cs
Labels: size/L

#12867 Do not abort round in input registration
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/CoordinatorTests.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
Labels: size/XS

#12869 Create Library and LaunchAgents folder if they don't exist
  WalletWasabi.Fluent/Helpers/MacOsStartupHelper.cs
  WalletWasabi.Fluent/Helpers/StartupHelper.cs
Labels: size/M

#12755 [Trivial] Fix CodeFactor
  WalletWasabi.Backend/Controllers/BlockchainController.cs
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi/Services/UpdateManager.cs
  WalletWasabi/Tor/Http/Models/HeaderSection.cs
Labels: size/S

#12874 [Release] Create Library and LaunchAgents folder if they don't exist
  WalletWasabi.Fluent/Helpers/MacOsStartupHelper.cs
  WalletWasabi.Fluent/Helpers/StartupHelper.cs
Labels: size/M

#12875 Bump v2.0.7.1
  WalletWasabi/Helpers/Constants.cs
Labels: size/XS

#12877 Bump version to v2.0.7.1
  WalletWasabi/Helpers/Constants.cs
Labels: size/XS

#12873 [trivial] `MicroserviceHelpers`: extract `GetFilenameWithExtension`
  WalletWasabi/Microservices/MicroserviceHelpers.cs
  WalletWasabi/Tor/TorProcessManager.cs
Labels: size/XS

#12880 Fix some comments
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
  WalletWasabi.Fluent/Extensions/FriendlyExceptionMessageExtensions.cs
  WalletWasabi.Fluent/Helpers/FileHelpers.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi/Helpers/IoHelpers.cs
Labels: size/S

#12884 Add `stddev` to statista
  WalletWasabi/Crypto/Extensions.cs
  WalletWasabi/Extensions/LinqExtensions.cs
  WalletWasabi/WabiSabi/Backend/Statistics/RequestTimeStatista.cs
Labels: size/M

#12886 Update tooling versions
  flake.lock
  flake.nix
Labels: size/S

#12887 Add `dotnet counters` to the available tool box
  flake.nix
Labels: size/XS

#12879 Removed rule1 from initialization screen
  WalletWasabi.Fluent/Views/AddWallet/WelcomePageView.axaml
Labels: size/XS

#12400 Satoshi notifications
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Backend/Middlewares/Extensions.cs
  WalletWasabi.Backend/Middlewares/SatoshiWebSocketHandler.cs
  WalletWasabi.Backend/Middlewares/WebSocketConnectionState.cs
  WalletWasabi.Backend/Middlewares/WebSocketHandlerBase.cs
  WalletWasabi.Backend/Middlewares/WebSocketHandlerMiddleware.cs
  WalletWasabi.Backend/Middlewares/WebSocketsConnectionTracker.cs
  WalletWasabi.Backend/Properties/launchSettings.json
  WalletWasabi.Backend/Startup.cs
  WalletWasabi.Daemon/Config.cs
  WalletWasabi.Daemon/Global.cs
  WalletWasabi.Fluent/Helpers/TransactionFeeHelper.cs
  WalletWasabi.Tests/IntegrationTests/P2pTests.cs
  WalletWasabi.Tests/RegressionTests/BackendTests.cs
  WalletWasabi.Tests/RegressionTests/BuildTransactionReorgsTest.cs
  WalletWasabi.Tests/RegressionTests/BuildTransactionValidationsTest.cs
  WalletWasabi.Tests/RegressionTests/CancelTests.cs
  WalletWasabi.Tests/RegressionTests/FilterDownloaderTest.cs
  WalletWasabi.Tests/RegressionTests/MaxFeeTests.cs
  WalletWasabi.Tests/RegressionTests/ReceiveSpeedupTests.cs
  WalletWasabi.Tests/RegressionTests/ReorgTest.cs
  WalletWasabi.Tests/RegressionTests/ReplaceByFeeTxTest.cs
  WalletWasabi.Tests/RegressionTests/SelfSpendSpeedupTests.cs
  WalletWasabi.Tests/RegressionTests/SendSpeedupTests.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi.Tests/RegressionTests/SpendUnconfirmedTxTests.cs
  WalletWasabi.Tests/RegressionTests/WalletTests.cs
  WalletWasabi.Tests/UnitTests/BitcoinCore/IndexBuilderServiceTests.cs
  WalletWasabi.Tests/UnitTests/Wallet/WalletBuilder.cs
  WalletWasabi/BitcoinCore/Monitoring/RpcFeeProvider.cs
  WalletWasabi/Blockchain/Analysis/FeesEstimation/HybridFeeProvider.cs
  WalletWasabi/Blockchain/Analysis/FeesEstimation/IThirdPartyFeeProvider.cs
  WalletWasabi/Blockchain/Analysis/FeesEstimation/ThirdPartyFeeProvider.cs
  WalletWasabi/Blockchain/BlockFilters/FilterProcessor.cs
  WalletWasabi/Blockchain/BlockFilters/IndexBuilderService.cs
  WalletWasabi/Blockchain/Mempool/MempoolService.cs
  WalletWasabi/CoinJoin/Client/CoinJoinProcessor.cs
  WalletWasabi/Extensions/StreamReaderWriterExtensions.cs
  WalletWasabi/Services/EventBus.cs
  WalletWasabi/Services/Events/Events.cs
  WalletWasabi/Services/ExchangeRateFetcher.cs
  WalletWasabi/Services/MiningFeeRateFetcher.cs
  WalletWasabi/Services/SatoshiSynchronizer.cs
  WalletWasabi/Services/UpdateChecker.cs
  WalletWasabi/Services/WasabiSynchronizer.cs
  WalletWasabi/Stores/IndexStore.cs
  WalletWasabi/Synchronization/BlockHeightMessage.cs
  WalletWasabi/Synchronization/ExchangeRateMessage.cs
  WalletWasabi/Synchronization/FilterMessage.cs
  WalletWasabi/Synchronization/FilterModelExtensions.cs
  WalletWasabi/Synchronization/HandshakeMessage.cs
  WalletWasabi/Synchronization/MiningFeeRatesMessage.cs
  WalletWasabi/Wallets/Wallet.cs
  WalletWasabi/WebClients/BlockstreamInfo/BlockstreamInfoFeeProvider.cs
Labels: size/XXL

#12890 Remove unused `Constants.OutputSizeInBytes` constant
  WalletWasabi/Helpers/Constants.cs
Labels: size/XS

#12905 [UI] MenuItem - make icons less emphazied
  WalletWasabi.Fluent/Styles/MenuItem.axaml
Labels: size/XS

#12918 Statista performance update
  WalletWasabi/WabiSabi/Backend/Statistics/RequestTimeStatista.cs
Labels: size/L

#12902 Install udevrules with Ubuntu distribution
  WalletWasabi.Packager/Program.cs
Labels: size/XS

#12894 Removing the remaining InsecureRandom usages
  WalletWasabi/BitcoinP2p/P2pNetwork.cs
  WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs
  WalletWasabi/Blockchain/TransactionBuilding/TransactionModifierWalletExtensions.cs
  WalletWasabi/BuyAnything/BuyAnythingManager.cs
  WalletWasabi/Tor/Socks5/Pool/Circuits/DefaultCircuit.cs
  WalletWasabi/Tor/Socks5/Pool/Circuits/OneOffCircuit.cs
  WalletWasabi/Tor/Socks5/Pool/Circuits/PersonCircuit.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Client/UtxoSelectionParameters.cs
  WalletWasabi/Wallets/P2PNodesManager.cs
Labels: size/S

#12915 Update WasabiCompatibility.md because of HWI
  WalletWasabi.Documentation/ClientRelease/ReleaseNotesTemplate.md
  WalletWasabi.Documentation/WasabiCompatibility.md
Labels: size/XS

#12925 Fix reorg error log
  WalletWasabi/Services/SatoshiSynchronizer.cs
Labels: size/S

#12841 Add SubActionButton
  WalletWasabi.Fluent/Controls/Button.axaml
  WalletWasabi.Fluent/Controls/IUICommand.cs
  WalletWasabi.Fluent/Controls/SplitButton.axaml
  WalletWasabi.Fluent/Controls/SubActionButton.axaml
  WalletWasabi.Fluent/Controls/SubActionButton.axaml.cs
  WalletWasabi.Fluent/Controls/UICommandCollection.cs
  WalletWasabi.Fluent/Controls/UICommandDesign.cs
  WalletWasabi.Fluent/Styles/Button.axaml
  WalletWasabi.Fluent/Styles/PathIcon.axaml
  WalletWasabi.Fluent/Styles/Themes/Fluent.axaml
Labels: size/L

#12913 [UI] Increase height of tiles
  WalletWasabi.Fluent/Views/Wallets/Home/WalletTiles.axaml
Labels: size/XS

#12920 Median of an empty set
  WalletWasabi.Tests/UnitTests/LinqExtensionsTests.cs
  WalletWasabi/Extensions/LinqExtensions.cs
Labels: size/S

#12692 Notify `SoftwareVersion` and `LegalDocumentVersion`
  WalletWasabi.Backend/Middlewares/SatoshiWebSocketHandler.cs
  WalletWasabi.Daemon/Global.cs
  WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
  WalletWasabi.Tests/RegressionTests/BackendTests.cs
  WalletWasabi.Tests/UnitTests/UpdateStatusTests.cs
  WalletWasabi/Extensions/StreamReaderWriterExtensions.cs
  WalletWasabi/Models/UpdateStatus.cs
  WalletWasabi/Services/Events/Events.cs
  WalletWasabi/Services/LegalChecker.cs
  WalletWasabi/Services/SatoshiSynchronizer.cs
  WalletWasabi/Services/UpdateChecker.cs
  WalletWasabi/Services/UpdateManager.cs
  WalletWasabi/Services/WasabiSynchronizer.cs
  WalletWasabi/Synchronization/FilterMessage.cs
  WalletWasabi/Synchronization/LegalDocumentVersionMessage.cs
  WalletWasabi/Synchronization/VersionMessage.cs
  WalletWasabi/WebClients/Wasabi/WasabiClient.cs
Labels: size/L

#12714 [Trivial] Disable IDE0028 & IDE0290 & IDE0300 & IDE0305 code style rules in `.editorconfig`
  .editorconfig
Labels: size/S

#12937 `SatoshiWebSocketHandler` is a required service
  WalletWasabi.Backend/Startup.cs
Labels: size/XS

#12919 Add command line option `--LogModes`
  WalletWasabi.Daemon/Config.cs
  WalletWasabi.Daemon/Global.cs
  WalletWasabi.Daemon/WasabiAppBuilder.cs
  WalletWasabi/Logging/Logger.cs
  WalletWasabi/Tor/TorSettings.cs
Labels: size/M

#12939 Remove filters from BlockFilterIterator after a reorg
  WalletWasabi/Wallets/FilterProcessor/BlockFilterIterator.cs
  WalletWasabi/Wallets/WalletFilterProcessor.cs
Labels: size/M

#12956 [UI] CrashReporter - remove logo from bg
  WalletWasabi.Fluent/CrashReport/Views/CrashReportWindow.axaml
Labels: size/XS

#12957 Update Client release docs
  WalletWasabi.Documentation/ClientRelease/ClientDeployment.md
Labels: size/XS
