Repository WalletWasabi/WalletWasabi, pull requests merged in 2024-03, with the labels that each got.

#12585 Add sanity check for round destroyer threshold
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/XS

#12588 BlockDownloadServiceTests: Use async code instead of sync one
  WalletWasabi.Tests/UnitTests/Wallet/FilterProcessor/BlockDownloadServiceTests.cs
Labels: size/XS

#12582 Fix for Restart not working
  WalletWasabi.Fluent/CrashReport/CrashReporter.cs
  WalletWasabi/Microservices/ProcessStartInfoFactory.cs
Labels: size/S

#12589 Add `WalletFactory` type
  WalletWasabi.Daemon/Global.cs
  WalletWasabi.Tests/IntegrationTests/P2pTests.cs
  WalletWasabi.Tests/RegressionTests/BuildTransactionReorgsTest.cs
  WalletWasabi.Tests/RegressionTests/BuildTransactionValidationsTest.cs
  WalletWasabi.Tests/RegressionTests/CancelTests.cs
  WalletWasabi.Tests/RegressionTests/MaxFeeTests.cs
  WalletWasabi.Tests/RegressionTests/ReceiveSpeedupTests.cs
  WalletWasabi.Tests/RegressionTests/ReplaceByFeeTxTest.cs
  WalletWasabi.Tests/RegressionTests/SelfSpendSpeedupTests.cs
  WalletWasabi.Tests/RegressionTests/SendSpeedupTests.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi.Tests/RegressionTests/SpendUnconfirmedTxTests.cs
  WalletWasabi.Tests/RegressionTests/WalletTests.cs
  WalletWasabi.Tests/UnitTests/Wallet/WalletBuilder.cs
  WalletWasabi/Wallets/Wallet.cs
  WalletWasabi/Wallets/WalletFactory.cs
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/L

#12571 Simplify estimation code
  WalletWasabi.Fluent/Helpers/TransactionFeeHelper.cs
  WalletWasabi.Tests/UnitTests/AllFeeEstimateTests.cs
  WalletWasabi.Tests/UnitTests/BitcoinCore/RpcBasedTests.cs
  WalletWasabi/BitcoinCore/Monitoring/RpcFeeProvider.cs
  WalletWasabi/Blockchain/Analysis/FeesEstimation/AllFeeEstimate.cs
  WalletWasabi/Blockchain/Analysis/FeesEstimation/HybridFeeProvider.cs
  WalletWasabi/Blockchain/Analysis/FeesEstimation/ThirdPartyFeeProvider.cs
  WalletWasabi/Extensions/RPCClientExtensions.cs
  WalletWasabi/WebClients/BlockstreamInfo/BlockstreamInfoClient.cs
Labels: size/L

#12569 [UI] FeeChart - Integrate WildEstimations
  WalletWasabi.Fluent/Helpers/TransactionFeeHelper.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/FeeChartViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendFeeViewModel.cs
Labels: size/S

#12577 [UI] Fix potential memory leaks
  WalletWasabi.Fluent/Extensions/ObservableExtensions.cs
  WalletWasabi.Fluent/Models/Wallets/CoinModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletCoinsModel.cs
Labels: size/M

#12591 Fix logging when we destroy a round (LoadBalancer)
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/S

#12601 Avoid caching non-existing inputs
  WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs
Labels: size/S

#12523 Log end of transaction file migration to SQL
  WalletWasabi/Blockchain/Transactions/TransactionStore.cs
Labels: size/XS

#12609 [VDG] Fix TextBox cursor
  WalletWasabi.Fluent/Controls/TextBox.axaml
Labels: size/S

#12628 Change RedirectSupportAsync for CodeMaid
  WalletWasabi.Tests/UnitTests/Tor/Socks5/Pool/TorHttpPoolTests.cs
Labels: size/XS

#12634 [Trivial] Fix warning in Blockchain Controller
  WalletWasabi.Backend/Controllers/BlockchainController.cs
Labels: size/XS

#12640 IsWasabiCoinJoinLookingTx need to account for delta
  WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
Labels: size/XS

#12604 transaction search with destination address
  WalletWasabi.Fluent/ViewModels/SearchBar/Sources/TransactionsSearchSource.cs
  WalletWasabi/Helpers/NBitcoinHelpers.cs
Labels: size/S

#12637 Add mention_users_on_filechange.yml script
  .github/notify-users-config.json
  .github/workflows/mention_users_on_filechange.yml
Labels: size/L

#12320 Use `passphrase` instead of `password`
  WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/Create/ConfirmRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/Authorization/PasswordAuthDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/LoginViewModel.cs
  WalletWasabi.Fluent/Views/Dialogs/Authorization/PasswordAuthDialogView.axaml
  WalletWasabi.Fluent/Views/Dialogs/CreatePasswordDialogView.axaml
  WalletWasabi.Fluent/Views/Login/LoginView.axaml
  WalletWasabi.Fluent/Views/Wallets/WalletSettingsView.axaml
  WalletWasabi/BitcoinCore/Rpc/RpcErrorTools.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/Userfacing/PasswordHelper.cs
Labels: size/M

#12660 [VDG] Format BTC with Fixed Fractional
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
  WalletWasabi.Fluent/Controls/DualCurrencyEntryBox.axaml.cs
  WalletWasabi.Fluent/Extensions/CurrencyExtensions.cs
Labels: size/S

#12564 [UI] Merge Wallet & Coinjoin settings
  WalletWasabi.Fluent/Styles/Styles.axaml
  WalletWasabi.Fluent/Styles/TabControl.axaml
  WalletWasabi.Fluent/ViewModels/Wallets/Settings/WalletCoinJoinSettingsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Settings/WalletRenameViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Settings/WalletSettingsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Settings/WalletVerifyRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/Views/CoinJoinProfiles/CoinJoinProfilesView.axaml
  WalletWasabi.Fluent/Views/Settings/SettingsPageView.axaml
  WalletWasabi.Fluent/Views/Wallets/CoinJoinSettingsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Settings/WalletCoinJoinSettingsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Settings/WalletCoinJoinSettingsView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Settings/WalletGeneralSettingsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Settings/WalletGeneralSettingsView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Settings/WalletRenameView.axaml
  WalletWasabi.Fluent/Views/Wallets/Settings/WalletRenameView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Settings/WalletSettingsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Settings/WalletSettingsView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Settings/WalletToolsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Settings/WalletToolsView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Settings/WalletVerifyRecoveryWordsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Settings/WalletVerifyRecoveryWordsView.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/WalletSettingsView.axaml
  WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
Labels: size/L

#12575 [VDG] Privacy Progress N/A when balance is zero
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/XS

#12671 Organize (move) client side CJ related code
  WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
  WalletWasabi.Fluent/Models/Wallets/CoinjoinModel.cs
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/AliceTimeoutTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputSuccessTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/AmountDecomposerTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/CoinJoinClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/CoinJoinCoinSelectionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/IsRoundEconomicTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiApiApplicationFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi/Services/SleepInhibitor.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Client/AliceClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Client/ArenaClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Client/ArenaResponse.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Client/BobClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Client/CoinJoinClientException.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Client/CoinJoinClientState.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Client/CoinJoinCoinSelector.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Client/CoinJoinCoinSelectorRandomnessGenerator.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Client/CoinJoinProgressEvents/CoinBanned.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Client/CoinJoinProgressEvents/CoinJoinProgressEventArgs.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Client/CoinJoinProgressEvents/EnteringConnectionConfirmationPhase.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Client/CoinJoinProgressEvents/EnteringCriticalPhase.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Client/CoinJoinProgressEvents/EnteringInputRegistrationPhase.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Client/CoinJoinProgressEvents/EnteringOutputRegistrationPhase.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Client/CoinJoinProgressEvents/EnteringSigningPhase.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Client/CoinJoinProgressEvents/LeavingCriticalPhase.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Client/CoinJoinProgressEvents/RoundEnded.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Client/CoinJoinProgressEvents/RoundStateChanged.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Client/CoinJoinProgressEvents/WaitingForBlameRound.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Client/CoinJoinProgressEvents/WaitingForRound.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Client/CoinJoinResult.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Client/Decomposer/AmountDecomposer.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Client/Decomposer/Decomposer.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Client/Decomposer/DenominationBuilder.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Client/Decomposer/Output.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Client/DependencyGraphTaskScheduler.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Client/UtxoSelectionParameters.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Manager/CoinJoinManager.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Manager/CoinJoinTracker.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Manager/CoinJoinTrackerFactory.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Manager/CoinRefrigerator.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Manager/LiquidityClueProvider.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Manager/StatusChangedEvents/CoinJoinStatusEventArgs.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Manager/StatusChangedEvents/CompletedEventArgs.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Manager/StatusChangedEvents/LoadedEventArgs.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Manager/StatusChangedEvents/StartErrorEventArgs.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Manager/StatusChangedEvents/StartedEventArgs.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Manager/StatusChangedEvents/StatusChangedEventArgs.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Manager/StatusChangedEvents/StoppedEventArgs.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Manager/StatusChangedEvents/WalletStartedCoinJoinEventArgs.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Manager/StatusChangedEvents/WalletStoppedCoinJoinEventArgs.cs
  WalletWasabi/WabiSabi/Client/OutputProvider.cs
  WalletWasabi/WabiSabi/Client/SmartRequestNode.cs
Labels: size/M

#12676 chore: remove repetitive words
  WalletWasabi.Documentation/CodeCoverage.md
  WalletWasabi.Documentation/WasabikaCodex.md
  WalletWasabi.Tests/RegressionTests/SendSpeedupTests.cs
  WalletWasabi/WabiSabi/Client/Batching/PaymentAwareOutputProvider.cs
  WalletWasabi/WabiSabi/Client/CredentialDependencies/DependencyGraph.cs
Labels: size/S

#12275 Use cache in `BlockchainController.GetTransactionsAsync` (take 2)
  WalletWasabi.Backend/Controllers/BlockchainController.cs
  WalletWasabi.Tests/UnitTests/Cache/IdempotencyRequestCacheTests.cs
  WalletWasabi/Cache/IdempotencyRequestCache.cs
Labels: size/L

#12688 Fix wrong `DataDir` error on Windows for Knots
  WalletWasabi/BitcoinCore/Processes/BitcoindRpcProcessBridge.cs
Labels: size/XS

#12689 Delete unused event
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/S

#12686 Fix typestring before HardwareWalletModels parsing
  WalletWasabi/Hwi/Parsers/HwiParser.cs
Labels: size/XS

#12684 Use Warning in case of wrong json in UpdateManager
  WalletWasabi/Services/UpdateManager.cs
Labels: size/XS

#12302 Get unconfirmed tx chain - backend only
  WalletWasabi.Backend/Controllers/BlockchainController.cs
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Tests/RegressionTests/BackendTests.cs
  WalletWasabi.Tests/UnitTests/JsonConverters/HashSetUint256JsonConverterTests.cs
  WalletWasabi/JsonConverters/Collections/HashSetUint256JsonConverter.cs
  WalletWasabi/Models/UnconfirmedTransactionChainItem.cs
  WalletWasabi/WabiSabi/Models/Serialization/JsonSerializationOptions.cs
Labels: size/L

#12677 Do not abort rounds paying more than attacker
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/CoordinatorTests.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
Labels: size/L

#11949 `AutoInterfaceGenerator`: Skip interface method implementations
  WalletWasabi.Fluent.Generators/Generators/AutoInterfaceGenerator.cs
Labels: size/M

#12675 [UI] SearchBar refreshment
  WalletWasabi.Fluent/Behaviors/OnSignalTriggerBehavior.cs
  WalletWasabi.Fluent/Behaviors/ShowFlyoutWhenFocusedBehavior.cs
  WalletWasabi.Fluent/Controls/ContentControl.axaml
  WalletWasabi.Fluent/Helpers/ApplicationHelper.cs
  WalletWasabi.Fluent/Styles/FlyoutPresenter.axaml
  WalletWasabi.Fluent/Styles/Themes/Fluent.axaml
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/SearchBarViewModel.cs
  WalletWasabi.Fluent/Views/MainWindow.axaml
  WalletWasabi.Fluent/Views/SearchBar/SearchBar.axaml
  WalletWasabi.Fluent/Views/SearchBar/SearchBarDropdown.axaml
  WalletWasabi.Fluent/Views/Shell/TitleBar.axaml
  WalletWasabi.Fluent/Views/Shell/TitleBar.axaml.cs
Labels: size/L

#12694 [UI] Make CJ settings more discoverable via MusicBox
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/MusicControlsView.axaml
Labels: size/M

#12661 [VDG] Fix Amount Paste
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
  WalletWasabi.Fluent/Controls/DualCurrencyEntryBox.axaml.cs
  WalletWasabi.Fluent/Extensions/CurrencyExtensions.cs
  WalletWasabi.Fluent/Infrastructure/ClipboardObserver.cs
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
  WalletWasabi.Tests/UnitTests/Userfacing/CurrencyInputTests.cs
  WalletWasabi/Userfacing/CurrencyInput.cs
Labels: size/M

#12683 [UI] Fix Address entry focus when user clicks Send
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/2_Delivery/TextInputStep.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/WorkflowStep.cs
  WalletWasabi.Fluent/Views/Wallets/Buy/UserInputValidatorView.axaml
Labels: size/S

#12657 [UI] Send - move recipient entry to the first dialog
  WalletWasabi.Fluent/Controls/DualCurrencyEntryBox.axaml
  WalletWasabi.Fluent/Controls/TagsBox.axaml
  WalletWasabi.Fluent/Controls/TagsBox.axaml.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Labels: size/M

#12716 `UpdateChecker`: Increase interval to 1 hour
  WalletWasabi.Daemon/Global.cs
Labels: size/XS

#12723 [UI] fix `Add Wallet`: sometimes wallet name page is displayed at first wallet creation
  WalletWasabi.Fluent/ViewModels/AddWallet/WalletNamePageViewModel.cs
Labels: size/XS

#12735 Fix macOS notarization (signing), migrate to `notarytool`
  WalletWasabi.Packager/MacSignTools.cs
Labels: size/M
