Repository WalletWasabi/WalletWasabi, pull requests merged in 2024-01, with the labels that each got.

#12162 [Trivial] Update license year to 2024
  LICENSE.md
Labels: size/XS

#12169 [UI] Fix usd balance copy button is not clickable
  WalletWasabi.Fluent/Converters/MoneyConverters.cs
Labels: size/XS

#12173 [VDG] Fix text rendering after Avalonia v11 update
  WalletWasabi.Fluent/Views/MainWindow.axaml
Labels: size/S

#7638 [VDG] Display fee rate & estimated time constantly instead of tooltip
  WalletWasabi.Fluent/Views/Wallets/Send/SendFeeView.axaml
Labels: size/L

#12164 [Trivial] Remove dead code
  WalletWasabi.Fluent/State/StateMachine.cs
Labels: size/XS

#12175 Generate Taproot external keys
  WalletWasabi.Tests/UnitTests/KeyManagementTests.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
Labels: size/M

#12178 [Trivial] Fix spelling
  WalletWasabi.Fluent/Views/MainWindow.axaml
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
Labels: size/S

#12177 [VDG] Fix recovery words dialog lines visibility
  WalletWasabi.Fluent/Views/AddWallet/Create/ConfirmRecoveryWordsView.axaml
  WalletWasabi.Fluent/Views/AddWallet/Create/RecoveryWordsView.axaml
Labels: size/S

#12179 [Trivial] Add more Bitcoin Core versions to Constants.UserAgents
  WalletWasabi/Helpers/Constants.cs
Labels: size/S

#12188 RegTest - enable wallet
  WalletWasabi.Documentation/WasabiSetupRegtest.md
Labels: size/XS

#12190 Allow `P2PKH` and `P2SH` scripts in coinjoin outputs
  WalletWasabi.Tests/UnitTests/Bases/ConfigManagerTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterOutputTests.cs
  WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
Labels: size/M

#12198 Revert "Allow `P2PKH` and `P2SH` scripts in coinjoin outputs"
  WalletWasabi.Tests/UnitTests/Bases/ConfigManagerTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterOutputTests.cs
  WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
Labels: size/M

#12196 Fix RpcMonitor init in HealthMonitor
  WalletWasabi.Fluent/Models/Wallets/HealthMonitor.cs
Labels: size/M

#12192 Ensure Height is at least SegWit activation
  WalletWasabi/Wallets/Wallet.cs
Labels: size/S

#12209 [UI] Fix NavBar selection correctly
  WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
Labels: size/XS

#12221 fix memory leak caused by content area.
  WalletWasabi.Fluent/Controls/ContentArea.axaml
  WalletWasabi.Fluent/Controls/SuggestionItem.axaml
Labels: size/XS

#11335 [VDG] RecoverWallet UX fixes
  WalletWasabi.Fluent/Views/AddWallet/RecoverWalletView.axaml
Labels: size/XS

#12218 [UI] Hide label suggestions in Discreet Mode
  WalletWasabi.Fluent/Controls/TagsBox.axaml
  WalletWasabi.Tests/UnitTests/ViewModels/UiContext/NullApplicationSettings.cs
Labels: size/M

#12214 [VDG] Use new file picker api
  WalletWasabi.Fluent/Controls/QrCode.cs
  WalletWasabi.Fluent/Helpers/FileDialogHelper.cs
  WalletWasabi.Fluent/Helpers/TransactionHelpers.cs
  WalletWasabi.Fluent/Screenshot/Capture.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/LoadTransactionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/HardwareWalletViewModel.cs
Labels: size/L

#12245 Remove unused parameter `AliceClient.OwnershipProof`
  WalletWasabi/WabiSabi/Client/AliceClient.cs
Labels: size/XS

#12224 [UI] Distinguish between 1 and multiple addresses for copy button
  WalletWasabi.Fluent/Controls/PreviewItem.axaml.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/TransactionDetailsViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/History/Details/TransactionDetailsView.axaml
Labels: size/S

#12250 Move repeating behavior of `P2PBlockProvider` to `SmartBlockProvider`
  WalletWasabi/Wallets/P2PBlockProvider.cs
  WalletWasabi/Wallets/SmartBlockProvider.cs
Labels: size/M

#12219 Fix round parameters
  WalletWasabi.Tests/UnitTests/TestWallet.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/CoinJoinCoinSelectionTests.cs
  WalletWasabi/WabiSabi/Backend/Rounds/RoundParameters.cs
  WalletWasabi/WabiSabi/Backend/Rounds/UtxoSelectionParameters.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoinCoinSelector.cs
  WalletWasabi/WabiSabi/Client/IDestinationProvider.cs
  WalletWasabi/WabiSabi/Client/InternalDestinationProvider.cs
  WalletWasabi/WabiSabi/Client/OutputProvider.cs
  WalletWasabi/WabiSabi/Client/UtxoSelectionParameters.cs
Labels: size/L

#12207 Include password instructions under wallet settings
  WalletWasabi.Fluent/Views/Wallets/WalletSettingsView.axaml
Labels: size/XS

#12251 Fix typos in Documentation
  WalletWasabi.Documentation/ClientRelease/ClientDeployment.md
  WalletWasabi.Documentation/Guides/HowToDebug.md
  WalletWasabi.Documentation/Guides/MacOsSigning.md
  WalletWasabi.Documentation/WasabikaCodex.md
  WalletWasabi/Gma/QrCodeNet/Encoding/QRCodeConstantVariable.cs
  WalletWasabi/Nito/Disposables/Internals/BoundAction.cs
  WalletWasabi/Nito/Disposables/SingleDisposable.cs
  WalletWasabi/WabiSabi/Client/CredentialDependencies/CredentialEdgeSet.cs
Labels: size/S

#12257 Fix oldPath for transactions migration
  WalletWasabi/Blockchain/Transactions/TransactionStore.cs
Labels: size/XS

#12233 [Trivial] Remove unused code
  WalletWasabi/WabiSabi/Client/IDestinationProvider.cs
Labels: size/XS

#12262 Use INotifyPropertyChanged instead of base in WasabiSynchronizer
  WalletWasabi/Services/WasabiSynchronizer.cs
Labels: size/S

#12268 [UI] Update the last selected wallet after rename
  WalletWasabi.Fluent/ViewModels/Wallets/WalletRenameViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletSettingsViewModel.cs
Labels: size/S

#12256 `P2PKH`, `P2SH` and `P2WSH` in coinjoin outputs
  WalletWasabi.Tests/UnitTests/Bases/ConfigManagerTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterOutputTests.cs
  WalletWasabi/Extensions/NBitcoinExtensions.cs
  WalletWasabi/Helpers/Constants.cs
  WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
Labels: size/M

#12234 Remove brain farts
  WalletWasabi.Tests/RegressionTests/ReorgTest.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
  WalletWasabi/Blockchain/Keys/HdPubKey.cs
  WalletWasabi/Blockchain/Keys/HdPubKeyCache.cs
  WalletWasabi/Blockchain/Keys/HdPubKeyGlobalView.cs
  WalletWasabi/Blockchain/Keys/HdPubKeyInfo.cs
  WalletWasabi/Blockchain/Keys/HdPubKeyPathView.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/Extensions/LazyExtensions.cs
  WalletWasabi/Wallets/WalletFilterProcessor.cs
Labels: size/L

#12270 Revert "Remove brain farts"
  WalletWasabi.Tests/RegressionTests/ReorgTest.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
  WalletWasabi/Blockchain/Keys/HdPubKey.cs
  WalletWasabi/Blockchain/Keys/HdPubKeyCache.cs
  WalletWasabi/Blockchain/Keys/HdPubKeyGlobalView.cs
  WalletWasabi/Blockchain/Keys/HdPubKeyInfo.cs
  WalletWasabi/Blockchain/Keys/HdPubKeyPathView.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/Extensions/LazyExtensions.cs
  WalletWasabi/Wallets/WalletFilterProcessor.cs
Labels: size/L

#12272 update to Avalonia 11.0.7
  Directory.Packages.props
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/packages.lock.json
Labels: size/L

#12283 Update WasabiSetupRegtest.md, for #12282
  WalletWasabi.Documentation/WasabiSetupRegtest.md
Labels: size/XS

#12281 Move EnsureHeightsAreAtLeastSegWitActivation to WalletManager
  WalletWasabi.Daemon/Global.cs
  WalletWasabi/Wallets/Wallet.cs
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/M

#12269 Introduce `PeriodicRunner` in `WasabiSynchronizer`
  WalletWasabi.Daemon/Global.cs
  WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
  WalletWasabi.Fluent/App.axaml.cs
  WalletWasabi.Fluent/Models/Wallets/HealthMonitor.cs
  WalletWasabi.Fluent/Models/Wallets/WalletLoadWorkflow.cs
  WalletWasabi.Fluent/Services.cs
  WalletWasabi.Tests/IntegrationTests/P2pTests.cs
  WalletWasabi.Tests/RegressionTests/BuildTransactionReorgsTest.cs
  WalletWasabi.Tests/RegressionTests/BuildTransactionValidationsTest.cs
  WalletWasabi.Tests/RegressionTests/CancelTests.cs
  WalletWasabi.Tests/RegressionTests/FilterDownloaderTest.cs
  WalletWasabi.Tests/RegressionTests/MaxFeeTests.cs
  WalletWasabi.Tests/RegressionTests/ReceiveSpeedupTests.cs
  WalletWasabi.Tests/RegressionTests/ReorgTest.cs
  WalletWasabi.Tests/RegressionTests/ReplaceByFeeTxTest.cs
  WalletWasabi.Tests/RegressionTests/SelfSpendSpeedupTests.cs
  WalletWasabi.Tests/RegressionTests/SendSpeedupTests.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi.Tests/RegressionTests/SpendUnconfirmedTxTests.cs
  WalletWasabi.Tests/RegressionTests/WalletTests.cs
  WalletWasabi.Tests/UnitTests/Wallet/WalletBuilder.cs
  WalletWasabi/Services/WasabiSynchronizer.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/L

#12273 Improve key cache perf
  WalletWasabi.Tests/RegressionTests/ReorgTest.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
  WalletWasabi/Blockchain/Keys/HdPubKey.cs
  WalletWasabi/Blockchain/Keys/HdPubKeyCache.cs
  WalletWasabi/Blockchain/Keys/HdPubKeyGlobalView.cs
  WalletWasabi/Blockchain/Keys/HdPubKeyInfo.cs
  WalletWasabi/Blockchain/Keys/HdPubKeyPathView.cs
  WalletWasabi/Blockchain/Keys/KeyManager.cs
  WalletWasabi/Wallets/WalletFilterProcessor.cs
Labels: size/L

#12290 Avoid unnecessary materialization
  WalletWasabi/Wallets/WalletFilterProcessor.cs
Labels: size/XS

#12286 [UI] Fix broken Send Privacy Suggestion preview on ALT+TAB
  WalletWasabi.Fluent/Behaviors/ListBoxPreviewBehavior.cs
  WalletWasabi.Fluent/Views/Wallets/Send/PrivacyWarningsView.axaml
Labels: size/XS

#12210 Fix osx dock icon issues
  WalletWasabi.Fluent/App.axaml
  WalletWasabi.Fluent/App.axaml.cs
  WalletWasabi.Fluent/ApplicationStateManager.cs
  WalletWasabi.Fluent/ViewModels/SearchBar/SettingsSearchSource.cs
  WalletWasabi.Fluent/Views/Settings/GeneralSettingsTabView.axaml
Labels: size/M

#12230 Fixes major memory leak
  WalletWasabi.Fluent/Behaviors/PendingHistoryItemSeparatorBehavior.cs
  WalletWasabi.Fluent/Controls/PrivacyContentControl.axaml
  WalletWasabi.Fluent/Controls/PrivacyContentControl.axaml.cs
  WalletWasabi.Fluent/Helpers/PrivacyModeHelper.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
  WalletWasabi.Fluent/test.bin
  WalletWasabi.sln
Labels: size/L

#12287 Fix rendering issues in privacy text cell
  WalletWasabi.Fluent/TreeDataGrid/TreeDataGridPrivacyTextCell.cs
Labels: size/M

#12288 Offline Psbt Workflow compatible
  WalletWasabi/Hwi/Models/HwiEnumerateEntry.cs
Labels: size/S

#12267 Open the wallet files in parallel at startup
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/M

#12258 Improve most used labels
  WalletWasabi.Fluent/Helpers/EnumerableExtensions.cs
  WalletWasabi.Fluent/Helpers/KeyManagerExtensions.cs
  WalletWasabi.Fluent/Helpers/LabelHelpers.cs
  WalletWasabi.Fluent/Helpers/WalletHelpers.cs
Labels: size/M

#12271 Allow arbitrary content in music box messages
  WalletWasabi.Fluent/Converters/ReplaceWordsByContentConverter.cs
  WalletWasabi.Fluent/Extensions/EnumerableExtension.cs
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/MusicControlsView.axaml
Labels: size/M

#12124 Override Fee Overpayment Protection via RPC
  WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
  WalletWasabi.Fluent/Helpers/TransactionHelpers.cs
  WalletWasabi.Tests/Helpers/TransactionParametersBuilder.cs
  WalletWasabi/Blockchain/TransactionBuilding/TransactionBuilderWalletExtensions.cs
  WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
  WalletWasabi/Blockchain/Transactions/TransactionParameters.cs
Labels: size/L

#12307 Add `HttpRequestException` handling in `PeriodicRunner`
  WalletWasabi/Bases/PeriodicRunner.cs
Labels: size/S

#12303 Remove Taproot-only compact filters
  WalletWasabi.Backend/Controllers/BatchController.cs
  WalletWasabi.Backend/Controllers/BlockchainController.cs
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Tests/RegressionTests/BackendTests.cs
Labels: size/L

#10884 Pay to miners the exact committed fee rate
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/MultipartyTransactionTests.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Labels: size/M

#12306 Try not to use unconfirmed coins when BnB.
  WalletWasabi.Fluent/Models/Transactions/PrivacySuggestionsModel.cs
Labels: size/S

#12311 Refactor exception catches in `WasabiSynchronizer`
  WalletWasabi/Services/WasabiSynchronizer.cs
Labels: size/M

#12277 Optimize application startup - alternate method
  WalletWasabi.Fluent/Models/Wallets/Address.cs
  WalletWasabi.Fluent/Models/Wallets/AddressesModel.cs
  WalletWasabi.Fluent/Models/Wallets/IAddress.cs
  WalletWasabi.Fluent/Models/Wallets/WalletModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/AddressViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressesViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveView.axaml
  WalletWasabi.Tests/UnitTests/ViewModels/AddressViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/ReceiveAddressViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/ReceiveViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/SuggestionLabelsViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/TestDoubles/AddressTestingMocks.cs
Labels: size/L

#12326 Coldcard Edge firmware version fixing
  WalletWasabi/Helpers/ImportWalletHelper.cs
Labels: size/XS

#12299 Wallets load - remove refresh mechanism
  WalletWasabi.Fluent/Helpers/WalletHelpers.cs
  WalletWasabi.Fluent/Models/Wallets/WalletRepository.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletPageViewModel.cs
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/M
