Repository WalletWasabi/WalletWasabi, pull requests merged in 2024-05, with the labels that each got.

#12964 Fix Password Finder's CTS dispose
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/SearchPasswordViewModel.cs
Labels: size/S

#12965 Reverts #12964 + Fix PF's CTS dispose
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/SearchPasswordViewModel.cs
Labels: size/S

#12968 Disable coinjoins
  WalletWasabi.Tests/UnitTests/Bases/ConfigManagerTests.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
  WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
Labels: size/S

#12974 `TerminateService`: Allow forceful termination on second CTLR+C
  WalletWasabi/Services/Terminate/TerminateService.cs
Labels: size/S

#12975 Remove `PasswordFinder`
  WalletWasabi.Documentation/PasswordFinder.md
  WalletWasabi.Fluent/Models/Wallets/PasswordFinderModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletAuthModel.cs
  WalletWasabi.Fluent/ViewModels/Login/LoginViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/CharsetViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/ContainsNumbersViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/ContainsSymbolsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/PasswordFinderIntroduceViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/PasswordFoundViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/PasswordNotFoundViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/SearchPasswordViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/SelectCharsetViewModel.cs
  WalletWasabi.Fluent/Views/Login/LoginView.axaml
  WalletWasabi.Fluent/Views/Login/PasswordFinder/ContainsNumbersView.axaml
  WalletWasabi.Fluent/Views/Login/PasswordFinder/ContainsNumbersView.axaml.cs
  WalletWasabi.Fluent/Views/Login/PasswordFinder/ContainsSymbolsView.axaml
  WalletWasabi.Fluent/Views/Login/PasswordFinder/ContainsSymbolsView.axaml.cs
  WalletWasabi.Fluent/Views/Login/PasswordFinder/PasswordFinderIntroduceView.axaml
  WalletWasabi.Fluent/Views/Login/PasswordFinder/PasswordFinderIntroduceView.axaml.cs
  WalletWasabi.Fluent/Views/Login/PasswordFinder/PasswordFoundView.axaml
  WalletWasabi.Fluent/Views/Login/PasswordFinder/PasswordFoundView.axaml.cs
  WalletWasabi.Fluent/Views/Login/PasswordFinder/PasswordNotFoundView.axaml
  WalletWasabi.Fluent/Views/Login/PasswordFinder/PasswordNotFoundView.axaml.cs
  WalletWasabi.Fluent/Views/Login/PasswordFinder/SearchPasswordView.axaml
  WalletWasabi.Fluent/Views/Login/PasswordFinder/SearchPasswordView.axaml.cs
  WalletWasabi.Fluent/Views/Login/PasswordFinder/SelectCharsetView.axaml
  WalletWasabi.Fluent/Views/Login/PasswordFinder/SelectCharsetView.axaml.cs
  WalletWasabi/Wallets/PasswordFinder/PasswordFinderCharset.cs
  WalletWasabi/Wallets/PasswordFinder/PasswordFinderHelper.cs
  WalletWasabi/Wallets/PasswordFinder/PasswordFinderOptions.cs
Labels: size/XL

#12976 Remove `BenchmarkLogger`
  WalletWasabi.Daemon/Global.cs
  WalletWasabi/BitcoinCore/CoreNode.cs
  WalletWasabi/Blockchain/Transactions/AllTransactionStore.cs
  WalletWasabi/Blockchain/Transactions/TransactionStore.cs
  WalletWasabi/Logging/BenchmarkLogger.cs
  WalletWasabi/Stores/BitcoinStore.cs
  WalletWasabi/Stores/IndexStore.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Client/CoinJoinClient.cs
  WalletWasabi/Wallets/FileSystemBlockRepository.cs
  WalletWasabi/Wallets/Wallet.cs
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/L

#12972 Remove `RequestTimeStatista`
  WalletWasabi.Backend/Controllers/BlockchainController.cs
  WalletWasabi.Backend/Controllers/WabiSabiController.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/ConfigTests.cs
  WalletWasabi/BitcoinCore/Rpc/RpcClientBase.cs
  WalletWasabi/WabiSabi/Backend/Banning/CoinVerifierApiClient.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Statistics/RequestTimeStatista.cs
Labels: size/L

#12970 Remove chain analysis querying
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Tests/RegressionTests/CoinVerifierApiClientStressTests.cs
  WalletWasabi.Tests/UnitTests/Bases/ConfigManagerTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/CoinVerifierTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/WhitelistTests.cs
  WalletWasabi/WabiSabi/Backend/Banning/ApiResponseItem.cs
  WalletWasabi/WabiSabi/Backend/Banning/AuditEventType.cs
  WalletWasabi/WabiSabi/Backend/Banning/CoinVerifier.cs
  WalletWasabi/WabiSabi/Backend/Banning/CoinVerifierApiClient.cs
  WalletWasabi/WabiSabi/Backend/Banning/CoinVerifierLogger.cs
  WalletWasabi/WabiSabi/Backend/Banning/CoinVerifyItem.cs
  WalletWasabi/WabiSabi/Backend/Banning/CoinVerifyResult.cs
  WalletWasabi/WabiSabi/Backend/Banning/Innocent.cs
  WalletWasabi/WabiSabi/Backend/Banning/Whitelist.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
  WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
Labels: size/XXL

#12987 [UI] Remove duplication of most used labels in Receive view
  WalletWasabi.Fluent/ViewModels/Wallets/Labels/SuggestionLabelsViewModel.cs
Labels: size/XS

#12983 [UI] Send - keep focus when clicking on amount hyperlink
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Labels: size/XS

#12980 Remove legal documents
  WalletWasabi.Backend/Controllers/SoftwareController.cs
  WalletWasabi.Backend/Controllers/WasabiController.cs
  WalletWasabi.Daemon/Global.cs
  WalletWasabi.Fluent/App.axaml.cs
  WalletWasabi.Fluent/Models/UI/UiContext.cs
  WalletWasabi.Fluent/Models/Wallets/LegalDocumentsProvider.cs
  WalletWasabi.Fluent/Models/Wallets/WalletAuthModel.cs
  WalletWasabi.Fluent/Services.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/AddedWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/LegalDocumentsViewModel.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/TermsAndConditionsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Login/LoginViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModelExtensions.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletPageViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/LegalDocumentsView.axaml
  WalletWasabi.Fluent/Views/AddWallet/LegalDocumentsView.axaml.cs
  WalletWasabi.Fluent/Views/AddWallet/TermsAndConditionsView.axaml
  WalletWasabi.Fluent/Views/AddWallet/TermsAndConditionsView.axaml.cs
  WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
  WalletWasabi.Tests/UnitTests/Affiliation/CanonicalSerializationTests.cs
  WalletWasabi.Tests/UnitTests/LegalTests.cs
  WalletWasabi.Tests/UnitTests/UpdateStatusTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/TestDoubles/MockUtils.cs
  WalletWasabi.Tests/UnitTests/ViewModels/UiContextBuilder.cs
  WalletWasabi/Backend/Models/Responses/VersionsResponse.cs
  WalletWasabi/Helpers/Constants.cs
  WalletWasabi/Legal/Assets/LegalDocumentsWw1.txt
  WalletWasabi/Legal/Assets/LegalDocumentsWw2.txt
  WalletWasabi/Legal/LegalDocuments.cs
  WalletWasabi/Models/UpdateStatus.cs
  WalletWasabi/Services/LegalChecker.cs
  WalletWasabi/Services/UpdateChecker.cs
  WalletWasabi/WalletWasabi.csproj
  WalletWasabi/WebClients/Wasabi/WasabiClient.cs
Labels: size/XXL

#12984 [UI] TagsBox - fix style
  WalletWasabi.Fluent/Controls/TagsBox.axaml
Labels: size/XS

#12981 [UI] Fee Slider - fix Y axis labels
  WalletWasabi.Fluent/ViewModels/Wallets/Send/FeeChartViewModel.cs
Labels: size/XS

#12990 Update ClientDeployment.md
  WalletWasabi.Documentation/ClientRelease/ClientDeployment.md
Labels: size/L

#12997 [v2.0.7.2] Mix to another wallet clean
  WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
  WalletWasabi.Fluent/Models/Wallets/WalletCoinjoinModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletSettingsModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Settings/WalletCoinJoinSettingsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Settings/WalletSettingsViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Settings/WalletCoinJoinSettingsView.axaml
  WalletWasabi.Tests/UnitTests/ViewModels/ReceiveAddressViewModelTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/SuggestionLabelsViewModelTests.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Manager/CoinJoinTrackerFactory.cs
  WalletWasabi/Wallets/IWallet.cs
Labels: size/L

#12999 Bump version to v2.0.7.2
  WalletWasabi/Helpers/Constants.cs
Labels: size/XS

#13000 Final Update of ClientDeployment
  WalletWasabi.Documentation/ClientRelease/ClientDeployment.md
Labels: size/M

#13001 [trivial] Warn about CA1865-CA1867: Use 'string.Method(char)' instead of 'strin…
  .editorconfig
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
  WalletWasabi/Blockchain/Keys/WalletGenerator.cs
  WalletWasabi/Helpers/EnvironmentHelpers.cs
  WalletWasabi/Tor/Control/Messages/CircuitStatus/CircuitInfo.cs
  WalletWasabi/Userfacing/CurrencyInput.cs
Labels: size/S

#12996 [FOSS] Remove CJ fee related contents
  WalletWasabi.Fluent/ViewModels/AddWallet/WelcomePageViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/WelcomePageView.axaml
  WalletWasabi.Fluent/Views/CoinJoinProfiles/CoinJoinProfilesView.axaml
Labels: size/L

#12995 Remove `CoinjoinIdStore`
  WalletWasabi.Backend/Controllers/WabiSabiController.cs
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Backend/Startup.cs
  WalletWasabi.Tests/Helpers/ArenaBuilder.cs
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/CoinjoinIdStoreTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/CoinJoinMempoolManagerTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/ConfigTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/CoordinatorTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputSuccessTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PrisonTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/UtxoPrisonWardenTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiApiApplicationFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi/WabiSabi/Backend/CoinJoinMempoolManager.cs
  WalletWasabi/WabiSabi/Backend/DoSPrevention/Prison.cs
  WalletWasabi/WabiSabi/Backend/DoSPrevention/Warden.cs
  WalletWasabi/WabiSabi/Backend/Models/Alice.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Rounds/CoinJoinStorage/CoinJoinIdStore.cs
  WalletWasabi/WabiSabi/Backend/Rounds/CoinJoinStorage/ICoinJoinIdStore.cs
  WalletWasabi/WabiSabi/Backend/Rounds/CoinJoinStorage/InMemoryCoinJoinIdStore.cs
  WalletWasabi/WabiSabi/CoordinatorParameters.cs
  WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
Labels: size/XL

#13013 fix coin join real start
  WalletWasabi.Fluent/Models/Wallets/WalletCoinjoinModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Settings/WalletCoinJoinSettingsViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Settings/WalletCoinJoinSettingsView.axaml
Labels: size/S

#13011 Update Terms and Conditions
  WalletWasabi/Helpers/Constants.cs
  WalletWasabi/Legal/Assets/LegalDocumentsWw2.txt
Labels: size/L

#13006 [UI] Add option to configure selectability of CJing coins
  WalletWasabi.Fluent/ViewModels/CoinControl/SelectCoinsDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoinsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Coins/CoinListViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Coins/CoinViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Coins/PocketViewModel.cs
Labels: size/S

#13005 Make Wasabi FREE by default
  WalletWasabi.Tests/UnitTests/Bases/ConfigManagerTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputSuccessTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/MultipartyTransactionTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Models/SerializationTests.cs
  WalletWasabi/Crypto/StrobeProtocol/StrobeHasherExtensions.cs
  WalletWasabi/JsonConverters/DefaultValueCoordinationFeeRateAttribute.cs
  WalletWasabi/WabiSabi/Backend/Models/Alice.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Client/AliceClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Client/ArenaClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Models/CoordinationFeeRate.cs
  WalletWasabi/WabiSabi/Models/InputRegistrationResponse.cs
Labels: size/M

#13017 Remove Human Monitor API
  WalletWasabi.Backend/Controllers/WabiSabiController.cs
  WalletWasabi/WabiSabi/Models/HumanMonitorResponse.cs
  WalletWasabi/WabiSabi/Models/HumanMonitorRoundResponse.cs
Labels: size/M

#12998 Remove coinjoin archive
  WalletWasabi.Tests/Helpers/ArenaBuilder.cs
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/CoordinatorTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputSuccessTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/Rounds/Utils/CoinJoinTransactionArchiverTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/UtxoPrisonWardenTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiApiApplicationFactory.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
  WalletWasabi/WabiSabi/Backend/DoSPrevention/Prison.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/Rounds/CoinJoinStorage/CoinJoinTransactionArchiver.cs
  WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
Labels: size/L

#12893 [UI] Exclude coins from coinjoin
  WalletWasabi.Fluent/Controls/Button.axaml
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/Models/Wallets/CoinModel.cs
  WalletWasabi.Fluent/Models/Wallets/WalletCoinsModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Coins/CoinListDataGridSource.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Coins/CoinListItem.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Coins/CoinListViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Coins/CoinViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Coins/PocketViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Settings/ExcludedCoinsViewModel.cs
  WalletWasabi.Fluent/Views/CoinControl/Core/Cells/IndicatorsCellView.axaml
  WalletWasabi.Fluent/Views/CoinControl/Core/Cells/SelectionCellView.axaml
  WalletWasabi.Fluent/Views/Wallets/MusicControlsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Settings/ExcludedCoinsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Settings/ExcludedCoinsView.axaml.cs
  WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
  WalletWasabi.Tests/UnitTests/ViewModels/ReceiveAddressViewModelTests.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/L

#13018 Remove status API
  WalletWasabi.Backend/Controllers/BlockchainController.cs
  WalletWasabi.Tests/RegressionTests/BackendTests.cs
  WalletWasabi/Backend/Models/Responses/StatusResponse.cs
Labels: size/L

#12896 SQLite: Disable connection pooling for block filter SQLite database
  WalletWasabi/Stores/BlockFilterSqliteStorage.cs
  WalletWasabi/Stores/IndexStore.cs
Labels: size/XS

#13019 Remove unused API
  WalletWasabi.Backend/Controllers/BlockchainController.cs
  WalletWasabi.Backend/Controllers/LegacyController.cs
  WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
  WalletWasabi.Tests/RegressionTests/RegTestSetup.cs
  WalletWasabi/WebClients/Wasabi/WasabiClient.cs
Labels: size/L

#12994 Disable `CA1861` analyzer
  WalletWasabi.Tests/.editorconfig
Labels: size/XS

#12992 Removing "can be simplified" warnings
  WalletWasabi.Backend/Controllers/BatchController.cs
  WalletWasabi.Fluent.Desktop/Extensions/AppBuilderExtension.cs
  WalletWasabi.Fluent.Generators/AnalyzerExtensions.cs
  WalletWasabi.Tests/Helpers/BitcoinFactory.cs
  WalletWasabi/Crypto/OwnershipIdentifier.cs
  WalletWasabi/Tor/Http/Models/HeaderSection.cs
Labels: size/S

#13026 Bump client version to 2.0.7.2
  WalletWasabi/Helpers/Constants.cs
Labels: size/XS

#13030 CodeFactor cleanup
  WalletWasabi.Daemon/WasabiAppBuilder.cs
  WalletWasabi.Fluent/ApplicationStateManager.cs
  WalletWasabi.Fluent/Behaviors/HorizontalScrollViewerBehavior.cs
  WalletWasabi.Fluent/Controls/LineChart.cs
  WalletWasabi.Fluent/Helpers/EnumerableExtensions.cs
  WalletWasabi.Fluent/MathNet/CubicSpline.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/OrderViewModel.cs
  WalletWasabi/Services/UpdateManager.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/MultipartyTransactionState.cs
  WalletWasabi/WabiSabi/Models/MultipartyTransaction/SigningState.cs
Labels: size/M

#13028 Move exchange rate to client
  WalletWasabi.Backend/Controllers/BatchController.cs
  WalletWasabi.Backend/Controllers/OffchainController.cs
  WalletWasabi.Backend/Startup.cs
  WalletWasabi.Daemon/Config.cs
  WalletWasabi.Daemon/Global.cs
  WalletWasabi.Daemon/PersistentConfig.cs
  WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
  WalletWasabi.Fluent/App.axaml.cs
  WalletWasabi.Fluent/Models/Transactions/PrivacySuggestionsModel.cs
  WalletWasabi.Fluent/Models/Wallets/AmountProvider.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi.Tests/IntegrationTests/BlockstreamInfoClientTests.cs
  WalletWasabi.Tests/IntegrationTests/ExternalApiTests.cs
  WalletWasabi.Tests/RegressionTests/BackendTests.cs
  WalletWasabi.Tests/UnitTests/Bases/ConfigManagerNgTests.cs
  WalletWasabi/Backend/Models/ExchangeRate.cs
  WalletWasabi/Backend/Models/Responses/SynchronizeResponse.cs
  WalletWasabi/ExchangeRate/ExchangeRate.cs
  WalletWasabi/ExchangeRate/ExchangeRateProvider.cs
  WalletWasabi/ExchangeRate/ExchangeRateUpdater.cs
  WalletWasabi/Extensions/StringExtensions.cs
  WalletWasabi/Interfaces/IExchangeRateProvider.cs
  WalletWasabi/Services/WasabiSynchronizer.cs
  WalletWasabi/WebClients/Bitstamp/BitstampExchangeRate.cs
  WalletWasabi/WebClients/Bitstamp/BitstampExchangeRateProvider.cs
  WalletWasabi/WebClients/BlockchainInfo/BlockchainInfoExchangeRateProvider.cs
  WalletWasabi/WebClients/CoinGecko/CoinGeckoExchangeRate.cs
  WalletWasabi/WebClients/CoinGecko/CoinGeckoExchangeRateProvider.cs
  WalletWasabi/WebClients/Coinbase/CoinbaseExchangeRateProvider.cs
  WalletWasabi/WebClients/Coingate/CoingateExchangeRateProvider.cs
  WalletWasabi/WebClients/ExchangeRateProviders.cs
  WalletWasabi/WebClients/Gemini/GeminiExchangeRateProvider.cs
  WalletWasabi/WebClients/UserAgent.cs
Labels: size/XXL

#13035 Move feerate to client
  WalletWasabi.Backend/Controllers/BatchController.cs
  WalletWasabi.Backend/Controllers/BlockchainController.cs
  WalletWasabi.Daemon/Config.cs
  WalletWasabi.Daemon/Global.cs
  WalletWasabi.Daemon/PersistentConfig.cs
  WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
  WalletWasabi.Fluent/Extensions/TransactionSummaryExtensions.cs
  WalletWasabi.Fluent/Helpers/TransactionFeeHelper.cs
  WalletWasabi.Fluent/Models/Wallets/TransactionTreeBuilder.cs
  WalletWasabi.Fluent/Models/Wallets/WalletTransactionsModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendFeeViewModel.cs
  WalletWasabi.Tests/IntegrationTests/ExternalApiTests.cs
  WalletWasabi.Tests/IntegrationTests/P2pTests.cs
  WalletWasabi.Tests/RegressionTests/BackendTests.cs
  WalletWasabi.Tests/RegressionTests/BuildTransactionReorgsTest.cs
  WalletWasabi.Tests/RegressionTests/BuildTransactionValidationsTest.cs
  WalletWasabi.Tests/RegressionTests/CancelTests.cs
  WalletWasabi.Tests/RegressionTests/FilterDownloaderTest.cs
  WalletWasabi.Tests/RegressionTests/MaxFeeTests.cs
  WalletWasabi.Tests/RegressionTests/ReceiveSpeedupTests.cs
  WalletWasabi.Tests/RegressionTests/ReorgTest.cs
  WalletWasabi.Tests/RegressionTests/ReplaceByFeeTxTest.cs
  WalletWasabi.Tests/RegressionTests/SelfSpendSpeedupTests.cs
  WalletWasabi.Tests/RegressionTests/SendSpeedupTests.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi.Tests/RegressionTests/SpendUnconfirmedTxTests.cs
  WalletWasabi.Tests/RegressionTests/WalletTests.cs
  WalletWasabi.Tests/UnitTests/AllFeeEstimateTests.cs
  WalletWasabi.Tests/UnitTests/Bases/ConfigManagerNgTests.cs
  WalletWasabi.Tests/UnitTests/Wallet/WalletBuilder.cs
  WalletWasabi/Backend/Models/Responses/SynchronizeResponse.cs
  WalletWasabi/BitcoinCore/Monitoring/RpcFeeProvider.cs
  WalletWasabi/Blockchain/Analysis/FeesEstimation/HybridFeeProvider.cs
  WalletWasabi/Blockchain/Analysis/FeesEstimation/IThirdPartyFeeProvider.cs
  WalletWasabi/Blockchain/Analysis/FeesEstimation/ThirdPartyFeeProvider.cs
  WalletWasabi/Blockchain/TransactionBuilding/TransactionBuilderWalletExtensions.cs
  WalletWasabi/Blockchain/TransactionBuilding/TransactionModifierWalletExtensions.cs
  WalletWasabi/ExchangeRate/ExchangeRateProvider.cs
  WalletWasabi/Extensions/RPCClientExtensions.cs
  WalletWasabi/FeeRateEstimation/AllFeeEstimate.cs
  WalletWasabi/FeeRateEstimation/FeeRateEstimationUpdater.cs
  WalletWasabi/FeeRateEstimation/FeeRateProvider.cs
  WalletWasabi/Models/CoinjoinSkipFactors.cs
  WalletWasabi/Services/WasabiSynchronizer.cs
  WalletWasabi/Tor/Socks5/Socks5Proxy.cs
  WalletWasabi/Wallets/Wallet.cs
  WalletWasabi/Wallets/WalletFactory.cs
  WalletWasabi/WebClients/BlockstreamInfo/BlockstreamInfoClient.cs
  WalletWasabi/WebClients/BlockstreamInfo/BlockstreamInfoFeeProvider.cs
Labels: size/XL

#13038 Remove leftovers
  WalletWasabi.Backend/Controllers/BatchController.cs
  WalletWasabi.Backend/Controllers/BlockchainController.cs
  WalletWasabi.Backend/Controllers/WabiSabiController.cs
  WalletWasabi.Backend/Startup.cs
Labels: size/M

#13031 Fix some CodeFactor issues
  WalletWasabi/BitcoinCore/Monitoring/RpcFeeProvider.cs
  WalletWasabi/Blockchain/Analysis/FeesEstimation/HybridFeeProvider.cs
  WalletWasabi/Blockchain/Analysis/FeesEstimation/ThirdPartyFeeProvider.cs
  WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
  WalletWasabi/Crypto/HashHelpers.cs
  WalletWasabi/Nito/AsyncEx/AbandonedTasks.cs
Labels: size/S

#13041 Pass KeyChain of the output wallet to DependencyGraphTaskScheduler
  WalletWasabi/WabiSabi/Client/CoinJoin/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Client/DependencyGraphTaskScheduler.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Manager/CoinJoinManager.cs
  WalletWasabi/WabiSabi/Client/IDestinationProvider.cs
  WalletWasabi/WabiSabi/Client/IKeyChain.cs
  WalletWasabi/WabiSabi/Client/InternalDestinationProvider.cs
  WalletWasabi/WabiSabi/Client/KeyChain.cs
Labels: size/M

#13027 Refactor `UpdateManager` & Remove `UpdateChecker`
  WalletWasabi.Backend/Controllers/SoftwareController.cs
  WalletWasabi.Daemon/Global.cs
  WalletWasabi.Fluent/Models/Wallets/HealthMonitor.cs
  WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
  WalletWasabi.Tests/UnitTests/UpdateStatusTests.cs
  WalletWasabi/Backend/Models/Responses/VersionsResponse.cs
  WalletWasabi/Models/UpdateStatus.cs
  WalletWasabi/Services/UpdateChecker.cs
  WalletWasabi/Services/UpdateManager.cs
  WalletWasabi/WebClients/Wasabi/WasabiClient.cs
Labels: size/L

#13040 Organize the API
  WalletWasabi.Backend/Controllers/BatchController.cs
  WalletWasabi.Backend/Controllers/WalletController.cs
  WalletWasabi/WebClients/Wasabi/WasabiClient.cs
Labels: size/L

#13048 Revert "Organize the API"
  WalletWasabi.Backend/Controllers/BatchController.cs
  WalletWasabi.Backend/Controllers/BlockchainController.cs
  WalletWasabi/WebClients/Wasabi/WasabiClient.cs
Labels: size/L

#13049 Organize the API
  WalletWasabi.Backend/Controllers/BatchController.cs
  WalletWasabi.Backend/Controllers/SoftwareController.cs
  WalletWasabi.Backend/Controllers/WalletController.cs
  WalletWasabi/WebClients/Wasabi/WasabiClient.cs
Labels: size/L

#13046 Improve output registration error handling
  WalletWasabi.Fluent/Models/Wallets/WalletRepository.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/AboutAdvancedInfoViewModel.cs
  WalletWasabi.Tests/UnitTests/Helpers/ResultTests.cs
  WalletWasabi/Helpers/Result.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Client/CoinJoinClient.cs
  WalletWasabi/WabiSabi/Client/CoinJoin/Client/DependencyGraphTaskScheduler.cs
Labels: size/L

#13052 [refactoring] `CoinJoinProcessor`: pass correctly `WasabiHttpClientFactory`
  WalletWasabi.Daemon/Global.cs
  WalletWasabi/CoinJoin/Client/CoinJoinProcessor.cs
Labels: size/S

#13057 Use correct path for `addressManagerFilePath` in `BlockDownloadTests`
  WalletWasabi.Tests/IntegrationTests/BlockDownloadTests.cs
Labels: size/XS

#13058 Mark BDS Tests as a collection + pass CT to Delay
  WalletWasabi.Tests/UnitTests/Wallet/FilterProcessor/BlockDownloadServiceTests.cs
Labels: size/XS

#13060 [UI] CurrencyEntryBox - add missing style class
  WalletWasabi.Fluent/Views/Settings/BitcoinTabSettingsView.axaml
  WalletWasabi.Fluent/Views/Wallets/Settings/WalletCoinJoinSettingsView.axaml
Labels: size/XS

#13061 [UI] Notification - adjust text when CPFP
  WalletWasabi.Fluent/Helpers/NotificationHelpers.cs
Labels: size/XS

#13063 [Trivial] Remove unused members
  WalletWasabi.Fluent/Controls/NavBarItem.axaml.cs
  WalletWasabi.Fluent/Controls/Spectrum/SpectrumDrawHandler.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Coins/CoinListViewModel.cs
Labels: size/S

#13075 Cleanup `IndexBuilderService`
  WalletWasabi.Backend/Global.cs
  WalletWasabi.Daemon/Global.cs
  WalletWasabi.Fluent/Models/Wallets/WalletLoadWorkflow.cs
  WalletWasabi.Tests/RegressionTests/BackendTests.cs
  WalletWasabi.Tests/UnitTests/BitcoinCore/IndexBuilderServiceTests.cs
  WalletWasabi.Tests/UnitTests/SmartHeaderTests.cs
  WalletWasabi/Blockchain/BlockFilters/IndexBuilderService.cs
  WalletWasabi/Blockchain/BlockFilters/IndexType.cs
  WalletWasabi/Blockchain/BlockFilters/IndexTypeConverter.cs
  WalletWasabi/Blockchain/BlockFilters/StartingFilters.cs
  WalletWasabi/Blockchain/Blocks/SmartHeader.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/L

#13071 Fix or remove some IntegrationsTests
  WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
  WalletWasabi.Tests/IntegrationTests/P2pTests.cs
  WalletWasabi.Tests/IntegrationTests/ShopWareApiClientTests.cs
Labels: size/L

#13070 Fix path in RegTestFixture
  WalletWasabi.Tests/XunitConfiguration/RegTestFixture.cs
Labels: size/XS

#13074 [Tor] Fix changing Tor modes in the UI settings
  WalletWasabi.Daemon/Config.cs
  WalletWasabi.Daemon/PersistentConfig.cs
  WalletWasabi.Fluent/Models/UI/ApplicationSettings.cs
Labels: size/M

#13068 Fix infinite await in `FetchTransactionsAsync` in case of missing txs (take 2)
  WalletWasabi.Backend/Controllers/BlockchainController.cs
Labels: size/M

#13083 Remove test-only API Client `mempool-hashes`
  WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
  WalletWasabi/WebClients/Wasabi/WasabiClient.cs
Labels: size/S

#13086 Allow to run multiple backend instances
  WalletWasabi.Backend/Controllers/WabiSabiController.cs
  WalletWasabi.Backend/Controllers/WalletController.cs
  WalletWasabi.Backend/Program.cs
  WalletWasabi.Backend/Properties/launchSettings.json
  WalletWasabi/Helpers/Constants.cs
  WalletWasabi/WabiSabi/Client/WabiSabiHttpApiClient.cs
  WalletWasabi/WebClients/Wasabi/WasabiClient.cs
Labels: size/S

#13088 [Config] Fix behavior
  WalletWasabi.Fluent/Models/UI/ApplicationSettings.cs
  WalletWasabi.Fluent/ViewModels/Settings/BitcoinTabSettingsViewModel.cs
Labels: size/XS

#13089 [Tor] Fix changing Tor modes in the UI settings (FOSS port)
  WalletWasabi.Daemon/Config.cs
  WalletWasabi.Daemon/PersistentConfig.cs
  WalletWasabi.Fluent/Models/UI/ApplicationSettings.cs
Labels: size/M

#13087 Explicitly split CoordinatorUri and BackendUri
  WalletWasabi.Daemon/Config.cs
  WalletWasabi.Daemon/PersistentConfig.cs
  WalletWasabi.Tests/UnitTests/Bases/ConfigManagerNgTests.cs
Labels: size/S

#13090 [UI] Settings - Coordinator URI
  WalletWasabi.Daemon/PersistentConfig.cs
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/Models/UI/ApplicationSettings.cs
  WalletWasabi.Fluent/Models/UI/UiContext.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/BitcoinTabSettingsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi.Fluent/Views/Settings/BitcoinTabSettingsView.axaml
  WalletWasabi.Fluent/Views/Wallets/MusicControlsView.axaml
  WalletWasabi.Tests/UnitTests/ViewModels/UiContext/NullApplicationSettings.cs
Labels: size/L

#13084 [UI] Coordinator stopped announcement dialog
  WalletWasabi.Fluent/Models/UI/ApplicationSettings.cs
  WalletWasabi.Fluent/UiConfig.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/Announcement/AnnouncementBase.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/Announcement/ZkSnacksCoordinatorAnnouncementViewModel.cs
  WalletWasabi.Fluent/ViewModels/MainViewModel.cs
  WalletWasabi.Fluent/ViewModels/Settings/SettingsPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi.Fluent/Views/Dialogs/Announcement/ZkSnacksCoordinatorAnnouncementView.axaml
  WalletWasabi.Fluent/Views/Dialogs/Announcement/ZkSnacksCoordinatorAnnouncementView.axaml.cs
  WalletWasabi.Tests/UnitTests/ViewModels/UiContext/NullApplicationSettings.cs
Labels: size/L

#13085 Split BackendCompatible and the Update flow
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/Models/HealthMonitorState.cs
  WalletWasabi.Fluent/Models/Wallets/HealthMonitor.cs
  WalletWasabi.Fluent/ViewModels/StatusIcon/StatusIconViewModel.cs
  WalletWasabi.Fluent/Views/StatusIcon/StatusIcon.axaml
  WalletWasabi.Tests/RegressionTests/BackendTests.cs
  WalletWasabi/Services/UpdateManager.cs
  WalletWasabi/Services/WasabiSynchronizer.cs
  WalletWasabi/WebClients/Wasabi/WasabiClient.cs
Labels: size/S

#13103 Removes `mempool-hashes`
  WalletWasabi.Backend/Controllers/WalletController.cs
  WalletWasabi.Daemon/Config.cs
  WalletWasabi.Daemon/PersistentConfig.cs
  WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
  WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
  WalletWasabi/Blockchain/Mempool/MempoolService.cs
  WalletWasabi/Cache/MemoryCache.cs
  WalletWasabi/Models/ServiceConfiguration.cs
  WalletWasabi/Wallets/Wallet.cs
  WalletWasabi/WebClients/Wasabi/WasabiClient.cs
Labels: Resiliency, Downsize
