Repository WalletWasabi/WalletWasabi, pull requests merged in 2024-02, with the labels that each got.

#11586 Split `JsonRpcResponse` is success and error
  WalletWasabi/Rpc/JsonRpcRequestHandler.cs
  WalletWasabi/Rpc/JsonRpcResponse.cs
Labels: size/M

#12289 Knots version fixing and document update
  WalletWasabi.Documentation/WasabiSetupRegtest.md
Labels: size/M

#12312 [VDG] Close the Success dialog automatically
  WalletWasabi.Fluent/UiConstants.cs
  WalletWasabi.Fluent/ViewModels/AddWallet/AddedWalletPageViewModel.cs
  WalletWasabi.Fluent/ViewModels/SuccessViewModel.cs
  WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/BroadcastTransactionViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendSuccessViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/VerifyRecoveryWordsViewModel.cs
  WalletWasabi.Fluent/Views/AddWallet/AddedWalletPageView.axaml
  WalletWasabi.Fluent/Views/SuccessAnimationView.axaml
  WalletWasabi.Fluent/Views/SuccessAnimationView.axaml.cs
  WalletWasabi.Fluent/Views/SuccessView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/SendSuccessView.axaml
Labels: size/L

#12338 Ensure only valid decompositions
  WalletWasabi/WabiSabi/Client/OutputProvider.cs
Labels: size/XS

#12293 [Trivial] Simplify member access
  WalletWasabi.Backend/Controllers/WabiSabiController.cs
  WalletWasabi.Fluent/Helpers/FlyoutHelpers.cs
  WalletWasabi.Fluent/Models/Wallets/WalletRepository.cs
  WalletWasabi.Tests/RegressionTests/SendTests.cs
  WalletWasabi.Tests/RegressionTests/SpendUnconfirmedTxTests.cs
Labels: size/S

#12349 [UI] fix cancel icon
  WalletWasabi.Fluent/Models/Wallets/TransactionTreeBuilder.cs
Labels: size/XS

#12355 Fix crash when opening send
  WalletWasabi.Fluent/Helpers/FlyoutHelpers.cs
Labels: size/XS

#12353 [VDG] Encapsulate clipboard access in ApplicationHelper and make sure always run on main UI thread
  WalletWasabi.Fluent/Behaviors/PasteButtonFlashBehavior.cs
  WalletWasabi.Fluent/Controls/ClipboardCopyButton.axaml.cs
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
  WalletWasabi.Fluent/CrashReport/ViewModels/CrashReportWindowViewModel.cs
  WalletWasabi.Fluent/Helpers/ApplicationHelper.cs
  WalletWasabi.Fluent/Models/UI/UiClipboard.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
Labels: size/L

#12337 Fixing large transaction inputs timeout
  WalletWasabi.Fluent/Models/Wallets/HardwareWalletModel.cs
Labels: size/S

#12335 Update CONTRIBUTING.md - add rule for unused return values
  CONTRIBUTING.md
Labels: size/S

#12319 Update SECURITY.md from nopara to molnard
  SECURITY.md
Labels: size/L

#12336 Remove unnecessary _ = from the code
  WalletWasabi.Fluent/Behaviors/HistoryItemTypeClassBehavior.cs
  WalletWasabi.Tests/RegressionTests/CoinVerifierApiClientStressTests.cs
  WalletWasabi.Tests/RegressionTests/IdempotencyRequestCacheStressTests.cs
  WalletWasabi.Tests/UnitTests/Blockchain/TransactionBuilding/BranchAndBoundTests.cs
  WalletWasabi.Tests/UnitTests/Blockchain/TransactionOutputs/CoinsRegistryTests.cs
  WalletWasabi.Tests/UnitTests/JsonConverters/ByteArrayJsonConverterTests.cs
  WalletWasabi.Tests/UnitTests/Tor/Control/TorControlClientTests.cs
  WalletWasabi.Tests/UnitTests/Tor/Control/Utils/AsyncEventParserTests.cs
  WalletWasabi.Tests/UnitTests/Tor/Socks5/Pool/TorHttpPoolTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/CoinJoinCoinSelectionTests.cs
  WalletWasabi.Tests/UnitTests/Wallet/FilterProcessor/BlockFilterIteratorTests.cs
  WalletWasabi.Tests/UnitTests/WalletDirTests.cs
  WalletWasabi.Tests/UnitTests/Wallets/SpecificNodeBlockProviderTests.cs
  WalletWasabi/BitcoinCore/Mempool/Mempool.cs
  WalletWasabi/Blockchain/Transactions/AllTransactionStore.cs
  WalletWasabi/Blockchain/Transactions/TransactionStore.cs
  WalletWasabi/Helpers/IoHelpers.cs
  WalletWasabi/Stores/BlockFilterSqliteStorage.cs
  WalletWasabi/Tor/Control/Messages/Events/StatusEvents/BootstrapStatusEvent.cs
  WalletWasabi/Tor/Control/TorControlClient.cs
  WalletWasabi/Tor/TorMonitor.cs
  WalletWasabi/Userfacing/CurrencyInput.cs
  WalletWasabi/WabiSabi/Backend/Banning/CoinVerifier.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
  WalletWasabi/Wallets/SpecificNodeBlockProvider.cs
  WalletWasabi/Wallets/WalletFilterProcessor.cs
Labels: size/L

#12356 Apply time preference check for all lower TimeFrames
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/IsRoundEconomicTests.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/M

#12374 Copy USD Balance to ToUsdFriendlyDecimals
  WalletWasabi.Fluent/Converters/MoneyConverters.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceTileView.axaml
Labels: size/XS

#12376 Add new HWs icon to WW
  WalletWasabi.Fluent/Assets/WalletIcons/Dark/bitbox.png
  WalletWasabi.Fluent/Assets/WalletIcons/Dark/jade.png
  WalletWasabi.Fluent/Assets/WalletIcons/Light/bitbox.png
  WalletWasabi.Fluent/Assets/WalletIcons/Light/jade.png
  WalletWasabi.Fluent/Converters/WalletIconConverter.cs
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/ViewModels/Wallets/WalletPageViewModel.cs
Labels: size/S

#12380 [UI] CurrencyEntryBox - hotfix for release
  WalletWasabi.Fluent/Behaviors/FlyoutSuggestionBehavior.cs
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
  WalletWasabi.Fluent/Controls/DualCurrencyEntryBox.axaml.cs
Labels: size/L

#12383 [VDG] Do not call NavigateAndHighlight if selected wallet is the same as found one
  WalletWasabi.Fluent/ViewModels/SearchBar/Sources/TransactionsSearchSource.cs
Labels: size/S

#12389 [Release] fix USD amount copy
  WalletWasabi.Fluent/Converters/MoneyConverters.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceTileView.axaml
Labels: size/XS

#12384 [Release] Fix CurrencyEntryBox
  WalletWasabi.Fluent/Behaviors/FlyoutSuggestionBehavior.cs
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
  WalletWasabi.Fluent/Controls/DualCurrencyEntryBox.axaml.cs
Labels: size/L

#12388 [Release] Fix history after txn search
  WalletWasabi.Fluent/ViewModels/SearchBar/Sources/TransactionsSearchSource.cs
Labels: size/S

#12252 musicbox: update RandomlySkippedRoundMessage
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
Labels: size/XS

#12394 Hwi icons align fix
  WalletWasabi.Fluent/Assets/WalletIcons/Dark/bitbox.png
  WalletWasabi.Fluent/Assets/WalletIcons/Dark/jade.png
  WalletWasabi.Fluent/Assets/WalletIcons/Light/bitbox.png
  WalletWasabi.Fluent/Assets/WalletIcons/Light/jade.png
  WalletWasabi.Fluent/Converters/WalletIconConverter.cs
  WalletWasabi.Fluent/Icons/Icons.axaml
  WalletWasabi.Fluent/ViewModels/Wallets/WalletPageViewModel.cs
  WalletWasabi/Wallets/WalletType.cs
Labels: size/S

#12396 Hw icons finalize
  WalletWasabi.Fluent/Icons/Icons.axaml
Labels: size/XS

#12393 [2.0.6 release] musicbox: update RandomlySkippedRoundMessage
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
Labels: size/XS

#12392 update avalonia
  Directory.Packages.props
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/App.axaml
  WalletWasabi.Fluent/ViewModels/ApplicationViewModel.cs
  WalletWasabi.Fluent/packages.lock.json
Labels: size/L

#12402 Code cleanup
  WalletWasabi.Fluent/Behaviors/FocusControlActionCustom.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/BuyViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/OrderViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/WorkflowStep.cs
  WalletWasabi.Tests/IntegrationTests/ShopWareApiClientTests.cs
  WalletWasabi.Tests/UnitTests/BuyAnything/BuyAnythingSerializationTests.cs
  WalletWasabi.Tests/UnitTests/ViewModels/UiContext/NullApplicationSettings.cs
  WalletWasabi/BuyAnything/BuyAnythingManager.cs
  WalletWasabi/BuyAnything/ConversationExtensions.cs
  WalletWasabi/BuyAnything/ConversationUpdateTrack.cs
  WalletWasabi/WebClients/BuyAnything/BuyAnythingClient.cs
Labels: size/M

#12409 [UI] Fix duplicate orders
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/BuyViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
Labels: size/S

#12398 [Release] Avalonia update
  Directory.Packages.props
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/App.axaml
  WalletWasabi.Fluent/ViewModels/ApplicationViewModel.cs
  WalletWasabi.Fluent/packages.lock.json
Labels: size/L

#12414 [Release] Fix duplicate orders
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/BuyViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
Labels: size/S

#12420 [UI][Trivial] Change BAB's position
  WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
Labels: UI, size/S

#12421 Privacy Ring - AnonScore Range for PrivacyLevel Segments
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyRing/PrivacyRingItemDetailsView.axaml
Labels: size/S

#12406 [UI] Chat workflow better error handling
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/OrderViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/1_Initial/StartConversationStep.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/2_Delivery/AcceptOfferStep.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/2_Delivery/SaveConversationStep.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/4_Finished/OrderFinishedMessage.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/ShopinBitWorkflow.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/Workflow.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/WorkflowStep.cs
Labels: size/L

#12413 Move NewFiltersEvent registration after Initial Tx Process
  WalletWasabi.Tests/UnitTests/Wallet/WalletFilterProcessorTests.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/S

#12425 [Release] PrivacyRing - Fix anonscore when display pockets
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingItemViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyRing/PrivacyRingItemDetailsView.axaml
Labels: size/S

#12416 Fix CrashReporter window - Continuation
  WalletWasabi.Fluent/CrashReport/CrashReporter.cs
  WalletWasabi/Microservices/ProcessStartInfoFactory.cs
Labels: size/S

#12426 [Release] BAB - Fix error handling
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/OrderViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/1_Initial/StartConversationStep.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/2_Delivery/AcceptOfferStep.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/2_Delivery/SaveConversationStep.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/4_Finished/OrderFinishedMessage.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/ShopinBitWorkflow.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/Workflow.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/WorkflowStep.cs
Labels: size/L

#12431 [Release] Move NewFiltersEvent registration after Initial Tx Process
  WalletWasabi.Tests/UnitTests/Wallet/WalletFilterProcessorTests.cs
  WalletWasabi/Wallets/Wallet.cs
Labels: size/S

#12432 [Release] Fix CrashReporter window - Continuation
  WalletWasabi.Fluent/CrashReport/CrashReporter.cs
  WalletWasabi/Microservices/ProcessStartInfoFactory.cs
Labels: size/S

#12428 Disable SleepInhibitor in Daemon
  WalletWasabi.Daemon/Global.cs
  WalletWasabi.Daemon/WasabiAppBuilder.cs
  WalletWasabi.Fluent.Desktop/Program.cs
Labels: size/M

#12433 [UI] BAB - Error dialog improvement
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/BuyViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/IOrderManager.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/OrderViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/Workflow.cs
Labels: size/S

#12436 [UI] Update spectrum control bounds
  WalletWasabi.Fluent/Controls/Rendering/DrawCompositionCustomVisualHandler.cs
  WalletWasabi.Fluent/Controls/Spectrum/SpectrumControl.cs
Labels: size/XS

#12438 [Release] Fix CJ aura
  WalletWasabi.Fluent/Controls/Rendering/DrawCompositionCustomVisualHandler.cs
  WalletWasabi.Fluent/Controls/Spectrum/SpectrumControl.cs
Labels: size/XS

#12410 [UI] fix BuyAnything button visibility
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/BuyViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
Labels: size/S

#12435 [Release] BuyAnything - error dialog adjustment
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/BuyViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/IOrderManager.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/OrderViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/Workflow.cs
Labels: size/S

#12440 [VDG] Fix discreet mode hover not working for Bitcoin P2P endpoint
  WalletWasabi.Fluent/Views/Settings/BitcoinTabSettingsView.axaml
Labels: size/XS

#12441 [Release] Fix BuyAnything button visibility
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/BuyViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
Labels: size/S

#12448 [Release] discreet mode fix
  WalletWasabi.Fluent/Views/Settings/BitcoinTabSettingsView.axaml
Labels: size/XS

#12439 [UI] Fix wrong unread badge
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/BuyViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/OrderViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/Workflow.cs
Labels: size/M

#12454 [Release] fix unread badge
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/BuyViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/OrderViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/Workflow.cs
Labels: size/M

#12455 [BAB] Adjust minimum amount wording
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/1_Initial/CountryStep.cs
Labels: size/XS

#12453 [UI] Add char limit
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/1_Initial/RequestedItemStep.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/WorkflowStep.cs
  WalletWasabi.Fluent/Views/Wallets/Buy/UserInputValidatorView.axaml
Labels: size/M

#12452 [BaB] Remove timestamp from UI message
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Messages/AssistantMessageViewModel.cs
Labels: size/S

#12457 [Release] BAB - char limit
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/1_Initial/RequestedItemStep.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/WorkflowStep.cs
  WalletWasabi.Fluent/Views/Wallets/Buy/UserInputValidatorView.axaml
Labels: size/M

#12459 Adjust bab visibility
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
Labels: size/S

#12460 [Release] Remove timestamp from UI message
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Messages/AssistantMessageViewModel.cs
Labels: size/S

#12462 [BAB] [trivial] update assistant greeting, remove "chosen"
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/1_Initial/CountryStep.cs
Labels: size/XS

#12463 [2.0.6 release] BAB: update assistant greeting text
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/1_Initial/CountryStep.cs
Labels: size/XS

#12437 Disable Taproot KeyPath under HW first connection
  WalletWasabi/Helpers/HardwareWalletOperationHelpers.cs
Labels: size/XS

#12469 [UI] PasswordFinder - add missing navtaget
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/PasswordFinderIntroduceViewModel.cs
Labels: size/XS

#12470 [Release] add missing navtaget
  WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/PasswordFinderIntroduceViewModel.cs
Labels: size/XS

#12468 [VDG] Use RoutingStrategies.Bubble for pointer event for closing dialog
  WalletWasabi.Fluent/Controls/Dialog.axaml.cs
Labels: size/XS

#12471 [Release] fix pointer event
  WalletWasabi.Fluent/Controls/Dialog.axaml.cs
Labels: size/XS

#12472 [UI] BAB - improve UX of min char limit
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/1_Initial/RequestedItemStep.cs
  WalletWasabi.Fluent/Views/Wallets/Buy/UserInputValidatorView.axaml
Labels: size/M

#12473 [Release] bab min char ux
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/1_Initial/RequestedItemStep.cs
  WalletWasabi.Fluent/Views/Wallets/Buy/UserInputValidatorView.axaml
Labels: size/M

#12417 Fix PayJoin
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi/Userfacing/Bip21/Bip21UriParser.cs
Labels: size/XS

#12466 Disable Taproot KeyPath under HW first connection
  WalletWasabi/Helpers/HardwareWalletOperationHelpers.cs
Labels: size/XS

#12450 Catch wrong phase exception in CJManager in case of detected double spend
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Labels: size/XS

#12475 [Release] Fix PayJoin
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
  WalletWasabi/Userfacing/Bip21/Bip21UriParser.cs
Labels: size/XS

#12476 [Release] Catch wrong phase exception in CJManager in case of detected double spend
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Labels: size/XS

#12478 [BIP21 parser] Add tests for unknown parameters
  WalletWasabi.Tests/UnitTests/Userfacing/Bip21/Bip21UriParserTests.cs
Labels: size/S

#12480 [trivial] `Program.cs`: Fix wrong use of `?`
  WalletWasabi.Fluent.Desktop/Program.cs
Labels: size/XS

#12456 [BaB] Fix shipping cost not showing
  WalletWasabi/BuyAnything/BuyAnythingManager.cs
  WalletWasabi/WebClients/ShopWare/Models/Order.cs
Labels: size/S

#12491 [Release] Fix shipping cost not showing
  WalletWasabi/BuyAnything/BuyAnythingManager.cs
  WalletWasabi/WebClients/ShopWare/Models/Order.cs
Labels: size/S

#12487 [Release] Time preference lower time frames
  WalletWasabi.Tests/UnitTests/WabiSabi/Client/IsRoundEconomicTests.cs
  WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Labels: size/M

#12489 Disable SleepInhibitor in Daemon
  WalletWasabi.Daemon/Global.cs
  WalletWasabi.Daemon/WasabiAppBuilder.cs
  WalletWasabi.Fluent.Desktop/Program.cs
Labels: size/M

#12483 [VDG] fix welcome page inaccuracies
  WalletWasabi.Fluent/Views/AddWallet/WelcomePageView.axaml
Labels: size/S

#12496 [release_v2.0.6] fix welcome page inaccuracies
  WalletWasabi.Fluent/Views/AddWallet/WelcomePageView.axaml
Labels: size/S

#12498 [Release] fix opening browser on macos
  WalletWasabi/Helpers/IoHelpers.cs
Labels: size/S

#12458 [UI][BAB] Remove assistant's explanation
  WalletWasabi.Fluent/Converters/TextToInlineCollectionConverter.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/1_Initial/WelcomeStep.cs
  WalletWasabi.Fluent/Views/Wallets/Buy/OrderMessagesView.axaml
Labels: size/L

#12503 [Release] BAB explanation link
  WalletWasabi.Fluent/Converters/TextToInlineCollectionConverter.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/1_Initial/WelcomeStep.cs
  WalletWasabi.Fluent/Views/Wallets/Buy/OrderMessagesView.axaml
Labels: size/L

#12507 do not use inlines, its buggy.
  WalletWasabi.Fluent/Views/Wallets/MusicControlsView.axaml
Labels: size/XS

#12508 [Release] Remove usuage of inlines completely
  WalletWasabi.Fluent/Views/Wallets/MusicControlsView.axaml
Labels: size/XS

#12506 [Release] Fix Linux popup and flyout issues 2
  Directory.Build.props
  Directory.Packages.props
  NuGet.Config
  WalletWasabi.Fluent.Desktop/packages.lock.json
  WalletWasabi.Fluent/ApplicationStateManager.cs
  WalletWasabi.Fluent/packages.lock.json
Labels: size/L

#12493 [VDG] ContentArea Improvements
  WalletWasabi.Fluent/Controls/ContentArea.axaml
  WalletWasabi.Fluent/Controls/ContentArea.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml
  WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
Labels: size/L

#12370 Remove temporary resync code
  WalletWasabi.Daemon/Global.cs
  WalletWasabi/Blockchain/Transactions/TransactionStore.cs
  WalletWasabi/Wallets/WalletManager.cs
Labels: size/M

#12502 Fix "StopWhenAllMixed = false doesn't work"
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Labels: size/XS

#12513 [Release] Fix StopWhenAllMixed = false
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Labels: size/XS

#12510 [VDG] Fix TreeDataGridPrivacyTextCell rendering
  WalletWasabi.Fluent/TreeDataGrid/TreeDataGridPrivacyTextCell.cs
Labels: size/M

#12512 [Trivial] Remove useless check in CoinJoinCoinSelector
  WalletWasabi/WabiSabi/Client/CoinJoinCoinSelector.cs
Labels: size/S

#12517 [Release] fix privacy cell discreet mode
  WalletWasabi.Fluent/TreeDataGrid/TreeDataGridPrivacyTextCell.cs
Labels: size/M

#12519 Fix WFP crash when network changes
  WalletWasabi/Wallets/Wallet.cs
Labels: size/XS

#12522 Fix crash when countries cannot be retrieved.
  WalletWasabi/BuyAnything/BuyAnythingManager.cs
Labels: size/XS

#12531 [Release] Fix crash when countries cannot be retrieved.
  WalletWasabi/BuyAnything/BuyAnythingManager.cs
Labels: size/XS

#12521 [Release] Add missing BitBox implementation?
  WalletWasabi.Documentation/WasabiCompatibility.md
  WalletWasabi.Tests/AcceptanceTests/HwiKatas.cs
  WalletWasabi.Tests/Helpers/HwiValidationHelper.cs
  WalletWasabi.Tests/UnitTests/Hwi/HwiProcessBridgeMock.cs
  WalletWasabi.Tests/UnitTests/Hwi/MockedDeviceTests.cs
  WalletWasabi/Hwi/Models/HwiEnumerateEntry.cs
Labels: size/L

#12504 Simplify synchronizer gensock event reporting
  WalletWasabi.Fluent/Models/Wallets/HealthMonitor.cs
  WalletWasabi/Services/WasabiSynchronizer.cs
Labels: size/M

#12532 [Release] Simplify synchronizer gensock event reporting
  WalletWasabi.Fluent/Models/Wallets/HealthMonitor.cs
  WalletWasabi/Services/WasabiSynchronizer.cs
Labels: size/M

#12538 CompletedEventArgs was not forwarded in the the observable chain
  WalletWasabi.Fluent/Models/Wallets/WalletCoinjoinModel.cs
Labels: size/XS

#12544 [Release] SendViewModel: Make AmountBtc nullable
  WalletWasabi.Fluent/Controls/DualCurrencyEntryBox.axaml.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
Labels: size/M

#12545 [Release] paste amount selection fix
  WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
Labels: size/XS

#12546 [Release] fix aura on CJ completed
  WalletWasabi.Fluent/Models/Wallets/WalletCoinjoinModel.cs
Labels: size/XS

#12541 [VDG] Privacy Ring - Remove Carousel
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingViewModel.cs
  WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyRing/PrivacyRingView.axaml
Labels: size/M

#12543 [VDG] Fix errors in ide
  WalletWasabi.Fluent/Controls/PreviewMessageItem.axaml.cs
  WalletWasabi.Fluent/Views/Wallets/Buy/UserInputValidatorView.axaml
Labels: size/XS

#12550 [Trivial] Update ReleaseNotesTemplate.md
  WalletWasabi.Documentation/ClientRelease/ReleaseNotesTemplate.md
Labels: size/XS

#12554 Revert "Fix "StopWhenAllMixed = false doesn't work""
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Labels: priority, size/XS

#12555 [Release] Revert "Fix "StopWhenAllMixed = false doesn't work""
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Labels: size/XS

#12553 Add missing state machine transition when wallet reached 100% - take 2
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Labels: priority, size/M

#12556 [Release] Add missing state machine transition when wallet reached 100% - take 2
  WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Labels: size/M, size/XXL

#12563 [VDG] Fix send To address field scrolling
  WalletWasabi.Fluent/Controls/TextBox.axaml
  WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Labels: size/XS

#12565 [Release] Bump version to v2.0.6
  WalletWasabi/Helpers/Constants.cs
Labels: size/XS

#12558 Ignore visual studio launchSettings.json
  .gitignore
Labels: size/XS

#12559 Don't mix if all non-private coins are unconfirmed.
  WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Labels: size/XS

#12566 BAB - fix visibility on testnet
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
Labels: size/XS

#12567 fix visibility on testnet
  WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
Labels: size/XS

#12524 Introduce MinInputCountByBlameRound - simple
  WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
  WalletWasabi.Tests/UnitTests/Bases/ConfigManagerTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepInputRegistrationTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
  WalletWasabi.Tests/UnitTests/WabiSabi/Backend/Rounds/MultipartyTransactionStateTests.cs
  WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
  WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
Labels: size/M

#12573 [VDG] WalletCoinsModel - Deferred Subscription
  WalletWasabi.Fluent/Models/Wallets/CoinModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/LabelEntryDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingViewModel.cs
Labels: size/M

#12576 [Release] Fix coin model leak
  WalletWasabi.Fluent/Models/Wallets/CoinModel.cs
  WalletWasabi.Fluent/ViewModels/Dialogs/LabelEntryDialogViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyBarViewModel.cs
  WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingViewModel.cs
Labels: size/M
